update(JS): web/javascript/reference/global_objects/array/every
webdoky/content pull request #1017
Opened 2022-11-27 21:17 UTC by undead404

Оригінальний вміст: [Array.prototype.every()@MDN](https://developer.mozilla.org/en-us/docs/Web/JavaScript/Reference/Global_Objects/Array/every), [сирці Array.prototype.every()@GitHub](https://github.com/mdn/content/blob/main/files/en-us/web/javascript/reference/global_objects/array/every/index.md)

Нові зміни:
- [mdn/content@1605e24](https://github.com/mdn/content/commit/1605e24b23ae34ea6c0cf0621c61852789f29a65)
- [mdn/content@cca000c](https://github.com/mdn/content/commit/cca000c28ef661e58a5beaff9c64f7a397a5f68a)

2022-11-30 23:00 UTC, AdriandeCita commented on files/uk/web/javascript/reference/global_objects/array/every/index.md
> +- Коли наявний, ще не оброблений елемент масиву змінює `callbackFn`, то значення такого елемента, передане в `callbackFn`, буде значенням, актуальним на ту мить, коли цей елемент обробляється. [Видал
елемент не повинен змінювати функцію.
```suggestion
- Коли наявний, ще не оброблений елемент масиву змінюється функцією `callbackFn`, то значення такого елемента, передане в `callbackFn`, буде значенням, актуальним на ту мить, коли цей елемент обробляється. [Видалені](/uk/docs/Web/JavaScript/Reference/Operators/delete) елементи – не обробляються.
```

2022-11-30 23:00 UTC, AdriandeCita requested changes
Одне зауваження

2022-12-01 08:38 UTC, undead404 commented
Прийнято

2022-12-01 23:07 UTC, AdriandeCita approved these changes

2022-12-01 23:07 UTC, merged