translation(CSS): web/css/transform-function/rotate
webdoky/content pull request #1022
Opened 2022-11-28 11:46 UTC by undead404

Оригінальний вміст: [rotate()@MDN](https://developer.mozilla.org/en-us/docs/Web/CSS/transform-function/rotate), [сирці rotate()@GitHub](https://github.com/mdn/content/blob/main/files/en-us/web/css/transform-function/rotate/index.md)

2022-12-09 21:21 UTC, AdriandeCita commented on files/uk/web/css/transform-function/rotate/index.md
> +Кількість обертання, спричиненого `rotate()`, задається у вигляді {{cssxref("&lt;angle&gt;", "кута")}}. Якщо кут додатний, то обертання відбувається за годинниковою стрілкою, а якщо від'ємний, то про
```suggestion
Величина обертання, спричиненого `rotate()`, задається у вигляді {{cssxref("&lt;angle&gt;", "кута")}}. Якщо кут додатний, то обертання відбувається за годинниковою стрілкою, а якщо від'ємний, то проти. Обертання на 180° зветься _центральною симетрією_.
```

2022-12-09 21:37 UTC, AdriandeCita commented on files/uk/web/css/transform-function/rotate/index.md
> +Коли хочеться застосувати до елемента декілька перетворень, слід поводитись обережно з порядком задання таких перетворень. Наприклад, якщо обернути до перекладу, то переклад відбудеться за новою вісс
"Translate" також цілком легітимно перекладається як "перенести" чи "перемістити", тож пропоную не ускладнювати собі і читачам життя)
Також у мене підозра, що в оригіналі хтось наплужив, бо вісь, навколо якої обертається елемент, лежить перпендикулярно до будь-якого можливого напрямку зміщення... Але я зараз не маю ніякого настрою описувати це зараз англійською :slightly_smiling_face: 
```suggestion
Коли хочеться застосувати до елемента декілька перетворень, слід поводитись обережно з порядком задання таких перетворень. Наприклад, якщо перед переміщенням обернути елемент, то переміщення відбудеться вздовж нової осі обертання!
```

2022-12-09 21:38 UTC, AdriandeCita commented on files/uk/web/css/transform-function/rotate/index.md
> +<div class="rotate-translate">Обернений + Перекладений</div>
```suggestion
<div class="rotate-translate">Обернений + Переміщений</div>
```

2022-12-09 21:38 UTC, AdriandeCita commented on files/uk/web/css/transform-function/rotate/index.md
> +<div class="translate-rotate">Перекладений + Обернений</div>
```suggestion
<div class="translate-rotate">Переміщений + Обернений</div>
```

2022-12-09 21:39 UTC, AdriandeCita requested changes
Декілька зауважень, зокрема стосовно термінології

2022-12-13 12:17 UTC, undead404 commented on files/uk/web/css/transform-function/rotate/index.md
> +<div class="rotate-translate">Обернений + Перекладений</div>
Не згодний: translate це "перекласти", а не "перемістити"

2022-12-13 12:17 UTC, undead404 commented on files/uk/web/css/transform-function/rotate/index.md
> +<div class="translate-rotate">Перекладений + Обернений</div>
Same here

2022-12-13 12:30 UTC, AdriandeCita commented on files/uk/web/css/transform-function/rotate/index.md
> +<div class="rotate-translate">Обернений + Перекладений</div>
Translate має декілька варіантів перекладу. В цьому випадку, оскільки відбувається саме переміщення елемента, доцільніше використовувати відповідний варіант перекладу.

![image](https://user-images.githubusercontent.com/11510394/207318405-64e5f309-4b0e-40e8-946b-2653f69d055c.png)

2022-12-13 13:30 UTC, undead404 commented on files/uk/web/css/transform-function/rotate/index.md
> +<div class="rotate-translate">Обернений + Перекладений</div>
Давай тоді перенесення, щоб звучало менш загально

2022-12-13 14:17 UTC, KlashReik commented on files/uk/web/css/transform-function/rotate/index.md
> +Коли хочеться застосувати до елемента декілька перетворень, слід поводитись обережно з порядком задання таких перетворень. Наприклад, якщо обернути до перекладу, то переклад відбудеться за новою вісс
Я більше схиляюся до варіанти Миколи. Як на мене, 2 варіант може спантеличити користувача.

2022-12-13 14:20 UTC, KlashReik commented on files/uk/web/css/transform-function/rotate/index.md
> +<div class="rotate-translate">Обернений + Перекладений</div>
Мені до вподоби "переміщений". Хочу наголосити на тому, що варто перекладати слово "translate" і у описі, і у самому прикладі однаково.

2022-12-13 14:26 UTC, AdriandeCita commented on files/uk/web/css/transform-function/rotate/index.md
> +Коли хочеться застосувати до елемента декілька перетворень, слід поводитись обережно з порядком задання таких перетворень. Наприклад, якщо обернути до перекладу, то переклад відбудеться за новою вісс
Оновив зміну
```suggestion
Коли хочеться застосувати до елемента декілька перетворень, слід поводитись обережно з порядком задання таких перетворень. Наприклад, якщо перед перенесенням обернути елемент, то перенесення відбудеться вздовж нової осі обертання!
```

2022-12-13 14:26 UTC, AdriandeCita commented on files/uk/web/css/transform-function/rotate/index.md
> +<div class="rotate-translate">Обернений + Перекладений</div>
Оновив
```suggestion
<div class="rotate-translate">Обернений + Перенесений</div>
```

2022-12-13 14:26 UTC, AdriandeCita commented on files/uk/web/css/transform-function/rotate/index.md
> +<div class="translate-rotate">Перекладений + Обернений</div>
Оновив
```suggestion
<div class="translate-rotate">Перенесений + Обернений</div>
```

2022-12-18 12:02 UTC, undead404 commented
Прийняв пропозиції

2022-12-18 12:03 UTC, undead404 commented
Розв'язав конфлікт

2022-12-25 14:59 UTC, AdriandeCita approved these changes

2022-12-25 14:59 UTC, merged