update(JS): web/javascript/reference/operators
webdoky/content pull request #1027
Opened 2022-11-29 12:37 UTC by undead404

Оригінальний вміст: [Вирази та оператори@MDN](https://developer.mozilla.org/en-us/docs/Web/JavaScript/Reference/Operators), [сирці Вирази та оператори@GitHub](https://github.com/mdn/content/blob/main/files/en-us/web/javascript/reference/operators/index.md)

Нові зміни:
- [mdn/content@313ad4f](https://github.com/mdn/content/commit/313ad4f907d58b7a5d8b68a7d4f45648b178f600)

2022-11-30 23:36 UTC, AdriandeCita commented on files/uk/web/javascript/reference/operators/index.md
> +  - : Базові літерали `null`, булевих значень, чисел та рядків.
```suggestion
  - : Базові літерали `null`, булевих значень, чисел та рядків.
- {{JSxRef("Global_Objects/Array", "[]")}}
```

2022-11-30 23:37 UTC, AdriandeCita commented on files/uk/web/javascript/reference/operators/index.md
> +  - : Array initializer/literal syntax.
```suggestion
  - : Синтаксис ініціалізаторів масивів – літералів.
```

2022-11-30 23:55 UTC, AdriandeCita commented on files/uk/web/javascript/reference/operators/index.md
> +  - : Оператори деталей надають доступ до властивостей чи методів об'єкта (`object.property` і `object["property"]`)
Згоден, "оператори доступу ... надають доступ" звучало так собі. І ні, не згоден з "деталями". Сенс додавати нове тлумачення, якщо термін "член" в подібному контексті вже довгий час активно використовується в математиці. Ну чи ось https://uk.wikipedia.org/wiki/%D0%9E%D0%BF%D0%B5%D1%80%D0%B0%D1%82%D0%BE%D1%80%D0%B8_%D0%B2_C_%D1%82%D0%B0_C%2B%2B тут наприклад повна сторінка членів :grin: 
Також переведення "властивостей та методів" у множину імхо немає суттєвого сенсу. В оригіналі однина, та й несхоже, щоб це шось суттєво міняло... Але це не принципово, на відміну від "деталей")
```suggestion
  - : Оператори роботи з членами надають доступ до властивостей чи методів об'єкта (`object.property` і `object["property"]`)
```

2022-11-30 23:58 UTC, AdriandeCita requested changes
Декілька зауважень

2022-12-07 12:00 UTC, undead404 commented on files/uk/web/javascript/reference/operators/index.md
> +  - : Array initializer/literal syntax.
```suggestion
  - : Синтаксис ініціалізаторів, чи літералів, масивів.
```

2022-12-07 12:01 UTC, undead404 commented
Більшість прийняв, в одному свій варіант.

2022-12-08 11:35 UTC, undead404 commented
невирішених проблем ніби немає

2022-12-08 23:27 UTC, AdriandeCita approved these changes

2022-12-08 23:27 UTC, merged