translation(CSS): web/css/background-position
webdoky/content pull request #1029
Opened 2022-11-29 19:16 UTC by undead404

Оригінальний вміст: [background-position@MDN](https://developer.mozilla.org/en-us/docs/Web/CSS/background-position), [сирці background-position@GitHub](https://github.com/mdn/content/blob/main/files/en-us/web/css/background-position/index.md)

2022-12-09 21:46 UTC, AdriandeCita commented on files/uk/web/css/background-position/index.md
> +  - : {{cssxref("&lt;position&gt;")}} – положення. Визначає координати X та Y, аби розташувати елемент відносно країв рамок елемента. Може визначатися за допомогою від одного до чотирьох значень. Якщ
"елемент відносно елемента." Думаю, малося на увазі одне із зображень, тож можна написати так
```suggestion
  - : {{cssxref("&lt;position&gt;")}} – положення. Визначає координати X та Y, аби розташувати зображення відносно країв рамок елемента. Може визначатися за допомогою від одного до чотирьох значень. Якщо задано два значення, що не є ключовими словами, то перше з них представляє положення по горизонталі, а друге – по вертикалі. Коли задано лише одне значення, то друге значення вважається за `center`. Коли використовуються три або чотири значення, то значення довжини або відсотків є відступами для попередніх значень – ключових слів.
```

2022-12-10 12:34 UTC, AdriandeCita commented on files/uk/web/css/background-position/index.md
> +    - Зверніть увагу, що: Якщо одне зі значень – `top` або `bottom`, то інше значення не може бути `top` або `bottom`. Якщо одне зі значень – `left` або `right`, то інше значення не може бути `left`
```suggestion
    - Зверніть увагу, що: якщо одне зі значень – `top` або `bottom`, то інше значення не може бути `top` або `bottom`. Аналогічно, якщо одне зі значень – `left` або `right`, то інше значення не може бути `left` або `right`. Це означає, що, наприклад, `top top` і `left right` – недійсні значення.
```

2022-12-10 12:41 UTC, AdriandeCita commented on files/uk/web/css/background-position/index.md
> +Слід згадати, що коли background-size має значення, рівне розмірові контейнера за відповідною віссю, то _відсоткове_ положення за цією віссю не матиме дії, тому що "різниця контейнер-зображення" буде
```suggestion
Слід згадати, що коли background-size має значення, рівне розмірові контейнера за відповідною віссю, то _відсоткове_ положення за цією віссю не діятиме, тому що "різниця контейнер-зображення" буде нулем. Доведеться робити відступи за допомогою абсолютних значень.
```

2022-12-10 12:42 UTC, AdriandeCita commented on files/uk/web/css/background-position/index.md
> +/* Ці приклади використовують властивість-скорочення `background` */
Думаю, це можна записувати простіше
```suggestion
/* Ці приклади використовують скорочену властивість `background` */
```

2022-12-10 12:50 UTC, AdriandeCita commented on files/uk/web/css/background-position/index.md
> +/* Декілька зображень тла: Кожне зображення відповідає
"...відповідає відповідній..."
```suggestion
/* Декілька зображень тла: для кожного зображення вказано
```

2022-12-10 12:50 UTC, AdriandeCita commented on files/uk/web/css/background-position/index.md
> +   відповідній позиції, від першої до останньої. */
```suggestion
   відповідну йому позицію, від першої до останньої. */
```

2022-12-10 12:50 UTC, AdriandeCita commented on files/uk/web/css/background-position/index.md
> +## See also
```suggestion
## Дивіться також
```

2022-12-10 12:50 UTC, AdriandeCita requested changes
Декілька зауважень

2022-12-13 12:19 UTC, undead404 commented on files/uk/web/css/background-position/index.md
> +/* Ці приклади використовують властивість-скорочення `background` */
Не згодний тут. Властивість ніяк не скорочена, це вона сама є скороченням для кількох властивостей

2022-12-13 14:13 UTC, KlashReik commented on files/uk/web/css/background-position/index.md
> +/* Ці приклади використовують властивість-скорочення `background` */
```suggestion
/* Ці приклади використовують скорочений запис властивості `background` */
```
Як вам такий варіант?)

2022-12-14 12:21 UTC, AdriandeCita commented on files/uk/web/css/background-position/index.md
> +/* Ці приклади використовують властивість-скорочення `background` */
це все властивості тла. І мені здається, що запис `background` цілком можна вважати "як скороченням від набору властивостей тла", так і "скороченою властивістю тла". І "скороченим записом властивості тла" - хоча громіздкі версії у нас тут зазвичай не в фаворі))

Наполягати не буду, як я й казав - мені вони здаються рівноправними, а враховуючи нашу любов до розгорнутих формулювань "скорочена властивість" мала б навіть отримати перевагу)

2022-12-14 12:22 UTC, AdriandeCita approved these changes

2022-12-14 12:22 UTC, merged