translation(JS): Web/JavaScript/Reference/Global_Objects/Date/toLocaleDateString
webdoky/content pull request #1030
Opened 2022-11-30 09:58 UTC by AdriandeCita

Оригінальний вміст: [Date.prototype.toLocaleDateString()@MDN](https://developer.mozilla.org/en-us/docs/Web/JavaScript/Reference/Global_Objects/Date/toLocaleDateString), [сирці Date.prototype.toLocaleDateString()@GitHub](https://github.com/mdn/content/blob/main/files/en-us/web/javascript/reference/global_objects/date/tolocaledatestring/index.md)

2022-12-10 16:27 UTC, undead404 requested changes
Стилістичні пропозиції, та принаймні одна помилка

2022-12-10 16:27 UTC, undead404 commented on files/uk/web/javascript/reference/global_objects/date/tolocaledatestring/index.md
> +Метод **`toLocaleDateString()`** повертає рядок із чутливим до мови відображенням тієї частини вказаної дати, яка містить лише календарну дату, в часовому поясі користувацького агента. В тих реалізац
```suggestion
Метод **`toLocaleDateString()`** повертає рядок із чутливим до мови відображенням тієї частини переданої дати, яка містить лише календарну дату, в часовому поясі користувацького агента. В тих реалізаціях, що мають підтримку [API `Intl.DateTimeFormat`](/uk/docs/Web/JavaScript/Reference/Global_Objects/Intl/DateTimeFormat), цей метод просто викликає `Intl.DateTimeFormat`.
```

2022-12-10 16:27 UTC, undead404 commented on files/uk/web/javascript/reference/global_objects/date/tolocaledatestring/index.md
> +Аргументи `locales` та `options` підлаштовують поведінку функції, і дають застосункам змогу ту мову, чиї правила форматування слід застосувати.
```suggestion
Аргументи `locales` та `options` підлаштовують поведінку функції, і дають застосункам змогу задати ту мову, чиї правила форматування слід застосувати.
```

2022-12-10 16:27 UTC, undead404 commented on files/uk/web/javascript/reference/global_objects/date/tolocaledatestring/index.md
> +Для перевірки, чи якась реалізація їх підтримує, можна скористатися існуванням вимоги відхиляти недійсні позначення мови із викиданням винятку {{jsxref("RangeError")}}:
```suggestion
Для перевірки, чи якась реалізація їх підтримує, можна скористатися перевіркою виконання вимоги відхиляти недійсні позначення мови із викиданням винятку {{jsxref("RangeError")}}:
```

2022-12-10 16:27 UTC, undead404 commented on files/uk/web/javascript/reference/global_objects/date/tolocaledatestring/index.md
> +// в разі запиту мови, яка може не підтримуватись, наприклад — Балійської,
```suggestion
// в разі запиту мови, яка може не підтримуватись, наприклад — балійської,
```

2022-12-10 16:27 UTC, undead404 commented on files/uk/web/javascript/reference/global_objects/date/tolocaledatestring/index.md
> +// варто додати запасну мову, в цьому випадку — Індонезійську
```suggestion
// варто додати запасну мову, в цьому випадку — індонезійську
```

2022-12-10 16:27 UTC, undead404 commented on files/uk/web/javascript/reference/global_objects/date/tolocaledatestring/index.md
> +// якийсь застосунок може вирішити вжити часовий пояс UTC, і показати це
```suggestion
// якийсь застосунок може вирішити вжити часовий пояс UTC, і явно показати це
```

2022-12-10 17:50 UTC, AdriandeCita commented on files/uk/web/javascript/reference/global_objects/date/tolocaledatestring/index.md
> +Метод **`toLocaleDateString()`** повертає рядок із чутливим до мови відображенням тієї частини вказаної дати, яка містить лише календарну дату, в часовому поясі користувацького агента. В тих реалізац
куди переданої, якщо цей метод викликається на примурнику дати? Аргументами передаєть локаль, а не дата.

2022-12-10 17:53 UTC, AdriandeCita commented on files/uk/web/javascript/reference/global_objects/date/tolocaledatestring/index.md
> +// В разі перської мови, доволі складно вручну привести дату до сонячної хіджрі
на українській вікі присутні обидва варіанти, тож я обрав ближчий до тексту 
![image](https://user-images.githubusercontent.com/11510394/206868657-596f8472-be74-498e-bcca-df51a044e7ef.png)

2022-12-10 17:56 UTC, AdriandeCita commented
Прийняв все, окрім двох)

2022-12-13 12:37 UTC, undead404 commented
Приймається, але іще треба внести два редіректи з https://raw.githubusercontent.com/mdn/content/main/files/en-us/_redirects.txt

2022-12-13 12:48 UTC, AdriandeCita commented
Ну я переглянув всі наявні посилання в тексті, і не бачу жодного, який треба було б винести до нашого списку переспрямувань

2022-12-13 14:50 UTC, merged