translation(CSS): web/css/calc
webdoky/content pull request #1031
Opened 2022-11-30 10:05 UTC by undead404

Оригінальний вміст: [calc()@MDN](https://developer.mozilla.org/en-us/docs/Web/CSS/calc), [сирці calc()@GitHub](https://github.com/mdn/content/blob/main/files/en-us/web/css/calc/index.md)

Залежить від: https://github.com/webdoky/interactive-examples/pull/59

2022-12-10 12:55 UTC, AdriandeCita commented on files/uk/web/css/calc/index.md
> +Операнди виразу можуть бути будь-якими значеннями синтаксису {{cssxref("&lt;length&gt;")}}. Для кожного значення у виразі можна використовувати різні одиниці вимірювання, якщо завгодно. Крім цього, м
ніколи не зустрічав словосполучення "якщо завгодно". Як правило, якщо вже "завгодно", то питання "якщо?" не стоїть :grin: 
```suggestion
Операнди виразу можуть бути будь-якими значеннями синтаксису {{cssxref("&lt;length&gt;")}}. Для кожного значення у виразі можна використовувати різні одиниці вимірювання, за бажанням. Крім цього, можна використовувати дужки для задання порядку обчислення.
```

2022-12-10 13:02 UTC, AdriandeCita commented on files/uk/web/css/calc/index.md
> +### Розташування на екрані об'єкта з зовнішнім відступом
На перший погляд це читається як "...екрані об'єкта..". Краще розбивати такі сполучення, або явно виділяти обставину комами
```suggestion
### Розташування об'єкта з зовнішнім відступом на екрані
```

2022-12-10 13:03 UTC, AdriandeCita commented on files/uk/web/css/calc/index.md
> +### Автоматичний розмір полів форми для вписування в контейнер
```suggestion
### Автоматичний розмір полів форми для вписування їх в контейнер
```

2022-12-10 13:09 UTC, AdriandeCita commented on files/uk/web/css/calc/index.md
> +Іще одне застосування `calc()` – допомогти пересвідчитись, що поля форми вписуються у доступний простір, не вилазить за край контейнера, дотримується відповідного відступу.
```suggestion
Іще одне застосування `calc()` – допомогти пересвідчитись, що поля форми вписуються у доступний простір, не вилазять за край контейнера, дотримуючись при цьому відповідного відступу.
```

2022-12-10 13:14 UTC, AdriandeCita commented on files/uk/web/css/calc/index.md
> +- [Повний посібник із calc() у CSS](https://css-tricks.com/a-complete-guide-to-calc-in-css/) (CSS-Tricks)
Ми іще не реалізували це на рівні постобробки вмісту, тож напевне є сенс поки продовжити додавати цю позначку в дужках?
```suggestion
- [Повний посібник із calc() у CSS (англ.)](https://css-tricks.com/a-complete-guide-to-calc-in-css/) (CSS-Tricks)
```

2022-12-10 13:14 UTC, AdriandeCita requested changes
Декілька побажань

2022-12-13 12:23 UTC, undead404 commented on files/uk/web/css/calc/index.md
> +Операнди виразу можуть бути будь-якими значеннями синтаксису {{cssxref("&lt;length&gt;")}}. Для кожного значення у виразі можна використовувати різні одиниці вимірювання, якщо завгодно. Крім цього, м
Повсюдно вживається. https://www.google.com/search?q=%22%D1%8F%D0%BA%D1%89%D0%BE%20%D0%B7%D0%B0%D0%B2%D0%B3%D0%BE%D0%B4%D0%BD%D0%BE%22&lr=(-lang_ru)

2022-12-14 12:23 UTC, AdriandeCita approved these changes

2022-12-18 12:09 UTC, undead404 commented
Оновлено: https://github.com/mdn/content/commit/110f67930c6e2efd2a7fb1fb6dc92d756ae30f6c

2022-12-25 15:00 UTC, AdriandeCita approved these changes

2022-12-25 15:00 UTC, merged