translation(HTML): web/html/viewport_meta_tag
webdoky/content pull request #1039
Opened 2022-12-01 08:48 UTC by undead404

Оригінальний вміст: [Viewport meta tag@MDN](https://developer.mozilla.org/en-us/docs/Web/HTML/Viewport_meta_tag), [сирці Viewport meta tag@GitHub](https://github.com/mdn/content/blob/main/files/en-us/web/html/viewport_meta_tag/index.md)

2022-12-09 18:58 UTC, undead404 commented
Оновлено: https://github.com/mdn/content/commit/0985765e63ef5148cba0e10a45be2fe6d2b6e15e

2022-12-10 13:33 UTC, AdriandeCita commented on files/uk/web/html/viewport_meta_tag/index.md
> +Проте цей механізм працює не так добре для сторінок, оптимізованих для вузьких екранів за допомогою [медіазапитів](/uk/docs/Web/CSS/Media_Queries): якщо віртуальна область перегляду, наприклад, 980px
У нас для цього склався термін "адаптивний дизайн", пропоную не відходити від нього. "Реагівний" звучить дещо неприродно, оскільки дієслово "реагувати" є похідним від "реакція". Тобто правильно було б "реактивний дизайн" :thinking: 
```suggestion
Проте цей механізм працює не так добре для сторінок, оптимізованих для вузьких екранів за допомогою [медіазапитів](/uk/docs/Web/CSS/Media_Queries): якщо віртуальна область перегляду, наприклад, 980px, то медіазапити, котрі спрацьовують на 640px або 480px і менше – ніколи не будуть застосовані, обмежуючи ефективність таких технік адаптивного дизайну. Метатег області перегляду пом'якшує цю проблему віртуальної області перегляду на пристроях з вузькими екранами.
```

2022-12-10 13:38 UTC, AdriandeCita commented on files/uk/web/html/viewport_meta_tag/index.md
> +## Основи областей перегляду
Щойно збагнув, отаке "основи ..." -- це дещо претензійно, наче ми тут цілий розділ фізики оглядаємо. Можна говорити "Основни CSS", але в контексті малих тем пропоную трохи перефразувати.
```suggestion
## Основне про область перегляду
```

2022-12-10 13:46 UTC, AdriandeCita commented on files/uk/web/html/viewport_meta_tag/index.md
> +Усталене співвідношення пікселів залежить від роздільної здатності екрана. На екрані з роздільною здатністю, меншою за 200dpi, співвідношення – 1.0. На екранах з роздільною здатністю від 200 до 300dp
```suggestion
Усталене співвідношення пікселів залежить від роздільної здатності екрана. На екрані з роздільною здатністю, меншою за 200dpi, співвідношення – 1.0. На екранах з роздільною здатністю від 200 до 300dpi це співвідношення – 1.5. Для екранів з роздільною здатністю понад 300 dpi співвідношення – ціле число дорівнює floor(_density_/150dpi). Зверніть увагу, що усталене співвідношення діє лише тоді, коли масштаб області перегляду дорівнює 1. Інакше – співвідношення між пікселями CSS та пікселями пристрою залежить від поточного рівня наближення.
```

2022-12-10 13:51 UTC, AdriandeCita commented on files/uk/web/html/viewport_meta_tag/index.md
> +Для сторінок, що задають початковий або максимальний масштаб, це означає, що властивість `width` фактично перекладається на _мінімальну_ ширину області перегляду. Наприклад, якщо макет потребує щонай
Трохи дивне вживання "завширшки".
```suggestion
Для сторінок, що задають початковий або максимальний масштаб, це означає, що властивість `width` фактично перекладається на _мінімальну_ ширину області перегляду. Наприклад, якщо макет потребує щонайменше 500 пікселів ширини, можна використати наступну розмітку. Якщо екран більш ніж 500 пікселів завширшки, браузер збільшить ширину області перегляду (а не виконає наближення) для заповнення екрана:
```

2022-12-10 13:53 UTC, AdriandeCita commented on files/uk/web/html/viewport_meta_tag/index.md
> +Інші доступні [атрибути](/uk/docs/Web/HTML/Element/meta#atrybuty) – `minimum-scale`, `maximum-scale` і `user-scalable`. Ці властивості впливають на початкові масштабування та ширину, а також обмежуют
```suggestion
Інші доступні [атрибути](/uk/docs/Web/HTML/Element/meta#atrybuty): `minimum-scale`, `maximum-scale` і `user-scalable`. Ці властивості впливають на початкові масштабування та ширину, а також обмежують зміни рівня наближення.
```

2022-12-10 13:54 UTC, AdriandeCita requested changes
Декілька побажань

2022-12-13 12:34 UTC, undead404 commented on files/uk/web/html/viewport_meta_tag/index.md
> +Усталене співвідношення пікселів залежить від роздільної здатності екрана. На екрані з роздільною здатністю, меншою за 200dpi, співвідношення – 1.0. На екранах з роздільною здатністю від 200 до 300dp
```suggestion
Усталене співвідношення пікселів залежить від роздільної здатності екрана. На екрані з роздільною здатністю, меншою за 200dpi, співвідношення – 1.0. На екранах з роздільною здатністю від 200 до 300dpi це співвідношення – 1.5. Для екранів з роздільною здатністю понад 300 dpi співвідношення – ціле число, що дорівнює floor(_density_/150dpi). Зверніть увагу, що усталене співвідношення діє лише тоді, коли масштаб області перегляду дорівнює 1. Інакше – співвідношення між пікселями CSS та пікселями пристрою залежить від поточного рівня наближення.
```

2022-12-13 12:35 UTC, undead404 commented
Прийняв, по одному запропонував своє

2022-12-14 12:26 UTC, AdriandeCita approved these changes

2022-12-14 12:27 UTC, AdriandeCita requested changes
Свіжі зміни https://github.com/mdn/content/pull/22893/files

2022-12-24 15:50 UTC, undead404 commented
Оновлено: https://github.com/mdn/content/commit/39d98a4af277139e44b9a57ae61d002d0db553ff

2022-12-25 16:55 UTC, AdriandeCita approved these changes

2022-12-25 16:55 UTC, merged