translation(JS): web/javascript/reference/global_objects/bigint
webdoky/content pull request #1046
Opened 2022-12-02 12:05 UTC by undead404

Оригінальний вміст: [BigInt@MDN](https://developer.mozilla.org/en-us/docs/Web/JavaScript/Reference/Global_Objects/BigInt), [сирці BigInt@GitHub](https://github.com/mdn/content/blob/main/files/en-us/web/javascript/reference/global_objects/bigint/index.md)

2022-12-10 13:58 UTC, AdriandeCita commented on files/uk/web/javascript/reference/global_objects/bigint/index.md
> +Наступні оператори можуть використовуватися зі значеннями BigInt або загорнутими в об'єкти значеннями BigInt:
```suggestion
Наступні оператори можуть використовуватися зі значеннями BigInt (як примітивними, так і загорнутими в об'єкти):
```

2022-12-10 13:59 UTC, AdriandeCita commented on files/uk/web/javascript/reference/global_objects/bigint/index.md
> +// 9007199254740993n, this works now!
```suggestion
// 9007199254740993n, це тепер працює!
```

2022-12-10 14:00 UTC, AdriandeCita commented on files/uk/web/javascript/reference/global_objects/bigint/index.md
> +// 2n, not 2.5n
```suggestion
// 2n, а не 2.5n
```

2022-12-10 14:08 UTC, AdriandeCita commented on files/uk/web/javascript/reference/global_objects/bigint/index.md
> +Значення BigInt не має строгої рівності щодо значення Number, але _має_ нестрогу:
Загалом було б непогано переглянути вирази "мати строгу/нестрогу рівність", вони надто неоднозначні. Я бачу щонайменше три різні тлумачення:
- Значення може дорівнювати/не дорівнювати іншому
- Значення в принципі можна/не можна порівнювати
- Значення може мати якийсь атрибут, асоційований з рівністю
Sounds a little bit messy)
```suggestion
Значення BigInt строго не дорівнює значенню Number, проте дорівнює нестрого:
```

2022-12-10 14:26 UTC, AdriandeCita commented on files/uk/web/javascript/reference/global_objects/bigint/index.md
> +- Рядки перетворюються шляхом розбору їх так, ніби вони містять цілочисловий літерал. Будь-яка невдача розбору призводить до {{jsxref("SyntaxError")}}. Синтаксис є підмножиною [рядкових літералів чис
```suggestion
- Рядки перетворюються шляхом розбору їх так, ніби вони містять цілочисловий літерал. Будь-яка невдача розбору призводить до {{jsxref("SyntaxError")}}. Синтаксис є підмножиною [рядкових літералів чисел](/uk/docs/Web/JavaScript/Reference/Global_Objects/Number#zvedennia-do-chysla), у якій десятковий розділювач і показник степеня – заборонені.
```

2022-12-10 14:56 UTC, AdriandeCita commented on files/uk/web/javascript/reference/global_objects/bigint/index.md
> +  - : Примушує значення BigInt до знакового цілого числа, і повертає таке значення.
```suggestion
  - : Обрізає значення BigInt до знакового цілого числа, і повертає його.
```

2022-12-10 14:57 UTC, AdriandeCita commented on files/uk/web/javascript/reference/global_objects/bigint/index.md
> +  - : Примушує значення BigInt до беззнакового цілого числа, і повертає таке значення.
```suggestion
  - : Обрізає значення BigInt до беззнакового цілого числа, і повертає його.
```

2022-12-10 15:01 UTC, AdriandeCita commented on files/uk/web/javascript/reference/global_objects/bigint/index.md
> +- Не слід перетворювати між собою значення BigInt і значення Number.
```suggestion
- Не слід перетворювати між собою значення BigInt і Number.
```

2022-12-10 15:16 UTC, AdriandeCita commented on files/uk/web/javascript/reference/global_objects/bigint/index.md
> +Операції, котрі підтримують значення BigInt, мають не сталий час виконання, а тому вразливі до [атак по часу](https://uk.wikipedia.org/wiki/%D0%90%D1%82%D0%B0%D0%BA%D0%B0_%D0%BF%D0%BE_%D1%87%D0%B0%D1
```suggestion
Операції, котрі підтримують значення BigInt, мають не сталий час виконання, а тому вразливі до [атак по часу](https://uk.wikipedia.org/wiki/%D0%90%D1%82%D0%B0%D0%BA%D0%B0_%D0%BF%D0%BE_%D1%87%D0%B0%D1%81%D1%83). Таким чином, значення BigInt у JavaScript можуть бути небезпечним для використання в криптографії, якщо не вживати застережних заходів. Як дуже узагальнений приклад – нападник може виміряти часову різницю між `101n ** 65537n` і `17n ** 9999n`, завдяки чому – оцінити потужність таємних значень, як то приватних ключів, на основі витрат часу. Якщо все ж необхідно використовувати BigInt, слід звернутися до [ЧаПів атак по часу](https://timing.attacks.cr.yp.to/programming.html) щодо загальних порад на тему цієї проблеми.
```

2022-12-10 15:19 UTC, AdriandeCita commented on files/uk/web/javascript/reference/global_objects/bigint/index.md
> +Коли є дані JSON, котрі містять значення, про котрі відомо, що там будуть великі цілі числа, то для їх обробки можна використати параметр `JSON.parse` [`reviver`](/uk/docs/Web/JavaScript/Reference/Gl
```suggestion
Коли є дані JSON, котрі містять значення, про котрі відомо, що там будуть великі цілі числа, то для їх обробки можна використати параметр [`reviver`](/uk/docs/Web/JavaScript/Reference/Global_Objects/JSON/parse#zastosuvannia-parametra-reviver) методу `JSON.parse`:
```

2022-12-10 15:20 UTC, AdriandeCita requested changes
Декілька зауважень

2022-12-13 13:35 UTC, undead404 commented on files/uk/web/javascript/reference/global_objects/bigint/index.md
> +Значення BigInt не має строгої рівності щодо значення Number, але _має_ нестрогу:
Норм, треба тільки курсив відтворити у пропозиції.

Щодо решти: навряд ми знайдемо для такої специфічної штуки кращі слова, ніж прямий переклад

2022-12-13 13:36 UTC, undead404 commented on files/uk/web/javascript/reference/global_objects/bigint/index.md
> +- Рядки перетворюються шляхом розбору їх так, ніби вони містять цілочисловий літерал. Будь-яка невдача розбору призводить до {{jsxref("SyntaxError")}}. Синтаксис є підмножиною [рядкових літералів чис
Мова саме про eX в кінці запису, не думаю, що це можна назвати "степенем"

2022-12-13 13:38 UTC, undead404 commented on files/uk/web/javascript/reference/global_objects/bigint/index.md
> +Операції, котрі підтримують значення BigInt, мають не сталий час виконання, а тому вразливі до [атак по часу](https://uk.wikipedia.org/wiki/%D0%90%D1%82%D0%B0%D0%BA%D0%B0_%D0%BF%D0%BE_%D1%87%D0%B0%D1
Чудово, але треба перечитати

2022-12-14 12:28 UTC, AdriandeCita commented on files/uk/web/javascript/reference/global_objects/bigint/index.md
> +Значення BigInt не має строгої рівності щодо значення Number, але _має_ нестрогу:
```suggestion
Значення BigInt строго не дорівнює значенню Number, проте _дорівнює_ нестрого:
```

2022-12-14 12:36 UTC, AdriandeCita commented on files/uk/web/javascript/reference/global_objects/bigint/index.md
> +- Рядки перетворюються шляхом розбору їх так, ніби вони містять цілочисловий літерал. Будь-яка невдача розбору призводить до {{jsxref("SyntaxError")}}. Синтаксис є підмножиною [рядкових літералів чис
хммм, так, ти частково правий 

![image](https://user-images.githubusercontent.com/11510394/207596941-ea128e0d-6703-475c-b6ed-ea0e9db9dc24.png)

2022-12-15 12:32 UTC, undead404 commented on files/uk/web/javascript/reference/global_objects/bigint/index.md
> +- Рядки перетворюються шляхом розбору їх так, ніби вони містять цілочисловий літерал. Будь-яка невдача розбору призводить до {{jsxref("SyntaxError")}}. Синтаксис є підмножиною [рядкових літералів чис
```suggestion
- Рядки перетворюються шляхом розбору їх так, ніби вони містять цілочисловий літерал. Будь-яка невдача розбору призводить до {{jsxref("SyntaxError")}}. Синтаксис є підмножиною [рядкових літералів чисел](/uk/docs/Web/JavaScript/Reference/Global_Objects/Number#zvedennia-do-chysla), у якій десятковий розділювач і експоненційний запис – заборонені.
```

2022-12-15 12:33 UTC, undead404 commented on files/uk/web/javascript/reference/global_objects/bigint/index.md
> +Операції, котрі підтримують значення BigInt, мають не сталий час виконання, а тому вразливі до [атак по часу](https://uk.wikipedia.org/wiki/%D0%90%D1%82%D0%B0%D0%BA%D0%B0_%D0%BF%D0%BE_%D1%87%D0%B0%D1
```suggestion
Операції, котрі підтримують значення BigInt, мають не сталий час виконання, а тому вразливі до [атак по часу](https://uk.wikipedia.org/wiki/%D0%90%D1%82%D0%B0%D0%BA%D0%B0_%D0%BF%D0%BE_%D1%87%D0%B0%D1%81%D1%83). Таким чином, значення BigInt у JavaScript можуть бути небезпечними для використання в криптографії, якщо не вживати застережних заходів. Як дуже узагальнений приклад – нападник може виміряти часову різницю між `101n ** 65537n` і `17n ** 9999n`, завдяки чому – оцінити потужність таємних значень, як то приватних ключів, на основі витрат часу. Якщо все ж необхідно використовувати BigInt, слід звернутися до [ЧаПів атак по часу](https://timing.attacks.cr.yp.to/programming.html) щодо загальних порад на тему цієї проблеми.
```

2023-01-05 21:23 UTC, AdriandeCita requested changes
Іще оновлення https://github.com/mdn/content/commit/970e2b839205f34c6d18ff623200630e7cc425cc#diff-ec3d4ea1ef73b0170e17bc63a3cb6641a67ce1661df1fda40f7ae38ad028754a

2023-01-07 11:59 UTC, undead404 commented
Оновлено

2023-01-08 19:33 UTC, AdriandeCita approved these changes

2023-01-08 19:33 UTC, merged