update(JS): web/javascript/reference/global_objects/encodeuricomponent
webdoky/content pull request #1065
Opened 2022-12-10 13:35 UTC by undead404

Оригінальний вміст: [encodeURIComponent()@MDN](https://developer.mozilla.org/en-us/docs/Web/JavaScript/Reference/Global_Objects/encodeURIComponent), [сирці encodeURIComponent()@GitHub](https://github.com/mdn/content/blob/main/files/en-us/web/javascript/reference/global_objects/encodeuricomponent/index.md)

Нові зміни:
- [mdn/content@180830a](https://github.com/mdn/content/commit/180830a7f75dec415efc53cb4a6c120e9bba45ab)
- [mdn/content@9e52d33](https://github.com/mdn/content/commit/9e52d335675a9f7daa34b5e24c9b1292dbf23b2e)
- [mdn/content@1ef21ad](https://github.com/mdn/content/commit/1ef21adae85db696674a78c4127bc032ef9003ae)

2022-12-10 15:45 UTC, AdriandeCita commented on files/uk/web/javascript/reference/global_objects/encodeuricomponent/index.md
> +Порівняно з {{jsxref("encodeURI()")}}, `encodeURIComponent()` екранує більшу множину символів. `encodeURIComponent()` слід застосовувати на введених користувачем полях форм, що надсилаються на сервер
Не одразу зрозуміло, до чого там "вона", пропоную вказати явно
```suggestion
Порівняно з {{jsxref("encodeURI()")}}, `encodeURIComponent()` екранує більшу множину символів. Функцію `encodeURIComponent()` слід застосовувати на введених користувачем полях форм, що надсилаються на сервер за допомогою {{HTTPMethod("POST")}}: вона екранує символи `&`, що можуть ненавмисно бути додані при введенні даних для певних сутностей HTML, та інші символи, що вимагають кодування й розкодування. Наприклад, якщо користувач напише `Jack & Jill`, то без `encodeURIComponent()` амперсанд може бути розтлумачений сервером як початок нового поля й поставити під загрозу цілісність даних.
```

2022-12-10 15:47 UTC, AdriandeCita requested changes
Невеличке зауваження

2022-12-12 10:41 UTC, Aenqau approved these changes

2022-12-13 13:15 UTC, undead404 commented
Прийнято

2022-12-14 13:12 UTC, AdriandeCita requested changes
Свіжі зміни https://github.com/mdn/content/commit/c4e3558ee1045803df4a685f11f94dca273cd5fe#diff-455fc23eab49cabe7c298c8e5cd7ca8fd06e8b2d01d8bf664a6ed93d0aea7366

2022-12-24 22:57 UTC, undead404 commented
Оновлено

2023-01-05 21:41 UTC, AdriandeCita approved these changes

2023-01-05 21:41 UTC, merged