update(JS): web/javascript/guide/using_promises
webdoky/content pull request #1066
Opened 2022-12-13 09:27 UTC by undead404

Оригінальний вміст: [Використання промісів@MDN](https://developer.mozilla.org/en-us/docs/Web/JavaScript/Guide/Using_promises), [сирці Використання промісів@GitHub](https://github.com/mdn/content/blob/main/files/en-us/web/javascript/guide/using_promises/index.md)

Нові зміни:
- [mdn/content@72ac1f6](https://github.com/mdn/content/commit/72ac1f6cc01545cc6e2de3e6d7bc1b33c52870ff)
- [mdn/content@1858440](https://github.com/mdn/content/commit/1858440356147c483daa58ea0ff3046015bd1056)
- [mdn/content@79f307c](https://github.com/mdn/content/commit/79f307ce6c91d661aa024addea2f6631f4853e47)
- [mdn/content@8fd1577](https://github.com/mdn/content/commit/8fd15775b58a2a671de6b38e4212773418c73a21)
- [mdn/content@36b5328](https://github.com/mdn/content/commit/36b5328376d94cd501dfc33ee600ee9f4a9669f5)

2022-12-24 23:01 UTC, undead404 commented
Оновлено

2023-01-05 21:47 UTC, AdriandeCita commented on files/uk/web/javascript/guide/using_promises/index.md
> +Перша помилка – не з'єднувати все правильно в ланцюжок. Так виходить, коли створюється новий проміс, але його забувають повернути. Як наслідок, ланцюжок розривається – або радше виходять два незалежн
```suggestion
Перша помилка – не з'єднувати все правильно в ланцюжок. Так виходить, коли створюється новий проміс, але його забувають повернути. Як наслідок, ланцюжок розривається – або радше виходять два незалежні ланцюжки, що виконуються окремо. Це означає, що `doFourthThing()` не чекатиме завершення `doSomethingElse()` чи `doThirdThing`, а запуститься паралельно щодо них – що, ймовірно, не було задумано. Окремі ланцюжки також мають окрему обробку помилок, що призводить до неперехоплених помилок.
```

2023-01-05 21:57 UTC, AdriandeCita requested changes
Невеличке зауваження

2023-01-08 08:29 UTC, undead404 commented
Прийнято

2023-01-08 19:34 UTC, AdriandeCita approved these changes

2023-01-08 19:34 UTC, merged