update(JS): web/javascript/closures
webdoky/content pull request #1078
Opened 2022-12-13 14:42 UTC by undead404

Оригінальний вміст: [Замикання@MDN](https://developer.mozilla.org/en-us/docs/Web/JavaScript/Closures), [сирці Замикання@GitHub](https://github.com/mdn/content/blob/main/files/en-us/web/javascript/closures/index.md)

Нові зміни:
- [mdn/content@2585122](https://github.com/mdn/content/commit/258512284e0f97534b18de488ac9ad1a9b70a253)

2022-12-14 15:10 UTC, AdriandeCita approved these changes

2022-12-14 15:11 UTC, AdriandeCita requested changes
Нові зміни https://github.com/mdn/content/commit/effd5de5e42bfe045c3bf44b2d7b14f4d6146785

2022-12-24 22:51 UTC, undead404 commented
Оновлено

2022-12-25 15:00 UTC, AdriandeCita approved these changes

2022-12-25 15:00 UTC, merged