translation(JS): docs/Web/JavaScript/Reference/Global_Objects/Array/indexOf
webdoky/content pull request #109
Opened 2021-11-14 15:03 UTC by Maksym1910

Original content: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/indexOf

2021-11-20 22:27 UTC, AdriandeCita commented on files/uk/web/javascript/reference/global_objects/array/indexof/index.md
> +Метод **`indexOf()`** повертає перший індекс, за яким даний елемент можна знайти в масиві або -1, якщо його немає.
```suggestion
Метод **`indexOf()`** повертає перший індекс, за яким даний елемент можна знайти в масиві, або -1 — якщо його немає.
```

2021-11-20 22:30 UTC, AdriandeCita commented on files/uk/web/javascript/reference/global_objects/array/indexof/index.md
> +  - : Індекс, з якого потрібно почати пошук. Якщо індекс більший або дорівнює довжині масиву, повертається -1, це означає, що пошук у масиві виконуватись не буде. Якщо надане значення індексу є від’є
```suggestion
  - : Індекс, з якого потрібно почати пошук. Якщо індекс більший або дорівнює довжині масиву, повертається -1 — це означає, що пошук у масиві виконуватись не буде. Якщо надане значення індексу є від’ємним числом, воно приймається як зміщення від кінця масиву. Примітка: якщо наданий індекс є від’ємним, пошук у масиві все одно виконується спереду назад. Якщо наданий індекс дорівнює 0, пошук буде здійснюватися в усьому масиві. Усталено: 0 (шукається весь масив).
```

2021-11-20 22:36 UTC, AdriandeCita commented on files/uk/web/javascript/reference/global_objects/array/indexof/index.md
> +  - : Індекс, з якого потрібно почати пошук. Якщо індекс більший або дорівнює довжині масиву, повертається -1, це означає, що пошук у масиві виконуватись не буде. Якщо надане значення індексу є від’є
```suggestion
  - : Індекс, з якого потрібно почати пошук. Якщо індекс більший або дорівнює довжині масиву, повертається -1, це означає, що пошук у масиві виконуватись не буде. Якщо надане значення індексу є від’ємним числом, воно приймається як зміщення від кінця масиву. Примітка: якщо наданий індекс є від’ємним, пошук у масиві все одно виконується спереду назад. Якщо наданий індекс дорівнює 0, пошук буде здійснюватися в усьому масиві. Усталено: 0 (перевіряється весь масив).
```

2021-11-20 22:38 UTC, AdriandeCita commented on files/uk/web/javascript/reference/global_objects/array/indexof/index.md
> +### Значення, що повертається
Ми колись глобально вирішили вживати "Повернене значення" для консистентності. Треба додати це в глосарій
```suggestion
### Повернене значення
```

2021-11-20 22:39 UTC, AdriandeCita commented on files/uk/web/javascript/reference/global_objects/array/indexof/index.md
> +Перший індекс елемента в масиві; **-1**, якщо не знайдено.
```suggestion
Перший індекс елемента в масиві; **-1**, якщо нічого не знайдено.
```

2021-11-20 22:45 UTC, AdriandeCita commented on files/uk/web/javascript/reference/global_objects/array/indexof/index.md
> +### Визначення, чи існує елемент у масиві чи ні, та оновлення масиву
```suggestion
### Визначення, чи знаходиться елемент у масиві, чи ні, та оновлення масиву
```

2021-11-20 22:45 UTC, AdriandeCita commented on files/uk/web/javascript/reference/global_objects/array/indexof/index.md
> +// Нова veggies колекція: potato,tomato,chillies,green-pepper,spinach
```suggestion
// Нова колекція veggies: potato,tomato,chillies,green-pepper,spinach
```

2021-11-20 22:48 UTC, AdriandeCita commented on files/uk/web/javascript/reference/global_objects/array/indexof/index.md
> +`indexOf()` було додано до стандарту ECMA-262 у 5-му виданні; тому він може бути присутнім не у всіх браузерах. Ви можете обійти це, використовуючи наведений нижче код на початку ваших скриптів. Це д
```suggestion
`indexOf()` було додано до стандарту ECMA-262 у 5-му виданні, тому він може бути присутнім не у всіх браузерах. Можна це обійти, використовуючи наведений нижче код на початку ваших скриптів. Це дозволить використовувати `indexOf()`, навіть якщо вбудована підтримка відсутня. Цей алгоритм відповідає алгоритму, зазначеному в ECMA-262, 5-те видання, за умови, що {{jsxref("Global_Objects/TypeError",
```

2021-11-20 23:02 UTC, AdriandeCita commented on files/uk/web/javascript/reference/global_objects/array/indexof/index.md
> +// Ця версія намагається оптимізувати, лише перевіряючи "in" під час пошуку undefined і
```suggestion
// Ця версія намагається оптимізуватися, перевіряючи "in" лише під час пошуку undefined, і
```

2021-11-20 23:12 UTC, AdriandeCita commented on files/uk/web/javascript/reference/global_objects/array/indexof/index.md
> +Однак, якщо вас більше цікавлять усі дрібні технічні деталі, визначені стандартом ECMA, і вас менше турбують продуктивність або стислість, цей більш описовий поліфіл може виявитися кориснішим.
```suggestion
Однак, якщо вас більше цікавлять усі дрібні технічні деталі, визначені стандартом ECMA, і менше турбують продуктивність або стислість, цей краще документований поліфіл може виявитися кориснішим.
```

2021-11-20 23:20 UTC, AdriandeCita commented on files/uk/web/javascript/reference/global_objects/array/indexof/index.md
> +      //   Це неявно для операндів LHS оператора in
```suggestion
      //   Це неявно для операндів лівої сторони оператора in
```

2021-11-20 23:22 UTC, AdriandeCita commented on files/uk/web/javascript/reference/global_objects/array/indexof/index.md
> +      // c. Якщо kPresent - вірно, то
Вірно - це для нерівностей, окремі значення радше істинні
```suggestion
      // c. Якщо значеня kPresent - істинне, то
```

2021-11-20 23:25 UTC, AdriandeCita commented on files/uk/web/javascript/reference/global_objects/array/indexof/index.md
> +## Технічні характеристики
Хоча специфікація ECMA якоюсь мірою є описом технічних характеристик, зазвичай її все-таки позначають терміном "специфікація"
```suggestion
## Специфікації
```

2021-11-20 23:28 UTC, AdriandeCita commented on files/uk/web/javascript/reference/global_objects/array/indexof/index.md
> +## Сумісність з браузером
Ліпше у множині, оскільки тема сумісності зачіпає багато браузерів
```suggestion
## Сумісність з браузерами
```

2021-11-20 23:30 UTC, AdriandeCita commented on files/uk/web/javascript/reference/global_objects/array/indexof/index.md
> +## Дивись також
В звертаннях до читача ми зазвичай вживаємо другу особу множини,
```suggestion
## Дивіться також
```

2021-11-21 13:28 UTC, undead404 requested changes

2021-11-21 13:28 UTC, undead404 commented on files/uk/web/javascript/reference/global_objects/array/indexof/index.md
> +  - : Індекс, з якого потрібно почати пошук. Якщо індекс більший або дорівнює довжині масиву, повертається -1, це означає, що пошук у масиві виконуватись не буде. Якщо надане значення індексу є від’є
```suggestion
  - : Індекс, з якого потрібно почати пошук. Якщо індекс більший або дорівнює довжині масиву, повертається -1: це означає, що пошук у масиві виконуватись не буде. Якщо надане значення індексу є від’ємним числом, то воно приймається як зміщення від кінця масиву. Примітка: якщо наданий індекс є від’ємним, то пошук у масиві все одно виконується спереду назад. Якщо наданий індекс дорівнює 0 – пошук буде здійснюватися в усьому масиві. Усталено: 0 (перевіряється весь масив).
```
У безсполучникових складних реченнях перед реченням-поясненням треба вживати все-таки `:`.

2021-11-21 13:28 UTC, undead404 commented on files/uk/web/javascript/reference/global_objects/array/indexof/index.md
> +`indexOf()` порівнює `searchElement` з елементами масиву, використовуючи [строгу рівність](/uk/docs/Web/JavaScript/Reference/Operators/Strict_equality) (той самий метод, що використовується операторо
```suggestion
`indexOf()` порівнює `searchElement` з елементами масиву, використовуючи [строгу рівність](/uk/docs/Web/JavaScript/Reference/Operators/Strict_equality) (той самий метод, що використовується оператором потрійної рівності `===`).
```

2021-11-21 13:28 UTC, undead404 commented on files/uk/web/javascript/reference/global_objects/array/indexof/index.md
> +var veggies = ['potato', 'tomato', 'chillies', 'green-pepper'];
```suggestion
var veggies = ['картопля', 'помідор', 'червоний гострий перець', 'зелений болгарський перець'];
```

2021-11-21 13:28 UTC, undead404 commented on files/uk/web/javascript/reference/global_objects/array/indexof/index.md
> +        console.log('New veggies collection is : ' + veggies);
```suggestion
        console.log('Нова овочева колекція: ' + veggies);
```

2021-11-21 13:28 UTC, undead404 commented on files/uk/web/javascript/reference/global_objects/array/indexof/index.md
> +        console.log(veggie + ' already exists in the veggies collection.');
```suggestion
        console.log(veggie + ' уже є в овочевій колекції.');
```

2021-11-21 13:28 UTC, undead404 commented on files/uk/web/javascript/reference/global_objects/array/indexof/index.md
> +updateVegetablesCollection(veggies, 'spinach');
```suggestion
updateVegetablesCollection(veggies, 'шпинат');
```

2021-11-21 13:28 UTC, undead404 commented on files/uk/web/javascript/reference/global_objects/array/indexof/index.md
> +// Нова veggies колекція: potato,tomato,chillies,green-pepper,spinach
```suggestion
// Нова овочева колекція: картопля,помідор,червоний гострий перець,зелений болгарський перець,шпинат
```

2021-11-21 13:28 UTC, undead404 commented on files/uk/web/javascript/reference/global_objects/array/indexof/index.md
> +// spinach вже є в колекції veggies.
```suggestion
// шпинат уже є в овочевій колекції.
```

2021-11-21 13:28 UTC, undead404 commented on files/uk/web/javascript/reference/global_objects/array/indexof/index.md
> +updateVegetablesCollection(veggies, 'spinach');
```suggestion
updateVegetablesCollection(veggies, 'шпинат');
```

2021-11-21 13:28 UTC, undead404 commented on files/uk/web/javascript/reference/global_objects/array/indexof/index.md
> +    // 1. Нехай o буде результатом виклику ToObject, передаючи
```suggestion
    // 1. Нехай o буде результатом виклику Object, передаючи
```

2021-11-21 13:28 UTC, undead404 commented on files/uk/web/javascript/reference/global_objects/array/indexof/index.md
> +      // c. Якщо kPresent - вірно, то
@AdriandeCita подільський діалект детектед))

2021-11-21 13:30 UTC, undead404 requested changes

2021-11-21 13:30 UTC, undead404 commented on files/uk/web/javascript/reference/global_objects/array/indexof/index.md
> +      // c. Якщо значеня kPresent - істинне, то
```suggestion
      // c. Якщо значення kPresent - істинне, то
```
Подільський варіант not allowed

2021-11-27 12:33 UTC, AdriandeCita commented on files/uk/web/javascript/reference/global_objects/array/indexof/index.md
> +Метод **`indexOf()`** повертає перший індекс, за яким даний елемент можна знайти в масиві, або -1 - якщо його немає.
Тут (і нижче) малося на увазі тире, а не дефіс.
```suggestion
Метод **`indexOf()`** повертає перший індекс, за яким даний елемент можна знайти в масиві, або -1 — якщо його немає.
```

Якщо його складно набирати - рекомендую або знайти системний метод додавання таких розділових знаків (@undead404 нещодавно кидав один такий для макосі), або додати сніпет в текстовий редактор (я колись кидав в чат, можу продублювати)

2021-11-27 12:39 UTC, AdriandeCita commented on files/uk/web/javascript/reference/global_objects/array/indexof/index.md
> +      // c. Якщо kPresent - вірно, то
закриваю цей діалог, оскільки @undead404 додав зауваження до свіжої версії

2021-11-27 12:40 UTC, AdriandeCita commented
Залишив декілька старих діалогів відкритими, здебільшого через дефіси замість тире

2021-11-29 11:30 UTC, undead404 commented on files/uk/web/javascript/reference/global_objects/array/indexof/index.md
> +Метод **`indexOf()`** повертає перший індекс, за яким даний елемент можна знайти в масиві, або -1 - якщо його немає.
`&mdash;` – можна іще таке ставити, також має працювати.

На макосі: Alt + -

2021-11-29 11:30 UTC, undead404 commented on files/uk/web/javascript/reference/global_objects/array/indexof/index.md
> +  - : Індекс, з якого потрібно почати пошук. Якщо індекс більший або дорівнює довжині масиву, повертається -1 - це означає, що пошук у масиві виконуватись не буде. Якщо надане значення індексу є від’
```suggestion
  - : Індекс, з якого потрібно почати пошук. Якщо індекс більший або дорівнює довжині масиву, повертається -1 - це означає, що пошук у масиві виконуватись не буде. Якщо надане значення індексу є від’ємним числом, воно приймається як зміщення від кінця масиву. Примітка: якщо наданий індекс є від’ємним, пошук у масиві все одно виконується від початку до кінця. Якщо наданий індекс дорівнює 0, пошук буде здійснюватися в усьому масиві. Усталено: 0 (перевіряється весь масив).
```

В оригіналі "front to back"... Твій переклад трохи мене заплутав

2021-12-07 21:51 UTC, AdriandeCita approved these changes

2021-12-07 21:52 UTC, merged