update(JS): web/javascript/guide/regular_expressions
webdoky/content pull request #1097
Opened 2022-12-15 10:22 UTC by undead404

Оригінальний вміст: [Регулярні вирази@MDN](https://developer.mozilla.org/en-us/docs/Web/JavaScript/Guide/Regular_Expressions), [сирці Регулярні вирази@GitHub](https://github.com/mdn/content/blob/main/files/en-us/web/javascript/guide/regular_expressions/index.md)

Нові зміни:
- [mdn/content@ba8f148](https://github.com/mdn/content/commit/ba8f14874591980b23ca63edc8357aa858d86413)
- [mdn/content@04e588e](https://github.com/mdn/content/commit/04e588e119741b47360e310ed20dba1dcc09aa7b)
- [mdn/content@effd5de](https://github.com/mdn/content/commit/effd5de5e42bfe045c3bf44b2d7b14f4d6146785)

2022-12-15 17:13 UTC, AdriandeCita commented on uk_spelling_additions.txt
> +неюнікодними
А сенс їх повертати?

2022-12-15 17:17 UTC, AdriandeCita requested changes
Схоже, треба переглянути весь текст статті і позабирати з нього всякі ці "юнікодні" згадки. Якщо ти не хочеш засмічувати поточний ПР цим - давай зробимо це пізніше

2022-12-15 18:55 UTC, undead404 commented on uk_spelling_additions.txt
> +неюнікодними
У цій статті геть інший випадок

2022-12-15 23:22 UTC, AdriandeCita commented on uk_spelling_additions.txt
> +неюнікодними
а-а, це може бути одна із причин, чому я взагалі в першій версії використав пряму кальку))

Добре, най повисить, я трохи пізніше іще подивлюся конкретно по місцю, не повертати ж його назад до вжитку

2022-12-16 09:10 UTC, undead404 commented on uk_spelling_additions.txt
> +неюнікодними
Трошки поясню свою проблему. Коли символ "юнікодний" чи рядок, то це можна легко замінити зворотом "X Unicode". А коли мова про регулярний вираз, котрий працює з Unicode... У мене якось не знайшлося уяви вигадати, як це краще сказати

2023-01-02 19:47 UTC, undead404 commented
Оновлено

2023-01-07 12:01 UTC, undead404 commented
Нові зміни – нерелевантні

2023-01-13 18:09 UTC, Aenqau commented on uk_spelling_additions.txt
> +неюнікодними
Мабуть не є великий сенс сюди придумувати всякі "юнікодопридатні" варіанти

2023-01-25 15:58 UTC, Aenqau commented on uk_spelling_additions.txt
> +неюнікодними
Перепрошую, я тут домахався до того, що "неюнікодний" в даному контексті може бути спробою скоротити характеристику певного явища, зі втратою контексту

2023-01-26 08:57 UTC, undead404 commented on uk_spelling_additions.txt
> +неюнікодними
Ок, а апрув ти помилково поставив?

2023-01-29 12:58 UTC, AdriandeCita commented on uk_spelling_additions.txt
> +неюнікодними
фактично у нас є три варіанти:
- Використовувати оригінальний термін `Unicode`. Наразі ми зіштовхнулися з тим, що це створює складнощі з виразами штибу "Using unicode regular expressions". Прямий переклад цього як `Застосування регулярних виразів unicode" звучить неоковирно, і трохи неоднозначно.
- Використовувати оригінальний термін `Unicode`, але додавати до нього наші суфікси, на кшталт "Застосування unicode-них регулярних виразів". В принципі, це може спрацювати, проте:
  - Здається громіздким
  - Виглядає як хак
  - Я не знайшов правопису на такі витребеньки. З точки зору прочитності нас зрозуміють, але це виглядає як недокументована фіча української мови (див. попередній пункт)
- Повернутися до кальки з англійської. Не є цілком коректним, оскільки Unicode - це покликання на назву стандарту, а калькою воно починає виглядати як рядовий іменник (із похідними).

У мене немає хорошого рішення. З точки зору SEO нам не завадить мати обидва варіанти, оскільки в мережі зустрічаються обидва (наприклад https://devzone.org.ua/post/yunikod-neobkhidniy-praktichniy-minimum-dlya-kozhnogo-rozrobnika)

2023-01-29 13:02 UTC, AdriandeCita commented on uk_spelling_additions.txt
> +неюнікодними
Описав це тут https://github.com/webdoky/content/issues/1264. Пропоную на цьому зупинитися, і продовжити дискусію поза контекстом цього конкретного ПРа

2023-01-29 13:03 UTC, AdriandeCita approved these changes

2023-01-29 13:03 UTC, merged