translation: web/html/element/hr/index.md
webdoky/content pull request #110
Opened 2021-11-15 20:22 UTC by Keira79

Original content here:
https://developer.mozilla.org/en-US/docs/Web/HTML/Element/hr

2021-11-20 23:34 UTC, AdriandeCita commented
Тут зараз дві сторінки, останнім комітом прилетіло. Я приберу той коміт, як візьмусь за рев'ю

2021-11-21 13:31 UTC, undead404 commented on block_level_elements
> +---
В цього файлу ще, мабуть, має бути якесь розширення

2021-11-21 16:45 UTC, Keira79 commented on block_level_elements
> +---
Цей файл тут взагалі не повинен існувати. Я тому й питала, як правильно коммітіти, в п'ятницю. Одже, в цієй гилці дивіться лише hr. Елементи що утворюють блоки вже збережено новим коммітом під час зустрічі ))

2021-11-28 17:38 UTC, AdriandeCita commented on files/uk/web/html/element/hr/index.md
> +title: '<hr> (горизонтальне правило): Елемент що розділяє через зміну теми'
В контексті вебу це радше лінія. В українській є слово "правИло", але для вебу воно не підходить. Також трохи спростив формулювання назви
```suggestion
title: '<hr> (horizontal rule — горизонтальна лінія): Елемент розділу між темами'
```

2021-11-28 17:38 UTC, AdriandeCita commented on files/uk/web/html/element/hr/index.md
> +title: '<hr> (горизонтальне правило): Елемент що розділяє через зміну теми'
аа, так, і я залишив англійський варіант через тире, для контексту з позначенням тегу

2021-11-28 17:43 UTC, AdriandeCita commented on files/uk/web/html/element/hr/index.md
> +Елемент **<hr>** в [HTML](/uk/docs/Web/HTML)  відокремлює параграфи, наприклад коли змінюється сцена в історії, чи коли змінюємо тему всередині секції.
Paragraph - це абзац, + трохи узгодив особи
```suggestion
Елемент **<hr>** в [HTML](/uk/docs/Web/HTML)  служить для розділення елементів рівня абзацу: наприклад, коли змінюється сцена в історії, чи тема всередині секції.
```

2021-11-28 18:20 UTC, AdriandeCita commented on files/uk/web/html/element/hr/index.md
> +Історично, елемент **<hr>**,  як "горизонтальне правило" презентував горизонтальну лінію, що розділяє зміст. Але ж сьогодні ми говоримо про **<hr>** у семантичному сенсі більш ніж у графічному. Одже,
вище згадував про правило, тут повинна бути "лінія". "has been presented" - це радше про "презентувався", аніж "презентував", але в українській краже вжити "зображався".
Друге речення переробив ближче до тексту, там трохи загубилося про візуальні браузери.
Щодо третього - в українському стилі зазвичай такі речі зазвичай оформлюються як безособові речення (перекладаєтсья так, щоб прибрати you), перевага надається дієсловам в інфінітиві (should do -> слід робити)
```suggestion
Історично, елемент **<hr>**,  зображався як горизонтальна лінія. Позаяк він все ще може мати вигляд горизонтальної лінії у візуальних браузерах, цей елемент тепер має більше семантичний зміст, аніж графічний. Отже, якщо потрібно просто провести горизонтальну лінію, слід робити це за допомогою відповідного CSS.
```

2021-11-28 18:23 UTC, AdriandeCita commented on files/uk/web/html/element/hr/index.md
> +          >Content categories</a
Текстові вставки всередині HTML ми також можемо перекладати. В оригінальній статті це оця табличка 
![image](https://user-images.githubusercontent.com/11510394/143780932-b857f661-3ca0-4f7f-ad6c-e788ff959775.png)
Взагалі в ідеалі ці таблички мають формуватися цілком в маркдауні, але народ з МДН іще не переробили все, тож поки чекаємо, і перекладаємо вміст всередині тегів
```suggestion
          >Категорії вмісту</a
```

2021-11-28 18:24 UTC, AdriandeCita commented on files/uk/web/html/element/hr/index.md
> +          >Flow content</a
```suggestion
          >Основний вміст</a
```

2021-11-28 18:25 UTC, AdriandeCita commented on files/uk/web/html/element/hr/index.md
> +      <th scope="row">Permitted content</th>
```suggestion
      <th scope="row">Дозволений вміст</th>
```

2021-11-28 18:25 UTC, AdriandeCita commented on files/uk/web/html/element/hr/index.md
> +      <td>None, it is an {{Glossary("empty element")}}.</td>
```suggestion
      <td>Ніякого, це {{Glossary("empty element", "порожній елемент")}}.</td>
```

2021-11-28 18:25 UTC, AdriandeCita commented on files/uk/web/html/element/hr/index.md
> +      <th scope="row">Tag omission</th>
```suggestion
      <th scope="row">Пропуск тегів</th>
```

2021-11-28 18:26 UTC, AdriandeCita commented on files/uk/web/html/element/hr/index.md
> +      <td>It must have start tag, but must not have an end tag.</td>
```suggestion
      <td>Повинен мати початковий тег, проте не повинен мати кінцевого тега.</td>
```

2021-11-28 18:26 UTC, AdriandeCita commented on files/uk/web/html/element/hr/index.md
> +      <th scope="row">Permitted parents</th>
```suggestion
      <th scope="row">Дозволені батьківські елементи</th>
```

2021-11-28 18:27 UTC, AdriandeCita commented on files/uk/web/html/element/hr/index.md
> +        Any element that accepts
```suggestion
        Будь-який елемент, який дозволяє містити
```

2021-11-28 18:27 UTC, AdriandeCita commented on files/uk/web/html/element/hr/index.md
> +        <a href="/en-US/docs/Web/Guide/HTML/Content_categories#flow_content"
```suggestion
        <a href="/uk/docs/Web/Guide/HTML/Content_categories#flow_content"
```

2021-11-28 18:27 UTC, AdriandeCita commented on files/uk/web/html/element/hr/index.md
> +          >flow content</a
```suggestion
          >основний вміст</a
```

2021-11-28 18:28 UTC, AdriandeCita commented on files/uk/web/html/element/hr/index.md
> +      <th scope="row">Implicit ARIA role</th>
```suggestion
      <th scope="row">Неявна ARIA-роль</th>
```

2021-11-28 18:28 UTC, AdriandeCita commented on files/uk/web/html/element/hr/index.md
> +      <th scope="row">Permitted ARIA roles</th>
```suggestion
      <th scope="row">Дозволені ARIA-ролі</th>
```

2021-11-28 18:29 UTC, AdriandeCita commented on files/uk/web/html/element/hr/index.md
> +        {{ARIARole("presentation")}} or {{ARIARole("none")}}
```suggestion
        {{ARIARole("presentation")}} чи {{ARIARole("none")}}
```

2021-11-28 18:29 UTC, AdriandeCita commented on files/uk/web/html/element/hr/index.md
> +      <th scope="row">DOM interface</th>
```suggestion
      <th scope="row">DOM-інтерфейс</th>
```

2021-11-28 18:36 UTC, AdriandeCita commented on files/uk/web/html/element/hr/index.md
> +This element's attributes include the [global attributes](/en-US/docs/Web/HTML/Global_attributes).
Схоже, просто не видалений артефакт після перекладу
```suggestion
```

2021-11-28 18:41 UTC, AdriandeCita commented on files/uk/web/html/element/hr/index.md
> +  - : Вирівнює обрані елементи на сторінці. Значення за замовчання — вирівнювати по лівому боку.
Там не обрані елементи, а сам елемент hr. Default ми перекладаємо як "усталено" https://webdoky.org/docs/glossary/#default-ie-by-default
```suggestion
  - : Вирівнює елемент на сторінці. Усталене значення — вирівнювати по лівому боці.
```

2021-11-28 18:43 UTC, AdriandeCita commented on files/uk/web/html/element/hr/index.md
> +  - : Визначає колір обраних елементів згідно з шістнадцятковою номенклатурою кольорів.
Те саме щодо елементів, плюс загубилися словесні позначення кольору
```suggestion
  - : Задає колір лінії шляхом вказування словесного позначення кольору, або його шістнадцяткового значення.
```

2021-11-28 18:43 UTC, AdriandeCita commented on files/uk/web/html/element/hr/index.md
> +  - : Визначає, що обрані елементи позбавлені тіні.
```suggestion
  - : Визначає, що лінія буде позбавлена тіні.
```

2021-11-28 18:44 UTC, AdriandeCita commented on files/uk/web/html/element/hr/index.md
> +  - : Встановлює висоту обраних елементів на сторінці у пікселях.
```suggestion
  - : Встановлює висоту лінії в пікселях.
```

2021-11-28 18:50 UTC, AdriandeCita commented on files/uk/web/html/element/hr/index.md
> +  - : Встановлює довжину  обраних елементів на сторінці у пікселях чи відсотках від сторінки.
Якщо ти хотіла узагальнити ці визначення на всі елементи - то це не зовсім той випадок, в даному випадку всі ці атрибути стосуються лише елемента hr. Загальні атрибути вказано вище, посилання "Global attributes".

Щодо відсотків - з оригіналу може бути не зовсім очевидно, але тут definitely не відсотки від сторінки, просто за механікою роботи відсоткових значень
```suggestion
  - : Встановлює довжину лінії на сторінці у пікселях чи відсотках.
```

2021-11-28 18:53 UTC, AdriandeCita commented on files/uk/web/html/element/hr/index.md
> +  This is the first paragraph of text.
@undead404 нещодавно започаткував гарну традицію перекладати рядки всередині кодових вставок.
```suggestion
  Це — перший абзац тексту.
```

2021-11-28 18:53 UTC, AdriandeCita commented on files/uk/web/html/element/hr/index.md
> +  This is the first paragraph of text.
```suggestion
  Це — перший абзац тексту..
```

2021-11-28 18:53 UTC, AdriandeCita commented on files/uk/web/html/element/hr/index.md
> +  This is the first paragraph of text.
```suggestion
  Це — перший абзац тексту.
```

2021-11-28 18:53 UTC, AdriandeCita commented on files/uk/web/html/element/hr/index.md
> +  This is the first paragraph of text.
```suggestion
  Це — перший абзац тексту.
```

2021-11-28 18:54 UTC, AdriandeCita commented on files/uk/web/html/element/hr/index.md
> +  This is the second paragraph of text.
```suggestion
  Це — другий абзац тексту.
```

2021-11-28 18:54 UTC, AdriandeCita commented on files/uk/web/html/element/hr/index.md
> +  This is the second paragraph of text.
```suggestion
  Це — другий абзац тексту.
```

2021-11-28 18:54 UTC, AdriandeCita commented on files/uk/web/html/element/hr/index.md
> +  This is the second paragraph of text.
```suggestion
  Це — другий абзац тексту.
```

2021-11-28 18:54 UTC, AdriandeCita commented on files/uk/web/html/element/hr/index.md
> +  This is the second paragraph of text.
```suggestion
  Це — другий абзац тексту.
```

2021-11-28 18:58 UTC, AdriandeCita commented on files/uk/web/html/element/hr/index.md
> +## Також дивиться
Для консистентності - ми тут вживаємо отакий варіант
```suggestion
## Дивіться також
```

2021-11-28 19:02 UTC, AdriandeCita commented
Круто, дякую! Маю купу зауважень, але це у всіх так, всі перші переклади зазвичай збирають багато коментарів.

Загальне побажання - ми користуємося оцим інструментом https://languagetool.org/ для автоматичної перевірки текстів, дозволяє ловити як просто помилки, так і деякі стилістичні речі. Оскільки наша версія вбудована в репозиторій і запускається з терміналу, тобі рекомендую скористатись веб-версією на їхньому вебсайті

2021-11-28 19:07 UTC, AdriandeCita commented
Навздогін до попереднього коментаря: код туди краще не вставляти, наша автоматична перевірка теж працює безпосередньо з текстом, а не розміткою. В середовищі гітхабу можна переглянути перемикатися між режимами коду і тексту за допомогою оцих кнопок
![1638126278](https://user-images.githubusercontent.com/11510394/143782308-b2cb6816-0cc0-404b-b09c-2d34e1435329.png)

2021-11-28 19:54 UTC, Keira79 commented
Я дуже дякую за комменти. Я також використовую languagetool )) В мене професійна підписка. Він не завжди все ловить в українській, але з вашою допомогою все буде добре.
Я наразі трохи запхекана з переїздом, але я з вами. Хоча може і пропала на декілька днів ))

> On 28 Nov 2021, at 21:03, Mykola Myslovskyi ***@***.***> wrote:
> 
> 
> Круто, дякую! Маю купу зауважень, але це у всіх так, всі перші переклади зазвичай збирають багато коментарів.
> 
> Загальне побажання - ми користуємося оцим інструментом https://languagetool.org/ <https://languagetool.org/> для автоматичної перевірки текстів, дозволяє ловити як просто помилки, так і деякі стилістичні речі. Оскільки наша версія вбудована в репозиторій і запускається з терміналу, тобі рекомендую скористатись веб-версією на їхньому вебсайті
> 
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub <https://github.com/webdoky/content/pull/110#issuecomment-981134841>, or unsubscribe <https://github.com/notifications/unsubscribe-auth/AWQHJTUN73SF4W7KBPEOQH3UOJ4GNANCNFSM5ICSJTLA>.
> Triage notifications on the go with GitHub Mobile for iOS <https://apps.apple.com/app/apple-store/id1477376905?ct=notification-email&mt=8&pt=524675> or Android <https://play.google.com/store/apps/details?id=com.github.android&referrer=utm_campaign%3Dnotification-email%26utm_medium%3Demail%26utm_source%3Dgithub>. 
>

2021-11-28 21:35 UTC, Keira79 commented
Дякую :)

נשלח מה-iPhone שלי

> ‫ב-28 בנוב׳ 2021, בשעה 21:54, ‏‏Keira Moore ***@***.***> כתב/ה:‬
> 
> ﻿Я дуже дякую за комменти. Я також використовую languagetool )) В мене професійна підписка. Він не завжди все ловить в українській, але з вашою допомогою все буде добре.
> Я наразі трохи запхекана з переїздом, але я з вами. Хоча може і пропала на декілька днів ))
> 
>> On 28 Nov 2021, at 21:03, Mykola Myslovskyi ***@***.***> wrote:
>> 
>> 
>> Круто, дякую! Маю купу зауважень, але це у всіх так, всі перші переклади зазвичай збирають багато коментарів.
>> 
>> Загальне побажання - ми користуємося оцим інструментом https://languagetool.org/ для автоматичної перевірки текстів, дозволяє ловити як просто помилки, так і деякі стилістичні речі. Оскільки наша версія вбудована в репозиторій і запускається з терміналу, тобі рекомендую скористатись веб-версією на їхньому вебсайті
>> 
>> —
>> You are receiving this because you authored the thread.
>> Reply to this email directly, view it on GitHub, or unsubscribe.
>> Triage notifications on the go with GitHub Mobile for iOS or Android. 
>> 
>

2021-12-09 13:16 UTC, undead404 requested changes

2021-12-09 13:16 UTC, undead404 commented on files/uk/web/html/element/hr/index.md
> +Елемент **<hr>** в [HTML](/uk/docs/Web/HTML)  відокремлює параграфи, наприклад коли змінюється сцена в історії, чи коли змінюємо тему всередині секції.
```suggestion
Елемент **<hr>** в [HTML](/uk/docs/Web/HTML) служить для розділення елементів рівня абзацу: наприклад, коли змінюється сцена в історії, чи тема всередині секції.
```
Поправив подвійний пробіл.

2022-01-24 22:46 UTC, AdriandeCita approved these changes

2022-01-24 22:46 UTC, merged