translation(CSS): web/css/css_box_model/introduction_to_the_css_box_model
webdoky/content pull request #1102
Opened 2022-12-15 12:30 UTC by undead404

Оригінальний вміст: [Introduction to the CSS basic box model@MDN](https://developer.mozilla.org/en-us/docs/Web/CSS/CSS_Box_Model/Introduction_to_the_CSS_box_model), [сирці Introduction to the CSS basic box model@GitHub](https://github.com/mdn/content/blob/main/files/en-us/web/css/css_box_model/introduction_to_the_css_box_model/index.md)

2023-01-31 20:26 UTC, AdriandeCita commented on files/uk/web/css/css_box_model/introduction_to_the_css_box_model/index.md
> +**Область вмісту**, оточена краями вмісту, вміщає "справжній" вміст елемента, як то текст, картинку чи програвач відео. Її розміри є _шириною вмісту_ (або _шириною рамки вмісту_) і \*висотою вмісту (
```suggestion
**Область вмісту**, оточена краями вмісту, вміщає "справжній" вміст елемента, як то текст, картинку чи програвач відео. Її розміри є _шириною вмісту_ (або _шириною рамки вмісту_) і _висотою вмісту_ (або _висотою рамки вмісту_). Нерідко вона має колір або зображення тла.
```

2023-01-31 20:38 UTC, AdriandeCita commented on files/uk/web/css/css_box_model/introduction_to_the_css_box_model/index.md
> +  - Values
Здається, я розумію, чому ти його пропустив... Є іще варіант "величини", але він не в'яжеться з підпунктами
```suggestion
  - Значення
```

2023-01-31 20:38 UTC, AdriandeCita requested changes
Пара зауважень

2023-02-01 06:17 UTC, undead404 commented
Прийняв пропозиції

2023-02-02 10:25 UTC, AdriandeCita approved these changes

2023-02-02 10:25 UTC, merged