translation(JS): web/javascript/reference/operators/null
webdoky/content pull request #1138
Opened 2022-12-16 10:06 UTC by undead404

Оригінальний вміст: [null@MDN](https://developer.mozilla.org/en-us/docs/Web/JavaScript/Reference/Operators/null), [сирці null@GitHub](https://github.com/mdn/content/blob/main/files/en-us/web/javascript/reference/operators/null/index.md)

2023-03-02 12:16 UTC, undead404 commented
Оновлено

2023-03-08 15:13 UTC, undead404 commented
Розв'язано конфлікт

2023-03-08 15:39 UTC, AdriandeCita commented on files/uk/web/javascript/reference/operators/null/index.md
> +{{jsxref("Global_Objects/undefined","undefined")}}. Натомість `null` виражає відсутність ідентифікації, що вказує на те, що змінна вказує на відсутність об'єкта. В API `null` нерідко повертається в т
"вказує на те, що ... вказує на"
```suggestion
{{jsxref("Global_Objects/undefined","undefined")}}. Натомість `null` виражає відсутність ідентифікації, що вказує на те, що змінна позначає відсутність об'єкта. В API `null` нерідко повертається в тих місцях, де може очікуватись об'єкт, але жодний об'єкт не знайдений.
```

2023-03-08 15:40 UTC, AdriandeCita requested changes
Дрібниця

2023-03-09 09:43 UTC, AdriandeCita approved these changes

2023-03-09 09:43 UTC, merged