update(JS): web/javascript/reference/operators/nullish_coalescing
webdoky/content pull request #1143
Opened 2022-12-18 11:00 UTC by undead404

Оригінальний вміст: [Регулярні вирази@MDN](https://developer.mozilla.org/en-us/docs/Web/JavaScript/Guide/Regular_Expressions), [сирці Регулярні вирази@GitHub](https://github.com/mdn/content/blob/main/files/en-us/web/javascript/guide/regular_expressions/index.md)

Нові зміни:
- https://github.com/mdn/content/commit/4c14928fa57a1cc6ec3a7678a7220784abbd24fa
- https://github.com/mdn/content/commit/0f248adcab759bdad247a5dbfb7da12dc32bce59
- https://github.com/mdn/content/commit/0ad08fe1d8830f11e0314733f56e391affc1fe94
- https://github.com/mdn/content/commit/c3201971442d7a84528a3ed6daee13f562b16eab
- https://github.com/mdn/content/commit/9e52d335675a9f7daa34b5e24c9b1292dbf23b2e
- https://github.com/mdn/content/commit/9a48871db490fef73eeb63ccf3ee6d37c2418df1

2023-01-05 22:02 UTC, AdriandeCita commented on files/uk/web/javascript/reference/operators/nullish_coalescing/index.md
> +Оператор null-злиття може розглядатися як особливий випадок [оператора логічного АБО (`||`)](/uk/docs/Web/JavaScript/Reference/Operators/Logical_OR). Останній повертає правий операнд, якщо лівий опер
```suggestion
Оператор null-злиття може розглядатися як особливий випадок [оператора логічного АБО (`||`)](/uk/docs/Web/JavaScript/Reference/Operators/Logical_OR). Останній повертає правий операнд, якщо лівий операнд дорівнює _будь-якому_ зі значень {{Glossary("falsy", "хибності")}}, а не лише `null` чи `undefined`. Інакше кажучи, якщо застосувати `||` для надання певній змінній усталеного значення, то можна зіткнутися з неочікуваною поведінкою, якщо частина значень хибності усе ж є корисною (наприклад, `''` або `0`). [Нижче](#prysvoiennia-zminniy-ustalenoho-znachennia) є більше прикладів.
```

2023-01-05 22:10 UTC, AdriandeCita commented on files/uk/web/javascript/reference/operators/nullish_coalescing/index.md
> +Оператор null-злиття обробляє `undefined` і `null` як особливі значення, так само як [оператор необов'язкового ланцюжка (`?.`)](/uk/docs/Web/JavaScript/Reference/Operators/Optional_chaining), котрий
```suggestion
Оператор null-злиття обробляє `undefined` і `null` як особливі значення, так само як [оператор необов'язкового ланцюжка (`?.`)](/uk/docs/Web/JavaScript/Reference/Operators/Optional_chaining), котрий є корисним для доступу до властивості об'єкта, котрий може виявитись `null` чи `undefined`. Поєднуючи їх, можна безпечно звертатися до властивості об'єкта, котра може виявитись відсутньою, і задати усталене значення на такий випадок.
```

2023-01-05 22:11 UTC, AdriandeCita requested changes
Декілька зауважень

2023-01-12 23:24 UTC, AdriandeCita commented on files/uk/web/javascript/reference/operators/nullish_coalescing/index.md
> +Не можна безпосередньо поєднувати з `??` і оператор логічного І (`&&`), і оператор логічного АБО (`||`). Така спроба призведе до викидання [синтаксичної помилки](/uk/docs/Web/JavaScript/Reference/Err
та не дуже. Але й мій варіант не звучить, тут би все речення якось переформулювати...

Отака побудова мені здається більш типовою:
```suggestion
Як оператор логічного І (`&&`), так і оператор логічного АБО (`||`) не можна безпосередньо поєднувати з `??`. Така спроба призведе до викидання [синтаксичної помилки](/uk/docs/Web/JavaScript/Reference/Errors/Cant_use_nullish_coalescing_unparenthesized).
```

Або можна іще якось виділити цей перелік:
```suggestion
Не можна безпосередньо поєднувати з `??`: оператор логічного І (`&&`) та оператор логічного АБО (`||`). Така спроба призведе до викидання [синтаксичної помилки](/uk/docs/Web/JavaScript/Reference/Errors/Cant_use_nullish_coalescing_unparenthesized).
```

2023-01-12 23:27 UTC, AdriandeCita commented on files/uk/web/javascript/reference/operators/nullish_coalescing/index.md
> +Оператор null-злиття обробляє `undefined` і `null` як особливі значення, так само як [оператор необов'язкового ланцюжка (`?.`)](/uk/docs/Web/JavaScript/Reference/Operators/Optional_chaining), котрий
Справедливо, тут я неправий. Але кінцівку давай все-одно трохи переробимо, бо ті 4 слова здаються зайвим ускладненням
```suggestion
Оператор null-злиття обробляє `undefined` і `null` як особливі значення, так само як [оператор необов'язкового ланцюжка (`?.`)](/uk/docs/Web/JavaScript/Reference/Operators/Optional_chaining), котрий є корисним для доступу до властивості об'єкта, котрий може виявитись `null` чи `undefined`. Поєднуючи їх, можна безпечно звертатися до властивості об'єкта, котрий може виявитись відсутнім, і задати усталене значення на такий випадок.
```

2023-01-21 08:33 UTC, undead404 commented
Прийнято

2023-01-29 13:07 UTC, AdriandeCita approved these changes

2023-01-29 13:07 UTC, merged