update(JS): web/javascript/reference/global_objects/number
webdoky/content pull request #1153
Opened 2022-12-18 11:53 UTC by undead404

Оригінальний вміст: [Number@MDN](https://developer.mozilla.org/en-us/docs/Web/JavaScript/Reference/Global_Objects/Number), [сирці Number@GitHub](https://github.com/mdn/content/blob/main/files/en-us/web/javascript/reference/global_objects/number/index.md)

Нові зміни:
- [mdn/content@c833d3f](https://github.com/mdn/content/commit/c833d3fa133bd8a8f3e95ab9e1122bdc6e3e1494)
- [mdn/content@effd5de](https://github.com/mdn/content/commit/effd5de5e42bfe045c3bf44b2d7b14f4d6146785)

2022-12-25 12:07 UTC, AdriandeCita commented on files/uk/web/javascript/reference/global_objects/number/index.md
> +title: Number (число)
- Немає сенсу додавати переклад у двох місцях
- В заголовку краще їх не додавати, оскільки це буде роздувати його в навігації і пошуку. Для цієї статті це неактуально, але для якоїсь "[AsyncGeneratorFunction](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/AsyncGeneratorFunction)" це може бути трохи ой
```suggestion
title: Number
```

2022-12-25 12:08 UTC, AdriandeCita requested changes
Невеличке зауваження

2022-12-25 13:52 UTC, undead404 commented
Прийнято

2023-01-02 22:31 UTC, AdriandeCita approved these changes

2023-01-02 22:32 UTC, merged