translation(JS): Web/JavaScript/Reference/Global_Objects/Object/create
webdoky/content pull request #1154
Opened 2022-12-18 18:35 UTC by AdriandeCita

Оригінальний вміст: [Object.create()@MDN](https://developer.mozilla.org/en-us/docs/Web/JavaScript/Reference/Global_Objects/Object/create), [сирці Object.create()@GitHub](https://github.com/mdn/content/blob/main/files/en-us/web/javascript/reference/global_objects/object/create/index.md)

2022-12-20 09:35 UTC, undead404 requested changes
Невелике зауваження, і чекаю interactive-examples

2023-01-03 12:17 UTC, undead404 commented
Є нові зміни https://github.com/mdn/content/commit/3f0cd840cd9575701c65b8c6a1e172a2b0c3bd62#diff-a584517afd11cd2657f856fdd07047a8646008f2060e645b5d8118e884b64ce3

2023-01-05 22:25 UTC, AdriandeCita commented on files/uk/web/javascript/reference/global_objects/object/create/index.md
> +Безперечно, якщо функція `Constructor` містить дійсний код ініціалізації — метод `Object.create()` не зможе його відобразити.
Мова в принципі не йде про запуск коду конструктора, `Object.create()` не зробить цього незалежно від того, чи той код існує. Мова йде про відображення його дії на результівному об'єкті.
Стосовно іншого - приймається, "авжеж" - справді здається кращою альтернативою. Про "actual-якийсь" так не скажу, але по змісту ок
```suggestion
Авжеж, якщо функція `Constructor` містить якийсь код ініціалізації — метод `Object.create()` не зможе його відтворити.
```

2023-01-30 22:16 UTC, AdriandeCita commented
Оновив згідно зі https://github.com/mdn/content/commit/3f0cd840cd9575701c65b8c6a1e172a2b0c3bd62#diff-a584517afd11cd2657f856fdd07047a8646008f2060e645b5d8118e884b64ce3

2023-02-08 12:02 UTC, undead404 approved these changes

2023-02-08 12:02 UTC, merged