translation(CSS): web/css/white-space
webdoky/content pull request #1155
Opened 2022-12-18 19:57 UTC by undead404

Оригінальний вміст: [white-space@MDN](https://developer.mozilla.org/en-us/docs/Web/CSS/white-space), [сирці white-space@GitHub](https://github.com/mdn/content/blob/main/files/en-us/web/css/white-space/index.md)

Залежить від:
* https://github.com/webdoky/interactive-examples/pull/63

2023-01-31 20:41 UTC, AdriandeCita commented on files/uk/web/css/white-space/index.md
> +- Чи [перекриваються](#perekryttia-probiliv), і якщо перекриваються, то як, пробіли.
Оце дуже дивна конструкція вийшла... Або треба або вставку в дужки обгорнути, або переформулювати якось так
```suggestion
- Чи [перекриваються](#perekryttia-probiliv) пробіли, і якщо перекриваються — то як.
```

2023-01-31 20:53 UTC, AdriandeCita commented on files/uk/web/css/white-space/index.md
> +- Чи може шеренга символів розірватись у точці потенційного м'якого розриву.
Властивість `white-space` призначена для роботи з текстом, тож не думаю, що є сенс узагальнювати
```suggestion
- Чи може відбутися перенос рядка у точці потенційного м'якого перенесення.
```

2023-01-31 20:58 UTC, AdriandeCita commented on files/uk/web/css/white-space/index.md
> +  - : Кілька пробілів підряд – [перекриваються](#perekryttia-probiliv). Символи нового рядка у вихідному коді обробляються як додаткові пробіли. Шеренги символів розриваються так, як необхідно для за
```suggestion
  - : Кілька пробілів підряд – [перекриваються](#perekryttia-probiliv). Символи нового рядка у вихідному коді обробляються як додаткові пробіли. Рядки розриваються так, як необхідно для заповнення їхніх рамок.
```

2023-01-31 21:06 UTC, AdriandeCita requested changes
Декілька зауважень. Я поки не горю бажанням переправляти всі шеренги, тим паче що заведена мною проблема досі висить без коментарів, але пару місць поправив, щоб було

2023-02-02 19:33 UTC, undead404 commented
Тут прийнято зауваження

2023-02-02 20:57 UTC, AdriandeCita approved these changes

2023-02-02 20:58 UTC, merged