translation(CSS): web/css/css_text/wrapping_text
webdoky/content pull request #1156
Opened 2022-12-18 20:58 UTC by undead404

Оригінальний вміст: [Wrapping and breaking text@MDN](https://developer.mozilla.org/en-us/docs/Web/CSS/CSS_Text/Wrapping_Text), [сирці Wrapping and breaking text@GitHub](https://github.com/mdn/content/blob/main/files/en-us/web/css/css_text/wrapping_text/index.md)

Залежить від:
* https://github.com/webdoky/css-examples/pull/1

2023-02-01 23:21 UTC, AdriandeCita commented on files/uk/web/css/css_text/wrapping_text/index.md
> +Альтернативна властивість, котру можна спробувати – {{cssxref("word-break")}}. Вона розриває слово у тій точці, в якій починається переповнення. Це призводить до break-even, якщо розміщення слова на
```suggestion
Альтернативна властивість, котру можна спробувати – {{cssxref("word-break")}}. Вона розриває слово у тій точці, в якій починається переповнення. Вона також збереже його цілим, якщо розміщення слова на новому рядку дозволить показати його без розриву.
```

2023-02-01 23:27 UTC, AdriandeCita commented on files/uk/web/css/css_text/wrapping_text/index.md
> +Для додавання дефісів при розриві слів, слід застосувати властивість CSS {{cssxref("hyphens")}}. При застосуванні значення `auto` браузер вільний автоматично розривати слова у відповідних точках для
Дивне формулювання, може складатися враження, що вони ледь не рандомом обираються. Трохи переформулював, щоб ближче до оригіналу було.
```suggestion
Для додавання дефісів при розриві слів, слід застосувати властивість CSS {{cssxref("hyphens")}}. При застосуванні значення `auto` браузер вільний автоматично розривати слова у відповідних точках для дефісів, згідно з будь-якими правилами, які він обере. Щоб мати якийсь контроль над цим процесом, можна задати значення `manual`, а тоді вставити в рядок символ жорсткого або м'якого розриву. Жорсткий розрив (`‐`) завжди відбудеться, навіть коли це не обов'язково. М'який розрив (`&shy;`) відбувається лише тоді, коли розрив потрібен.
```

2023-02-01 23:29 UTC, AdriandeCita requested changes
Пара зауважень

2023-02-02 19:33 UTC, undead404 commented
Тут прийнято зауваження

2023-02-02 20:59 UTC, AdriandeCita approved these changes

2023-02-02 20:59 UTC, merged