translation(JS): Web/JavaScript/Reference/Global_Objects/Object/toString
webdoky/content pull request #1157
Opened 2022-12-18 21:21 UTC by AdriandeCita

Оригінальний вміст: [Object.prototype.toString()@MDN](https://developer.mozilla.org/en-us/docs/Web/JavaScript/Reference/Global_Objects/Object/toString), [сирці Object.prototype.toString()@GitHub](https://github.com/mdn/content/blob/main/files/en-us/web/javascript/reference/global_objects/object/tostring/index.md)

2022-12-20 09:43 UTC, undead404 requested changes
Є трохи неузгодженості, і чекаю на interactive-examples

2022-12-20 09:43 UTC, undead404 commented on files/uk/web/javascript/reference/global_objects/object/tostring/index.md
> +Усталено метод `toString()` не приймає аргументів. Проте, об'єкти, які успадковують від `Object`, можуть заміщати його власними реалізаціями, що приймають аргументи. До прикладу, методи [`Number.prot
```suggestion
Усталено метод `toString()` не приймає аргументів. Проте об'єкти, які успадковують від `Object`, можуть заміщати його власними реалізаціями, що приймають аргументи. До прикладу, методи [`Number.prototype.toString()`](/uk/docs/Web/JavaScript/Reference/Global_Objects/Number/toString) і [`BigInt.prototype.toString()`](/uk/docs/Web/JavaScript/Reference/Global_Objects/BigInt/toString) приймають необов'язковий параметр `radix`.
```

2022-12-20 09:43 UTC, undead404 commented on files/uk/web/javascript/reference/global_objects/object/tostring/index.md
> +Аби застосувати базовий метод `Object.prototype.toString()` на об'єкті, в якому його було заміщено (або звернутися до нього на значеннях `null` чи `undefined`), слід на ньому викликати {{jsxref("Func
Трохи неясно, на кому - на ньому

```suggestion
Аби застосувати базовий метод `Object.prototype.toString()` на об'єкті, в якому його було заміщено (або звернутися до нього на значеннях `null` чи `undefined`), слід на такому методі викликати {{jsxref("Function.prototype.call()")}} чи {{jsxref("Function.prototype.apply()")}}, передавши першим параметром (називається `thisArg`) об'єкт, який потрібно дослідити.
```

2022-12-20 09:43 UTC, undead404 commented on files/uk/web/javascript/reference/global_objects/object/tostring/index.md
> +Об'єкт [`arguments`](/uk/docs/Web/JavaScript/Reference/Functions/arguments) повертає `"[object Arguments]"`. Всі інші, включно з означеними користувачем класами, повертатиме `"[object Object]"` (якщо
```suggestion
Об'єкт [`arguments`](/uk/docs/Web/JavaScript/Reference/Functions/arguments) повертає `"[object Arguments]"`. Всі інші, включно з означеними користувачем класами, повертатимуть `"[object Object]"` (якщо не матимуть власного `Symbol.toStringTag`).
```

2022-12-20 09:43 UTC, undead404 commented on files/uk/web/javascript/reference/global_objects/object/tostring/index.md
> +З урахуванням попереднього коду, кожного разу коли примірник класу `Dog` вживається в рядковому контексті, JavaScript автоматично викличе метод `toString()`.
```suggestion
З урахуванням попереднього коду, кожного разу, коли примірник класу `Dog` вживається в рядковому контексті, JavaScript автоматично викличе метод `toString()`.
```

2023-01-30 20:08 UTC, AdriandeCita commented
Прийняв всі

2023-01-30 21:06 UTC, undead404 approved these changes

2023-01-30 21:07 UTC, merged