update(JS): web/javascript/reference/global_objects/json/stringify
webdoky/content pull request #1158
Opened 2022-12-22 10:03 UTC by undead404

Оригінальний вміст: [JSON.stringify()@MDN](https://developer.mozilla.org/en-us/docs/Web/JavaScript/Reference/Global_Objects/JSON/stringify), [сирці JSON.stringify()@GitHub](https://github.com/mdn/content/blob/main/files/en-us/web/javascript/reference/global_objects/json/stringify/index.md)

Нові зміни:
- [mdn/content@e5806fd](https://github.com/mdn/content/commit/e5806fd2c97e2ee5fb9a822fd9482aacc42bbd44)

2022-12-25 12:13 UTC, AdriandeCita commented on files/uk/web/javascript/reference/global_objects/json/stringify/index.md
> +  - : Функція, яка змінює поведінку процесу перетворення значення на рядок, або ж масив із рядків і чисел, котрий задає властивості `value` до включення у вивід. Якщо цей параметр є масивом, то всі е
Попередній переклад вже був конкретніший, ніж попередній оригінал)
```suggestion
  - : Функція, яка змінює поведінку процесу перетворення значення на рядок, або ж масив із рядків і чисел, котрий задає властивості `value` до включення у вивід. Якщо цей параметр є масивом, то всі ті його елементи, котрі не є ані рядками, ані числами (в т.ч. як примітивами, так об'єктами-обгортками), включно зі значеннями {{jsxref("Symbol")}}, цілковито ігноруються. Якщо цей параметр не є ані функцією, ані масивом (наприклад, дорівнює [`null`](/uk/docs/Web/JavaScript/Reference/Operators/null) або просто не заданий), то в отриманий рядок будуть включені всі властивості об'єкта, котрі мають рядкові ключі.
```

2022-12-25 12:17 UTC, AdriandeCita requested changes
дрібничка

2022-12-25 13:51 UTC, undead404 commented
Прийнято

2023-01-02 19:49 UTC, undead404 commented
Оновлено

2023-01-02 22:28 UTC, AdriandeCita approved these changes

2023-01-02 22:28 UTC, merged