translation(JS): Web/JavaScript/Reference/Global_Objects/Object/defineProperty
webdoky/content pull request #1163
Opened 2022-12-23 11:47 UTC by AdriandeCita

Оригінальний вміст: [Object.defineProperty()@MDN](https://developer.mozilla.org/en-us/docs/Web/JavaScript/Reference/Global_Objects/Object/defineProperty), [сирці Object.defineProperty()@GitHub](https://github.com/mdn/content/blob/main/files/en-us/web/javascript/reference/global_objects/object/defineproperty/index.md)

2022-12-24 19:09 UTC, undead404 requested changes

2022-12-24 19:09 UTC, undead404 commented on files/uk/web/javascript/reference/global_objects/object/defineproperty/index.md
> +Коли його значенням встановлено `false`, проте атрибут `writable` дорівнює `true` — `value` все ще можна змінювати, і `writable` все ще можна перемкнути з `true` на `false`. Коли його значення дорівн
```suggestion
Коли його значенням встановлено `false`, проте атрибут `writable` дорівнює `true` — `value` все ж можна змінювати, і `writable` все ще можна перемкнути з `true` на `false`. Коли його значення дорівнює `true`, а `writable` — `false`, — то `value` все ж можна замінити за допомогою `defineProperty` (проте не операторами присвоєння), і сам атрибут `writable` можна перемкнути.
```

2022-12-24 19:09 UTC, undead404 commented on files/uk/web/javascript/reference/global_objects/object/defineproperty/index.md
> +}); // викидає TypeError // ('value' можна змінювати із 'configurable' встановленим у false, проте не в цьому випадку, через наявність аксесора 'get')
```suggestion
}); // викидає TypeError // ('value' можна змінювати із 'configurable', встановленим у false, проте не в цьому випадку, через наявність аксесора 'get')
```

2022-12-24 19:09 UTC, undead404 commented on files/uk/web/javascript/reference/global_objects/object/defineproperty/index.md
> +Важливо розуміти, яким чином застосовуються усталені значення атрибутів. Часто існує певна відмінність між застосуванням запису через крапку для присвоєння значення, і вживання методу `Object.defineP
```suggestion
Важливо розуміти, яким чином застосовуються усталені значення атрибутів. Нерідко існує певна відмінність між застосуванням запису через крапку для присвоєння значення, і вживанням методу `Object.defineProperty()`, як проілюстровано у прикладі нижче.
```

2022-12-24 19:09 UTC, undead404 commented on files/uk/web/javascript/reference/global_objects/object/defineproperty/index.md
> +### Власті гетери й сетери
Думаю, "власні" тут – надто загальне слово
```suggestion
### Самописні гетери й сетери
```

2022-12-24 19:09 UTC, undead404 commented on files/uk/web/javascript/reference/global_objects/object/defineproperty/index.md
> +Це можна виправити, якщо зберігати значення всередині іншої властивості. Всередині методів `get` та `set`, значення `this` вказує на об'єкт, який було використано для доступу чи зміни властивості.
```suggestion
Це можна виправити, якщо зберігати значення всередині іншої властивості. Всередині методів `get` та `set` значення `this` вказує на об'єкт, який було використано для доступу чи зміни властивості.
```

2022-12-24 19:09 UTC, undead404 commented on files/uk/web/javascript/reference/global_objects/object/defineproperty/index.md
> +На відміну від аксесорних властивостей, значення властивостей даних завжди встановлюються на самому об'єкті, а не на його прототипі. Проте, якщо успадковується незаписувана властивість, це продовжить
```suggestion
На відміну від аксесорних властивостей, значення властивостей даних завжди встановлюються на самому об'єкті, а не на його прототипі. Проте, якщо успадковується незаписувана властивість, то це перешкодить внесенням змін до неї на дочірньому об'єкті.
```

2023-01-30 20:28 UTC, AdriandeCita commented on files/uk/web/javascript/reference/global_objects/object/defineproperty/index.md
> +### Власті гетери й сетери
"Самописні" мені здається суттєво гіршою альтернативою, бо це:
- завузький термін, прив'язаний до контексту написання, що не завжди доречно;
- більше підходить для позначення чогось, що само себе пише (так, на найближчому СНД склалася певна традиція називати "самописними" написані самостійно інструменти, але я маю певні сумніви в її доречності).
Пропоную натомість додати більше контексту до заголовка в цілому:
```suggestion
### Застосування власних гетерів і сетерів
```

2023-01-30 21:08 UTC, undead404 approved these changes

2023-01-30 21:08 UTC, merged