translation(JS): Web/JavaScript/Reference/Global_Objects/Object/is
webdoky/content pull request #1169
Opened 2022-12-24 15:11 UTC by AdriandeCita

Оригінальний вміст: [Object.is()@MDN](https://developer.mozilla.org/en-us/docs/Web/JavaScript/Reference/Global_Objects/Object/is), [сирці Object.is()@GitHub](https://github.com/mdn/content/blob/main/files/en-us/web/javascript/reference/global_objects/object/is/index.md)

2022-12-24 19:17 UTC, undead404 requested changes

2022-12-24 19:17 UTC, undead404 commented on files/uk/web/javascript/reference/global_objects/object/is/index.md
> +Метод **`Object.is()`** визначає, чи два передані значення є насправді [одним значенням](/uk/docs/Web/JavaScript/Equality_comparisons_and_sameness#same-value_equality_using_object.is).
```suggestion
Метод **`Object.is()`** визначає, чи два передані значення є насправді [одним значенням](/uk/docs/Web/JavaScript/Equality_comparisons_and_sameness#rivnist-odnoho-znachennia-za-dopomohoiu-object-is).
```

2022-12-24 19:17 UTC, undead404 commented on files/uk/web/javascript/reference/global_objects/object/is/index.md
> +Метод `Object.is()` визначає, чи являються два передані значення [одним](/uk/docs/Web/JavaScript/Equality_comparisons_and_sameness#same-value_equality_using_object.is). Два значення вважаються одним,
```suggestion
Метод `Object.is()` визначає, чи є два передані значення [одним і тим же значенням](/uk/docs/Web/JavaScript/Equality_comparisons_and_sameness#rivnist-odnoho-znachennia-za-dopomohoiu-object-is). Два значення вважаються одним і тим же, якщо виконується одна з наведених нижче умов:
```

2022-12-24 19:17 UTC, undead404 commented on files/uk/web/javascript/reference/global_objects/object/is/index.md
> +- обидва дорівнюють {{jsxref("undefined")}}
```suggestion
- обидва вони – {{jsxref("undefined")}}
```

2022-12-24 19:17 UTC, undead404 commented on files/uk/web/javascript/reference/global_objects/object/is/index.md
> +- обидва дорівнюють [`null`](/uk/docs/Web/JavaScript/Reference/Operators/null)
```suggestion
- обидва вони – [`null`](/uk/docs/Web/JavaScript/Reference/Operators/null)
```

2022-12-24 19:17 UTC, undead404 commented on files/uk/web/javascript/reference/global_objects/object/is/index.md
> +- обидва `true` чи обидва `false`
```suggestion
- обидва `true`, чи обидва `false`
```

2022-12-24 19:17 UTC, undead404 commented on files/uk/web/javascript/reference/global_objects/object/is/index.md
> +- обидва дорівнюють одному об'єкту (тобто обидва значення посилаються на один об'єкт в пам'яті)
```suggestion
- обидва є одним і тим же об'єктом (тобто обидва значення посилаються на один об'єкт в пам'яті)
```

2022-12-24 19:17 UTC, undead404 commented on files/uk/web/javascript/reference/global_objects/object/is/index.md
> +`Object.is()` не є еквівалентом оператору [`==`](/uk/docs/Web/JavaScript/Reference/Operators/Equality). Оператор `==` застосовує різноманітні зведення до операндів з кожного боку (якщо вони не є знач
```suggestion
`Object.is()` не є еквівалентом оператору [`==`](/uk/docs/Web/JavaScript/Reference/Operators/Equality). Оператор `==` застосовує різноманітні зведення типів до операндів з обох боків (якщо вони не є значеннями одного типу) перед перевіркою на рівність (що призводить до такої поведінки, як істинність виразу `"" == false`), натомість метод `Object.is()` не виконує зведення жодного значення.
```

2022-12-24 19:17 UTC, undead404 commented on files/uk/web/javascript/reference/global_objects/object/is/index.md
> +`Object.is()` також _не_ еквівалентний оператору [`===`](/uk/docs/Web/JavaScript/Reference/Operators/Strict_equality). Єдиною відмінністю між `Object.is()` та `===` є їхнє ставлення до нулів зі знака
```suggestion
`Object.is()` також _не_ еквівалентний оператору [`===`](/uk/docs/Web/JavaScript/Reference/Operators/Strict_equality). Єдиною відмінністю між `Object.is()` та `===` є їхнє ставлення до нулів зі знаками, а також значень `NaN`. Оператор `===` (як і оператор `==`) сприймає числові значення `-0` та `+0` як рівні, проте вважає значення {{jsxref("NaN")}} не рівними між собою.
```

2022-12-25 11:39 UTC, AdriandeCita commented on files/uk/web/javascript/reference/global_objects/object/is/index.md
> +`Object.is()` також _не_ еквівалентний оператору [`===`](/uk/docs/Web/JavaScript/Reference/Operators/Strict_equality). Єдиною відмінністю між `Object.is()` та `===` є їхнє ставлення до нулів зі знака
Чим "вважає" краще за "сприймає"?
Я послуговувався тією логікою, що функція не може мати власної думки, тому щось "вважати" їй не притаманно

2022-12-25 11:43 UTC, AdriandeCita commented on files/uk/web/javascript/reference/global_objects/object/is/index.md
> +Метод **`Object.is()`** визначає, чи два передані значення є насправді [одним значенням](/uk/docs/Web/JavaScript/Equality_comparisons_and_sameness#same-value_equality_using_object.is).
який сенс давати якір на заголовок, якого не існує, якщо немає гарантії, що він залишиться актуальним після її перекладу?

2022-12-25 11:54 UTC, AdriandeCita commented on files/uk/web/javascript/reference/global_objects/object/is/index.md
> +Метод **`Object.is()`** визначає, чи два передані значення є насправді [одним значенням](/uk/docs/Web/JavaScript/Equality_comparisons_and_sameness#same-value_equality_using_object.is).
прийму щоб не роздувати дискусію

2023-01-03 12:20 UTC, undead404 commented on files/uk/web/javascript/reference/global_objects/object/is/index.md
> +`Object.is()` також _не_ еквівалентний оператору [`===`](/uk/docs/Web/JavaScript/Reference/Operators/Strict_equality). Єдиною відмінністю між `Object.is()` та `===` є їхнє ставлення до нулів зі знака
Я мав на увазі неузгодженість. Тоді пропоную такий варіант
```suggestion
`Object.is()` також _не_ еквівалентний оператору [`===`](/uk/docs/Web/JavaScript/Reference/Operators/Strict_equality). Єдиною відмінністю між `Object.is()` та `===` є їхнє ставлення до нулів зі знаками, а також значень `NaN`. Оператор `===` (як і оператор `==`) сприймає числові значення `-0` та `+0` як рівні, однак значення {{jsxref("NaN")}} – як не рівні між собою.
```

2023-01-03 12:21 UTC, undead404 commented
Нові зміни: https://github.com/mdn/content/commit/3f0cd840cd9575701c65b8c6a1e172a2b0c3bd62#diff-b60dc8ee9c06d122dde87f5dffb659a1aa9b2e02108f74caee8de9f44ad4ec17

2023-01-30 22:18 UTC, AdriandeCita commented on files/uk/web/javascript/reference/global_objects/object/is/index.md
> +`Object.is()` також _не_ еквівалентний оператору [`===`](/uk/docs/Web/JavaScript/Reference/Operators/Strict_equality). Єдиною відмінністю між `Object.is()` та `===` є їхнє ставлення до нулів зі знака
ааа, точно, "сприймає... сприймає", має сенс, дякую

2023-01-30 22:20 UTC, AdriandeCita commented
Оновив згідно з https://github.com/mdn/content/commit/3f0cd840cd9575701c65b8c6a1e172a2b0c3bd62#diff-b60dc8ee9c06d122dde87f5dffb659a1aa9b2e02108f74caee8de9f44ad4ec17

2023-02-08 12:02 UTC, undead404 commented
Іще одне оновлення https://github.com/mdn/content/commit/1c70095257ba7f6d1195d1d33340e234dfc80b3e

2023-03-09 13:50 UTC, undead404 commented
Іще одне https://github.com/mdn/content/commit/fcd80ee4c8477b6f73553bfada841781cf74cf46

2024-08-10 13:40 UTC, kant2002 commented on files/uk/web/javascript/reference/global_objects/object/is/index.md
> +Статичний метод **`Object.is()`** визначає, чи два передані значення є насправді [одним значенням](/uk/docs/Web/JavaScript/Equality_comparisons_and_sameness#rivnist-odnoho-znachennia-za-dopomohoiu-ob
```suggestion
Статичний метод **`Object.is()`** визначає, чи два передані значення насправді є [одним значенням](/uk/docs/Web/JavaScript/Equality_comparisons_and_sameness#rivnist-odnoho-znachennia-za-dopomohoiu-object-is).
```

2024-08-10 13:41 UTC, kant2002 commented on files/uk/web/javascript/reference/global_objects/object/is/index.md
> +Метод `Object.is()` визначає, чи є два передані значення [одним і тим же значенням](/uk/docs/Web/JavaScript/Equality_comparisons_and_sameness#rivnist-odnoho-znachennia-za-dopomohoiu-object-is). Два з
```suggestion
Метод `Object.is()` визначає, чи є два передані значення [одним і тим же значенням](/uk/docs/Web/JavaScript/Equality_comparisons_and_sameness#rivnist-odnoho-znachennia-za-dopomohoiu-object-is). Два значення вважаються одним і тим же значенням, якщо виконується одна з наведених нижче умов:
```

2024-08-10 13:43 UTC, kant2002 commented on files/uk/web/javascript/reference/global_objects/object/is/index.md
> +- обидва вони – {{jsxref("undefined")}}
```suggestion
- обидва значення – {{jsxref("undefined")}}
```

2024-08-10 13:43 UTC, kant2002 commented on files/uk/web/javascript/reference/global_objects/object/is/index.md
> +- обидва вони – [`null`](/uk/docs/Web/JavaScript/Reference/Operators/null)
```suggestion
- обидва значення – [`null`](/uk/docs/Web/JavaScript/Reference/Operators/null)
```

2024-08-10 13:43 UTC, kant2002 commented on files/uk/web/javascript/reference/global_objects/object/is/index.md
> +- обидва `true`, чи обидва `false`
```suggestion
- обидва значення `true`, чи обидва `false`
```

2024-08-10 13:44 UTC, kant2002 commented on files/uk/web/javascript/reference/global_objects/object/is/index.md
> +- обидва є рядками однакової довжини, з однаковими символами та в однаковій послідовності
```suggestion
- обидва значення є рядками однакової довжини, з однаковими символами та в однаковій послідовності
```

2024-08-10 13:44 UTC, kant2002 commented on files/uk/web/javascript/reference/global_objects/object/is/index.md
> +- обидва є одним і тим же об'єктом (тобто обидва значення посилаються на один об'єкт в пам'яті)
```suggestion
- обидва значення є одним і тим же об'єктом (тобто обидва значення посилаються на один об'єкт в пам'яті)
```

2024-08-10 13:46 UTC, kant2002 commented on files/uk/web/javascript/reference/global_objects/object/is/index.md
> +`Object.is()` також _не_ еквівалентний оператору [`===`](/uk/docs/Web/JavaScript/Reference/Operators/Strict_equality). Єдиною відмінністю між `Object.is()` та `===` є їхнє ставлення до нулів зі знака
```suggestion
`Object.is()` також _не_ еквівалентний оператору [`===`](/uk/docs/Web/JavaScript/Reference/Operators/Strict_equality). Єдиною відмінністю між `Object.is()` та `===` є їх ставлення до нулів зі знаками, а також значень `NaN`. Оператор `===` (як і оператор `==`) сприймає числові значення `-0` та `+0` як рівні, однак значення {{jsxref("NaN")}} – як не рівні між собою.
```

2024-08-10 13:47 UTC, kant2002 commented
Мабуть треба було у одному ревью зробити, вибачаюся. В цілому там багато однотипних речей.

2024-08-16 13:33 UTC, undead404 commented
Переклали з нуля
https://github.com/webdoky/content/pull/3309

2024-08-16 13:33 UTC, closed without merging