update(HTML): web/html/element/script
webdoky/content pull request #1171
Opened 2022-12-24 15:47 UTC by undead404

Оригінальний вміст: [&lt;script>: Елемент сценарію@MDN](https://developer.mozilla.org/en-us/docs/Web/HTML/Element/script), [сирці &lt;script>: Елемент сценарію@GitHub](https://github.com/mdn/content/blob/main/files/en-us/web/html/element/script/index.md)

Нові зміни:
- [mdn/content@8a72e8b](https://github.com/mdn/content/commit/8a72e8bc250e2b5d51e17bd59bc94300849c14b5)

2023-01-21 08:54 UTC, undead404 commented
Оновлено

2023-01-29 14:44 UTC, AdriandeCita commented on files/uk/web/html/element/script/index.md
> +        На відміну від класичних, модульні сценарії вимагають для отримання з іншого походження використання протоколу CORS.
тут виділяється підрядне речення
```suggestion
        На відміну від класичних, модульні сценарії вимагають, для отримання з іншого походження, використання протоколу CORS.
```

2023-01-29 14:57 UTC, AdriandeCita requested changes
Дрібниця щодо ком. Я завис над відображеннями, але так і не придумав нічого кращого, тож най поки буде.

2023-01-29 17:07 UTC, undead404 commented
Прийнято

2023-01-29 18:52 UTC, AdriandeCita approved these changes

2023-01-29 18:52 UTC, merged