update(JS): web/javascript/guide/modules
webdoky/content pull request #1172
Opened 2022-12-24 22:00 UTC by undead404

Оригінальний вміст: [Модулі JavaScript@MDN](https://developer.mozilla.org/en-us/docs/Web/JavaScript/Guide/Modules), [сирці Модулі JavaScript@GitHub](https://github.com/mdn/content/blob/main/files/en-us/web/javascript/guide/modules/index.md)

Нові зміни:
- [mdn/content@8a72e8b](https://github.com/mdn/content/commit/8a72e8bc250e2b5d51e17bd59bc94300849c14b5)
- [mdn/content@effd5de](https://github.com/mdn/content/commit/effd5de5e42bfe045c3bf44b2d7b14f4d6146785)

2023-01-21 09:04 UTC, undead404 commented
Оновлено

2023-01-29 21:29 UTC, AdriandeCita commented on files/uk/web/javascript/guide/modules/index.md
> +Проте тут натомість вжито синтаксис крапки (`.`), котра вказує на "поточне розташування", після крапки ж – решта шляху до шуканого файлу. Це набагато краще за написання щоразу всього відносного шляху
```suggestion
Проте тут натомість вжито синтаксис крапки (`.`), котра вказує на "поточне розташування", після крапки ж – решта шляху до шуканого файлу. Це набагато краще за написання щоразу всього абсолютного шляху, адже так коротше, і так URL стає більш переносним: приклад все одно працюватиме, якщо перенести його в інше місце в ієрархії сайту.
```

2023-01-29 21:40 UTC, AdriandeCita commented on files/uk/web/javascript/guide/modules/index.md
> +[Карти імпортування](/uk/docs/Web/HTML/Element/script/type/importmap) дають розробникам змогу натомість задати майже будь-який текст, який завгодно, у модульному специфікаторі при імпорті модуля; кар
Комбінація "майже будь-який" і "який завгодно" звучить дивно. Кращого перекладу для того шматка у мене немає, проте можна його просто опустити без втрати змісту
```suggestion
[Карти імпортування](/uk/docs/Web/HTML/Element/script/type/importmap) дають розробникам змогу натомість задати майже будь-який текст у модульному специфікаторі при імпорті модуля; карта надає відповідне значення, котре замінить текст при розв'язанні URL модуля.
```

2023-01-29 21:49 UTC, AdriandeCita commented on files/uk/web/javascript/guide/modules/index.md
> +Якщо в кінці ключа – модульного специфікатора немає скісної риски, то увесь такий ключ дає збіг і замінюється.
Тут краще або не виділяти взагалі, або виділяти з обох боків
```suggestion
Якщо в кінці ключа – модульного специфікатора – немає скісної риски, то увесь такий ключ дає збіг і замінюється.
```

2023-01-29 21:54 UTC, AdriandeCita commented on files/uk/web/javascript/guide/modules/index.md
> +Можна імпортувати `fp` вище і без розширення файлу `.js`, але для цього довелось би створити простий ключ – модульний специфікатор для цього файлу, як то `lodash/fp`, а не використовувати шлях до ньо
```suggestion
Можна імпортувати `fp` вище і без розширення файлу `.js`, але для цього довелось би створити простий ключ – модульний специфікатор – для цього файлу, як то `lodash/fp`, а не використовувати шлях до нього.
```

2023-01-29 21:59 UTC, AdriandeCita commented on files/uk/web/javascript/guide/modules/index.md
> +Можна імпортувати `fp` вище і без розширення файлу `.js`, але для цього довелось би створити простий ключ – модульний специфікатор для цього файлу, як то `lodash/fp`, а не використовувати шлях до ньо
Думаю, тут можна було б використовувати іще щось таке. Це несе дещо іншу семантику, але я поки не зовсім розумію, чи це погано)
```suggestion
Можна імпортувати `fp` вище і без розширення файлу `.js`, але для цього довелось би створити простий ключ модульного специфікатора для цього файлу, як то `lodash/fp`, а не використовувати шлях до нього.
```

2023-01-29 22:01 UTC, AdriandeCita commented on files/uk/web/javascript/guide/modules/index.md
> +Ключ – модульний специфікатор не обов'язково повинен бути шляхом – він також може бути абсолютним URL (або подібним до URL відносним шляхом, як то `./`, `../`, `/`).
Проблема  з таким записом в тому, що вираз "модульний специфікатор не обов'язково повинен бути шляхом" сприймається як окрема вставна конструкція всередині "Ключ ... він також може бути", і тільки після другого тире ти розумієш, що прочитав щось дивне

2023-01-29 22:07 UTC, AdriandeCita commented on files/uk/web/javascript/guide/modules/index.md
> +Карти імпортування дають змогу імпортувати модулі за допомогою простих імен модулів (як в Node.js), а також імітують імпортування модулів з пакетів, як з розширеннями файлів, так і без них.
Досі ми перекладали "package" як "пакунок". Здається, ми це ніяк в глосарії не закріплювали, тож може бути й пакет, але треба буде проконтролювати консистентність

2023-01-29 22:15 UTC, AdriandeCita requested changes
Є трохи зауважень

2023-01-30 10:02 UTC, undead404 commented on files/uk/web/javascript/guide/modules/index.md
> +Ключ – модульний специфікатор не обов'язково повинен бути шляхом – він також може бути абсолютним URL (або подібним до URL відносним шляхом, як то `./`, `../`, `/`).
```suggestion
Ключ – модульний специфікатор не обов'язково повинен бути шляхом: він також може бути абсолютним URL (або подібним до URL відносним шляхом, як то `./`, `../`, `/`).
```
Тут насправді більш доречна двокрапка.

2023-01-30 10:02 UTC, undead404 commented
Дещо прийняв, на дещо дав свою пропозицію

2023-01-30 20:05 UTC, AdriandeCita commented on files/uk/web/javascript/guide/modules/index.md
> +Ключ – модульний специфікатор не обов'язково повинен бути шляхом – він також може бути абсолютним URL (або подібним до URL відносним шляхом, як то `./`, `../`, `/`).
так, але шматок між тире і двокрапкою продовжує сприйматися як цілісна річ, що не зовсім відповідає початковому змістові.
```suggestion
Ключ – модульний специфікатор – не обов'язково повинен бути шляхом: він також може бути абсолютним URL (або подібним до URL відносним шляхом, як то `./`, `../`, `/`).
```

2023-01-30 21:40 UTC, AdriandeCita approved these changes

2023-01-30 21:40 UTC, merged