translation(JS): web/javascript/reference/operators/await
webdoky/content pull request #1193
Opened 2022-12-27 00:14 UTC by undead404

Оригінальний вміст: [await@MDN](https://developer.mozilla.org/en-us/docs/Web/JavaScript/Reference/Operators/await), [сирці await@GitHub](https://github.com/mdn/content/blob/main/files/en-us/web/javascript/reference/operators/await/index.md)

2023-01-03 10:53 UTC, undead404 commented
Оновлено

2023-02-02 09:11 UTC, undead404 commented
Розв'язано конфлікт

2023-02-02 22:28 UTC, AdriandeCita commented on files/uk/web/javascript/reference/operators/await/index.md
> +Це за умови, що `promisedFunction()` ніколи не викидає синхронної помилки, а щоразу повертає відхилений проміс. Так це працює в більшості як слід спроєктованих функціях на основі промісів, котрі зазв
```suggestion
Це за умови, що `promisedFunction()` ніколи не викидає синхронної помилки, а щоразу повертає відхилений проміс. Так це працює в більшості як слід спроєктованих функцій на основі промісів, котрі зазвичай мають такий вигляд:
```

2023-02-02 22:35 UTC, AdriandeCita requested changes
Невеличке зауваження

2023-02-03 08:21 UTC, undead404 commented
Прийняв пропозицію

2023-02-05 22:49 UTC, merged