translation(JS): web/javascript/guide/regular_expressions/cheatsheet
webdoky/content pull request #1214
Opened 2023-01-04 12:06 UTC by undead404

Оригінальний вміст: [Regular expression syntax cheatsheet@MDN](https://developer.mozilla.org/en-us/docs/Web/JavaScript/Guide/Regular_Expressions/Cheatsheet), [сирці Regular expression syntax cheatsheet@GitHub](https://github.com/mdn/content/blob/main/files/en-us/web/javascript/guide/regular_expressions/cheatsheet/index.md)

2023-01-10 08:20 UTC, undead404 commented
Оновлено

2023-02-04 10:01 UTC, AdriandeCita commented on files/uk/web/javascript/guide/regular_expressions/cheatsheet/index.md
> +            Для символів, котрі зазвичай сприймаються по-особливому, вказує, що наступний символ не є спеціальним і повинен тлумачитись буквально. Наприклад, "*" – спеціальний символ, котрий збіг з 0
```suggestion
            Для символів, котрі зазвичай сприймаються по-особливому, вказує, що наступний символ не є спеціальним і повинен тлумачитись буквально. Наприклад, "*" – спеціальний символ, котрий збіг з 0 або більше входженнями символу перед ним; наприклад, <code>/a*/</code> означає 0 або більше входжень літери "a". Щоб отримати збіг буквально з <code>*</code>, перед нею треба поставити зворотну скісну риску; наприклад, <code>/a\*/</code> дасть збіг з "a*".
```

2023-02-04 10:09 UTC, AdriandeCita commented on files/uk/web/javascript/guide/regular_expressions/cheatsheet/index.md
> +            >позначкою Unicode</a> вони призводять до помилки <em>invalid identity escape</em> (недійсне самоекранування). Так зроблено для надійної зворотної сумісності з наявним кодом, котрий викор
Думаю, тут радше мається на увазі щось таке
```suggestion
            >позначкою Unicode</a> вони призводять до помилки <em>invalid identity escape</em> (недійсна екранована одиниця). Так зроблено для надійної зворотної сумісності з наявним кодом, котрий використовує нові послідовності екранування, наприклад, <code>\p</code> чи <code>\k</code>.
```

2023-02-04 10:17 UTC, AdriandeCita commented on files/uk/web/javascript/guide/regular_expressions/cheatsheet/index.md
> +[Судження](/uk/docs/Web/JavaScript/Guide/Regular_Expressions/Assertions) включають межі, котрі позначають початок і кінець рядків та слів, а також інші патерни, котрі в певний спосіб позначають те, щ
мені подобаються ці "визиральними, озиральними", але я їх ніде не зустрічав. Я додам їх у обговорення, бо конкретних лаконічних альтернатив у мене наразі немає

2023-02-04 10:23 UTC, AdriandeCita commented on files/uk/web/javascript/guide/regular_expressions/cheatsheet/index.md
> +[Судження](/uk/docs/Web/JavaScript/Guide/Regular_Expressions/Assertions) включають межі, котрі позначають початок і кінець рядків та слів, а також інші патерни, котрі в певний спосіб позначають те, щ
https://github.com/webdoky/content/issues/1290

2023-02-04 10:39 UTC, AdriandeCita commented on files/uk/web/javascript/guide/regular_expressions/cheatsheet/index.md
> +[Судження](/uk/docs/Web/JavaScript/Guide/Regular_Expressions/Assertions) включають межі, котрі позначають початок і кінець рядків та слів, а також інші патерни, котрі в певний спосіб позначають те, щ
Помітив далі "зазиральними", мені він подобається більше, пропоную вживати його для консистентності
```suggestion
[Судження](/uk/docs/Web/JavaScript/Guide/Regular_Expressions/Assertions) включають межі, котрі позначають початок і кінець рядків та слів, а також інші патерни, котрі в певний спосіб позначають те, що збіг можливий (включно з зазиральними, озиральними та умовними виразами).
```

2023-02-04 10:44 UTC, AdriandeCita commented on files/uk/web/javascript/guide/regular_expressions/cheatsheet/index.md
> +          Групи захоплення шкодять швидкодії. Коли немає потреби згадувати підрядковий збіг, слід віддавати перевагу дужкам без захоплення (дивіться нижче).
"підрядковий збіг" звучить не дуже зрозуміло
```suggestion
          Групи захоплення шкодять швидкодії. Коли немає потреби згадувати підрядки, що збіглися — слід віддавати перевагу дужкам без захоплення (дивіться нижче).
```

2023-02-04 10:53 UTC, AdriandeCita commented on files/uk/web/javascript/guide/regular_expressions/cheatsheet/index.md
> +          <strong>Іменована група захоплення: </strong>Дає збіг з "x", котрий зберігає на властивості групи повернених збігів, за ім'ям, заданим у вигляді <code>&#x3C;Name></code>. Кутові дужки (<cod
Це трохи дивне формулювання, пропоную переробити ось так. Я додаю обгортання  `groups` в код, оскільки мається на увазі буквально назва властивості
![image](https://user-images.githubusercontent.com/11510394/216763099-e14edee6-546e-4f82-9dea-69556410e1f2.png)
```suggestion
          <strong>Іменована група захоплення: </strong>Дає збіг з "x", і зберігає його у властивості `groups` повернених збігів, за ім'ям, заданим у вигляді <code>&#x3C;Name></code>. Кутові дужки (<code>&#x3C;</code>
```

2023-02-04 11:06 UTC, AdriandeCita commented on files/uk/web/javascript/guide/regular_expressions/cheatsheet/index.md
> +        <strong>Група без захоплення: </strong>Дає збіг з "x", але не запам'ятовує цього збігу. Підрядок збігу не можна відтворити з елементів результівного масиву (<code>[1], …, [n]</code>) чи напер
```suggestion
        <strong>Група без захоплення: </strong>Дає збіг з "x", але не запам'ятовує цього збігу. Підрядок збігу не можна відтворити з елементів результівного масиву (<code>[1], …, [n]</code>) чи властивостей (<code>$1, …, $9</code>) заздалегідь означеного об'єкта <code>RegExp</code>.
```

2023-02-04 15:11 UTC, AdriandeCita commented on files/uk/web/javascript/guide/regular_expressions/cheatsheet/index.md
> +> **Примітка:** Оскільки доступно чимало властивостей і значень, вони не будуть описані вичерпно тут, а радше описані в різних прикладах.
```suggestion
> **Примітка:** Оскільки доступно чимало властивостей і значень, вони не будуть описані вичерпно тут, а радше наведені в різних прикладах.
```

2023-02-04 15:12 UTC, AdriandeCita commented on uk_spelling_additions.txt
> +визиральними
Якщо приймається мій коментар стосовно "зазиральними", то цей рядок стає непотрібним
```suggestion
```

2023-02-04 15:12 UTC, AdriandeCita requested changes
Декілька зауважень

2023-02-04 19:50 UTC, undead404 commented
Прийняв пропозиції

2023-02-05 22:50 UTC, AdriandeCita approved these changes

2023-02-05 22:50 UTC, merged