translation(JS): web/javascript/reference/global_objects/intl/numberformat
webdoky/content pull request #1216
Opened 2023-01-04 13:27 UTC by undead404

Оригінальний вміст: [Intl.NumberFormat@MDN](https://developer.mozilla.org/en-us/docs/Web/JavaScript/Reference/Global_Objects/Intl/NumberFormat), [сирці Intl.NumberFormat@GitHub](https://github.com/mdn/content/blob/main/files/en-us/web/javascript/reference/global_objects/intl/numberformat/index.md)

2023-01-21 09:13 UTC, undead404 commented
Оновлено

2023-02-04 15:20 UTC, AdriandeCita commented on files/uk/web/javascript/reference/global_objects/intl/numberformat/index.md
> +  - : Повертає {{jsxref("Array")}} з об'єктів, котрі представляють числовий рядок у вигляді частин, що може використовуватися для самописного форматування з урахуванням локалі.
```suggestion
  - : Повертає {{jsxref("Array")}} з об'єктів, котрі представляють числовий рядок у вигляді частин, що може використовуватися для виконання власного форматування з урахуванням локалі.
```

2023-02-04 15:22 UTC, AdriandeCita commented on files/uk/web/javascript/reference/global_objects/intl/numberformat/index.md
> +  - : Повертає {{jsxref("Array")}} з об'єктів, що представляють діапазон числових рядків у вигляді частин, що можуть бути використані для самописного форматування з урахуванням локалі.
```suggestion
  - : Повертає {{jsxref("Array")}} з об'єктів, що представляють діапазон числових рядків у вигляді частин, що можуть бути використані для виконання власного форматування з урахуванням локалі.
```

2023-02-04 15:23 UTC, AdriandeCita commented on files/uk/web/javascript/reference/global_objects/intl/numberformat/index.md
> +При базовому застосуванні, без задання локалі, повертається рядок, форматований згідно з усталеною локаллю та усталеними опціями.
```suggestion
При базовому застосуванні, без задання локалі, повертається рядок, форматований згідно з усталеними локаллю та опціями.
```

2023-02-04 15:26 UTC, AdriandeCita requested changes
Пара зауважень

2023-02-04 19:52 UTC, undead404 commented
Прийняв пропозиції

2023-02-05 22:51 UTC, AdriandeCita approved these changes

2023-02-05 22:51 UTC, merged