translation(JS): web/javascript/reference/global_objects/symbol
webdoky/content pull request #1217
Opened 2023-01-04 15:06 UTC by undead404

Оригінальний вміст: [Symbol@MDN](https://developer.mozilla.org/en-us/docs/Web/JavaScript/Reference/Global_Objects/Symbol), [сирці Symbol@GitHub](https://github.com/mdn/content/blob/main/files/en-us/web/javascript/reference/global_objects/symbol/index.md)

2023-02-04 15:32 UTC, AdriandeCita commented on files/uk/web/javascript/reference/global_objects/symbol/index.md
> +**`Symbol`** (символ) – це вбудований об'єкт, чий конструктор повертає [примітив](/uk/docs/Glossary/Primitive) `symbol` – котрий також звуть **символьним значенням** або просто **символом**, і котрий
Тут в двох речення підряд 5 слів "котрий" в різних формах)
```suggestion
**`Symbol`** (символ) – це вбудований об'єкт, чий конструктор повертає [примітив](/uk/docs/Glossary/Primitive) `symbol` – котрий також звуть **символьним значенням** або просто **символом**, і котрий гарантовано є унікальним. Символи нерідко використовуються для додання до об'єкта унікальних ключів властивостей, котрі не конфліктуватимуть з жодними ключами, які може додати до цього об'єкта якийсь інший код, і котрі приховані від будь-яких механізмів, за допомогою яких інший корд здебільшого буде звертатися до цього об'єкта. Таким чином доступна певного роду слабка {{Glossary("encapsulation", "інкапсуляція")}}, або ж слабка форма [приховування інформації](https://en.wikipedia.org/wiki/Information_hiding).
```

2023-02-04 15:41 UTC, AdriandeCita commented on files/uk/web/javascript/reference/global_objects/symbol/index.md
> +Кожний виклик `Symbol()` гарантовано повертає унікальний символ. Кожний виклик `Symbol.for("key")` повертає той самий символ для того самого значення `"key"`. Коли викликається `Symbol.for("key")`, т
"...то якщо... то повертається". Трохи переформулював для кращої прочитності.
```suggestion
Кожний виклик `Symbol()` гарантовано повертає унікальний символ. Кожний виклик `Symbol.for("key")` повертає той самий символ для того самого значення `"key"`. Коли викликається `Symbol.for("key")`, то якщо символ з переданим ключем може бути знайдений у глобальному реєстрі символів — цей символ повертається. Інакше – створюється і додається до глобального реєстру символів за переданим ключем новий символ, після чого – повертається.
```

2023-02-04 16:48 UTC, AdriandeCita commented on files/uk/web/javascript/reference/global_objects/symbol/index.md
> +Зверніть увагу, що "глобальний реєстр символів" є лише уявною концепцією, котра може не відповідати жодній потаємній структурі даних у рушії JavaScript – і навіть коли такий реєстр існує, його вміст
Навіть якщо не зациклюватися на перекладі терміну "internal" - "глобальний реєстр символів" в принципі не зобов'язаний відповідати ні явним структурам рушія, ні прихованим, тож немає сенсу конкретизувати це до "потаємних структур"
```suggestion
Зверніть увагу, що "глобальний реєстр символів" є лише уявною концепцією, котра може не відповідати жодній внутрішній структурі даних рушія JavaScript – і навіть коли такий реєстр існує, його вміст недоступний кодові на JavaScript ніяким іншим чином, окрім методів `for()` і `keyFor()`.
```

2023-02-04 16:50 UTC, AdriandeCita commented on files/uk/web/javascript/reference/global_objects/symbol/index.md
> +Метод `Symbol.for(tokenString)` приймає рядковий ключ і повертає символьне значення з реєстру, а `Symbol.keyFor(symbolValue)` приймає символьне значення і повертає рядковий ключ, котрий цьому значенн
Думаю, тут краще підійде "обернений", inverse - це не зовсім про протилежність
```suggestion
Метод `Symbol.for(tokenString)` приймає рядковий ключ і повертає символьне значення з реєстру, а `Symbol.keyFor(symbolValue)` приймає символьне значення і повертає рядковий ключ, котрий цьому значенню відповідає. Ці методи є взаємно оберненими, тож код нижче дає `true`:
```

2023-02-04 16:54 UTC, AdriandeCita commented on files/uk/web/javascript/reference/global_objects/symbol/index.md
> +До загальновідомих символів JavaScript для реалізації певних вбудованих операцій використовував звичайні властивості. Наприклад, функція [`JSON.stringify`](/uk/docs/Web/JavaScript/Reference/Global_Ob
Трошки розділових знаків, бо складно читається
```suggestion
До появи загальновідомих символів JavaScript, для реалізації певних вбудованих операцій, використовував звичайні властивості. Наприклад, функція [`JSON.stringify`](/uk/docs/Web/JavaScript/Reference/Global_Objects/JSON/stringify) намагається викликати на кожному об'єкті метод `toJSON()`, а функція [`String`](/uk/docs/Web/JavaScript/Reference/Global_Objects/String/String) викликає на об'єкті методи `toString()` і `valueOf()`. Проте, із доданням до мови більшої кількості операцій, виділення кожній з них "магічної властивості" могло зламати зворотну сумісність й ускладнити роботу з логікою мови. Загальновідомі символи дають кастомізаціям змогу бути "невидимими" для звичайного коду, котрий зазвичай зчитує лише рядкові властивості.
```

2023-02-04 17:01 UTC, AdriandeCita commented on files/uk/web/javascript/reference/global_objects/symbol/index.md
> +  - : Метод, котрий повертає індекс всередині рядка, котрий дає збіг з регулярним виразом. Використовується методом {{jsxref("String.prototype.search()")}}.
котрий...котрий
```suggestion
  - : Метод, котрий повертає індекс всередині рядка, який дає збіг з регулярним виразом. Використовується методом {{jsxref("String.prototype.search()")}}.
```

2023-02-04 17:01 UTC, AdriandeCita commented on files/uk/web/javascript/reference/global_objects/symbol/index.md
> +  - : Метод, котрий розбиває рядок за індексами, котрі дають збіг з регулярним виразом. Використовується методом {{jsxref("String.prototype.split()")}}.
котрий...котрий
```suggestion
  - : Метод, котрий розбиває рядок за індексами, що дають збіг з регулярним виразом. Використовується методом {{jsxref("String.prototype.split()")}}.
```

2023-02-04 17:04 UTC, AdriandeCita commented on files/uk/web/javascript/reference/global_objects/symbol/index.md
> +  - : Об'єктне значення, чиї власні й успадковані імена властивостей виключаються зі зв'язування середовища [`with`](/uk/docs/Web/JavaScript/Reference/Statements/with) для асоційованого об'єкта.
```suggestion
  - : Об'єктне значення, чиї власні й успадковані імена властивостей виключаються зі зв'язувань середовища інструкції [`with`](/uk/docs/Web/JavaScript/Reference/Statements/with) для асоційованого об'єкта.
```

2023-02-04 17:20 UTC, AdriandeCita commented on uk_spelling_additions.txt
> +картинку-в-
```suggestion
картинку-в-картинці
```

2023-02-04 17:21 UTC, AdriandeCita commented on files/uk/web/javascript/reference/global_objects/symbol/index.md
> +- `Symbol("foo") + "bar"` викидає {{jsxref("TypeError")}} (не можна перетворювати символ на рядок). Це запобігає, наприклад, тихому створенню з символу нового імені рядкової властивості.
```suggestion
- `Symbol("foo") + "bar"` викидає {{jsxref("TypeError")}} (не можна перетворювати символ на рядок). Це запобігає, наприклад, тихому створенню з символу нового рядкового імені властивості.
```

2023-02-04 17:21 UTC, AdriandeCita requested changes
Декілька зауважень

2023-02-04 19:55 UTC, undead404 commented
Прийняв пропозиції

2023-02-05 22:51 UTC, AdriandeCita approved these changes

2023-02-05 22:51 UTC, merged