translation(CSS): web/css/containing_block
webdoky/content pull request #1220
Opened 2023-01-05 16:41 UTC by undead404

Оригінальний вміст: [Layout and the containing block@MDN](https://developer.mozilla.org/en-us/docs/Web/CSS/Containing_block), [сирці Layout and the containing block@GitHub](https://github.com/mdn/content/blob/main/files/en-us/web/css/containing_block/index.md)

2023-02-04 18:34 UTC, AdriandeCita commented on files/uk/web/css/containing_block/index.md
> +4. Коли властивість `position` має значення **`absolute`** або **`fixed`**, контейнерний блок так само буде бути утворений краєм _рамок внутрішніх відступів_ найближчого елемента-предка, котрий викон
```suggestion
4. Коли властивість `position` має значення **`absolute`** або **`fixed`**, контейнерний блок може також формуватися краєм _рамок внутрішніх відступів_ найближчого елемента-предка, котрий виконує наступні умови:
```

2023-02-04 18:39 UTC, AdriandeCita commented on files/uk/web/css/containing_block/index.md
> +Як зазначено вище, коли певні властивості отримують відсоткове значення, то обчислене значення залежить від контейнерного блока елемента. Властивості, котрі так працюють – **властивості рамкової моде
offset - це радше "зміщення"
```suggestion
Як зазначено вище, коли певні властивості отримують відсоткове значення, то обчислене значення залежить від контейнерного блока елемента. Властивості, котрі так працюють – **властивості рамкової моделі** та **властивості зміщення**:
```

2023-02-04 18:41 UTC, AdriandeCita commented on files/uk/web/css/containing_block/index.md
> +У цьому прикладі контейнерний блок абзацу – `<section>`, бо властивість `position` останнього має значення `absolute`. На відсоткові значення абзацу впливає `padding` його контейнерного блоку; якби з
```suggestion
У цьому прикладі контейнерний блок абзацу – `<section>`, бо властивість `position` останнього має значення `absolute`. На відсоткові значення абзацу впливає `padding` його контейнерного блоку; якби значенням властивості {{cssxref("box-sizing")}} контейнерного блоку було `border-box` — це було б не так.
```

2023-02-04 18:43 UTC, AdriandeCita requested changes
пара зауважень

2023-02-04 19:56 UTC, undead404 commented
Прийняв пропозиції

2023-02-05 22:52 UTC, AdriandeCita approved these changes

2023-02-05 22:53 UTC, merged