translation(Accessibility): web/accessibility/understanding_wcag/perceivable
webdoky/content pull request #1222
Opened 2023-01-07 11:53 UTC by undead404

Оригінальний вміст: [Perceivable@MDN](https://developer.mozilla.org/en-US/docs/Web/Accessibility/Understanding_WCAG/Perceivable), [сирці Perceivable@GitHub](https://github.com/mdn/content/blob/main/files/en-us/web/accessibility/understanding_wcag/perceivable/index.md?plain=1)

2023-01-07 11:54 UTC, undead404 commented
Розумію, що ми цей розділ наразі не обробляємо, але це дуже цікава розумова вправа – такий переклад

2023-02-04 18:48 UTC, AdriandeCita commented on files/uk/web/accessibility/understanding_wcag/perceivable/index.md
> +Ключовою думкою тут є те, що текст може бути перетворений в інші форми, котрі можуть використовувати люди з особливими потребами. Наприклад, його може зачитати читач з екрана, може бути збільшений йо
можливо, менш прямий переклад, але звучатиме трохи ліпше, аніж "може зачитати читач..."
```suggestion
Ключовою думкою тут є те, що текст може бути перетворений в інші форми, котрі можуть використовувати люди з особливими потребами. Наприклад, його може озвучити читач з екрана, може бути збільшений його шрифт, він може бути представлений на дисплеї Брайля. Нетекстовий вміст позначає мультимедійний вміст, як то зображення, аудіо та відео.
```

2023-02-04 18:53 UTC, AdriandeCita commented on files/uk/web/accessibility/understanding_wcag/perceivable/index.md
> +## Настанови 1.2 — Надання текстових альтернатив часозалежним носіям
"часозалежний" може бути трохи проблематичним терміном, але притомних альтернатив у мене поки немає, тож най буде

2023-02-07 20:51 UTC, AdriandeCita requested changes
є трохи зауважень

2023-02-07 20:51 UTC, AdriandeCita commented on files/uk/web/accessibility/understanding_wcag/perceivable/index.md
> +          Інструкції для оперативних елементів чи розуміння вмісту не повинні покладатися на одне чуття. Це зробило б їх недоступними для людей з вадами щодо цього чуття або пристрою, що не підтримує
```suggestion
          Інструкції з оперування елементами керування чи розуміння вмісту не повинні покладатися на одне чуття. Це зробило б їх недоступними для людей з вадами щодо цього чуття або пристрою, що не підтримує це чуття. Тож, наприклад:
```

2023-02-07 20:51 UTC, AdriandeCita commented on files/uk/web/accessibility/understanding_wcag/perceivable/index.md
> +        Вміст не обмежує свій вигляд та роботу єдиною орієнтацією дисплея, як то портретною чи альбомною, якщо конкретна орієнтація не є невід'ємною його частиною.
Звучить як наче орієнтація дисплея може бути частиною вмісту. Пропоную спростити
```suggestion
        Вміст не обмежує свій вигляд та роботу єдиною орієнтацією дисплея, як то портретною чи альбомною, якщо конкретна орієнтація не є необхідною.
```

2023-02-07 20:51 UTC, AdriandeCita commented on files/uk/web/accessibility/understanding_wcag/perceivable/index.md
> +> **Примітка:** Також дивіться опис WCAG для [Настанов 1.3: Адаптивність: Створювати вміст, котрий може бути представлений у різний спосіб без утрати інформації чи структури.](https://www.w3.org/TR/W
```suggestion
> **Примітка:** Також дивіться опис WCAG для [Настанови 1.3: Адаптивність: Створювати вміст, котрий може бути представлений у різний спосіб без утрати інформації чи структури.](https://www.w3.org/TR/WCAG21/#adaptable)
```

2023-02-07 20:51 UTC, AdriandeCita commented on files/uk/web/accessibility/understanding_wcag/perceivable/index.md
> +        Використовуйте нативні елементи `&#x3C;button> для надання доступного контролю з клавіатури, як це показано в
```suggestion
        Використовуйте нативні елементи `&#x3C;button>` для надання доступного контролю з клавіатури, як це показано в
```

2023-02-07 20:51 UTC, AdriandeCita commented on files/uk/web/accessibility/understanding_wcag/perceivable/index.md
> +          Колірний контраст між вмістом заднього та переднього плану повинен бути на мінімальному рівні, що забезпечує розбірливість:
Це може звучати наче контраст повинен бути мінімальним, хоча це не так. Здається, це іще одне з тих місць, де треба перекладати артикль _a_ :grin: 
```suggestion
          Колірний контраст між вмістом заднього та переднього плану повинен бути на певному мінімальному рівні, що забезпечує розбірливість:
```

2023-02-07 20:51 UTC, AdriandeCita commented on files/uk/web/accessibility/understanding_wcag/perceivable/index.md
> +            Висота лінії повинна бути щонайменше 1.5 розмірів тексту, коли це текст в межах абзаців (наприклад, `line-height: 1.5;`), і щонайменше 2.25 розмірів для тексту між абзацами (наприклад, <c
```suggestion
            Висота рядка повинна бути щонайменше 1.5 розмірів тексту, коли це текст в межах абзаців (наприклад, `line-height: 1.5;`), і щонайменше 2.25 розмірів для тексту між абзацами (наприклад, <code>padding: 2.25rem;</code>).
```

2023-02-07 20:51 UTC, AdriandeCita commented on files/uk/web/accessibility/understanding_wcag/perceivable/index.md
> +        1.4.10 Переспрямування (AA) <em><a href="https://www.w3.org/TR/WCAG21/#new-features-in-wcag-2-1">додано у 2.1</a></em>
Тут мова про те, що кожного разу після масштабування чи зміни області перегляду, вміст сторінки повинен укладатися наново, і не утворювати смуг прокрутки. "Переспрямування" — це зазвичай про зміну напрямку або точки призначення, що не зовсім те.
```suggestion
        1.4.10 Переукладання (AA) <em><a href="https://www.w3.org/TR/WCAG21/#new-features-in-wcag-2-1">додано у 2.1</a></em>
```

2023-02-07 20:51 UTC, AdriandeCita commented on files/uk/web/accessibility/understanding_wcag/perceivable/index.md
> +        <a href="https://www.w3.org/WAI/WCAG21/Understanding/reflow.html">Розуміння переспрямування</a>
```suggestion
        <a href="https://www.w3.org/WAI/WCAG21/Understanding/reflow.html">Розуміння переукладання</a>
```

2023-02-07 20:51 UTC, AdriandeCita commented on files/uk/web/accessibility/understanding_wcag/perceivable/index.md
> +          Не повинно бути втрати вмісту чи функціональності, коли застосовуються наступні стилі:
```suggestion
          Не повинно відбуватися втрати вмісту чи функціональності, коли застосовуються наступні стилі:
```

2023-02-08 10:06 UTC, undead404 commented on files/uk/web/accessibility/understanding_wcag/perceivable/index.md
> +        Вміст не обмежує свій вигляд та роботу єдиною орієнтацією дисплея, як то портретною чи альбомною, якщо конкретна орієнтація не є невід'ємною його частиною.
Ну воно фактично так і задумано: деякі медіа не можна крутити туди-сюди, орієнтація є частиною вмісту

2023-02-08 10:08 UTC, undead404 commented
Прийняв пропозиції, окрім однієї

2023-03-02 11:26 UTC, undead404 commented
Оновлено

2023-03-08 15:35 UTC, AdriandeCita approved these changes

2023-03-08 15:36 UTC, merged