translation(JS): web/javascript/reference/lexical_grammar
webdoky/content pull request #1229
Opened 2023-01-20 15:11 UTC by undead404

Оригінальний вміст: [Lexical grammar@MDN](https://developer.mozilla.org/en-us/docs/Web/JavaScript/Reference/Lexical_grammar), [сирці Lexical grammar@GitHub](https://github.com/mdn/content/blob/main/files/en-us/web/javascript/reference/lexical_grammar/index.md)

2023-02-02 09:25 UTC, undead404 commented
Розв'язано конфлікт

2023-02-24 00:01 UTC, AdriandeCita requested changes
Декілька зауважень

2023-03-02 12:08 UTC, undead404 commented
Розв'язано конфлікт

2023-03-02 13:11 UTC, undead404 commented
Оновлено

2023-03-08 15:40 UTC, AdriandeCita approved these changes

2023-03-08 15:41 UTC, merged

2023-03-08 15:47 UTC, AdriandeCita commented
Там три дні тому з'явилися нові зміни, їх треба або внести в складі цього пулреквеста (я створив відповідний запит на реверт), або додати як оновлення окремо

https://github.com/mdn/content/commit/519e4e0308379d8c2b461d0202130ca4a652d4d9