translation(CSS): web/css/replaced_element
webdoky/content pull request #1256
Opened 2023-01-21 12:37 UTC by undead404

Оригінальний вміст: [Replaced elements@MDN](https://developer.mozilla.org/en-us/docs/Web/CSS/Replaced_element), [сирці Replaced elements@GitHub](https://github.com/mdn/content/blob/main/files/en-us/web/css/replaced_element/index.md)

2023-01-24 12:22 UTC, undead404 commented on files/uk/web/css/replaced_element/index.md
> +- CSS key concepts:
```suggestion
- Ключові концепції CSS:
```

2023-02-25 08:43 UTC, AdriandeCita commented on files/uk/web/css/replaced_element/index.md
> +Частина елементів вважається заміщеними елементами лише в певних випадках:
```suggestion
Частина елементів вважається заміщеними лише в певних випадках:
```

2023-02-25 08:52 UTC, AdriandeCita commented on files/uk/web/css/replaced_element/index.md
> +  - : Задає спосіб шикування об'єкта вмісту заміщеного елемента всередині рамок елемента.
```suggestion
  - : Задає спосіб шикування об'єкта вмісту заміщеного елемента всередині його рамок.
```

Окрім цього це гарний приклад контексту, в якому шикування звучить чужо, оскільки мова йде про єдиний елемент. В контексті цього ПРа я пропонувати нічого не буду, але десь буду пушити ту дискусію, щоб ми швидше прийшли до чогось

2023-02-25 08:52 UTC, AdriandeCita requested changes
Пара спрощень

2023-03-02 11:29 UTC, undead404 commented on files/uk/web/css/replaced_element/index.md
> +  - : Задає спосіб шикування об'єкта вмісту заміщеного елемента всередині рамок елемента.
Ти що, ні разу не виконував команду "шикуйсь", бувши єдиним учасником шеренги? :-D

2023-03-02 11:30 UTC, undead404 commented
Прийняв пропозиції

2023-03-08 15:48 UTC, AdriandeCita approved these changes

2023-03-08 15:48 UTC, merged