translation(CSS): web/css/image
webdoky/content pull request #1257
Opened 2023-01-26 08:48 UTC by undead404

Оригінальний вміст: [&lt;image>@MDN](https://developer.mozilla.org/en-us/docs/Web/CSS/image), [сирці &lt;image>@GitHub](https://github.com/mdn/content/blob/main/files/en-us/web/css/image/index.md)

2023-02-25 08:57 UTC, AdriandeCita commented on files/uk/web/css/image/index.md
> +| ґатунок об'єкта (властивість CSS)                                                          | Усталені розміри об'єкта
```suggestion
| Ґатунок об'єкта (властивість CSS)                                                          | Усталені розміри об'єкта                                                                                                                |
```

2023-02-25 09:01 UTC, AdriandeCita commented on files/uk/web/css/image/index.md
> +- Якщо заданий розмір визначає _лише ширину або лише висоту_, то відсутнє значення визначається на основі природного співвідношення сторін, якщо воно є, природних розмірів, якщо задане значення збіга
Це речення складно читається, бо обставини перемішані з елементами переліку. Треба або переформулювати, або виразити це на рівні пунктуації
```suggestion
- Якщо заданий розмір визначає _лише ширину або лише висоту_, то відсутнє значення визначається на основі: природного співвідношення сторін — якщо воно є, — природних розмірів — якщо задане значення збігається з відповідним природним розміром, — або усталеним розміром об'єкта.
```

2023-02-25 09:04 UTC, AdriandeCita requested changes
Пара дрібниць

2023-03-02 12:09 UTC, undead404 commented
Прийняв пропозиції

2023-03-02 13:12 UTC, undead404 commented
Оновлено

2023-03-08 15:49 UTC, AdriandeCita approved these changes

2023-03-08 15:49 UTC, merged