translation(CSS): web/css/shorthand_properties
webdoky/content pull request #1265
Opened 2023-01-29 16:11 UTC by undead404

Оригінальний вміст: [Shorthand properties@MDN](https://developer.mozilla.org/en-us/docs/Web/CSS/Shorthand_properties), [сирці Shorthand properties@GitHub](https://github.com/mdn/content/blob/main/files/en-us/web/css/shorthand_properties/index.md)

2023-02-25 09:10 UTC, AdriandeCita commented on files/uk/web/css/shorthand_properties/index.md
> +Значення, котре не задано, задається із власним початковим значенням. Це означає, що таке значення **відкидає** до того задані значення. Наприклад:
значення із значенням? Пропоную переформулювати інакше
```suggestion
Значенню, котре не задано, задається його власне початкове значення. Це означає, що воно **відкидає** до того задані значення. Наприклад:
```

2023-02-25 09:17 UTC, AdriandeCita commented on files/uk/web/css/shorthand_properties/index.md
> +(Скорочена форма фактично є рівносильною щодо розгорнутих властивостей вище плюс `background-attachment: scroll`, а також, у CSS3, кількох додаткових властивостей.)
```suggestion
(Скорочена форма фактично є рівносильною щодо розгорнутих властивостей вище плюс `background-attachment: scroll`, а також — у CSS3 — кількох додаткових властивостей.)
```

2023-02-25 09:20 UTC, AdriandeCita requested changes
Пара зауважень

2023-03-02 12:22 UTC, undead404 commented
Оновлено

2023-03-08 15:50 UTC, AdriandeCita approved these changes

2023-03-08 15:50 UTC, merged