translation(JS): web/javascript/reference/statements/let
webdoky/content pull request #1268
Opened 2023-01-31 14:57 UTC by undead404

Оригінальний вміст: [let@MDN](https://developer.mozilla.org/en-us/docs/Web/JavaScript/Reference/Statements/let), [сирці let@GitHub](https://github.com/mdn/content/blob/main/files/en-us/web/javascript/reference/statements/let/index.md)

2023-02-26 18:52 UTC, AdriandeCita requested changes
Є декілька зауважень

2023-02-26 18:52 UTC, AdriandeCita commented on files/uk/web/javascript/reference/statements/let/index.md
> +Змінна в TDZ іще не була ініціалізована значенням, і будь-які спроби звернутися до неї призведуть до {{jsxref("ReferenceError")}}.
```suggestion
Поки змінна в TDZ — вона іще не ініціалізована значенням, і будь-які спроби звернутися до неї призведуть до {{jsxref("ReferenceError")}}.
```

2023-02-26 18:52 UTC, AdriandeCita commented on files/uk/web/javascript/reference/statements/let/index.md
> +Проте поєднання оголошень **`var`** і **`let`** нижче – {{jsxref("SyntaxError")}}, у зв'язку з тим, що **`var`** піднімається нагору блоку.
Не зовсім коректне твердження. `SyntaxError` - це тип об'єкта, а просто шматок коду не може бути примірником такого об'єкта. В оригіналі таке речення працює лише тому, що код пишеться теж англійською
```suggestion
Проте поєднання оголошень **`var`** і **`let`** нижче – {{jsxref("SyntaxError", "синтаксична помилка")}}, у зв'язку з тим, що **`var`** піднімається нагору блоку.
```

2023-03-02 11:32 UTC, undead404 commented on files/uk/web/javascript/reference/statements/let/index.md
> +At the top level of programs and functions, **`let`**, unlike **`var`**, does not create a property on the global object.
```suggestion
На верхньому рівні програм та функцій, **`let`**, на відміну від **`var`**, не створює властивості у глобальному об'єкті.
```
Поправочка

2023-03-02 11:32 UTC, undead404 commented
Прийняв пропозиції, з одною поправкою.

2023-03-08 15:52 UTC, AdriandeCita approved these changes

2023-03-08 15:52 UTC, merged