translation(JS): web/javascript/reference/global_objects/error
webdoky/content pull request #1269
Opened 2023-01-31 17:20 UTC by undead404

Оригінальний вміст: [Error@MDN](https://developer.mozilla.org/en-us/docs/Web/JavaScript/Reference/Global_Objects/Error), [сирці Error@GitHub](https://github.com/mdn/content/blob/main/files/en-us/web/javascript/reference/global_objects/error/index.md)

2023-02-26 18:57 UTC, AdriandeCita commented on files/uk/web/javascript/reference/global_objects/error/index.md
> +  - : Повертає рядок, що представляє заданий об'єкт. Відкидає метод {{jsxref("Object.prototype.toString()")}}.
Я розумію, чому "відкидання" доречніше в CSS, але в ООП "заміщення" виглядає кращою альтернативою.
https://uk.wikipedia.org/wiki/%D0%97%D0%B0%D0%BC%D1%96%D1%89%D0%B5%D0%BD%D0%BD%D1%8F_%D0%BC%D0%B5%D1%82%D0%BE%D0%B4%D1%83
```suggestion
  - : Повертає рядок, що представляє заданий об'єкт. Заміщує метод {{jsxref("Object.prototype.toString()")}}.
```

2023-02-26 19:01 UTC, AdriandeCita requested changes
Невеличке зауваження

2023-03-02 11:31 UTC, undead404 commented
Слушна пропозиція, дякую, прийняв

2023-03-02 12:33 UTC, undead404 commented
Оновлено

2023-03-08 15:54 UTC, AdriandeCita approved these changes

2023-03-08 15:54 UTC, merged