translation(JS): Math cos and cosh
webdoky/content pull request #127
Opened 2021-11-30 23:17 UTC by AdriandeCita

Original content: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Math/cos, https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Math/cosh

2021-12-09 21:35 UTC, AdriandeCita commented on files/uk/web/javascript/reference/global_objects/math/cos/index.md
> +Оскільки `cos()` — це статичний метод об'єкта `Math`, його потрібно завжди використовувати через `Math.cos()`. Не слід звертатись до нього, як до методу створеного вами об'єкту `Math` (`Math` не є ко
```suggestion
Оскільки `cos()` — це статичний метод об'єкта `Math`, його потрібно завжди використовувати через `Math.cos()`. Не слід звертатись до нього, як до методу власноруч створеного екземпляра `Math` (`Math` не є конструктором).
```

2021-12-09 21:35 UTC, AdriandeCita commented on files/uk/web/javascript/reference/global_objects/math/cosh/index.md
> +Оскільки `cosh()` — це статичний метод об'єкта `Math`, його потрібно завжди використовувати через `Math.cosh()`. Не слід звертатись до нього, як до методу створеного вами об'єкту `Math` (`Math` не є
```suggestion
Оскільки `cosh()` — це статичний метод об'єкта `Math`, його потрібно завжди використовувати через `Math.cosh()`. Не слід звертатись до нього, як до методу власноруч створеного екземпляра `Math` (`Math` не є конструктором).
```

2021-12-25 16:10 UTC, undead404 requested changes

2021-12-25 16:10 UTC, undead404 commented on files/uk/web/javascript/reference/global_objects/math/cos/index.md
> +Оскільки `cos()` — це статичний метод об'єкта `Math`, його потрібно завжди використовувати через `Math.cos()`. Не слід звертатись до нього, як до методу власноруч створеного екземпляра `Math` (`Math`
```suggestion
Оскільки `cos()` — це статичний метод об'єкта `Math`, його потрібно завжди використовувати через `Math.cos()`. Не слід звертатись до нього як до методу власноруч створеного екземпляра `Math` (`Math` не є конструктором).
```

2021-12-25 16:10 UTC, undead404 commented on files/uk/web/javascript/reference/global_objects/math/cosh/index.md
> +Оскільки `cosh()` — це статичний метод об'єкта `Math`, його потрібно завжди використовувати через `Math.cosh()`. Не слід звертатись до нього, як до методу власноруч створеного екземпляра `Math` (`Mat
```suggestion
Оскільки `cosh()` — це статичний метод об'єкта `Math`, його потрібно завжди використовувати через `Math.cosh()`. Не слід звертатись до нього як до методу власноруч створеного екземпляра `Math` (`Math` не є конструктором).
```

2021-12-30 21:55 UTC, undead404 approved these changes

2021-12-30 23:01 UTC, merged