translation(JS): web/javascript/reference/global_objects/boolean
webdoky/content pull request #1270
Opened 2023-01-31 20:11 UTC by undead404

Оригінальний вміст: [Boolean@MDN](https://developer.mozilla.org/en-us/docs/Web/JavaScript/Reference/Global_Objects/Boolean), [сирці Boolean@GitHub](https://github.com/mdn/content/blob/main/files/en-us/web/javascript/reference/global_objects/boolean/index.md)

2023-01-31 20:11 UTC, undead404 commented on files/uk/web/javascript/reference/global_objects/boolean/index.md
> +- [Булів тип даних (Вікіпедія](https://en.wikipedia.org/wiki/Boolean_data_type)
```suggestion
- [Логічний тип даних (Вікіпедія](https://uk.wikipedia.org/wiki/%D0%9B%D0%BE%D0%B3%D1%96%D1%87%D0%BD%D0%B8%D0%B9_%D1%82%D0%B8%D0%BF_%D0%B4%D0%B0%D0%BD%D0%B8%D1%85)
```

2023-01-31 20:12 UTC, undead404 commented on files/uk/web/javascript/reference/global_objects/boolean/index.md
> +- [Логічний тип даних (Вікіпедія](https://uk.wikipedia.org/wiki/%D0%9B%D0%BE%D0%B3%D1%96%D1%87%D0%BD%D0%B8%D0%B9_%D1%82%D0%B8%D0%BF_%D0%B4%D0%B0%D0%BD%D0%B8%D1%85)
```suggestion
- [Логічний тип даних (Вікіпедія)](https://uk.wikipedia.org/wiki/%D0%9B%D0%BE%D0%B3%D1%96%D1%87%D0%BD%D0%B8%D0%B9_%D1%82%D0%B8%D0%BF_%D0%B4%D0%B0%D0%BD%D0%B8%D1%85)
```

2023-02-27 22:47 UTC, AdriandeCita commented on files/uk/web/javascript/reference/global_objects/boolean/index.md
> +- `NaN`, `undefined` і `null` – хибні, але не мають нестрогої рівності щодо `false`.
```suggestion
- `NaN`, `undefined` і `null` – хибні, але нестрого не дорівнюють `false`.
```

2023-02-27 22:48 UTC, AdriandeCita commented on files/uk/web/javascript/reference/global_objects/boolean/index.md
> +- Об'єкти – завжди істинні, але їхнє примітивне представлення може мати нестрогу рівність щодо `false`.
```suggestion
- Об'єкти – завжди істинні, але їхнє примітивне представлення може нестрого дорівнювати `false`.
```

2023-02-27 22:50 UTC, AdriandeCita commented on files/uk/web/javascript/reference/global_objects/boolean/index.md
> +Істинні значення – іще з меншою імовірністю мають нестрогу рівність щодо `true`. Усі значення є або істинними, або хибними, але більшість значень не є нестрого рівними ані `true`, ані `false`.
```suggestion
Істинні значення мають навіть меншу ймовірність нестрого дорівнювати `true`. Усі значення є або істинними, або хибними, але більшість значень не є нестрого рівними ані `true`, ані `false`.
```

2023-02-27 22:50 UTC, AdriandeCita commented on files/uk/web/javascript/reference/global_objects/boolean/index.md
> +  - : Повертає рядок – або `true`, або `false`, залежно від значення об'єкта. Відкидає метод {{jsxref("Object.prototype.toString()")}}.
```suggestion
  - : Повертає рядок – або `true`, або `false`, залежно від значення об'єкта. Заміщує метод {{jsxref("Object.prototype.toString()")}}.
```

2023-02-27 22:51 UTC, AdriandeCita commented on files/uk/web/javascript/reference/global_objects/boolean/index.md
> +  - : Повертає примітивне значення об'єкта {{jsxref("Boolean")}}. Відкидає метод{{jsxref("Object.prototype.valueOf()")}}.
```suggestion
  - : Повертає примітивне значення об'єкта {{jsxref("Boolean")}}. Заміщує метод{{jsxref("Object.prototype.valueOf()")}}.
```

2023-02-27 22:52 UTC, AdriandeCita requested changes
Декілька зауважень, здебільшого стосовно виразу "мати рівність"

2023-03-02 12:10 UTC, undead404 commented
Прийняв пропозиції

2023-03-02 13:16 UTC, undead404 commented
Оновлено

2023-03-08 15:54 UTC, AdriandeCita approved these changes

2023-03-08 15:54 UTC, merged