translation(JS): web/javascript/reference/global_objects/object/getownpropertynames
webdoky/content pull request #1274
Opened 2023-01-31 22:06 UTC by undead404

Оригінальний вміст: [Object.getOwnPropertyNames()@MDN](https://developer.mozilla.org/en-us/docs/Web/JavaScript/Reference/Global_Objects/Object/getOwnPropertyNames), [сирці Object.getOwnPropertyNames()@GitHub](https://github.com/mdn/content/blob/main/files/en-us/web/javascript/reference/global_objects/object/getownpropertynames/index.md)

2023-02-27 23:21 UTC, AdriandeCita approved these changes

2023-02-27 23:23 UTC, AdriandeCita requested changes
Є свіжі оновлення:
https://github.com/mdn/content/commit/d61bfb9ae59aabab7ac17ba345035e260f28fc83#diff-67fb6f809cba9386d3213ecc89d8d5d7b347ee362c1cdff263e144928fbc82be
https://github.com/mdn/content/commit/fcd80ee4c8477b6f73553bfada841781cf74cf46#diff-67fb6f809cba9386d3213ecc89d8d5d7b347ee362c1cdff263e144928fbc82be

2023-03-02 13:26 UTC, undead404 commented
Оновлено

2023-03-08 15:56 UTC, AdriandeCita approved these changes

2023-03-08 15:56 UTC, merged