translation(JS): Math pow and sign
webdoky/content pull request #128
Opened 2021-11-30 23:31 UTC by AdriandeCita

Original content: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Math/pow, https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Math/sign

2021-12-09 21:36 UTC, AdriandeCita commented on files/uk/web/javascript/reference/global_objects/math/sign/index.md
> +Оскільки `sign()` — це статичний метод об'єкта `Math`, його потрібно завжди використовувати через `Math.sign()`. Не слід звертатись до нього, як до методу створеного вами об'єкту `Math` (`Math` не є
```suggestion
Оскільки `sign()` — це статичний метод об'єкта `Math`, його потрібно завжди використовувати через `Math.sign()`. Не слід звертатись до нього, як до методу власноруч створеного екземпляра `Math` (`Math` не є конструктором).
```

2021-12-25 16:18 UTC, undead404 requested changes

2021-12-25 16:18 UTC, undead404 commented on files/uk/web/javascript/reference/global_objects/math/pow/index.md
> +Оскільки `pow()` — це статичний метод об'єкта `Math`, його потрібно завжди використовувати через `Math.pow()`. Не слід звертатись до нього, як до методу власноруч створеного екземпляра `Math` (`Math`
```suggestion
Оскільки `pow()` — це статичний метод об'єкта `Math`, його потрібно завжди використовувати через `Math.pow()`. Не слід звертатись до нього як до методу власноруч створеного екземпляра `Math` (`Math` не є конструктором).
```

2021-12-25 16:18 UTC, undead404 commented on files/uk/web/javascript/reference/global_objects/math/pow/index.md
> +// показники степеня зі знаком
```suggestion
// від‘ємні показники степеня
```

2021-12-25 16:18 UTC, undead404 commented on files/uk/web/javascript/reference/global_objects/math/pow/index.md
> +// основи зі знаком
```suggestion
// від‘ємні основи
```

2021-12-25 16:18 UTC, undead404 commented on files/uk/web/javascript/reference/global_objects/math/sign/index.md
> +Функція **`Math.sign()`** повертає або **додатну**, або **від'ємну** +/- 1, позначаючи знак числа, переданого як аргумент. Якщо число, передане до `Math.sign()` дорівнює 0, функція поверне +/- 0. Зау
```suggestion
Функція **`Math.sign()`** повертає або **додатну**, або **від'ємну** +/- 1 (одиницю), позначаючи знак числа, переданого як аргумент. Якщо число, передане до `Math.sign()`, дорівнює 0, функція поверне +/- 0. Зауважте, що, якщо число додатне, знак `+` **не буде** повернено явно.
```

2021-12-25 16:18 UTC, undead404 commented on files/uk/web/javascript/reference/global_objects/math/sign/index.md
> +Оскільки `sign()` — це статичний метод об'єкта `Math`, його потрібно завжди використовувати через `Math.sign()`. Не слід звертатись до нього, як до методу власноруч створеного екземпляра `Math` (`Mat
```suggestion
Оскільки `sign()` — це статичний метод об'єкта `Math`, його потрібно завжди використовувати через `Math.sign()`. Не слід звертатись до нього як до методу власноруч створеного екземпляра `Math` (`Math` не є конструктором).
```

2021-12-30 21:56 UTC, undead404 approved these changes

2021-12-30 23:01 UTC, merged