translation(Glossary): glossary/shallow_copy
webdoky/content pull request #1286
Opened 2023-02-03 15:03 UTC by undead404

Оригінальний вміст: [Shallow copy@MDN](https://developer.mozilla.org/en-us/docs/Glossary/Shallow_copy), [сирці Shallow copy@GitHub](https://github.com/mdn/content/blob/main/files/en-us/glossary/shallow_copy/index.md)

2023-02-27 23:25 UTC, AdriandeCita approved these changes

2023-02-27 23:26 UTC, AdriandeCita requested changes
Свіжі зміни https://github.com/mdn/content/commit/4bd65a01204446af2254bb8864bd22ad87bc86b0#diff-4f45627591fff95af9fbcbc9c6953a8fadd3658fd34b03d5c0684556a247fa4c

2023-03-13 08:46 UTC, undead404 commented
Оновлено

2023-03-31 10:42 UTC, AdriandeCita approved these changes

2023-03-31 10:42 UTC, merged