translation(JS): Math log, log10, log1p and log2
webdoky/content pull request #129
Opened 2021-11-30 23:32 UTC by AdriandeCita

Original content: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Math/log, https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Math/log10, https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Math/log1p, https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Math/log2

2021-12-09 21:36 UTC, AdriandeCita commented on files/uk/web/javascript/reference/global_objects/math/log/index.md
> +Оскільки `log()` — це статичний метод об'єкта `Math`, його потрібно завжди використовувати через `Math.log()`. Не слід звертатись до нього, як до методу створеного вами об'єкту `Math` (`Math` не є ко
```suggestion
Оскільки `log()` — це статичний метод об'єкта `Math`, його потрібно завжди використовувати через `Math.log()`. Не слід звертатись до нього, як до методу власноруч створеного екземпляра `Math` (`Math` не є конструктором).
```

2021-12-09 21:37 UTC, AdriandeCita commented on files/uk/web/javascript/reference/global_objects/math/log1p/index.md
> +Оскільки `log1p()` — це статичний метод об'єкта `Math`, його потрібно завжди використовувати через `Math.log1p()`. Не слід звертатись до нього, як до методу створеного вами об'єкту `Math` (`Math` не
```suggestion
Оскільки `log1p()` — це статичний метод об'єкта `Math`, його потрібно завжди використовувати через `Math.log1p()`. Не слід звертатись до нього, як до методу власноруч створеного екземпляра `Math` (`Math` не є конструктором).
```

2021-12-25 16:34 UTC, undead404 requested changes

2021-12-25 16:34 UTC, undead404 commented on files/uk/web/javascript/reference/global_objects/math/log/index.md
> +Якщо значення `x` — від'ємне, повернений результат завжди дорівнює {{jsxref("NaN")}}.
```suggestion
Якщо значення `x` — від'ємне, повернений результат завжди {{jsxref("NaN")}}.
```
Тут із "дорівнює" треба обережно

2021-12-25 16:34 UTC, undead404 commented on files/uk/web/javascript/reference/global_objects/math/log/index.md
> +Оскільки `log()` — це статичний метод об'єкта `Math`, його потрібно завжди використовувати через `Math.log()`. Не слід звертатись до нього, як до методу власноруч створеного екземпляра `Math` (`Math`
```suggestion
Оскільки `log()` — це статичний метод об'єкта `Math`, його потрібно завжди використовувати через `Math.log()`. Не слід звертатись до нього як до методу власноруч створеного екземпляра `Math` (`Math` не є конструктором).
```

2021-12-25 16:34 UTC, undead404 commented on files/uk/web/javascript/reference/global_objects/math/log/index.md
> +Якщо потрібно отримати натуральний логарифм 2 чи 10, використовуйте сталі {{jsxref("Math.LN2")}} чи {{jsxref("Math.LN10")}}. Якщо ж потрібен логарифм за основою 2 чи 10, для цього існують функції {{j
```suggestion
Якщо потрібно отримати натуральний логарифм 2 чи 10 – використовуйте сталі {{jsxref("Math.LN2")}} чи {{jsxref("Math.LN10")}}. Якщо ж потрібен логарифм за основою 2 чи 10 – для цього існують функції {{jsxref("Math.log2()")}} та {{jsxref("Math.log10()")}}. Для отримання логарифму за якоюсь іншою основою – використайте `Math.log(x) / Math.log(іншаОснова)`, як це показано в прикладі нижче; можливо, ви також захочете заздалегідь обчислити значення `1 / Math.log(іншаОснова)`.
```

2021-12-25 16:34 UTC, undead404 commented on files/uk/web/javascript/reference/global_objects/math/log/index.md
> +Math.log(-1); // NaN, out of range
```suggestion
Math.log(-1); // NaN, вихід за межі області визначення
```

2021-12-25 16:34 UTC, undead404 commented on files/uk/web/javascript/reference/global_objects/math/log10/index.md
> +Якщо значення `x` менше за 0, повернений результат завжди дорівнює {{jsxref("NaN")}}.
```suggestion
Якщо значення `x` менше за 0, то повернений результат завжди {{jsxref("NaN")}}.
```

2021-12-25 16:34 UTC, undead404 commented on files/uk/web/javascript/reference/global_objects/math/log1p/index.md
> +Для дуже малих значень _x_, додавання 1 може зменшити точність. Числа з рухомою комою подвійної точності, які використовуються в JS дають близько 15 розрядів точності. 1 + 1e-15
```suggestion
Для дуже малих значень _x_ додавання 1 може зменшити точність. Числа з рухомою комою подвійної точності, які використовуються в JS, дають близько 15 розрядів точності. 1 + 1e-15
```

2021-12-25 16:34 UTC, undead404 commented on files/uk/web/javascript/reference/global_objects/math/log1p/index.md
> +\= 1.000000000000001, але 1 + 1e-16 = 1.000000000000000, або рівно 1.0 в такій арифметиці, оскільки числа після 15 розряду зникають під час округлення.
```suggestion
\= 1.000000000000001, але 1 + 1e-16 = 1.000000000000000, або рівно 1.0 в такій арифметиці, оскільки цифри після 15 розряду зникають під час округлення.
```

2021-12-25 16:34 UTC, undead404 commented on files/uk/web/javascript/reference/global_objects/math/log1p/index.md
> +Під час обчислення log(1 + x), ми отримуємо дуже близький до `x` результат, за умови, що `x` малий (саме тому його називають 'натуральним' логарифмом). Коли ми викликаємо Math.log(1 + 1.1111111111e-1
```suggestion
Під час обчислення log(1 + x) отримуємо дуже близький до `x` результат, за умови, що `x` малий (саме тому його називають 'натуральним' логарифмом). Коли ми викликаємо Math.log(1 + 1.1111111111e-15), ми очікуємо отримати результат, близький до 1.1111111111e-15. Натомість доведеться брати логарифм 1.00000000000000111022 (помилки заокруглення накопичуються у двійковій системі числення, тому інколи вони виглядають незграбно), що дасть нам в результаті 1.11022...e-15, де лише 3 правильні цифри. Якщо натомість обчислити Math.log1p(1.1111111111e-15), отримаємо значно точніший результат 1.1111111110999995e-15, з 15 правильними розрядами точності (в цьому випадку навіть 16).
```

2021-12-25 16:34 UTC, undead404 commented on files/uk/web/javascript/reference/global_objects/math/log1p/index.md
> +Якщо значення `x` менше за -1, повернене значення завжди дорівнює {{jsxref("NaN")}}.
```suggestion
Якщо значення `x` менше за -1, то повернене значення завжди {{jsxref("NaN")}}.
```

2021-12-25 16:34 UTC, undead404 commented on files/uk/web/javascript/reference/global_objects/math/log1p/index.md
> +Оскільки `log1p()` — це статичний метод об'єкта `Math`, його потрібно завжди використовувати через `Math.log1p()`. Не слід звертатись до нього, як до методу власноруч створеного екземпляра `Math` (`M
```suggestion
Оскільки `log1p()` — це статичний метод об'єкта `Math` – його потрібно завжди використовувати через `Math.log1p()`. Не слід звертатись до нього як до методу власноруч створеного екземпляра `Math` (`Math` не є конструктором).
```

2021-12-25 16:34 UTC, undead404 commented on files/uk/web/javascript/reference/global_objects/math/log2/index.md
> +Якщо значення `x` менше за 0, повернене значення завжди дорівнює {{jsxref("NaN")}}.
```suggestion
Якщо значення `x` менше за 0, то повернене значення завжди {{jsxref("NaN")}}.
```

2021-12-30 21:56 UTC, undead404 approved these changes

2021-12-30 23:03 UTC, merged