translation(JS): /Web/JavaScript/Reference/Global_Objects/Math/imul
webdoky/content pull request #130
Opened 2021-11-30 23:33 UTC by AdriandeCita

Original content: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Math/imul

2021-12-09 21:38 UTC, AdriandeCita commented on files/uk/web/javascript/reference/global_objects/math/imul/index.md
> +Оскільки `imul()` — це статичний метод об'єкта `Math`, його потрібно завжди використовувати через `Math.imul()`. Не слід звертатись до нього, як до методу створеного вами об'єкту `Math` (`Math` не є
```suggestion
Оскільки `imul()` — це статичний метод об'єкта `Math`, його потрібно завжди використовувати через `Math.imul()`. Не слід звертатись до нього, як до методу власноруч створеного екземпляра `Math` (`Math` не є конструктором).
```

2021-12-25 16:54 UTC, undead404 requested changes

2021-12-25 16:54 UTC, undead404 commented on files/uk/web/javascript/reference/global_objects/math/imul/index.md
> +`Math.imul()` дозволяє множити 32-бітні цілі числа з традиційною для C семантикою. Цей функціонал корисний для таких проєктів, як [Emscripten](https://en.wikipedia.org/wiki/Emscripten).
```suggestion
`Math.imul()` дає змогу множити 32-бітні цілі числа з традиційною для C семантикою. Цей функціонал корисний для таких проєктів, як [Emscripten](https://en.wikipedia.org/wiki/Emscripten).
```

2021-12-25 16:54 UTC, undead404 commented on files/uk/web/javascript/reference/global_objects/math/imul/index.md
> +Оскільки `imul()` — це статичний метод об'єкта `Math`, його потрібно завжди використовувати через `Math.imul()`. Не слід звертатись до нього, як до методу власноруч створеного екземпляра `Math` (`Mat
```suggestion
Оскільки `imul()` — це статичний метод об'єкта `Math`, його потрібно завжди використовувати через `Math.imul()`. Не слід звертатись до нього як до методу власноруч створеного екземпляра `Math` (`Math` не є конструктором).
```

2021-12-25 16:54 UTC, undead404 commented on files/uk/web/javascript/reference/global_objects/math/imul/index.md
> +Якщо використати звичайні для JavaScript числа з рухомою комою в `imul`, ви помітите суттєву деградацію продуктивності коду. Це відбувається у зв'язку з дорогим перетворенням чисел з рухомою комою в
```suggestion
Якщо використати звичайні для JavaScript числа з рухомою комою в `imul`, ви помітите суттєву деградацію продуктивності коду. Це відбувається у зв'язку з дорогим перетворенням чисел з рухомою комою на цілі числа для множення, і наступною конвертацією цілочисельного результату множення назад у число з рухомою комою. Причина існування `imul` полягає в тому, що ця функція швидша в одному (поки що) разі, а саме — AsmJS. AsmJS дозволяє JIT-оптимізаторам простіше реалізовувати цілі числа всередині JavaScript. Множення двох чисел, внутрішньо збережених як цілі числа (що можливо лише з AsmJS) через `imul` — це єдина ситуація, де `Math.imul` може бути ефективним в сучасних браузерах.
```

2021-12-25 16:54 UTC, undead404 commented on files/uk/web/javascript/reference/global_objects/math/imul/index.md
> +  // кінцеве |0 перетворює беззнакове значення у число зі знаком
```suggestion
  // кінцеве |0 перетворює беззнакове значення на число зі знаком
```

2021-12-25 16:54 UTC, undead404 commented on files/uk/web/javascript/reference/global_objects/math/imul/index.md
> +  opB |= 0; // впевнимося, що opB — ціле число. opA буде приведено автоматично.
```suggestion
  opB |= 0; // впевнімося, що opB — ціле число. opA буде приведено автоматично.
```

2021-12-30 21:56 UTC, undead404 approved these changes

2021-12-30 23:03 UTC, merged