translation(CSS): web/css/css_flexible_box_layout
webdoky/content pull request #1302
Opened 2023-02-07 09:08 UTC by undead404

Оригінальний вміст: [CSS Flexible Box Layout@MDN](https://developer.mozilla.org/en-us/docs/Web/CSS/CSS_Flexible_Box_Layout), [сирці CSS Flexible Box Layout@GitHub](https://github.com/mdn/content/blob/main/files/en-us/web/css/css_flexible_box_layout/index.md)

Залежить від:
* https://github.com/webdoky/css-examples/pull/2

2023-02-21 14:28 UTC, KlashReik commented on files/uk/web/css/css_flexible_box_layout/index.md
> +В наступному прикладі контейнер отримує `display: flex`, що означає, що три дочірні елементи стають гнучкими елементами. Значенням `justify-content` стало `space-between`, щоб розташувати елементи рі
```suggestion
В наступному прикладі контейнер отримує `display: flex`, що означає, що три дочірні елементи стають гнучкими елементами. Значенням `justify-content` стало `space-between`, щоб розташувати елементи рівномірно на головній осі. Однакова кількість простору розташовується між всіма елементами, а лівий і правий елементи знаходяться на краях гнучкого контейнера. Також можна спостерігати, що елементи розтягуються на поперечній осі, адже значення `align-items` – `stretch`. Елементи розтягуються до висоти гнучкого контейнера, тобто кожен з них стає настільки ж високим, як найвищий елемент.
```

2023-02-21 14:44 UTC, KlashReik commented on files/uk/web/css/css_flexible_box_layout/index.md
> +- [Майстерність загортання гнучких елементів](/uk/docs/Web/CSS/CSS_Flexible_Box_Layout/Mastering_Wrapping_of_Flex_Items)
```suggestion
- [Освоєння загортання гнучких елементів](/uk/docs/Web/CSS/CSS_Flexible_Box_Layout/Mastering_Wrapping_of_Flex_Items)
```

2023-03-13 10:01 UTC, AdriandeCita requested changes
Згідно з коментарями

2023-03-13 10:01 UTC, AdriandeCita commented on files/uk/web/css/css_flexible_box_layout/index.md
> +title: Компонування Гнучкої рамки CSS (Флексбокс)
Або так
```suggestion
title: Компонування Гнучкої Рамки CSS
```

2023-03-13 15:56 UTC, undead404 commented on files/uk/web/css/css_flexible_box_layout/index.md
> +title: Компонування Гнучкої рамки CSS (Флексбокс)
Всі великі літери – точно ні, а Флексбокс і Гнучка рамка – це дві альтернативні назви концепції, тому хотів би це виділити. Подумаю іще

2023-03-13 15:57 UTC, undead404 commented
Частково прийняв, іще думаю

2023-03-16 08:26 UTC, undead404 commented
Прийняв один з варіантів

2023-03-31 10:43 UTC, AdriandeCita approved these changes

2023-03-31 10:44 UTC, merged