translation(CSS): web/css/css_box_model/mastering_margin_collapsing
webdoky/content pull request #1306
Opened 2023-02-08 14:19 UTC by undead404

Оригінальний вміст: [Mastering margin collapsing@MDN](https://developer.mozilla.org/en-us/docs/Web/CSS/CSS_Box_Model/Mastering_margin_collapsing), [сирці Mastering margin collapsing@GitHub](https://github.com/mdn/content/blob/main/files/en-us/web/css/css_box_model/mastering_margin_collapsing/index.md)

2023-03-02 13:27 UTC, undead404 commented
Оновлено

2023-05-14 13:57 UTC, undead404 commented on files/uk/web/css/css_box_model/mastering_margin_collapsing/index.md
> +  - [Успадкування](/uk/docs/Web/CSS/inheritance)
```suggestion
  - [Успадкування](/uk/docs/Web/CSS/Inheritance)
```

2023-05-14 13:57 UTC, undead404 commented on files/uk/web/css/css_box_model/mastering_margin_collapsing/index.md
> +- Зовнішні поля не перекриваються в контейнері, котрий має властивість `display` зі значенням `flex`.
```suggestion
- Зовнішні поля не перекриваються в контейнері, котрий має властивість `display` зі значенням `flex` або `grid`.
```

2023-05-14 13:57 UTC, undead404 commented
Оновлено

2023-05-14 20:04 UTC, AdriandeCita commented on files/uk/web/css/css_box_model/mastering_margin_collapsing/index.md
> +  - : Зовнішні поля сусідніх сестринських елементів – перекриваються (окрім випадків, коли друга з сестер потребує [звільнення](/uk/docs/Web/CSS/clear) від пливних сусідів).
неузгоджено: сестра - це вона, а елемент - він. Може "нащадки"?

Також не зовсім зрозуміло про "звільнення", я не пригадую його вживання в такому контексті. Першою асоціацією виникає "звільнення від бусурманів". І хоча певна доля правди в тому є, елементи можуть потребувати певного "звільнення" від "впливу" пливних елементів -- стаття про clearfix говорить більше про "clear" в сенсі "звільнення простору від пливних елементів". Я б запропонував варіант "очищення" в сенсі "очищення рядка" (що доволі близько описує суть процесу) - та от біда, всюди кажуть "переведення на новий рядок", а не очищення. Навіть англійською "clear" не використовується в такому контексті.

Тож пропоную варіант "розчищення", мені він здається більш однозначним
```suggestion
  - : Зовнішні поля сусідніх сестринських елементів – перекриваються (окрім випадків, коли другий з нащадків потребує [розчищення](/uk/docs/Web/CSS/clear) від пливних сусідів).
```

2023-05-14 20:05 UTC, AdriandeCita commented on files/uk/web/css/css_box_model/mastering_margin_collapsing/index.md
> +  - : Якщо немає меж, внутрішніх відступів, рядкового вмісту, не створюється [блоковий контекст форматування](/uk/docs/Web/Guide/CSS/Block_formatting_context), не відбувається _[звільнення](/uk/docs/
```suggestion
  - : Якщо немає меж, внутрішніх відступів, рядкового вмісту, не створюється [блоковий контекст форматування](/uk/docs/Web/Guide/CSS/Block_formatting_context), не відбувається _[розчищення](/uk/docs/Web/CSS/clear)_, що відділяло б {{cssxref("margin-top")}} блока від {{cssxref("margin-top")}} одного чи більше його блоків-нащадків; або коли немає меж, внутрішніх відступів, рядкового вмісту, {{cssxref("height")}} або {{cssxref("min-height")}}, котрі відділяли б {{cssxref("margin-bottom")}} блока від {{cssxref("margin-bottom")}} одного чи більше його блоків-нащадків, то такі зовнішні поля – перекриваються. Перекрите зовнішнє поле опиняється зовні батьківського елемента.
```

2023-05-14 20:07 UTC, AdriandeCita reviewed
Є трохи зауважень, здебільшого стосовно термінології

2023-05-14 20:07 UTC, AdriandeCita requested changes
відповідно до коментарів

2023-05-17 21:42 UTC, AdriandeCita approved these changes

2023-05-17 21:42 UTC, merged