translation(JS): web/javascript/inheritance_and_the_prototype_chain
webdoky/content pull request #1308
Opened 2023-02-11 16:30 UTC by undead404

Оригінальний вміст: [Inheritance and the prototype chain@MDN](https://developer.mozilla.org/en-us/docs/Web/JavaScript/Inheritance_and_the_prototype_chain), [сирці Inheritance and the prototype chain@GitHub](https://github.com/mdn/content/blob/main/files/en-us/web/javascript/inheritance_and_the_prototype_chain/index.md)

2023-03-02 13:30 UTC, undead404 commented
Оновлено

2023-03-08 15:18 UTC, undead404 commented
Розв'язано конфлікт

2023-03-13 09:02 UTC, undead404 commented
Розв'язано конфлікт

2023-03-13 09:10 UTC, undead404 commented
Оновлено

2023-03-30 10:45 UTC, undead404 commented
Розв'язано конфлікт

2023-06-09 10:42 UTC, Aenqau requested changes

2023-06-09 10:42 UTC, Aenqau commented on files/uk/web/javascript/inheritance_and_the_prototype_chain/index.md
> +        Не підтримується в IE8 та старіших версіях. Проте оскільки Microsoft припинила розширену підтримку систем, що працюють з IE та старшими версіями, це не повинно бути проблемою для більшості за
```suggestion
        Не підтримується в IE8 та старіших версіях. Проте оскільки Microsoft припинила розширену підтримку систем, що працюють з IE8 та старшими версіями, це не повинно бути проблемою для більшості застосунків. На додачу, повільна ініціалізація об'єктів може бути чорною дірою швидкодії, якщо використовувати другий аргумент, тому що кожна об'єктно-дескрипторна властивість має власний окремий об'єкт-дескриптор. При роботі з сотнями тисяч об'єктних дескрипторів у вигляді об'єктів, такі затримки можуть стати суттєвою проблемою.
```

2023-06-09 10:42 UTC, Aenqau commented on files/uk/web/javascript/inheritance_and_the_prototype_chain/index.md
> +        Не підтримується в IE8 та старіших версіях. Проте оскільки Microsoft припинила розширену підтримку систем, що працюють з IE та старшими версіями, це не повинно бути проблемою для більшості за
<img width="842" alt="image" src="https://github.com/webdoky/content/assets/11777713/b37df472-abe3-4f11-9413-0811f2c5ba1b">

2023-06-10 19:13 UTC, Aenqau approved these changes

2023-06-10 19:13 UTC, merged