translation(JS): /Web/JavaScript/Reference/Global_Objects/Math/hypot
webdoky/content pull request #131
Opened 2021-11-30 23:33 UTC by AdriandeCita

Original content: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Math/hypot

2021-12-09 21:38 UTC, AdriandeCita commented on files/uk/web/javascript/reference/global_objects/math/hypot/index.md
> +Оскільки `hypot()` — це статичний метод об'єкта `Math`, його потрібно завжди використовувати через `Math.hypot()`. Не слід звертатись до нього, як до методу створеного вами об'єкту `Math` (`Math` не
```suggestion
Оскільки `hypot()` — це статичний метод об'єкта `Math`, його потрібно завжди використовувати через `Math.hypot()`. Не слід звертатись до нього, як до методу власноруч створеного екземпляра `Math` (`Math` не є конструктором).
```

2021-12-25 17:00 UTC, undead404 requested changes

2021-12-25 17:00 UTC, undead404 commented on files/uk/web/javascript/reference/global_objects/math/hypot/index.md
> +Math.hypot(-3);            // 3, the same as Math.abs(-3)
```suggestion
Math.hypot(-3);            // 3, еквівалентно до Math.abs(-3)
```

2021-12-30 21:57 UTC, undead404 approved these changes

2021-12-30 23:03 UTC, merged