update(CSS): web/css/css_animations/using_css_animations
webdoky/content pull request #1313
Opened 2023-02-12 10:29 UTC by undead404

Оригінальний вміст: [Застосування анімацій CSS@MDN](https://developer.mozilla.org/en-us/docs/Web/CSS/CSS_Animations/Using_CSS_animations), [сирці Застосування анімацій CSS@GitHub](https://github.com/mdn/content/blob/main/files/en-us/web/css/css_animations/using_css_animations/index.md)

Нові зміни:
- [mdn/content@4e002d2](https://github.com/mdn/content/commit/4e002d26cb032c915aeee366f922f23cbacd8bf1)

2023-02-19 13:15 UTC, AdriandeCita commented on files/uk/web/css/css_animations/using_css_animations/index.md
> +Застосуймо код JavaScript для слухання всіх трьох можливих подій анімації. Код нижче налаштовує слухачів коду; він викликається, коли документ завантажився, щоб усе приготувати.
```suggestion
Застосуймо код JavaScript для слухання всіх трьох можливих подій анімації. Код нижче налаштовує слухачів подій; він викликається, коли документ завантажився, щоб усе приготувати.
```

2023-02-19 13:16 UTC, AdriandeCita requested changes
Маленьке доповнення

2023-03-07 13:36 UTC, undead404 commented
Оновлено

2023-03-07 13:37 UTC, AdriandeCita approved these changes

2023-03-07 13:37 UTC, merged