translation(JS): Math tan and tanh
webdoky/content pull request #133
Opened 2021-11-30 23:34 UTC by AdriandeCita

Original content: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Math/tan, https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Math/tanh

2021-12-09 21:39 UTC, AdriandeCita commented on files/uk/web/javascript/reference/global_objects/math/tanh/index.md
> +Оскільки `tanh()` — це статичний метод об'єкта `Math`, його потрібно завжди використовувати через `Math.tanh()`. Не слід звертатись до нього, як до методу створеного вами об'єкту `Math` (`Math` не є
```suggestion
Оскільки `tanh()` — це статичний метод об'єкта `Math`, його потрібно завжди використовувати через `Math.tanh()`. Не слід звертатись до нього, як до методу власноруч створеного екземпляра `Math` (`Math` не є конструктором).
```

2021-12-25 17:09 UTC, undead404 requested changes

2021-12-25 17:09 UTC, undead404 commented on files/uk/web/javascript/reference/global_objects/math/tan/index.md
> +Оскільки `tan()` — це статичний метод об'єкта `Math`, його потрібно завжди використовувати через `Math.tan()`. Не слід звертатись до нього, як до методу власноруч створеного екземпляра `Math` (`Math`
```suggestion
Оскільки `tan()` — це статичний метод об'єкта `Math`, його потрібно завжди використовувати через `Math.tan()`. Не слід звертатись до нього як до методу власноруч створеного екземпляра `Math` (`Math` не є конструктором).
```
https://onlinecorrector.com.ua/uk/%D0%BA%D0%BE%D0%BC%D0%B0-%D0%BF%D0%B5%D1%80%D0%B5%D0%B4-%D0%BF%D0%BE%D1%80%D1%96%D0%B2%D0%BD%D1%8F%D0%BB%D1%8C%D0%BD%D0%B8%D0%BC-%D0%B7%D0%B2%D0%BE%D1%80%D0%BE%D1%82%D0%BE%D0%BC/

2021-12-25 17:09 UTC, undead404 commented on files/uk/web/javascript/reference/global_objects/math/tan/index.md
> +У зв'язку з тим, що функція `Math.tan()` приймає значення в радіанах, проте часто зручніше працювати з градусами, наступна функція приймає значення в градусах, перетворює його в радіани, і повертає т
```suggestion
У зв'язку з тим, що функція `Math.tan()` приймає значення в радіанах, проте часто зручніше працювати з градусами, наступна функція приймає значення в градусах, перетворює його в радіани – і повертає тангенс.
```

2021-12-25 17:09 UTC, undead404 commented on files/uk/web/javascript/reference/global_objects/math/tanh/index.md
> +Оскільки `tanh()` — це статичний метод об'єкта `Math`, його потрібно завжди використовувати через `Math.tanh()`. Не слід звертатись до нього, як до методу власноруч створеного екземпляра `Math` (`Mat
```suggestion
Оскільки `tanh()` — це статичний метод об'єкта `Math`, його потрібно завжди використовувати через `Math.tanh()`. Не слід звертатись до нього як до методу власноруч створеного екземпляра `Math` (`Math` не є конструктором).
```

2021-12-30 20:07 UTC, AdriandeCita commented on files/uk/web/javascript/reference/global_objects/math/tan/index.md
> +Оскільки `tan()` — це статичний метод об'єкта `Math`, його потрібно завжди використовувати через `Math.tan()`. Не слід звертатись до нього, як до методу власноруч створеного екземпляра `Math` (`Math`
порівняльний зворот, ага... Я взагалі хз, чи я це запам'ятаю з першого разу, але принаймні додам в закладки

2021-12-30 21:57 UTC, undead404 approved these changes

2021-12-30 23:03 UTC, merged