update(HTML): web/html/element
webdoky/content pull request #1334
Opened 2023-02-28 09:59 UTC by undead404

Оригінальний вміст: [Довідник елементів HTML@MDN](https://developer.mozilla.org/en-us/docs/Web/HTML/Element), [сирці Довідник елементів HTML@GitHub](https://github.com/mdn/content/blob/main/files/en-us/web/html/element/index.md)

Нові зміни:
- [mdn/content@aab3135](https://github.com/mdn/content/commit/aab3135e4dd89dd419826b7d3a7ca1ac59e4e282)
- [mdn/content@c05df13](https://github.com/mdn/content/commit/c05df137bd9ea1148b03f2f158b5e5fb77d08beb)
- [mdn/content@95fa3de](https://github.com/mdn/content/commit/95fa3ded73a1662f201e47b0e80c4902c30ef2ef)
- [mdn/content@b05f6a6](https://github.com/mdn/content/commit/b05f6a6d07f6c6a1d8416ba3f8ce392d1e701684)

2023-03-06 15:41 UTC, undead404 commented
Оновлено

2023-03-09 10:13 UTC, KlashReik commented on files/uk/web/html/element/index.md
> +| {{HTMLElement("dfn")}}    | Вживається на позначення терміну, що означається, в межах контексту фрази або речення визначення. Визначенням цього терміну вважається елемент-предок {{HTMLElement("p")}
```suggestion
| {{HTMLElement("dfn")}}    | Вживається на позначення терміну, що визначається, в межах контексту фрази або речення. Визначенням цього терміну вважається елемент-предок {{HTMLElement("p")}}, пара {{HTMLElement("dt")}} і {{HTMLElement("dd")}} або найближчий розділовий предок елемента `<dfn>`.                                                                                                                                                                                                                                                                               |
```

2023-03-09 10:33 UTC, KlashReik commented on files/uk/web/html/element/index.md
> +| {{HTMLElement("ruby")}}   | Представляє невеликі анотації, що виводяться над, під або після тексту і зазвичай використовуються для виведення вимови східноазійських символів. It can also be used for
```suggestion
| {{HTMLElement("ruby")}}   | Представляє невеликі анотації, що виводяться над, під або після тексту і зазвичай використовуються для виведення вимови східноазійських символів. Також може вживатися для анотування тексту іншого роду, але таке вжиття – менш поширене.                                                                                                                                                                                                                               |
```

2023-03-09 15:21 UTC, KlashReik commented on files/uk/web/html/element/index.md
> +| {{HTMLElement("slot")}}     | Частина технологічного блоку [Вебкомпонентів](/uk/docs/Web/Web_Components); цей елемент є гніздом всередині вебкомпонента, котрий можна заповнити власною розміткою, що
```suggestion
| {{HTMLElement("slot")}}     | Частина технологічного блоку [Вебкомпонентів](/uk/docs/Web/Web_Components); цей елемент є заповнювачем всередині вебкомпонента, котрий можна заповнити власною розміткою, що дає змогу створювати окремі дерева DOM і виводити їх разом. |
```

2023-03-09 15:23 UTC, KlashReik commented on files/uk/web/html/element/index.md
> +| {{HTMLElement("template")}} | A mechanism for holding HTML that is not to be rendered immediately when a page is loaded but may be instantiated subsequently during runtime using JavaScript.
Не перекладено. Мій варіант:
Механізм для зберігання HTML, що не повинен відображатися одразу після завантаження сторінки, проте може створити його примірник згодом під час виконання Javascript.

2023-03-09 15:29 UTC, KlashReik commented on files/uk/web/html/element/index.md
> +| {{HTMLElement("keygen")}}    | Існує для організації генерування ключа, а також подання публічного ключа як частини [форми HTML](/uk/docs/Learn/Forms). Цей механізм розроблений для використання в с
```suggestion
| {{HTMLElement("keygen")}}    | Існує для організації генерування ключа, а також подання публічного ключа як частини [форми HTML](/uk/docs/Learn/Forms). Цей механізм розроблений для використання в системах керування сертифікатами, заснованих на вебтехнологіях. Очікується, що елемент `<keygen>` використовується в формі HTML поруч з іншою інформацією, необхідною для конструювання запиту на сертифікат, і що результатом процесу буде підписаний сертифікат.    |
```
Пропущено пробіл)

2023-03-10 07:25 UTC, undead404 commented on files/uk/web/html/element/index.md
> +| {{HTMLElement("template")}} | A mechanism for holding HTML that is not to be rendered immediately when a page is loaded but may be instantiated subsequently during runtime using JavaScript.
Супер, закидай suggestion

2023-03-10 10:47 UTC, KlashReik commented on files/uk/web/html/element/index.md
> +| {{HTMLElement("template")}} | A mechanism for holding HTML that is not to be rendered immediately when a page is loaded but may be instantiated subsequently during runtime using JavaScript.
```suggestion
| {{HTMLElement("template")}} | Механізм для зберігання HTML, що не повинен відображатися одразу після завантаження сторінки, проте може створити його примірник згодом під час виконання JavaScript.                                                                    |
```

2023-03-10 10:53 UTC, KlashReik commented on files/uk/web/html/element/index.md
> +| {{HTMLElement("slot")}}     | Частина технологічного блоку [Вебкомпонентів](/uk/docs/Web/Web_Components); цей елемент є гніздом всередині вебкомпонента, котрий можна заповнити власною розміткою, що
```suggestion
| {{HTMLElement("slot")}}     | Частина технологічного блоку [Вебкомпонентів](/uk/docs/Web/Web_Components); цей елемент є слотом всередині вебкомпонента, котрий можна заповнити власною розміткою, що дає змогу створювати окремі дерева DOM і виводити їх разом. |
```

2023-03-11 09:58 UTC, AdriandeCita requested changes
Трохи є зауважень

2023-03-11 09:58 UTC, AdriandeCita commented on files/uk/web/html/element/index.md
> +| {{HTMLElement("kbd")}}    | Представляє уривок тексту, що позначає текст, введений з клавіатури, диктування голосом або будь-якого іншого пристрою введення тексту. Заведено, що користувацький агент
пропоную дещо перефразувати, бо "диктування голосом" звучить саме як процес диктування, а не пристрій вводу. Тут або явно вказувати "пристрою диктування голосом" (що теж не аж, насправді), або якось так:
```suggestion
| {{HTMLElement("kbd")}}    | Представляє уривок тексту, що позначає текст, введений з клавіатури, голосового вводу або будь-якого іншого пристрою введення тексту. Заведено, що користувацький агент усталено виводить вміст елемента `<kbd>` за допомогою свого усталеного моноширинного шрифту, попри те, що цього не вимагає стандарт HTML.                                                                                                                                                                                                                                             |
```

2023-03-11 09:58 UTC, AdriandeCita commented on files/uk/web/html/element/index.md
> +| {{HTMLElement("area")}}  | Задає область всередині карти зображення, котра має наперед визначені зони для клацання. _Карта зображення_ дає геометричним зонам на зображенні бути пов'язаними з {{Glos
"дає...бути" - пропоную перефразувати
```suggestion
| {{HTMLElement("area")}}  | Задає область всередині карти зображення, котра має наперед визначені зони для клацання. _Карта зображення_ дає змогу пов'язувати геометричні зони на зображенні з {{Glossary("Hyperlink", "гіперпосиланнями")}}.                                                                                                                       |
```

2023-03-11 09:58 UTC, AdriandeCita commented on files/uk/web/html/element/index.md
> +| {{HTMLElement("embed")}}   | Вставляє зовнішній вміст у задане місце документа. Такий вміст надається зовнішнім застосунком або іншим джерелом інтерактивного вмісту, як то втулком браузера.
Звучить цікаво, але я не знайшов прикладів вживання терміну "втулОк" в однині, тим паче в такому контексті. Пропоную замінити більш традиційним https://uk.wikipedia.org/wiki/%D0%9F%D0%BB%D0%B0%D0%B3%D1%96%D0%BD
```suggestion
| {{HTMLElement("embed")}}   | Вставляє зовнішній вміст у задане місце документа. Такий вміст надається зовнішнім застосунком або іншим джерелом інтерактивного вмісту, як то плагін браузера.                                                                                                                                                                                                                                                                                       |
```

2023-03-11 09:58 UTC, AdriandeCita commented on files/uk/web/html/element/index.md
> +| {{HTMLElement("object")}}  | Представляє зовнішній ресурс, котрий може оброблятися як зображення, вкладений контекст перегляду, або ресурс, що повинен оброблятися втулком.
```suggestion
| {{HTMLElement("object")}}  | Представляє зовнішній ресурс, котрий може оброблятися як зображення, вкладений контекст перегляду, або ресурс, що повинен оброблятися плагіном.                                                                                                                                                                                                                                                                                                         |
```

2023-03-11 09:58 UTC, AdriandeCita commented on files/uk/web/html/element/index.md
> +| {{HTMLElement("picture")}} | Містить нуль або більше елементів {{HTMLElement("source")}}, а також один елемент {{HTMLElement("img")}}, аби запропонувати різні варіанти зображення для різних випадкі
"випадок виведення" звучить трохи дивно
```suggestion
| {{HTMLElement("picture")}} | Містить нуль або більше елементів {{HTMLElement("source")}}, а також один елемент {{HTMLElement("img")}}, аби запропонувати різні варіанти зображення для різних пристроїв та варіантів виведення.                                                                                                                                                                                                                                                      |
```

2023-03-11 09:58 UTC, AdriandeCita commented on files/uk/web/html/element/index.md
> +| {{HTMLElement("textarea")}} | Представляє багаторядковий контрольний елемент для редагування простого тексту, корисний, аби дати користувачам змогу ввести суттєву кількість тексту довільної форми,
звучить наче в textarea можна ввести цілу "форму зворотного зв'язку", пропоную переформулювати. Плюс review в цьому контексті — це радше про відгук, ніж про огляд
```suggestion
| {{HTMLElement("textarea")}} | Представляє багаторядковий контрольний елемент для редагування простого тексту, корисний, аби дати користувачам змогу ввести суттєву кількість тексту довільної форми, наприклад, коментар у формі відгуку або зворотного зв'язку.                                                                                                                                        |
```

2023-03-11 09:58 UTC, AdriandeCita commented on files/uk/web/html/element/index.md
> +| {{HTMLElement("details")}} | Створює відгук розгортання, в якому інформація видима лише тоді, коли віджет переключений в стан "відкритості". Повинен бути виведений підсумок або підпис – за допомого
Мені здається, в оригіналі мається на увазі, що цьому елементу треба обов'язково надати якийсь підпис чи саммарі, інакше він не працюватиме (йому не буде що розгортати)
```suggestion
| {{HTMLElement("details")}} | Створює віджет розгортання, в якому інформація видима лише тоді, коли він переключений в стан "відкритості". Повинен бути наданий підсумок або підпис – за допомогою елемента {{HTMLElement("summary")}}. |
```

2023-03-11 09:58 UTC, AdriandeCita commented on files/uk/web/html/element/index.md
> +| {{HTMLElement("template")}} | A mechanism for holding HTML that is not to be rendered immediately when a page is loaded but may be instantiated subsequently during runtime using JavaScript.
Єдине зауваження, не зовсім зрозуміло кого мається на увазі в "його примірник". По факту він використовується для інстанціації самого себе
```suggestion
| {{HTMLElement("template")}} | Механізм для зберігання HTML, що не повинен відображатися одразу після завантаження сторінки, проте може створити свій примірник згодом під час виконання JavaScript.                                                                     |
```

2023-03-11 09:58 UTC, AdriandeCita commented on files/uk/web/html/element/index.md
> +| {{HTMLElement("content")}}   | Застаріла частина блоку технологій [Вебкомпонентів](/uk/docs/Web/Web_Components), що використовувалася всередині [тіньового DOM](/uk/docs/Web/Web_Components/Using_sha
Думаю, доречніше вжити жіночий рід, оскільки "Об'єктна модель документа — DOM"
```suggestion
| {{HTMLElement("content")}}   | Застаріла частина блоку технологій [Вебкомпонентів](/uk/docs/Web/Web_Components), що використовувалася всередині [тіньової DOM](/uk/docs/Web/Web_Components/Using_shadow_DOM) як точка вставки, і для використання у звичайному HTML не планувалася. Тепер цей елемент замінений елементом {{HTMLElement("slot")}}, котрий створює точку в DOM, в якій може бути вставлено тіньову DOM.                                                |
```

2023-03-11 09:58 UTC, AdriandeCita commented on files/uk/web/html/element/index.md
> +| {{HTMLElement("nobr")}}      | Запобігає автоматичному загортанню тексту всередині на кілька рядків, що може призвести до того, що користувачу доведеться використати горизонтальне прокручення, аби
Тут мається на увазі перенос
```suggestion
| {{HTMLElement("nobr")}}      | Запобігає автоматичному переносу тексту всередині на кілька рядків, що може призвести до того, що користувачу доведеться використати горизонтальне прокручення, аби побачити ввесь текст.                                                                                                                                                                                                                                               |
```

2023-03-11 09:58 UTC, AdriandeCita commented on files/uk/web/html/element/index.md
> +| {{HTMLElement("shadow")}}    | Застаріла частина технологічного блоку [Вебкомпонентів](/uk/docs/Web/Web_Components), котра планувалася для використання як точка вставки тіньового DOM. Можливо, ви в
```suggestion
| {{HTMLElement("shadow")}}    | Застаріла частина технологічного блоку [Вебкомпонентів](/uk/docs/Web/Web_Components), котра планувалася для використання як точка вставки тіньової DOM. Можливо, ви використовували його, якщо створювали декілька тіньових коренів усередині тіньового хоста.                                                                                                                                                                           |
```

2023-03-13 09:20 UTC, undead404 commented
Перевірив: усе актуально

2023-03-31 10:47 UTC, AdriandeCita approved these changes

2023-03-31 10:47 UTC, merged