translation(JS): Math round and trunc
webdoky/content pull request #134
Opened 2021-11-30 23:35 UTC by AdriandeCita

Original content: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Math/round, https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Math/trunc

2021-12-09 21:39 UTC, AdriandeCita commented on files/uk/web/javascript/reference/global_objects/math/round/index.md
> +Оскільки `round()` — це статичний метод об'єкта `Math`, його потрібно завжди використовувати через `Math.round()`. Не слід звертатись до нього, як до методу створеного вами об'єкту `Math` (`Math` не
```suggestion
Оскільки `round()` — це статичний метод об'єкта `Math`, його потрібно завжди використовувати через `Math.round()`. Не слід звертатись до нього, як до методу власноруч створеного екземпляра `Math` (`Math` не є конструктором).
```

2021-12-09 21:39 UTC, AdriandeCita commented on files/uk/web/javascript/reference/global_objects/math/trunc/index.md
> +Оскільки `trunc()` — це статичний метод об'єкта `Math`, його потрібно завжди використовувати через `Math.trunc()`. Не слід звертатись до нього, як до методу створеного вами об'єкту `Math` (`Math` не
```suggestion
Оскільки `trunc()` — це статичний метод об'єкта `Math`, його потрібно завжди використовувати через `Math.trunc()`. Не слід звертатись до нього, як до методу власноруч створеного екземпляра `Math` (`Math` не є конструктором).
```

2021-12-25 17:15 UTC, undead404 requested changes

2021-12-25 17:15 UTC, undead404 commented on files/uk/web/javascript/reference/global_objects/math/round/index.md
> +Оскільки `round()` — це статичний метод об'єкта `Math`, його потрібно завжди використовувати через `Math.round()`. Не слід звертатись до нього, як до методу власноруч створеного екземпляра `Math` (`M
```suggestion
Оскільки `round()` — це статичний метод об'єкта `Math`, його потрібно завжди використовувати через `Math.round()`. Не слід звертатись до нього як до методу власноруч створеного екземпляра `Math` (`Math` не є конструктором).
```

2021-12-25 17:15 UTC, undead404 commented on files/uk/web/javascript/reference/global_objects/math/trunc/index.md
> +{{jsxref("Math.ceil()")}} та {{jsxref("Math.round()")}}, — `Math.trunc()` працює дуже просто. Вона *відкидає* (обрізає) крапку та всі цифри справа від неї, не дивлячись на те, чи це аргумент є додатн
```suggestion
{{jsxref("Math.ceil()")}} та {{jsxref("Math.round()")}}, — `Math.trunc()` працює дуже просто. Вона *відкидає* (обрізає) крапку та всі цифри справа від неї, не зважаючи на те, чи аргумент є додатним числом, чи від'ємним.
```

2021-12-25 17:15 UTC, undead404 commented on files/uk/web/javascript/reference/global_objects/math/trunc/index.md
> +Оскільки `trunc()` — це статичний метод об'єкта `Math`, його потрібно завжди використовувати через `Math.trunc()`. Не слід звертатись до нього, як до методу власноруч створеного екземпляра `Math` (`M
```suggestion
Оскільки `trunc()` — це статичний метод об'єкта `Math`, його потрібно завжди використовувати через `Math.trunc()`. Не слід звертатись до нього як до методу власноруч створеного екземпляра `Math` (`Math` не є конструктором).
```

2021-12-30 21:57 UTC, undead404 approved these changes

2021-12-30 23:03 UTC, merged