translation(JS): Math sin and sinh
webdoky/content pull request #135
Opened 2021-11-30 23:35 UTC by AdriandeCita

Original content: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Math/sin, https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Math/sinh

2021-12-09 21:40 UTC, AdriandeCita commented on files/uk/web/javascript/reference/global_objects/math/sinh/index.md
> +Оскільки `sinh()` — це статичний метод об'єкта `Math`, його потрібно завжди використовувати через `Math.sinh()`. Не слід звертатись до нього, як до методу створеного вами об'єкту `Math` (`Math` не є
```suggestion
Оскільки `sinh()` — це статичний метод об'єкта `Math`, його потрібно завжди використовувати через `Math.sinh()`. Не слід звертатись до нього, як до методу власноруч створеного екземпляра `Math` (`Math` не є конструктором).
```

2021-12-25 17:16 UTC, undead404 requested changes

2021-12-25 17:16 UTC, undead404 commented on files/uk/web/javascript/reference/global_objects/math/sin/index.md
> +Оскільки `sin()` — це статичний метод об'єкта `Math`, його потрібно завжди використовувати через `Math.sin()`. Не слід звертатись до нього, як до методу власноруч створеного екземпляра `Math` (`Math`
```suggestion
Оскільки `sin()` — це статичний метод об'єкта `Math`, його потрібно завжди використовувати через `Math.sin()`. Не слід звертатись до нього як до методу власноруч створеного екземпляра `Math` (`Math` не є конструктором).
```

2021-12-25 17:16 UTC, undead404 commented on files/uk/web/javascript/reference/global_objects/math/sinh/index.md
> +Оскільки `sinh()` — це статичний метод об'єкта `Math`, його потрібно завжди використовувати через `Math.sinh()`. Не слід звертатись до нього, як до методу власноруч створеного екземпляра `Math` (`Mat
```suggestion
Оскільки `sinh()` — це статичний метод об'єкта `Math`, його потрібно завжди використовувати через `Math.sinh()`. Не слід звертатись до нього як до методу власноруч створеного екземпляра `Math` (`Math` не є конструктором).
```

2021-12-30 21:58 UTC, undead404 approved these changes

2021-12-30 23:03 UTC, merged