update(JS): web/javascript/reference/global_objects/object/entries
webdoky/content pull request #1353
Opened 2023-02-28 12:29 UTC by undead404

Оригінальний вміст: [Object.entries()@MDN](https://developer.mozilla.org/en-us/docs/Web/JavaScript/Reference/Global_Objects/Object/entries), [сирці Object.entries()@GitHub](https://github.com/mdn/content/blob/main/files/en-us/web/javascript/reference/global_objects/object/entries/index.md)

Нові зміни:
- [mdn/content@fcd80ee](https://github.com/mdn/content/commit/fcd80ee4c8477b6f73553bfada841781cf74cf46)

2023-02-28 21:45 UTC, AdriandeCita commented on files/uk/web/javascript/reference/global_objects/map/index.md
> +  - : Початковим значенням властивості [`@@toStringTag`](/uk/docs/Web/JavaScript/Reference/Global_Objects/Symbol/toStringTag) ж рядок `"Map"`. Вона використовується в {{jsxref("Object.prototype.toStr
```suggestion
  - : Початковим значенням властивості [`@@toStringTag`](/uk/docs/Web/JavaScript/Reference/Global_Objects/Symbol/toStringTag) є рядок `"Map"`. Вона використовується в {{jsxref("Object.prototype.toString()")}}.
```

2023-02-28 21:45 UTC, AdriandeCita commented
Оригінальний вміст: [Map@MDN](https://developer.mozilla.org/en-us/docs/Web/JavaScript/Reference/Global_Objects/Map), [сирці Map@GitHub](https://github.com/mdn/content/blob/main/files/en-us/web/javascript/reference/global_objects/map/index.md)

Нові зміни:
- [mdn/content@d19dc31](https://github.com/mdn/content/commit/d19dc31570f62196a5837be38bd0b11c45e67b05)
- [mdn/content@fcd80ee](https://github.com/mdn/content/commit/fcd80ee4c8477b6f73553bfada841781cf74cf46)

2023-02-28 21:46 UTC, AdriandeCita requested changes
Дрібничка

2023-03-01 05:57 UTC, undead404 commented
Прийняв пропозицію

2023-03-08 15:57 UTC, AdriandeCita approved these changes

2023-03-08 15:58 UTC, merged