translation(JS): Math min and max
webdoky/content pull request #136
Opened 2021-11-30 23:36 UTC by AdriandeCita

Original content: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Math/min, https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Math/max

2021-12-09 21:40 UTC, AdriandeCita commented on files/uk/web/javascript/reference/global_objects/math/max/index.md
> +Оскільки `max()` — це статичний метод об'єкта `Math`, його потрібно завжди використовувати через `Math.max()`. Не слід звертатись до нього, як до методу створеного вами об'єкту `Math` (`Math` не є ко
```suggestion
Оскільки `max()` — це статичний метод об'єкта `Math`, його потрібно завжди використовувати через `Math.max()`. Не слід звертатись до нього, як до методу власноруч створеного екземпляра `Math` (`Math` не є конструктором).
```

2021-12-09 21:40 UTC, AdriandeCita commented on files/uk/web/javascript/reference/global_objects/math/min/index.md
> +Оскільки `min()` — це статичний метод об'єкта `Math`, його потрібно завжди використовувати через `Math.min()`. Не слід звертатись до нього, як до методу створеного вами об'єкту `Math` (`Math` не є ко
```suggestion
Оскільки `min()` — це статичний метод об'єкта `Math`, його потрібно завжди використовувати через `Math.min()`. Не слід звертатись до нього, як до методу власноруч створеного екземпляра `Math` (`Math` не є конструктором).
```

2021-12-25 17:26 UTC, undead404 requested changes

2021-12-25 17:26 UTC, undead404 commented on files/uk/web/javascript/reference/global_objects/math/max/index.md
> +Функція **`Math.max()`** повертає найбільше значення з-поміж переданих нуля чи більше вхідних чисел, або {{jsxref("NaN")}}, якщо будь-який з аргументів не є числом чи не може бути приведений до числа
```suggestion
Функція **`Math.max()`** повертає найбільше значення з-поміж переданих нуля чи більше вхідних чисел, або {{jsxref("NaN")}}, якщо будь-який з аргументів не є числом і не може бути приведений до числа.
```
Логічніше ж так?

2021-12-25 17:26 UTC, undead404 commented on files/uk/web/javascript/reference/global_objects/math/max/index.md
> +Оскільки `max()` — це статичний метод об'єкта `Math`, його потрібно завжди використовувати через `Math.max()`. Не слід звертатись до нього, як до методу власноруч створеного екземпляра `Math` (`Math`
```suggestion
Оскільки `max()` — це статичний метод об'єкта `Math`, його потрібно завжди використовувати через `Math.max()`. Не слід звертатись до нього як до методу власноруч створеного екземпляра `Math` (`Math` не є конструктором).
```

2021-12-25 17:26 UTC, undead404 commented on files/uk/web/javascript/reference/global_objects/math/max/index.md
> +Якщо принаймні один з аргументів не можна привести до числового вигляду, результат дорівнюватиме {{jsxref("NaN")}}.
```suggestion
Якщо принаймні один з аргументів не можна привести до числового вигляду, то результатом буде {{jsxref("NaN")}}.
```

2021-12-25 17:26 UTC, undead404 commented on files/uk/web/javascript/reference/global_objects/math/max/index.md
> +Наступна функція використовує {{jsxref("Function.prototype.apply()")}} для отримання найбільшого елемента масиву. Виклик `getMaxOfArray([1, 2, 3])` еквівалентний застосуванню `Math.max(1, 2, 3)`, але
```suggestion
Наступна функція використовує {{jsxref("Function.prototype.apply()")}} для отримання найбільшого елемента масиву. Виклик `getMaxOfArray([1, 2, 3])` еквівалентний застосуванню `Math.max(1, 2, 3)`, але `getMaxOfArray()` можна використовувати на програмно сконструйованих масивах. Такий підхід слід застосовувати лише на масивах з відносно невеликою кількістю елементів.
```

2021-12-25 17:26 UTC, undead404 commented on files/uk/web/javascript/reference/global_objects/math/max/index.md
> +Новий [спред-оператор](/uk/docs/Web/JavaScript/Reference/Operators/Spread_syntax) — це скорочений спосіб запису рішення з `apply` для отримання найбільшого з елементів масиву:
```suggestion
Новий [оператор розгортання](/uk/docs/Web/JavaScript/Reference/Operators/Spread_syntax) — це скорочений спосіб запису рішення з `apply` для отримання найбільшого з елементів масиву:
```

2021-12-25 17:26 UTC, undead404 commented on files/uk/web/javascript/reference/global_objects/math/max/index.md
> +Однак, як спред-оператор (`...`), так і `apply` або завершаться невдачею, або повернуть некоректне значення, якщо масив містить занадто багато елементів, оскільки вони намагаються передати елементи м
```suggestion
Втім, як оператор розгортання (`...`), так і `apply` – або завершаться невдачею, або повернуть некоректне значення, якщо масив містить занадто багато елементів, оскільки вони намагаються передати елементи масиву аргументами до функції. Зверніть увагу на розділ [Застосування `apply` із вбудованими функціями](/uk/docs/Web/JavaScript/Reference/Global_Objects/Function/apply#using_apply_and_built-in_functions) для отримання подробиць. Рішення з `reduce` не має такої проблеми.
```

2021-12-25 17:26 UTC, undead404 commented on files/uk/web/javascript/reference/global_objects/math/min/index.md
> +Оскільки `min()` — це статичний метод об'єкта `Math`, його потрібно завжди використовувати через `Math.min()`. Не слід звертатись до нього, як до методу власноруч створеного екземпляра `Math` (`Math`
```suggestion
Оскільки `min()` — це статичний метод об'єкта `Math`, його потрібно завжди використовувати через `Math.min()`. Не слід звертатись до нього як до методу власноруч створеного екземпляра `Math` (`Math` не є конструктором).
```

2021-12-25 17:26 UTC, undead404 commented on files/uk/web/javascript/reference/global_objects/math/min/index.md
> +Ця функція знаходить мінімальне з-поміж двох значень `x` та `y`, і присвоює його змінній `z`:
```suggestion
Наступний код знаходить менше з-поміж двох значень `x` та `y` і присвоює його змінній `z`:
```

2021-12-25 17:26 UTC, undead404 commented on files/uk/web/javascript/reference/global_objects/math/min/index.md
> +`Math.min()` часто застосовується для обрізання значення таким чином, щоб воно завжди було меншим, або дорівнювало певній межі. Для прикладу, цей код:
```suggestion
`Math.min()` часто застосовується для обрізання значення таким чином, щоб воно завжди було меншим або рівним відносно певної межі. Для прикладу, наступний код:
```

2021-12-30 20:11 UTC, AdriandeCita commented on files/uk/web/javascript/reference/global_objects/math/max/index.md
> +Функція **`Math.max()`** повертає найбільше значення з-поміж переданих нуля чи більше вхідних чисел, або {{jsxref("NaN")}}, якщо будь-який з аргументів не є числом чи не може бути приведений до числа
Справедливо. В оригіналі там здається таки `or`, але справді, нахіба нам приводити щось до числа, якщо воно вже число (і тим паче, ловити під час цього `NaN`)

2021-12-30 21:58 UTC, undead404 approved these changes

2021-12-30 23:03 UTC, merged