translation(JS): /Web/JavaScript/Reference/Global_Objects/Math/fround
webdoky/content pull request #137
Opened 2021-11-30 23:36 UTC by AdriandeCita

Original content: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Math/fround

2021-12-09 21:41 UTC, AdriandeCita commented on files/uk/web/javascript/reference/global_objects/math/fround/index.md
> +Оскільки `fround()` — це статичний метод об'єкта `Math`, його потрібно завжди використовувати через `Math.fround()`. Не слід звертатись до нього, як до методу створеного вами об'єкту `Math` (`Math` н
```suggestion
Оскільки `fround()` — це статичний метод об'єкта `Math`, його потрібно завжди використовувати через `Math.fround()`. Не слід звертатись до нього, як до методу власноруч створеного екземпляра `Math` (`Math` не є конструктором).
```

2021-12-25 17:33 UTC, undead404 requested changes

2021-12-25 17:33 UTC, undead404 commented on files/uk/web/javascript/reference/global_objects/math/fround/index.md
> +  - : {{jsxref("Number", "Число")}}. Якщо замість числа трапився інший тип, то параметр буде перетворено на число, або на {{jsxref("NaN")}}, якщо його не можна привести до числа.
```suggestion
  - : {{jsxref("Number", "Число")}}. Якщо замість числа трапився інший тип, то параметр буде перетворено на число, або буде повернено {{jsxref("NaN")}}, якщо його не можна привести до числа.
```

2021-12-25 17:33 UTC, undead404 commented on files/uk/web/javascript/reference/global_objects/math/fround/index.md
> +JavaScript всередині використовує 64-бітні числа з рухомою комою подвійної точності, які, як це видно з назви, мають дуже високу точність. Однак, інколи може виникнути необхідність попрацювати з 32-б
```suggestion
JavaScript всередині використовує 64-бітні числа з рухомою комою подвійної точності, які, як це видно з назви, мають дуже високу точність. Однак, інколи може виникнути необхідність попрацювати з 32-бітними числами з рухомою комою — наприклад, під час читання значень із {{jsxref("Float32Array")}}. Це може призвести до плутанини: порівняння 64-бітних чисел із 32-бітними може не спрацювати, навіть якщо самі числа мають ідентичний вигляд.
```

2021-12-25 17:33 UTC, undead404 commented on files/uk/web/javascript/reference/global_objects/math/fround/index.md
> +Для розв'язання цієї проблеми, можна застосувати `Math.fround()` для переведення 64-бітних чисел з рухомою комою в 32-бітні. JavaScript всередині продовжить сприймати числа як 64-бітні, лише виконає
```suggestion
Для розв'язання цієї проблеми можна застосувати `Math.fround()` для переведення 64-бітних чисел з рухомою комою в 32-бітні. JavaScript всередині продовжить сприймати числа як 64-бітні, лишень виконає "округлення до найближчого парного" на 23-му біті мантиси, і встановить всі наступні біти мантиси в `0`. Якщо число знаходиться за межами діапазону 32-бітних чисел з рухомою комою, то в результаті буде повернено {{jsxref("Infinity")}} чи `-Infinity`.
```

2021-12-25 17:33 UTC, undead404 commented on files/uk/web/javascript/reference/global_objects/math/fround/index.md
> +Оскільки `fround()` — це статичний метод об'єкта `Math`, його потрібно завжди використовувати через `Math.fround()`. Не слід звертатись до нього, як до методу власноруч створеного екземпляра `Math` (
```suggestion
Оскільки `fround()` — це статичний метод об'єкта `Math`, його потрібно завжди використовувати через `Math.fround()`. Не слід звертатись до нього як до методу власноруч створеного екземпляра `Math` (`Math` не є конструктором).
```

2021-12-30 23:05 UTC, undead404 approved these changes

2021-12-30 23:06 UTC, merged