translation(JS): Math exp and expm1
webdoky/content pull request #138
Opened 2021-11-30 23:37 UTC by AdriandeCita

Original content: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Math/exp, https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Math/expm1

2021-12-09 21:41 UTC, AdriandeCita commented on files/uk/web/javascript/reference/global_objects/math/exp/index.md
> +Оскільки `exp()` — це статичний метод об'єкта `Math`, його потрібно завжди використовувати через `Math.exp()`. Не слід звертатись до нього, як до методу створеного вами об'єкту `Math` (`Math` не є ко
```suggestion
Оскільки `exp()` — це статичний метод об'єкта `Math`, його потрібно завжди використовувати через `Math.exp()`. Не слід звертатись до нього, як до методу власноруч створеного екземпляра `Math` (`Math` не є конструктором).
```

2021-12-09 21:41 UTC, AdriandeCita commented on files/uk/web/javascript/reference/global_objects/math/expm1/index.md
> +Оскільки `expm1()` — це статичний метод об'єкта `Math`, його потрібно завжди використовувати через `Math.expm1()`. Не слід звертатись до нього, як до методу створеного вами об'єкту `Math` (`Math` не
```suggestion
Оскільки `expm1()` — це статичний метод об'єкта `Math`, його потрібно завжди використовувати через `Math.expm1()`. Не слід звертатись до нього, як до методу власноруч створеного екземпляра `Math` (`Math` не є конструктором).
```

2021-12-25 17:36 UTC, undead404 requested changes

2021-12-25 17:36 UTC, undead404 commented on files/uk/web/javascript/reference/global_objects/math/exp/index.md
> +Оскільки `exp()` — це статичний метод об'єкта `Math`, його потрібно завжди використовувати через `Math.exp()`. Не слід звертатись до нього, як до методу власноруч створеного екземпляра `Math` (`Math`
```suggestion
Оскільки `exp()` — це статичний метод об'єкта `Math`, його потрібно завжди використовувати через `Math.exp()`. Не слід звертатись до нього як до методу власноруч створеного екземпляра `Math` (`Math` не є конструктором).
```

2021-12-25 17:36 UTC, undead404 commented on files/uk/web/javascript/reference/global_objects/math/expm1/index.md
> +Оскільки `expm1()` — це статичний метод об'єкта `Math`, його потрібно завжди використовувати через `Math.expm1()`. Не слід звертатись до нього, як до методу власноруч створеного екземпляра `Math` (`M
```suggestion
Оскільки `expm1()` — це статичний метод об'єкта `Math`, його потрібно завжди використовувати через `Math.expm1()`. Не слід звертатись до нього як до методу власноруч створеного екземпляра `Math` (`Math` не є конструктором).
```

2021-12-30 23:05 UTC, undead404 approved these changes

2021-12-30 23:06 UTC, merged