Translation(CSS): display. Update
webdoky/content pull request #139
Opened 2021-12-19 21:55 UTC by undead404

Original content: [<ENTER_ACTUAL_MDN_LINK_HERE>](https://developer.mozilla.org/en-US/docs/Web/CSS/display)

2021-12-26 20:04 UTC, AdriandeCita requested changes

2021-12-26 20:04 UTC, AdriandeCita commented on files/uk/web/css/display/index.md
> +      - : Значення `inline-table` не має прямого відповідника у HTML. Такий елемент поводиться неначе HTML-елемент {{HTMLElement("table")}}, але як рядкова коробка, а не як коробка блокового рівня. В
Поміняв місцями щоб рознести "елемент"
```suggestion
      - : Значення `inline-table` не має прямого відповідника у HTML. Такий елемент поводиться неначе HTML-елемент {{HTMLElement("table")}}, але не як рамки блокового рівня, а як рядковий елемент. Всередині табличних рамок діє контекст блокового рівня.
```

2021-12-26 20:04 UTC, AdriandeCita commented on uk_ignore_additions.txt
> +блокового-та-рядкового
Відповідно, якщо приймається зміна отут https://github.com/webdoky/content/pull/139/files#diff-d000ae1659aa731b250de622835aded85c02234b2c5db35c78a23877c3e8bc82R87, то цей додаток не знадобиться
```suggestion
```

2021-12-27 10:26 UTC, undead404 commented on files/uk/web/css/display/index.md
> +> **Зверніть увагу:** Браузери, що підтримують синтаксис із двома значеннями, отримуючи виключно зовнішнє значення, наприклад, `display: block`, чи `display: inline`, встановлюють внутрішнє значення
```suggestion
> **Зверніть увагу:** У випадку отримання виключно зовнішнього значення (наприклад, `display: block`, чи `display: inline`) ті браузери, що підтримують синтаксис із двома значеннями, встановлюють внутрішнє значення у `flow`.
```

2021-12-27 10:26 UTC, undead404 commented on files/uk/web/css/display/index.md
> +      - : Елемент поводиться як рядковий, і розкладає свій вміст згідно з рубіновою моделлю форматування. Він поводиться як відповідний елемент HTML {{HTMLElement("ruby")}}.
До речі, треба й собі почитати, що таке те `ruby`...

2021-12-30 19:53 UTC, AdriandeCita approved these changes

2021-12-30 19:53 UTC, merged