translation(CSS): web/css/position/index.md
webdoky/content pull request #140
Opened 2021-12-24 16:36 UTC by undead404

Original content: [position - CSS: Cascading Style Sheets | MDN](https://developer.mozilla.org/en-US/docs/Web/CSS/position)

2021-12-30 11:24 UTC, AdriandeCita requested changes
Окрім вказаних маю іще таке загальне зауваження: тут трохи забагато ком. Ні, вони абсолютно легітимні, просто коли їх в реченні 4-5 штук - стає важкувато читати. Частину, де я одразу щось придумав, я переформулював, але то не все. Це не те, що виправляється одразу, просто радше побажання на майбутнє

2021-12-30 11:24 UTC, AdriandeCita commented on files/uk/web/css/position/index.md
> +Елементи, що є відносно позиціонованими, залишаються у звичайному плині документа. На відміну від них, елемент, що є позиціонованим абсолютно, виймається із плину; таким чином, інші елементи позиціон
```suggestion
Елементи, що є відносно позиціонованими, залишаються у звичайному плині документа. На відміну від них, абсолютно позиціонований елемент виймається із плину; таким чином, інші елементи розміщуються так, ніби його не існує. Абсолютно позиціонований елемент позиціонується відносно до свого _найближчого позиціонованого предка_ (наприклад, найближчого предка, що не є `static`). Якщо позиціонований предок не існує, елемент позиціонується відносно ПКБ (початкового контейнерного блока – дивіться також [визначення W3C](https://www.w3.org/TR/CSS2/visudet.html#containing-block-details)), котрий є контейнерним блоком кореневого елемента документа.
```

2021-12-30 11:24 UTC, AdriandeCita commented on files/uk/web/css/position/index.md
> +  рядку є місце. Переповнюючі рядкові елементи
```suggestion
  рядку є місце. Рядкові елементи з переповненням
```

2021-12-30 11:24 UTC, AdriandeCita commented on files/uk/web/css/position/index.md
> +Фіксоване позиціонування є подібним до абсолютного позиціонування, за виключенням того, що [контейнерний блок](/uk/docs/Web/CSS/Containing_block) елемента є початковим контейнерним блоком, утвореним
```suggestion
Фіксоване позиціонування є подібним до абсолютного позиціонування, за виключенням того, що [контейнерний блок](/uk/docs/Web/CSS/Containing_block) елемента є початковим контейнерним блоком, утвореним _областю перегляду_, якщо жоден предок не має властивості `transform`, `perspective` чи `filter` зі значенням, відмінним від `none` (дивіться [Специфікацію CSS перетворень](https://www.w3.org/TR/css-transforms-1/#propdef-transform)), що змусило б такого предка замінити елементові його [контейнерний блок](/uk/docs/Web/CSS/Containing_block). Це може бути використано для створення "плавучого" елемента, що залишається на одній позиції, незалежно від прокручування. У прикладі нижче елемент "Один" зафіксований на відстані 80 пікселів від верху сторінки, і 10 пікселів від лівого краю.
```

2021-12-30 11:24 UTC, AdriandeCita commented on files/uk/web/css/position/index.md
> +Обов‘язково вказати поріг в одній з властивостей: `top`, `right`, `bottom` чи `left`, щоб липке позиціонування поводилось як очікується.
```suggestion
Обов‘язково слід вказувати поріг в одній з властивостей: `top`, `right`, `bottom` чи `left`, щоб липке позиціонування поводилось як очікується.
```

2021-12-30 23:10 UTC, undead404 commented on files/uk/web/css/position/index.md
> +  - : Елемент позиціонується згідно зі звичайним плином документа, а тоді відступає вбік _відносно початкового положення_ на основі значень `top`, `right`, `bottom` та `left`. Відступ не вражає позиц
```suggestion
  - : Елемент позиціонується згідно зі звичайним плином документа, а тоді відступає вбік _відносно початкового положення_ на основі значень `top`, `right`, `bottom` та `left`. Відступ жодним чином не впливає на розміщення інших елементів; таким чином, простір, виділений для елемента у макеті сторінки, залишається таким самим, як був би, якби його `position` мала значення `static`.
```

2021-12-30 23:10 UTC, undead404 commented on files/uk/web/css/position/index.md
> +    Це значення завжди створює новий [контекст нагромадження](/uk/docs/Web/CSS/CSS_Positioning/Understanding_z_index/The_stacking_context). При друкові документа такий елемент друкується на одній поз
Я спеціально категорію часу прибираю із таких конструкцій, чому тут ти пропонуєш її додати?

2021-12-30 23:10 UTC, undead404 commented on files/uk/web/css/position/index.md
> +Відносно позиціоновані елементи мають заданий відступ від звичайної позиції в документі, але, втім, їх відступ не вражає інші елементи. У прикладі нижче зверніть увагу на те, як інші елементи розміще
```suggestion
Відносно позиціоновані елементи мають заданий відступ від звичайної позиції в документі, але, втім, їх відступ не впливає на інші елементи. У прикладі нижче зверніть увагу: інші елементи розміщені так, неначе блок "Два" займає місце у своєму звичайному положенні.
```

2021-12-31 09:25 UTC, AdriandeCita commented on files/uk/web/css/position/index.md
> +    Це значення завжди створює новий [контекст нагромадження](/uk/docs/Web/CSS/CSS_Positioning/Understanding_z_index/The_stacking_context). При друкові документа такий елемент друкується на одній поз
Виключно з міркувань зменшення вживання "при" https://onlinecorrector.com.ua/uk/%D0%B1%D1%96%D0%BB%D1%8F-%D0%BA%D1%80%D0%B0%D0%B9-%D0%B7%D0%B0-%D0%BF%D1%96%D0%B4-%D1%87%D0%B0%D1%81-%D1%83-%D1%80%D0%B0%D0%B7%D1%96/. На мою суб'єктивну думку "під час" сюди також чудово вписується. Але я не наполягаю, це радше стилістична річ, особливо коли таких місць ~1 на весь документ

2021-12-31 09:26 UTC, AdriandeCita approved these changes

2021-12-31 09:34 UTC, merged