translation(CSS): css/css_flexible_box_layout/aligning_items_in_a_fle…
webdoky/content pull request #141
Opened 2021-12-25 12:55 UTC by undead404

…x_container/index.md

Original content: [Aligning Items in a Flex Container - CSS: Cascading Style Sheets | MDN](https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_Flexible_Box_Layout/Aligning_Items_in_a_Flex_Container)

2021-12-30 17:26 UTC, AdriandeCita requested changes

2021-12-30 17:26 UTC, AdriandeCita commented on files/uk/web/css/css_flexible_box_layout/aligning_items_in_a_flex_container/index.md
> +Після шикування на поперечній осі – варто розглянути головну ось. Для шикування на ній доступна єдина властивість — `justify-content`. Причина цього – те, що обробляються елементи лише як група на го
```suggestion
Після шикування на поперечній осі – варто розглянути головну ось. Для шикування на ній доступна єдина властивість — `justify-content`. Причина цього – те, що на головній осі елементи обробляються лише як група. За допомогою `justify-content` можна керувати тим, що відбувається із доступним простором, якщо доступно більше простору, ніж необхідно для показу елементів.
```

2021-12-30 17:26 UTC, AdriandeCita commented on files/uk/web/css/css_flexible_box_layout/aligning_items_in_a_flex_container/index.md
> +У прикладі нижче значення `justify-content` – `space-between`. Доступний простір, не зайнятий елементами, розподілений у проміжках між елементами. Крайній лівий та крайній правий елементи розташовані
```suggestion
У прикладі нижче значення `justify-content` – `space-between`. Доступний простір, не зайнятий елементами, розподілений у проміжках між елементами. Крайній лівий та правий елементи розташовані безпосередньо на початку та в кінці рядка, відповідно.
```

2021-12-30 17:26 UTC, AdriandeCita commented on files/uk/web/css/css_flexible_box_layout/aligning_items_in_a_flex_container/index.md
> +Якщо головна вісь збігається із блоковим напрямком (значення `flex-direction` – `column`), то `justify-content` розподілятиме простір між елементами у відповідному вимірі доти, доки не буде більше пр
```suggestion
Якщо головна вісь збігається із блоковим напрямком (значення `flex-direction` – `column`), то `justify-content` розподілятиме простір між елементами у відповідному вимірі доти, доки у flex-контейнері більше не залишиться простору для розподілу.
```

2021-12-30 17:26 UTC, AdriandeCita commented on files/uk/web/css/css_flexible_box_layout/aligning_items_in_a_flex_container/index.md
> +Живий приклад нижче має властивість `direction`, встановлену у значення `rtl`, щоб примусити елементи до плину справа наліво. Це можна прибрати, або встановити значення властивості `justify-content`,
```suggestion
Живий приклад нижче має властивість `direction`, встановлену у значення `rtl`, щоб примусити елементи до плину справа наліво. Це можна прибрати, або встановити значення властивості `justify-content`, щоб перевірити поведінку flexbox в умовах, коли початок рядків знаходиться справа.
```

2021-12-30 17:26 UTC, AdriandeCita commented on files/uk/web/css/css_flexible_box_layout/aligning_items_in_a_flex_container/index.md
> +Початкова лінія також зміниться, якщо змінити значення властивості `flex-direction` — наприклад, вказати `row-reverse` замість `row`.
В англійській версії теж лінія, але наскільки я зрозумів з контексту, мова все-таки про початок рядка
```suggestion
Початок рядка також зміниться, якщо змінити значення властивості `flex-direction` — наприклад, вказати `row-reverse` замість `row`.
```

2021-12-30 17:26 UTC, AdriandeCita commented on files/uk/web/css/css_flexible_box_layout/aligning_items_in_a_flex_container/index.md
> +Якщо змінити `flex-direction` на одне зі зворотних значень, елементи розставлятимуться починаючи від кінця осі у зворотному до написання слів мовою документа порядку. `flex-start` тоді означатиме кін
```suggestion
Якщо змінити `flex-direction` на одне зі зворотних значень, елементи розставлятимуться починаючи від кінця осі у зворотному порядку до написання слів мовою документа. `flex-start` тоді означатиме кінець тієї осі – тож місце, де б відбувався перенос (при роботі з рядами), або кінець останнього параграфа тексту (при роботі з колонками).
```

2021-12-30 17:26 UTC, AdriandeCita commented on files/uk/web/css/css_flexible_box_layout/aligning_items_in_a_flex_container/index.md
> +Загальноприйнятим зразком є панель навігації, на котрій певні ключові елементи вишикувані до правого краю, а головна група – до лівого. Можна було б припустити, що це має бути приклад використання вл
```suggestion
Загальноприйнятим зразком є панель навігації, на котрій певні ключові елементи вишикувані до правого краю, а головна група – до лівого. Можна було б припустити, що це має бути приклад використання властивості `justify-self`, однак погляньмо на зображення нижче. Є три елементи з одного боку і два з іншого. Якби можна було використати `justify-self` на елементі _d_, це б також змінило шикування елемента _e_, який йде наступним, що може бути як доречним, так і небажаним.
```

2021-12-30 17:26 UTC, AdriandeCita commented on files/uk/web/css/css_flexible_box_layout/aligning_items_in_a_flex_container/index.md
> +## Перегляньте також
```suggestion
## Дивіться також
```

2021-12-30 23:16 UTC, undead404 commented on files/uk/web/css/css_flexible_box_layout/aligning_items_in_a_flex_container/index.md
> +Властивості `align-items` та `align-self` керують шикуванням елементів flex на поперечній осі – у колонках, якщо значення властивості `flex-direction` – `row`, і у рядах, якщо `flex-direction` – `col
Може, краще flex таки всюди лишати flex? Для одноманітності

2021-12-30 23:16 UTC, undead404 commented on files/uk/web/css/css_flexible_box_layout/aligning_items_in_a_flex_container/index.md
> +Погляньмо на використання шикування на поперечній осі у найпростішому прикладі flex. Якщо додати контейнерові `display: flex`, то дочірні елементи стануть flex-елементами, впорядкованими у ряд. Вони
Тут так само: може, нехай буде flex-розкладка?

2021-12-31 09:31 UTC, AdriandeCita commented on files/uk/web/css/css_flexible_box_layout/aligning_items_in_a_flex_container/index.md
> +Властивості `align-items` та `align-self` керують шикуванням елементів flex на поперечній осі – у колонках, якщо значення властивості `flex-direction` – `row`, і у рядах, якщо `flex-direction` – `col
Поки ми не маємо узгодженого перекладу назв специфікацій - може бути. Я просто дуже не люблю ніяк не виділені англійські слова в тексті, виглядає тупо як пропущений переклад. Або вже перекладати як "елеметнів flex-розкладки", або перекладати цілком, або виділяти як код (останній варіант тут не дуже підгожий)

2021-12-31 09:33 UTC, AdriandeCita commented on files/uk/web/css/css_flexible_box_layout/aligning_items_in_a_flex_container/index.md
> +Погляньмо на використання шикування на поперечній осі у найпростішому прикладі flex. Якщо додати контейнерові `display: flex`, то дочірні елементи стануть flex-елементами, впорядкованими у ряд. Вони
так, най буде flex-розкладка. Просто flex тут виглядає неузгоджено з реченням.

2021-12-31 09:36 UTC, AdriandeCita commented on files/uk/web/css/css_flexible_box_layout/aligning_items_in_a_flex_container/index.md
> +Погляньмо на використання шикування на поперечній осі у найпростішому прикладі flex. Якщо додати контейнерові `display: flex`, то дочірні елементи стануть flex-елементами, впорядкованими у ряд. Вони
```suggestion
Погляньмо на використання шикування на поперечній осі у найпростішому прикладі flex-розкладки. Якщо додати контейнерові `display: flex`, то дочірні елементи стануть flex-елементами, впорядкованими у ряд. Вони будуть розтягнені, аби бути настільки ж високими, як найвищий елемент, оскільки такий елемент визначає висоту елементів на поперечній осі. Якщо flex-контейнер має явно вказану висоту, то всі елементи розтягнуться до його висоти, незалежно від того, скільки вмісту вони мають.
```

2021-12-31 09:37 UTC, AdriandeCita commented on files/uk/web/css/css_flexible_box_layout/aligning_items_in_a_flex_container/index.md
> +Властивості `align-items` та `align-self` керують шикуванням елементів flex на поперечній осі – у колонках, якщо значення властивості `flex-direction` – `row`, і у рядах, якщо `flex-direction` – `col
```suggestion
Властивості `align-items` та `align-self` керують шикуванням елементів flex-розкладки на поперечній осі – у колонках, якщо значення властивості `flex-direction` – `row`, і у рядах, якщо `flex-direction` – `column`.
```

2021-12-31 09:54 UTC, AdriandeCita approved these changes

2021-12-31 09:54 UTC, merged