translation(CSS): css/box-shadow/index.md
webdoky/content pull request #142
Opened 2021-12-25 15:52 UTC by undead404

Original content: [box-shadow - CSS: Cascading Style Sheets | MDN](https://developer.mozilla.org/en-US/docs/Web/CSS/box-shadow)

2021-12-30 18:16 UTC, AdriandeCita commented on files/uk/web/css/box-shadow/index.md
> +Властивість `box-shadow` дає змогу відкидати тінь від рамки майже будь-якого елемента. Якщо на елементі з тінню вказано {{cssxref("border-radius")}}, то тінь так само матиме заокруглені кути. Порядок
```suggestion
Властивість `box-shadow` дає змогу відкидати тінь від рамки майже будь-якого елемента. Якщо на елементі з тінню вказано {{cssxref("border-radius")}}, то тінь так само матиме заокруглені кути. Порядок нагромадження кількох тіней такий самий, як для кількох [тіней тексту](/uk/docs/Web/CSS/text-shadow) (раніше описана перекриває наступні).
```

2021-12-30 18:19 UTC, AdriandeCita commented on files/uk/web/css/box-shadow/index.md
> +/* Ключові значення */
"Ключове значення" наче натякає, що це значення якесь важливіше ніж інші. Думаю, ліпше просто залишити так:
```suggestion
/* Ключові слова */
```

2021-12-30 19:37 UTC, AdriandeCita requested changes

2021-12-30 19:37 UTC, AdriandeCita commented on files/uk/web/css/box-shadow/index.md
> +Кожна тінь у списку (розглядаючи `none` як список нульової довжини) інтерполюється через кольорову (як колір) компоненту, а також компоненти x, y, розмиття та (коли припустимо) розмаху (як довжина) к
Трохи переформулював, бо продиратися через це і в оригіналі складно (знайшов навіть запитання на СО, присвячене цьому https://stackoverflow.com/questions/41398269/how-understand-interpolation-about-box-shadow-described-on-mdn)
```suggestion
Кожна тінь у списку (розглядаючи `none` як список нульової довжини) інтерполюється через кольорову (як колір) компоненту, а також компоненти x, y, розмиття та (коли припустимо) розмах (як довжина). Для кожної початкової тіні виконується перевірка параметру `inset`. Якщо обидві тіні є `inset` (або обидві не є `inset`), то значення інтерпольованої тіні збігатиметься з початковими стосовно цього параметру. Якщо ж у будь-якій парі вхідних тіней одна містить `inset`, а інша – ні, то весь набір тіней не інтерполюється. Якщо списки тіней мають різну довжину, то коротший список в кінці заповнюється тінями, чий колір – `transparent`, усі довжини – `0`, і для котрих `inset` вказано чи не вказано – згідно з вихідним списком, поки короткий список не відповідатиме за довжиною довгому спискові.
```

2021-12-30 19:37 UTC, AdriandeCita commented on files/uk/web/css/box-shadow/index.md
> +Коли значення `x-offset`, `y-offset` та `blur` – нуль, тінь матиме контур суцільного кольору рівного розміру з усіх боків. Тіні відображаються від спідньої до верхньої, тож перша тінь лежить поверх н
```suggestion
Коли значення `x-offset`, `y-offset` та `blur` – нуль, тінь матиме контур суцільного кольору рівного розміру з усіх боків. Тіні відображаються від спідньої до верхньої, тож перша тінь лежить поверх наступних тіней. Коли значення `border-radius` – 0, як усталено, то кути тіні будуть, власне, кутами. Якщо ж вказана властивість `border-radius` з будь-яким іншим значенням, то кути будуть закруглені.
```

2021-12-30 19:37 UTC, AdriandeCita commented on files/uk/web/css/box-shadow/index.md
> +Додано зовнішнє поле такого ж розміру, як найширша тінь, аби пересвідчитись, що тінь не перекриває суміжні елементи й не виходить за межі контейнерної коробки. Коробкова тінь не вражає вимірів [короб
```suggestion
Додано зовнішнє поле такого ж розміру, як найширша тінь, аби пересвідчитись, що тінь не перекриває суміжні елементи й не виходить за межі рамок контейнера. Властивість `box-shadow` не впливає на виміри [блокової моделі](/uk/docs/Web/CSS/CSS_Box_Model).
```

2021-12-30 19:37 UTC, AdriandeCita commented on files/uk/web/css/box-shadow/index.md
> +  - : Це два значення {{cssxref("&lt;length&gt;")}} для опису відступу тіні. `<offset-x>` вказує горизонтальний відступ. Від‘ємні значення поміщають тінь зліва від елемента. `<offset-y>` вказує верти
Для офсетів краще взяти щось більш підгоже - або зміщення, або зсув. Окрім того, що це більш відповідний переклад, "зсув" дає зрозуміти, що розміри тіні не зміняться під час зміщення, а "відступ" такої семантики не має. 
```suggestion
  - : Це два значення {{cssxref("&lt;length&gt;")}} для опису зсуву тіні. `<offset-x>` вказує зсув по горизонталі. Від‘ємні значення поміщають тінь зліва від елемента. `<offset-y>` вказує вертикальний зсув. Від‘ємні значення поміщають тінь згори від елемента. Дивіться {{cssxref("&lt;length&gt;")}} для інформації про можливі одиниці вимірювання.
```

2021-12-30 19:37 UTC, AdriandeCita commented on files/uk/web/css/box-shadow/index.md
> +Властивість [CSS](/uk/docs/Web/CSS) **`box-shadow`** ("тінь коробки") додає ефекти тіні навколо рамки елемента. Можна вказати кілька ефектів через кому. Тінь описується відступами за осями X та Y від
```suggestion
Властивість [CSS](/uk/docs/Web/CSS) **`box-shadow`** ("тінь коробки") додає ефекти тіні навколо рамки елемента. Можна вказати кілька ефектів через кому. Тінь описується зсувом за осями X та Y від елемента, радіусами розмиття та розмаху, а також кольором.
```

2021-12-30 19:37 UTC, AdriandeCita commented on files/uk/web/css/box-shadow/index.md
> +### Нуль як значення відступу та розмиття
```suggestion
### Нуль як значення зсуву та розмиття
```

2021-12-30 23:19 UTC, undead404 commented on files/uk/web/css/box-shadow/index.md
> +  - Якщо вказані два значення, вони приймаються у якості значень `<offset-x>` та `<offset-y>` (відступи за осями X та Y).
```suggestion
  - Якщо вказані два, то вони вважаються значеннями `<offset-x>` та `<offset-y>` (засув за осями X та Y).
```

2021-12-30 23:19 UTC, undead404 commented on files/uk/web/css/box-shadow/index.md
> +  - Якщо вказане четверте значення, воно приймається у якості `<spread-radius>` (радіус розмаху).
Resolve?

2021-12-30 23:19 UTC, undead404 commented on files/uk/web/css/box-shadow/index.md
> +- `<spread-radius>` (радіус розмаху)
Resolve?

2021-12-31 09:33 UTC, AdriandeCita approved these changes

2021-12-31 09:34 UTC, merged