update(JS): web/javascript/reference/global_objects/encodeuricomponent
webdoky/content pull request #1480
Opened 2023-03-08 13:43 UTC by undead404

Оригінальний вміст: [encodeURIComponent()@MDN](https://developer.mozilla.org/en-us/docs/Web/JavaScript/Reference/Global_Objects/encodeURIComponent), [сирці encodeURIComponent()@GitHub](https://github.com/mdn/content/blob/main/files/en-us/web/javascript/reference/global_objects/encodeuricomponent/index.md)

Нові зміни:
- [mdn/content@6b72869](https://github.com/mdn/content/commit/6b728699f5f38f1070a94673b5e7afdb1102a941)

2023-03-08 14:37 UTC, AdriandeCita requested changes
Є свіжі зміни https://github.com/mdn/content/pull/25152/files#diff-455fc23eab49cabe7c298c8e5cd7ca8fd06e8b2d01d8bf664a6ed93d0aea7366

2023-03-09 09:55 UTC, undead404 commented
Оновлено

2023-03-12 09:31 UTC, AdriandeCita commented on files/uk/web/javascript/reference/global_objects/encodeuricomponent/index.md
> +      // toUpperCase() для коректного кодування). Коли RFC3986 резервує "!",
Вживання "коли" в значенні "although" здається a bit of a stretch, пропоную вжити більш традиційне формулювання
```suggestion
      // toUpperCase() для коректного кодування). І хоча RFC3986 резервує "!",
```

2023-03-12 09:32 UTC, AdriandeCita commented on files/uk/web/javascript/reference/global_objects/encodeuricomponent/index.md
> +      // то RFC5987 – ні, тому цей символ немає потреби екранувати.
```suggestion
      // RFC5987 – ні, тому цей символ немає потреби екранувати.
```

2023-03-12 09:32 UTC, AdriandeCita requested changes
Стосовно коментаря

2023-03-31 10:47 UTC, AdriandeCita approved these changes

2023-03-31 10:48 UTC, merged