update(JS): web/javascript/guide/using_promises
webdoky/content pull request #1481
Opened 2023-03-08 13:55 UTC by undead404

Оригінальний вміст: [Використання промісів@MDN](https://developer.mozilla.org/en-us/docs/Web/JavaScript/Guide/Using_promises), [сирці Використання промісів@GitHub](https://github.com/mdn/content/blob/main/files/en-us/web/javascript/guide/using_promises/index.md)

Нові зміни:
- [mdn/content@9c4fb23](https://github.com/mdn/content/commit/9c4fb236cd9ced12b1eb8e7696d8e6fcb8d8bad3)
- [mdn/content@6132ac2](https://github.com/mdn/content/commit/6132ac29c94583a1bbdecc7a1eeede970600c675)
- [mdn/content@2a06138](https://github.com/mdn/content/commit/2a06138a9676d1ef7b84d2b79f2a1085d366c0c2)
- [mdn/content@13dc8d7](https://github.com/mdn/content/commit/13dc8d707abd26319eba06d9c48630eb25e9adb9)

2023-03-12 09:37 UTC, AdriandeCita commented on files/uk/web/javascript/guide/using_promises/index.md
> +Підхід вище наполегливо не рекомендується, адже призводить до так званого "стану Зальґо". У контексті проєктування асинхронних API це означає функцію зворотного виклику, що викликається синхронно в о
Пропоную переформулювати "...це означає функцію зворотного виклику...", бо складається враження, що стан Зальґо означає функцію.
```suggestion
Наведений вище підхід наполегливо не рекомендується, адже призводить до так званого "стану Зальґо". У контексті проєктування асинхронних API це означає, що функція зворотного виклику викликається синхронно в одних випадках, але асинхронно в інших, призводячи до неоднозначності для того, хто її викликає. Більше контексту на цю тему можна знайти в статті [Проєктування API з асинхронністю](https://blog.izs.me/2013/08/designing-apis-for-asynchrony/), де цей термін уперше вбув формально введений. Такий підхід до створення API призводить до того, що побічні ефекти важко аналізувати:
```

2023-03-12 09:38 UTC, AdriandeCita requested changes
Невеличке зауваження

2023-03-13 09:24 UTC, undead404 commented
Прийняв оновлення

2023-03-31 10:48 UTC, AdriandeCita approved these changes

2023-03-31 10:48 UTC, merged