update(HTML): web/html/element/a
webdoky/content pull request #1500
Opened 2023-03-10 07:40 UTC by undead404

Оригінальний вміст: [&lt;a>: Якірний елемент@MDN](https://developer.mozilla.org/en-us/docs/Web/HTML/Element/a), [сирці &lt;a>: Якірний елемент@GitHub](https://github.com/mdn/content/blob/main/files/en-us/web/html/element/a/index.md)

Нові зміни:
- [mdn/content@5c30b5e](https://github.com/mdn/content/commit/5c30b5e4e57d1a77ce56b88b3de1171d57562808)

2023-03-10 11:16 UTC, AdriandeCita requested changes
Є свіжі зміни https://github.com/mdn/content/commit/7b5b5ab9e42da8c46d2a54ef24b40033b8528d24#diff-8dae45e8aa4220ab9b4cd77d1c59ad7d470e590a7f0e6c297123740f937acd8d

2023-03-11 17:03 UTC, undead404 commented
Оновлено

2023-03-12 09:04 UTC, AdriandeCita requested changes
Іще одне https://github.com/mdn/content/commit/d3cdafcdb4d22e5c55771501e7c80451a96aa032#diff-8dae45e8aa4220ab9b4cd77d1c59ad7d470e590a7f0e6c297123740f937acd8d

2023-03-13 09:29 UTC, undead404 commented
Оновлено

2023-03-18 14:09 UTC, AdriandeCita approved these changes

2023-03-18 14:09 UTC, merged