translation(CSS): css/cursor/index.md
webdoky/content pull request #151
Opened 2022-01-01 18:43 UTC by undead404

Original content: [cursor - CSS: Cascading Style Sheets | MDN](https://developer.mozilla.org/en-US/docs/Web/CSS/cursor)

2022-01-06 09:05 UTC, AdriandeCita commented on files/uk/web/css/cursor/index.md
> +Властивість [CSS](/en-US/docs/Web/CSS) **`cursor`** вказує курсор миші, котрий повинен бути показаний, коли вказівник миші розташований над елементом.
```suggestion
Властивість [CSS](/en-US/docs/Web/CSS) **`cursor`** встановлює курсор миші, котрий повинен бути показаний, коли вказівник миші розташований над елементом.
```

2022-01-06 09:07 UTC, AdriandeCita commented on files/uk/web/css/cursor/index.md
> +Встановлення курсора повинне повідомити користувачів про дії миші, котрі можуть бути виконані у поточному положенні, включаючи: вибір тексту, активацію помічника або контекстних меню, копіювання вміс
```suggestion
Встановлення курсора повинне повідомити користувачів про дії, котрі можна виконати за допомогою миші в поточному положенні, включаючи: вибір тексту, активацію помічника або контекстних меню, копіювання вмісту, зміну розміру таблиць, і так далі.
```

2022-01-06 09:10 UTC, AdriandeCita commented on files/uk/web/css/cursor/index.md
> +Властивість `cursor` встановлюється нулем або більшою кількістю значень `<url>`, розділених комами, з обов‘язковим ключовим словом у кінці.
```suggestion
Властивість `cursor` встановлюється довільною кількістю значень `<url>` (нуль чи більше), розділених комами, з обов‘язковим ключовим словом у кінці.
```

2022-01-06 09:14 UTC, AdriandeCita commented on files/uk/web/css/cursor/index.md
> +    Більш ніж одне значення {{cssxref("url()")}} може бути вказане як запасні варіанти, на випадок того, що якісь типи зображень курсорів не підтримуються.
```suggestion
    На випадок того, що якісь типи зображень курсорів не підтримуються, можна вказати більш ніж одне значення {{cssxref("url()")}}.
```

2022-01-06 09:18 UTC, AdriandeCita commented on files/uk/web/css/cursor/index.md
> +            Користувацький фактор визначить курсор на основі поточного контексту. Наприклад, еквівалентно до <code>text</code>, коли вказівник знаходиться над текстом.
"фактор" звучить як аллюзія на "людський фактор", що не зовсім справедливо. Поки немає остаточного рішення - заміняю на агент
```suggestion
            Користувацький агент визначить курсор на основі поточного контексту. Наприклад, еквівалентно до <code>text</code>, коли вказівник знаходиться над текстом.
```

2022-01-06 09:22 UTC, AdriandeCita commented on files/uk/web/css/cursor/index.md
> +Хоч специфікація не обмежує розмір зображення курсора, {{Glossary("user agent", "користувацькі фактори")}} зазвичай обмежують його, аби уникнути можливого зловживання.
```suggestion
Хоч специфікація не обмежує розмір зображення курсора, {{Glossary("user agent", "користувацькі агенти")}} зазвичай обмежують його, аби уникнути можливого зловживання.
```

2022-01-06 09:23 UTC, AdriandeCita commented on files/uk/web/css/cursor/index.md
> +Перевірте таблицю "{{anch("Сумісність із браузерами")}}" щодо зауважень щодо обмежень розмірів курсора.
```suggestion
Перевірте таблицю "{{anch("Сумісність із браузерами")}}" щодо зауважень стосовно обмежень розмірів курсора.
```

2022-01-06 09:24 UTC, AdriandeCita commented on files/uk/web/css/cursor/index.md
> +Наприклад, на Firefox та Chromium зображення курсора усталено обмежені розміром 32x32 пікселів, і заміна курсора з використанням більших зображень буде в загальному просто проігнорована.
```suggestion
Наприклад, у Firefox та Chromium зображення курсора усталено обмежені розміром 32x32 пікселів, і заміна курсора з використанням більших зображень буде в загальному просто проігнорована.
```

2022-01-06 09:27 UTC, AdriandeCita commented on files/uk/web/css/cursor/index.md
> +Специфікація вимагає від користувацьких факторів підтримки файлів PNG, файлів SVG версії 1.1 у безпечному статичному режимі, що містять природний розмір, та будь-яких інших неанімованих форматів файл
```suggestion
Специфікація вимагає від користувацьких факторів підтримки файлів PNG, файлів SVG версії 1.1 у безпечному статичному режимі і природнього розміру, та будь-яких інших неанімованих форматів файлів зображень, що підтримуються для зображень в інших властивостях.
```

2022-01-06 09:28 UTC, AdriandeCita commented on files/uk/web/css/cursor/index.md
> +Специфікація вимагає від користувацьких факторів підтримки файлів PNG, файлів SVG версії 1.1 у безпечному статичному режимі, що містять природний розмір, та будь-яких інших неанімованих форматів файл
ну тобто розмір - це не те, що може десь міститись, звучить трохи дивно

2022-01-06 09:29 UTC, AdriandeCita commented on files/uk/web/css/cursor/index.md
> +Далі специфікація показує, що користувацькі фактори _повинні_ також підтримувати файли SVG версії 1.1 files у безпечному анімованому режимі, що містять природний розмір, поруч із будь-якими іншими ан
```suggestion
Далі специфікація показує, що користувацькі фактори _повинні_ також підтримувати файли SVG версії 1.1 природнього розміру у безпечному анімованому режимі, поруч із будь-якими іншими анімованими форматами файлів зображень, що підтримуються для зображень в інших властивостях.
```

2022-01-06 09:30 UTC, AdriandeCita commented on files/uk/web/css/cursor/index.md
> +Користувацькі фактори _можуть_ підтримувати як статичні, так анімовані SVG зображення, що не містять природного розміру.
```suggestion
Користувацькі агенти _можуть_ підтримувати як статичні, так анімовані SVG зображення, що не містять природного розміру.
```

2022-01-06 09:36 UTC, AdriandeCita requested changes
Стосовно коментарів

2022-01-06 09:37 UTC, AdriandeCita commented
І мерсі за чистку дублікатів зі списку винятків :smiley:

2022-01-09 18:26 UTC, undead404 commented on files/uk/web/css/cursor/index.md
> +Специфікація вимагає від користувацьких факторів підтримки файлів PNG, файлів SVG версії 1.1 у безпечному статичному режимі, що містять природний розмір, та будь-яких інших неанімованих форматів файл
Мені здається, SVG мають містити в цьому випадку якийсь захардкоджений розмір. Це не так?

2022-01-10 13:12 UTC, undead404 commented on files/uk/web/css/cursor/index.md
> +Специфікація вимагає від користувацьких факторів підтримки файлів PNG, файлів SVG версії 1.1 у безпечному статичному режимі, що містять природний розмір, та будь-яких інших неанімованих форматів файл
Компроміс?
```suggestion
Специфікація вимагає від користувацьких факторів підтримки файлів PNG, файлів SVG версії 1.1 у безпечному статичному режимі, що мають природний розмір, та будь-яких інших неанімованих форматів файлів зображень, що підтримуються для зображень в інших властивостях.
```

2022-01-10 13:12 UTC, undead404 commented on files/uk/web/css/cursor/index.md
> +Далі специфікація показує, що користувацькі фактори _повинні_ також підтримувати файли SVG версії 1.1 files у безпечному анімованому режимі, що містять природний розмір, поруч із будь-якими іншими ан
```suggestion
Далі специфікація показує, що користувацькі агенти _повинні_ також підтримувати файли SVG версії 1.1 files у безпечному анімованому режимі, що мають природний розмір, поруч із будь-якими іншими анімованими форматами файлів зображень, що підтримуються для зображень в інших властивостях.
```

2022-01-10 13:12 UTC, undead404 commented on files/uk/web/css/cursor/index.md
> +Користувацькі фактори _можуть_ підтримувати як статичні, так анімовані SVG зображення, що не містять природного розміру.
```suggestion
Користувацькі агенти _можуть_ підтримувати як статичні, так анімовані SVG зображення, що не мають природного розміру.
```

2022-01-10 21:42 UTC, merged