update(JS): web/javascript/reference/global_objects/string/indexof
webdoky/content pull request #1511
Opened 2023-03-10 20:08 UTC by undead404

Оригінальний вміст: [String.prototype.indexOf()@MDN](https://developer.mozilla.org/en-us/docs/Web/JavaScript/Reference/Global_Objects/String/indexOf), [сирці String.prototype.indexOf()@GitHub](https://github.com/mdn/content/blob/main/files/en-us/web/javascript/reference/global_objects/string/indexof/index.md)

Нові зміни:
- [mdn/content@f3df525](https://github.com/mdn/content/commit/f3df52530f974e26dd3b14f9e8d42061826dea20)
- [mdn/content@989bcd8](https://github.com/mdn/content/commit/989bcd8266f53d0134d26c5bb307c08718a60162)
- [mdn/content@2eb202a](https://github.com/mdn/content/commit/2eb202adbe3d83292500ed46344d63fbbae410b5)
- [mdn/content@7b72e7d](https://github.com/mdn/content/commit/7b72e7d4860bcac018713414df3ca7e941cb7bd3)
- [mdn/content@9e52d33](https://github.com/mdn/content/commit/9e52d335675a9f7daa34b5e24c9b1292dbf23b2e)
- [mdn/content@1302c24](https://github.com/mdn/content/commit/1302c248288a4813256af1d0043f33deaf9868b2)
- [mdn/content@ce29091](https://github.com/mdn/content/commit/ce2909126eb09e44c9f48d9f65d072acae827749)
- [mdn/content@968e6f1](https://github.com/mdn/content/commit/968e6f1f3b6f977a09e116a0ac552459b741eac3)
- [mdn/content@4cf1362](https://github.com/mdn/content/commit/4cf1362de4a7634f5f21deba949973cc240f5fd4)
- [mdn/content@50146bf](https://github.com/mdn/content/commit/50146bf188d7661d10a402fa2881c292e89e7cdc)
- [mdn/content@2c2f8ca](https://github.com/mdn/content/commit/2c2f8caac8cbf8e41019c01be5635e10fe65f2cd)
- [mdn/content@2d6d6a1](https://github.com/mdn/content/commit/2d6d6a1d9f8ba2073c9f8e1bbc6b4e20204fb53c)
- [mdn/content@8a5ab92](https://github.com/mdn/content/commit/8a5ab92ceab8fe1b8f44597381cf3fd996e252e9)
- [mdn/content@4c9f9bb](https://github.com/mdn/content/commit/4c9f9bb287b37743a0e626fd2b60f54240f4f07e)
- [mdn/content@07884a3](https://github.com/mdn/content/commit/07884a3f4081ac587348656d475b55a61f746197)
- [mdn/content@281e3b2](https://github.com/mdn/content/commit/281e3b21178946c8301232a8eb50d11770ee8450)
- [mdn/content@971592a](https://github.com/mdn/content/commit/971592a84ccc3296ec1686dcc3253b5a764c8c84)

2023-04-30 19:32 UTC, AdriandeCita approved these changes

2023-04-30 19:34 UTC, AdriandeCita requested changes
Є свіжі зміни https://github.com/mdn/content/commit/6bd17cb9cbc2d11163617b9f71706e93fdd743c8#diff-9c1c24f531ee7b77fa84694b2a757a7499e138172b0b76403d60a8de697da5fc

2023-05-03 07:25 UTC, undead404 commented
Оновлено

2023-05-04 12:16 UTC, AdriandeCita approved these changes

2023-05-04 12:16 UTC, merged