update(JS): web/javascript/reference/global_objects/promise/then
webdoky/content pull request #1517
Opened 2023-03-11 16:13 UTC by undead404

Оригінальний вміст: [Promise.prototype.then()@MDN](https://developer.mozilla.org/en-us/docs/Web/JavaScript/Reference/Global_Objects/Promise/then), [сирці Promise.prototype.then()@GitHub](https://github.com/mdn/content/blob/main/files/en-us/web/javascript/reference/global_objects/promise/then/index.md)

Нові зміни:
- [mdn/content@fcd80ee](https://github.com/mdn/content/commit/fcd80ee4c8477b6f73553bfada841781cf74cf46)
- [mdn/content@2eb202a](https://github.com/mdn/content/commit/2eb202adbe3d83292500ed46344d63fbbae410b5)
- [mdn/content@79f307c](https://github.com/mdn/content/commit/79f307ce6c91d661aa024addea2f6631f4853e47)
- [mdn/content@9a771cd](https://github.com/mdn/content/commit/9a771cdf71361a2d7528fa729e1512461a97db28)

2023-03-30 11:12 UTC, undead404 commented
Оновлено

2023-03-30 11:15 UTC, undead404 commented
Розв'язано конфлікт

2023-04-26 16:39 UTC, undead404 commented
Оновлено

2023-04-29 10:58 UTC, undead404 commented
Оновлено

2023-04-30 19:39 UTC, AdriandeCita commented on uk_spelling_additions.txt
> +функцію-виконавця
Схоже, це дублікат
```suggestion
```

2023-04-30 19:39 UTC, AdriandeCita requested changes
Дрібничка

2023-05-03 08:58 UTC, AdriandeCita approved these changes

2023-05-03 08:58 UTC, merged