update(CSS): web/css/containing_block
webdoky/content pull request #1529
Opened 2023-03-14 08:53 UTC by undead404

Оригінальний вміст: [Компонування та контейнерний блок@MDN](https://developer.mozilla.org/en-us/docs/Web/CSS/Containing_block), [сирці Компонування та контейнерний блок@GitHub](https://github.com/mdn/content/blob/main/files/en-us/web/css/containing_block/index.md)

Нові зміни:
- [mdn/content@a0dc6df](https://github.com/mdn/content/commit/a0dc6df55e75171236937d1b5059117bc5c0176f)
- [mdn/content@489dbd4](https://github.com/mdn/content/commit/489dbd4d8e2e099733d3bb04ad3f97678c54ac8e)
- [mdn/content@4e002d2](https://github.com/mdn/content/commit/4e002d26cb032c915aeee366f922f23cbacd8bf1)

2023-04-30 19:49 UTC, AdriandeCita approved these changes

2023-04-30 19:50 UTC, AdriandeCita requested changes
Є пара оновлень https://github.com/mdn/content/commits/main/files/en-us/web/css/containing_block/index.md

2023-05-03 07:43 UTC, undead404 commented
Оновлено

2023-05-04 12:16 UTC, AdriandeCita approved these changes

2023-05-04 12:16 UTC, merged