chore: formatting, correction
webdoky/content pull request #153
Opened 2022-01-01 20:43 UTC by undead404

Formatting & few corrections

2022-01-07 10:38 UTC, AdriandeCita commented
гарна ідея. Чим форматував?

2022-01-07 10:39 UTC, AdriandeCita commented on files/uk/web/css/background-color/index.md
> +- [Використання кількох фонів](/uk/docs/Web/CSS/CSS_Backgrounds_and_Borders/Using_multiple_backgrounds)
:+1:

2022-01-07 10:43 UTC, AdriandeCita commented on files/uk/web/javascript/reference/global_objects/array/includes/index.md
> +[1, 2, 3]
Оце щось дивне, попереднэ форматування виглядало логічніше

2022-01-07 10:47 UTC, AdriandeCita commented on files/uk/web/javascript/reference/global_objects/array/index.md
> -console.log(arr[0])              // виводить 'це перший елемент'
ну, як для довідкового/навчального матеріалу цей варіант виглядав кращим, простішим для сприйняття. Це не критично, але я б десь в перспективі повернувся до цього питання

2022-01-07 10:49 UTC, AdriandeCita commented on files/uk/web/javascript/reference/global_objects/array/map/index.md
> +['1', '2', '3']
Теж форматування поїхало, схоче - через відсутність крапок з комами

2022-01-07 10:53 UTC, AdriandeCita commented on files/uk/web/javascript/reference/global_objects/array/reduce/index.md
> +    - _previousValue_ (результат виконання попереднього виклику `callbackFn`)
Тобто для жирного шрифту ми використовуємо зірочки, а для курсиву - андерскори? Є можливість винести це на рівень автоматичної перевірки і виправлення? (в перспективі)

2022-01-07 11:02 UTC, AdriandeCita commented on files/uk/web/javascript/reference/global_objects/math/hypot/index.md
> +      ? 1 / 0
Форматування вкладених тернарних виразів теж треба перевірити. В оригіналі він явно виділявся дужками, а тут навіть додаткового відступу немає

2022-01-07 11:06 UTC, AdriandeCita commented on files/uk/web/javascript/reference/global_objects/math/log10e/index.md
> +<math display="block"><semantics><mrow><mstyle mathvariant="monospace"><mi>Math.LOG10E</mi></mstyle><mo>=</mo><msub><mo lspace="0em" rspace="0em">log</mo><mn>10</mn></msub><mo stretchy="false">(</mo>
:ok_hand:

2022-01-07 11:10 UTC, AdriandeCita commented on files/uk/web/javascript/reference/global_objects/promise/index.md
> +<!-- окрема область тут -->
оце теж зайве, напевне. Зараз не так очевидно, що воно стосується саме айфрейму

2022-01-07 11:13 UTC, AdriandeCita requested changes
Деякі моменти варто підправити

2022-01-09 18:30 UTC, undead404 commented
Я не можу розібратись, якась штука в VS Code ось так форматує мені Markdown :-D Розширень для цього формату не маю. Можливо, так тепер працює розширення Prettier

2022-01-09 18:38 UTC, undead404 commented on files/uk/web/javascript/reference/global_objects/array/reduce/index.md
> +    - _previousValue_ (результат виконання попереднього виклику `callbackFn`)
Боюсь, від такої перевірки буде більше проблем, аніж допомоги

2022-01-09 19:17 UTC, AdriandeCita commented
Хмм, цікаво, мій vscode наче ніяких зайвих модифікацій в маркдаун не вносить, 100% якесь розширення

2022-01-09 19:22 UTC, AdriandeCita commented
Іще такий момент, цей ПР зачіпає 83 файли. І, оскільки ми визначаємо актуальність нашого перекладу саме за часом останнього коміту, такий масивний ПР позбиває нам всі мітки часу. Є сенс розбити його на менші, щоб було простіше прослідкувати за актуальністю задіяних сторінок

2022-01-11 17:22 UTC, undead404 commented
Нюанс із часом останнього комміту у файл нівелює корисність такого PR

2022-01-11 17:22 UTC, closed without merging

2022-01-11 17:31 UTC, AdriandeCita commented
Такого - так. Слоненят краще жерти потрошки