update(HTML): web/html/global_attributes
webdoky/content pull request #1539
Opened 2023-03-14 09:36 UTC by undead404

Оригінальний вміст: [Глобальні атрибути@MDN](https://developer.mozilla.org/en-us/docs/Web/HTML/Global_attributes), [сирці Глобальні атрибути@GitHub](https://github.com/mdn/content/blob/main/files/en-us/web/html/global_attributes/index.md)

Нові зміни:
- [mdn/content@fa8a44b](https://github.com/mdn/content/commit/fa8a44b8bff24a4032181c4fd155c459c0dc9161)
- [mdn/content@d3cdafc](https://github.com/mdn/content/commit/d3cdafcdb4d22e5c55771501e7c80451a96aa032)
- [mdn/content@5c30b5e](https://github.com/mdn/content/commit/5c30b5e4e57d1a77ce56b88b3de1171d57562808)
- [mdn/content@7671d18](https://github.com/mdn/content/commit/7671d18ab2d141906af448d5bb125eebc16d3994)
- [mdn/content@ba96f2f](https://github.com/mdn/content/commit/ba96f2f183353872db6d9242c7d2dffe2dbc0c35)
- [mdn/content@4a2b6ca](https://github.com/mdn/content/commit/4a2b6cafbf9bc5b006eedbdf0e9fdf2c8626d5b6)
- [mdn/content@8c0dfad](https://github.com/mdn/content/commit/8c0dfadb9fb1407a7216b287d1bc79ce3a1f99c8)
- [mdn/content@e800a2a](https://github.com/mdn/content/commit/e800a2ad1a8f024c710a829c111fb3b2a9ca167f)
- [mdn/content@658fb87](https://github.com/mdn/content/commit/658fb8714c56051b1de99b864b22587eec323d3a)

2023-04-30 20:03 UTC, AdriandeCita commented on files/uk/web/html/global_attributes/index.md
> +  - : [Перелічений](/uk/docs/Glossary/Enumerated) атрибут, що використовується для контролю поведінки екранної віртуальної клавіатури на пристроях штибу планшетів, мобільних телефонів та інших, на як
Ну, значить будуть "перелічені"

2023-04-30 20:03 UTC, AdriandeCita approved these changes

2023-04-30 20:04 UTC, AdriandeCita requested changes
Є свіжі зміни, станом на зараз принаймні три коміти https://github.com/mdn/content/commits/main/files/en-us/web/html/global_attributes/index.md

2023-05-03 06:41 UTC, undead404 commented
Оновлено

2023-05-04 11:43 UTC, undead404 commented
Оновлено

2023-05-19 09:27 UTC, undead404 commented
Зміни з оновлень – відносно суттєві, тому я не просуваю цей PR сильно

2023-08-06 12:34 UTC, KlashReik approved these changes

2023-08-06 13:37 UTC, merged