translation(js): Web/JavaScript/Reference/Global_Objects/String/fromCharCode
webdoky/content pull request #158
Opened 2022-01-07 09:20 UTC by AdriandeCita

Original content: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/fromCharCode

2022-01-10 13:08 UTC, undead404 requested changes

2022-01-10 13:08 UTC, undead404 commented on files/uk/web/javascript/reference/global_objects/string/fromcharcode/index.md
> +Цей повертає рядок, а не об'єкт {{jsxref("String")}}.
```suggestion
Цей метод повертає рядок, а не об'єкт {{jsxref("String")}}.
```

2022-01-10 13:08 UTC, undead404 commented on files/uk/web/javascript/reference/global_objects/string/fromcharcode/index.md
> +Більшість загальновживаних символів в UTF-16 позначається одинарним 16-бітним значенням (тобто — кодовою одиницею). Однак, ця множина символів, відома як Базова Багатомовна Площина (Basic Multilingua
```suggestion
Більшість загальновживаних символів в UTF-16 позначається одинарним 16-бітним значенням (тобто — кодовою одиницею). Втім, ця множина символів, відома як Базове багатомовне поле (Basic Multilingual Plane — BMP), складає лише 1/17 всієї множини придатних для адресації кодових одиниць Unicode. Решта кодових одиниць, на проміжку від `65536` (`0x010000`) і до `1114111` (`0x10FFFF`), — відома як допоміжні або додаткові символи. В UTF-16 додаткові символи позначаються двома 16-бітними кодовими одиницями, відомими як сурогати, зарезервованими для цих потреб. Дійсна комбінація з двох сурогатів, застосована для позначення додаткового символу, називається сурогатною парою.
```
Тут не площина, бо навряд можна пов‘язувати це поняття з чимось пласким

2022-01-10 13:08 UTC, undead404 commented on files/uk/web/javascript/reference/global_objects/string/fromcharcode/index.md
> +Хоча існує математична залежність між значенням допоміжної кодової одиниці (наприклад, `0x1F303`) і обома сурогатними парами, що її позначають (наприклад, `0xD83C` та `0xDF03`), необхідний додатковий
```suggestion
Незважаючи на те, що існує математична залежність між значенням допоміжної кодової одиниці (наприклад, `0x1F303`) і обома сурогатними парами, що її позначають (наприклад, `0xD83C` та `0xDF03`), необхідний додатковий крок для обчислення або пошуку значень сурогатних пар кожного разу, коли вживається допоміжна кодова одиниця. З цієї причини зручніше використовувати {{jsxref("String.fromCodePoint()")}} (яка входить до стандарту ES2015), що дає змогу отримувати допоміжні символи на основі дійсних значень їхніх кодових одиниць. Наприклад, `String.fromCodePoint(0x1F303)` поверне кодову одиницю `U+1F303` "Зоряна ніч".
```

2022-01-10 13:08 UTC, undead404 commented on files/uk/web/javascript/reference/global_objects/string/fromcharcode/index.md
> +В UTF-16 символи базової багатомовної площини займають одну кодову одиницю:
```suggestion
В UTF-16 символи Базового багатомовного поля займають одну кодову одиницю:
```

2022-01-10 13:08 UTC, undead404 commented on files/uk/web/javascript/reference/global_objects/string/fromcharcode/index.md
> +String.fromCharCode(0x12014);      // також повертає "—"; цифра 1 обрізається, тому нею нехтуємо
```suggestion
String.fromCharCode(0x12014);      // також повертає "—"; цифра 1 обрізається, тож нею знехтувано
```

2022-01-10 21:50 UTC, AdriandeCita commented on files/uk/web/javascript/reference/global_objects/string/fromcharcode/index.md
> +Більшість загальновживаних символів в UTF-16 позначається одинарним 16-бітним значенням (тобто — кодовою одиницею). Однак, ця множина символів, відома як Базова Багатомовна Площина (Basic Multilingua
Думаю, тут немає суттєвого значення, сенс не втрачається. Але площина - це також доволі вживаний термін https://uk.wikipedia.org/wiki/%D0%91%D0%B0%D0%B3%D0%B0%D1%82%D0%BE%D0%BC%D0%BE%D0%B2%D0%BD%D0%B0_%D0%BF%D0%BB%D0%BE%D1%89%D0%B8%D0%BD%D0%B0_(%D0%AE%D0%BD%D1%96%D0%BA%D0%BE%D0%B4)

Думаю, якщо уявити собі таблицю символів саме як таблицю - "площина" перестає здаватись чимось чужим для цього контексту

2022-01-11 09:08 UTC, undead404 commented on files/uk/web/javascript/reference/global_objects/string/fromcharcode/index.md
> +Більшість загальновживаних символів в UTF-16 позначається одинарним 16-бітним значенням (тобто — кодовою одиницею). Однак, ця множина символів, відома як Базова Багатомовна Площина (Basic Multilingua
Я гадаю, це калька з російської. Документація Gentoo українською вживає "Багатомовний план".
```suggestion
Більшість загальновживаних символів в UTF-16 позначається одинарним 16-бітним значенням (тобто — кодовою одиницею). Однак, ця множина символів, відома як Базовий багатомовний план (Basic Multilingual Plane — BMP), складає лише 1/17 всієї множини придатних для адресації кодових одиниць Unicode. Решта кодових одиниць, на проміжку від `65536` (`0x010000`) і до `1114111` (`0x10FFFF`) — відома як допоміжні, або додаткові символи. В UTF-16, додаткові символи позначаються двома 16-бітними кодовими одиницями, відомими як сурогати, зарезервованими для цих потреб. Дійсна комбінація з двох сурогатів, застосована для позначення додаткового символу, називається сурогатною парою.
```

2022-01-11 09:08 UTC, undead404 commented on files/uk/web/javascript/reference/global_objects/string/fromcharcode/index.md
> +В UTF-16 символи базової багатомовної площини займають одну кодову одиницю:
```suggestion
В UTF-16 символи базового багатомовного плану займають одну кодову одиницю:
```

2022-01-11 09:33 UTC, AdriandeCita commented on files/uk/web/javascript/reference/global_objects/string/fromcharcode/index.md
> +Більшість загальновживаних символів в UTF-16 позначається одинарним 16-бітним значенням (тобто — кодовою одиницею). Однак, ця множина символів, відома як Базова Багатомовна Площина (Basic Multilingua
ну, можливо, можливо... ок, в такому разі пропоную зупинитись на "плані", він також і у вікіпедії вживається

2022-01-11 11:33 UTC, undead404 approved these changes

2022-01-11 16:31 UTC, merged