translation(HTML): web/html/element/input/image
webdoky/content pull request #1588
Opened 2023-03-30 16:57 UTC by undead404

Оригінальний вміст: [&lt;input type="image">@MDN](https://developer.mozilla.org/en-us/docs/Web/HTML/Element/input/image), [сирці &lt;input type="image">@GitHub](https://github.com/mdn/content/blob/main/files/en-us/web/html/element/input/image/index.md)

2023-09-08 09:56 UTC, KlashReik commented on files/uk/web/html/element/input/image/index.md
> +### Використання порцій даних x та y
Може краще "точок", а не "порцій"?

2023-09-08 09:56 UTC, KlashReik commented on files/uk/web/html/element/input/image/index.md
> +Наступний приклад показує те таку ж кнопку, як вище, але включає її в контекст типової форми входу.
```suggestion
Наступний приклад показує таку ж кнопку, як вище, але включає її в контекст типової форми входу.
```

2023-09-08 09:56 UTC, KlashReik commented on files/uk/web/html/element/input/image/index.md
> +У цьому прикладі попередній приклад змінюється, аби виділити для зображення більше простору, а потім підлаштувати його фактичний розмір і розташування за допомогою {{cssxref("object-fit")}} і {{cssxr
```suggestion
У цьому прикладі попередня реалізація змінюється, аби виділити для зображення більше простору, а потім підлаштувати його фактичний розмір і розташування за допомогою {{cssxref("object-fit")}} і {{cssxref("object-position")}}.
```

2023-09-08 09:57 UTC, KlashReik requested changes
Декілька зауважень

2023-09-08 10:04 UTC, undead404 commented on files/uk/web/html/element/input/image/index.md
> +    - \_`self`: Завантажити відповідь в поточний контекст перегляду. Це значення є усталеним, якщо атрибут не задано.
```suggestion
    - `_self`: Завантажити відповідь в поточний контекст перегляду. Це значення є усталеним, якщо атрибут не задано.
```

2023-09-08 10:05 UTC, undead404 commented on files/uk/web/html/element/input/image/index.md
> +### Використання порцій даних x та y
Не чув, щоб слово "точка" використовувалося в такому значенні, крім хіба "кодових точок Unicode"

2023-09-19 10:03 UTC, KlashReik commented on files/uk/web/html/element/input/image/index.md
> +### Використання порцій даних x та y
```suggestion
### Використання значень x та y
```

2023-09-20 08:20 UTC, KlashReik approved these changes

2023-09-20 09:59 UTC, merged