translation(HTML): web/html/element/input/month
webdoky/content pull request #1590
Opened 2023-04-05 11:56 UTC by undead404

Оригінальний вміст: [&lt;input type="month">@MDN](https://developer.mozilla.org/en-us/docs/Web/HTML/Element/input/month), [сирці &lt;input type="month">@GitHub](https://github.com/mdn/content/blob/main/files/en-us/web/html/element/input/month/index.md)

2023-07-05 21:44 UTC, undead404 commented
Оновлення – нікчемні

2023-09-20 09:24 UTC, KlashReik requested changes

2023-09-20 09:24 UTC, KlashReik commented on files/uk/web/html/element/input/month/index.md
> +Як наслідок, браузери, що це підтримують, покажуть помилку, якщо спробувати подати дату, що лежить поза заданими межами, або порожнє її поле.
```suggestion
Як наслідок, браузери, що це підтримують, покажуть помилку, якщо спробувати подати дату, що лежить поза заданими межами, або порожнє поле.
```

2023-09-20 09:24 UTC, KlashReik commented on files/uk/web/html/element/input/month/index.md
> +Як згадувалося вище, головна проблема при використанні полів дат під час написання цієї статті – те, що серед головних браузерів чимало іще не мають реалізації їх усіх; лише Chrome-Opera та Edge підт
```suggestion
Як згадувалося вище, головна проблема при використанні полів дат під час написання цієї статті – те, що серед головних браузерів чимало іще не мають реалізації їх усіх; лише Chrome, Opera та Edge підтримують їх на настільних комп'ютерах, а також більшість сучасних браузерів на мобільних. Наприклад, інтерфейс `month` на Chrome для Android має такий вигляд:
```

2023-09-20 09:24 UTC, KlashReik commented on files/uk/web/html/element/input/month/index.md
> +Один зі способів це обійти – додати полю `month` атрибут [`pattern`](/uk/docs/Web/HTML/Element/input#pattern) `month`.
```suggestion
Один зі способів це обійти – додати полю `month` атрибут [`pattern`](/uk/docs/Web/HTML/Element/input#pattern).
```

2023-09-20 09:24 UTC, KlashReik commented on files/uk/web/html/element/input/month/index.md
> +Форма, що запитує місяць і рік, має такий вигляд?
```suggestion
Форма, що запитує місяць і рік, має такий вигляд:
```

2023-09-20 09:24 UTC, KlashReik commented on files/uk/web/html/element/input/month/index.md
> +Код JavaScript, що обробляє вибір конкретного підходу й налаштовує список років для виводу в ненативному `<select>` року – нижче..
```suggestion
Код JavaScript, що обробляє вибір конкретного підходу й налаштовує список років для виводу в ненативному `<select>` з роками – нижче.
```

2023-09-20 09:24 UTC, KlashReik commented on files/uk/web/html/element/input/month/index.md
> +Код JavaScript, що обробляє вибір конкретного підходу й налаштовує список років для виводу в ненативному `<select>` року – нижче..
```suggestion
Код JavaScript, що обробляє вибір конкретного підходу й налаштовує список років для виводу в ненативному `<select>` – нижче.
```

Ось такі варіанти. Який подобається більше?

2023-09-20 09:24 UTC, KlashReik commented on files/uk/web/html/element/input/month/index.md
> +Браузери, що не підтримують тип `month`, повернуть `text`, оскільки це те, До чого відступає поле місяця, коли не підтримується.
```suggestion
Браузери, що не підтримують тип `month`, повернуть `text`, оскільки це те до чого відступає поле місяця, коли не підтримується.
```

2023-09-20 09:24 UTC, KlashReik commented on files/uk/web/html/element/input/month/index.md
> +// Перевірити, чи відступає нове поле дати до текстового поля, чи ні
```suggestion
// Перевірити чи відступає нове поле дати до текстового поля, чи ні
```

2023-09-20 10:00 UTC, undead404 commented on files/uk/web/html/element/input/month/index.md
> +Як згадувалося вище, головна проблема при використанні полів дат під час написання цієї статті – те, що серед головних браузерів чимало іще не мають реалізації їх усіх; лише Chrome-Opera та Edge підт
Ні, тут малась на увазі саме Chrome-Opera, здається

2023-09-20 10:01 UTC, undead404 commented on files/uk/web/html/element/input/month/index.md
> +Браузери, що не підтримують тип `month`, повернуть `text`, оскільки це те, До чого відступає поле місяця, коли не підтримується.
А кома куди ділась...

2023-09-20 10:01 UTC, undead404 commented on files/uk/web/html/element/input/month/index.md
> +// Перевірити, чи відступає нове поле дати до текстового поля, чи ні
Е, ну ні, тут кома лишається

2023-09-21 07:18 UTC, KlashReik commented on files/uk/web/html/element/input/month/index.md
> +// Перевірити, чи відступає нове поле дати до текстового поля, чи ні
А чому?

2023-09-21 07:18 UTC, KlashReik commented on files/uk/web/html/element/input/month/index.md
> +Браузери, що не підтримують тип `month`, повернуть `text`, оскільки це те, До чого відступає поле місяця, коли не підтримується.
```suggestion
Браузери, що не підтримують тип `month`, повернуть `text`, оскільки це те, до чого відступає поле місяця, коли не підтримується.
```

2023-09-21 07:21 UTC, KlashReik commented on files/uk/web/html/element/input/month/index.md
> +Як згадувалося вище, головна проблема при використанні полів дат під час написання цієї статті – те, що серед головних браузерів чимало іще не мають реалізації їх усіх; лише Chrome-Opera та Edge підт
Хром та Опера однаково підтримуються цей тип інпуту по статті. Про те, що Хром та Опера між собою більш схожі не було нічого написано. Тому вважаю, що краще використати кому.
P.S. Гадаю, що вони по-приколу туди "/" вліпили :)

2023-09-21 08:12 UTC, undead404 commented on files/uk/web/html/element/input/month/index.md
> +// Перевірити, чи відступає нове поле дати до текстового поля, чи ні
Бо це складнопідрядне речення з двома синтаксичними центрами, воно розділяється комами https://www.miyklas.com.ua/p/ukrainska-mova/9-klas/skladnopidriadne-rechennia-43534/poniattia-pro-skladnopidriadne-rechennia-41448/re-7628dd75-fe20-4253-978e-9e69ad01413a

Можливо, ти побачиш в цьому інше тлумачення, але я точно бачу тут кому

2023-09-25 07:20 UTC, KlashReik commented on files/uk/web/html/element/input/month/index.md
> +// Перевірити, чи відступає нове поле дати до текстового поля, чи ні
Тю, шось я дурню зробив. Звісно кома має бути.

2023-09-25 07:22 UTC, KlashReik approved these changes

2023-09-25 08:33 UTC, merged