translation(HTML): web/html/element/input/search
webdoky/content pull request #1599
Opened 2023-04-14 14:02 UTC by undead404

Оригінальний вміст: [&lt;input type="search">@MDN](https://developer.mozilla.org/en-us/docs/Web/HTML/Element/input/search), [сирці &lt;input type="search">@GitHub](https://github.com/mdn/content/blob/main/files/en-us/web/html/element/input/search/index.md)

2023-04-18 13:48 UTC, undead404 commented on files/uk/web/html/element/input/search/index.md
> +Значення атрибута list – це {{domxref("Element.id", "id")}} елемента {{HTMLElement("datalist")}}, розташованого в тому самому документі. {{HTMLElement("datalist")}} надає список наперед визначених зн
```suggestion
Значення атрибута list – це {{domxref("Element.id", "id")}} елемента {{HTMLElement("datalist")}}, розташованого в тому самому документі. {{HTMLElement("datalist")}} надає список наперед визначених значень, що пропонуються користувачам для поля. Всі значення в списку, несумісні з [`type`](/uk/docs/Web/HTML/Element/input#type), не включаються в список запропонованих варіантів. Ці значення подаються як пропозиції, а не вимога: користувачі можуть як обирати зі списку, так і ввести щось своє
```

2023-06-11 06:05 UTC, undead404 commented
Розв'язано конфлікт

2023-09-15 08:45 UTC, KlashReik requested changes
пара зауважень

2023-09-15 08:45 UTC, KlashReik commented on files/uk/web/html/element/input/search/index.md
> +Всередині пошукового поля можна дати змістовний заповнювач, котрий служитиме підказкою щодо того, що з полем робити, за допомогою атрибута [`placeholder`](/uk/docs/Web/HTML/Element/input#placeholder)
```suggestion
Всередині пошукового поля можна дати змістовний заповнювач, котрий служитиме підказкою щодо того, що робити з полем, за допомогою атрибута [`placeholder`](/uk/docs/Web/HTML/Element/input#placeholder). Погляньте на наступний приклад:
```

2023-09-15 08:45 UTC, KlashReik commented on files/uk/web/html/element/input/search/index.md
> +Одна з проблем пошукових форм – їхня доступність; загальноприйнята практика проєктування – не давати пошуковому полю підпису (хоч у нього може бути піктограма збільшувального скла чи щось подібне), а
```suggestion
Одна з проблем пошукових форм – їхня доступність. Загальноприйнята практика проєктування – не давати пошуковому полю підпису (хоч у нього може бути піктограма збільшувального скла чи щось подібне), адже призначення пошукового поля зазвичай доволі очевидне для зрячих користувачів, у зв'язку зі своїм розташуванням ([цей приклад показує типовий патерн](https://mdn.github.io/learning-area/accessibility/aria/website-aria-roles/)).
```

2023-09-15 10:01 UTC, merged