translation(JS): Web/JavaScript/Reference/Global_Objects/Object/freeze
webdoky/content pull request #1635
Opened 2023-04-25 18:44 UTC by AdriandeCita

Оригінальний вміст: [Object.freeze()@MDN](https://developer.mozilla.org/en-us/docs/Web/JavaScript/Reference/Global_Objects/Object/freeze), [сирці Object.freeze()@GitHub](https://github.com/mdn/content/blob/main/files/en-us/web/javascript/reference/global_objects/object/freeze/index.md)

2023-04-25 21:09 UTC, undead404 requested changes

2023-04-25 21:09 UTC, undead404 commented on files/uk/web/javascript/reference/global_objects/object/freeze/index.md
> +  - lock
```suggestion
```

2023-04-25 21:09 UTC, undead404 commented on files/uk/web/javascript/reference/global_objects/object/freeze/index.md
> +Стосовно властивостей даних у заморожених об'єктів — їхні значення неможливо змінити, адже значенням їхніх атрибутів записуваності та налаштовності встановлюється `false`. Аксесорні властивості (гете
```suggestion
Стосовно властивостей даних у заморожених об'єктів — їхні значення неможливо змінити, адже значенням їхніх атрибутів записуваності та налаштовності встановлюється `false`. Аксесорні властивості (гетери й сетери) працюють як і раніше — значення, повернене гетером, все ще може змінюватися, а сетер і далі зможе викликатися без викидання помилки, під час встановлення значень властивості. Слід зауважити, що ті значення властивостей, які є об'єктами, можна буде й далі змінювати, якщо вони також не заморожені. Як і об'єкт, масив також можна заморозити. Після цього його елементи неможливо буде змінити, і жодного елемента не можна буде додати чи видалити з масиву.
```

2023-04-25 21:09 UTC, undead404 commented on files/uk/web/javascript/reference/global_objects/object/freeze/index.md
> +Примірник {{jsxref("TypedArray")}} чи {{jsxref("DataView")}} з елементами призведуть до помилки {{jsxref("TypeError")}}, оскільки вони є проєкціями на область пам'яті, і авжеж призведуть до інших мож
```suggestion
Примірник {{jsxref("TypedArray")}} чи {{jsxref("DataView")}} з елементами призведе до помилки {{jsxref("TypeError")}}, оскільки такі об'єкти є проєкціями на область пам'яті, і, авжеж, призведуть до інших можливих проблем:
```

2023-04-25 21:09 UTC, undead404 commented on files/uk/web/javascript/reference/global_objects/object/freeze/index.md
> +Заморожений об'єкт стає _імутабельним_. Проте, це не обов'язково означає _сталий_. Наступний приклад ілюструє, що заморожений об'єкт не є сталим(тобто, замороження є поверхневим).
```suggestion
Заморожений об'єкт стає _імутабельним_. Проте це не обов'язково означає, що він буде _сталим_. Наступний приклад ілюструє, що заморожений об'єкт не є сталим (тобто, замороження є поверхневим).
```

2023-04-25 21:09 UTC, undead404 commented on files/uk/web/javascript/reference/global_objects/object/freeze/index.md
> +Аби зробити весь об'єкт незмінним — слід рекурсивно заморозити кожну з тих його властивостей, які мають об'єктний тип (глибоке замороження). Можна застосовувати цей патерн в архітектурі, залежно від
```suggestion
Аби зробити весь об'єкт незмінним — слід рекурсивно заморозити кожну з тих його властивостей, які мають об'єктний тип (глибоке замороження). Можна застосовувати цей патерн в архітектурі, залежно від конкретного випадку — якщо відомо, що об'єкт не містить [зациклень](<https://uk.wikipedia.org/wiki/%D0%A6%D0%B8%D0%BA%D0%BB_(%D1%82%D0%B5%D0%BE%D1%80%D1%96%D1%8F_%D0%B3%D1%80%D0%B0%D1%84%D1%96%D0%B2)>) у графі залежностей, бо інакше це спричинить нескінченний цикл. Певним вдосконаленням функції `deepFreeze()` було б додати внутрішню функцію, яка б отримувала аргумент (наприклад, масив Array) зі шляхом до об'єкта, щоб можна було заблокувати рекурсивний виклик `deepFreeze()` в разі, якщо об'єкт вже в процесі замороження. Проте залишиться ризик заморозити об'єкт, який заморожуватися не повинен, наприклад — \[window].
```

2023-04-26 18:40 UTC, AdriandeCita commented on files/uk/web/javascript/reference/global_objects/object/freeze/index.md
> +  - lock
ммм?

2023-04-26 18:41 UTC, undead404 commented
В тебе одне оновлення пропущено, це воно.

ср, 26 квіт. 2023 р., 21:40 користувач Mykola Myslovskyi <
***@***.***> пише:

> ***@***.**** commented on this pull request.
> ------------------------------
>
> In files/uk/web/javascript/reference/global_objects/object/freeze/index.md
> <https://github.com/webdoky/content/pull/1635#discussion_r1178259930>:
>
> > +tags:
> +  - Change
> +  - Changeability
> +  - ECMAScript 5
> +  - JavaScript
> +  - Method
> +  - Mutability
> +  - Mutable
> +  - Object
> +  - Reference
> +  - freeze
> +  - lock
>
> ммм?
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/webdoky/content/pull/1635#discussion_r1178259930>, or
> unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AFN3MVNCGBVRN7NO2K6N3EDXDFT3JANCNFSM6AAAAAAXLMUYTM>
> .
> You are receiving this because your review was requested.Message ID:
> ***@***.***>
>

2023-04-26 18:41 UTC, AdriandeCita commented on files/uk/web/javascript/reference/global_objects/object/freeze/index.md
> +  - lock
а-а, теги видаляються, прийняв

2023-04-27 07:26 UTC, undead404 approved these changes

2023-04-27 07:26 UTC, merged