translation(HTML): web/html/element/input/time
webdoky/content pull request #1683
Opened 2023-05-02 16:35 UTC by undead404

Оригінальний вміст: [&lt;input type="time">@MDN](https://developer.mozilla.org/en-us/docs/Web/HTML/Element/input/time), [сирці &lt;input type="time">@GitHub](https://github.com/mdn/content/blob/main/files/en-us/web/html/element/input/time/index.md)

2023-07-05 21:55 UTC, undead404 commented
Оновлення – нікчемне

2023-09-25 08:17 UTC, KlashReik requested changes
декілька зауважень

2023-09-25 08:17 UTC, KlashReik commented on files/uk/web/html/element/input/time/index.md
> +Як зазначалося, старі версії Safari та деякі інші, менш поширені, браузери не підтримують нативно поля часу. В цілому, підтримка досить хороша — особливо на мобільних платформах, де зазвичай дуже гар
```suggestion
Як зазначалося, старі версії Safari та деякі інші, менш поширені браузери не підтримують нативно поля часу. В цілому, підтримка досить хороша — особливо на мобільних платформах, де зазвичай дуже гарні користувацькі інтерфейси для задання часових значень. Наприклад, вибір часу в Chrome для Android має такий вигляд:
```

Мені здається, що кома тут помилкова після less common, адже зміст стає незрозумілим.

2023-09-25 08:49 UTC, KlashReik approved these changes

2023-09-25 08:49 UTC, merged