translation(HTML): web/html/element/audio
webdoky/content pull request #1739
Opened 2023-05-09 11:20 UTC by undead404

Оригінальний вміст: [&lt;audio>: The Embed Audio element@MDN](https://developer.mozilla.org/en-us/docs/Web/HTML/Element/audio), [сирці &lt;audio>: The Embed Audio element@GitHub](https://github.com/mdn/content/blob/main/files/en-us/web/html/element/audio/index.md)

Залежить від:
* https://github.com/webdoky/interactive-examples/pull/105

2023-10-20 11:50 UTC, KlashReik requested changes
незначні зауваження

2023-10-20 11:50 UTC, KlashReik commented on files/uk/web/html/element/audio/index.md
> +  - : Цей [перелічений](/uk/docs/Glossary/Enumerated) атрибут позначає те, чи потрібно використовувати CORS для отримання пов'язаного аудіофайлу. [Ресурси, що підтримують CORS](/uk/docs/Web/HTML/CORS
Можливо тут мається на увазі tainted як зараженими? Можу помилятися, не маю достатніх знань у цій темі.

2023-10-20 11:50 UTC, KlashReik commented on files/uk/web/html/element/audio/index.md
> +Не всі браузери підтримують одній й ті самі [типи файлів](/uk/docs/Web/Media/Formats/Containers) та [кодеки аудіо](/uk/docs/Web/Media/Formats/Audio_codecs); можна надати декілька джерел у вкладених е
```suggestion
Не всі браузери підтримують одній й ті самі [типи файлів](/uk/docs/Web/Media/Formats/Containers) та [кодеки аудіо](/uk/docs/Web/Media/Formats/Audio_codecs); можна надати декілька джерел у вкладених елементах {{htmlelement("source")}}, і браузер використає перше, яке зрозуміє:
```

2023-10-20 11:50 UTC, KlashReik commented on files/uk/web/html/element/audio/index.md
> +  - : Додайте до цього об'єкта {{domxref("VideoTrackList")}} слухач `addtrack`, щоб отримати звістку про додавання до елемента доріжок відео.
```suggestion
  - : Додайте до об'єкта {{domxref("VideoTrackList")}} слухач `addtrack`, щоб отримати звістку про додавання до елемента доріжок відео.
```

2023-10-20 11:50 UTC, KlashReik commented on files/uk/web/html/element/audio/index.md
> +  - : Додайте до цього об'єкта {{domxref("TextTrackList")}} слухач подій `addtrack`, щоб отримати звістку про додавання до елемента нових текстових доріжок.
```suggestion
  - : Додайте до об'єкта {{domxref("TextTrackList")}} слухач подій `addtrack`, щоб отримати звістку про додавання до елемента нових текстових доріжок.
```

2023-10-20 11:50 UTC, KlashReik commented on files/uk/web/html/element/audio/index.md
> +Цей приклад задає те, яку аудіодоріжку вбудувати, використовуючи атрибут `src` вкладеного елемента `<source>`, а не безпосередньо на елементі `<audio>`. Завжди корисно включати MIME-тип файлу в атриб
```suggestion
Цей приклад задає те, яку аудіодоріжку вбудувати, використовуючи атрибут `src` вкладеного елемента `<source>`, а не безпосередньо на елементі `<audio>`. Завжди корисно включати MIME-тип файлу в атрибут `type`, оскільки так браузер може миттєво визначити чи здатен він відтворити цей файл, і не витрачати на нього час, якщо ні.
```

2023-10-20 11:50 UTC, KlashReik commented on files/uk/web/html/element/audio/index.md
> +  <a href="foo.wav">Стягнути аудіо WAV</a>.
```suggestion
  <a href="foo.wav">Стягнути аудіо у форматі WAV</a>.
```

2023-10-20 11:50 UTC, KlashReik commented on files/uk/web/html/element/audio/index.md
> +  <a href="AudioTest.ogg">Стягнути аудіо OGG</a>.
```suggestion
  <a href="AudioTest.ogg">Стягнути аудіо у форматі OGG</a>.
```

2023-10-20 11:50 UTC, KlashReik commented on files/uk/web/html/element/audio/index.md
> +[Сміх] Вибачте! Я маю на увазі, який наручний годинник є швейцарським годинником?
```suggestion
[Сміх] Вибачте! Я маю на увазі, який наручний годинник є швейцарським годинником.
```

2023-10-20 11:50 UTC, KlashReik commented on files/uk/web/html/element/audio/index.md
> +    Стягнути аудіо <a href="myAudio.mp3">MP3</a> або
```suggestion
    Стягнути аудіо у форматах <a href="myAudio.mp3">MP3</a> або
```

2023-10-21 07:43 UTC, undead404 commented on files/uk/web/html/element/audio/index.md
> +  - : Цей [перелічений](/uk/docs/Glossary/Enumerated) атрибут позначає те, чи потрібно використовувати CORS для отримання пов'язаного аудіофайлу. [Ресурси, що підтримують CORS](/uk/docs/Web/HTML/CORS
Ні, це не щось однозначно шкідливе. Це лише означає, що ресурси, які отримано з потенційно небезпечних джерел, стають _ославленими_, тобто їх варто остерігатися, і їх не можна використовувати в певних випадках

2023-10-21 07:45 UTC, undead404 commented on files/uk/web/html/element/audio/index.md
> +Цей приклад задає те, яку аудіодоріжку вбудувати, використовуючи атрибут `src` вкладеного елемента `<source>`, а не безпосередньо на елементі `<audio>`. Завжди корисно включати MIME-тип файлу в атриб
Тут має бути кома, що розділяє частини складнопідрядного речення

2023-10-21 07:46 UTC, undead404 commented on files/uk/web/html/element/audio/index.md
> +[Сміх] Вибачте! Я маю на увазі, який наручний годинник є швейцарським годинником?
Чому ти пропонуєш прибрати знак питання в кінці питання?

2023-11-01 08:00 UTC, KlashReik commented on files/uk/web/html/element/audio/index.md
> +[Сміх] Вибачте! Я маю на увазі, який наручний годинник є швейцарським годинником?
Бо це вже не запитання.

2023-11-01 08:00 UTC, KlashReik commented on files/uk/web/html/element/audio/index.md
> +Цей приклад задає те, яку аудіодоріжку вбудувати, використовуючи атрибут `src` вкладеного елемента `<source>`, а не безпосередньо на елементі `<audio>`. Завжди корисно включати MIME-тип файлу в атриб
Зауваження знімається, а кома - залишається)

2023-11-01 08:01 UTC, KlashReik commented on files/uk/web/html/element/audio/index.md
> +  - : Цей [перелічений](/uk/docs/Glossary/Enumerated) атрибут позначає те, чи потрібно використовувати CORS для отримання пов'язаного аудіофайлу. [Ресурси, що підтримують CORS](/uk/docs/Web/HTML/CORS
Окей, хай буде так

2023-11-03 09:20 UTC, KlashReik approved these changes

2023-11-03 09:27 UTC, merged