translation(HTML): web/html/element/input/week
webdoky/content pull request #1740
Opened 2023-05-11 06:19 UTC by undead404

Оригінальний вміст: [&lt;input type="week">@MDN](https://developer.mozilla.org/en-us/docs/Web/HTML/Element/input/week), [сирці &lt;input type="week">@GitHub](https://github.com/mdn/content/blob/main/files/en-us/web/html/element/input/week/index.md)

2023-07-06 09:36 UTC, undead404 commented
Оновлення – нікчемне

2023-09-26 09:16 UTC, KlashReik requested changes
Декілька зауважень

2023-09-26 09:16 UTC, KlashReik commented on files/uk/web/html/element/input/week/index.md
> +Повинна була б бути змога використовувати атрибут [`step`](/uk/docs/Web/HTML/Element/input#step-krok), щоб змінити кількість тижнів, які перескакуються при інкременті або декременті значення, проте с
```suggestion
Повинна була б бути змога використовувати атрибут [`step`](/uk/docs/Web/HTML/Element/input#step-krok), щоб змінити кількість тижнів, які перескакуються при інкременті або декременті значення, проте, схоже, що він ніяк не діє в браузерах, що підтримують тип поля `week`.
```

2023-09-26 09:16 UTC, KlashReik commented on files/uk/web/html/element/input/week/index.md
> +  // динамічно заповнити тижні
Не розумію чому тут вже перша буква маленька

2023-09-26 09:16 UTC, KlashReik commented on files/uk/web/html/element/input/week/index.md
> +  // заповнити select тижнів 52 тижнями
І тут. Так і залишаємо?

2023-09-27 07:45 UTC, undead404 commented on files/uk/web/html/element/input/week/index.md
> +  // динамічно заповнити тижні
Я, як правило, залишаю регістр як в оригіналі в таких випадках

2023-09-27 07:45 UTC, undead404 commented on files/uk/web/html/element/input/week/index.md
> +  // заповнити select тижнів 52 тижнями
Я б залишив

2023-09-27 11:31 UTC, KlashReik approved these changes

2023-09-27 12:04 UTC, merged