translation(HTML): web/html/attributes/autocomplete
webdoky/content pull request #1747
Opened 2023-05-15 15:31 UTC by undead404

Оригінальний вміст: [HTML attribute: autocomplete@MDN](https://developer.mozilla.org/en-us/docs/Web/HTML/Attributes/autocomplete), [сирці HTML attribute: autocomplete@GitHub](https://github.com/mdn/content/blob/main/files/en-us/web/html/attributes/autocomplete/index.md)

2023-11-27 20:41 UTC, undead404 reviewed
Still relevant?

2023-11-27 20:51 UTC, undead404 reviewed
Still relevant?

2023-11-27 20:56 UTC, undead404 reviewed
Still relevant?

2023-11-27 21:03 UTC, undead404 reviewed
Still relevant?

2023-12-05 09:14 UTC, KlashReik requested changes
Декілька зауважень

2023-12-05 09:14 UTC, KlashReik commented on files/uk/web/html/attributes/autocomplete/index.md
> +  - : Сума, вказана в валюті, вказаній у "`transaction-currency`", транзакції для платіжної форми.
```suggestion
  - : Сума, вказана в валюті, описана в "`transaction-currency`", транзакції для платіжної форми.
```

2023-12-05 09:14 UTC, KlashReik commented on files/uk/web/html/attributes/autocomplete/index.md
> +  - : Сума, вказана в валюті, вказаній у "`transaction-currency`", транзакції для платіжної форми.
```suggestion
  - : Сума, вказана в валюті, визначена в "`transaction-currency`", транзакції для платіжної форми.
```

2023-12-05 10:18 UTC, undead404 commented on files/uk/web/html/attributes/autocomplete/index.md
> +  - : Кожен окремий рядок адреси на вулиці. Такі поля повинні з'являтися лише тоді, коли "`street-address`" відсутнє.
"Адреса на вулиці" – тут мова про "вулиця така-то, будинок такий-то, квартира така-то" – оцю частину адреси.

Можливо, краще взагалі сформулювати інакше

2023-12-05 10:18 UTC, undead404 commented on files/uk/web/html/attributes/autocomplete/index.md
> +  - : Сума, вказана в валюті, вказаній у "`transaction-currency`", транзакції для платіжної форми.
В тому значенні описана саме валюта, а не сума

2023-12-07 08:55 UTC, KlashReik commented on files/uk/web/html/attributes/autocomplete/index.md
> +  - : Сума, вказана в валюті, вказаній у "`transaction-currency`", транзакції для платіжної форми.
```suggestion
  - : Сума, описана у валюті, вказана у "`transaction-currency`", транзакції для платіжної форми.
```

Так краще?

2023-12-07 09:18 UTC, undead404 commented on files/uk/web/html/attributes/autocomplete/index.md
> +  - : Сума, вказана в валюті, вказаній у "`transaction-currency`", транзакції для платіжної форми.
Ні, так само не те.

transaction-amout – сама сума, тобто число. transaction-currency – це валюта.

2023-12-11 08:40 UTC, KlashReik commented on files/uk/web/html/attributes/autocomplete/index.md
> +  - : Кожен окремий рядок адреси на вулиці. Такі поля повинні з'являтися лише тоді, коли "`street-address`" відсутнє.
"Адреса будівлі"/"Адреса приміщення"?

2023-12-11 08:44 UTC, KlashReik commented on files/uk/web/html/attributes/autocomplete/index.md
> +  - : Сума, вказана в валюті, вказаній у "`transaction-currency`", транзакції для платіжної форми.
```suggestion
  - : Сума, вказана в валюті, котра зі свого боку - у "`transaction-currency`", транзакції для платіжної форми.
```

А таке шось?

2023-12-11 10:45 UTC, undead404 commented on files/uk/web/html/attributes/autocomplete/index.md
> +  - : Сума, вказана в валюті, вказаній у "`transaction-currency`", транзакції для платіжної форми.
```suggestion
  - : Сума, вказана в валюті, котра зі свого боку – у "`transaction-currency`", транзакції для платіжної форми.
```

2023-12-14 08:44 UTC, KlashReik commented on files/uk/web/html/attributes/autocomplete/index.md
> +  - : Кожен окремий рядок адреси на вулиці. Такі поля повинні з'являтися лише тоді, коли "`street-address`" відсутнє.
```suggestion
  - : Вулична адреса. Значення може мати кілька рядків тексту і повинно цілком ідентифікувати місце адреси в межах другого адміністративного рівня (зазвичай міста або містечка), але не повинно вміщати назву міста, поштовий індекс та назву країни.
    - "`shipping`"
      - : Вулична адреса для надсилання товару. Може бути поєднана з іншими лексемами, наприклад, "`shipping street-address`" чи "`shipping address-level2`".
    - "`billing`"
      - : Вулична адреса для зв'язування з використаною формою оплати. Може бути поєднана з іншими лексемами, наприклад, "`billing street-address`" чи "`billing address-level2`".
- "`address-line1`", "`address-line2`", "`address-line3`"
  - : Кожен окремий рядок вуличної адреси. Такі поля повинні з'являтися лише тоді, коли "`street-address`" відсутнє.
```

2023-12-14 10:29 UTC, KlashReik approved these changes

2023-12-14 10:55 UTC, merged