translation(glossary): glossary/inline-level_content
webdoky/content pull request #1748
Opened 2023-05-15 15:42 UTC by undead404

Оригінальний вміст: [Inline-level content@MDN](https://developer.mozilla.org/en-us/docs/Glossary/Inline-level_content), [сирці Inline-level content@GitHub](https://github.com/mdn/content/blob/main/files/en-us/glossary/inline-level_content/index.md)

2023-05-17 07:52 UTC, AdriandeCita commented on files/uk/glossary/inline-level_content/index.md
> +При рядковому компонуванні змішаний потік тексту, [заміщених елементів](/uk/docs/Web/CSS/Replaced_element) та інших рядкових рамок розміщується шляхом фрагментації їх у стеку лінійних рамок. У межах
"лінійні рамки" натякають на те, що є іще й нелінійні (квадратичні? експоненційні? щось цікавіше?). Насправді в оригіналі малося на увазі, що весь масив рядкового вмісту розбивається на рядки.

Також починаю випаравляти шикування)
```suggestion
При рядковому компонуванні змішаний потік тексту, [заміщених елементів](/uk/docs/Web/CSS/Replaced_element) та інших рядкових рамок розміщується шляхом розбивання їх на стос рядкових рамок. У межах кожної рядкової рамки, рамки рядкового рівня шикуються одна відносно одної по вертикалі або горизонталі, залежно від напрямку письма. Зазвичай вони вирівнюються відносно базових ліній їхнього тексту. Це можна змінити за допомогою CSS.
```

2023-05-17 07:54 UTC, AdriandeCita commented on files/uk/glossary/inline-level_content/index.md
> +У цьому прикладі елемент {{HTMLElement("p")}} містить певний текст. У межах цього тексту є елемент {{HTMLElement("span")}} та два елементи {{HTMLElement("input")}}, які є елементами рядкового рівня.
```suggestion
У цьому прикладі елемент {{HTMLElement("p")}} містить певний текст. У межах цього тексту є елемент {{HTMLElement("span")}} та два елементи {{HTMLElement("input")}}, які є елементами рядкового рівня. Якщо `<span>` простягається на два рядки, генеруються дві рядкові рамки. У зв'язку з тим, що ці елементи є рядковими, абзац правильно візуалізується як один абзац неперервного текстового потоку:
```

2023-05-17 07:54 UTC, AdriandeCita requested changes
пара зауважень

2023-05-17 10:09 UTC, undead404 commented on files/uk/glossary/inline-level_content/index.md
> +При рядковому компонуванні змішаний потік тексту, [заміщених елементів](/uk/docs/Web/CSS/Replaced_element) та інших рядкових рамок розміщується шляхом фрагментації їх у стеку лінійних рамок. У межах
Ні, так не піде, це ти в одному тексті "inline box" і "line box" перекладаєш однаково

2023-05-17 10:09 UTC, undead404 commented on files/uk/glossary/inline-level_content/index.md
> +При рядковому компонуванні змішаний потік тексту, [заміщених елементів](/uk/docs/Web/CSS/Replaced_element) та інших рядкових рамок розміщується шляхом фрагментації їх у стеку лінійних рамок. У межах
Я переклав "line box" як "лінійну рамку", а "inline box" – як "рядкову".

2023-11-27 21:11 UTC, undead404 reviewed
Still relevant?

2024-02-15 13:14 UTC, undead404 commented
Still relevant?

2024-02-15 13:14 UTC, undead404 reviewed
Still relevant?

2024-07-19 13:41 UTC, undead404 reviewed
Relevant?

2024-08-09 20:27 UTC, alinkedd reviewed
Relevant?

2024-12-27 16:29 UTC, AdriandeCita commented on files/uk/glossary/inline-level_content/index.md
> +При рядковому компонуванні змішаний потік тексту, [заміщених елементів](/uk/docs/Web/CSS/Replaced_element) та інших рядкових рамок розміщується шляхом фрагментації їх у стеку лінійних рамок. У межах
нухз поки, я не маю наразі кращих варіантів. Най буде поки так

2024-12-27 16:32 UTC, merged