translation(glossary): glossary/baseline/compatibility
webdoky/content pull request #1750
Opened 2023-05-15 17:56 UTC by undead404

Оригінальний вміст: [Baseline (compatibility)@MDN](https://developer.mozilla.org/en-us/docs/Glossary/Baseline/Compatibility), [сирці Baseline (compatibility)@GitHub](https://github.com/mdn/content/blob/main/files/en-us/glossary/baseline/compatibility/index.md)

2023-10-20 13:35 UTC, KlashReik requested changes
невеличне зауваження

2023-10-20 13:35 UTC, KlashReik commented on files/uk/glossary/baseline/compatibility/index.md
> +База – це спільна робота Групи спільноти WebDX W3C, вона ґрунтується на відкритих даних про сумісність браузерів від MDN.
```suggestion
База – це спільна робота спільноти WebDX W3C, вона ґрунтується на відкритих даних про сумісність браузерів від MDN.
```

2023-10-21 07:48 UTC, undead404 commented on files/uk/glossary/baseline/compatibility/index.md
> +База – це спільна робота Групи спільноти WebDX W3C, вона ґрунтується на відкритих даних про сумісність браузерів від MDN.
Вона саме так називається – WebDX Community Group

2023-11-03 09:22 UTC, KlashReik commented on files/uk/glossary/baseline/compatibility/index.md
> +База – це спільна робота Групи спільноти WebDX W3C, вона ґрунтується на відкритих даних про сумісність браузерів від MDN.
```suggestion
База – це спільна робота спільноти W3C WebDX Community Group, вона ґрунтується на відкритих даних про сумісність браузерів від MDN.
```
Може тоді так?

2023-11-03 12:05 UTC, KlashReik approved these changes

2023-11-03 12:59 UTC, merged