translation(HTML): web/html/element/dialog
webdoky/content pull request #1751
Opened 2023-05-16 10:07 UTC by undead404

Оригінальний вміст: [&lt;dialog>: The Dialog element@MDN](https://developer.mozilla.org/en-us/docs/Web/HTML/Element/dialog), [сирці &lt;dialog>: The Dialog element@GitHub](https://github.com/mdn/content/blob/main/files/en-us/web/html/element/dialog/index.md)

2023-11-26 20:14 UTC, undead404 commented on files/uk/web/html/element/dialog/index.md
> +Елементи `<dialog>` отримують `display: none;`, коли приховані, і `display: block;`, коли показані, а також вилучаються чи додаються до {{glossary("top layer", "вищого шару")}} та [дерева доступності
```suggestion
Елементи `<dialog>` отримують `display: none;`, коли приховані, і `display: block;`, коли показані, а також вилучаються чи додаються до {{glossary("top layer", "вищого шару")}} та [дерева доступності](/uk/docs/Web/Performance/How_browsers_work#vybudovuvannia-dereva-dostupnosti). Тому для анімування елементів `<dialog>` властивість {{cssxref("display")}} повинна бути придатною для анімування. [Браузери, що це підтримують](/uk/docs/Web/CSS/display#sumisnist-iz-brauzeramy), анімують `display` з варіацією на [дискретному типі анімації](/uk/docs/Web/CSS/CSS_animated_properties#dyskretni). А саме, браузер перемикається між `none` та іншим значенням `display` так, щоб анімований вміст був видимим протягом усієї тривалості анімації.
```

2023-11-26 20:14 UTC, undead404 commented on files/uk/web/html/element/dialog/index.md
> +  - : Задайте на переходах `display` і `overlay` `transition-behavior: allow-discrete` (або на скороченні {{cssxref("transition")}}), щоб увімкнути дискретні переходи на цих двох властивостях, які ус
```suggestion
  - : Задайте на переходах `display` та `overlay` `transition-behavior: allow-discrete` (або на скороченні {{cssxref("transition")}}), щоб увімкнути дискретні переходи на цих двох властивостях, які усталено не піддаються анімуванню.
```

2024-01-13 20:12 UTC, AdriandeCita commented on files/uk/web/html/element/dialog/index.md
> +- Псевдоелемент CSS {{cssxref('::backdrop')}} може використовуватися для оформлення задника модального діалогу, який виводиться під елементом `<dialog>`, коли цей діалог виводиться за допомогою метод
Нерухомий - це не зовсім те. Думаю, ніякого обмеження на анімації в основному вмісті сторінки насправді немає
```suggestion
- Псевдоелемент CSS {{cssxref('::backdrop')}} може використовуватися для оформлення задника модального діалогу, який виводиться під елементом `<dialog>`, коли цей діалог виводиться за допомогою метода {{domxref("HTMLDialogElement.showModal()")}}. Наприклад, цей елемент можна використовувати для затемнення інертного вмісту за модальним діалогом.
```

2024-01-13 20:15 UTC, AdriandeCita commented on files/uk/web/html/element/dialog/index.md
> +### Діалог лише з HTML
```suggestion
### Діалог, використовуючи лише HTML
```

2024-01-13 20:23 UTC, AdriandeCita commented on files/uk/web/html/element/dialog/index.md
> +- Шляхом подавання форми всередині діалогу за допомогою методу `dialog` (як у прикладі [діалогу лише з HTML](#dialoh-lyshe-z-html)).
```suggestion
- Шляхом подавання форми всередині діалогу за допомогою методу `dialog` (як у прикладі [діалогу, використовуючи лише HTML](#dialoh-vykorystovuiuchy-lyshe-html)).
```

2024-01-13 20:24 UTC, AdriandeCita commented on files/uk/web/html/element/dialog/index.md
> +- By calling the {{domxref("HTMLDialogElement.close()")}} method (as seen in the [modal example](#creating_a_modal_dialog)).
```suggestion
```

2024-01-13 20:30 UTC, AdriandeCita commented on files/uk/web/html/element/dialog/index.md
> +> **Примітка:** При анімуванні за допомогою [Переходів CSS](/uk/docs/Web/CSS/CSS_transitions), для ввімкнення логіки, описаної вище, необхідно задати [`transition-behavior: allow-discrete`](/uk/docs/
переклав `an`, бо трохи не в'яжеться
```suggestion
> **Примітка:** При анімуванні за допомогою [Переходів CSS](/uk/docs/Web/CSS/CSS_transitions), для ввімкнення логіки, описаної вище, необхідно задати [`transition-behavior: allow-discrete`](/uk/docs/Web/CSS/transition-behavior). Ця поведінка усталено доступна при анімуванні за допомогою [Анімацій CSS](/uk/docs/Web/CSS/CSS_animations); іншого еквівалентного кроку не потрібно.
```

2024-01-13 20:30 UTC, AdriandeCita commented on files/uk/web/html/element/dialog/index.md
> +Коли виводиться модальний діалог, він з'являється поверх усіх інших діалогів, що вже виведені. Все, що знаходиться поза цим модальним діалогом, стає нерухомим, а взаємодія поза діалогом блокується. З
```suggestion
Коли виводиться модальний діалог, він з'являється поверх усіх інших діалогів, що вже виведені. Все, що знаходиться поза цим модальним діалогом, стає інертним, а взаємодія поза діалогом блокується. Зверніть увагу, що коли діалог відкритий, то, за винятком самого діалогу, взаємодія з документом неможлива; кнопка "Показати діалог" здебільшого прихована майже непрозорим задником діалогу і є нерухомою.
```

2024-01-13 21:06 UTC, AdriandeCita commented on uk_spelling_additions.txt
> +Байненса
```suggestion
```

2024-01-13 21:07 UTC, AdriandeCita requested changes
декілька зауважень

2024-01-14 08:51 UTC, undead404 commented on files/uk/web/html/element/dialog/index.md
> +### Діалог лише з HTML
```suggestion
### Діалог з використанням лише HTML
```
Може, так?

2024-01-14 08:52 UTC, undead404 commented on files/uk/web/html/element/dialog/index.md
> +- Шляхом подавання форми всередині діалогу за допомогою методу `dialog` (як у прикладі [діалогу лише з HTML](#dialoh-lyshe-z-html)).
```suggestion
- Шляхом подавання форми всередині діалогу за допомогою методу `dialog` (як у прикладі [діалогу з використанням лише HTML](#dialoh-z-vykorystanniam-lyshe-html)).
```

2024-02-15 13:14 UTC, undead404 reviewed
Still relevant?

2024-07-19 13:42 UTC, undead404 reviewed
Relevant?

2024-08-10 15:48 UTC, undead404 commented on files/uk/web/javascript/reference/global_objects/array/index.md
> +> [!NOTE]
```suggestion
> [!NOTE] 
```

2024-08-10 16:21 UTC, undead404 reviewed
Relevant?

2024-08-11 07:24 UTC, undead404 commented on files/uk/web/javascript/reference/global_objects/array/index.md
> +> [!NOTE]
```suggestion
> [!NOTE]
```

2024-08-16 07:43 UTC, kant2002 commented on files/uk/web/html/element/dialog/index.md
> +Кнопка "Скасувати" має атрибут [`formmethod="dialog"`](/uk/docs/Web/HTML/Element/input/submit#formmethod), який відкидає усталений метод {{HTMLElement("form")}} {{HTTPMethod("GET")}}. Коли метод форм
```suggestion
Кнопка "Скасувати" має атрибут [`formmethod="dialog"`](/uk/docs/Web/HTML/Element/input/submit#formmethod), який перевизначає усталений метод {{HTTPMethod("GET")}} для тега {{HTMLElement("form")}}. Коли метод форми – [`dialog`](#prymitky-shchodo-zastosuvannia), стан форми зберігається, але не подається, а діалог закривається.
```

2024-08-16 07:43 UTC, kant2002 commented on files/uk/web/html/element/dialog/index.md
> +Судячи з результату, неможливо закрити діалог за допомогою кнопки _Закрити – нормально_. Проте його можна закрити, якщо обійти валідацію форми за допомогою атрибута `formnovalidate` на кнопці _Скасув
```suggestion
Судячи з виводу, неможливо закрити діалог за допомогою кнопки _Закрити – нормально_. Проте його можна закрити, якщо обійти валідацію форми за допомогою атрибута `formnovalidate` на кнопці _Скасувати_. Програмно – `dialog.close()` також закриває такий діалог.
```

2024-08-16 07:43 UTC, kant2002 commented on files/uk/web/html/element/dialog/index.md
> +HTML вміщає елемент `<dialog>`, плюс кнопку для показу діалогу. Крім того, елемент `<dialog>` містить іншу кнопку для закриття себе.
```suggestion
HTML містить елемент `<dialog>`, плюс кнопку для показу діалогу. Крім того, елемент `<dialog>` містить іншу кнопку для закриття себе.
```

2024-08-16 07:43 UTC, kant2002 commented on files/uk/web/html/element/dialog/index.md
> +JavaScript додає до кнопок показу та закриття слухачі подій, змушуючи їх показувати та закривати `<dialog>`, коли по них клацають:
```suggestion
JavaScript додає до кнопок показу та закриття слухачі подій, змушуючи кнопки показувати та закривати `<dialog>`, коли по них клацають:
```

2024-08-16 13:11 UTC, undead404 commented on files/uk/web/html/element/dialog/index.md
> +- Не слід додавати до елемента `<dialog>` властивість `tabindex`, адже не очікується, що цей елемент може отримати фокус. Вміст діалогу, включно зі вміщеною в ньому кнопкою закриття, може отримати фо
```suggestion
- Не слід додавати до елемента `<dialog>` властивість `tabindex`, адже не очікується, що цей елемент може отримати фокус. Вміст діалогу, включно із кнопкою закриття, яка знаходиться всередині діалогу, може отримати фокус та бути інтерактивним.
```

2024-08-16 13:11 UTC, undead404 commented on files/uk/web/html/element/dialog/index.md
> +Усталено діалог, закликаний методом `showModal()`, може бути закритий шляхом натискання клавіші <kbd>Esc</kbd>. Немодальний діалог усталено не закривається клавішею <kbd>Esc</kbd>, і залежно від того
```suggestion
Усталено, діалог, закликаний методом `showModal()`, може бути закритий шляхом натискання клавіші <kbd>Esc</kbd>. Немодальний діалог усталено не закривається клавішею <kbd>Esc</kbd>, і залежно від того, що він собою являю, це може бути небажаним. Клавіатурні користувачі розраховують на те, що клавіша <kbd>Esc</kbd> закриває модальні діалоги; переконайтеся, що ця поведінка реалізована та підтримується. Якщо відкрито кілька модальних діалогів, то натискання клавіші <kbd>Esc</kbd> має закривати лише останній показаний діалог. Коли використовується `<dialog>`, ця логіка надається браузером.
```
В першому випадку кома – це виділення дієприкметникового звороту, а в другому проблема в https://onlinecorrector.com.ua/uk/%D0%B1%D1%83%D1%82%D0%B8-%D1%8F%D0%B2%D0%BB%D1%8F%D1%82%D0%B8-%D1%81%D0%BE%D0%B1%D0%BE%D1%8E/

2024-08-16 13:11 UTC, undead404 commented on files/uk/web/html/element/dialog/index.md
> +### Обробка поверненого значення з діалогу
Всюди перекладаємо "returned" як "повернений". І дієприкметники як такі це зло

2024-08-16 13:11 UTC, undead404 commented on files/uk/web/html/element/dialog/index.md
> +// Кнопка "Скасувати" закриває діалог без подання, у зв'язку з [formmethod="dialog"], запускаючи подію закриття.
```suggestion
// Кнопка "Скасувати", оскільки є [formmethod="dialog"], закриває діалог без подання, запускаючи подію закриття.
```

2024-08-16 13:11 UTC, undead404 commented on files/uk/web/html/element/dialog/index.md
> +Судячи з результату, неможливо закрити діалог за допомогою кнопки _Закрити – нормально_. Проте його можна закрити, якщо обійти валідацію форми за допомогою атрибута `formnovalidate` на кнопці _Скасув
```suggestion
Судячи з прикладу, неможливо закрити діалог за допомогою кнопки _Закрити – нормально_. Проте його можна закрити, якщо обійти валідацію форми за допомогою атрибута `formnovalidate` на кнопці _Скасувати_. Програмно – `dialog.close()` також закриває такий діалог.
```
Тут оце малося на увазі. Може, так краще

2024-08-16 13:11 UTC, undead404 commented on files/uk/web/html/element/dialog/index.md
> +JavaScript додає до кнопок показу та закриття слухачі подій, змушуючи їх показувати та закривати `<dialog>`, коли по них клацають:
```suggestion
JavaScript додає до кнопок показу та закриття слухачі подій, змушуючи ці кнопки показувати та закривати `<dialog>`, коли по них клацають:
```
А давай зі словом "ці"

2024-12-25 21:19 UTC, undead404 commented on files/uk/web/html/element/dialog/index.md
> +      ? "Немає значення повернення."
```suggestion
      ? "Немає поверненого значення."
```
"Повертаємий" – це дієприкметник, звучить неприємно, на мій смак

2024-12-25 21:19 UTC, undead404 commented on files/uk/web/html/element/dialog/index.md
> +      : `Значення повернення: ${favDialog.returnValue}.`; // Необхідно перевіряти на "default", а не на порожній рядок
```suggestion
      : `Повернене значення: ${favDialog.returnValue}.`; // Необхідно перевіряти на "default", а не на порожній рядок
```

2024-12-26 07:11 UTC, kant2002 commented on files/uk/web/html/element/dialog/index.md
> +JavaScript додає до кнопок показу та закриття слухачі подій, змушуючи їх показувати та закривати `<dialog>`, коли по них клацають:
Я за. Так краще

2024-12-26 07:13 UTC, kant2002 commented on files/uk/web/html/element/dialog/index.md
> +- Не слід додавати до елемента `<dialog>` властивість `tabindex`, адже не очікується, що цей елемент може отримати фокус. Вміст діалогу, включно зі вміщеною в ньому кнопкою закриття, може отримати фо
Так. Наче норм. Великих преференцій не маю. Так точно краще ніж було

2024-12-26 07:14 UTC, kant2002 commented on files/uk/web/html/element/dialog/index.md
> +Усталено діалог, закликаний методом `showModal()`, може бути закритий шляхом натискання клавіші <kbd>Esc</kbd>. Немодальний діалог усталено не закривається клавішею <kbd>Esc</kbd>, і залежно від того
Правила граматики це точно не моє :)) дякую

2024-12-27 16:27 UTC, AdriandeCita approved these changes

2024-12-27 16:32 UTC, merged