translation(HTML): web/html/constraint_validation
webdoky/content pull request #1766
Opened 2023-05-18 14:04 UTC by undead404

Оригінальний вміст: [Constraint validation@MDN](https://developer.mozilla.org/en-us/docs/Web/HTML/Constraint_validation), [сирці Constraint validation@GitHub](https://github.com/mdn/content/blob/main/files/en-us/web/html/constraint_validation/index.md)

2023-07-06 10:39 UTC, undead404 commented
Оновлення – нікчемне

2024-01-13 20:58 UTC, AdriandeCita commented on files/uk/web/html/constraint_validation/index.md
> +- Шляхом виклику методу `checkValidity()` або `reportValidity()` на пов'язаному з DOM інтерфейсі ([`HTMLInputElement`](/uk/docs/Web/API/HTMLInputElement), [`HTMLSelectElement`](/uk/docs/Web/API/HTMLS
`...method of a form-associated DOM interface`
```suggestion
- Шляхом виклику методу `checkValidity()` або `reportValidity()` на пов'язаному з формою інтерфейсі DOM ([`HTMLInputElement`](/uk/docs/Web/API/HTMLInputElement), [`HTMLSelectElement`](/uk/docs/Web/API/HTMLSelectElement), [`HTMLButtonElement`](/uk/docs/Web/API/HTMLButtonElement), [`HTMLOutputElement`](/uk/docs/Web/API/HTMLOutputElement) або [`HTMLTextAreaElement`](/uk/docs/Web/API/HTMLTextAreaElement)), що обчислює обмеження лише на відповідному елементі, даючи сценарію змогу отримати цю інформацію. Метод `checkValidity()` повертає булеве значення, що вказує, чи пройшло значення елемента його обмеження. (Це, як правило, робиться користувацьким агентом при визначенні того, який з псевдокласів CSS, {{Cssxref(":valid")}} або {{Cssxref(":invalid")}}, застосовується.) На противагу йому, метод `reportValidity()` повідомляє користувачу про будь-які порушення обмежень.
```

2024-01-13 21:00 UTC, AdriandeCita commented on files/uk/web/html/constraint_validation/index.md
> +Метод `checkValidity()` викликається _статично_ при валідації обмежень, а метод `reportValidity()` або подання форми викликаються _інтерактивно_ при валідації обмежень.
```suggestion
Виклик `checkValidity()` називається _статичною_ валідацією обмежень, а виклик `reportValidity()` або подання форми називається _інтерактивною_ валідацією обмежень.
```

2024-01-13 21:01 UTC, AdriandeCita commented on files/uk/web/html/constraint_validation/index.md
> +In addition to the `type` attribute described above, the following attributes are used to describe basic constraints:
```suggestion
```

2024-01-13 21:01 UTC, AdriandeCita commented on files/uk/web/html/constraint_validation/index.md
> +
```suggestion
```

2024-01-13 21:06 UTC, AdriandeCita commented on files/uk/web/html/constraint_validation/index.md
> +  - {{HTMLElement("fieldset")}}. Note: Setting a custom validity message on fieldset elements will not prevent form submission in most browsers.
```suggestion
```

2024-01-13 21:06 UTC, AdriandeCita requested changes
декілька зауважень

2024-02-15 13:15 UTC, undead404 reviewed
Still relevant?

2024-06-19 09:09 UTC, undead404 commented
Still relevant?

2024-06-19 09:10 UTC, undead404 reviewed
Still relevant?

2024-07-19 13:42 UTC, undead404 reviewed
Relevant?

2024-08-10 15:50 UTC, undead404 reviewed
Relevant?

2024-08-23 13:08 UTC, merged