Translation/web html attributes required
webdoky/content pull request #1781
Opened 2023-05-21 10:12 UTC by undead404

Оригінальний вміст: [HTML attribute: required@MDN](https://developer.mozilla.org/en-us/docs/Web/HTML/Attributes/required), [сирці HTML attribute: required@GitHub](https://github.com/mdn/content/blob/main/files/en-us/web/html/attributes/required/index.md)

2023-05-26 08:54 UTC, AdriandeCita commented on files/uk/web/html/attributes/required/index.md
> +При доданні атрибута `required` слід надавати видиме позначення поруч з контрольним елементом, що сповіщатиме користувачів про те, що {{HTMLElement("input")}}, {{HTMLElement("select")}} або {{HTMLEle
```suggestion
При доданні атрибута `required` слід надавати видиме позначення поруч з контрольним елементом, що сповіщатиме користувачів про те, що {{HTMLElement("input")}}, {{HTMLElement("select")}} або {{HTMLElement("textarea")}} є обов'язковим. На додачу до цього, слід використовувати псевдоклас {{cssxref(':required')}}, оформлюючи елементи так, аби було видно, що вони обов'язкові. Це покращує зручність для зрячих користувачів. Допоміжні технології повинні сповіщати користувачів, що контрольний елемент є обов'язковим, на основі атрибута required, але додавання `aria-required="true"` також не завадить, якщо комбінація браузера та читача з екрана ще не підтримує `required`.
```

2023-05-26 09:01 UTC, AdriandeCita commented on files/uk/web/html/attributes/required/index.md
> +Якщо елемент є обов'язковим, а його значення — порожній рядок, то елемент страждає на порушення {{domxref('ValidityState.valueMissing','valueMissing')}} і буде відповідати псевдокласу {{cssxref(':inv
https://developer.mozilla.org/en-US/docs/Web/API/ValidityState/valueMissing - це властивість, яка позначає певний стан валідації. "Страждає на порушення [...]" звучить дивно в цьому контексті, пропоную змінити:
```suggestion
Якщо елемент є обов'язковим, а його значення — порожній рядок, то елемент переживає стан {{domxref('ValidityState.valueMissing','valueMissing')}} і буде відповідати псевдокласу {{cssxref(':invalid')}}.
```

2023-05-26 09:02 UTC, AdriandeCita requested changes
Пара зауважень

2023-05-26 09:03 UTC, undead404 commented
Прийняв пропозиції

2023-05-30 12:00 UTC, ibulik approved these changes

2023-07-06 14:21 UTC, AdriandeCita approved these changes

2023-07-06 14:21 UTC, merged