translation(JS): web/javascript/reference/regular_expressions/character_class
webdoky/content pull request #1809
Opened 2023-06-02 12:13 UTC by undead404

Оригінальний вміст: [Character class: [...], [^...]@MDN](https://developer.mozilla.org/en-us/docs/Web/JavaScript/Reference/Regular_expressions/Character_class), [сирці Character class: [...], [^...]@GitHub](https://github.com/mdn/content/blob/main/files/en-us/web/javascript/reference/regular_expressions/character_class/index.md)

2023-11-08 09:33 UTC, KlashReik requested changes
Декілька зауважень

2023-11-08 09:33 UTC, KlashReik commented on files/uk/web/javascript/reference/regular_expressions/character_class/index.md
> +За присутності позначки `v` перетин виражається за допомогою `&&`, а різниця — за допомогою `--`. Відсутність обох цих комбінацій позначає об'єднання. Два операнди `&&` або `--` можуть бути символами
```suggestion
За присутності позначки `v` перетин виражається за допомогою `&&`, а різниця — за допомогою `--`. Відсутність обох цих комбінацій позначає об'єднання. Два операнди `&&` або `--` можуть бути символами, екрануваннями символів, екрануванням класу символів або навіть іншим класом символів. Наприклад, щоб виразити "символ літери, який не є підкресленням", можна використовувати `[\w--_]`. Не можна змішувати оператори на одному рівні. Наприклад, `[\w&&[A-z]--_]` є синтаксичною помилкою. Однак, оскільки можна вкладати класи символів один в одного, можна явно написати `[\w&&[[A-z]--_]]` або `[[\w&&[A-z]]--_]` (обидва ці записи означають `[A-Za-z]`). Аналогічно, `[AB--C]` є недійсним, і необхідно написати `[A[B--C]]` (що означає просто `[AB]`).
```

2023-11-08 09:33 UTC, KlashReik commented on files/uk/web/javascript/reference/regular_expressions/character_class/index.md
> +Доповняльні класи символів `[^...]` взагалі не можуть збігатися з рядками, довшими за один символ. Наприклад, `[\q{ab|c}]` є дійсним і дає збіг з рядком `"ab"`, але `[^\q{ab|c}]` є недійсним, оскільк
```suggestion
Доповняльні класи символів `[^...]` взагалі не можуть збігатися з рядками, довшими за один символ. Наприклад, `[\q{ab|c}]` є дійсним і дає збіг з рядком `"ab"`, але `[^\q{ab|c}]` є недійсним, оскільки неясно, скільки символів потрібно спожити. Перевірка виконується шляхом перевірки того, чи всі `\q` містять один символ, і чи всі `\p` вказують властивості символів — для об'єднань всі операнди повинні бути чисто символами; для перетинів, принаймні один операнд повинен бути чисто символом; для віднімання, лівий операнд повинен бути чисто символом. Перевірка є синтаксичною без перегляду фактичного набору символів, який вказується, що означає, що хоча `/[^\q{ab|c}--\q{ab}]/v` еквівалентний `/[^c]/v`, він все ще відхиляється.
```

2023-11-08 09:33 UTC, KlashReik commented on files/uk/web/javascript/reference/regular_expressions/character_class/index.md
> +// 𑜹 is U+11739 AHOM DIGIT NINE (ахомська цифра дев'ять)
```suggestion
// 𑜹 – це U+11739 AHOM DIGIT NINE (ахомська цифра дев'ять)
```

2023-11-08 09:33 UTC, KlashReik commented on files/uk/web/javascript/reference/regular_expressions/character_class/index.md
> +Ситуація, в якій `\q{}` найбільш корисний, – це різниця та перетин. Раніше таке було можливо за допомогою [кількох визирань](/uk/docs/Web/JavaScript/Reference/Regular_expressions/Lookahead_assertion#
```suggestion
Ситуації, в яких `\q{}` найбільш корисний, – це різниця та перетин. Раніше таке було можливо за допомогою [кількох визирань](/uk/docs/Web/JavaScript/Reference/Regular_expressions/Lookahead_assertion#riznytsia-ta-peretyn-u-paternakh). Функція нижче шукає прапори, які не є американським, китайським, російським, британським та французьким.
```
антибаза люта з цим "російський"

2023-11-08 12:22 UTC, undead404 commented on files/uk/web/javascript/reference/regular_expressions/character_class/index.md
> +**Клас символів** дає збіг з будь-яким символом, присутнім або відсутнім в заданому наборі символів. Коли ввімкнена позначка [`v`](/uk/docs/Web/JavaScript/Reference/Global_Objects/RegExp/unicodeSets)
Типу "прапорець" замість "позначки"? Регулярно промахуюсь і так і пишу. Не певен, що це так працює в українській

2023-11-08 12:24 UTC, undead404 commented on files/uk/web/javascript/reference/regular_expressions/character_class/index.md
> +За присутності позначки `v` перетин виражається за допомогою `&&`, а різниця — за допомогою `--`. Відсутність обох цих комбінацій позначає об'єднання. Два операнди `&&` або `--` можуть бути символами
Тоді там має бути "літери або цифри"...

2023-11-08 12:24 UTC, undead404 commented on files/uk/web/javascript/reference/regular_expressions/character_class/index.md
> +Ситуація, в якій `\q{}` найбільш корисний, – це різниця та перетин. Раніше таке було можливо за допомогою [кількох визирань](/uk/docs/Web/JavaScript/Reference/Regular_expressions/Lookahead_assertion#
То, може, заміни українським, та й усе

2023-11-10 08:23 UTC, KlashReik commented on files/uk/web/javascript/reference/regular_expressions/character_class/index.md
> +  - : Буквальний рядок.
Мене це "бувальний" лякає, хоч бери і просто залишай "рядок" чи, може, використати "символьний рядок".

2023-11-10 08:25 UTC, KlashReik commented on files/uk/web/javascript/reference/regular_expressions/character_class/index.md
> +За присутності позначки `v` перетин виражається за допомогою `&&`, а різниця — за допомогою `--`. Відсутність обох цих комбінацій позначає об'єднання. Два операнди `&&` або `--` можуть бути символами
```suggestion
За присутності позначки `v` перетин виражається за допомогою `&&`, а різниця — за допомогою `--`. Відсутність обох цих комбінацій позначає об'єднання. Два операнди `&&` або `--` можуть бути символами, екрануваннями символів, екрануванням класу символів або навіть іншим класом символів. Наприклад, щоб виразити "символ літери або цифри який не є підкресленням", можна використовувати `[\w--_]`. Не можна змішувати оператори на одному рівні. Наприклад, `[\w&&[A-z]--_]` є синтаксичною помилкою. Однак, оскільки можна вкладати класи символів один в одного, можна явно написати `[\w&&[[A-z]--_]]` або `[[\w&&[A-z]]--_]` (обидва ці записи означають `[A-Za-z]`). Аналогічно, `[AB--C]` є недійсним, і необхідно написати `[A[B--C]]` (що означає просто `[AB]`).
```

2023-11-10 08:28 UTC, KlashReik commented on files/uk/web/javascript/reference/regular_expressions/character_class/index.md
> +**Клас символів** дає збіг з будь-яким символом, присутнім або відсутнім в заданому наборі символів. Коли ввімкнена позначка [`v`](/uk/docs/Web/JavaScript/Reference/Global_Objects/RegExp/unicodeSets)
Прапорець у контексті регулярних виразів просто більш очікувано почути, але "позначка" також добре описує свій зміст :)

2023-11-10 08:37 UTC, undead404 commented on files/uk/web/javascript/reference/regular_expressions/character_class/index.md
> +  - : Буквальний рядок.
А може, взагалі "рядковий рядок"?)

Тут немає громіздкого контексту, можна додати слів, щось виду "Рядок, представлений буквально".

2023-11-10 08:41 UTC, undead404 commented on files/uk/web/javascript/reference/regular_expressions/character_class/index.md
> +За присутності позначки `v` перетин виражається за допомогою `&&`, а різниця — за допомогою `--`. Відсутність обох цих комбінацій позначає об'єднання. Два операнди `&&` або `--` можуть бути символами
```suggestion
За присутності позначки `v` перетин виражається за допомогою `&&`, а різниця — за допомогою `--`. Відсутність обох цих комбінацій позначає об'єднання. Два операнди `&&` або `--` можуть бути символами, екрануваннями символів, екрануванням класу символів або навіть іншим класом символів. Наприклад, щоб виразити "символ літери або цифри, але не підкреслення", можна використовувати `[\w--_]`. Не можна змішувати оператори на одному рівні. Наприклад, `[\w&&[A-z]--_]` є синтаксичною помилкою. Однак, оскільки можна вкладати класи символів один в одного, можна явно написати `[\w&&[[A-z]--_]]` або `[[\w&&[A-z]]--_]` (обидва ці записи означають `[A-Za-z]`). Аналогічно, `[AB--C]` є недійсним, і необхідно написати `[A[B--C]]` (що означає просто `[AB]`).
```
Тоді давай так

2023-11-10 08:44 UTC, KlashReik commented on files/uk/web/javascript/reference/regular_expressions/character_class/index.md
> +  - : Буквальний рядок.
Не знаю, хай ще хтось з хлопців скаже свою думку

2023-11-10 10:26 UTC, AdriandeCita commented on files/uk/web/javascript/reference/regular_expressions/character_class/index.md
> +  - : Буквальний рядок.
Ми не можемо тут використати "шаблонний рядок" чи "рядковий літерал". "Рядковий рядок" також так собі підходить.
Справа в тім, що тут акцент не стільки на тому, що передається, скільки на тому, як воно інтерпретується. А інтрепретується воно як буквально рядок символів. Тому або "Буквальний рядок", або я б краще вжив "Рядок, буквально".

"Рядок, представлений буквально" мені теж здається більше натякає на його вміст, а не на результат інтерпретації

2023-11-10 10:26 UTC, AdriandeCita commented on files/uk/web/javascript/reference/regular_expressions/character_class/index.md
> +  - : Буквальний рядок.
```suggestion
  - : Рядок, буквально.
```

2023-11-10 11:01 UTC, merged