translation(CSS): web/css/visual_formatting_model
webdoky/content pull request #1811
Opened 2023-06-07 12:45 UTC by undead404

Оригінальний вміст: [Visual formatting model@MDN](https://developer.mozilla.org/en-us/docs/Web/CSS/Visual_formatting_model), [сирці Visual formatting model@GitHub](https://github.com/mdn/content/blob/main/files/en-us/web/css/visual_formatting_model/index.md)

Залежить від:
* https://github.com/webdoky/css-examples/pull/5

2024-01-13 19:29 UTC, AdriandeCita commented on files/uk/web/css/visual_formatting_model/index.md
> +У пливній моделі рамка спершу розміщається згідно зі звичайним потоком, а потім виймається з потоку та позиціонується, зазвичай до лівого або правого краю. Вміст може розтікатися по краю пливуна.
```suggestion
У пливній моделі рамка спершу розміщається згідно зі звичайним потоком, а потім виймається з потоку та позиціонується, зазвичай до лівого або правого краю. Вміст може розтікатися вздовж краю пливуна.
```

2024-01-13 19:46 UTC, AdriandeCita commented on files/uk/web/css/visual_formatting_model/index.md
> +**Блоковий контейнер** або вміщає лише рамки рядкового рівня, що беруть участь в рядковому форматувальному контексті, або лише рамки блокового рівня, що беруть участь у блоковому форматувальному конт
```suggestion
**Блоковий контейнер** або вміщає лише рамки рядкового рівня, що беруть участь в рядковому форматувальному контексті, або лише рамки блокового рівня, що беруть участь у блоковому форматувальному контексті. Через це спостерігається поведінка, описана вище, коли вводяться анонімні рамки, аби пересвідчитися, що всі елементи можуть брати участь у блоковому або рядковому форматувальному контексті. Елемент є блоковим контейнером лише тоді, коли вміщає рамки блокового або рядкового рівня.
```

2024-01-13 19:47 UTC, AdriandeCita commented on files/uk/web/css/visual_formatting_model/index.md
> +Наступний приклад демонструє дію `display: flow-root`. Рамка з чорним тлом ніби обгортає пливний елемент і текст. Якщо видалити з редагованого CSS `display: flow-root`, пливун виступатиме знизу рамки
омг, та це ж clearfix :grinning:

2024-01-13 20:07 UTC, AdriandeCita commented on files/uk/web/css/visual_formatting_model/index.md
> +Проте внутрішній тип виведення може бути чимось штибу `grid` або `flex`, у випадку чого безпосередні дочірні елементи виводитимуться як сітка або як гнучкі елементи. У такому випадку про елемент кажу
Не часто чую "з багатьож боків". А ще "з боків" частіше вживається в контексті певної колізії чи суперечності (з одного боку..., а з іншого ...), тут не зовсім той контекст
```suggestion
Проте внутрішній тип виведення може бути чимось штибу `grid` або `flex`, у випадку чого безпосередні дочірні елементи виводитимуться як сітка або як гнучкі елементи. У такому випадку про елемент кажуть, що він утворює сітковий або гнучкий [форматувальний контекст](/uk/docs/Web/CSS/CSS_flow_layout/Introduction_to_formatting_contexts). Багато в чому це подібно до блокового форматувального контексту, але дочірні елементи поводяться як гнучкі або сіткові елементи, а не елементи у звичайному потоці.
```

2024-01-13 20:07 UTC, AdriandeCita commented on files/uk/web/css/visual_formatting_model/index.md
> +### Пливуни
Навіває асоціацію зі старим колодязем. Не знаю, поки най буде, поведінка пливних елементів дещо нагадує властивості пливунів, хоча я б сам обирав якийсь інший варіант

2024-01-13 20:07 UTC, AdriandeCita requested changes
Пара зауважень

2024-01-14 08:46 UTC, undead404 commented on files/uk/web/css/visual_formatting_model/index.md
> +### Пливуни
Ще не пізно щось підкинути...

2024-01-14 08:47 UTC, undead404 commented on files/uk/web/css/visual_formatting_model/index.md
> +Наступний приклад демонструє дію `display: flow-root`. Рамка з чорним тлом ніби обгортає пливний елемент і текст. Якщо видалити з редагованого CSS `display: flow-root`, пливун виступатиме знизу рамки
Я тільки побіжно це зустрів на початку кар'єри :-)

2024-02-15 13:15 UTC, undead404 reviewed
Still relevant?

2024-07-19 13:42 UTC, undead404 reviewed
Relevant?

2024-08-10 16:11 UTC, closed without merging

2024-08-10 16:12 UTC, undead404 commented
Перестворив https://github.com/webdoky/content/pull/3295