translation(HTML): web/html/global_attributes/enterkeyhint
webdoky/content pull request #1828
Opened 2023-06-14 14:27 UTC by undead404

Оригінальний вміст: [enterkeyhint@MDN](https://developer.mozilla.org/en-us/docs/Web/HTML/Global_attributes/enterkeyhint), [сирці enterkeyhint@GitHub](https://github.com/mdn/content/blob/main/files/en-us/web/html/global_attributes/enterkeyhint/index.md)

Залежить від:
* https://github.com/webdoky/interactive-examples/pull/110

2023-11-16 18:57 UTC, KlashReik requested changes
Зауваження

2023-11-16 18:57 UTC, KlashReik commented on files/uk/web/html/global_attributes/enterkeyhint/index.md
> +        Зазвичай означає, що користувач буде переведений до цілі тексту, котрий надруковано.
```suggestion
        Зазвичай означає, що користувач буде переведений до цільового тексту, котрий надруковано.
```
Якщо я правильно розумію зміст

2023-11-17 06:10 UTC, undead404 commented on files/uk/web/html/global_attributes/enterkeyhint/index.md
> +        Зазвичай означає, що користувач буде переведений до цілі тексту, котрий надруковано.
Ні, ти зрозумів неправильно, але дякую, що підсвітив неясне місце.

```suggestion
        Зазвичай означає, що користувач буде переведений до місця призначення тексту, котрий надруковано.
```
Тут мається на увазі, що в поле вводиться якась точка призначення, а кнопка стає "Відкрити"

2023-11-20 08:47 UTC, KlashReik commented on files/uk/web/html/global_attributes/enterkeyhint/index.md
> +        Зазвичай означає, що користувач буде переведений до цілі тексту, котрий надруковано.
А, зрозумів, тоді давай твій варіант візьмемо

2023-11-20 08:48 UTC, KlashReik approved these changes

2023-11-20 08:54 UTC, merged