update(HTML): web/html/element/input
webdoky/content pull request #1912
Opened 2023-07-19 12:05 UTC by undead404

Оригінальний вміст: [&lt;input>: Елемент введення (форм)@MDN](https://developer.mozilla.org/en-us/docs/Web/HTML/Element/input), [сирці &lt;input>: Елемент введення (форм)@GitHub](https://github.com/mdn/content/blob/main/files/en-us/web/html/element/input/index.md)

Нові зміни:
- [mdn/content@07f0cf4](https://github.com/mdn/content/commit/07f0cf4375aaa02e1071d8bd0e8518db7609b7a9)
- [mdn/content@acfe8c9](https://github.com/mdn/content/commit/acfe8c9f1f4145f77653a2bc64a9744b001358dc)

2023-07-20 12:27 UTC, Aenqau requested changes

2023-07-20 12:27 UTC, Aenqau commented on files/uk/web/html/element/input/index.md
> +      "Імена користувачів можуть містити лише великі та малі літери. Спробуйте ще!",
А нащо тут кома?

2023-07-20 12:31 UTC, undead404 commented on files/uk/web/html/element/input/index.md
> +      "Імена користувачів можуть містити лише великі та малі літери. Спробуйте ще!",
Якщо тебе цікавить концептуально, то це щоб при потенційній появі додаткових параметрів у Git не лізли зайві зміни. А тут – просто Prettier оновився до третьої версії

2023-07-21 07:58 UTC, undead404 commented
Оновлення  – нікчемне

2023-07-21 08:41 UTC, Aenqau approved these changes

2023-07-21 08:41 UTC, Aenqau commented on files/uk/web/html/element/input/index.md
> +      "Імена користувачів можуть містити лише великі та малі літери. Спробуйте ще!",
Переконав, дякую

2023-07-21 08:41 UTC, merged