update(HTML): web/html/element/a
webdoky/content pull request #1917
Opened 2023-07-19 12:31 UTC by undead404

Оригінальний вміст: [&lt;a>: Якірний елемент@MDN](https://developer.mozilla.org/en-us/docs/Web/HTML/Element/a), [сирці &lt;a>: Якірний елемент@GitHub](https://github.com/mdn/content/blob/main/files/en-us/web/html/element/a/index.md)

Нові зміни:
- [mdn/content@07f0cf4](https://github.com/mdn/content/commit/07f0cf4375aaa02e1071d8bd0e8518db7609b7a9)
- [mdn/content@acfe8c9](https://github.com/mdn/content/commit/acfe8c9f1f4145f77653a2bc64a9744b001358dc)

2023-07-20 13:41 UTC, Aenqau approved these changes

2023-07-20 13:41 UTC, Aenqau commented on files/uk/web/html/element/a/index.md
> +  draw(event.offsetX, event.offsetY),
```suggestion
  draw(event.offsetX, event.offsetY)
```

2023-07-20 13:41 UTC, Aenqau commented on files/uk/web/html/element/a/index.md
> +    (event) => (event.target.href = canvas.toDataURL()),
```suggestion
    (event) => (event.target.href = canvas.toDataURL())
```

2023-07-20 13:42 UTC, Aenqau requested changes
Коми

2023-07-20 16:57 UTC, undead404 commented
Давай не будемо цього вносити, бо такі зміни вже прийшли на ввесь MDN, а я б не хотів у таких дрібницях з ними розходитись

2023-07-21 08:41 UTC, Aenqau approved these changes

2023-07-21 08:41 UTC, merged