translation(CSS): web/css/css_pseudo-elements
webdoky/content pull request #1973
Opened 2023-07-27 11:42 UTC by undead404

Оригінальний вміст: [CSS pseudo-elements@MDN](https://developer.mozilla.org/en-us/docs/Web/CSS/CSS_pseudo-elements), [сирці CSS pseudo-elements@GitHub](https://github.com/mdn/content/blob/main/files/en-us/web/css/css_pseudo-elements/index.md)

2024-01-06 22:29 UTC, AdriandeCita approved these changes

2024-01-06 22:31 UTC, AdriandeCita requested changes
Є свіжі зміни

2024-01-07 15:56 UTC, undead404 commented
Це помилка, всі зміни внесені

2024-01-13 17:46 UTC, AdriandeCita approved these changes

2024-01-13 17:47 UTC, merged