translation(JS): web/javascript/guide/using_classes
webdoky/content pull request #1996
Opened 2023-08-09 08:58 UTC by undead404

Оригінальний вміст: [Using classes@MDN](https://developer.mozilla.org/en-us/docs/Web/JavaScript/Guide/Using_classes), [сирці Using classes@GitHub](https://github.com/mdn/content/blob/main/files/en-us/web/javascript/guide/using_classes/index.md)

2023-11-17 10:25 UTC, KlashReik requested changes

2023-11-17 10:25 UTC, KlashReik commented on files/uk/web/javascript/guide/using_classes/index.md
> +Всередині конструктора класу значення `this` вказує на новостворений примірник. Чому можна присвоїти властивості, а також зчитати наявні (особливо методи – про що буде мова далі).
або

```suggestion
Всередині конструктора класу значення `this` вказує на новостворений примірник. Котрому можна присвоїти властивості, а також зчитати наявні (особливо методи – про що буде мова далі).
```

2023-11-17 10:25 UTC, KlashReik commented on files/uk/web/javascript/guide/using_classes/index.md
> +console.log(red.values[0]); // 0; Уже не 255, тому що значення H для щирого червоного – 0
```suggestion
console.log(red.values[0]); // 0; Уже не 255, тому що значення H для чистого червоного – 0
```

2023-11-17 10:25 UTC, KlashReik commented on files/uk/web/javascript/guide/using_classes/index.md
> +Цей посібник досі був прагматичним: ми зосередились на тому, _як_ можна використовувати класи, але є ще одне питання без відповіді: _навіщо_ використовувати класи? Відповідь: буває по-різному.
```suggestion
Цей посібник досі був прагматичним: ми зосередились на тому, _як_ можна використовувати класи, але є ще одне питання без відповіді: _навіщо_ використовувати класи? Відповідь: буває по-різному.
```

2023-11-17 10:25 UTC, KlashReik commented on files/uk/web/javascript/guide/using_classes/index.md
> +Проте нерідко важко описати успадкування чисто, щоб один клас міг успадковувати тільки один інший клас. Часто потрібна поведінка з декількох класів. У Java це робиться за допомогою інтерфейсів; в Jav
```suggestion
Проте нерідко важко описати успадкування чисто, щоб один клас міг успадковувати тільки один інший клас. Часто потрібна поведінка з декількох класів. У Java це робиться за допомогою інтерфейсів; в JavaScript це можна зробити за допомогою домішок. Але, врешті-решт, це все одно не дуже зручно.
```

Не вперше помічаю. Ми можемо якось за один раз пофіксити усі "врешті решт" на "врешті-решт"?

2023-11-18 10:46 UTC, undead404 commented on files/uk/web/javascript/guide/using_classes/index.md
> +Проте нерідко важко описати успадкування чисто, щоб один клас міг успадковувати тільки один інший клас. Часто потрібна поведінка з декількох класів. У Java це робиться за допомогою інтерфейсів; в Jav
Врешті-решт, можна написати правило для Markdownlint

2023-11-19 21:04 UTC, KlashReik approved these changes

2023-11-20 08:25 UTC, merged