translation(js): Web/JavaScript/Reference/Global_Objects/String/fontcolor
webdoky/content pull request #201
Opened 2022-01-16 14:30 UTC by AdriandeCita

Original content: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/fontcolor

2022-01-18 15:35 UTC, undead404 requested changes

2022-01-18 15:35 UTC, undead404 commented on files/uk/web/javascript/reference/global_objects/string/fontcolor/index.md
> +  - : Рядок, що містить вираження кольору через шістнадцятковий RGB-триплет, чи рядковий літерал. Перелік літералів для позначення імен кольорів наведений у [довіднику з кольорів CSS](/uk/docs/Web/CS
```suggestion
  - : Рядок, що містить вираження кольору через шістнадцятковий RGB-триплет чи рядковий літерал. Перелік літералів для позначення імен кольорів наведений у [довіднику з кольорів CSS](/uk/docs/Web/CSS/color_value).
```

2022-01-18 15:35 UTC, undead404 commented on files/uk/web/javascript/reference/global_objects/string/fontcolor/index.md
> +зелений=80, і блакитний=72, — тобто RGB-триплетом для лососевого кольору є рядок "`FA8072`".
Точно блакитний, а не синій?

2022-01-18 15:35 UTC, undead404 commented on files/uk/web/javascript/reference/global_objects/string/fontcolor/index.md
> +Наступний приклад використовує метод `fontcolor()` для зміни кольору рядка шляхом рядка з HTML-елементом `<font>`.
```suggestion
Наступний приклад використовує метод `fontcolor()` для зміни кольору тексту шляхом створення рядка з HTML-елементом `<font>`.
```

2022-01-23 16:35 UTC, AdriandeCita commented on files/uk/web/javascript/reference/global_objects/string/fontcolor/index.md
> +зелений=80, і блакитний=72, — тобто RGB-триплетом для лососевого кольору є рядок "`FA8072`".
слушне зауваження, точно синій

2022-01-23 16:35 UTC, AdriandeCita commented on files/uk/web/javascript/reference/global_objects/string/fontcolor/index.md
> +зелений=80, і блакитний=72, — тобто RGB-триплетом для лососевого кольору є рядок "`FA8072`".
```suggestion
зелений=80, і синій=72, — тобто RGB-триплетом для лососевого кольору є рядок "`FA8072`".
```

2022-01-23 18:17 UTC, undead404 approved these changes

2022-01-23 22:20 UTC, merged