translation(HTML): web/html/element/input/index.md
webdoky/content pull request #209
Opened 2022-01-21 21:41 UTC by undead404

Original content: [<input>: The Input (Form Input) element - HTML: HyperText Markup Language | MDN](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input)

Нехай з рев‘юверами буде сила...

2022-01-23 13:59 UTC, AdriandeCita commented on files/uk/web/html/element/input/index.md
> +[HTML](/uk/docs/Web/HTML) елемент **`<input>`** використовується для створення інтерактивних засобів керування у вебформах для приймання даних від користувача; доступно широке розмаїття типів даних в
трохи розділив, бо так не зрозуміло, чи то "засоби керування для приймання даних", чи "вебформи для приймання даних", чи все разом
```suggestion
[HTML](/uk/docs/Web/HTML) елемент **`<input>`** використовується для створення інтерактивних засобів керування у вебформах, щоб приймати дані від користувача; доступно широке розмаїття типів даних введення та контрольних віджетів, залежно від пристрою та {{Glossary("user agent", "користувацького агента")}}. Елемент `<input>` – один із найпотужніших та найскладніших у всій HTML, тому що має безліч комбінацій типів введення та атрибутів.
```

2022-01-23 14:00 UTC, AdriandeCita commented on files/uk/web/html/element/input/index.md
> +Те, як `<input>` працює, значною мірою залежить від значення його атрибута {{htmlattrxref("type", "input")}}, і – різні типи покриті на власних довідкових сторінках. Якщо цей атрибут не вказаний – ви
```suggestion
Те, як `<input>` працює, значною мірою залежить від значення його атрибута {{htmlattrxref("type", "input")}}, – тому різні типи покриті на власних довідкових сторінках. Якщо цей атрибут не вказаний – використовується усталене значення `text`.
```

2022-01-23 14:01 UTC, AdriandeCita commented on files/uk/web/html/element/input/index.md
> +Доступні типи – наступні:
```suggestion
Доступні наступні типи:
```

2022-01-23 14:02 UTC, AdriandeCita commented on files/uk/web/html/element/input/index.md
> +      <td>Прапорець, котрий дає змогу обирати певні значення та скасовувати вибір.</td>
```suggestion
      <td>Прапорець, котрий дає змогу обирати та скасовувати вибір окремих значень.</td>
```

2022-01-23 14:04 UTC, AdriandeCita commented on files/uk/web/html/element/input/index.md
> +        Поле для редагування адреси електронної пошти. Має вигляд введення
```suggestion
        Поле для редагування адреси електронної пошти. Має вигляд поля з типом
```

2022-01-23 14:05 UTC, AdriandeCita commented on files/uk/web/html/element/input/index.md
> +        Контрольний елемент, що дає змогу користувачеві обрати файл. Для встановлення типів файлів, що цей елемент може обрати, слід використовувати атрибут {{anch('attr-accept', 'accept')}}.
```suggestion
        Контрольний елемент, що дає змогу користувачеві обрати файл. Для встановлення типів файлів, які може обрати цей елемент, слід використовувати атрибут {{anch('attr-accept', 'accept')}}.
```

2022-01-23 14:07 UTC, AdriandeCita commented on files/uk/web/html/element/input/index.md
> +        показується, якщо зображення {{anch('attr-src', 'src')}} немає.
```suggestion
        показується, якщо атрибут {{anch('attr-src', 'src')}} із зображенням відсутній.
```

2022-01-23 14:08 UTC, AdriandeCita commented on files/uk/web/html/element/input/index.md
> +        Контрольний елемент для введення числа, чиє точне значення неважливе. Показує віджет діапазону, що зводиться до значення посередині. Використовується у зв‘язці з атрибутами {{anch('attr-min',
```suggestion
        Контрольний елемент для введення числа, чиє точне значення неважливе. Показує віджет діапазону, що усталено показує значення посередині. Використовується у зв‘язці з атрибутами {{anch('attr-min', 'min')}} та
```

2022-01-23 14:11 UTC, AdriandeCita commented on files/uk/web/html/element/input/index.md
> +        Однорядкове текстове поле для введення рядків пошуку. Розриви рядка автоматично прибираються зі значення введення. Може включати значок видалення у деяких браузерах, що може використовуватись
```suggestion
        Однорядкове текстове поле для введення рядків пошуку. Розриви рядка автоматично прибираються з введеного значення. Може включати значок видалення у деяких браузерах, що може використовуватись для очищення поля. Показує значок пошуку замість кнопки "Enter" на деяких пристроях із динамічними клавіатурами.
```

2022-01-23 14:15 UTC, AdriandeCita commented on files/uk/web/html/element/input/index.md
> +        Поле для введення URL. Має вигляд поля <code>text</code>, але має параметри валідації та відповідну клавіатуру, коли це підтримується браузером чи на пристроях з динамічними клавіатурами.
```suggestion
        Поле для введення URL. Має вигляд поля з типом <code>text</code>, але має параметри валідації та відповідну клавіатуру, коли це підтримується браузером чи на пристроях з динамічними клавіатурами.
```

2022-01-23 14:18 UTC, AdriandeCita commented on files/uk/web/html/element/input/index.md
> +Цей розділ містить таблицю з переліком усіх атрибутів зі стислим їх описом. Нижче цієї таблиці розміщений список, що описує кожний атрибут більш докладно, в тому числі вказуючи, з якими типами полів
```suggestion
Цей розділ містить таблицю з переліком усіх атрибутів зі стислим їх описом. Нижче цієї таблиці розміщений список, що описує кожний атрибут більш докладно, в тому числі вказуючи, з якими типами полів введення пов‘язаний кожний атрибут. Ті з них, що діють для більшості або всіх типів полів введення, описані докладно нижче. Атрибути, що є ексклюзивними для певних типів полів введення, а також ті, що діють для всіх полів введення, але мають особливу поведінку на певному типі полів введення – документовані на сторінках відповідних типів. Також цей елемент приймає [глобальні атрибути](/uk/docs/Web/HTML/Global_attributes). Додатково виділено ті з них, які особливо важливі для `<input>`.
```

2022-01-23 14:24 UTC, AdriandeCita commented on files/uk/web/html/element/input/index.md
> +        вертикальна розмірність
"dimensions" також означає "габарити". В цьому випадку радше мається на увазі габаритний розмір
```suggestion
        вертикальний розмір
```

2022-01-23 14:29 UTC, AdriandeCita commented on files/uk/web/html/element/input/index.md
> +      <td>Схема, котрій мусить відповідати <code>value</code>, щоб бути дійсним</td>
В таких випадках я зазвичай керуюсь математичною нотацією. У нас прийнято вказувати зміст змінної і її назву, як от "...нехай шлях `S` дорівнює...". У нас не зовсім змінні, але `value` - це цілком схоже на вказівку на одноіменний атрибут і поле об'єкта HTMLInputElement
```suggestion
      <td>Схема, котрій мусить відповідати значення <code>value</code>, щоб бути дійсним</td>
```

2022-01-23 15:04 UTC, AdriandeCita commented on files/uk/web/html/element/input/index.md
> +  - : (**Не** булів атрибут!) атрибут [`autocomplete`](/uk/docs/Web/HTML/Attributes/autocomplete) приймає розділений пробілами рядок, що описує, який, якщо будь-який, тип функціональності автозаповне
```suggestion
  - : (**Не** булів атрибут!) атрибут [`autocomplete`](/uk/docs/Web/HTML/Attributes/autocomplete) приймає розділений пробілами рядок, що описує, який тип функціональності автозаповнення слід надати (якщо це взагалі потрібно). Типова реалізація автозаповнення нагадує попередні значення, введені у таке ж поле вводу, але можуть існувати складніші форми автозаповнення. Наприклад, браузер може використовувати список контактів пристрою для автозаповнення адрес `email` у полі введення електронної адреси. Дивіться {{SectionOnPage("/uk/docs/Web/HTML/Attributes/autocomplete", "Значення")}} щодо дозволених значень.
```

2022-01-23 15:28 UTC, AdriandeCita commented on files/uk/web/html/element/input/index.md
> +    Ретельно обміркуйте можливі проблеми доступності при застосуванні атрибута `autofocus`. Автоматичне фокусування на контрольному елементі може змусити сторінку прокрутитись при завантаженні. На де
```suggestion
    Ретельно обміркуйте можливі проблеми доступності при застосуванні атрибута `autofocus`. Автоматичне фокусування на контрольному елементі може змусити сторінку прокрутитись при завантаженні. На деяких сенсорних пристроях фокус може також змусити з‘явитись динамічну клавіатуру. Хоч читач з екрана оголосить підпис контрольного елемента, що отримує фокус, читач з екрана не оголосить нічого вище такої бирки, а зрячий користувач із малим пристроєм аналогічним чином упустить контекст, створений вмістом вище.
```

2022-01-23 15:47 UTC, AdriandeCita commented on files/uk/web/html/element/input/index.md
> +  - : Булів атрибут, котрий, бувши встановленим, вказує, що користувач не повинен мати змогу взаємодіяти з полем введення. Вимкнені поля введення зазвичай зображаються у тьмяніших кольорах, або те, щ
```suggestion
  - : Булів атрибут, котрий, бувши встановленим, вказує, що користувач не повинен мати змогу взаємодіяти з полем введення. Вимкнені поля введення зазвичай зображаються у тьмяніших кольорах, або з якоюсь іншою візуальною індикацією того, що поле недоступне для використання.
```

2022-01-23 15:49 UTC, AdriandeCita commented on files/uk/web/html/element/input/index.md
> +  - : Чинний лише для кнопки `image`. `height` – висота файлу зображення для представлення графічної кнопки подання. Дивіться тип поля введення {{HTMLElement("input/image", "image")}}.
```suggestion
  - : Чинний лише для кнопки `image`. `height` – висота файлу зображення для представлення графічної кнопки подання форми. Дивіться тип поля введення {{HTMLElement("input/image", "image")}}.
```

2022-01-23 15:55 UTC, AdriandeCita commented on files/uk/web/html/element/input/index.md
> +    Поле введення провалить [валідацію обмежень](/uk/docs/Web/Guide/HTML/Constraint_validation), якщо довжина введеного в поле тексту перевищить `maxlength` кодових одиниць UTF-16. Усталено браузери
```suggestion
    Поле введення провалить [валідацію обмежень](/uk/docs/Web/Guide/HTML/Constraint_validation), якщо довжина введеного в поле тексту перевищить `maxlength` кодових одиниць UTF-16. Усталено браузери не дають користувачам вводити більше символів, ніж дозволено атрибутом `maxlength`. Детальніше про це в секції {{anch("validatsiia-na-kliientskomu-botsi", "Валідація на клієнтському боці")}}.
```

2022-01-23 15:55 UTC, AdriandeCita commented on files/uk/web/html/element/input/index.md
> +  - : Чинний для `date`, `month`, `week`, `time`, `datetime-local`, `number` та `range`. Визначає найменше значення діапазону прийнятних значень. Якщо значення {{htmlattrxref("value", "input")}}, вве
```suggestion
  - : Чинний для `date`, `month`, `week`, `time`, `datetime-local`, `number` та `range`. Визначає нижню межу діапазону прийнятних значень. Якщо значення {{htmlattrxref("value", "input")}}, введене в елемент, менше за значення `min`, то елемент провалює [валідацію обмежень](/uk/docs/Web/Guide/HTML/Constraint_validation). Якщо значення атрибута `min` не є числом, то елемент не має мінімального значення.
```

2022-01-23 15:58 UTC, AdriandeCita commented on files/uk/web/html/element/input/index.md
> +    Поле введення провалить [валідацію обмежень](/uk/docs/Web/Guide/HTML/Constraint_validation), якщо довжина введеного в поле тексту менша за `minlength` кодових одиниць UTF-16, і форма не буде пода
```suggestion
    Поле введення провалить [валідацію обмежень](/uk/docs/Web/Guide/HTML/Constraint_validation), якщо довжина введеного в поле тексту менша за `minlength` кодових одиниць UTF-16, і форма не буде подана. Детальніше про це в секції {{anch("validatsiia-na-kliientskomu-botsi", "Валідація на клієнтському боці")}}.
```

2022-01-23 15:59 UTC, AdriandeCita commented on files/uk/web/html/element/input/index.md
> +  - : Чинний для `text`, `search`, `url`, `tel`, `email` та `password`. Встановлює найбільшу прийнятну кількість символів (як кодових одиниць UTF-16), що їх користувач може ввести у поле. Мусить мати
```suggestion
  - : Чинний для `text`, `search`, `url`, `tel`, `email` та `password`. Встановлює найменшу прийнятну кількість символів (як кодових одиниць UTF-16), що їх користувач може ввести у поле. Мусить мати ціле числове значення, менше або рівне значенню `maxlength`. Якщо атрибут `minlength` не вказаний, або вказане недійсне значення, то поле не має мінімальної довжини.
```

2022-01-23 16:15 UTC, AdriandeCita commented on files/uk/web/html/element/input/index.md
> +    При табулюванні до групи однойменних радіокнопок, якщо одна з них обрана, то така радіокнопка отримає фокус. Якщо вони не згруповані докупи в коді HTML, то якщо одна радіокнопка в групі обрана –
```suggestion
    При табулюванні до групи однойменних радіокнопок, якщо одна з них обрана, то така радіокнопка отримає фокус. Якщо вони не згруповані докупи в коді HTML, то якщо одна радіокнопка в групі обрана – табулювання до групи починається тоді, коли зустрічається перша радіокнопка групи, пропускаючи всі ті, що не є обраними. Інакше кажучи, якщо одна радіокнопка обрана — табулювання пропустить всі інші радіокнопки групи. Якщо жодна з радіокнопок не обрана, група отримує фокус, коли він досягає до першої кнопки групи.
```

2022-01-23 16:17 UTC, AdriandeCita commented on files/uk/web/html/element/input/index.md
> +    Коли елемент введення отримує `name`, таке ім‘я стає властивістю об‘єкта {{domxref("HTMLFormElement.elements")}} форми-власника елемента. Якщо існує поле введення, в котрого атрибут `name` має зн
```suggestion
    Коли елемент введення отримує атрибут `name`, це ім‘я стає властивістю об‘єкта {{domxref("HTMLFormElement.elements")}} форми-власника елемента. Якщо існує поле введення, в котрого атрибут `name` має значення `guest`, і іще одне з `name` – `hat-size`, можна використати наступний код:
```

2022-01-23 16:20 UTC, AdriandeCita commented on files/uk/web/html/element/input/index.md
> +  - : Властивість `pattern` – регулярний вираз, котрому повинно відповідати {{htmlattrxref("value", "input")}} поля введення, щоб значення пройшло [валідацію обмежень](/uk/docs/Web/Guide/HTML/Constra
```suggestion
  - : Властивість `pattern` – регулярний вираз, котрому повинно відповідати значення {{htmlattrxref("value", "input")}} поля введення, щоб пройти [валідацію обмежень](/uk/docs/Web/Guide/HTML/Constraint_validation). Значенням атрибута має бути дійсний регулярний вираз JavaScript, такий, як використовується типом {{jsxref("RegExp")}} і як документовано у наших [настановах із регулярних виразів](/uk/docs/Web/JavaScript/Guide/Regular_Expressions). При компіляції регулярного виразу автоматично вказується прапорець `'u'`, тож схема розглядається як послідовність кодових точок Юнікоду, а не як ASCIII. Текст схеми не повинен бути оточений рисками.
```

2022-01-23 16:23 UTC, AdriandeCita commented on files/uk/web/html/element/input/index.md
> +    Якщо атрибут `pattern` присутній, але не має значення, або має недійсне значення, то регулярний вираз не застосовується, і такий атрибут цілком ігнорується. Якщо атрибут схеми дійсний, і непусте
Пропоную залишити схему для баз даних)
```suggestion
    Якщо атрибут `pattern` присутній, але не має значення, або має недійсне значення, то регулярний вираз не застосовується, і такий атрибут цілком ігнорується. Якщо атрибут з патерном дійсний, і непусте значення поля введення не відповідає йому, то валідація обмежень перешкодить поданню форми.
```

2022-01-23 16:25 UTC, AdriandeCita commented on files/uk/web/html/element/input/index.md
> +    > **Примітка:** Атрибут `placeholder` не є так семантично корисним, як інші способи пояснення форми, і може спричинити неочікувані технічні проблеми зі вмістом. Дивіться {{anch("pidpysy", "Підпис
```suggestion
    > **Примітка:** Атрибут `placeholder` не є так семантично корисним, як інші способи пояснення форми, і може спричинити неочікувані технічні проблеми зі вмістом. Дивіться {{anch("pidpysy", "Підписи")}} для докладнішої інформації.
```

2022-01-23 16:28 UTC, AdriandeCita commented on files/uk/web/html/element/input/index.md
> +    Значення мусить бути додатним числом, цілим чи з плавучою комою – або особливим значенням `any`, котре вказує не застосовувати крокування і приймати будь-яке значення (прийнятне згідно з іншими о
```suggestion
    Значення мусить бути додатним числом, цілим чи з рухомою комою – або особливим значенням `any`, котре вказує не застосовувати крокування і приймати будь-яке значення (прийнятне згідно з іншими обмеженнями, наприклад, `{{anch("min")}}` і `{{anch("max")}}`).
```

2022-01-23 16:29 UTC, AdriandeCita commented on files/uk/web/html/element/input/index.md
> +    Значення мусить бути додатним числом, цілим чи з плавучою комою – або особливим значенням `any`, котре вказує не застосовувати крокування і приймати будь-яке значення (прийнятне згідно з іншими о
референс https://uk.wikipedia.org/wiki/%D0%A7%D0%B8%D1%81%D0%BB%D0%BE_%D0%B7_%D1%80%D1%83%D1%85%D0%BE%D0%BC%D0%BE%D1%8E_%D0%BA%D0%BE%D0%BC%D0%BE%D1%8E

2022-01-23 16:30 UTC, AdriandeCita commented on files/uk/web/html/element/input/index.md
> +    Якщо явно не вказане значення `any`, то дійсні значення для типів `number`, дати й часу, а також `range` – це основа крокування – значення `{{anch("min")}}` та збільшення на значення кроку, аж до
**// TBD**

2022-01-23 18:20 UTC, undead404 commented
Як то так, що коммітів не було, але коментарі outdated?..

2022-01-23 18:41 UTC, AdriandeCita commented on files/uk/web/html/element/input/index.md
> +    Якщо явно не вказане значення `any`, то дійсні значення для типів `number`, дати й часу, а також `range` – це основа крокування – значення `{{anch("min")}}` та збільшення на значення кроку, аж до
Так наче зрозуміліше. Хоча оригінал просто дикий...
```suggestion
    Якщо явно не вказане значення `any`, то дійсні значення для типів `number`, дати й часу, а також `range` охоплюють: основу крокування – значення `{{anch("min")}}`, та всі її зростання на розмір кроку, аж до значення `{{anch("max")}}` (якщо воно вказане).
```

2022-01-23 18:42 UTC, AdriandeCita commented on files/uk/web/html/element/input/index.md
> +    Наприклад, якщо є `<input type="number" min="10" step="2">`, то будь-яке парне число, починаючи від `10`, є дійсним значенням. Якщо опустити атрибути обмежень, `<input type="number">`, то усі ціл
```suggestion
    Наприклад, якщо є `<input type="number" min="10" step="2">`, то будь-яке парне число, починаючи від `10`, є дійсним значенням. Якщо опустити атрибути обмежень, `<input type="number">`, то усі цілі числа будуть дійсними значеннями, а числа з дробовою частиною (як `4.2`) – ні, бо усталене значення `step` – `1`. Щоб `4.2` було дійсним значенням, `step` має бути або `any`, або 0.1, або 0.2. А якби значення `min` було числом, що закінчується на `.2`, – значення `step` могло б бути будь-яким: `<input type="number" min="-5.2">`
```

2022-01-23 18:44 UTC, AdriandeCita commented on files/uk/web/html/element/input/index.md
> +  - : Глобальний атрибут, чинний для всіх елементів, включаючи поля введення усіх типів. Цілочисловий атрибут, що вказує, чи може елемент отримати фокус введення (чи є фокусованим) під час послідовно
```suggestion
  - : Глобальний атрибут, чинний для всіх елементів, включаючи поля введення усіх типів. Цілочисловий атрибут, що вказує, чи може елемент отримати фокус введення (чи є фокусованим) під час послідовної навігації за допомогою клавіатури. Оскільки поля введення усіх типів, окрім типу `hidden`, є фокусованими, то цей атрибут не повинен застосовуватись на контрольних елементах, оскільки це призвело б до необхідності керувати порядком фокусування усіх елементів документа та загрози погіршення зручності та доступності при неправильній реалізації.
```

2022-01-23 18:48 UTC, AdriandeCita commented on files/uk/web/html/element/input/index.md
> +  - : Чинний лише для кнопки введення `image`. `width` – це ширина файлу зображення для представлення графічної кнопки подання. Дивіться тип поля введення {{HTMLElement("input/image", "image")}}.
```suggestion
  - : Чинний лише для кнопки — поля введення з типом `image`. `width` – це ширина файлу зображення для представлення графічної кнопки подання. Дивіться тип поля введення {{HTMLElement("input/image", "image")}}.
```

2022-01-23 19:02 UTC, AdriandeCita commented on files/uk/web/html/element/input/index.md
> +  - : Обирає вказаний відрізок символів всередині текстового поля введення. нічого не робить для полів введення, що не представлені текстовими полями.
```suggestion
  - : Обирає вказаний відрізок символів всередині текстового поля введення. Нічого не робить для полів введення, що не представлені текстовими полями.
```

2022-01-23 19:05 UTC, AdriandeCita commented on files/uk/web/html/element/input/index.md
> +Поля введення, бувши заміщеними елементами, мають кілька особливостей, що не властиві елементам іншого роду. Є селектори CSS, що можуть націлювати на контрольні елементи форм на основі функціональнос
```suggestion
Поля введення, бувши заміщеними елементами, мають кілька особливостей, що не властиві елементам іншого роду. Є селектори CSS, що можуть націлювати на контрольні елементи форм на основі функціональності їх користувацького інтерфейсу, також відомі як псевдокласи користувацького інтерфейсу. Серед них також є деякі особливо корисні властивості.
```

2022-01-23 19:09 UTC, AdriandeCita commented on files/uk/web/html/element/input/index.md
> +        в тому числі елементи <code>&#x3C;input></code> and
```suggestion
        в тому числі елементи <code>&#x3C;input></code> і
```

2022-01-23 19:11 UTC, AdriandeCita commented on files/uk/web/html/element/input/index.md
> +        та {{HTMLElement("input/radio", "radio")}}, що були обрані при завантаженні сторінки чи візуалізації.
```suggestion
        та {{HTMLElement("input/radio", "radio")}}, що уже були обрані на момент завантаження сторінки чи візуалізації.
```

2022-01-23 19:12 UTC, AdriandeCita commented on files/uk/web/html/element/input/index.md
> +        елементи {{HTMLElement("input/radio", "radio")}}, коли всі радіокнопки з таким само значенням у формі є непозначеними, і елементи {{HTMLElement("progress")}} у невизначеному стані
```suggestion
        елементи {{HTMLElement("input/radio", "radio")}}, коли всі радіокнопки з однаковим іменем у формі є непозначеними, і елементи {{HTMLElement("progress")}} у невизначеному стані
```

2022-01-23 20:43 UTC, AdriandeCita commented on files/uk/web/html/element/input/index.md
> +        Подібний до <code>:invalid</code>, але активується при втраті фокусу. Збігається з невалідними полями введення, але лише після взаємодії з ними користувача, наприклад, сфокусування на такому
```suggestion
        Подібний до <code>:invalid</code>, але активується при втраті фокусу. Збігається з невалідними полями введення, але лише після взаємодії з ними користувача. Наприклад, коли користувач сфокусування на такому контрольному елементі, а потім залишив його, або спробував подати форму з невалідним контрольним елементом.
```

2022-01-23 20:44 UTC, AdriandeCita commented on files/uk/web/html/element/input/index.md
> +Можна стилізувати підпис прапорця по різному на основі того, є він позначеним чи ні. У цьому прикладі стиль – це {{cssxref('color')}} і {{cssxref('font-weight')}} на {{htmlelement('label')}}, що йде
```suggestion
Можна по різному стилізувати підпис прапорця на основі того, є він позначеним чи ні. У цьому прикладі стиль – це {{cssxref('color')}} і {{cssxref('font-weight')}} на {{htmlelement('label')}}, що йде зразу після позначеного поля введення. Якщо `input` не позначений – не встановлюються жодні стилі.
```

2022-01-23 20:51 UTC, AdriandeCita commented on files/uk/web/html/element/input/index.md
> +Можна цілитись на різноманітні контрольні елементи на основі їх {{ htmlattrxref("type", "input", "", 1)}} за допомогою [селекторів атрибутів](/uk/docs/Learn/CSS/Building_blocks/Selectors/Attribute_se
В деяких контекстах "відповідають" звучить трохи дивно. Я б краще перекладав "matches" як "вказують на":
```suggestion
Можна цілитись на різноманітні контрольні елементи на основі їх типу {{ htmlattrxref("type", "input", "", 1)}} за допомогою [селекторів атрибутів](/uk/docs/Learn/CSS/Building_blocks/Selectors/Attribute_selectors). Селектори атрибутів CSS вказують на елементи, спираючись або лиш на присутність атрибута, або на наявність атрибута з певним значенням.
```

2022-01-23 20:55 UTC, AdriandeCita commented on files/uk/web/html/element/input/index.md
> +Властивість {{cssxref("appearance")}} (зовнішній вигляд) вмикає відображення (майже) будь-якого елемента в стилі, що є природним для платформи, на основі теми операційної системи, або ж вимикає усі н
```suggestion
Властивість {{cssxref("appearance")}} (зовнішній вигляд) вмикає відображення (майже) будь-якого елемента в стилі, що є природним для платформи, на основі теми операційної системи, або ж вимикає усі нативні стилі, якщо вказано значення `none`.
```

2022-01-23 21:06 UTC, AdriandeCita commented on files/uk/web/html/element/input/index.md
> +- [Передова стилізація для форм HTML](/uk/docs/Learn/Forms/Advanced_form_styling) і
Думаю, тут краще вжити щось таке. Тут мається на увазі не стільки сучасність, скільки вища складність матеріалу і ширші можливості.
```suggestion
- [Розширена стилізація для форм HTML](/uk/docs/Learn/Forms/Advanced_form_styling) і
```

2022-01-23 21:09 UTC, AdriandeCita commented on files/uk/web/html/element/input/index.md
> +Підписи необхідні для сполучення допоміжного тексту з `<input>`. Елемент {{HTMLElement("label")}} надає пояснювальну інформацію про поле форми, що _завжди_ є доречною (попри можливі занепокоєння щодо
У мене виникає враження, що просто компонування не дає достатньо контексту, пропоную хоча б додати вказівку на елементи
```suggestion
Підписи необхідні для сполучення допоміжного тексту з `<input>`. Елемент {{HTMLElement("label")}} надає пояснювальну інформацію про поле форми, що _завжди_ є доречною (попри можливі занепокоєння щодо компонування елементів). Ніколи не є поганою ідеєю використати `<label>`, щоб пояснити, що саме повинно бути введено в `<input>` чи {{HTMLElement("textarea")}}.
```

2022-01-23 21:10 UTC, AdriandeCita commented on files/uk/web/html/element/input/index.md
> +Семантичне парування елементів `<input>` і `<label>` корисне для технологій типу читачів з екрана. Бувши спарованими за допомогою атрибута {{htmlattrxref("for", "label")}} елемента `<label>`, підпис
```suggestion
Семантичне парування елементів `<input>` і `<label>` корисне для технологій типу читачів з екрана. Бувши спарованими за допомогою атрибута {{htmlattrxref("for", "label")}} елемента `<label>`, підпис та поле введення пов‘язані так, що читачі з екрана можуть точніше описати користувачам поля введення.
```

2022-01-23 21:12 UTC, AdriandeCita commented on files/uk/web/html/element/input/index.md
> +На додачу до доступного імені, підпис надає більшу зону "попадання" для миші та користувачів сенсорних екранів для кліку чи дотику. При паруванні `<label>` із `<input>` клік на будь-якому з цих двох
```suggestion
На додачу до доступного імені, підпис надає більшу зону "попадання" для миші та користувачів сенсорних екранів для кліку чи дотику. При паруванні `<label>` із `<input>` клік на будь-якому з цих двох елементів спричинить передачу фокусу до елементу `<input>`. При використанні простого тексту для "підписування" поля введення – цього не відбудеться. Присутність зони підказки для активації поля введення допомагає людям із порушеннями контролю руху.
```

2022-01-23 21:23 UTC, AdriandeCita commented on files/uk/web/html/element/input/index.md
> +        Трапляється, коли число символів більше за число, дозволене властивістю <code>maxlength</code>
```suggestion
        Трапляється, коли кількість символів більша за число, дозволене властивістю <code>maxlength</code>
```

2022-01-23 21:24 UTC, AdriandeCita commented on files/uk/web/html/element/input/index.md
> +        Трапляється, коли число символів менше за число, дозволене властивістю <code>maxlength</code>
```suggestion
        Трапляється, коли кількість символів менша за число, дозволене властивістю <code>minlength</code>
```

2022-01-23 21:24 UTC, AdriandeCita commented on files/uk/web/html/element/input/index.md
> +        Трапляється, коли присутній атрибут `pattern` з дійсним регулярним виразом, а <code>value</code> цьому виразові не відповідає.
```suggestion
        Трапляється, коли присутній атрибут `pattern` з дійсним регулярним виразом, а значення <code>value</code> цьому виразові не відповідає.
```

2022-01-23 21:26 UTC, AdriandeCita commented on files/uk/web/html/element/input/index.md
> +        дійсні значення – лише цілі числа, якщо нема атрибута `step`. <code>step="any"</code> ніколи не викидатиме такої помилки
```suggestion
        дійсні значення – лише цілі числа, якщо нема атрибута `step`. Поле з атрибутом <code>step="any"</code> ніколи не викидатиме такої помилки.
```

2022-01-23 21:26 UTC, AdriandeCita commented on files/uk/web/html/element/input/index.md
> +        error.
```suggestion
```

2022-01-23 21:27 UTC, AdriandeCita commented on files/uk/web/html/element/input/index.md
> +Можна встановлювати межі того, які значення приймаються, і браузери, що це підтримують, будуть природно валідувати такі значення форми й повідомити користувача при поданні форми, що присутня помилка.
```suggestion
Можна встановлювати межі того, які значення приймаються, і браузери, що це підтримують, будуть природно валідувати такі значення форми й повідомляти користувача про помилку при поданні форми.
```

2022-01-23 21:28 UTC, AdriandeCita commented on files/uk/web/html/element/input/index.md
> +- {{domxref('validityState.patternMismatch')}} (невідповідність схемі)
```suggestion
- {{domxref('validityState.patternMismatch')}} (невідповідність патерну)
```

2022-01-23 21:29 UTC, AdriandeCita commented on files/uk/web/html/element/input/index.md
> +- {{domxref('validityState.rangeUnderflow')}} (недосягнення діапазону)
```suggestion
- {{domxref('validityState.rangeUnderflow')}} (вихід за нижню межу діапазону)
```

2022-01-23 21:29 UTC, AdriandeCita commented on files/uk/web/html/element/input/index.md
> +- {{domxref('validityState.rangeOverflow')}} (перевищення діапазону)
```suggestion
- {{domxref('validityState.rangeOverflow')}} (вихід за верхню межу діапазону)
```

2022-01-23 21:33 UTC, AdriandeCita commented on files/uk/web/html/element/input/index.md
> +Для кожної з цих булевих властивостей значення `true` вказує, що з відповідної причини валідація може бути провалена, окрім властивості `valid`, що має значення `true`, коли значення елемента відпові
```suggestion
Для кожної з цих булевих властивостей значення `true` вказує, що з відповідної причини валідація може бути провалена, окрім властивості `valid`, що має значення `true`, коли значення елемента задовільняє усім обмеженням.
```

2022-01-23 21:54 UTC, AdriandeCita commented on files/uk/web/html/element/input/index.md
> +Останній рядок, встановлення особливого повідомлення валідації як рядка помилки – вся суть. Якщо користувач робить помилку, і встановлене значення валідності, то відбудеться провал подання, навіть як
```suggestion
Останній рядок, встановлення особливого повідомлення валідації як рядка помилки – вся суть. Якщо користувач робить помилку, і значення валідності встановлено, то подання форми провалюватиметься навіть після того, коли всі значення стануть дійсними, аж поки повідомлення не стане `null`.
```

2022-01-23 21:55 UTC, AdriandeCita commented on files/uk/web/html/element/input/index.md
> +Якщо необхідно показати особливе повідомлення помилки, коли поле провалює валідацію, слід використовувати [функціональність валідації обмежень](/uk/docs/Web/API/Constraint_validation#constraint_valid
```suggestion
Якщо необхідно показати особливе повідомлення помилки, коли поле провалює валідацію, слід використовувати [функціональність валідації обмежень](/uk/docs/Web/API/Constraint_validation#constraint_validation_interfaces), доступну на елементі `<input>` (та споріднених до нього). Розберімо наступну форму:
```

2022-01-23 21:59 UTC, AdriandeCita commented on files/uk/web/html/element/input/index.md
> +Базова функціональність валідації форм HTML спричинить усталене повідомлення помилки, якщо спробувати подати форму або без дійсного введення, або зі значенням, що не відповідає `pattern`.
```suggestion
Базова функціональність валідації форм HTML спричинить появу усталеного повідомлення про помилку, якщо спробувати подати форму або без дійсного заповнення, або зі значенням, яке не задовольняє `pattern`.
```

2022-01-23 22:05 UTC, AdriandeCita commented on files/uk/web/html/element/input/index.md
> +- Якщо значення – недійсне, то виринає подія `invalid` і запускається функція, що є обробником події `invalid`. Всередині цієї функції приймається рішення, чи значення недійсне, бо пусте, чи через те
```suggestion
- Якщо значення – недійсне, то виринає подія `invalid` і запускається функція, що є обробником події `invalid`. Всередині цієї функції за допомогою блоку `if()` приймається рішення, чому значення недійсне: бо порожнє, чи через невідповідність патерну, і – встановлюється власне повідомлення помилки валідації.
```

2022-01-23 22:07 UTC, AdriandeCita commented on files/uk/web/html/element/input/index.md
> +> **Примітка:** Firefox підтримував власницький атрибут помилки — `x-moz-errormessage` — протягом багатьох версій, котрий давав змогу встановлювати повідомлення помилки у подібний спосіб. Це було при
```suggestion
> **Примітка:** Firefox підтримував власницький атрибут помилки — `x-moz-errormessage` — протягом багатьох версій, котрий давав змогу подібним чином встановлювати спеціальні повідомлення про помилки. Це було прибрано у версії 66 (дивіться {{bug(1513890)}}).
```

2022-01-23 22:13 UTC, AdriandeCita commented on files/uk/web/html/element/input/index.md
> +При включенні полів введення є вимогою доступності додання підписів поруч. Це потрібно, щоб користувачі допоміжних технологій могли зрозуміти призначення поля. А ще – натискання на підпис передає фок
```suggestion
При включенні полів введення вимогою доступності є додання підписів поруч. Це потрібно, щоб користувачі допоміжних технологій могли зрозуміти призначення поля. А ще – натискання на підпис передає фокус контрольному елементові, що сполучений з підписом. Це покращує доступність та зручність для зрячих користувачів, збільшує область, на котру може натиснути користувач для активування контрольного елемента. Це перш за все корисно (і навіть необхідно) для радіокнопок та прапорців, котрі самі по собі крихітні. Для докладнішої інформації про підписи в загальному дивіться {{anch("pidpysy", "Підписи")}}.
```

2022-01-23 22:15 UTC, AdriandeCita commented on files/uk/web/html/element/input/index.md
> +- [Природні віджети форми](/uk/docs/Learn/Forms/Basic_native_form_controls)
```suggestion
- [Нативні віджети форми](/uk/docs/Learn/Forms/Basic_native_form_controls)
```

2022-01-23 22:16 UTC, AdriandeCita commented on files/uk/web/html/element/input/index.md
> +- [Передова стилізація для форм HTML](/uk/docs/Learn/Forms/Advanced_form_styling)
```suggestion
- [Розширена стилізація для форм HTML](/uk/docs/Learn/Forms/Advanced_form_styling)
```

2022-01-23 22:17 UTC, AdriandeCita requested changes
Є трохи зауважень

2022-02-07 12:13 UTC, undead404 commented on files/uk/web/html/element/input/index.md
> +  - : (**Не** булів атрибут!) атрибут [`autocomplete`](/uk/docs/Web/HTML/Attributes/autocomplete) приймає розділений пробілами рядок, що описує, який, якщо будь-який, тип функціональності автозаповне
По-моєму, тут не про необхідність, а про змогу показати

2022-02-07 12:28 UTC, undead404 commented on files/uk/web/html/element/input/index.md
> +- {{domxref('validityState.patternMismatch')}} (невідповідність схемі)
Можливо, мені варто усюди тут схему на патерн перебити?

2022-02-11 19:01 UTC, AdriandeCita commented on files/uk/web/html/element/input/index.md
> +  - : (**Не** булів атрибут!) атрибут [`autocomplete`](/uk/docs/Web/HTML/Attributes/autocomplete) приймає розділений пробілами рядок, що описує, який, якщо будь-який, тип функціональності автозаповне
єп, має сенс

2022-02-11 19:24 UTC, AdriandeCita approved these changes

2022-02-11 19:24 UTC, merged