translation(js): Web/JavaScript/Reference/Global_Objects/String/localeCompare
webdoky/content pull request #210
Opened 2022-01-23 08:58 UTC by AdriandeCita

Original content: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/localeCompare

2022-01-23 18:30 UTC, undead404 requested changes

2022-01-23 18:30 UTC, undead404 commented on files/uk/web/javascript/reference/global_objects/string/localecompare/index.md
> +Нові аргументи `locales` та `options` дозволяють вказувати в застосунках мову, згідно з правилами якої слід виконувати сортування, та підлаштовувати поведінку функції. В старіших реалізаціях, які не
```suggestion
Нові аргументи `locales` та `options` дають змогу вказувати в застосунках мову, згідно з правилами якої слід виконувати сортування, та підлаштовувати поведінку функції. В старіших реалізаціях, які не зважають на аргументи `locales` та `options`, мова і порядок сортування цілком залежать від реалізації.
```

2022-01-23 18:30 UTC, undead404 commented on files/uk/web/javascript/reference/global_objects/string/localecompare/index.md
> +> **Застереження:** Не варто покладатись на конкретні значення `-1` чи `1`.
Warning? Я це перекладаю тепер як "Зауваження", бо "Застереження" – то більше "alert". До речі, чудовий переклад слова "alert" має бути

2022-01-23 18:30 UTC, undead404 commented on files/uk/web/javascript/reference/global_objects/string/localecompare/index.md
> +Для порівняння великої кількості рядків (наприклад, під час сортування великих масивів), краще створити окремий об'єкт {{jsxref("Global_Objects/Collator", "Intl.Collator")}}, і застосувати функцію, я
```suggestion
Для порівняння великої кількості рядків (наприклад, під час сортування великих масивів) краще створити окремий об'єкт {{jsxref("Global_Objects/Collator", "Intl.Collator")}} і застосувати функцію, яка надається його властивістю {{jsxref("Collator.prototype.compare", "compare")}}.
```

2022-01-23 18:30 UTC, undead404 commented on files/uk/web/javascript/reference/global_objects/string/localecompare/index.md
> +// З точки зору алфавітного порядку,
```suggestion
// З точки зору алфавітного порядку –
```

2022-01-23 18:30 UTC, undead404 commented on files/uk/web/javascript/reference/global_objects/string/localecompare/index.md
> +'check'.localeCompare('against'); // 2 або 1 (чи якесь інше додате значення)
```suggestion
'check'.localeCompare('against'); // 2 або 1 (чи якесь інше додатне значення)
```

2022-01-23 18:30 UTC, undead404 commented on files/uk/web/javascript/reference/global_objects/string/localecompare/index.md
> +Для перевірки, чи дана реалізація їх підтримує, достатньо вжити `"i"` другим аргументом (відповідно до вимоги відхиляти недійсні мовні позначення) і перевірити наявність винятку {{jsxref("RangeError"
```suggestion
Для перевірки їх підтримки даною реалізацією достатньо вжити `"i"` другим аргументом (відповідно до вимоги відхиляти недійсні мовні позначення) і перевірити наявність винятку {{jsxref("RangeError")}}:
```

2022-01-23 18:30 UTC, undead404 commented on files/uk/web/javascript/reference/global_objects/string/localecompare/index.md
> +Результат, повернений методом `localeCompare()` відрізняється для різних мов. Аби отримати порядок сортування згідно з мовою інтерфейсу конкретного застосунку, необхідно впевнитися, що ця мова (і мож
```suggestion
Результат, повернений методом `localeCompare()`, відрізняється для різних мов. Аби отримати порядок сортування згідно з мовою інтерфейсу конкретного застосунку, необхідно впевнитися, що ця мова (разом із, можливо, якимись запасними варіантами мов) вказана в аргументі `locales`:
```

2022-01-24 22:18 UTC, AdriandeCita commented on files/uk/web/javascript/reference/global_objects/string/localecompare/index.md
> +> **Застереження:** Не варто покладатись на конкретні значення `-1` чи `1`.
слушно, додам у глосарій

2022-01-24 22:24 UTC, AdriandeCita commented on files/uk/web/javascript/reference/global_objects/string/localecompare/index.md
> +> **Застереження:** Не варто покладатись на конкретні значення `-1` чи `1`.
```suggestion
> **Зауваження:** Не варто покладатись на конкретні значення `-1` чи `1`.
```

2022-02-04 08:48 UTC, merged