translation(JS): Web/JavaScript/Reference/Global_Objects/String/normalize
webdoky/content pull request #211
Opened 2022-01-23 08:59 UTC by AdriandeCita

Original content: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/normalize

2022-01-23 18:50 UTC, undead404 requested changes

2022-01-23 18:50 UTC, undead404 commented on files/uk/web/javascript/reference/global_objects/string/normalize/index.md
> +  - : Форма нормалізації Unicode, задана одним із чотирьох значень: `"NFC"`, `"NFD"`, `"NFKC"`, чи `"NFKD"`. Якщо цей параметр не задано, або передано {{jsxref("undefined")}}, буде використана `"NFC"
```suggestion
  - : Форма нормалізації Unicode, задана одним із чотирьох значень: `"NFC"`, `"NFD"`, `"NFKC"` чи `"NFKD"`. Якщо цей параметр не задано, або передано {{jsxref("undefined")}}, буде використана `"NFC"`.
```

2022-01-23 18:50 UTC, undead404 commented on files/uk/web/javascript/reference/global_objects/string/normalize/index.md
> +Кожному окремому символу Unicode призначає числове значення, назване _кодовою точкою_. Наприклад, для літери `"A"` визначено кодову точку U+0041. Однак, інколи один і той самий абстрактний символ мож
```suggestion
Кожному окремому символу Unicode призначає числове значення, назване _кодовою точкою_. Наприклад, для літери `"A"` визначено кодову точку U+0041. Утім, інколи один і той самий абстрактний символ можна позначати декількома різними кодовими точками, або навіть їх послідовністю. Наприклад, символ `"ñ"` можна позначити одним із двох способів:
```

2022-01-23 18:50 UTC, undead404 commented on files/uk/web/javascript/reference/global_objects/string/normalize/index.md
> +В Unicode, дві послідовності кодових точок канонічно еквівалентні, якщо вони позначають ті самі абстрактні символи. Вони повинні завжди мати однаковий візуальний вигляд і поведінку (наприклад, вони п
```suggestion
В Unicode дві послідовності кодових точок канонічно еквівалентні, якщо вони позначають ті самі абстрактні символи. Вони повинні завжди мати однаковий візуальний вигляд і поведінку (наприклад, вони повинні завжди однаково сортуватись).
```

2022-01-23 18:50 UTC, undead404 commented on files/uk/web/javascript/reference/global_objects/string/normalize/index.md
> +Варто зауважити, що довжина форми, нормалізованої методом `"NFD"`, дорівнює `2`. Це відбувається тому, що `"NFD"` видає **декомпоновану** версію канонічної форми, в якій поодинокі кодові точки розділ
```suggestion
Варто зауважити, що довжина форми, нормалізованої методом `"NFD"`, дорівнює `2`. Так виходь, тому що `"NFD"` видає **декомпоновану** версію канонічної форми, в якій поодинокі кодові точки розділені на декілька базових. Декомпонована канонічна форма літери `"ñ"` — це послідовність `"\u006E\u0303"`.
```

2022-01-23 18:50 UTC, undead404 commented on files/uk/web/javascript/reference/global_objects/string/normalize/index.md
> +В Unicode, дві послідовності кодових точок — сумісні, якщо вони позначають однакові абстрактні символи. Сумісні форми повинні однаково оброблятись у деяких (проте не обов'язково у всіх) застосунках.
```suggestion
В Unicode дві послідовності кодових точок — сумісні, якщо вони позначають однакові абстрактні символи. Сумісні форми повинні однаково оброблятись у деяких (проте не обов'язково у всіх) застосунках.
```

2022-01-23 18:50 UTC, undead404 commented on files/uk/web/javascript/reference/global_objects/string/normalize/index.md
> +Як і з канонічною нормалізацією, можна запросити компоновану чи декомпоновану сумісні форми шляхом передачі аргументів `"NFKD"` чи `"NFKC"`, відповідно.
```suggestion
Як і з канонічною нормалізацією, можна отримати компоновану чи декомпоновану сумісні форми шляхом передачі аргументів `"NFKD"` чи `"NFKC"`, відповідно.
```

2022-01-23 18:50 UTC, undead404 commented on files/uk/web/javascript/reference/global_objects/string/normalize/index.md
> +- [Стандарт Unicode, додаток #15, Форми нормалізації Unicode (англ)](http://www.unicode.org/reports/tr15/)
```suggestion
- [Стандарт Unicode, додаток #15, Форми нормалізації Unicode (англ.)](http://www.unicode.org/reports/tr15/)
```

2022-01-23 18:50 UTC, undead404 commented on files/uk/web/javascript/reference/global_objects/string/normalize/index.md
> +- [Unicode equivalence](https://en.wikipedia.org/wiki/Unicode_equivalence)
```suggestion
- [Юнікодна еквівалентність](https://en.wikipedia.org/wiki/Unicode_equivalence)
```

2022-01-24 22:26 UTC, AdriandeCita commented on files/uk/web/javascript/reference/global_objects/string/normalize/index.md
> +Варто зауважити, що довжина форми, нормалізованої методом `"NFD"`, дорівнює `2`. Це відбувається тому, що `"NFD"` видає **декомпоновану** версію канонічної форми, в якій поодинокі кодові точки розділ
```suggestion
Варто зауважити, що довжина форми, нормалізованої методом `"NFD"`, дорівнює `2`. Так виходить, тому що `"NFD"` видає **декомпоновану** версію канонічної форми, в якій поодинокі кодові точки розділені на декілька базових. Декомпонована канонічна форма літери `"ñ"` — це послідовність `"\u006E\u0303"`.
```

2022-02-04 08:48 UTC, merged