translatio(js): Web/JavaScript/Reference/Global_Objects/String/match
webdoky/content pull request #212
Opened 2022-01-23 08:59 UTC by AdriandeCita

Original content: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/match

2022-01-24 08:31 UTC, undead404 requested changes

2022-01-24 08:31 UTC, undead404 commented on files/uk/web/javascript/reference/global_objects/string/match/index.md
> +    Якщо не передати функції жодного параметра, і викликати метод `match()` напряму, з нього повернеться {{jsxref("Array", "масив")}} з порожнім рядком: `[""]`.
```suggestion
    Якщо не передати функції жодного параметра і викликати метод `match()` напряму, з нього повернеться {{jsxref("Array", "масив")}} з порожнім рядком: `[""]`.
```

2022-01-24 08:31 UTC, undead404 commented on files/uk/web/javascript/reference/global_objects/string/match/index.md
> +{{jsxref("Array", "Масив")}}, вміст якого залежить від наявності чи відсутності глобального прапорця (`g`), або {{jsxref("null")}}: якщо жодного збігу знайдено не було.
```suggestion
{{jsxref("Array", "Масив")}}, вміст якого залежить від наявності чи відсутності глобального прапорця (`g`), або {{jsxref("null")}}, якщо жодного збігу знайдено не було.
```

2022-01-24 08:31 UTC, undead404 commented on files/uk/web/javascript/reference/global_objects/string/match/index.md
> +  - : Об'єкт з іменованими групами захоплення, де ключі — це імена груп, а значення — значення відповідної групи або {{jsxref("undefined")}}, якщо жодної іменованої групи оголошено не було. Більше ін
```suggestion
  - : Об'єкт з іменованими групами захоплення, де ключі — це імена груп, а значення — значення відповідної групи, або {{jsxref("undefined")}}, якщо жодної іменованої групи оголошено не було. Більше інформації можна знайти в розділі [Групи та діапазони](/uk/docs/Web/JavaScript/Guide/Regular_Expressions/Groups_and_Ranges).
```
Помилка в оригіналі, знов

2022-01-24 08:31 UTC, undead404 commented on files/uk/web/javascript/reference/global_objects/string/match/index.md
> +В наступному прикладі метод `match()` використовується для пошуку слова '`Chapter`', за яким слідує 1 чи більше цифр із десятковою крапкою, повторені 0 чи більше разів.
```suggestion
В наступному прикладі метод `match()` використовується для пошуку слова '`Chapter`', за яким слідує 1 чи більше цифр, за якими слідують 0 або більше груп із точки та цифри.
```

2022-01-24 08:31 UTC, undead404 commented on files/uk/web/javascript/reference/global_objects/string/match/index.md
> +// '.1' — це останнє значеня, що буо захоплено групою '(\.\d)'.
```suggestion
// '.1' — це останнє значення, що було захоплено групою '(\.\d)'.
```

2022-01-24 08:31 UTC, undead404 commented on files/uk/web/javascript/reference/global_objects/string/match/index.md
> +> **Примітка:** також зверніть увагу на метод {{jsxref("String.prototype.matchAll()")}} та [Розширений пошук з прапорцями](/uk/docs/Web/JavaScript/Guide/Regular_Expressions#advanced_searching_with_fl
Розширений...

2022-01-24 08:31 UTC, undead404 commented on files/uk/web/javascript/reference/global_objects/string/match/index.md
> +> **Примітка:** також зверніть увагу на метод {{jsxref("String.prototype.matchAll()")}} та [Розширений пошук з прапорцями](/uk/docs/Web/JavaScript/Guide/Regular_Expressions#advanced_searching_with_fl
```suggestion
> **Примітка:** також зверніть увагу на метод {{jsxref("String.prototype.matchAll()")}} та [Розвинений пошук з прапорцями](/uk/docs/Web/JavaScript/Guide/Regular_Expressions#advanced_searching_with_flags).
```

2022-01-24 08:31 UTC, undead404 commented on files/uk/web/javascript/reference/global_objects/string/match/index.md
> +str1.match(NaN);        // NaN має тип "число". Поверає ["NaN"]
```suggestion
str1.match(NaN);        // NaN має тип "число". Повертає ["NaN"]
```

2022-01-24 08:31 UTC, undead404 commented
Хибодрук у назві PR виправив сам

2022-01-24 22:29 UTC, AdriandeCita commented
Так, особливо дякую за того чортика)

2022-01-24 22:32 UTC, AdriandeCita commented on files/uk/web/javascript/reference/global_objects/string/match/index.md
> +str1.match(NaN);        // NaN має тип "число". Поверає ["NaN"]
Іще одна причина, чому я хочу зробити роботу зі вмістом статей трохи грамотніше: з АСТ можна буде виділяти також коментарі в коді, і надсилати їх на перевірку в ЛТ

2022-01-24 22:36 UTC, AdriandeCita commented on files/uk/web/javascript/reference/global_objects/string/match/index.md
> +> **Примітка:** також зверніть увагу на метод {{jsxref("String.prototype.matchAll()")}} та [Розширений пошук з прапорцями](/uk/docs/Web/JavaScript/Guide/Regular_Expressions#advanced_searching_with_fl
Тут не згоден з розвиненим. Але припускаю, що розширений може комусь так само різати вуха, як мені - розвинений. Пропоную іншу альтернативу
```suggestion
> **Примітка:** також зверніть увагу на метод {{jsxref("String.prototype.matchAll()")}} та [Поліпшений пошук з прапорцями](/uk/docs/Web/JavaScript/Guide/Regular_Expressions#advanced_searching_with_flags).
```

2022-01-24 22:41 UTC, IhorHordiichuk commented on files/uk/web/javascript/reference/global_objects/string/match/index.md
> +> **Примітка:** також зверніть увагу на метод {{jsxref("String.prototype.matchAll()")}} та [Розширений пошук з прапорцями](/uk/docs/Web/JavaScript/Guide/Regular_Expressions#advanced_searching_with_fl
У цьому випадку точно розширений, тобто має розширені, чи то пак, додаткові можливості. Якби йшлося про етапи розвитку, наприклад, раніше він був без додаткових опцій, а зараз розвинувся у пошук з додатковими можливостями, тоді б він був розвиненим. Розвинений, у прикладі, розширено пояснює природу слова розвинений, яка споріднена зі словами «становлення» або «перетворення». Якщо контекст не викликає такого синонімічного ряду, тоді це слово явно не тулиться.

2022-02-04 09:03 UTC, undead404 approved these changes

2022-02-04 09:35 UTC, merged