translation(js): Web/JavaScript/Reference/Global_Objects/String/substring
webdoky/content pull request #231
Opened 2022-01-27 10:36 UTC by AdriandeCita

Original content: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/substring

2022-02-04 13:52 UTC, undead404 commented on files/uk/web/javascript/reference/global_objects/string/substring/index.md
> +Є невелика різниця між методами `substring()` та {{jsxref("String.substr", "substr()")}}, тож слід бути уважним і не плутати їх.
```suggestion
Є невелика різниця між методами `substring()` та {{jsxref("String.substr", "substr()")}}, тож слід бути уважними і не плутати їх.
```

2022-02-04 13:52 UTC, undead404 commented on files/uk/web/javascript/reference/global_objects/string/substring/index.md
> +Методи `substring()` та {{jsxref("String.slice", "slice()")}} — майже ідентичні, проте між ними двома є пара тонких відмінностей, здебільшого у способах роботи з від'ємними аргументами.
```suggestion
Методи `substring()` та {{jsxref("String.slice", "slice()")}} — майже ідентичні, проте між ними двома є кілька тонких відмінностей, здебільшого у способах роботи з від'ємними аргументами.
```

2022-02-04 13:52 UTC, undead404 commented on files/uk/web/javascript/reference/global_objects/string/substring/index.md
> +Кращий спосіб заміни рядків виглядає так:
```suggestion
Кращий спосіб заміни рядків має такий вигляд:
```

2022-02-04 13:52 UTC, undead404 commented on files/uk/web/javascript/reference/global_objects/string/substring/index.md
> +Весь код вище служить прикладом роботи з підрядками. В разі потреби замінити підрядок, в більшості випадків краще використати {{jsxref("String.prototype.replace()")}}.
```suggestion
Весь код вище служить прикладом роботи з підрядками. В разі потреби замінити підрядок, в більшості випадків, краще використати {{jsxref("String.prototype.replace()")}}.
```

2022-02-11 12:17 UTC, Aenqau requested changes

2022-02-11 12:17 UTC, Aenqau commented on files/uk/web/javascript/reference/global_objects/string/substring/index.md
> +Будь-яке значення аргументу, мене за `0` чи більше за `stringName.length` опрацьовується так, як наче воно дорівнювало `0` чи `stringName.length` відповідно.
Будь-яке значення аргументу, мене за `0`

Тебе за нуль??)

2022-02-11 12:17 UTC, Aenqau commented on files/uk/web/javascript/reference/global_objects/string/substring/index.md
> +Наступний приклад застосовує метод `substring()` з властивістю {{jsxref("String.length", "length")}} для вибирання останніх символів певного рядка. Ймовірно запам'ятати цей метод буде простіше, оскіл
Тут з логіки речення виходить ніби початковий та кінцевий індекси потрібно не просто знати, а саме так, як у попередніх прикладах. Можливо варто переформулювати

2022-02-11 18:52 UTC, AdriandeCita commented on files/uk/web/javascript/reference/global_objects/string/substring/index.md
> +Метод **`substring()`** повертає частину рядка `string` між вказаними індексами початку і кінця, або до кінця рядка — якщо кінцевий індекс не вказано.
глибоко... Зазвичай назви змінних обгортаються в код, тому такої проблеми виникати не повинно. Втім, ти правий, "та" тут дає краще чергування голосних-приголосних

2022-02-11 18:55 UTC, AdriandeCita commented on files/uk/web/javascript/reference/global_objects/string/substring/index.md
> +Наступний приклад застосовує метод `substring()` з властивістю {{jsxref("String.length", "length")}} для вибирання останніх символів певного рядка. Ймовірно запам'ятати цей метод буде простіше, оскіл
тонко, але влучно, справді гарна заміна

2022-02-11 19:20 UTC, undead404 approved these changes

2022-02-11 19:50 UTC, merged