translation(HTML): web/html/element/area
webdoky/content pull request #2347
Opened 2023-10-05 10:08 UTC by undead404

Оригінальний вміст: [&lt;area>: The Image Map Area element@MDN](https://developer.mozilla.org/en-us/docs/Web/HTML/Element/area), [сирці &lt;area>: The Image Map Area element@GitHub](https://github.com/mdn/content/blob/main/files/en-us/web/html/element/area/index.md)

2023-11-09 18:53 UTC, AdriandeCita commented on files/uk/web/html/element/area/index.md
> +    Усталений взаємозв'язок, якщо не задано іншого, – пустий. Цей атрибут слід використовувати лише тоді, коли присутній атрибут [`href`](#href).
Неузгоджено з контекстом, треба або в обох випадках перекладати "relationship" як "відношення", або як "взаємозв'язок" 
```suggestion
    Усталене відношення, якщо не задано іншого, – пусте. Цей атрибут слід використовувати лише тоді, коли присутній атрибут [`href`](#href).
```

2023-11-09 18:56 UTC, AdriandeCita requested changes
Дрібничка, плюс в оригіналі є пара оновлень

2023-11-09 20:43 UTC, undead404 commented
Внесено, оновлено

2023-12-08 12:28 UTC, AdriandeCita approved these changes

2023-12-08 12:28 UTC, merged