translation(CSS): web/css/pseudo-classes
webdoky/content pull request #2354
Opened 2023-10-11 17:39 UTC by undead404

Оригінальний вміст: [Pseudo-classes@MDN](https://developer.mozilla.org/en-us/docs/Web/CSS/Pseudo-classes), [сирці Pseudo-classes@GitHub](https://github.com/mdn/content/blob/main/files/en-us/web/css/pseudo-classes/index.md)

2023-11-09 18:31 UTC, AdriandeCita commented on files/uk/web/css/pseudo-classes/index.md
> +Псевдокласи дають змогу застосовувати стиль до елемента не лише на основі вмісту дерева документа, а й також на основі зовнішніх чинників, наприклад, історії навігатора (наприклад, {{CSSxRef(":visite
Там далі у всіх дужках "наприклад" повторюється. Кожна дужка - то окремий контекст, але оце загальне "наприклад" я б замінив
```suggestion
Псевдокласи дають змогу застосовувати стиль до елемента не лише на основі вмісту дерева документа, а й також на основі зовнішніх чинників, як от: історії навігатора (наприклад, {{CSSxRef(":visited")}}), стану його вмісту (наприклад, {{CSSxRef(":checked")}} для деяких елементів форми) або положення миші (наприклад, {{CSSxRef(":hover")}}, який дозволяє визначити, чи перебуває миша над елементом, чи ні).
```

2023-11-09 18:35 UTC, AdriandeCita commented on files/uk/web/css/pseudo-classes/index.md
> +  - : Applies to elements with range limitations. For example, a slider control when the selected value is outside the allowed range.
```suggestion
```

2023-11-09 18:46 UTC, AdriandeCita requested changes
пара дрібниць

2023-11-23 16:03 UTC, undead404 commented on files/uk/web/css/pseudo-classes/index.md
> +## Псевдокласи полів
```suggestion
  - : Дає збіг з елементами, що наразі перебувають у стані картинки-в-картинці.

## Псевдокласи полів
```

2023-11-23 16:04 UTC, undead404 commented on files/uk/web/css/pseudo-classes/index.md
> +- {{CSSxRef(":enabled")}}
```suggestion
  - : Дає збіг з елементами {{htmlelement("input")}}, які автозаповнив браузер.
- {{CSSxRef(":enabled")}}
```

2023-11-23 16:06 UTC, undead404 commented on files/uk/web/css/pseudo-classes/index.md
> +  - : Дає збіг з елементами {{htmlelement("input")}}, які автозаповнив браузер.
```suggestion
  - : Дає збіг з елементами {{htmlelement("input")}}, які автоматично заповнив браузер.
```

2024-01-13 17:59 UTC, AdriandeCita approved these changes

2024-01-13 18:10 UTC, AdriandeCita approved these changes

2024-01-13 18:10 UTC, AdriandeCita requested changes
Є свіжі змістовні зміни

2024-02-15 13:15 UTC, undead404 reviewed
Still relevant?

2024-07-19 13:43 UTC, undead404 reviewed
Relevant?

2024-12-27 16:21 UTC, AdriandeCita approved these changes

2024-12-27 22:03 UTC, AdriandeCita approved these changes

2024-12-27 22:04 UTC, merged