translation(CSS): web/css/flex-grow
webdoky/content pull request #2366
Opened 2023-10-16 11:42 UTC by undead404

Оригінальний вміст: [flex-grow@MDN](https://developer.mozilla.org/en-us/docs/Web/CSS/flex-grow), [сирці flex-grow@GitHub](https://github.com/mdn/content/blob/main/files/en-us/web/css/flex-grow/index.md)

2023-11-06 14:20 UTC, AdriandeCita commented on files/uk/web/css/flex-grow/index.md
> +In this example, there is a total of 8 growth factors distributed among the 6 flex items, meaning each growth factor is 12.5% of the remaining space.
```suggestion
```

2023-11-06 14:20 UTC, AdriandeCita commented on files/uk/web/css/flex-grow/index.md
> +
```suggestion
```

2023-11-06 14:21 UTC, AdriandeCita commented on files/uk/web/css/flex-grow/index.md
> +When the six flex items are distributed along the container's main axis, if the sum of the main content of those flex items is less than the size of the container's main axis, the extra space is dist
```suggestion
```

2023-11-06 14:21 UTC, AdriandeCita commented on files/uk/web/css/flex-grow/index.md
> +
```suggestion
```

2023-11-06 14:30 UTC, AdriandeCita requested changes
пара дрібничок + там здається якісь свіжі оновлення в оригіналі є (не дивився, наскільки вони актуальні)

2023-11-06 15:06 UTC, undead404 commented
Оновлення нікчемне

2023-11-07 20:28 UTC, AdriandeCita approved these changes

2023-11-07 20:28 UTC, merged