translation(CSS): web/css/css_media_queries
webdoky/content pull request #2373
Opened 2023-10-17 12:18 UTC by undead404

Оригінальний вміст: [CSS media queries@MDN](https://developer.mozilla.org/en-us/docs/Web/CSS/CSS_media_queries), [сирці CSS media queries@GitHub](https://github.com/mdn/content/blob/main/files/en-us/web/css/css_media_queries/index.md)

2023-11-06 13:12 UTC, AdriandeCita commented on files/uk/web/css/css_media_queries/index.md
> +- [Testing media queries programmatically](/uk/docs/Web/CSS/CSS_media_queries/Testing_media_queries)
```suggestion
```

2023-11-06 13:13 UTC, AdriandeCita commented on files/uk/web/css/css_media_queries/media-queries.svg
Локалізовані картинки! :heart_eyes:

2023-11-06 13:14 UTC, AdriandeCita requested changes
дрібничка по тексту

2023-11-06 13:41 UTC, undead404 commented on files/uk/web/css/css_media_queries/media-queries.svg
Локалізувати SVG кожен дурень зможе)

2023-11-06 13:41 UTC, undead404 commented on files/uk/web/css/css_media_queries/media-queries.svg
Ну ок, не кожен, довелося трохи погратися з відступами

2023-11-07 20:27 UTC, AdriandeCita approved these changes

2023-11-07 20:27 UTC, merged