translation(CSS): web/css/transform-function
webdoky/content pull request #2377
Opened 2023-10-17 14:01 UTC by undead404

Оригінальний вміст: [&lt;transform-function>@MDN](https://developer.mozilla.org/en-us/docs/Web/CSS/transform-function), [сирці &lt;transform-function>@GitHub](https://github.com/mdn/content/blob/main/files/en-us/web/css/transform-function/index.md)

2023-11-06 12:40 UTC, AdriandeCita commented on files/uk/web/css/transform-function/index.md
> +Various coordinate models can be used to describe an HTML element's size and shape, as well as any transformations applied to it. The most common is the [Cartesian coordinate system](https://en.wikip
```suggestion
```

2023-11-06 12:48 UTC, AdriandeCita commented on files/uk/web/css/transform-function/index.md
> +Проте одне важливе перетворення не є лінійним, а отже – повинно мати особливий випадок при застосуванні такого запису: переклад. Вектор перекладу `(tx, ty)` повинен бути виражений окремо, як два дода
Взагалі можна було використати "переміщення", ми колись навіть сперечалися на цю тему. Але якщо вже мова зайшла про вживання терміну "переклад" як "переміщення", то краще вживати "перекладання", менше шансів сплутати з мовним "перекладом"
```suggestion
Проте одне важливе перетворення не є лінійним, а отже – повинно мати особливий випадок при застосуванні такого запису: перекладання. Вектор перекладання `(tx, ty)` повинен бути виражений окремо, як два додаткові параметри.
```

2023-11-06 12:49 UTC, AdriandeCita commented on files/uk/web/css/transform-function/index.md
> +Наступний приклад містить тривимірний куб, створений з елементів DOM і перетворень, а також меню вибору, яке дає змогу вибрати різні функції перетворення для перетворення куба, щоб порівняти вплив рі
Пропоную прибрати одне "перетворення" для кращої прочитності
```suggestion
Наступний приклад містить тривимірний куб, створений з елементів DOM і перетворень, а також меню вибору, яке дає змогу вибрати різні перетворення для перетворення куба, щоб порівняти вплив різних типів.
```

2023-11-06 13:02 UTC, AdriandeCita requested changes
Декілька зауважень. Стосовно "переклад-перекладання" я б розглянув або заміну на "переміщення", або хоча б на "перекладання", якщо хочеться вжити буквально ближчий варіант

2023-11-06 13:40 UTC, undead404 commented
переміщення то лише вузький випадок перекладання(

2023-11-07 20:26 UTC, AdriandeCita approved these changes

2023-11-07 20:26 UTC, merged