translation(CSS): web/css/_colon_required
webdoky/content pull request #2444
Opened 2023-10-24 09:55 UTC by undead404

Оригінальний вміст: [:required@MDN](https://developer.mozilla.org/en-us/docs/Web/CSS/:required), [сирці :required@GitHub](https://github.com/mdn/content/blob/main/files/en-us/web/css/_colon_required/index.md)

2023-10-24 12:39 UTC, KlashReik requested changes

2023-10-24 12:39 UTC, KlashReik commented on files/uk/web/css/_colon_required/index.md
> +Якщо форма також містить [необов'язкові](/uk/docs/Web/CSS/:optional) поля, то обов'язкові поля повинні бути візуально позначені, у спосіб, який не ґрунтує передачу значення лише на кольорі. Зазвичай
```suggestion
Якщо форма також містить [необов'язкові](/uk/docs/Web/CSS/:optional) поля, то обов'язкові поля повинні бути візуально позначені, у спосіб, який не орієнтується на передачу значення лише кольором. Зазвичай використовують описовий текст чи піктограму.
```

2023-10-26 08:13 UTC, AdriandeCita commented on files/uk/web/css/_colon_required/index.md
> +Якщо форма також містить [необов'язкові](/uk/docs/Web/CSS/:optional) поля, то обов'язкові поля повинні бути візуально позначені, у спосіб, який не ґрунтує передачу значення лише на кольорі. Зазвичай
в оригіналі "to rely", це радше "покладатися, засновуватися". Або ґрунтуватися.
Якщо хочеться вжити щось більш традиційно вживане - то краще так
```suggestion
Якщо форма також містить [необов'язкові](/uk/docs/Web/CSS/:optional) поля, то обов'язкові поля повинні бути візуально позначені, у спосіб, який не покладається лише на колір для передачі змісту. Зазвичай використовують описовий текст чи піктограму.
```

2023-11-01 07:57 UTC, KlashReik approved these changes

2023-11-02 20:17 UTC, merged