translation(JS): web/javascript/reference/global_objects/set/difference
webdoky/content pull request #2484
Opened 2023-11-10 09:41 UTC by undead404

Оригінальний вміст: [descent@MDN](https://developer.mozilla.org/en-us/docs/Web/JavaScript/Reference/Global_Objects/Set/difference), [сирці descent@GitHub](https://github.com/mdn/content/blob/main/files/en-us/web/javascript/reference/global_objects/set/difference/index.md)

2023-11-23 12:42 UTC, undead404 commented on files/uk/web/javascript/reference/global_objects/set/difference/index.md
> +- Якщо число елементів у `this` перевищує `other.size`, то він ітерує по `other`, викликаючи її метод `keys()`, і конструює нову множину з елементів `this`, не помічених у `other`.
```suggestion
- Якщо число елементів у `this` перевищує `other.size`, то він ітерує по `other`, викликаючи її метод `keys()`, і конструює нову множину з елементів `this`, не помічених в `other`.
```

2024-01-06 21:40 UTC, AdriandeCita approved these changes

2024-01-06 21:42 UTC, AdriandeCita requested changes
Є свіжі зміни

2024-01-13 18:00 UTC, AdriandeCita approved these changes

2024-01-13 18:08 UTC, merged