translation(CSS): web/css/@starting-style
webdoky/content pull request #2529
Opened 2023-11-23 08:10 UTC by undead404

Оригінальний вміст: [@starting-style@MDN](https://developer.mozilla.org/en-us/docs/Web/CSS/@starting-style), [сирці @starting-style@GitHub](https://github.com/mdn/content/blob/main/files/en-us/web/css/@starting-style/index.md)

2024-01-06 23:39 UTC, AdriandeCita commented on files/uk/web/css/@starting-style/index.md
> +Коли клацають кнопка закриття, виконується функція, яка додає клас `fade-out` до `<div>`. Додавання класу викликає анімацію виходу, задану для цього класу. Після тайм-ауту вилучається `<div>` з DOM (
Не певен, що це взагалі звідси
```suggestion
```

2024-01-06 23:39 UTC, AdriandeCita commented on files/uk/web/css/@starting-style/index.md
> +
```suggestion
```

2024-01-06 23:42 UTC, AdriandeCita commented on files/uk/web/css/@starting-style/index.md
> +When the "Create new column" button is clicked, the `createColumn()` function is called. This creates a {{htmlelement("div")}} element with a randomly generated background color and a {{htmlelement("
```suggestion
Коли клацають кнопку  "Створити нову колонку", викликається функція `createColumn()`. Це породжує новий елемент {{htmlelement("div")}} з випадково згенерованим кольором тла і елементом {{htmlelement("button")}} для закриття цього `<div>`. Потім вона додає `<button>` до `<div>`, а `<div>` — до контейнера `<section>`.
```

2024-01-06 23:44 UTC, AdriandeCita requested changes
Пара дрібниць

2024-01-07 16:10 UTC, undead404 commented on files/uk/web/css/@starting-style/index.md
> +Коли клацають кнопку  "Створити нову колонку", викликається функція `createColumn()`. Це породжує новий елемент {{htmlelement("div")}} з випадково згенерованим кольором тла і елементом {{htmlelement(
```suggestion
Коли клацають кнопку "Створити нову колонку", викликається функція `createColumn()`. Це породжує новий елемент {{htmlelement("div")}} з випадково згенерованим кольором тла й елементом {{htmlelement("button")}} для закриття цього `<div>`. Потім вона додає `<button>` до `<div>`, а `<div>` — до контейнера `<section>`.
```

2024-01-13 18:02 UTC, AdriandeCita approved these changes

2024-01-13 18:12 UTC, merged