update(HTML): web/html/element/form
webdoky/content pull request #2582
Opened 2023-12-05 09:20 UTC by undead404

2024-01-06 18:27 UTC, AdriandeCita commented on files/uk/web/html/element/form/index.md
> +- : Контролює те, чи додаються великі літери до тексту, введеного у поля вводу, а також, якщо так, то яким чином. Шукайте більше інформації на сторінці глобального атрибута [`autocapitalize`](/uk/doc
```suggestion
- : Контролює те, чи додаються великі літери до тексту, введеного у поля вводу, а також, якщо так — то яким чином. Шукайте більше інформації на сторінці глобального атрибута [`autocapitalize`](/uk/docs/Web/HTML/Global_attributes/autocapitalize).
```

2024-01-06 18:27 UTC, AdriandeCita commented on files/uk/web/html/element/form/index.md
> -  - : Нестандартний атрибут, що використовується iOS Safari для контролю того, як текстові елементи форми повинні автоматично отримувати великі літери. Атрибути `autocapitalize` на елементах форми ві
Зайшов подивитися сумісність - і чомусь саме Сафарі його не підтримує :D

2024-01-06 18:29 UTC, AdriandeCita requested changes
дрібничка в пунктуації

2024-01-09 11:17 UTC, Aenqau approved these changes

2024-01-10 09:24 UTC, AdriandeCita approved these changes

2024-01-10 09:31 UTC, merged