translation(JS): web/javascript/reference/regular_expressions/charact…
webdoky/content pull request #2602
Opened 2023-12-12 17:22 UTC by undead404

…er_escape

2023-12-12 17:26 UTC, undead404 commented on files/uk/web/javascript/reference/regular_expressions/character_escape/index.md
> +  - : Представляє сам символ. Наприклад, `\\` представляє зворотню скісну риску, а `\(` – ліву дужку. Ці символи в регулярних виразах є [синтаксичними символами](/uk/docs/Web/JavaScript/Reference/Reg
```suggestion
  - : Представляє сам символ. Наприклад, `\\` представляє зворотну скісну риску, а `\(` – ліву дужку. Ці символи в регулярних виразах є [синтаксичними символами](/uk/docs/Web/JavaScript/Reference/Regular_expressions/Literal_character) (наприклад, `/` є межею регулярного виразу), тому вони потребують екранування, якщо не знаходяться у [класі символів](/uk/docs/Web/JavaScript/Reference/Regular_expressions/Character_class).
```

2023-12-12 17:26 UTC, undead404 commented on files/uk/web/javascript/reference/regular_expressions/character_escape/index.md
> +У [режимі без урахування Unicode](/uk/docs/Web/JavaScript/Reference/Global_Objects/RegExp/unicode#rezhym-z-ukrakhuvanniam-unicode), екранування символів, що не належить до перелічених вище, стає _екр
```suggestion
У [режимі без урахування Unicode](/uk/docs/Web/JavaScript/Reference/Global_Objects/RegExp/unicode#rezhym-z-ukrakhuvanniam-unicode), екранування символів, що не належить до перелічених вище, стає _екрануванням ідентичності_: воно представляє символ, що йде після зворотної скісної риски. Наприклад, `\a` представляє символ `a`. Ця поведінка обмежує можливість введення нових екранувань символів без порушення сумісності з попередніми версіями, тому вона заборонена у режимі з урахуванням Unicode.
```

2023-12-12 17:26 UTC, undead404 commented on files/uk/web/javascript/reference/regular_expressions/character_escape/index.md
> +У режимі без урахування Unicode екранування символів у межах [класів символів](/uk/docs/Web/JavaScript/Reference/Regular_expressions/Character_class) у формі `\cX`, де `X` – це число або `_`, кодують
```suggestion
У режимі без урахування Unicode екранування символів у межах [класів символів](/uk/docs/Web/JavaScript/Reference/Regular_expressions/Character_class) у формі `\cX`, де `X` – це число або `_`, кодуються так само, як і ті, що містять літери {{Glossary("ASCII")}}: `\c0` – те саме, що й `\cP`, якщо остачу від ділення на 32. Крім того, якщо форма `\cX` зустрічається де завгодно, де `X` не є одним із розпізнаних символів, то зворотна скісна риска вважається буквальним символом. Ці форми синтаксису також нерекомендовані.
```

2024-01-06 21:04 UTC, AdriandeCita commented on files/uk/web/javascript/reference/regular_expressions/character_escape/index.md
> +У режимі без урахування Unicode екранування символів у межах [класів символів](/uk/docs/Web/JavaScript/Reference/Regular_expressions/Character_class) у формі `\cX`, де `X` – це число або `_`, кодують
```suggestion
У режимі без урахування Unicode екранування символів у межах [класів символів](/uk/docs/Web/JavaScript/Reference/Regular_expressions/Character_class) у формі `\cX`, де `X` – це число або `_`, кодуються так само, як і ті, що містять літери {{Glossary("ASCII")}}: `\c0` – те саме, що й `\cP`, якщо взято остачу від ділення на 32. Крім того, якщо форма `\cX` зустрічається де завгодно, де `X` не є одним із розпізнаних символів, то зворотна скісна риска вважається буквальним символом. Ці форми синтаксису також нерекомендовані.
```

2024-01-06 21:05 UTC, AdriandeCita requested changes
дрібничка

2024-01-08 11:05 UTC, AdriandeCita approved these changes

2024-01-08 11:07 UTC, merged