translation(CSS): web/css/appearance
webdoky/content pull request #2603
Opened 2023-12-13 09:16 UTC by undead404

2023-12-13 09:18 UTC, undead404 commented on files/uk/web/css/appearance/index.md
> +    Клюочві слова, що рівносильні `auto` заради збереження сумісності зі старими браузерами.
```suggestion
    Ключові слова, що рівносильні `auto` заради збереження сумісності зі старими браузерами.
```

2024-01-06 21:06 UTC, AdriandeCita commented on files/uk/web/css/appearance/index.md
> +> **Примітка:** За бажання використовувати цю властивість на вебсайтах, слід дуже ретельно її перевірити. Попри те, що вона підтримується в більшості сучасних браузерів, її реалізація відрізняється.
```suggestion
> **Примітка:** За бажання використовувати цю властивість на вебсайтах, слід дуже ретельно її перевірити. Попри те, що вона підтримується в більшості сучасних браузерів, її реалізація відрізняється. У старих браузерах навіть ключове слово `none` не має однакової дії на всі елементи форми в різних браузерах, а деякі взагалі не підтримують його. В найновіших браузерах різниці менше.
```

2024-01-06 21:10 UTC, AdriandeCita commented on files/uk/web/css/appearance/index.md
> +The appearance of the checkbox is changed to a circle, and the select element shows how to remove the arrow indicating that the list can be expanded.
```suggestion
Зовнішній вигляд галочки змінено на круг, а елемент вибору ілюструє, як можна прибрати стрілочку, яка позначає, що список можна розгортати.
```

2024-01-06 21:11 UTC, AdriandeCita requested changes
пара зауважень

2024-01-08 11:05 UTC, AdriandeCita approved these changes

2024-01-08 11:07 UTC, merged