translation(CSS): web/css/transition-behavior
webdoky/content pull request #2614
Opened 2023-12-14 11:27 UTC by undead404

2024-01-06 20:40 UTC, AdriandeCita commented on files/uk/web/css/transition-behavior/index.md
> +У зразку коду вище властивість `transition` додана двічі. Перший раз не включає значення `allow-discrete` – це забезпечує кросбраузерну підтримку, забезпечуючи перехід інших властивостей картки в бра
забезпечує забезпечуючи
```suggestion
У зразку коду вище властивість `transition` додана двічі. Перший раз не включає значення `allow-discrete` – це надає кросбраузерну підтримку, забезпечуючи перехід інших властивостей картки в браузерах, які не підтримують `transition-behavior`.
```

2024-01-06 20:50 UTC, AdriandeCita commented on files/uk/web/css/transition-behavior/index.md
> +Значення `transition-behavior` може бути включено як частина скороченого оголошення {{cssxref("transition")}}. Коли воно включене в скорочення, при використанні або дефолтуванні всіх властивостей, зн
```suggestion
Значення `transition-behavior` може бути включено як частина скороченого оголошення {{cssxref("transition")}}. Коли воно включене в скорочення, при використанні або усталенні до всіх властивостей, значення `allow-discrete` не впливає на звичайні анімовані властивості. Наступний CSS рівносильний розгорнутим оголошенням вище:
```

2024-01-06 21:02 UTC, AdriandeCita commented on uk_spelling_additions.txt
> +дефолтуванні
Не певен, чи є сенс, якщо ми вже використовуємо термін "усталений". Та й навряд чи термін "дефолтування" звучить зрозуміліше, аніж "усталення")
```suggestion
```

2024-01-06 21:03 UTC, AdriandeCita requested changes
пара нюансів

2024-01-07 15:39 UTC, undead404 commented on files/uk/web/css/transition-behavior/index.md
> +Значення `transition-behavior` може бути включено як частина скороченого оголошення {{cssxref("transition")}}. Коли воно включене в скорочення, при використанні або дефолтуванні всіх властивостей, зн
Тут складна штука... Мова про те, що коли в скороченні властивості-складові не мають заданого значення, їм даються усталені значення

Це точно перекладається саме так?

2024-01-13 17:58 UTC, AdriandeCita commented on files/uk/web/css/transition-behavior/index.md
> +Значення `transition-behavior` може бути включено як частина скороченого оголошення {{cssxref("transition")}}. Коли воно включене в скорочення, при використанні або дефолтуванні всіх властивостей, зн
Що ж, через тиждень я зрозумів, що вони хотіли сказати)

```suggestion
Значення `transition-behavior` може бути включено як частина скороченого оголошення {{cssxref("transition")}}. Коли воно включене в скорочення, при застосуванні його до властивостей (явно, або усталено — до всіх), значення `allow-discrete` не впливає на звичайні анімовані властивості. Наступний CSS рівносильний розгорнутим оголошенням вище:
```

2024-02-15 13:15 UTC, undead404 reviewed
Still relevant?

2024-07-19 13:43 UTC, undead404 reviewed
Relevant?

2024-12-27 10:09 UTC, AdriandeCita approved these changes

2024-12-27 11:13 UTC, merged