update(CSS): web/css/css_cascading_variables
webdoky/content pull request #2624
Opened 2023-12-19 21:35 UTC by undead404

2023-12-19 21:37 UTC, undead404 commented on files/uk/web/css/css_cascading_variables/index.md
> +При роботі з CSS нерідко доводиться багаторазово використовувати одні й ті самі в межах одного проєкту значення, наприклад, ширини, що добре підходять для макету, або набір кольорів колірної схеми.
```suggestion
При роботі з CSS нерідко доводиться багаторазово використовувати одні й ті самі в межах одного проєкту значення, наприклад, ширини, що добре підходять для макета, або набір кольорів колірної схеми.
```

2024-01-06 17:48 UTC, AdriandeCita commented on files/uk/web/css/css_cascading_variables/index.md
> +При роботі з CSS нерідко доводиться багаторазово використовувати одні й ті самі в межах одного проєкту значення, наприклад, ширини, що добре підходять для макета, або набір кольорів колірної схеми.
я розумію, що ти хотів сказати, але воно так не дуже читається, мені довелося декілька разів перечитати, аби зрозуміти, що там нічого не пропущено.
Пропоную перефразувати, це буде трохи далі від оригіналу, але зрозуміліше
```suggestion
При роботі з CSS нерідко доводиться багаторазово використовувати в межах одного проєкту одні й ті самі значення, наприклад, ширини, що добре підходять для макета, або набір кольорів колірної схеми.
```

2024-01-06 17:54 UTC, AdriandeCita commented on files/uk/web/css/css_cascading_variables/index.md
> +У цих колірних зразках значення {{cssxref("background-color")}} задано за допомогою функції {{cssxref("color_value/hsl", "hsl()")}} {{cssxref("&lt;color&gt;")}} як `hsl(var(--hue) 50% 50%)`.
Може здатися, що  <color> - це частина функції, хоча це мається на увазі саме тип функції
```suggestion
У цих колірних зразках значення {{cssxref("background-color")}} задано за допомогою функції {{cssxref("&lt;color&gt;", "кольору")}} {{cssxref("color_value/hsl", "hsl()")}} як `hsl(var(--hue) 50% 50%)`.
```

2024-01-06 17:56 UTC, AdriandeCita requested changes
декілька зауважень

2024-01-06 18:51 UTC, AdriandeCita approved these changes

2024-01-06 18:53 UTC, merged