update(CSS): web/css/css_flexible_box_layout/basic_concepts_of_flexbox
webdoky/content pull request #2638
Opened 2023-12-27 10:49 UTC by undead404

2023-12-27 10:51 UTC, undead404 commented on files/uk/web/css/css_flexible_box_layout/basic_concepts_of_flexbox/index.md
> +Як і в випадку всіх інших властивостей CSS, визначені певні початкові значення, тож вміст нового гнучкого контейнера поводитиметься наступним чином:
```suggestion
Як і в випадку всіх інших властивостей CSS, визначені певні початкові значення, тож вміст нового гнучкого контейнера поводитиметься так:
```

2024-01-05 06:54 UTC, AdriandeCita commented on files/uk/web/css/css_flexible_box_layout/basic_concepts_of_flexbox/index.md
> +Область документа, скомпонована за допомогою флексбокса, називається **гнучким контейнером**. Щоб створити гнучкий контейнер, слід вказати для контейнера області властивість {{cssxref("display")}} зі
тут потрібен явний розділювач, бо `і` сполучає не просто однорідні члени речення, а цілі підрядні конструкції
```suggestion
Область документа, скомпонована за допомогою флексбокса, називається **гнучким контейнером**. Щоб створити гнучкий контейнер, слід вказати для контейнера області властивість {{cssxref("display")}} зі значенням `flex`. Коли це зроблено, то безпосередні нащадки такого контейнера стають **гнучкими елементами**. Контролювати, чи відображається сам контейнер в контексті рядка, чи в контексті блокового контексту форматування, можна за допомогою значень `inline flex` або `inline-flex` для рядкових гнучких контейнерів, і `block flex` або `flex` для гнучких контейнерів блокового рівня.
```

2024-01-05 06:58 UTC, AdriandeCita commented on files/uk/web/css/css_flexible_box_layout/basic_concepts_of_flexbox/index.md
> +Як і в випадку всіх інших властивостей CSS, визначені певні початкові значення, тож вміст нового гнучкого контейнера поводитиметься так:
Звучить неузгоджено, пропоную трохи уточнити
```suggestion
Як і в випадку всіх інших властивостей CSS, існують певні визначені початкові значення, тож вміст нового гнучкого контейнера поводитиметься так:
```

2024-01-05 06:58 UTC, AdriandeCita requested changes
пара дрібниць

2024-01-05 16:07 UTC, Aenqau approved these changes

2024-01-05 16:07 UTC, Aenqau commented on files/uk/web/css/css_flexible_box_layout/basic_concepts_of_flexbox/index.md
> +Область документа, скомпонована за допомогою флексбокса, називається **гнучким контейнером**. Щоб створити гнучкий контейнер, слід вказати для контейнера області властивість {{cssxref("display")}} зі
```suggestion
Область документа, скомпонована за допомогою флексбокса, називається **гнучким контейнером**. Щоб створити гнучкий контейнер, слід вказати для контейнера області властивість {{cssxref("display")}} зі значенням `flex`. Коли це зроблено, то безпосередні нащадки такого контейнера стають **гнучкими елементами**. Контролювати, чи відображається сам контейнер в контексті рядка, або ж в контексті блокового контексту форматування, можна за допомогою значень `inline flex` або `inline-flex` для рядкових гнучких контейнерів, і `block flex` або `flex` для гнучких контейнерів блокового рівня.
```

2024-01-05 16:14 UTC, Aenqau commented on files/uk/web/css/css_flexible_box_layout/basic_concepts_of_flexbox/index.md
> +Область документа, скомпонована за допомогою флексбокса, називається **гнучким контейнером**. Щоб створити гнучкий контейнер, слід вказати для контейнера області властивість {{cssxref("display")}} зі
В даному випадку коли я прочитав вперше, то подумав, що перше "чи" відноситься до слова "контролювати", тому запропонував "розбити" повторення

2024-01-06 17:56 UTC, merged