update(JS): web/javascript/reference/global_objects/array/index.md
webdoky/content pull request #264
Opened 2022-02-07 21:31 UTC by undead404

Original content: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array

Changes:
* https://github.com/mdn/content/commit/e752a8fe731fbdb9061e39a6e2b797a7ccb7e2b5
* https://github.com/mdn/content/commit/99479d5e8ac0b018240727e398f46ae465b901d6
* https://github.com/mdn/content/commit/d304a553b8c05629376dfc8b593364cd3128b07d
* https://github.com/mdn/content/commit/80ac011bc87a5d72cf51659998a9b22a1a2536c5

2022-02-08 22:05 UTC, AdriandeCita commented on files/uk/web/javascript/reference/global_objects/array/index.md
> +Клас **`Array`** (масив) у JavaScript - це глобальний об'єкт, що використовується для створення масивів, які є високорівневими об'єктами, подібними до списків.
Є сенс повторювати це двічі, якщо у нас уже в заголовку це є? Чи може краще з заголовку прибрати?
```suggestion
Клас **`Array`** у JavaScript - це глобальний об'єкт, що використовується для створення масивів, які є високорівневими об'єктами, подібними до списків.
```

2022-02-08 22:10 UTC, AdriandeCita commented on files/uk/web/javascript/reference/global_objects/array/index.md
> +  - : Повертає новий масив шляхом з'єднання даного масиву з іншим масивом чи значенням (або масивами та значеннями).
```suggestion
  - : Повертає новий масив, утворений шляхом з'єднання даного масиву з іншим масивом чи значенням (або масивами та значеннями).
```

2022-02-08 22:11 UTC, AdriandeCita requested changes
пара дрібниць

2022-02-11 19:25 UTC, undead404 commented on files/uk/web/javascript/reference/global_objects/array/index.md
> +Клас **`Array`** (масив) у JavaScript - це глобальний об'єкт, що використовується для створення масивів, які є високорівневими об'єктами, подібними до списків.
Я іноді так "уважно" читаю, що заголовка взагалі не помічаю, а тут починається текст. Тому я б лишив як є

2022-02-18 21:27 UTC, merged