update(JS): web/javascript/reference/global_objects/array/map/index.md
webdoky/content pull request #267
Opened 2022-02-07 22:05 UTC by undead404

Original content: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/map

Changes:
* https://github.com/mdn/content/commit/3d491ed7bf4ef118bd6db845d76f9cf0ed335b66
* https://github.com/mdn/content/commit/88508ebe5c73264be2cf03f1a949d8099d68d1ea

2022-02-08 21:54 UTC, AdriandeCita commented on files/uk/web/javascript/reference/global_objects/array/map/index.md
> +Метод **`map()`** (відобразити) **створює новий масив**, наповнений результатами виклику переданої функції на кожному з елементів початкового масиву.
Відображення сюди погано в'яжеться. Один із перекладів "map" в контексті математики - це перетворити, подібно до transform.
```suggestion
Метод **`map()`** (перетворити) **створює новий масив**, наповнений результатами виклику переданої функції на кожному з елементів початкового масиву.
```

2022-02-08 22:00 UTC, AdriandeCita commented on files/uk/web/javascript/reference/global_objects/array/map/index.md
> +Інакший варіант результату виклику методу `map` із функцією {{jsxref("parseInt")}} як аргументом має такий вигляд:
хмм, зустрічаю вже не перший раз, є принципова різниця?

2022-02-08 22:03 UTC, AdriandeCita commented on files/uk/web/javascript/reference/global_objects/array/map/index.md
> +Оскільки `map` будує новий масив, його застосування є шкідливою практикою у тих ситуаціях, коли повернений в результаті масив не використовується. Натомість краще використати {{jsxref("Array/forEach"
ми таки позбуваємося антипатерну?

2022-02-08 22:04 UTC, AdriandeCita requested changes
невеличке доповнення, і пара запитань

2022-02-11 19:33 UTC, undead404 commented on files/uk/web/javascript/reference/global_objects/array/map/index.md
> +Метод **`map()`** (відобразити) **створює новий масив**, наповнений результатами виклику переданої функції на кожному з елементів початкового масиву.
Я бачу в одному словнику переклад "перетворити", але тут мені такий варіант дуже не подобається, бо на мою думку, `map` саме відображає один масив на інший. @Aenqau @IhorHordiichuk @Maksym1910 думки?

2022-02-11 19:33 UTC, undead404 commented on files/uk/web/javascript/reference/global_objects/array/map/index.md
> +Оскільки `map` будує новий масив, його застосування є шкідливою практикою у тих ситуаціях, коли повернений в результаті масив не використовується. Натомість краще використати {{jsxref("Array/forEach"
Та мабуть, що ні, кидай suggestion на повернення

2022-02-18 21:28 UTC, AdriandeCita commented on files/uk/web/javascript/reference/global_objects/array/map/index.md
> +Оскільки `map` будує новий масив, його застосування є шкідливою практикою у тих ситуаціях, коли повернений в результаті масив не використовується. Натомість краще використати {{jsxref("Array/forEach"
```suggestion
Оскільки `map` будує новий масив, його застосування є антипатерном у тих ситуаціях, коли повернений в результаті масив не використовується. Натомість краще використати {{jsxref("Array/forEach", "forEach")}} чи
```

2022-02-18 21:33 UTC, AdriandeCita commented on files/uk/web/javascript/reference/global_objects/array/map/index.md
> +Метод **`map()`** (відобразити) **створює новий масив**, наповнений результатами виклику переданої функції на кожному з елементів початкового масиву.
ну, поки інших думок немає, то най буде))

2022-02-19 21:32 UTC, AdriandeCita approved these changes

2022-02-19 21:32 UTC, merged