translation(CSS): web/css/css_properties_and_values_api
webdoky/content pull request #2670
Opened 2024-01-09 07:09 UTC by undead404

2024-01-09 07:13 UTC, undead404 commented on files/uk/web/css/css_properties_and_values_api/index.md
> +API властивостей і значень CSS є частиною пакету API [Гудіні CSS](/uk/docs/Web/CSS/CSS_Houdini).
```suggestion
API властивостей і значень CSS є частиною пакета API [Гудіні CSS](/uk/docs/Web/CSS/CSS_Houdini).
```

2024-01-13 18:38 UTC, AdriandeCita approved these changes

2024-01-13 18:51 UTC, AdriandeCita requested changes
Схоже, є свіжі зміни

2024-02-15 13:16 UTC, undead404 reviewed
Still relevant?

2024-08-09 20:26 UTC, alinkedd reviewed
Relevant?

2024-11-03 16:59 UTC, undead404 commented
Зміни нікчемні

2024-12-27 10:20 UTC, AdriandeCita requested changes
дрібничка

2024-12-27 10:20 UTC, AdriandeCita commented on files/uk/web/css/css_properties_and_values_api/index.md
> +<div class="box"><p>Linear gradient with transition</p></div>
```suggestion
<div class="box"><p>Лінійний градієнт з переходом</p></div>
```

2024-12-27 16:20 UTC, AdriandeCita approved these changes

2024-12-27 18:28 UTC, merged