update(JS): web/javascript/reference/global_objects/array/foreach/index.md
webdoky/content pull request #268
Opened 2022-02-08 14:06 UTC by undead404

Original content: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/forEach

**Застереження**: я бачу, що на MDN на цій сторінці є зміни, комміти котрих до нас в трекер змін іще не потрапили.

2022-02-08 14:27 UTC, AdriandeCita commented
оу, 16 годин тому останній коміт... Є сенс оновити вебсайт?

2022-02-08 14:38 UTC, undead404 commented
@AdriandeCita коли буде щось злите – оновиш і повідомиш мені, я оновлю свої оновлення

2022-02-19 21:36 UTC, AdriandeCita commented on files/uk/web/javascript/reference/global_objects/array/foreach/index.md
> +// коментар: як можна побачити, пропущене значення між 3 та 7 не потрапило до функції зворотного виклику
Тут трохи зміст втрачається. Ідея прикладу - проілюструвати, що функція взагалі не викликається на порожніх значеннях.
```suggestion
// коментар: як можна побачити, на пропущеному між 3 та 7 значенні функція зворотного виклику не викликалась
```

2022-02-19 21:40 UTC, AdriandeCita requested changes
Залишив коментар щодо однієї дрібнички. Так то виглядає круто

2022-02-21 20:11 UTC, merged