translation(CSS): web/css/cascade
webdoky/content pull request #2701
Opened 2024-01-14 08:40 UTC by undead404

2024-02-15 13:34 UTC, undead404 reviewed
Still relevant?

2024-12-27 10:05 UTC, AdriandeCita requested changes
пара побажань

2024-12-27 16:20 UTC, AdriandeCita approved these changes

2024-12-27 18:41 UTC, undead404 commented
Потребує суттєвого додаткового розгляду

2024-12-27 22:02 UTC, AdriandeCita commented on files/uk/web/css/cascade/index.md
> +Presentational attributes cannot be declared `!important`.
```suggestion
Презентаційні атрибути не можна оголошувати важливими (`!important`).
```

2024-12-27 22:04 UTC, AdriandeCita requested changes
дрібничка

2025-01-05 13:23 UTC, AdriandeCita approved these changes

2025-01-05 14:37 UTC, undead404 commented
Потребує додаткової перевірки

2025-03-01 17:00 UTC, undead404 commented
Закрито на користь https://github.com/webdoky/content/pull/3909

2025-03-01 17:00 UTC, closed without merging