translation(CSS): web/css/@scope
webdoky/content pull request #2707
Opened 2024-01-14 13:32 UTC by undead404

2024-02-15 13:35 UTC, undead404 reviewed
Still relevant?

2024-12-27 08:55 UTC, AdriandeCita commented on files/uk/web/css/@scope/index.md
> +Складний вебдокумент може містити компоненти штибу колонтитулів, новинних статей, карт, медіаплеєрів, рекламних оголошень та іншого. Зі зростанням складності ефективне керування оформленням цих компо
```suggestion
Складний вебдокумент може містити компоненти штибу колонтитулів, новинних статей, карт, медіаплеєрів, рекламних оголошень та іншого. Зі зростанням складності ефективне керування оформленням цих компонентів стає все більшим клопотом, і ефективне обмеження стилів допомагає керувати цією складністю. Розгляньмо наступне дерево DOM:
```

2024-12-27 09:11 UTC, AdriandeCita requested changes
дрібничка

2024-12-27 10:08 UTC, AdriandeCita approved these changes

2024-12-27 11:06 UTC, merged