update(JS): javascript/reference/global_objects/promise/index.md
webdoky/content pull request #271
Opened 2022-02-09 12:06 UTC by undead404

Original content: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Promise

Зміни:
* https://github.com/mdn/content/commit/09bc26fb8264fff6396e75b45481187866cb9493
* https://github.com/mdn/content/commit/88508ebe5c73264be2cf03f1a949d8099d68d1ea

2022-02-19 15:12 UTC, undead404 commented
Перевірено 2022-02-19

2022-02-19 21:47 UTC, AdriandeCita commented on files/uk/web/javascript/reference/global_objects/promise/index.md
> +Стан, з яким завершується проміс, визначає результат, яким "залагоджується" наступний проміс у послідовності. "Вирішений " стан позначає успішне завершення промісу, натомість стан "відхилено" познача
думаю, принаймні один "натомість" тут зайвий.
```suggestion
Стан, з яким завершується проміс, визначає результат, яким "залагоджується" наступний проміс у послідовності. "Вирішений " стан позначає успішне завершення промісу, а стан "відхилено" — невдачу. Результат, повернутий кожним промісом у послідовності, передається далі до наступного `.then()`, натомість причина, з якої було відхилено якийсь із промісів, передається тільки до наступного обробника помилки у послідовності.
```

2022-02-19 21:52 UTC, AdriandeCita commented on files/uk/web/javascript/reference/global_objects/promise/index.md
> +<!-- окрема область тут -->
Можна щось із форматуванням зробити? Зараз ці коментарі не додають зрозумілості

2022-02-19 21:57 UTC, AdriandeCita requested changes
пара зауважень. Стосовно форматування - я раніше не дуже звертав увагу, але схоже, що ми могли його трохи попсувати. Можливо є сенс переглянути старші оновлення...

2022-02-21 20:14 UTC, AdriandeCita commented on files/uk/web/javascript/reference/global_objects/promise/index.md
> +  - : Повертає новий об'єкт типу `Promise`, який вирішується з переданим результатом. Якщо результат є then-спроможним (має метод `then` - "відтак"), то повернений в результаті проміс "прослідкує" за
:+1:

2022-02-21 20:18 UTC, AdriandeCita approved these changes

2022-02-21 20:21 UTC, AdriandeCita commented on files/uk/web/javascript/reference/global_objects/promise/index.md
> +> **Примітка:** Проміс вважається _settled — залагодженим_ якщо він або сповнений, або відхилений, але не в стані очікування. Також зустрічається термін _вирішений — resolved_ — це означає, що проміс
Це виглядає дрібницею, тому мержу одразу, але якщо є краща ідея - пінгуй

2022-02-21 20:22 UTC, merged