translation(CSS): web/css/css_functions/using_css_math_functions
webdoky/content pull request #2714
Opened 2024-01-16 08:33 UTC by undead404

2024-01-16 08:40 UTC, undead404 commented on files/uk/web/css/css_functions/using_css_math_functions/index.md
> +## `calc()` – базові математичні операції
```suggestion
В цілому розробники можуть скористатися поєднанням [більш ніж двох десятків математичних функцій CSS](/uk/docs/Web/CSS/CSS_Functions#matematychni-funktsii) у своїх списках стилів. У цьому посібнику вводяться чотири з найбільш поширених, а також складніші.

## `calc()` – базові математичні операції
```

2024-01-16 08:40 UTC, undead404 commented on files/uk/web/css/css_functions/using_css_math_functions/index.md
> +Є випадки, коли ми не хочемо, щоб значення властивості CSS перевищувало певне число. Скажімо, наприклад, хочемо, щоб ширина контейнера вмісту була меншою поміж "повної ширини нашого екрану" та "500 п
```suggestion
Є випадки, коли ми не хочемо, щоб значення властивості CSS перевищувало певне число. Скажімо, наприклад, хочемо, щоб ширина контейнера вмісту була меншою поміж "повної ширини нашого екрана" та "500 пікселів". У таких випадках можна скористатися математичною функцією CSS {{CSSxRef("min", "min()")}}.
```

2024-01-16 08:40 UTC, undead404 commented on files/uk/web/css/css_functions/using_css_math_functions/index.md
> +Аналогічно до `min()`, іноді ми не хочемо, щоб значення властивості CSS не досягало певного числа. Наприклад, можемо хотіти, щоб ширина контейнера вмісту була _більшим значенням_ серед "повної ширини
```suggestion
Аналогічно до `min()`, іноді ми не хочемо, щоб значення властивості CSS не досягало певного числа. Наприклад, можемо хотіти, щоб ширина контейнера вмісту була _більшим значенням_ серед "повної ширини нашого екрана" і "500 пікселів". У таких випадках можна скористатися математичною функцією CSS {{CSSxRef("max", "max()")}}.
```

2024-01-16 08:40 UTC, undead404 commented on files/uk/web/css/css_functions/using_css_math_functions/index.md
> +  - {{CSSxRef("acos", "acos()")}} – обчислює **тригоноетричний арккосинус** числа
```suggestion
  - {{CSSxRef("acos", "acos()")}} – обчислює **тригонометричний арккосинус** числа
```

2024-01-16 08:40 UTC, undead404 commented on files/uk/web/css/css_functions/using_css_math_functions/index.md
> +  - {{CSSxRef("atan", "atan()")}} – обчислює **тригоноетричний арктангенс** числа
```suggestion
  - {{CSSxRef("atan", "atan()")}} – обчислює **тригонометричний арктангенс** числа
```

2024-02-15 13:47 UTC, undead404 reviewed
Still relevant?

2024-12-26 16:23 UTC, AdriandeCita commented on files/uk/web/css/css_functions/using_css_math_functions/index.md
> +Аналогічно до `min()`, іноді ми не хочемо, щоб значення властивості CSS не досягало певного числа. Наприклад, можемо хотіти, щоб ширина контейнера вмісту була _більшим значенням_ серед "повної ширини
```suggestion
Аналогічно до `min()`, іноді ми не хочемо, щоб значення властивості CSS впало нижче певного числа. Наприклад, можемо хотіти, щоб ширина контейнера вмісту була _більшим значенням_ серед "повної ширини нашого екрана" і "500 пікселів". У таких випадках можна скористатися математичною функцією CSS {{CSSxRef("max", "max()")}}.
```

2024-12-26 16:28 UTC, AdriandeCita requested changes
дрібничка

2024-12-27 08:47 UTC, AdriandeCita approved these changes

2024-12-27 09:34 UTC, merged