translation(CSS): web/css/css_functions
webdoky/content pull request #2721
Opened 2024-01-16 13:00 UTC by undead404

2024-02-15 13:47 UTC, undead404 reviewed
Still relevant?

2024-12-26 16:12 UTC, AdriandeCita requested changes
кілька побажань

2024-12-26 16:12 UTC, AdriandeCita commented on files/uk/web/css/css_functions/index.md
> +  - : Визначає даний колір за його складовими світлості, інтенсивності, барви та альфа-каналу (прозорості).
```suggestion
  - : Визначає даний колір за його складовими світності, інтенсивності, барви та альфа-каналу (прозорості).
```

2024-12-26 16:12 UTC, AdriandeCita commented on files/uk/web/css/css_functions/index.md
> +  - : Визначає даний колір за його складовими світлості, відстані по осі A та відстані по осі B в колірному просторі LAB.
```suggestion
  - : Визначає даний колір за його складовими світності, відстаней по осях A та B в колірному просторі LAB.
```

2024-12-26 16:12 UTC, AdriandeCita commented on files/uk/web/css/css_functions/index.md
> +  - : Визначає даний колір за його складовими світлості, відстані по осі A та відстані по осі B в колірному просторі LAB, а також альфа-каналу (прозорості).
```suggestion
  - : Визначає даний колір за його складовими світності, відстаней по осях A та B в колірному просторі LAB, а також альфа-каналу (прозорості).
```

2024-12-27 08:47 UTC, AdriandeCita approved these changes

2024-12-27 10:55 UTC, undead404 commented
Потребує додаткового розгляду абзац про якірно-позиційні функції

2024-12-27 16:31 UTC, merged