translation(JS): web/javascript/reference/global_objects/set/symmetricdifference
webdoky/content pull request #2723
Opened 2024-01-16 14:29 UTC by undead404

Оригінальний вміст: [Set.prototype.symmetricDifference()@MDN](https://developer.mozilla.org/en-us/docs/Web/JavaScript/Reference/Global_Objects/Set/symmetricDifference), [сирці Set.prototype.symmetricDifference()@GitHub](https://github.com/mdn/content/blob/main/files/en-us/web/javascript/reference/global_objects/set/symmetricdifference/index.md)

2024-02-15 13:47 UTC, undead404 reviewed
Still relevant?

2024-12-26 15:38 UTC, AdriandeCita commented on files/uk/web/javascript/reference/global_objects/set/symmetricdifference/index.md
> +Наступний приклад обчислює симетричну різницю між множиною парних чисел (<10) і множиною квадратів натуральних чисел (<10). Результатом є множина чисел, які є або парними, або квадратами натуральних
```suggestion
Наступний приклад обчислює симетричну різницю між множиною парних чисел (<10) і множиною квадратів натуральних чисел (<10). Результатом є множина чисел, які є або парними, або квадратами натуральних чисел, але не і тим, і іншим водночас.
```

2024-12-26 15:38 UTC, AdriandeCita requested changes
дрібничка

2024-12-27 08:46 UTC, AdriandeCita approved these changes

2024-12-27 09:33 UTC, merged