translation(HTML): web/html/element/output
webdoky/content pull request #2725
Opened 2024-01-16 15:27 UTC by undead404

2024-01-16 15:29 UTC, undead404 commented on files/uk/web/html/element/output/index.md
> +Чимало браузерів реалізують цей елемент як регіон [`aria-live`](/uk/docs/Web/Accessibility/ARIA/ARIA_Live_Regions). Допоміжна технологія, таким чином, оголошує результати взаємодії з користувацьким і
```suggestion
Чимало браузерів реалізують цей елемент як регіон [`aria-live`](/uk/docs/Web/Accessibility/ARIA/ARIA_Live_Regions). Допоміжна технологія, таким чином, оголошує результати взаємодії з користувацьким інтерфейсом, розміщені всередині неї, не вимагаючи перемикання фокуса з елементів керування, що виробляють ці результати.
```

2024-02-15 13:47 UTC, undead404 reviewed
Still relevant?

2024-08-09 20:25 UTC, alinkedd reviewed
Relevant?

2024-10-09 07:54 UTC, KlashReik reviewed
Relevant?

2024-11-03 13:06 UTC, alinkedd reviewed
Relevant?

2024-11-03 13:40 UTC, alinkedd requested changes

2024-11-03 13:40 UTC, alinkedd commented on files/uk/web/html/element/output/index.md
> +  - : Елемент {{HTMLElement("form")}}, яким пов'язане виведення (його _форма-власник_). Значення цього атрибута повинно бути [`id`](/uk/docs/Web/HTML/Global_attributes/id) елемента `<form>` у тому ж
```suggestion
  - : Елемент {{HTMLElement("form")}}, з яким пов'язане виведення (його _форма-власник_). Значення цього атрибута повинно бути [`id`](/uk/docs/Web/HTML/Global_attributes/id) елемента `<form>` у тому ж документі. (Якщо цей атрибут не задано, то `<output>` пов'язано з його предком `<form>`, якщо такий є.)
```

2024-11-03 13:40 UTC, alinkedd commented on files/uk/web/html/element/output/index.md
> +    Цей атрибут дає змогу пов'язувати елементи `<output>` з елементами `<form>` у будь-якому місці документа, а не лише всередині `<form>`. Він також може переважити елемент-предок `<form>`. Назва та
```suggestion
    Цей атрибут дає змогу пов'язувати елементи `<output>` з елементами `<form>` у будь-якому місці документа, а не лише всередині `<form>`. Він також може переважити елемент-предок `<form>`. Назва та вміст елемента `<output>` не надсилаються вкупі з формою.
```

2024-11-03 13:40 UTC, alinkedd commented on files/uk/web/html/element/output/index.md
> +Значення, назва та вміст `<output>` НЕ надсилаються під час подання форми.
```suggestion
Значення, назва та вміст `<output>` НЕ надсилаються під час надсилання форми.
```

2024-11-03 13:40 UTC, alinkedd commented on files/uk/web/html/element/output/index.md
> +Чимало браузерів реалізують цей елемент як регіон [`aria-live`](/uk/docs/Web/Accessibility/ARIA/ARIA_Live_Regions). Допоміжна технологія, таким чином, оголошує результати взаємодії з користувацьким і
```suggestion
Чимало браузерів реалізують цей елемент як регіон [`aria-live`](/uk/docs/Web/Accessibility/ARIA/ARIA_Live_Regions). Так допоміжна технологія оголошує результати взаємодії з користувацьким інтерфейсом, розміщені всередині нього, не вимагаючи перемикання фокуса з елементів керування, що виробляють ці результати.
```

2024-11-03 17:00 UTC, undead404 commented on files/uk/web/html/element/output/index.md
> +Чимало браузерів реалізують цей елемент як регіон [`aria-live`](/uk/docs/Web/Accessibility/ARIA/ARIA_Live_Regions). Допоміжна технологія, таким чином, оголошує результати взаємодії з користувацьким і
Це точно вдало звучить? Може, замість "Так" спрацювало б "отже"?

2024-11-03 21:11 UTC, alinkedd commented on files/uk/web/html/element/output/index.md
> +Чимало браузерів реалізують цей елемент як регіон [`aria-live`](/uk/docs/Web/Accessibility/ARIA/ARIA_Live_Regions). Допоміжна технологія, таким чином, оголошує результати взаємодії з користувацьким і
До елемента додається атрибут. У такий спосіб ми вирішуємо проблему зміни фокуса.

До елемента додається атрибут. Ми так вирішуємо проблему зміни фокуса.

До елемента додається атрибут. Отже, ми вирішуємо проблему зміни фокуса.

Воно по-різному читається. Якби thereby був на початку хоча б, то я б може погодилась, але тут Assistive technology will thereby announce...

2024-11-04 23:04 UTC, alinkedd approved these changes

2024-11-05 08:30 UTC, merged