translation(CSS): web/css/universal_selectors
webdoky/content pull request #2730
Opened 2024-01-17 13:13 UTC by undead404

2024-01-30 11:43 UTC, KlashReik requested changes
Невеличке уточнення

2024-01-30 11:43 UTC, KlashReik commented on files/uk/web/css/universal_selectors/index.md
> +/* автоматично звільняти наступний сестринський елемент після рухомого елемента */
```suggestion
/* автоматично звільняти місце від наступного сестринського елементу після рухомого елемента */
```

Можливо, не найкращий приклад. Але просто "звільняти" якась неправильно відображає зміст.

2024-01-30 12:47 UTC, undead404 commented on files/uk/web/css/universal_selectors/index.md
> +/* автоматично звільняти наступний сестринський елемент після рухомого елемента */
Ти ж побачив, що мова про `clear: left;`, так? Хіба це звільнення місця від...

2024-02-15 13:48 UTC, undead404 reviewed
Still relevant?

2024-02-18 17:15 UTC, Aenqau commented on files/uk/web/css/universal_selectors/index.md
> +/* автоматично звільняти наступний сестринський елемент після рухомого елемента */
Гаразд, я бачу що основної статті по `float` у нас не перекладено також. Загалом оригінальний коментар в сирцях також не надто зрозуміло пояснює, що тут робиться. 


Проте. Стаття про clear каже, що "The clear property sets whether an element must be moved below (cleared) floating elements that precede it. The clear property applies to floating and non-floating elements."
<img width="794" alt="image" src="https://github.com/webdoky/content/assets/11777713/24ffebfd-aeae-40ae-ab48-b855c703a5b9">
Отже я б залишив варіант @undead404 за умови що у нас колись буде перекладена стаття про clear із збереженою термінологією як тут або ж якщо ця стаття буде потім підредактована.

https://developer.mozilla.org/en-US/docs/Web/CSS/clear

2024-02-18 17:40 UTC, Aenqau approved these changes

2024-02-19 08:29 UTC, KlashReik approved these changes

2024-02-19 08:32 UTC, merged