translation(JS): web/javascript/reference/functions/arguments
webdoky/content pull request #2732
Opened 2024-01-17 14:14 UTC by undead404

2024-02-15 13:48 UTC, undead404 reviewed
Still relevant?

2024-08-09 20:25 UTC, alinkedd reviewed
Relevant?

2024-08-23 11:13 UTC, alinkedd requested changes

2024-08-23 11:13 UTC, alinkedd commented on files/uk/web/javascript/reference/functions/arguments/index.md
> +Цей приклад визначає функцію, що з'єднує докупи декілька рядків. Її єдиний формальний аргумент – це рядок, що містить символи, які розділяють елементи, котрі з'єднуються.
в оригіналі дуже важко написано
```suggestion
Цей приклад визначає функцію, що з'єднує докупи декілька рядків. Її єдиний формальний аргумент – це рядок символів між з'єднуваними елементами.
```

2024-08-23 11:13 UTC, alinkedd commented on files/uk/web/javascript/reference/functions/arguments/index.md
> +Оператор {{jsxref("Operators/typeof", "typeof")}} повертає `'object'`, коли його застосувати до `arguments`:
```suggestion
Оператор {{jsxref("Operators/typeof", "typeof")}} повертає `'object'` для `arguments`:
```

2024-08-23 11:27 UTC, undead404 commented on files/uk/web/javascript/reference/functions/arguments/index.md
> +Кожен індекс аргументу також можна задати або перезаписати:
Воно-то так, але, здається, тут можна й "перезаписати"

2024-08-23 11:27 UTC, undead404 commented on files/uk/web/javascript/reference/functions/arguments/index.md
> +`arguments` – це масивоподібний об'єкт, тобто `arguments` має властивість {{jsxref("Functions/arguments/length", "length")}} і властивості з індексами від нуля, але не має вбудованих методів {{jsxref
Так, саме так

2024-08-23 11:30 UTC, alinkedd commented on files/uk/web/javascript/reference/functions/arguments/index.md
> +Кожен індекс аргументу також можна задати або перезаписати:
ну поки залишу

2024-08-23 11:30 UTC, alinkedd approved these changes

2024-08-23 11:39 UTC, merged