translation(CSS): web/css/_colon_where
webdoky/content pull request #2734
Opened 2024-01-18 10:51 UTC by undead404

2024-02-15 13:49 UTC, undead404 reviewed
Still relevant?

2024-12-26 15:33 UTC, AdriandeCita approved these changes

2024-12-26 15:53 UTC, undead404 commented
Додані зміни потребують перевірки, вони маленькі

2024-12-27 16:39 UTC, AdriandeCita commented on files/uk/web/css/_colon_where/index.md
> +Псевдоклас `:where()` вимагає [список селекторів](/uk/docs/Web/CSS/CSS_selectors/Selector_structure#spysok-selektoriv), розділений комами список з одного чи більшої кількості селекторів, як його аргу
Коми тут недостатньо, пропоную додатково виділити визначення
```suggestion
Псевдоклас `:where()` вимагає [список селекторів](/uk/docs/Web/CSS/CSS_selectors/Selector_structure#spysok-selektoriv) — розділений комами список з одного чи більшої кількості селекторів — як його аргумент. Такий список не повинен містити [псевдоелементів](/uk/docs/Web/CSS/Pseudo-elements), але будь-які інші прості, складені та складні селектори допускаються.
```

2024-12-27 16:40 UTC, AdriandeCita commented on files/uk/web/css/_colon_where/index.md
> +Проте що, якщо пізніше захочеться перевизначити колір посилань у нижніх колонтитулах за допомогою складеного селектора, що складається з селекторів низької специфічності типу?
```suggestion
Проте що, якщо пізніше захочеться перевизначити колір посилань у нижніх колонтитулах за допомогою складеного селектора, що складається з селекторів типу низької специфічності?
```

2024-12-27 16:41 UTC, AdriandeCita requested changes
пара побажань до оновлення

2024-12-27 21:59 UTC, AdriandeCita approved these changes

2024-12-27 22:03 UTC, merged