translation(glossary): glossary/media_query
webdoky/content pull request #2736
Opened 2024-01-19 08:16 UTC by undead404

2024-02-08 12:10 UTC, KlashReik reviewed
медіазапит у нас вказано як альтернативна назва. Чи не варто у такому випадку цю назву використовувати у статті, щоб зменшити повторення "медійний запит"? Це запитання стосується устіх статей

2024-02-08 12:38 UTC, undead404 commented
Думаю, варто, адже так красивіше, і це нікого не заплутає

2024-02-13 08:46 UTC, KlashReik requested changes
Трішки розбавив текст

2024-02-13 08:46 UTC, KlashReik commented on files/uk/glossary/media_query/index.md
> +Перед медійним запитом може стояти один необов'язковий модифікатор медійного запиту, `not` чи `only`, і якщо це `not`, то такий модифікатор змінює значення подальшого медійного запиту.
```suggestion
Перед медійним запитом може стояти один необов'язковий модифікатор медіазапиту, `not` чи `only`, і якщо це `not`, то такий модифікатор змінює значення подальшого медійного запиту.
```

2024-02-13 08:46 UTC, KlashReik commented on files/uk/glossary/media_query/index.md
> +Кілька розділених комами медійних запитів утворюють **список медійних запитів**. Список медійних запитів є істинним, якщо щонайменше один з медійних запитів у ньому є істинним, а хибним – лише якщо в
```suggestion
Кілька розділених комами медіазапитів утворюють **список медійних запитів**. Список медійних запитів є істинним, якщо щонайменше один з медіазапитів у ньому є істинним, а хибним – лише якщо всі медіазапити у ньому є хибними.
```

2024-02-13 12:30 UTC, KlashReik approved these changes

2024-02-13 12:46 UTC, merged