translation(glossary): glossary/world_wide_web
webdoky/content pull request #2745
Opened 2024-01-19 20:42 UTC by undead404

2024-01-21 09:00 UTC, undead404 commented on files/uk/glossary/world_wide_web/index.md
> +- Щоб звернутися до вебкомпонента, клієнт надає унікальний універсальний ідентифікатор, який зветься **{{Glossary("URL")}}** (однорідний локатор ресурса) або {{Glossary("URI")}} (однорідний ідентифік
```suggestion
- Щоб звернутися до вебкомпонента, клієнт надає унікальний універсальний ідентифікатор, який зветься **{{Glossary("URL")}}** (однорідний локатор ресурсу) або {{Glossary("URI")}} (однорідний ідентифікатор ресурсу) (раніше відомий як універсальний ідентифікатор документа – UDI).
```

2024-01-21 09:00 UTC, undead404 commented on files/uk/glossary/world_wide_web/index.md
> +Невдовзі після винайдення Вебу Тім Бернерс-Лі заснував {{Glossary("W3C")}} (Консорціум Світової павутини), щоб стандартизувати і розвивати Веб далі. Цей консорціум складається з ключових груп, заціка
```suggestion
Невдовзі після винайдення Вебу Тім Бернерс-Лі заснував {{Glossary("W3C")}} (Консорціум Світової павутини), щоб стандартизувати та розвивати Веб далі. Цей консорціум складається з ключових груп, зацікавлених у Вебі, як то розробників веббраузерів, урядових установ, дослідників і університетів. Його місія включає освіту та просвіту.
```

2024-02-08 12:21 UTC, KlashReik requested changes

2024-02-08 12:21 UTC, KlashReik commented on files/uk/glossary/world_wide_web/index.md
> +Невдовзі після винайдення Вебу Тім Бернерс-Лі заснував {{Glossary("W3C")}} (Консорціум Світової павутини), щоб стандартизувати та розвивати Веб далі. Цей консорціум складається з ключових груп, зацік
```suggestion
Невдовзі після винайдення Вебу, Тім Бернерс-Лі заснував {{Glossary("W3C")}} (Консорціум Світової павутини), щоб стандартизувати та розвивати Веб далі. Цей консорціум складається з ключових груп, зацікавлених у Вебі, як то розробників веббраузерів, урядових установ, дослідників і університетів. Його місія включає освіту та просвіту.
```

2024-02-13 12:31 UTC, KlashReik approved these changes

2024-02-13 12:47 UTC, merged