update(HTML): web/html/element/table
webdoky/content pull request #2747
Opened 2024-01-22 15:36 UTC by undead404

Оригінальний вміст: ["&lt;table&gt; – елемент таблиці"@MDN](https://developer.mozilla.org/en-us/docs/Web/HTML/Element/table), [сирці "&lt;table&gt; – елемент таблиці"@GitHub](https://github.com/mdn/content/blob/main/files/en-us/web/html/element/table/index.md)

Нові зміни:
- [chore(learn): Move MDN Curriculum into Learning Area (#36967)](https://github.com/mdn/content/commit/5b20f5f4265f988f80f513db0e4b35c7e0cd70dc)
- [update links: replace DT link with real target (#36302)](https://github.com/mdn/content/commit/816cc4d4a5a318a23222946b6981bb92b499aebb)
- [Remove quotes around code spans 3 (#36037)](https://github.com/mdn/content/commit/5bd9fe2b25c6eee2a14d0406ce7116998fa48c13)
- [Convert noteblocks for web/html folder (#35114)](https://github.com/mdn/content/commit/9c09b183a5ce844a75c2f22e909d03f71ca329fc)
- [Convert noteblocks for web/html/element folder (#35085)](https://github.com/mdn/content/commit/b7955e77cd4293adf45ef23686df50b0305f02ad)
- [Fix typo in HTML table element page (#34258)](https://github.com/mdn/content/commit/dac2d6ea525dd46fc461f3be4e34bad5941f8ea1)
- [Move Accessibility section above Examples for html element pages (#34007)](https://github.com/mdn/content/commit/bde0cb215d1d307c08678abe6623fc0d39f4cf7f)
- [chore: fix broken links (#32809)](https://github.com/mdn/content/commit/829db137a01feb14af7beaec178a3ea0118b4777)
- [Fix issue 32554: avoid documenting obsolete attributes (#32737)](https://github.com/mdn/content/commit/9bb46b1c04e21fb4fb805ae5acef74b4def2a52e)
- [chore(macros): Replace no_tag_omission macro with single sentence of text (#32394)](https://github.com/mdn/content/commit/fdd3ac5598c3ddceb71e59949b003936ae99f647)
- [fix and improve content on reference pages of table elements (#27958)](https://github.com/mdn/content/commit/fffabdeeb9a069e40a070dadeedc93298b2aca7e)
- [fix(html): mention that table cell styles are painted over column styles (#30830)](https://github.com/mdn/content/commit/7a5d4c39c672ee4562aba5f4e8254dcbe6cc0d7f)

2024-08-09 20:20 UTC, alinkedd reviewed
Relevant?

2024-12-25 22:13 UTC, AdriandeCita commented on files/uk/web/html/element/table/index.md
> +Наступне правило CSS задає {{cssxref("background-color")}} для всіх елементів {{HTMLElement("tr")}} у верху таблиці (як вказано за допомогою {{HTMLElement("thead")}}). Потім нижня межа верху встановл
```suggestion
Наступне правило CSS задає {{cssxref("background-color")}} для всіх елементів {{HTMLElement("tr")}} у верху таблиці (як вказано за допомогою {{HTMLElement("thead")}}). Потім нижня межа верху встановлюється як двопіксельна лінія. Проте зверніть увагу, що використовується селектор {{CSSxRef(":nth-of-type")}}, аби застосувати властивість {{CSSxRef("border-bottom")}} до _другого_ згори ряду. Чому? Тому що верх складається з двох рядів, на які простягається частина комірок. Це означає, що насправді є два ряди; застосування стилю до першого ряду не дало б очікуваного результату:
```

2024-12-25 22:18 UTC, AdriandeCita requested changes
дрібничка

2024-12-26 15:21 UTC, AdriandeCita approved these changes

2024-12-26 15:23 UTC, merged