translation(js): /Web/JavaScript/Reference/Template_literals
webdoky/content pull request #280
Opened 2022-02-23 09:15 UTC by AdriandeCita

Original content: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Template_literals

2022-02-26 14:27 UTC, undead404 requested changes

2022-02-26 14:27 UTC, undead404 commented on files/uk/web/javascript/reference/template_literals/index.md
> +Тегова функція далі може виконати які завгодно операції на цих аргументах, і повернути оброблений рядок. (Вона також може повертати щось абсолютно інше, як описано в одному з прикладів нижче.)
```suggestion
Тегова функція далі може виконати які завгодно операції на цих аргументах і повернути оброблений рядок. (Вона також може повертати щось абсолютно інше, як описано в одному з прикладів нижче.)
```

2022-02-26 14:27 UTC, undead404 commented on files/uk/web/javascript/reference/template_literals/index.md
> +На додаток, для створення необроблених рядків існує метод {{jsxref("String.raw()")}}, який працює точнісінько так само, як усталена тегова функція, і конкатенація рядків.
```suggestion
На додаток, для створення необроблених рядків існує метод {{jsxref("String.raw()")}}, який працює точнісінько так само, як усталена тегова функція і конкатенація рядків.
```

2022-02-26 14:27 UTC, undead404 commented on files/uk/web/javascript/reference/template_literals/index.md
> +Від ECMAScript 2016, теговані шаблони враховують правила таких екранованих послідовностей:
```suggestion
Починаючи з ECMAScript 2016, теговані шаблони враховують правила таких екранованих послідовностей:
```

2022-02-26 14:27 UTC, undead404 commented on files/uk/web/javascript/reference/template_literals/index.md
> +- Екрановані послідовності кодової точки Unicode, що позначаються "`\u{}`", наприклад `\u{2F804}`
```suggestion
- Екрановані послідовності кодової точки Unicode, що позначаються "`\u{}`", наприклад, `\u{2F804}`
```

2022-02-26 14:27 UTC, undead404 commented on files/uk/web/javascript/reference/template_literals/index.md
> +- Шістнадцяткові екранування, що починаються з "`\x`", наприклад `\xA9`
```suggestion
- Шістнадцяткові екранування, що починаються з "`\x`", наприклад, `\xA9`
```

2022-02-26 14:27 UTC, undead404 commented on files/uk/web/javascript/reference/template_literals/index.md
> +- Вісімкові літеральні екранування, що починаються з "`\0o`", а продовжуються однією чи декількома цифрами, наприклад `\0o251`
```suggestion
- Вісімкові літеральні екранування, що починаються з "`\0o`", а продовжуються однією чи декількома цифрами, наприклад, `\0o251`
```

2022-02-26 14:27 UTC, undead404 commented on files/uk/web/javascript/reference/template_literals/index.md
> +Це означає, що буде проблематичним вжити таки тегований шаблон, як наведено нижче, оскільки, згідно з граматикою ECMAScript, парсер шукатиме дійсну екрановану послідовність Unicode, але знайде дефект
```suggestion
Це означає, що буде проблематичним вжити такий тегований шаблон, як наведено нижче, оскільки, згідно з граматикою ECMAScript, парсер шукатиме дійсну екрановану послідовність Unicode, але знайде дефектний синтаксис:
```

2022-02-26 14:27 UTC, undead404 commented on files/uk/web/javascript/reference/template_literals/index.md
> +Теговані шаблони повинні давати змогу вкладати інші мови (наприклад [предметно орієнтовані](https://en.wikipedia.org/wiki/Domain-specific_language), чи [LaTeX](https://en.wikipedia.org/wiki/LaTeX)),
```suggestion
Теговані шаблони повинні давати змогу вкладати інші мови (наприклад, [предметно орієнтовані](https://uk.wikipedia.org/wiki/%D0%9F%D1%80%D0%B5%D0%B4%D0%BC%D0%B5%D1%82%D0%BD%D0%BE-%D0%BE%D1%80%D1%96%D1%94%D0%BD%D1%82%D0%BE%D0%B2%D0%B0%D0%BD%D0%B0_%D0%BC%D0%BE%D0%B2%D0%B0_%D0%BF%D1%80%D0%BE%D0%B3%D1%80%D0%B0%D0%BC%D1%83%D0%B2%D0%B0%D0%BD%D0%BD%D1%8F), чи [LaTeX](https://uk.wikipedia.org/wiki/LaTeX)), в яких поширені інші екрановані послідовності. Пропозиція до розгляду ECMAScript під назвою [Перегляд шаблонних літералів (англ.)](https://tc39.github.io/proposal-template-literal-revision/) (інтегровано в стандарт ECMAScript 2018) прибрала обмеження екранованих послідовностей ECMAScript з тегованих шаблонів.
```

2022-02-26 14:27 UTC, undead404 commented on files/uk/web/javascript/reference/template_literals/index.md
> +Все ж, недійсні екрановані послідовності все одно необхідно показати в "приготовленому" виразі. Їх буде показано як {{jsxref("undefined", "невизначені")}} елементи в масиві "cooked":
```suggestion
Все ж, недійсні екрановані послідовності все одно необхідно показати в "приготованому" виразі. Їх буде показано як {{jsxref("undefined", "невизначені")}} елементи в масиві "cooked":
```

2022-06-07 21:49 UTC, AdriandeCita commented
Оновлено, додано нові зміни: [7449143](https://github.com/mdn/content/commit/74491431d2afdcb4049efe037349361dca9329b6), [461710a](https://github.com/mdn/content/commit/461710a5d168c58ca67818895059772a26a17de3), [dd242c9](https://github.com/mdn/content/commit/dd242c9a48f7c34d068fb10bbe3f4f0fd34a17bd), [6fb517d](https://github.com/mdn/content/commit/6fb517d5f9724399d490fb9cda7a03898f40e2fd), [76a015f](https://github.com/mdn/content/commit/76a015ffc44bd29c93e725366ad023171e6c7e7d), [37676df](https://github.com/mdn/content/commit/37676df66bb7cf9c7b59ac573c98febe401c9eed), [c502c81](https://github.com/mdn/content/commit/c502c811a563440296bfd29d1d9862772005d337), [a94ef2c](https://github.com/mdn/content/commit/a94ef2c598fc7b6a8006bb66227da870df61e3d6), [529663b](https://github.com/mdn/content/commit/529663b77721cded2c6ea2634d89d0fc38481bcb), [4794d70](https://github.com/mdn/content/commit/4794d70196f15bff02cbd8334665eaed61959ac8)

2022-06-11 08:09 UTC, undead404 approved these changes

2022-06-11 14:03 UTC, merged