translation(js): /Web/JavaScript/Reference/Statements/for...in
webdoky/content pull request #281
Opened 2022-02-23 09:23 UTC by AdriandeCita

Original content: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/for...in

2022-06-07 21:59 UTC, AdriandeCita commented
Оновлено, нові зміни: [18c7b9e](https://github.com/mdn/content/commit/18c7b9ed2a009efd7974f0af41996b99895382ca), [76a015f](https://github.com/mdn/content/commit/76a015ffc44bd29c93e725366ad023171e6c7e7d)

2022-06-11 08:31 UTC, undead404 requested changes
Оригінал вчора оновився, потребує додаткової перевірки

2022-06-11 08:31 UTC, undead404 commented on files/uk/web/javascript/reference/statements/for...in/index.md
> +  - : Об'єкт, чиї перелічувані властивості з несимвольними ключами зараз перебираються.
```suggestion
  - : Об'єкт, чиї перелічувані властивості з несимвольними ключами перебираються.
```

2022-06-11 08:31 UTC, undead404 commented on files/uk/web/javascript/reference/statements/for...in/index.md
> +Цикл `for...in` перебирає лише ті перелічувані властивості, чиїм ключем не є символ. Об'єкти, які створюються за допомогою таких вбудованих конструкторів, як `Array` і `Object`, мають неперелічувані
```suggestion
Цикл `for...in` перебирає лише ті перелічувані властивості, чиїм ключем не є символ. Об'єкти, які створюються за допомогою вбудованих конструкторів, наприклад, `Array` і `Object`, мають неперелічувані властивості, успадковані від `Object.prototype` та `String.prototype`, як от метод {{jsxref("String.indexOf", "indexOf()")}} об'єкту {{jsxref("String")}} чи метод {{jsxref("Object.toString", "toString()")}} об'єкта {{jsxref("Object")}}. Цикл опрацює всі власні перелічувані властивості об'єкта, а також ті, що успадковуються об'єктом від його прототипного ланцюжка (властивості ближчих прототипів мають перевагу над властивостями тих прототипів, які знаходяться далі від об'єкта у ланцюжку прототипів).
```

2022-06-11 08:31 UTC, undead404 commented on files/uk/web/javascript/reference/statements/for...in/index.md
> +Цикл `for...in` перебирає властивості об'єкта у довільному порядку (більше деталей про те, чому не можна залежати від позірної впорядкованості цього перебирання, принаймні в кросбраузерному контексті
```suggestion
Цикл `for...in` перебирає властивості об'єкта у довільному порядку (більше деталей про те, чому не можна покладатися на позірну впорядкованість цього перебирання, принаймні в кросбраузерному контексті, — в описі оператора {{jsxref("Operators/delete", "delete")}}).
```

2022-06-11 08:31 UTC, undead404 commented on files/uk/web/javascript/reference/statements/for...in/index.md
> +Якщо під час однієї з ітерацій властивість змінюється, а потім опрацьовується в одній з наступних ітерацій, в циклі буде використано те значення, яке вона має на момент її опрацювання другого разу. В
```suggestion
Якщо під час однієї з ітерацій властивість змінюється, а потім опрацьовується в одній з наступних ітерацій, в циклі буде використано те значення, яке вона має на момент її опрацювання другого разу. Властивість, яку було видалено перед своєю обробкою, пізніше оброблено не буде. Властивості, які додаються до об'єкта під час перебирання його властивостей, можуть бути як оброблені пізніше, так і пропущені в циклі.
```

2022-06-11 08:31 UTC, undead404 commented on files/uk/web/javascript/reference/statements/for...in/index.md
> +Загалом краще не додавати, не змінювати й не видаляти властивості з об'єкта під час ітерування, поза властивістю, які безпосередньо обробляється ітерацією. Немає ніяких гарантій того, що додана власт
```suggestion
Загалом,  під час ітерування краще не додавати, не змінювати й не видаляти властивості з об'єкта, окрім властивості, котра безпосередньо обробляється поточною ітерацією. Немає ніяких гарантій того, що додана властивість буде опрацьована циклом, чи буде змінена властивість оброблена до, чи після модифікації, і чи буде видалена властивість опрацьована до моменту видалення.
```

2022-06-11 08:31 UTC, undead404 commented on files/uk/web/javascript/reference/statements/for...in/index.md
> +Індекси масиву — це лише перелічувані властивості, які у всьому ідентичні властивостям звичайних об'єктів, окрім того, що їхні імена — це цілі числа. Немає гарантії, що цикл `for...in` повертатиме ін
```suggestion
Індекси масиву — прості перелічувані властивості, які у всьому ідентичні властивостям звичайних об'єктів, окрім того, що їхні імена — це цілі числа. Немає гарантії, що цикл `for...in` повертатиме індекси в певному порядку. Інструкція циклу `for...in` поверне всі перелічувані властивості, включно з успадкованими, а також такими, чиї імена не є цілими числами.
```

2022-06-11 08:31 UTC, undead404 commented on files/uk/web/javascript/reference/statements/for...in/index.md
> +Найбільш доцільним може бути його використання для потреб зневадження, як простого способу перевірити властивості об'єкту (шляхом виведення їх у консоль, або ж інакшим чином). І хоча масиви часто є п
```suggestion
Найбільш доцільним може бути його використання для потреб зневадження, як простого способу перевірити властивості об'єкту (шляхом виведення їх у консоль, або ж інакшим чином). І хоча масиви часто є практичнішим способом зберігання даних, в ситуаціях, коли доцільніше використовувати для роботи з даними формат ключ-значення (де імена властивостей грають роль "ключа"), можуть траплятися випадки, коли потрібно перевірити, чи якийсь із таких ключів зберігає певне значення.
```

2022-06-11 08:31 UTC, undead404 commented on files/uk/web/javascript/reference/statements/for...in/index.md
> +У Firefox до версії 40, було можливо використовувати вираз ініціалізації (`i=0`) у циклі `for...in`:
```suggestion
У Firefox до версії 40 у циклі `for...in` було можливо використовувати вираз ініціалізації (`i=0`):
```

2022-06-11 08:31 UTC, undead404 commented on files/uk/web/javascript/reference/statements/for...in/index.md
> +Ця нестандартна поведінка ігнорується починаючи з версії 40, і покаже помилку {{jsxref("SyntaxError")}} ("[заголовок оголошення циклу for-in не може містити вирази ініціалізації](/uk/docs/Web/JavaScr
```suggestion
Ця нестандартна поведінка ігнорується починаючи з версії 40 і покаже помилку {{jsxref("SyntaxError")}} ("[заголовок оголошення циклу for-in не може містити вирази ініціалізації](/uk/docs/Web/JavaScript/Reference/Errors/Invalid_for-in_initializer)") в [суворому режимі](/uk/docs/Web/JavaScript/Reference/Strict_mode) (вади [748550](https://bugzilla.mozilla.org/show_bug.cgi?id=748550) і [1164741](https://bugzilla.mozilla.org/show_bug.cgi?id=1164741)).
```

2022-06-11 15:19 UTC, undead404 commented
Ок, але чекаю змін по https://github.com/mdn/content/commit/bd2d4aea36b322592fbec76aaf77686e8b010190

2022-06-11 21:44 UTC, AdriandeCita commented
Оновив, там трохи є змін

2022-06-12 07:52 UTC, undead404 commented on files/uk/web/javascript/reference/statements/for...in/index.md
> +Краще використовувати цикл {{jsxref("Statements/for", "for")}} з числовим індексом, {{jsxref("Array.prototype.forEach()")}}, чи цикл {{jsxref("Statements/for...of", "for...of")}}, оскільки вони повер
```suggestion
Краще використовувати цикл {{jsxref("Statements/for", "for")}} з числовим індексом, {{jsxref("Array.prototype.forEach()")}} чи цикл {{jsxref("Statements/for...of", "for...of")}}, оскільки вони повертатимуть індекс як число, а не як рядок, а також уникатимуть властивостей поза індексом.
```

2022-06-12 07:52 UTC, undead404 commented on files/uk/web/javascript/reference/statements/for...in/index.md
> +Багато настанов щодо стилю та лінтерів у JavaScript рекомендують не застосовувати `for...in` тому, що він перебирає весь ланцюжок прототипів, що рідко є бажаним. Також його часто плутають із більш вж
```suggestion
Багато настанов щодо стилю та лінтерів у JavaScript рекомендують не застосовувати `for...in` через те, що він перебирає весь ланцюжок прототипів, а це рідко є бажаним. Також його часто плутають із більш вживаним циклом `for...of`. В яких випадках `for...in` був би взагалі корисним?
```

2022-06-12 16:57 UTC, undead404 approved these changes

2022-06-12 18:05 UTC, merged