translation(js): /Web/JavaScript/Reference/Statements/async_function
webdoky/content pull request #282
Opened 2022-02-23 09:30 UTC by AdriandeCita

Original content: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/async_function

2022-06-08 09:11 UTC, AdriandeCita commented
Оновлено, нові зміни: [2ec681b](https://github.com/mdn/content/commit/2ec681bd9ad77115496f551c62fee2ba50c9007f), [76a015f](https://github.com/mdn/content/commit/76a015ffc44bd29c93e725366ad023171e6c7e7d)

2022-06-11 09:04 UTC, undead404 requested changes

2022-06-11 09:04 UTC, undead404 commented on files/uk/web/javascript/reference/statements/async_function/index.md
> +> У функції `concurrentPromise`, `Promise.all` зв'язує ланцюжок промісів за один прохід, тобто операція негайно завершить роботу в разі помилки незалежно від послідовності відхилення промісів, і поми
```suggestion
> У функції `concurrentPromise` `Promise.all` зв'язує ланцюжок промісів за один прохід, тобто операція негайно завершить роботу в разі помилки незалежно від послідовності відхилення промісів, і помилка завжди відбуватиметься всередині налаштованого ланцюжка промісів, що дає змогу її обробити у звичайний спосіб.
```

2022-06-11 09:04 UTC, undead404 commented on files/uk/web/javascript/reference/statements/async_function/index.md
> +Цей можна переписати як одну асинхронну функцію, як це показано нижче:
```suggestion
Це можна переписати як одну асинхронну функцію, як це показано нижче:
```

2022-06-11 09:04 UTC, undead404 commented on files/uk/web/javascript/reference/statements/async_function/index.md
> +Цей можна переписати як одну асинхронну функцію, як це показано нижче:
Цейво...

2022-06-11 15:20 UTC, undead404 approved these changes

2022-06-11 19:55 UTC, merged