translation(js): /Web/JavaScript/Reference/Operators/typeof
webdoky/content pull request #283
Opened 2022-02-23 09:38 UTC by AdriandeCita

Original content: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/typeof

2022-06-08 09:28 UTC, AdriandeCita commented
Оновлено, нові зміни: [abcebf4](https://github.com/mdn/content/commit/abcebf471d56ef12239e2565f26d952e8a8cab2e), [df6360a](https://github.com/mdn/content/commit/df6360a23ca7c231b4bf1340b028440344bbc159), [4e55ef8](https://github.com/mdn/content/commit/4e55ef8d3618f047997d8670fce06b838de6a17b)

2022-06-11 11:28 UTC, undead404 requested changes

2022-06-11 11:28 UTC, undead404 commented on files/uk/web/javascript/reference/operators/typeof/index.md
> +typeof '1' === 'string'; // зауважте, що число всерединні рядка все ж має рядковий тип
```suggestion
typeof '1' === 'string'; // зауважте, що число всередині рядка все ж має рядковий тип
```

2022-06-11 11:28 UTC, undead404 commented on files/uk/web/javascript/reference/operators/typeof/index.md
> +Було запропоновано виправлення для ECMAScript (як "opt-in" — можливість, яку можна було ввімкнути), проте [його відхилили](https://web.archive.org/web/20160331031419/http://wiki.ecmascript.org:80/dok
```suggestion
Було запропоновано виправлення для ECMAScript (як "opt-in" — можливість, яку можна було б увімкнути), проте [його відхилили](https://web.archive.org/web/20160331031419/http://wiki.ecmascript.org:80/doku.php?id=harmony:typeof_null). Результатом його прийняття була б рівність `typeof null === 'null'`.
```

2022-06-11 11:28 UTC, undead404 commented on files/uk/web/javascript/reference/operators/typeof/index.md
> +Хоча специфікація дає змогу мати користувацькі теги типу для нестандартних екзотичних об'єктів, вона вимагає, щоб ці теги відрізнялися від раніше заданих. Випадок з `document.all`, що має тип `'undef
```suggestion
Хоча специфікація дає змогу мати користувацькі теги типу для нестандартних екзотичних об'єктів, вона вимагає, щоб ці теги відрізнялися від раніше заданих. Випадок з `document.all`, що має тип `'undefined'`, класифіковано у вебстандартах як "навмисне порушення" первісного стандарту ECMA JavaScript.
```

2022-06-11 11:28 UTC, undead404 commented on files/uk/web/javascript/reference/operators/typeof/index.md
> +Для більшої специфічности під час перевірки типів, можна зробити таку обгортку над `typeof` для використання в робочому коді (за умови, що `obj` існує):
```suggestion
Для більшої специфічности під час перевірки типів можна зробити таку обгортку над `typeof` для використання в робочому коді (за умови, що `obj` існує):
```

2022-06-11 15:20 UTC, undead404 approved these changes

2022-06-11 19:55 UTC, merged