update(HTML): web/html/element/script/type/speculationrules
webdoky/content pull request #2932
Opened 2024-03-27 15:47 UTC by undead404

2024-03-27 16:00 UTC, undead404 commented on files/uk/web/html/element/script/type/speculationrules/index.md
> +  - : Масив рядків, що представляє список URL, до яких застосовуватиметься правило. Це можуть бути абсолютні чи відносні URL. Відносні URL тлумачаться відносно базового URL документа (якщо опис прави
```suggestion
  - : Масив рядків, що представляє список URL, до яких застосовуватиметься правило. Це можуть бути абсолютні чи відносні URL. Відносні URL тлумачаться відносно базового URL документа (якщо опис правил вбудований у документ) або відносно URL зовнішнього ресурсу (якщо вони отримані зовні). В одному правилі не можна задати водночас як `"urls"`, так і `"where"`.
```

2024-03-27 16:00 UTC, undead404 commented on files/uk/web/html/element/script/type/speculationrules/index.md
> +  - : Об'єкт, що представляє умови, за яких правило відповідає URL, що містяться в пов'язаному документі. Фактично, об'єкт `"where"` представляє перевірку, яка виконується для кожного посилання на ст
```suggestion
  - : Об'єкт, що представляє умови, за яких правило відповідає URL, що містяться в пов'язаному документі. Фактично, об'єкт `"where"` представляє перевірку, яка виконується для кожного посилання на сторінці, щоб визначити, чи застосовувати до нього правило спекуляції. В одному правилі не можна задати водночас як і `"where"`, так і `"urls"`.
```

2024-03-27 16:00 UTC, undead404 commented on files/uk/web/html/element/script/type/speculationrules/index.md
> +      - : Розробник вважає, що за посиланням перейдуть з дуже високою ймовірністю, чи документ може завантажуватися суттєвий час. Попереднє отримання або попереднє візуалізування має початися якомога
```suggestion
      - : Розробник вважає, що за посиланням перейдуть з дуже високою ймовірністю, чи документ може завантажуватися суттєвий час. Попереднє отримання або попередня візуалізація має початися якомога швидше, за винятком випадків, коли цьому заважають налаштування користувача або обмеження щодо ресурсів.
```

2024-03-27 16:00 UTC, undead404 commented on files/uk/web/html/element/script/type/speculationrules/index.md
> +      - : Розробник бажає попередньо завантажити чи візуалізувати велику кількість переходів, якомога раніше. Попереднє отримання або попереднє візуалізування має початися при найменшому натяку на те
```suggestion
      - : Розробник бажає попередньо завантажити чи візуалізувати велику кількість переходів, якомога раніше. Попереднє отримання або попередня візуалізація має початися при найменшому натяку на те, що за посиланням можуть перейти. Наприклад, користувач може порухати курсор миші в бік посилання, навести на неї чи передати їй фокус на якусь мить, або зупинити прокручення, коли посилання перебуває на видноті.
```

2024-03-27 16:00 UTC, undead404 commented on files/uk/web/html/element/script/type/speculationrules/index.md
> +      - : Розробник прагне золотої середини між `eager` і `conservative`. Попереднє отримання або візуалізування має початися, коли є доцільна вказівка на те, що користувач перейде за посиланням у на
```suggestion
      - : Розробник прагне золотої середини між `eager` і `conservative`. Попереднє отримання або візуалізація має початися, коли є доцільна вказівка на те, що користувач перейде за посиланням у найближчому майбутньому. Наприклад, він може прокрутити сторінку так, що посилання потрапить в область перегляду, або торкнутися його на якусь мить.
```

2024-03-27 16:00 UTC, undead404 commented on files/uk/web/html/element/script/type/speculationrules/index.md
> +    > **Примітка:** У випадку правил документу буде використана задана політика посилача для посилання, що дало збіг (наприклад, за допомогою атрибута [`referrerpolicy`](/uk/docs/Web/HTML/Element/a#r
```suggestion
    > **Примітка:** У випадку правил документа буде використана задана політика посилача для посилання, що дало збіг (наприклад, за допомогою атрибута [`referrerpolicy`](/uk/docs/Web/HTML/Element/a#referrerpolicy)), якщо правило не задає політику, що її пересилює.
```

2024-03-27 16:00 UTC, undead404 commented on files/uk/web/html/element/script/type/speculationrules/index.md
> +Що до наборів правил, які отримані зовні (наприклад, за допомогою заголовка відповіді {{httpheader("Speculation-Rules")}}), URL у правилах списку та патернах URL у правилах документу усталено розбира
```suggestion
Що до наборів правил, які отримані зовні (наприклад, за допомогою заголовка відповіді {{httpheader("Speculation-Rules")}}), URL у правилах списку та патернах URL у правилах документа усталено розбираються відносно URL зовнішнього текстового файлу, що їх вміщає. Щоб URL у правилі списку розбиралися відносно базового URL поточного документа, отак використовується `"relative_to"`:
```

2024-03-27 16:00 UTC, undead404 commented on files/uk/web/html/element/script/type/speculationrules/index.md
> +Що до правил документу, то `"relative_to"` можна безпосередньо поєднати з `"href_matches"`, і базовий URL документа буде використовуватися лише для патернів у цій конкретній умові:
```suggestion
Що до правил документа, то `"relative_to"` можна безпосередньо поєднати з `"href_matches"`, і базовий URL документа буде використовуватися лише для патернів у цій конкретній умові:
```

2024-03-27 16:00 UTC, undead404 commented on files/uk/web/html/element/script/type/speculationrules/index.md
> +Наступний набір правил документу показує, як `eagerness` можна скористатися, аби підказати щодо терміновості, з якої браузер повинен попередньо візуалізувати кожний набір посилань, що дає збіг.
```suggestion
Наступний набір правил документа показує, як `eagerness` можна скористатися, аби підказати щодо терміновості, з якої браузер повинен попередньо візуалізувати кожний набір посилань, що дає збіг.
```

2024-03-27 16:00 UTC, undead404 commented on files/uk/web/html/element/script/type/speculationrules/index.md
> +> **Примітка:** Дія налаштувань терміновості має меншу корисність для правил списку. Усталено URL правил списку попередньо отримуються чи візуалізуються негайно, щойно правила розібрані, і це те, що
```suggestion
> **Примітка:** Дія налаштувань терміновості має меншу корисність для правил списку. Усталено URL правил списку попередньо отримуються чи візуалізуються негайно, щойно правила розібрані, і це те, що очікується – такі правила призначені для явного перелічення високопріоритетних URL, які повинні бути доступними якомога швидше. Через це `eager` у нинішніх реалізаціях діє так само, як `immediate`. Налаштування нижчої терміновості призначені для попереднього отримання чи візуалізації при взаємодії з посиланнями, і для цього, ймовірно, ви скористаєтесь правилами документа для їх пошуку на сторінці.
```

2024-04-13 10:32 UTC, AdriandeCita commented on files/uk/web/html/element/script/type/speculationrules/index.md
> +    > **Примітка:** У випадку правил документа буде використана задана політика посилача для посилання, що дало збіг (наприклад, за допомогою атрибута [`referrerpolicy`](/uk/docs/Web/HTML/Element/a#r
В оригіналі це окремі примітки
```suggestion

    > **Примітка:** У випадку правил документа буде використана задана політика посилача для посилання, що дало збіг (наприклад, за допомогою атрибута [`referrerpolicy`](/uk/docs/Web/HTML/Element/a#referrerpolicy)), якщо правило не задає політику, що її пересилює.
```

2024-04-13 10:41 UTC, AdriandeCita commented on files/uk/web/html/element/script/type/speculationrules/index.md
> +Що до наборів правил, які отримані зовні (наприклад, за допомогою заголовка відповіді {{httpheader("Speculation-Rules")}}), URL у правилах списку та патернах URL у правилах документа усталено розбира
```suggestion
Що до наборів правил, які отримані зовні (наприклад, за допомогою заголовка відповіді {{httpheader("Speculation-Rules")}}), URL у правилах списку та патерни URL у правилах документа усталено розбираються відносно URL зовнішнього текстового файлу, що їх вміщає. Щоб URL у правилі списку розбиралися відносно базового URL поточного документа, отак використовується `"relative_to"`:
```

2024-04-13 10:45 UTC, AdriandeCita commented on files/uk/web/html/element/script/type/speculationrules/index.md
> +3. Інший потенціальний (хоч і рідкісніший) випадок використання трапляється, коли URL задані у вигляді `home`, а не `/home`. Якщо документ розташований за адресою `https://example.com/some/subpage.ht
```suggestion
3. Інший потенційний (хоч і рідкісніший) випадок використання трапляється, коли URL задані у вигляді `home`, а не `/home`. Якщо документ розташований за адресою `https://example.com/some/subpage.html`, а правила — за адресою `https://example.com/resources/rules.json`, то:
```

2024-04-13 10:48 UTC, AdriandeCita commented on files/uk/web/html/element/script/type/speculationrules/index.md
> +Наступний набір правил документа показує, як `eagerness` можна скористатися, аби підказати щодо терміновості, з якої браузер повинен попередньо візуалізувати кожний набір посилань, що дає збіг.
```suggestion
Наступний набір правил документа показує, як `eagerness` можна скористатися, аби підказати браузеру, наскільки терміново він повинен попередньо візуалізувати кожний набір посилань, що дає збіг.
```

2024-04-13 10:50 UTC, AdriandeCita commented on files/uk/web/html/element/script/type/speculationrules/index.md
> +Розумно уявляти об'єкт `"where"` як такий, що рівносильний операції `if`. Тож
```suggestion
Доречно уявляти об'єкт `"where"` як такий, що рівносильний операції `if`. Тож
```

2024-04-13 10:59 UTC, AdriandeCita commented on files/uk/web/html/element/script/type/speculationrules/index.md
> +Будь-яка умова може бути заперечена, коли поставити її всередину умови `"not"` – це означає, що коли така вкладена умова дає збіг, до посилання _не буде_ застосовуватися правило спекуляції, а коли _н
Пригадую, в курсі математики колись були такі терміни, як "пряма і обернена (операція, функція, умова тощо)". Думаю, доречніше "negation" перекладати саме в такому контексті
```suggestion
Будь-яку умову можна обернути, якщо поставити її всередину умови `"not"` – це означає, що коли така вкладена умова дає збіг, до посилання _не буде_ застосовуватися правило спекуляції, а коли _не_ дає – то _буде_. Наступний приклад призведе до того, що до всіх посилань, які _не_ відповідають патерну URL `/logout`, буде застосовано правило, але не до посилань, що відповідають `/logout`:
```

2024-04-13 11:06 UTC, AdriandeCita commented on files/uk/web/html/element/script/type/speculationrules/index.md
> +Будь-яка умова може бути заперечена, коли поставити її всередину умови `"not"` – це означає, що коли така вкладена умова дає збіг, до посилання _не буде_ застосовуватися правило спекуляції, а коли _н
Пригадую, в курсі математики колись були такі терміни, як "пряма і обернена (операція, функція, умова тощо)". Думаю, доречніше "negation" перекладати саме в такому контексті
```suggestion
Будь-яку умову можна обернути, якщо поставити її всередину умови `"not"` – це означає, що коли така вкладена умова дає збіг, до посилання _не буде_ застосовуватися правило спекуляції, а коли _не_ дає – то _буде_. Наступний приклад призведе до того, що до всіх посилань, які _не_ відповідають патерну URL `/logout`, буде застосовано правило, але не до посилань, що відповідають `/logout`:
```

2024-04-13 11:09 UTC, AdriandeCita commented on files/uk/web/html/element/script/type/speculationrules/index.md
> +  - : Об'єкт, що представляє умови, за яких правило відповідає URL, що містяться в пов'язаному документі. Фактично, об'єкт `"where"` представляє перевірку, яка виконується для кожного посилання на ст
правило не відповідає, а знаходить відповідники
```suggestion
  - : Об'єкт, що представляє умови, за яких правило оцінює URL, що містяться в пов'язаному документі. Фактично, об'єкт `"where"` представляє перевірку, яка виконується для кожного посилання на сторінці, щоб визначити, чи застосовувати до нього правило спекуляції. В одному правилі не можна задати водночас як і `"where"`, так і `"urls"`.
```

2024-04-13 11:09 UTC, AdriandeCita commented on files/uk/web/html/element/script/type/speculationrules/index.md
> +      - : У випадку умови `"href_matches"`, це може вказувати, відносно чого повинна бути відносною умова. Це працює так само, як [ключ `"relative_to"` на рівні правила](/uk/docs/Web/HTML/Element/scr
"відносно чого ... відносна"
```suggestion
      - : У випадку умови `"href_matches"`, це може вказувати, відносно чого повинна застосовуватися умова. Це працює так само, як [ключ `"relative_to"` на рівні правила](/uk/docs/Web/HTML/Element/script/type/speculationrules#relative_to_2), за винятком того, що воно впливає лише на одну умову `"href_matches"` всередині ключа `"where"`.
```

2024-04-13 11:10 UTC, AdriandeCita commented on files/uk/web/html/element/script/type/speculationrules/index.md
> +  - : Рядок, що дає браузеру підказку щодо того, наскільки швидко він має попередньо завантажувати або попередньо візуалізувати цільову сторінку посилання, щоб збалансувати виграш щодо продуктивності
```suggestion
  - : Рядок, що дає браузеру підказку щодо того, наскільки швидко він має попередньо завантажувати або візуалізувати цільову сторінку посилання, щоб збалансувати виграш щодо продуктивності відносно витрат ресурсів. Можливі значення:
```

2024-04-13 11:13 UTC, AdriandeCita commented on files/uk/web/html/element/script/type/speculationrules/index.md
> +      - : Розробник прагне золотої середини між `eager` і `conservative`. Попереднє отримання або візуалізація має початися, коли є доцільна вказівка на те, що користувач перейде за посиланням у найб
Доцільність - це радше про відповідність меті, а тут мається на увазі "така, що є достатньо достовірною"
```suggestion
      - : Розробник прагне золотої середини між `eager` і `conservative`. Попереднє отримання або візуалізація має початися, коли є резонна вказівка на те, що користувач перейде за посиланням у найближчому майбутньому. Наприклад, він може прокрутити сторінку так, що посилання потрапить в область перегляду, або торкнутися його на якусь мить.
```

2024-04-13 11:16 UTC, AdriandeCita requested changes
декілька зауважень

2024-04-13 11:18 UTC, AdriandeCita requested changes
Декілька зауважень

2024-04-13 18:03 UTC, undead404 commented on files/uk/web/html/element/script/type/speculationrules/index.md
> +Що до наборів правил, які отримані зовні (наприклад, за допомогою заголовка відповіді {{httpheader("Speculation-Rules")}}), URL у правилах списку та патернах URL у правилах документа усталено розбира
По-моєму, тут не те малось на увазі...

2024-08-09 11:52 UTC, alinkedd reviewed
Relevant?

2024-11-06 08:17 UTC, undead404 reviewed
Relevant?

2024-12-25 21:16 UTC, AdriandeCita approved these changes

2024-12-25 21:34 UTC, merged