translation(HTML): web/html/element/section
webdoky/content pull request #2941
Opened 2024-04-05 07:23 UTC by undead404

2024-06-19 09:10 UTC, undead404 reviewed
Still relevant?

2024-07-16 16:14 UTC, alinkedd requested changes
(File parity review, not finished)

2024-07-16 16:14 UTC, alinkedd commented on files/uk/web/html/element/section/index.md
> +        >. Зверніть увагу на те, що елемент <code>&#x3C;section></code> повинен не бути нащадком елемента {{HTMLElement("address")}}.
Має бути на двох рядках

https://github.com/mdn/content/blob/main/files/en-us/web/html/element/section/index.md?plain=1#L129-L130

```suggestion
        >. Зверніть увагу на те, що елемент <code>&#x3C;section></code> повинен не бути 
        нащадком елемента {{HTMLElement("address")}}.
```

2024-07-16 16:14 UTC, alinkedd commented on files/uk/web/html/element/section/index.md
> +        >, якщо елемент має
Має бути на двох рядках

https://github.com/mdn/content/blob/main/files/en-us/web/html/element/section/index.md?plain=1#L140-L141

```suggestion
        >,
        якщо елемент має
```

2024-07-16 16:39 UTC, undead404 commented on files/uk/web/html/element/section/index.md
> +        >. Зверніть увагу на те, що елемент <code>&#x3C;section></code> повинен не бути нащадком елемента {{HTMLElement("address")}}.
Як я вже писав, ми не стежимо за порядковою відповідністю

2024-07-16 17:26 UTC, alinkedd commented on files/uk/web/html/element/section/index.md
> +        >. Зверніть увагу на те, що елемент <code>&#x3C;section></code> повинен не бути нащадком елемента {{HTMLElement("address")}}.
але ж тоді простіше порівнювати рядок у рядок і бачити різницю, гмм..

2024-07-16 17:28 UTC, undead404 commented on files/uk/web/html/element/section/index.md
> +        >. Зверніть увагу на те, що елемент <code>&#x3C;section></code> повинен не бути нащадком елемента {{HTMLElement("address")}}.
Можливо, але історично склалося, що нас по рядках від оригіналу MDN відділяв Prettier. Потім вони нас догнали з його використанням, але де-не-де різниця все одно лишилася

2024-08-08 16:06 UTC, undead404 commented
Ти тут ще будеш щось дивитися?

2024-08-08 16:12 UTC, alinkedd commented
@undead404 я поки переклади не дивлюсь, думаю добити оновлення на цьому тижні

2024-08-08 17:23 UTC, undead404 commented
Гаразд, прийнято

2024-11-03 13:05 UTC, alinkedd commented
Relevant?

2024-11-03 13:06 UTC, alinkedd reviewed
Relevant?

2024-11-29 14:07 UTC, alinkedd requested changes

2024-11-29 14:07 UTC, alinkedd commented on files/uk/web/html/element/section/index.md
> +Умови, за яких можна зустріти `<section>` без заголовка, зазвичай трапляються в розділах вебзастосунків або інтерфейсів користувача, а не в структурах традиційних документів. У документі не дуже логі
```suggestion
Умови, за яких можна зустріти `<section>` без заголовка, зазвичай трапляються в розділах вебзастосунків або інтерфейсів користувача, а не в структурах традиційних документів. У документі не дуже логічно мати окремий розділ вмісту без заголовка, що описує його вміст. Такі заголовки корисні для всіх читачів, але особливо корисні для користувачів допоміжних технологій, як-от читачі з екрана, а також вони добрі для SEO.
```

2024-11-29 14:07 UTC, alinkedd commented on files/uk/web/html/element/section/index.md
> +Або що на рахунок панелі кнопок для керування застосунком? Тоді не обов'язково потрібен заголовок, але це все одно окремий розділ документа:
```suggestion
Або як щодо панелі кнопок для керування застосунком? Тоді не обов'язково потрібен заголовок, але це все одно окремий розділ документа:
```
https://onlinecorrector.com.ua/%D1%89%D0%BE%D0%B4%D0%BE-%D0%BD%D0%B0-%D1%80%D0%B0%D1%85%D1%83%D0%BD%D0%BE%D0%BA/

2024-11-29 14:07 UTC, alinkedd commented on files/uk/web/html/element/section/index.md
> +- [Використання розділів і планів HTML](/uk/docs/Web/HTML/Element/Heading_Elements)
outlines - плани?

2024-11-29 14:55 UTC, undead404 commented on files/uk/web/html/element/section/index.md
> +- Якщо вміст елемента є самостійною, неподільною одиницею вмісту, яку є сенс синдикувати як самостійний твір (наприклад, допис у блозі чи коментар у блозі, або стаття у газеті), краще використовувати
```suggestion
- Якщо вміст елемента є самостійною, неподільною одиницею вмісту, яку є сенс подавати як самостійний твір (наприклад, допис у блозі чи коментар у блозі, або стаття у газеті), краще використовувати елемент {{HTMLElement("article")}}.
```

2024-11-29 14:55 UTC, undead404 commented on files/uk/web/html/element/section/index.md
> +- [Використання розділів і планів HTML](/uk/docs/Web/HTML/Element/Heading_Elements)
Так, у деяких випадках може бути "плани". У значенні "план тексту".

2024-12-25 21:05 UTC, AdriandeCita commented on files/uk/web/html/element/section/index.md
> +- Якщо вміст елемента є самостійною, неподільною одиницею вмісту, яку є сенс синдикувати як самостійний твір (наприклад, допис у блозі чи коментар у блозі, або стаття у газеті), краще використовувати
плюсую за "подавати"

2024-12-25 21:09 UTC, AdriandeCita requested changes
не маю інших зауважень, окрім "подавати"

2024-12-25 21:18 UTC, AdriandeCita approved these changes

2024-12-25 21:40 UTC, alinkedd approved these changes

2024-12-25 21:48 UTC, merged