update(CSS): web/css/text-align
webdoky/content pull request #2951
Opened 2024-04-12 09:45 UTC by undead404

2024-04-13 09:52 UTC, AdriandeCita commented on files/uk/web/css/text-align/index.md
> +Цей приклад демонструє, як використання `text-align` на елементах {{htmlelement("table")}}, в тому числі рядах {{htmlelement("tr")}} і комірках {{htmlelement("td")}}.
```suggestion
Цей приклад демонструє, як використовувати `text-align` на елементах {{htmlelement("table")}}, в тому числі рядах {{htmlelement("tr")}} і комірках {{htmlelement("td")}}.
```

2024-04-13 09:52 UTC, AdriandeCita approved these changes

2024-04-13 10:00 UTC, AdriandeCita requested changes
дрібничка

2024-07-22 22:10 UTC, alinkedd requested changes

2024-07-22 22:10 UTC, alinkedd commented on files/uk/web/css/text-align/index.md
> +Цей приклад демонструє, як використовувати `text-align` на елементах {{htmlelement("table")}}, в тому числі рядах {{htmlelement("tr")}} і комірках {{htmlelement("td")}}.
```suggestion
Цей приклад демонструє, як використовувати `text-align` на елементах {{htmlelement("table")}}, включно з рядами {{htmlelement("tr")}} і комірками {{htmlelement("td")}}.
```

2024-07-22 22:10 UTC, alinkedd commented on files/uk/web/css/text-align/index.md
> +Властивість `text-align` задається у вигляді одного ключового слова зі списку нижче.
```suggestion
Властивість `text-align` задається як одне ключове слово зі списку нижче.
```

2024-07-22 22:10 UTC, alinkedd commented on files/uk/web/css/text-align/index.md
на 54 рядку треба замінити `текст` на `вміст`

(як тут на 58 рядку https://github.com/mdn/content/commit/6c858b4def85320d7acecf9b1327409f3da57a60#diff-1fefb044af2f63283e00dfccb725bb8dc623c6dd64dc564f8a4b6fffa56151e8)

2024-07-23 06:52 UTC, alinkedd approved these changes

2024-07-23 07:48 UTC, merged