update(JS): web/javascript/guide/grammar_and_types
webdoky/content pull request #2968
Opened 2024-04-24 13:26 UTC by undead404

2024-07-15 20:47 UTC, alinkedd requested changes

2024-07-15 20:47 UTC, alinkedd commented on files/uk/web/javascript/guide/grammar_and_types/index.md
> +Оголошені з `var` змінні [піднімаються](/uk/docs/Glossary/Hoisting), тобто можна звертатися до змінної будь-де в її області видимості, навіть якщо виконання ще не дійшло до її оголошення. Оголошення
```suggestion
Оголошені з `var` змінні [піднімаються](/uk/docs/Glossary/Hoisting), тобто можна звертатися до змінної будь-де в її області видимості, навіть якщо виконання ще не дійшло до її оголошення. Оголошення змінної `var` можна розглядати як такі, що "піднімаються" до початку своєї функції або глобальної області видимості. Проте якщо звернутися до змінної до її оголошення, то її значення завжди буде `undefined`, оскільки піднімаються лише _оголошення_ та _початкова ініціалізація (значенням `undefined`)_, проте не _присвоєння значення_.
```

2024-07-16 07:45 UTC, undead404 commented on files/uk/web/javascript/guide/grammar_and_types/index.md
> +Оголошені з `var` змінні [піднімаються](/uk/docs/Glossary/Hoisting), тобто можна звертатися до змінної будь-де в її області видимості, навіть якщо виконання ще не дійшло до її оголошення. Оголошення
Ми практично всюди перекладаємо "default" як усталений, можливо, не варто ламати цю традицію?..

2024-07-16 09:08 UTC, alinkedd commented on files/uk/web/javascript/guide/grammar_and_types/index.md
> +Оголошені з `var` змінні [піднімаються](/uk/docs/Glossary/Hoisting), тобто можна звертатися до змінної будь-де в її області видимості, навіть якщо виконання ще не дійшло до її оголошення. Оголошення
зроз, може, створю ще одне issue :)

тоді ок

2024-07-16 09:09 UTC, alinkedd approved these changes

2024-07-16 09:10 UTC, alinkedd commented on files/uk/web/javascript/guide/grammar_and_types/index.md
> +Оголошені з `var` змінні [піднімаються](/uk/docs/Glossary/Hoisting), тобто можна звертатися до змінної будь-де в її області видимості, навіть якщо виконання ще не дійшло до її оголошення. Оголошення
(не можу резолвити, закрий, будь ласка)

2024-07-16 09:11 UTC, merged