update(CSS): web/css/css_box_model
webdoky/content pull request #2975
Opened 2024-04-27 07:08 UTC by undead404

2024-08-09 11:51 UTC, alinkedd reviewed
Relevant?

2024-08-09 19:36 UTC, alinkedd requested changes

2024-08-09 19:36 UTC, alinkedd commented on files/uk/web/css/css_box_model/index.md
> +Модуль **Рамкової моделі CSS** визначає властивості `height`, `width`, `margin` і `padding`, які разом зі [властивостями меж](/uk/docs/Web/CSS/CSS_backgrounds_and_borders) утворюють [рамкову модель](
```suggestion
Модуль **Рамкової моделі CSS** визначає властивості `height`, `width`, `margin` і `padding`, які разом із [властивостями меж](/uk/docs/Web/CSS/CSS_backgrounds_and_borders) утворюють [рамкову модель](/uk/docs/Web/CSS/CSS_box_model/Introduction_to_the_CSS_box_model) CSS.
```

2024-08-09 19:36 UTC, alinkedd commented on files/uk/web/css/css_box_model/index.md
> +Кожний видимий елемент на вебсторінці – це рамка, скомпонована згідно з [моделлю візуального форматування](/uk/docs/Web/CSS/Visual_formatting_model). Властивості CSS визначають для цих рамок їхні роз
```suggestion
Кожний видимий елемент на вебсторінці – це рамка, скомпонована згідно з [моделлю візуального форматування](/uk/docs/Web/CSS/Visual_formatting_model). Властивості CSS визначають для цих рамок їхні розмір, положення та рівень у нагромадженні (stacking level), а властивості рамкової моделі (серед інших) визначають власний розмір кожної рамки та вільний простір навколо неї.
```

2024-08-09 19:36 UTC, alinkedd commented on files/uk/web/css/css_box_model/index.md
> +Кожний видимий елемент на вебсторінці – це рамка, скомпонована згідно з [моделлю візуального форматування](/uk/docs/Web/CSS/Visual_formatting_model). Властивості CSS визначають для цих рамок їхні роз
intrinsic та extrinsic розмір - тут про це https://developer.mozilla.org/en-US/docs/Glossary/Intrinsic_Size або https://www.w3.org/TR/css-sizing-3/#extrinsic

якщо intrinsic - це природній (у цій статті власний), то extrinsic - це набутий, отриманий, контекстний?
чи розмір відносно контенту і розмір відносно контексту?
треба думати

2024-08-09 19:36 UTC, alinkedd commented on files/uk/web/css/css_box_model/index.md
> +Кожна рамка має прямокутну область вмісту, всередині якої виводяться текст, зображення та інший вміст. Цей вміст може бути оточений внутрішніми відступами, межею та зовнішніми відступами, на одному а
```suggestion
Кожна рамка має прямокутну область вмісту, всередині якої виводяться текст, зображення та інший вміст. Цей вміст може бути оточений внутрішніми відступами, межею та зовнішніми відступами на одному або декількох боках. Внутрішні відступи – навколо вмісту, межа – навколо внутрішніх відступів, а зовнішні відступи – поза межами. Рамкова модель описує, як ці аспекти – вміст, внутрішні відступи, межі та зовнішні відступи – взаємодіють для утворення рамки, яку відображає CSS.
```

2024-08-09 19:36 UTC, alinkedd commented on files/uk/web/css/css_box_model/index.md
> +  - {{cssxref("border-width")}} shorthand
```suggestion
  - Скорочення {{cssxref("border-width")}}
```

2024-08-09 19:36 UTC, alinkedd commented on files/uk/web/css/css_box_model/index.md
> +  - {{CSSxRef("overflow")}} shorthand
```suggestion
  - Скорочення {{CSSxRef("overflow")}}
```

2024-08-09 20:59 UTC, undead404 commented on files/uk/web/css/css_box_model/index.md
> +Кожний видимий елемент на вебсторінці – це рамка, скомпонована згідно з [моделлю візуального форматування](/uk/docs/Web/CSS/Visual_formatting_model). Властивості CSS визначають для цих рамок їхні роз
Я б переклав як "нав'язаний", щоб звучало як антонім до "природний"

2024-08-09 21:02 UTC, alinkedd commented on files/uk/web/css/css_box_model/index.md
> +Кожний видимий елемент на вебсторінці – це рамка, скомпонована згідно з [моделлю візуального форматування](/uk/docs/Web/CSS/Visual_formatting_model). Властивості CSS визначають для цих рамок їхні роз
просто у спеці

- Extrinsic sizing determines sizes based on the context of an element, without regard for its contents. 
- Intrinsic sizing determines sizes based on the contents of an element, without regard for its context. 

я тепер не впевнена, що ці терміни взагалі треба перекладати природний/нав'язаний

2024-08-09 21:16 UTC, undead404 commented on files/uk/web/css/css_box_model/index.md
> +Кожний видимий елемент на вебсторінці – це рамка, скомпонована згідно з [моделлю візуального форматування](/uk/docs/Web/CSS/Visual_formatting_model). Властивості CSS визначають для цих рамок їхні роз
Притаманний і зумовлений?

2024-08-09 21:17 UTC, alinkedd commented on files/uk/web/css/css_box_model/index.md
> +Кожний видимий елемент на вебсторінці – це рамка, скомпонована згідно з [моделлю візуального форматування](/uk/docs/Web/CSS/Visual_formatting_model). Властивості CSS визначають для цих рамок їхні роз
розмір зсередини, розмір ззовні :smiley: 
треба на обговорення у чат

2024-08-23 10:23 UTC, alinkedd commented on files/uk/web/css/css_box_model/index.md
> +Кожний видимий елемент на вебсторінці – це рамка, скомпонована згідно з [моделлю візуального форматування](/uk/docs/Web/CSS/Visual_formatting_model). Властивості CSS визначають для цих рамок їхні роз
@undead404 ви це не обговорили на дзвінку?

2024-08-23 10:40 UTC, undead404 commented on files/uk/web/css/css_box_model/index.md
> +Кожний видимий елемент на вебсторінці – це рамка, скомпонована згідно з [моделлю візуального форматування](/uk/docs/Web/CSS/Visual_formatting_model). Властивості CSS визначають для цих рамок їхні роз
@alinkedd безтолкові ми без тебе

2024-08-28 15:12 UTC, alinkedd commented on files/uk/web/css/css_box_model/index.md
> +Кожний видимий елемент на вебсторінці – це рамка, скомпонована згідно з [моделлю візуального форматування](/uk/docs/Web/CSS/Visual_formatting_model). Властивості CSS визначають для цих рамок їхні роз
@undead404 тільки оце тоді зроби https://github.com/webdoky/content/pull/2975#discussion_r1712014060

а бесіду відтянемо до вирішення #3348

2024-08-28 17:50 UTC, alinkedd approved these changes

2024-08-28 18:14 UTC, merged