update(CSS): web/css/css_colors/applying_color
webdoky/content pull request #2982
Opened 2024-05-16 14:32 UTC by undead404

Оригінальний вміст: [Застосування кольору до елементів HTML за допомогою CSS@MDN](https://developer.mozilla.org/en-us/docs/Web/CSS/CSS_colors/Applying_color), [сирці Застосування кольору до елементів HTML за допомогою CSS@GitHub](https://github.com/mdn/content/blob/main/files/en-us/web/css/css_colors/applying_color/index.md)

Нові зміни:
- [chore: convert some noteblocks (#35180)](https://github.com/mdn/content/commit/cdb23fdf261a071951e1e46a0a6c7bc6daa691ff)
- [chore: convert noteblocks for `/web/css` (part 2) (#35148)](https://github.com/mdn/content/commit/4e508e2f543c0d77c9c04f406ebc8e9db7e965be)
- [New color guides and some associated link updates (#33071)](https://github.com/mdn/content/commit/5f13cbe7517ce96deeb521d4c8e6923266a22913)

2024-05-16 14:38 UTC, undead404 commented on files/uk/web/css/css_colors/applying_color/index.md
> +  - : Колір для використання при нанесенні окреслення навколо елемента. Це окреслення відрізняється від меж тим, що для нього не відводиться місце в документі. Окреслення не бере участі в [рамковій м
```suggestion
  - : Колір для використання при нанесенні окреслення навколо елемента. Це окреслення відрізняється від меж тим, що для нього не відводиться місце в документі. Окреслення не бере участі в [рамковій моделі](/uk/docs/Learn/CSS/Building_blocks/The_box_model), накладаючись на інший вміст. Зазвичай окреслення використовується як ознака фокуса, показуючи, який елемент наразі має фокус і отримає події введення з клавіатури.
```

2024-05-16 14:38 UTC, undead404 commented on files/uk/web/css/css_colors/applying_color/index.md
> +  - : Дає змогу створювати зображення за допомогою команд, що наносять конкретні фігури, патерни та лінії. Команди SVG форматуються як XML, і можуть бути вбудовані безпосередньо в веб-сторінку або ро
```suggestion
  - : Дає змогу створювати зображення за допомогою команд, що наносять конкретні фігури, патерни та лінії. Команди SVG форматуються як XML, і можуть бути вбудовані безпосередньо в вебсторінку або розміщені на сторінці за допомогою елемента {{HTMLElement("img")}}, як будь-який інший тип зображення.
```

2024-05-16 14:38 UTC, undead404 commented on files/uk/web/css/css_colors/applying_color/index.md
> +  - : Бібліотека вебграфіки – це API OpenGL, застований на ES, для нанесення високопродуктивної двовимірної та тривимірної графіки у Вебі. Дивіться наш [Підручник з WebGL](/uk/docs/Web/API/WebGL_API/
```suggestion
  - : Бібліотека вебграфіки – це API OpenGL, заснований на ES, для нанесення високопродуктивної двовимірної та тривимірної графіки у Вебі. Дивіться наш [Підручник з WebGL](/uk/docs/Web/API/WebGL_API/Tutorial), щоб дізнатися більше. Також дивіться [WebGPU](/uk/docs/Web/API/WebGPU_API), наступника WebGL для сучасних графічних процесорів.
```

2024-08-03 08:19 UTC, undead404 reviewed
Relevant?

2024-08-03 10:46 UTC, undead404 commented on files/uk/web/javascript/reference/global_objects/array/index.md
> +> [!NOTE]
```suggestion
> [!NOTE] 
```

2024-08-03 10:47 UTC, undead404 reviewed
Relevant?

2024-08-03 14:48 UTC, KlashReik commented on files/uk/web/css/css_colors/applying_color/index.md
> +- : Колір до застосування при нанесенні тексту та будь-яких [прикрас тексту](/uk/docs/Learn/CSS/Styling_text/Fundamentals#font-style-font-weight-text-transform-i-text-decoration) (наприклад, додаванн
Як на мене, то попередній варіант був кращим

2024-08-03 14:52 UTC, KlashReik commented on files/uk/web/css/css_colors/applying_color/index.md
> +  - : Усталеним кольором прикрас тексту є [`currentcolor`](/uk/docs/Web/CSS/color_value#kliuchove-slovo-currentcolor). Це ключове слово представляє поточне значення властивості `color`. Однак це знач
```suggestion
  - : Усталеним кольором прикрас тексту (таких як підкреслення, перекреслення тощо) є [`currentcolor`](/uk/docs/Web/CSS/color_value#kliuchove-slovo-currentcolor). Це ключове слово представляє поточне значення властивості `color`. Однак це значення можна перевизначити та використати для них інший колір, використовуючи властивість `text-decoration-color`.
```

В оригіналі: The default text decorations (such as underlines, strikethroughs, etc.) color is [currentcolor].

2024-08-03 14:57 UTC, KlashReik commented on files/uk/web/css/css_colors/applying_color/index.md
> +  - : Колір для використання при нанесенні окреслення навколо елемента. Це окреслення відрізняється від меж тим, що для нього не відводиться місце в документі. Окреслення не бере участі в [рамковій м
Нещодавно в чаті бачив, що outline - обрис. Треба глосарій...

2024-08-03 15:03 UTC, KlashReik requested changes

2024-08-03 16:53 UTC, undead404 commented on files/uk/web/css/css_colors/applying_color/index.md
> +- : Колір до застосування при нанесенні тексту та будь-яких [прикрас тексту](/uk/docs/Learn/CSS/Styling_text/Fundamentals#font-style-font-weight-text-transform-i-text-decoration) (наприклад, додаванн
То що будемо робить? Запропонуєш як краще?

2024-08-03 16:53 UTC, undead404 commented on files/uk/web/css/css_colors/applying_color/index.md
> +  - : Колір для використання при нанесенні окреслення навколо елемента. Це окреслення відрізняється від меж тим, що для нього не відводиться місце в документі. Окреслення не бере участі в [рамковій м
Так, плутаюся сам

2024-08-05 14:31 UTC, KlashReik approved these changes

2024-08-05 14:32 UTC, merged