update(HTML): web/html/element/script
webdoky/content pull request #2996
Opened 2024-05-17 13:37 UTC by undead404

2024-08-01 14:19 UTC, alinkedd requested changes

2024-08-01 14:19 UTC, alinkedd commented on files/uk/web/html/element/script/index.md
> +    > Значення порожнього рядка (`""`) є водночас і усталеним значенням, і запасним значенням, коли `referrerpolicy` не підтримується. Якщо `referrerpolicy` не вказаний явно на елементі `<script>`, т
```suggestion
    > Значення порожнього рядка (`""`) є водночас і усталеним значенням, і запасним значенням, коли `referrerpolicy` не підтримується. Якщо `referrerpolicy` не вказаний явно на елементі `<script>`, то буде прийнята політика посилача вищого рівня, тобто та, що встановлена для всього документа чи всього домену. Якщо політика вищого рівня не доступна, то порожній рядок розглядається як еквівалент до `strict-origin-when-cross-origin`.
```
якщо прикметник виступає дієсловом, то тоді частка заперечення "не" пишеться окремо

2024-08-01 14:19 UTC, alinkedd commented on files/uk/web/html/element/script/index.md
> +Сценарії, завантажені з використанням атрибуту `async`, завантажують сценарій без блокування сторінки, поки сценарій отримується.
```suggestion
Сценарії, завантажені з використанням атрибута `async`, завантажують сценарій без блокування сторінки під час його отримання.
```

2024-08-01 14:19 UTC, alinkedd commented on files/uk/web/html/element/script/index.md
> +Проте щойно завантаження завершилось, такий сценарій виконується, що блокує візуалізацію сторінки. Таким чином, решта вмісту вебсторінки не може оброблятися та виводитися користувачу, поки цей сценар
```suggestion
Проте щойно завантаження завершилось, такий сценарій виконується, що блокує візуалізацію сторінки. Отже, решта вмісту вебсторінки не може оброблятися та виводитися користувачу, поки цей сценарій не завершить виконання.
```

2024-08-01 14:19 UTC, alinkedd commented on files/uk/web/html/element/script/index.md
> +Найкраще використовувати `async` тоді, коли сценарії на сторінці спрацьовують незалежно одне від одного та не залежать від жодних інших сценаріїв на сторінці.
```suggestion
Немає гарантії, що сценарії будуть виконуватися у певному порядку.
Найкраще використовувати `async` тоді, коли сценарії на сторінці спрацьовують незалежно один від одного та не залежать від жодних інших сценаріїв на сторінці.
```

2024-08-01 14:19 UTC, alinkedd commented on files/uk/web/html/element/script/index.md
> +Сценарії, завантажені з використанням атрибуту `defer`, завантажуються в тому порядку, в якому зустрічаються на сторінці.
```suggestion
Сценарії, завантажені з використанням атрибута `defer`, завантажуються в тому порядку, в якому зустрічаються на сторінці.
```

2024-08-01 14:19 UTC, alinkedd commented on files/uk/web/html/element/script/index.md
> +_Це зображення, взяте зі [специфікації HTML](https://html.spec.whatwg.org/images/asyncdefer.svg), скопійоване та обрізане, передбуває під ліцензією [CC BY 4.0](https://creativecommons.org/licenses/by
```suggestion
_Це зображення, взяте зі [специфікації HTML](https://html.spec.whatwg.org/images/asyncdefer.svg), скопійоване та обрізане, перебуває під ліцензією [CC BY 4.0](https://creativecommons.org/licenses/by/4.0/)._
```

2024-08-01 14:19 UTC, alinkedd commented on files/uk/web/html/element/script/index.md
> +У другому прикладі можна мати певність, що `jquery.js` завантажиться до `script2.js` і `script3.js`, і що `script2.js` завантажиться до `script3.js`.
```suggestion
У другому прикладі можна мати певність, що `jquery.js` завантажиться до `script2.js` і `script3.js`, а `script2.js` – до `script3.js`.
```

2024-08-01 14:19 UTC, alinkedd commented on files/uk/web/html/element/script/index.md
> +- як `async`, так і `defer` вказують браузеру завантажити сценарій (або сценарії) в окремому потоці, поки завантажується решта сторінки (DOM тощо), тож завантаження сторінки не блокується під час про
```suggestion
- і `async`, і `defer` вказують браузеру завантажити сценарій (або сценарії) в окремому потоці, поки завантажується решта сторінки (DOM тощо), тож завантаження сторінки не блокується під час процесу отримання сценарію.
```

2024-08-01 21:20 UTC, alinkedd commented on files/uk/web/html/element/script/index.md
> +  - : Задає те, що ви хочете, аби браузер надіслав вкупі з запитом на ресурс сценарію заголовок {{httpheader("Attribution-Reporting-Eligible")}}. На серверному боці такий заголовок використовується д
засноване на зображенні - JavaScript-based, шось не туди
@undead404

2024-08-02 05:30 UTC, undead404 commented on files/uk/web/html/element/script/index.md
> +  - : Задає те, що ви хочете, аби браузер надіслав заголовок {{httpheader("Attribution-Reporting-Eligible")}} вкупі з запитом на ресурс сценарію. На серверному боці такий заголовок використовується д
```suggestion
  - : Задає те, що ви хочете, аби браузер надіслав заголовок {{httpheader("Attribution-Reporting-Eligible")}} вкупі з запитом на ресурс сценарію. На серверному боці такий заголовок використовується для запуску надсилання у відповіді заголовка {{httpheader("Attribution-Reporting-Register-Source")}} або {{httpheader("Attribution-Reporting-Register-Trigger")}}, щоб зареєструвати засноване на JavaScript [джерело атрибуції](/uk/docs/Web/API/Attribution_Reporting_API/Registering_sources#dzherela-podii-na-osnovi-html) або [пускача атрибуції](/uk/docs/Web/API/Attribution_Reporting_API/Registering_triggers#puskach-atrybutsii-na-osnovi-html) відповідно. Те, який заголовок відповіді слід надсилати у відповідь, залежить від значення заголовка `Attribution-Reporting-Eligible`, що спричинив реєстрацію.
```
@alinkedd дякую

2024-08-02 15:28 UTC, alinkedd approved these changes

2024-08-02 15:29 UTC, merged