Update/web html element video
webdoky/content pull request #3019
Opened 2024-06-19 08:01 UTC by undead404

2024-07-16 10:39 UTC, undead404 commented on files/uk/web/html/element/video/index.md
> +Хронометровані текстові доріжки з титрами, закритими субтитрами, заголовками розділів і так далі можна декларативно додавати, вкладаючи їх у елемент {{HTMLElement("track")}}.
```suggestion
Хронометровані текстові доріжки з титрами, закритими субтитрами, заголовками розділів і так далі можна декларативно додавати, вкладаючи їх в елемент {{HTMLElement("track")}}.
```

2024-07-16 10:39 UTC, undead404 commented on files/uk/web/html/element/video/index.md
> +  - : {{domxref("TextTrackList")}}, що вміщає усі текстові доріжки медійного елемента (які використовуються як титри, закриті субтитри і так далі).
```suggestion
  - : {{domxref("TextTrackList")}}, що вміщає усі текстові доріжки медійного елемента (які використовуються як титри, закриті субтитри й так далі).
```

2024-08-08 17:30 UTC, alinkedd requested changes

2024-08-08 17:30 UTC, alinkedd commented on files/uk/web/html/element/video/index.md
>    - : Булів атрибут; коли вказаний, то відео автоматично починає відтворення, щойно може, не зупиняючи закінчення завантаження даних
```suggestion
  - : Булів атрибут; коли вказаний, то відео автоматично починає відтворення, щойно може зробити це без зупинки для закінчення завантаження даних.
```

2024-08-08 17:30 UTC, alinkedd commented on files/uk/web/html/element/video/index.md
> +  - : Булів атрибут, що вказує усталене налаштування заглушення для аудіо, включеного у відео. Якщо встановлений, то аудіо спершу буде заглушене. Усталене значення – `false`, отже – аудіо буде відтво
```suggestion
  - : Булів атрибут, що вказує усталене налаштування заглушення для аудіо, включеного у відео. Якщо встановлений, то аудіо спершу буде заглушене. Усталене значення – `false`, тому аудіо буде відтворено разом з відтворенням відео.
```

2024-08-08 17:30 UTC, alinkedd commented on files/uk/web/html/element/video/index.md
> +Спершу виконується спроба відтворити AVI. Якщо це не вдається, наступна спроба [MP4](/uk/docs/Web/Media/Formats/Containers#mpeg-4_mp4). Запасне повідомлення виводиться, якщо елемент video не підтриму
```suggestion
Спершу виконується спроба відтворити AVI. Якщо це не вдається, то [MP4](/uk/docs/Web/Media/Formats/Containers#mpeg-4_mp4). Запасне повідомлення виводиться, якщо елемент video не підтримується, але не тоді, коли всі джерела не спрацьовують.
```

2024-08-08 17:30 UTC, alinkedd commented on files/uk/web/html/element/video/index.md
> +Додавання й видалення з елемента `<video>` доріжок можна відстежувати за допомогою подій {{domxref("VideoTrackList/addtrack_event", "addtrack")}} і {{domxref("VideoTrackList/removetrack_event", "remo
```suggestion
Додавання й видалення доріжок з елемента `<video>` можна відстежувати за допомогою подій {{domxref("VideoTrackList/addtrack_event", "addtrack")}} і {{domxref("VideoTrackList/removetrack_event", "removetrack")}}. Втім, ці події не надсилаються до самого елемента `<video>`.
```

2024-08-08 17:30 UTC, alinkedd commented on files/uk/web/html/element/video/index.md
> +Натомість вони надсилаються до об'єкта списку доріжок всередині {{domxref("HTMLMediaElement")}} елемента `<video>`, що відповідає типові доріжки, котра була додана:
```suggestion
Натомість вони надсилаються до об'єкта списку доріжок всередині {{domxref("HTMLMediaElement")}} елемента `<video>`, що відповідає типу доріжки, котра була додана:
```

2024-08-08 17:30 UTC, alinkedd commented on files/uk/web/html/element/video/index.md
> +    > Сучасні браузери блокують автоматичне відтворення аудіо (та відео з незаглушеною аудіостежиною), адже сайти, що автоматично відтворюють аудіо, можуть бути неприємними для користувачів. Дивіться
```suggestion
    > Сучасні браузери блокують автоматичне відтворення аудіо (та відео з незаглушеною аудіодоріжкою), адже сайти, що автоматично відтворюють аудіо, можуть бути неприємними для користувачів. Дивіться додаткову інформацію про те, як правильно користуватися автоматичним відтворенням, у нашому [посібнику з автоматичного відтворення](/uk/docs/Web/Media/Autoplay_guide)
```

2024-08-08 17:30 UTC, alinkedd commented on files/uk/web/html/element/video/index.md
> +          нуль чи більше елементів {{HTMLElement("track")}}, після котрих – прозорий вміст, що не містить мультимедійних елементів, тобто жодних {{HTMLElement("audio")}} чи <code>&lt;video&gt;</code>
```suggestion
          нуль чи більше елементів {{HTMLElement("track")}}, за якими прозорий вміст, що не містить мультимедійних елементів, тобто жодних {{HTMLElement("audio")}} чи <code>&lt;video&gt;</code>.
```

2024-08-08 17:30 UTC, alinkedd commented on files/uk/web/html/element/video/index.md
> +          Інакше: нуль чи більше елементів {{HTMLElement("source")}}, після котрих – нуль чи більше елементів {{HTMLElement("track")}}, після котрих – прозорий вміст, що не містить мультимедійних еле
```suggestion
          Інакше: нуль чи більше елементів {{HTMLElement("source")}}, за якими нуль чи більше елементів {{HTMLElement("track")}}, за якими прозорий вміст, що не містить мультимедійних елементів, тобто жодних {{HTMLElement("audio")}} чи <code>&lt;video&gt;</code>.
```

2024-08-08 17:30 UTC, alinkedd commented on files/uk/web/html/element/video/index.md
> +    > [!NOTE]
на 81 рядку ще

2024-08-08 20:28 UTC, alinkedd approved these changes

2024-08-08 20:46 UTC, merged