update(JS): web/javascript/reference/global_objects/promise
webdoky/content pull request #3021
Opened 2024-06-19 08:25 UTC by undead404

2024-06-21 12:39 UTC, undead404 commented on files/uk/web/javascript/reference/global_objects/promise/index.md
> +Наприклад, у коді вище, якщо `myPromise` відхиляється, то викликається `handleRejectedA`, і якщо `handleRejectedA` завершиться нормально (без викидання помилки чи повернення відхиленого проміса), то
```suggestion
Наприклад, у коді вище, якщо `myPromise` відхиляється, то викликається `handleRejectedA`, і якщо `handleRejectedA` завершиться нормально (без викидання помилки чи повернення відхиленого проміса), то проміс, повернений першим `then`, буде сповнений, а не залишиться відхиленим. Тому, якщо помилку треба обробити негайно, але потрібно зберегти стан помилки для використання в ланцюжку, необхідно викинути помилку певного типу в обробнику відхилення. З іншого боку, якщо немає негайної потреби, простіше покласти обробку помилок на останній обробник `catch()`.
```

2024-06-21 12:39 UTC, undead404 commented on files/uk/web/javascript/reference/global_objects/promise/index.md
> +Можна прив'язати якусь дію до вже залагодженого промісу. У цьому випадку дія додається в кінець черги завдань негайно, і виконується, коли завершуютьсяя всі наявні завдання. Таким чином, дія для вже
```suggestion
Можна прив'язати якусь дію до вже залагодженого промісу. У цьому випадку дія додається в кінець черги завдань негайно, і виконується, коли завершуються всі наявні завдання. Таким чином, дія для вже "залагодженого" промісу відбудеться лише після завершення поточного синхронного коду та принаймні одного циклу обробки. Це створює гарантію того, що дії промісів – асинхронні.
```

2024-07-16 11:05 UTC, undead404 commented on files/uk/web/javascript/reference/global_objects/promise/index.md
> +`Promise` – це заміна для значення, яке, як правило, невідоме на момент, коли проміс створюється. Він дає змогу прив'язати обробники до результату успішного виконання чи до причини невдачі асинхронно
@alinkedd ось іще одна кумедна ситуація

2024-08-08 15:39 UTC, alinkedd commented on files/uk/web/javascript/reference/global_objects/promise/index.md
> +`Promise` – це заміна для значення, яке, як правило, невідоме на момент, коли проміс створюється. Він дає змогу прив'язати обробники до результату успішного виконання чи до причини невдачі асинхронно
same
https://github.com/webdoky/content/pull/3242#discussion_r1709215540

2024-08-08 20:38 UTC, alinkedd requested changes

2024-08-08 20:38 UTC, alinkedd commented on files/uk/web/javascript/reference/global_objects/promise/index.md
> +Можна прив'язати якусь дію до вже залагодженого промісу. У цьому випадку дія додається в кінець черги завдань негайно, і виконується, коли завершуються всі наявні завдання. Таким чином, дія для вже "
```suggestion
Можна прив'язати якусь дію до вже залагодженого промісу. У цьому випадку дія додається в кінець черги завдань негайно і виконується, коли завершуються всі наявні завдання. У такий спосіб дія для вже "залагодженого" промісу відбудеться лише після завершення поточного синхронного коду та принаймні одного циклу обробки. Це створює гарантію того, що дії промісів – асинхронні.
```

2024-08-08 20:48 UTC, undead404 commented on files/uk/web/javascript/reference/global_objects/promise/index.md
> +Методи промісів {{jsxref("Promise/then", "then()")}}, {{jsxref("Promise/catch", "catch()")}} і {{jsxref("Promise/finally", "finally()")}} використовуються, щоб приєднати якусь наступну дію до промісу
Може й так, але я таке прямо перекладаю, тому fulfillment – сповнення

2024-08-09 12:12 UTC, alinkedd commented on files/uk/web/javascript/reference/global_objects/promise/index.md
> +Методи промісів {{jsxref("Promise/then", "then()")}}, {{jsxref("Promise/catch", "catch()")}} і {{jsxref("Promise/finally", "finally()")}} використовуються, щоб приєднати якусь наступну дію до промісу
ок

2024-08-09 12:12 UTC, alinkedd approved these changes

2024-08-09 12:41 UTC, merged