update(CSS): web/css/background-image
webdoky/content pull request #3025
Opened 2024-06-19 08:50 UTC by undead404

2024-07-16 14:46 UTC, alinkedd requested changes

2024-07-16 14:46 UTC, alinkedd commented on files/uk/web/css/background-image/index.md
> +Співвідношення колірного контрасту визначається шляхом порівняння світності тексту та значень кольору тла. Щоб відповідати вимогам [Настанов з доступності вебвмісту (WCAG)](https://www.w3.org/WAI/sta
```suggestion
Співвідношення колірного контрасту визначається шляхом порівняння яскравості (luminance) значень кольорів тексту і тла. Щоб відповідати вимогам [Настанов із доступності вебвмісту (WCAG)](https://www.w3.org/WAI/standards-guidelines/wcag/), потрібне співвідношення 4,5:1 для текстового вмісту тіла сторінки та 3:1 для більшого тексту, як-от заголовки. Великий текст визначається як 24px або більше, або [жирний текст](/uk/docs/Web/CSS/font-weight) 18.66px або більше.
```
1. виправила порядок слів
2. luminance - яскравість (https://uk.wikipedia.org/wiki/%D0%AF%D1%81%D0%BA%D1%80%D0%B0%D0%B2%D1%96%D1%81%D1%82%D1%8C)
3. із між приголосними
4. https://onlinecorrector.com.ua/uk/%D1%8F%D0%BA-%D0%BE%D1%82/
5. bold - жирний (для тексту) (звичайний, курсив, напівжирний, жирний)

2024-07-16 14:46 UTC, alinkedd commented on files/uk/web/css/background-image/index.md
> +      farthest-corner, #fc1c14 20%, #cf15cf 80%);
зберегти оригінальне форматування
```suggestion
background-image: radial-gradient(circle, #0000 45%, #000f 48%),
  radial-gradient(ellipse farthest-corner, #fc1c14 20%, #cf15cf 80%);
```
https://github.com/mdn/content/blob/main/files/en-us/web/css/background-image/index.md?plain=1#L30-L31

2024-07-16 14:46 UTC, alinkedd commented on files/uk/web/css/background-image/index.md
треба ще викинути ось оце (один пустий рядок і 4 рядки до градієнтів)

```

  - {{cssxref("cross-fade", "cross-fade()")}}
  - {{cssxref("element", "element()")}}
  - {{cssxref("image/image", "image()")}}
  - {{cssxref("image/image-set", "image-set()")}}
```

- коміт https://github.com/mdn/content/commit/95168b5d90db944146761aec99a462ecf857234a
- зараз https://github.com/mdn/content/blob/main/files/en-us/web/css/background-image/index.md?plain=1#L129

2024-07-16 14:46 UTC, alinkedd commented on files/uk/web/css/background-image/index.md
> +
тут пустого рядка не треба

2024-07-16 14:46 UTC, alinkedd commented on files/uk/web/css/background-image/index.md
> +- [Реалізація спрайтових зображень на CSS](/uk/docs/Web/CSS/CSS_images/Implementing_image_sprites_in_CSS)
```suggestion
- [Реалізація спрайтових зображень у CSS](/uk/docs/Web/CSS/CSS_images/Implementing_image_sprites_in_CSS)
```
або
```suggestion
- [Реалізація спрайтових зображень за допомогою CSS](/uk/docs/Web/CSS/CSS_images/Implementing_image_sprites_in_CSS)
```

2024-07-16 14:46 UTC, alinkedd commented on files/uk/web/css/background-image/index.md
> +- Властивості, пов'язані з фонами
тут і нижче: фон чи тло?
бо знизу фон, а зверху тло, виберіть щось одне

2024-07-16 17:16 UTC, alinkedd commented on files/uk/web/css/background-image/index.md
> +- Властивості, пов'язані з фонами
окей, закривай

2024-07-16 17:17 UTC, undead404 commented on files/uk/web/css/background-image/index.md
>    - {{cssxref("element", "element()")}}
```suggestion
```

2024-07-16 17:17 UTC, undead404 commented on files/uk/web/css/background-image/index.md
>    - {{cssxref("image/image", "image()")}}
```suggestion
```

2024-07-16 17:17 UTC, undead404 commented on files/uk/web/css/background-image/index.md
>    - {{cssxref("image/image-set", "image-set()")}}
```suggestion
```

2024-07-16 17:19 UTC, alinkedd commented on files/uk/web/css/background-image/index.md
> +Співвідношення колірного контрасту визначається шляхом порівняння світності тексту та значень кольору тла. Щоб відповідати вимогам [Настанов з доступності вебвмісту (WCAG)](https://www.w3.org/WAI/sta
Це фізика, а не варіанти :)
Luminance - Яскравість
Luminosity - Світність
Illuminance - Освітленість
типу ми не можемо вибирати будь-яке, це пряме поняття, але так як у яскравості більше значень, то я прямо додала в дужках (luminance)

2024-07-16 17:37 UTC, undead404 commented on files/uk/web/css/background-image/index.md
> +Співвідношення колірного контрасту визначається шляхом порівняння світності тексту та значень кольору тла. Щоб відповідати вимогам [Настанов з доступності вебвмісту (WCAG)](https://www.w3.org/WAI/sta
Мені інтуїтивне сприйняття не дає погодитися, бо коли інтуїтивно думаю, який в слова "яскравий" антонім, то перше, що спадає на думку — це "блідий".

Пропоную вирішити колегіально

2024-07-23 10:45 UTC, alinkedd approved these changes

2024-07-23 10:53 UTC, merged