update(CSS): web/css/font-family
webdoky/content pull request #3032
Opened 2024-06-21 13:49 UTC by undead404

2024-07-15 20:27 UTC, alinkedd requested changes

2024-07-15 20:27 UTC, alinkedd commented on files/uk/web/css/font-family/index.md
> +Властивість [CSS](/uk/docs/Web/CSS) **`font-family`** (сімейство шрифту) встановлює для обраного елемента список за пріоритетом з одного або кількох сімейств шрифту та (або) загальних імен сімейств.
```suggestion
Властивість [CSS](/uk/docs/Web/CSS) **`font-family`** (сімейство шрифтів) встановлює для обраного елемента список за пріоритетом з одного або кількох імен сімейств шрифтів та (або) загальних сімейств.
```
(Я знаю, що змінилось тільки посилання, але можна виправити разом.
- коли перекладаємо вираз з двох англійських іменників зі збірним значенням, то треба у множині писати підпорядковане слово
- font family names and/or generic family names => names of font families and/or generic families, тому змінило позицію `імен`
)

2024-07-15 20:27 UTC, alinkedd commented on files/uk/web/css/font-family/index.md
> +Властивість [CSS](/uk/docs/Web/CSS) **`font-family`** (сімейство шрифту) встановлює для обраного елемента список за пріоритетом з одного або кількох сімейств шрифту та (або) загальних імен сімейств.
З іншого боку, я бачу, що сімейство шрифту у всьому тексті, то тоді краще винести цю зміну в issue і потім обговорити і замінити

2024-07-15 20:27 UTC, alinkedd commented on files/uk/web/css/font-family/index.md
> +  - : Ім'я сімейства шрифту. Це повинно бути або одне {{cssxref("string", "рядкове")}} значення, або розділена пробілами послідовність значень {{cssxref("custom-ident")}}. Рядкові значення повинні бу
кастомні -> власні, створені власноруч

2024-07-15 20:27 UTC, alinkedd commented on files/uk/web/css/font-family/index.md
> +    Дивіться також [Дійсні імена сімейств](#diisni-imena-simeistv).
- (тут і далі) Valid як дійсний -> чинний, правильний, прийнятний (тут, бо далі список правильних варіантів)? (винести в окреме issue?)
- назви розділів і підрозділів треба брати в лапки

2024-07-16 07:39 UTC, undead404 commented on files/uk/web/css/font-family/index.md
> +Властивість [CSS](/uk/docs/Web/CSS) **`font-family`** (сімейство шрифту) встановлює для обраного елемента список за пріоритетом з одного або кількох сімейств шрифту та (або) загальних імен сімейств.
У нас контроль за актуальністю перекладів на основі дати останнього редагування, тому ми нічого не відкладаємо на потім отак

2024-07-16 07:39 UTC, undead404 commented on files/uk/web/css/font-family/index.md
> +  - : Ім'я сімейства шрифту. Це повинно бути або одне {{cssxref("string", "рядкове")}} значення, або розділена пробілами послідовність значень {{cssxref("custom-ident")}}. Рядкові значення повинні бу
Ми билися-билися з приводу цього слова, але нічого кращого за "кастомний" придумати не змогли. Надто специфічне поняття. Слово "саморобний" наближене, але не змогли дійти згоди

2024-07-16 07:39 UTC, undead404 commented on files/uk/web/css/font-family/index.md
> +    Дивіться також [Дійсні імена сімейств](#diisni-imena-simeistv).
В оригіналі розділи й підрозділи не в лапках, точно є зміст додавати ці лапки?

2024-07-16 09:16 UTC, alinkedd commented on files/uk/web/css/font-family/index.md
> +Властивість [CSS](/uk/docs/Web/CSS) **`font-family`** (сімейство шрифту) встановлює для обраного елемента список за пріоритетом з одного або кількох сімейств шрифту та (або) загальних імен сімейств.
я більше про те, сімейство шрифтів піде в нове issue, а тут поки буде так
```suggestion
Властивість [CSS](/uk/docs/Web/CSS) **`font-family`** (сімейство шрифту) встановлює для обраного елемента список за пріоритетом з одного або кількох імен сімейств шрифту та (або) загальних сімейств.
```

2024-07-16 09:17 UTC, alinkedd commented on files/uk/web/css/font-family/index.md
> +  - : Ім'я сімейства шрифту. Це повинно бути або одне {{cssxref("string", "рядкове")}} значення, або розділена пробілами послідовність значень {{cssxref("custom-ident")}}. Рядкові значення повинні бу
тоді ок, резолви

p.s. знайду/створю issue

2024-07-16 09:19 UTC, alinkedd commented on files/uk/web/css/font-family/index.md
> +    Дивіться також [Дійсні імена сімейств](#diisni-imena-simeistv).
так, для valid вже є issue, для лапок створю (у нас з англійською відрізняється граматика, є різна пунктуація, в issue опишу)

тоді ок, закривай

2024-07-16 09:21 UTC, alinkedd approved these changes

2024-07-16 09:23 UTC, merged