update(HTML): web/html/element/a
webdoky/content pull request #3035
Opened 2024-06-22 19:34 UTC by undead404

2024-06-22 19:57 UTC, undead404 commented on files/uk/web/html/element/a/index.md
> +    Браузер зберігає дані про джерело, пов'язані з джерелом атрибуцї, заснованим на навігації (таким, яке задано в заголовку відповіді {{httpheader("Attribution-Reporting-Register-Source")}}), коли к
```suggestion
    Браузер зберігає дані про джерело, пов'язані з джерелом атрибуції, заснованим на навігації (таким, яке задано в заголовку відповіді {{httpheader("Attribution-Reporting-Register-Source")}}), коли користувач клацає посилання. Дивіться подробиці в [API звітування про атрибуцію](/uk/docs/Web/API/Attribution_Reporting_API).
```

2024-08-08 15:37 UTC, alinkedd requested changes

2024-08-08 15:37 UTC, alinkedd commented on files/uk/web/html/element/a/index.md
> +
тут те саме - передивись, як ми змержили, то так і пофікси, щоб було у всіх файлах однаково

2024-08-08 15:44 UTC, undead404 commented on files/uk/web/html/element/a/index.md
> +  - : Задає те, що ви хочете, аби браузер надіслав заголовок {{httpheader("Attribution-Reporting-Eligible")}}. З серверного боку це використовується для пуску надсилання заголовка {{httpheader("Attri
```suggestion
  - : Задає те, що ви хочете, аби браузер надіслав заголовок {{httpheader("Attribution-Reporting-Eligible")}}. На серверному боці такий заголовок використовується для запуску надсилання у відповіді заголовка {{httpheader("Attribution-Reporting-Register-Source")}} у відповіді, щоб зареєструвати [джерело атрибуції на основі навігації](/uk/docs/Web/API/Attribution_Reporting_API/Registering_sources#dzherela-atrybutsii-na-osnovi-navihatsii).
```

2024-08-08 15:44 UTC, undead404 commented on files/uk/web/html/element/a/index.md
> +    Є дві версії цього атрибуту, які можна задати:
```suggestion
    Можна задати одну з двох версій цього атрибуту:
```

2024-08-08 15:44 UTC, undead404 commented on files/uk/web/html/element/a/index.md
> +    - Значення, що вміщає один чи більше URL, наприклад:
```suggestion
    - Значення, що вміщає один або кілька URL, наприклад:
```

2024-08-08 15:44 UTC, undead404 commented on files/uk/web/html/element/a/index.md
> +      Це корисно в тих випадках, коли запитаний ресурс не перебуває на тому сервері, який ви контролюєте, або просто треба обробляти реєстрацію джерела атрибуції на іншому сервері. У такому випадку м
```suggestion
      Це корисно в тих випадках, коли запитаний ресурс не перебуває на сервері під вашим контролем або просто хочеться обробляти реєстрацію джерела атрибуції на іншому сервері. Тоді можна задати одну або більше адрес URL як значення `attributionsrc`. Коли відбувається запит на ресурс, заголовок {{httpheader("Attribution-Reporting-Eligible")}} надсилається на адреси URL, задані в `attributionsrc `, а не лише за походженням ресурсу. Ці адреси URL потім можуть відповісти заголовком {{httpheader("Attribution-Reporting-Register-Source")}} відповідно для завершення реєстрації.
```

2024-08-08 15:44 UTC, undead404 commented on files/uk/web/html/element/a/index.md
> +      > Задання кількох URL означає те, що на одну можливість може бути зареєстровано більш ніж одне джерело атрибуції. Можна, наприклад, мати різні кампанії, успішність яких вимірюється, що включає
```suggestion
      > Задання кількох адрес URL означає те, що на один елемент можна зареєструвати кілька джерел атрибуції. Можна, наприклад, мати різні кампанії, для вимірювання успішності яких потрібно генерувати різні звіти щодо різних даних.
```

2024-08-08 15:57 UTC, alinkedd commented on files/uk/web/html/element/a/index.md
> +
апрув, я тобі довіряю :)

2024-08-08 15:57 UTC, alinkedd approved these changes

2024-08-08 15:59 UTC, undead404 commented
Дякую!

2024-08-08 16:00 UTC, merged