update(HTML): web/html/element/iframe
webdoky/content pull request #3036
Opened 2024-06-22 19:57 UTC by undead404

2024-06-22 20:06 UTC, undead404 commented on files/uk/web/html/element/iframe/index.md
> +  > **Примітка:** Сторінка `about:blank` використовує URL документа, щ вбудовується, як свій базовий URL, коли розв'язуються відносні URL, наприклад, якірні посилання.
```suggestion
  > **Примітка:** Сторінка `about:blank` використовує URL документа, що вбудовується, як свій базовий URL, коли розв'язуються відносні URL, наприклад, якірні посилання.
```

2024-06-22 20:06 UTC, undead404 commented on files/uk/web/html/element/iframe/index.md
> +  - : Супутній HTML для вбудовування, що відкидає атрибут `src`. Його вміст повинен відповідати синтаксису цілого документа URL, що складається з директиви doctype, тегів `<html>`, `<body>` тощо, хоч
```suggestion
  - : Супутній HTML для вбудовування, що відкидає атрибут `src`. Його вміст повинен відповідати синтаксису цілого документа URL, що складається з директиви doctype, тегів `<html>`, `<body>` тощо, хоч і більшість з цих тегів можна пропустити, залишивши лише вміст тіла. Такий документ матиме адресу `about:srcdoc`. Якщо браузер не підтримує атрибут `srcdoc`, то звернеться до URL в атрибуті `src`.
```

2024-06-22 20:06 UTC, undead404 commented on files/uk/web/html/element/iframe/index.md
> +    > **Примітка:** Сторінка `about:srcdoc` використовує URL документа, щ вбудовується, як свій базовий URL, коли розв'язуються відносні URL, наприклад, якірні посилання.
```suggestion
    > **Примітка:** Сторінка `about:srcdoc` використовує URL документа, що вбудовується, як свій базовий URL, коли розв'язуються відносні URL, наприклад, якірні посилання.
```

2024-06-22 20:06 UTC, undead404 commented on files/uk/web/html/element/iframe/index.md
> +- `&lt;` і `<` у атрибуті `srcdoc` представляють один і той же символ. Таким чином, щоб зробити таку послідовність справжньою послідовністю екранування в документі HTML, замініть усі амперсанди (`&`)
```suggestion
- `&lt;` і `<` в атрибуті `srcdoc` представляють один і той же символ. Таким чином, щоб зробити таку послідовність справжньою послідовністю екранування в документі HTML, замініть усі амперсанди (`&`) на `&amp;`. Наприклад, `&lt;` стане `&amp;lt;`, а `&amp;` стане `&amp;amp;`.
```

2024-08-09 18:38 UTC, alinkedd requested changes

2024-08-09 18:38 UTC, alinkedd commented on files/uk/web/html/element/iframe/index.md
> +Цей приклад безпосередньо візуалізує вихідний код у супутньому фреймі. Це можна використовувати як техніку для запобігання ін'єкціям сценаріїв при виведенні вмісту, створеного користувачами, коли поє
```suggestion
Цей приклад безпосередньо візуалізує вихідний код у супутньому фреймі. Якщо поєднати з атрибутом `sandbox`, то це можна використовувати як техніку для запобігання ін'єкціям сценаріїв при виведенні вмісту, створеного користувачами.
```

2024-08-09 18:38 UTC, alinkedd commented on files/uk/web/html/element/iframe/index.md
> +Зверніть увагу на те, що при використанні `srcdoc` будь-які відносні URL у вбудованому вмісті розв'язуються відносно URL вбудованої сторінки. При потребі використання якірних посилань, що вказують на
```suggestion
Зверніть увагу на те, що за використання `srcdoc` будь-які відносні URL у вбудованому вмісті розв'язуються відносно URL вбудованої сторінки. Якщо потрібно використати якірні посилання, що вказують на місця у вбудованому вмісті, необхідно явно задати `about:srcdoc` як базовий URL.
```

2024-08-09 18:38 UTC, alinkedd commented on files/uk/web/html/element/iframe/index.md
> +- `&lt;` і `<` в атрибуті `srcdoc` представляють один і той же символ. Таким чином, щоб зробити таку послідовність справжньою послідовністю екранування в документі HTML, замініть усі амперсанди (`&`)
```suggestion
- `&lt;` і `<` в атрибуті `srcdoc` представляють один і той же символ. Тому, щоб зробити таку послідовність справжньою послідовністю екранування в документі HTML, замініть усі амперсанди (`&`) на `&amp;`. Наприклад, `&lt;` стане `&amp;lt;`, а `&amp;` – `&amp;amp;`.
```

2024-08-09 18:38 UTC, alinkedd commented on files/uk/web/html/element/iframe/index.md
> +    > [!NOTE]
треба ще цей note додати https://github.com/mdn/content/blob/main/files/en-us/web/html/element/iframe/index.md?plain=1#L72-L74 для loading lazy

2024-08-09 20:57 UTC, undead404 commented on files/uk/web/html/element/iframe/index.md
> +    > [!NOTE]
Додано

2024-08-09 21:14 UTC, alinkedd approved these changes

2024-08-09 21:16 UTC, merged