update(HTML): web/html/element/input
webdoky/content pull request #3048
Opened 2024-07-11 10:47 UTC by undead404

2024-07-15 19:35 UTC, alinkedd requested changes

2024-07-15 19:35 UTC, alinkedd commented on files/uk/web/html/element/input/index.md
> +    Поле введення провалить [валідацію обмежень](/uk/docs/Web/HTML/Constraint_validation), якщо довжина введеного в поле тексту перевищить `maxlength` кодових одиниць UTF-16. Усталено браузери не даю
```suggestion
    Поле введення провалить [валідацію обмежень](/uk/docs/Web/HTML/Constraint_validation), якщо довжина введеного в поле тексту перевищить `maxlength` кодових одиниць UTF-16. Усталено браузери не дають користувачам вводити більше символів, ніж дозволено атрибутом `maxlength`. Валідація обмежень застосовується лише тоді, коли значення змінюється користувачем. Детальніше про це в секції [Валідація на клієнтському боці](#validatsiia-na-kliientskomu-botsi).
```

2024-07-15 19:35 UTC, alinkedd commented on files/uk/web/html/element/input/index.md
> +    Поле введення провалить [валідацію обмежень](/uk/docs/Web/HTML/Constraint_validation), якщо довжина введеного в поле тексту менша за `minlength` кодових одиниць UTF-16, і форма не буде подана. Ва
same
```suggestion
    Поле введення провалить [валідацію обмежень](/uk/docs/Web/HTML/Constraint_validation), якщо довжина введеного в поле тексту менша за `minlength` кодових одиниць UTF-16, і форма не буде подана. Валідація обмежень застосовується лише тоді, коли значення змінюється користувачем. Детальніше про це в секції [Валідація на клієнтському боці](#validatsiia-na-kliientskomu-botsi).
```

2024-07-16 07:33 UTC, undead404 commented on files/uk/web/html/element/input/index.md
> +    Поле введення провалить [валідацію обмежень](/uk/docs/Web/HTML/Constraint_validation), якщо довжина введеного в поле тексту перевищить `maxlength` кодових одиниць UTF-16. Усталено браузери не даю
Але навіщо? Активний стан же краще

2024-07-16 09:34 UTC, alinkedd commented on files/uk/web/html/element/input/index.md
> +    Поле введення провалить [валідацію обмежень](/uk/docs/Web/HTML/Constraint_validation), якщо довжина введеного в поле тексту перевищить `maxlength` кодових одиниць UTF-16. Усталено браузери не даю
В документації має бути одразу зрозуміле підпорядкування слів і прямий порядок слів за можливості.

Також уяви конструкцію `значення змінює речення` - підсвідомо ти скажеш, що `значення` підмет, а не `речення`, але якщо `речення`, то ми вже перекладемо хибно.

Тому якщо хочеш активний стан, то `користувач змінює значення` (ну або `значення змінюється користувачем`)

2024-07-16 09:48 UTC, alinkedd approved these changes

2024-07-16 10:12 UTC, merged