update(JS): web/javascript/reference/functions/arrow_functions
webdoky/content pull request #3050
Opened 2024-07-11 11:15 UTC by undead404

2024-07-15 18:47 UTC, alinkedd requested changes

2024-07-15 18:47 UTC, alinkedd commented on files/uk/web/javascript/reference/functions/arrow_functions/index.md
> +Стрілкові функції самі по собі не пов'язуються з жодними іменами. Якщо стрілковій функції треба викликати саму себе, слід натомість використовувати іменований вираз функції. Крім цього, можна присвої
самі по собі - не характерний вираз https://onlinecorrector.com.ua/uk/%D1%81%D0%B0%D0%BC%D0%BE-%D1%81%D0%BE%D0%B1%D0%BE%D1%8E/

треба пошукати щось інше, схоже за синонімами 
fundamentally
naturally
intrinsically
basically
essentially

наприклад, внутрішньо, сутнісно, за своєю суттю, в основі тощо

2024-07-16 07:22 UTC, undead404 commented on files/uk/web/javascript/reference/functions/arrow_functions/index.md
> +Стрілкові функції самі по собі не пов'язуються з жодними іменами. Якщо стрілковій функції треба викликати саму себе, слід натомість використовувати іменований вираз функції. Крім цього, можна присвої
```suggestion
Стрілкові функції як такі не пов'язуються з жодними іменами. Якщо стрілковій функції треба викликати саму себе, слід натомість використовувати іменований вираз функції. Крім цього, можна присвоїти стрілкову функцію змінній, що дає змогу звертатися до цієї функції через цю змінну.
```

2024-07-16 09:03 UTC, alinkedd approved these changes

2024-07-16 09:06 UTC, merged