update(CSS): web/css/font-weight
webdoky/content pull request #3054
Opened 2024-07-11 11:35 UTC by undead404

2024-07-15 18:50 UTC, alinkedd commented
@undead404 
Fix some fragment links (#31967) - цієї зміни я не бачу у цьому PR

2024-07-15 18:55 UTC, alinkedd requested changes

2024-07-15 18:55 UTC, alinkedd commented on files/uk/web/css/font-weight/index.md
> +> **Примітка:** Запасний алгоритм ваги використовується лише для візуалізації. Обчисленим значенням властивості все одно є задане значення.
- `Запасний алгоритм ваги` -> `Алгоритм запасних ваг` (не алгоритм запасний, а ваги)
- Чому візуалізації, а не рендеринг?
- Я би після `Обчисленим` поставила в дужках `(computed)`, бо у цій статті вже є обчислення як переклад `calculation`. Взагалі треба подумати, щоб у вас завжди був переклад один для одного слова сalculated та інший для іншого сomputed: наприклад, вирахуваний та обчислений, обрахунок та обчислення

2024-07-16 07:27 UTC, undead404 commented on files/uk/web/css/font-weight/index.md
> +> **Примітка:** Запасний алгоритм ваги використовується лише для візуалізації. Обчисленим значенням властивості все одно є задане значення.
```suggestion
> **Примітка:** Алгоритм запасних ваг використовується лише для візуалізації. Обчисленим (computed) значенням властивості все одно є задане значення.
```
Терміном "рендеринг" ми стараємось не користуватися, це неадаптоване слово, прагнемо вводити якомога менше сленгу (хоча зі словом "кастомний" ми без сленгу обійтися поки не змогли). В нашому масиві роботи "рендеринг" цілком природно замінюється на "візуалізацію".

2024-07-16 08:32 UTC, alinkedd commented
@undead404 щодо https://github.com/webdoky/content/pull/3054#issuecomment-2229166828

хіба вам не треба в оцих посиланях змінити - на _, як тут https://github.com/mdn/content/commit/2077d0702d038c9ccc743a53d8ad1c0c21fef5be#diff-98bce00b3360417c58b007be9f77adf31284ad00c4deb6184a72aeb8adfe4333? (я не знаю технічну сторону питання вашого роунтингу)

2024-07-16 08:36 UTC, undead404 commented
> @undead404 щодо [#3054 (comment)](https://github.com/webdoky/content/pull/3054#issuecomment-2229166828)
> 
> хіба вам не треба в оцих посиланях змінити - на _, як тут [mdn/content@2077d07#diff-98bce00b3360417c58b007be9f77adf31284ad00c4deb6184a72aeb8adfe4333](https://github.com/mdn/content/commit/2077d0702d038c9ccc743a53d8ad1c0c21fef5be#diff-98bce00b3360417c58b007be9f77adf31284ad00c4deb6184a72aeb8adfe4333)? (я не знаю технічну сторону питання вашого роунтингу)

Ні, в нас роутинг працює по-своєму, з дефісами, а не підкресленнями. Що не складає проблеми, бо все одно всі якорі треба перебивати

2024-07-16 08:49 UTC, undead404 commented
Забув дописати: commit зі змінами в якорях – нерелевантний для нас

2024-07-16 09:01 UTC, alinkedd approved these changes

2024-07-16 09:05 UTC, merged