update(HTML): web/html/element/img
webdoky/content pull request #3055
Opened 2024-07-12 08:34 UTC by undead404

2024-07-12 08:36 UTC, undead404 commented on files/uk/web/html/element/img/index.md
> +    > **Примітка:** Дивіться подробиці у [API звітування атрибуції](/uk/docs/Web/API/Attribution_Reporting_API).
```suggestion
    > **Примітка:** Дивіться подробиці в [API звітування атрибуції](/uk/docs/Web/API/Attribution_Reporting_API).
```

2024-07-12 08:36 UTC, undead404 commented on files/uk/web/html/element/img/index.md
> +    Це корисно в тих випадках, коли запитаний ресурс не перебуває на сервері під вашим контролем, або просто хочеться обробляти реєстрацію реєстрацію джерела атрибуції на іншому сервері. У такому вип
```suggestion
    Це корисно в тих випадках, коли запитаний ресурс не перебуває на сервері під вашим контролем, або просто хочеться обробляти реєстрацію джерела атрибуції на іншому сервері. У такому випадку можна задати один або більше URL як значення `attributionsrc`. Коли трапляється запит на ресурс, заголовок {{httpheader("Attribution-Reporting-Eligible")}} надсилається на URL, задані в `attributionSrc`, а не лише за походженням ресурсу. Ці URL потім можуть відповісти заголовком {{httpheader("Attribution-Reporting-Register-Source")}} або {{httpheader("Attribution-Reporting-Register-Trigger")}}, як доречно, для завершення реєстрації.
```

2024-08-08 14:50 UTC, alinkedd requested changes

2024-08-08 14:50 UTC, alinkedd commented on files/uk/web/html/element/img/index.md
> +    > Задання кількох URL означає те, що на одну можливість можна зареєструвати кілька джерел атрибуції. Можна, наприклад, мати різні кампанії, успішність яких вимірюється, що включає генерування різ
ми недавно десь редагували майже такий самий шматок. можеш, будь ласка, глянути і внести ті самі зміни/фікси? (дуже дякую :smiling_face_with_tear:) 

все інше ок

2024-08-08 15:37 UTC, undead404 commented on files/uk/web/html/element/img/index.md
> +    > Задання кількох URL означає те, що на одну можливість можна зареєструвати кілька джерел атрибуції. Можна, наприклад, мати різні кампанії, успішність яких вимірюється, що включає генерування різ
```suggestion
    > Задання кількох адрес URL означає те, що на один елемент можна зареєструвати кілька джерел атрибуції. Можна, наприклад, мати різні кампанії, для вимірювання успішності яких потрібно генерувати різні звіти щодо різних даних.
```

2024-08-08 15:37 UTC, undead404 commented on files/uk/web/html/element/img/index.md
> +    На серверному боці такий заголовок використовується для запуску надсилання у відповіді заголовка {{httpheader("Attribution-Reporting-Register-Source")}} або {{httpheader("Attribution-Reporting-Re
```suggestion
    На серверному боці такий заголовок використовується для запуску надсилання у відповіді заголовка {{httpheader("Attribution-Reporting-Register-Source")}} або {{httpheader("Attribution-Reporting-Register-Trigger")}}, щоб зареєструвати засноване на JavaScript [джерело атрибуції](/uk/docs/Web/API/Attribution_Reporting_API/Registering_sources#dzherela-podii-na-osnovi-html) або [пускача атрибуції](/uk/docs/Web/API/Attribution_Reporting_API/Registering_triggers#puskach-atrybutsii-na-osnovi-html) відповідно. Те, який заголовок відповіді слід надсилати у відповідь, залежить від значення заголовка `Attribution-Reporting-Eligible`, що спричинив реєстрацію.
```

2024-08-08 15:37 UTC, undead404 commented on files/uk/web/html/element/img/index.md
> +    - Булева, тобто просто запис `attributionsrc`. Це задає те, щоб тому самому серверу, що й сервер, на який посилається атрибут `src`, надсилався заголовок {{httpheader("Attribution-Reporting-Eligi
```suggestion
    - Булева, тобто просто запис `attributionsrc`. Це задає те, щоб заголовок {{httpheader("Attribution-Reporting-Eligible")}} надсилався тому самому серверу, на який посилається атрибут `src`. Це годиться, коли джерело атрибуції чи реєстрація пускача обробляється на тому самому сервері. Під час реєстрації пускача атрибуції ця властивість не обов'язкова, і за її опущення використовується значення пустого рядка.
```

2024-08-08 15:37 UTC, undead404 commented on files/uk/web/html/element/img/index.md
> +    Це корисно в тих випадках, коли запитаний ресурс не перебуває на сервері під вашим контролем, або просто хочеться обробляти реєстрацію джерела атрибуції на іншому сервері. У такому випадку можна
```suggestion
    Це корисно в тих випадках, коли запитаний ресурс не перебуває на сервері під вашим контролем або просто хочеться обробляти реєстрацію джерела атрибуції на іншому сервері. Тоді можна задати одну або більше адрес URL як значення `attributionsrc`. Коли відбувається запит на ресурс, заголовок {{httpheader("Attribution-Reporting-Eligible")}} надсилається на адреси URL, задані в `attributionSrc`, а не лише за походженням ресурсу. Ці адреси URL потім можуть відповісти заголовком {{httpheader("Attribution-Reporting-Register-Source")}} або {{httpheader("Attribution-Reporting-Register-Trigger")}} відповідно для завершення реєстрації.
```

2024-08-08 16:01 UTC, alinkedd approved these changes

2024-08-08 16:03 UTC, merged