update(JS): web/javascript/reference/global_objects/date/now
webdoky/content pull request #3073
Opened 2024-07-16 18:08 UTC by undead404

2024-07-17 13:03 UTC, alinkedd requested changes

2024-07-17 13:03 UTC, alinkedd commented on files/uk/web/javascript/reference/global_objects/date/now/index.md
> +Наприклад, при зниженій точності часу результат `Date.now()` завжди буде кратним 2, або кратним 100 (або `privacy.resistFingerprinting.reduceTimerPrecision.microseconds`), коли ввімкнено `privacy.res
```suggestion
Наприклад, за зниженої точності значення часу результат `Date.now()` завжди буде кратним 2 та буде кратним 100 (або `privacy.resistFingerprinting.reduceTimerPrecision.microseconds`), коли ввімкнено `privacy.resistFingerprinting`.
```

2024-07-17 15:28 UTC, alinkedd requested changes

2024-07-17 15:28 UTC, alinkedd commented on files/uk/web/javascript/reference/global_objects/date/now/index.md
>  Для забезпечення захисту від часових атак і [створення цифрових відбитків](/uk/docs/Glossary/Fingerprinting), точні значення `Date.now()` можуть заокруглюватись залежно від налаштувань браузера. Напр
```suggestion
Для забезпечення захисту від часових атак і [створення цифрових відбитків](/uk/docs/Glossary/Fingerprinting), точні значення `Date.now()` можуть заокруглюватись залежно від налаштувань браузера. Наприклад, у Firefox опція `privacy.reduceTimerPrecision` — усталено ввімкнена і усталено дорівнює 2 мс у Firefox. Також можна увімкнути `privacy.resistFingerprinting`, і в цьому випадку точність дорівнюватиме 100 мс або значенню `privacy.resistFingerprinting.reduceTimerPrecision.microseconds` — залежно від того, яке з цих значень більше.
```
(знайшла помилку після #3095 )

2024-07-17 15:35 UTC, alinkedd commented on files/uk/web/javascript/reference/global_objects/date/now/index.md
> +Для забезпечення захисту від часових атак і [створення цифрових відбитків](/uk/docs/Glossary/Fingerprinting), точні значення `Date.now()` можуть заокруглюватись залежно від налаштувань браузера. Напр
```suggestion
Для забезпечення захисту від часових атак і [створення цифрових відбитків](/uk/docs/Glossary/Fingerprinting), точні значення `Date.now()` можуть заокруглюватись залежно від налаштувань браузера. Наприклад, у Firefox опція `privacy.reduceTimerPrecision` — усталено ввімкнена й усталено дорівнює 2 мс у Firefox. Також можна увімкнути `privacy.resistFingerprinting`, і в цьому випадку точність дорівнюватиме 100 мс або значенню `privacy.resistFingerprinting.reduceTimerPrecision.microseconds` — залежно від того, яке з цих значень більше.
```
від мене проблема

2024-07-17 18:20 UTC, undead404 commented on files/uk/web/javascript/reference/global_objects/date/now/index.md
> +Для забезпечення захисту від часових атак і [створення цифрових відбитків](/uk/docs/Glossary/Fingerprinting), точні значення `Date.now()` можуть заокруглюватись залежно від налаштувань браузера. Напр
Поки від тебе тільки рішення

2024-07-19 11:35 UTC, alinkedd approved these changes

2024-07-19 11:37 UTC, merged