update(JS): web/javascript/data_structures
webdoky/content pull request #3076
Opened 2024-07-16 18:16 UTC by undead404

2024-07-16 18:19 UTC, undead404 commented on files/uk/web/javascript/data_structures/index.md
> +Тип {{jsxref("Number")}} є [64-бітним значенням двійкового формату IEEE 754 подвійної точності](/uk/docs/Web/JavaScript/Reference/Global_Objects/Number#koduvannia-number). Він здатний зберігати додат
```suggestion
Тип {{jsxref("Number")}} є [64-бітовим значенням двійкового формату IEEE 754 подвійної точності](/uk/docs/Web/JavaScript/Reference/Global_Objects/Number#koduvannia-number). Він здатний зберігати додатні числа з рухомою комою між 2<sup>-1074</sup> ({{jsxref("Number.MIN_VALUE")}}) і 2<sup>1023</sup> × (2 - 2<sup>-52</sup>) ({{jsxref("Number.MAX_VALUE")}}), а також від'ємні числа з рухомою комою аналогічного діапазону, але може надійно зберігати цілі числа лише в діапазоні від -(2<sup>53</sup> − 1) ({{jsxref("Number.MIN_SAFE_INTEGER")}}) до 2<sup>53</sup> − 1 ({{jsxref("Number.MAX_SAFE_INTEGER")}}). Поза цим діапазоном JavaScript не може надійно представляти цілі числа; замість цього вони представляються у вигляді наближення з рухомою комою подвійної точності. Перевірити число на попадання в діапазон надійних цілих чисел можна за допомогою {{jsxref("Number.isSafeInteger()")}}.
```

2024-07-17 14:03 UTC, alinkedd requested changes

2024-07-17 14:08 UTC, undead404 commented on files/uk/web/javascript/data_structures/index.md
> +Тип {{jsxref("Number")}} є [64-бітовим значенням двійкового формату IEEE 754 подвійної точності](/uk/docs/Web/JavaScript/Reference/Global_Objects/Number#koduvannia-number). Він здатний зберігати дода
Отакої маємо. За посиланням я трохи очманів, що ще за нарости на якихось пнях іменникових......

2024-07-17 14:08 UTC, undead404 commented on files/uk/web/javascript/data_structures/index.md
> +Neither `{}` nor `[]` has a `[Symbol.toPrimitive]()` method. Both `{}` and `[]` inherit `valueOf()` from {{jsxref("Object.prototype.valueOf")}}, which returns the object itself. Since the return valu
Так, треба виправити неподобство

2024-07-17 15:48 UTC, alinkedd commented on files/uk/web/javascript/data_structures/index.md
> +Тип {{jsxref("Number")}} є [64-бітним значенням двійкового формату IEEE 754 подвійної точності](/uk/docs/Web/JavaScript/Reference/Global_Objects/Number#koduvannia-number). Він здатний зберігати додат
оце прикол

2024-07-19 11:35 UTC, alinkedd commented on files/uk/web/javascript/data_structures/index.md
> +Тип {{jsxref("Number")}} є [64-бітним значенням двійкового формату IEEE 754 подвійної точності](/uk/docs/Web/JavaScript/Reference/Global_Objects/Number#koduvannia-number). Він здатний зберігати додат
https://github.com/brown-uk/dict_uk/issues/381

2024-07-19 11:39 UTC, undead404 commented on files/uk/web/javascript/data_structures/index.md
> +Тип {{jsxref("Number")}} є [64-бітним значенням двійкового формату IEEE 754 подвійної точності](/uk/docs/Web/JavaScript/Reference/Global_Objects/Number#koduvannia-number). Він здатний зберігати додат
Підписався там, чекатиму відповіді. Цей PR можна обробляти не оглядаючись на Браун

2024-07-19 11:57 UTC, alinkedd approved these changes

2024-07-19 12:51 UTC, merged