update(JS): web/javascript/reference/global_objects/date/tolocaledate…
webdoky/content pull request #3094
Opened 2024-07-17 08:28 UTC by undead404

…string

2024-07-17 15:02 UTC, alinkedd requested changes

2024-07-17 15:02 UTC, alinkedd commented on files/uk/web/javascript/reference/global_objects/date/tolocaledatestring/index.md
> +> **Примітка:** В більшості випадків форматування, повернене `toLocaleDateString()`, є сталим. Проте вивід може відрізнятися в різних реалізаціях, навіть при використанні однієї локалі: відмінності в
```suggestion
> **Примітка:** В більшості випадків форматування, повернене `toLocaleDateString()`, є сталим. Проте вивід може відрізнятися в різних реалізаціях, навіть із використанням однієї локалі: відмінності виводу є свідомими та дозволені специфікацією. Також вивід може бути не таким, як ви очікуєте. Наприклад, рядок може містити нерозривні пробіли або бути оточеним символами контролю напрямку письма. Не слід порівнювати результати `toLocaleDateString()` із попередньо вписаними сталими значеннями.
```

(при - при людині, при комітеті, при мені. в інших моментах `при` не треба)
(попередньо вписаними, попередньо запрограмованими - якось так або схоже, точно не закодований, бо закодований - це більше до кодування/encoding)

2024-07-17 15:11 UTC, undead404 commented on files/uk/web/javascript/reference/global_objects/date/tolocaledatestring/index.md
> +page-type: javascript-instance-method
Пропустив колись

2024-07-17 15:12 UTC, undead404 commented on files/uk/web/javascript/reference/global_objects/date/tolocaledatestring/index.md
> +> **Примітка:** В більшості випадків форматування, повернене `toLocaleDateString()`, є сталим. Проте вивід може відрізнятися в різних реалізаціях, навіть при використанні однієї локалі: відмінності в
```suggestion
> **Примітка:** В більшості випадків форматування, повернене `toLocaleDateString()`, є сталим. Проте вивід може відрізнятися в різних реалізаціях, навіть із використанням однієї локалі: відмінності виводу є свідомими та дозволені специфікацією. Також вивід може бути не таким, як ви очікуєте. Наприклад, рядок може містити нерозривні пробіли або бути оточеним символами контролю напрямку письма. Не слід порівнювати результати `toLocaleDateString()` з жорстко зафіксованими сталими значеннями.
```
Можливо, так?

2024-07-17 15:38 UTC, alinkedd commented on files/uk/web/javascript/reference/global_objects/date/tolocaledatestring/index.md
> +> **Примітка:** В більшості випадків форматування, повернене `toLocaleDateString()`, є сталим. Проте вивід може відрізнятися в різних реалізаціях, навіть при використанні однієї локалі: відмінності в
ок, тільки 'із' (вам треба буде додати правила милозвучності для з/із/зі)
```suggestion
> **Примітка:** В більшості випадків форматування, повернене `toLocaleDateString()`, є сталим. Проте вивід може відрізнятися в різних реалізаціях, навіть із використанням однієї локалі: відмінності виводу є свідомими та дозволені специфікацією. Також вивід може бути не таким, як ви очікуєте. Наприклад, рядок може містити нерозривні пробіли або бути оточеним символами контролю напрямку письма. Не слід порівнювати результати `toLocaleDateString()` із жорстко зафіксованими сталими значеннями.
```

2024-07-17 15:41 UTC, alinkedd commented on files/uk/web/javascript/reference/global_objects/date/tolocaledatestring/index.md
> +page-type: javascript-instance-method
можливо, просто можна додавати в опис у зміни "додав відсутні частини" (це більше від мене)

2024-07-17 18:20 UTC, undead404 commented on files/uk/web/javascript/reference/global_objects/date/tolocaledatestring/index.md
> +page-type: javascript-instance-method
Так, слушно дописувати це окремим коментарем, "знайшов упущене" чи щось таке

2024-07-19 11:55 UTC, alinkedd approved these changes

2024-07-19 12:50 UTC, merged