update(HTML): web/html/element/input/time
webdoky/content pull request #3120
Opened 2024-07-17 14:40 UTC by undead404

2024-07-17 14:41 UTC, undead404 commented on files/uk/web/html/element/input/time/index.md
> +Цей атрибут приймає ціле числове значення, що визначає кількість секунд, на які повинен відбувати інкремент; усталене значення – 60 секунд. Коли вживається це усталене значення, більшість UI часу кор
```suggestion
Цей атрибут приймає ціле числове значення, що визначає кількість секунд, на які повинен відбувати інкремент; усталене значення – 60 секунд. Коли вживається це усталене значення, більшість UI часу користувацьких агентів виводять години та хвилини, але не секунди. Додання атрибута [`step`](/uk/docs/Web/HTML/Element/input#step-krok) з будь-яким числовим значенням, що не ділиться на `60`, додає до UI секунди, якщо до появи секунд не призвели значення `min` або `max`.
```

2024-08-08 21:44 UTC, alinkedd requested changes

2024-08-08 21:44 UTC, alinkedd commented on files/uk/web/html/element/input/time/index.md
> +Попри те, що зовнішній вигляд користувацького інтерфейсу цього контрольного елемента залежить від браузера та операційної системи, можливості в нього одні й ті ж. Значення завжди є 24-годинним відфор
```suggestion
Попри те, що зовнішній вигляд користувацького інтерфейсу цього контрольного елемента залежить від браузера та операційної системи, можливості в нього одні й ті ж. Значення завжди є 24-годинним відформатованим часом `hh:mm` або `hh:mm:ss` з провідними нулями, незалежно від формату введення UI.
```
https://uk.wikipedia.org/wiki/%D0%9F%D1%80%D0%BE%D0%B2%D1%96%D0%B4%D0%BD%D1%96_%D0%BD%D1%83%D0%BB%D1%96

2024-08-08 21:44 UTC, alinkedd commented on files/uk/web/html/element/input/time/index.md
> +Коли як значення `step` задано `any`, то вживається усталене значення 60 секунд, а секундне значення не виводиться в UI.
```suggestion
Коли `step` має значення `any`, то вживається усталене значення 60 секунд, а секундне значення не виводиться в UI.
```

2024-08-08 21:44 UTC, alinkedd commented on files/uk/web/html/element/input/time/index.md
> +Цей атрибут приймає ціле числове значення, що визначає кількість секунд, на які повинен відбувати інкремент; усталене значення – 60 секунд. Коли вживається це усталене значення, більшість UI часу кор
```suggestion
Цей атрибут приймає ціле числове значення, що визначає кількість секунд, на яку відбувається інкремент; усталене значення – 60 секунд. Коли вживається це усталене значення, більшість UI часу в користувацьких агентах виводить години та хвилини, але не секунди. Додання атрибута [`step`](/uk/docs/Web/HTML/Element/input#step-krok) з будь-яким числовим значенням, що не ділиться на `60`, додає до UI секунди, якщо цього ще не зробили значення `min` або `max`.
```

2024-08-08 21:44 UTC, alinkedd commented on files/uk/web/html/element/input/time/index.md
> +Щоб задати як крок хвилини або години, задайте число хвилин або годин у секундах, наприклад, 120 для 2 хвилин, або 7200 для 2 годин.
```suggestion
Щоб задати як крок хвилини або години, задайте число хвилин або годин у секундах, наприклад, 120 для 2 хвилин або 7200 для 2 годин.
```

2024-08-08 21:44 UTC, alinkedd commented on files/uk/web/html/element/input/time/index.md
> +Усталено `<input type="time">` не застосовує до введених значень жодної валідації, окрім того, що інтерфейс користувацького агента, загалом, не дозволяє ввести нічого, крім значення часу. Це корисно,
```suggestion
Усталено `<input type="time">` не застосовує до введених значень жодної валідації, окрім того, що інтерфейс користувацького агента загалом не дозволяє ввести нічого, крім значення часу. Це корисно, але не можна повністю покладатися на те, що значення буде коректним часовим рядком, оскільки воно може бути порожнім рядком (`""`), що допускається.
```

2024-08-08 21:44 UTC, alinkedd commented on files/uk/web/html/element/input/time/index.md
> +Ось CSS, використаний у прикладі вище. Тут використовуються властивості CSS {{cssxref(":valid")}} та {{cssxref(":invalid")}}, щоб оформити поле на основі того, чи є поточне значення дійсним. Піктогра
```suggestion
Ось CSS, використаний у прикладі вище. Тут використовуються властивості CSS {{cssxref(":valid")}} та {{cssxref(":invalid")}}, щоб оформити поле на основі того, чи є поточне значення дійсним. Піктограма додана через згенерований вміст (поле content) в елементі {{htmlelement("span")}} поряд з полем.
```

2024-08-09 11:47 UTC, alinkedd approved these changes

2024-08-09 12:36 UTC, merged