update(JS): web/javascript/reference/iteration_protocols
webdoky/content pull request #3132
Opened 2024-07-17 18:19 UTC by undead404

2024-07-17 18:27 UTC, undead404 commented on files/uk/web/javascript/reference/iteration_protocols/index.md
> +У разі асинхронних ітерованих, то якщо їхня властивість `[Symbol.asyncIterator]()` має значення `undefined` або `null`, то JavaScript відступає до вживання натомість властивості `[Symbol.iterator]` (
```suggestion
У разі асинхронних ітерованих, то якщо їхня властивість `[Symbol.asyncIterator]()` має значення `undefined` або `null`, то JavaScript відступає до вживання натомість властивості `[Symbol.iterator]` (і загортає результівний ітератор в асинхронний ітератор, [переспрямовуючи](#perespriamuvannia-pomylok) методи). Інакше – властивість `[Symbol.asyncIterator]` також повинна відповідати інваріантам вище.
```

2024-07-17 18:27 UTC, undead404 commented on files/uk/web/javascript/reference/iteration_protocols/index.md
> +Якщо викликач вирішить вийти з ітерування з якихось причин, відмінних від помилок, описаних у абзаці вище, наприклад, коли він перейшов до стану помилки у власному коді (наприклад, у разі обробки нев
```suggestion
Якщо викликач вирішить вийти з ітерування з якихось причин, відмінних від помилок, описаних в абзаці вище, наприклад, коли він перейшов до стану помилки у власному коді (наприклад, у разі обробки невалідного значення, виданого ітератором), йому слід викликати метод `return()` на ітераторі, якщо такий є. Це дасть ітератору змогу виконати якесь очищення. Метод `return()` викликається лише для раннього виходу: якщо `next()` повертає `done: true`, то метод `return()` не викликається, виходячи з припущення, що ітератор уже очистився.
```

2024-07-17 18:27 UTC, undead404 commented on files/uk/web/javascript/reference/iteration_protocols/index.md
> +`catch` зможе перехопити помилки, викинуті, бо `iterable` не є валідним ітерованим об'єктом, бо `next()` викидає помилку, бо `return()` викидає помилку (якщо цикл `for` завершується передчасно) і бо
```suggestion
`catch` зможе перехопити помилки, викинуті, коли `iterable` не є валідним ітерованим об'єктом, коли `next()` викидає помилку, коли `return()` викидає помилку (якщо цикл `for` завершується передчасно) або коли тіло циклу `for` викидає помилку.
```

2024-07-17 18:27 UTC, undead404 commented on files/uk/web/javascript/reference/iteration_protocols/index.md
> +Частина вбудованих записів синтаксису загортають ітератор у інший ітератор. Серед них ітератор, що створюється {{jsxref("Iterator.from()")}}, [ітераторні помічники](/uk/docs/Web/JavaScript/Reference/
```suggestion
Частина вбудованих записів синтаксису загортають ітератор в інший ітератор. Серед них ітератор, що створюється {{jsxref("Iterator.from()")}}, [ітераторні помічники](/uk/docs/Web/JavaScript/Reference/Global_Objects/Iterator#iteratorni-pomichnyky) (`map()`, `filter()`, `take()`, `drop()` і `flatMap()`), [`yield *`](/uk/docs/Web/JavaScript/Reference/Operators/yield*) і прихована обгортка, коли щодо синхронного ітератора використовується асинхронна ітерація (`for await...of`, `Array.fromAsync`). Загорнутий ітератор тоді відповідає за переспрямування помилок між внутрішнім ітератором і викликачем.
```

2024-08-02 09:23 UTC, alinkedd commented on CHANGELOG.md
> +- **Оновлення перекладу(JS):** web/javascript/reference/global_objects/object/freeze (#3148) ([aa8a981d](https://github.com/webdoky/content/commit/aa8a981d016cf6929ec057cc26cf9c65a823b1a9))
А оці всі зміни в оцих файлах мають тут бути?

2024-08-02 09:55 UTC, undead404 commented on CHANGELOG.md
> +- **Оновлення перекладу(JS):** web/javascript/reference/global_objects/object/freeze (#3148) ([aa8a981d](https://github.com/webdoky/content/commit/aa8a981d016cf6929ec057cc26cf9c65a823b1a9))
Категорично ні. Треба буде перестворювати, ех

2024-08-02 09:57 UTC, closed without merging

2024-08-02 10:16 UTC, alinkedd requested changes

2024-08-02 10:16 UTC, alinkedd commented on files/uk/web/javascript/reference/iteration_protocols/index.md
> +Якщо інваріант порушено або метод `next()` викидає помилку (для асинхронних ітераторів також може бути повернення відхиленого промісу), то помилка поширюється до викликача. У вбудованих записах синта
```suggestion
Якщо інваріант порушено або метод `next()` викидає помилку (для асинхронних ітераторів також може бути повернення відхиленого промісу), то помилка поширюється до викликача. У вбудованих записах синтаксису така ітерація переривається без повторних спроб і очищення (виходячи з припущення, що якщо метод `next()` викинув помилку, то все уже очищено). Якщо ви вручну викликаєте `next()`, то можете перехопити помилку і спробувати повторно викликати `next()`, проте загалом слід припускати, що ітератор вже закрито.
```

2024-08-02 10:16 UTC, alinkedd commented on files/uk/web/javascript/reference/iteration_protocols/index.md
> +Метод `return()` так само може бути невалідним! Мова також вимагає, щоб метод `return()` повертав об'єкт, а інакше - викидав TypeError. Якщо метод `return()` викидає помилку, то ця помилка поширюєтьс
```suggestion
Метод `return()` так само може бути невалідним! Мова також вимагає, щоб метод `return()` повертав об'єкт, а інакше викидав TypeError. Якщо метод `return()` викидає помилку, то ця помилка поширюється до викликача. Проте якщо метод `return()` викликається, тому що викликач зіткнувся з помилкою у своєму власному коді, то така помилка замінює помилку, викинуту методом `return()`.
```

2024-08-02 10:16 UTC, alinkedd commented on files/uk/web/javascript/reference/iteration_protocols/index.md
> +Відсутність `catch` змушує помилки, викинуті `doSomething()` або `doSomethingElse()`, поширюватися до викликача `gen`. Якщо ці помилки перехоплюються всередині функції-генератора (що так само вітаєть
```suggestion
Відсутність `catch` змушує помилки, викинуті `doSomething()` або `doSomethingElse()`, поширюватися до викликача `gen`. Якщо ці помилки перехоплюються всередині функції-генератора (що так само вітається), то така функція-генератор може вирішити продовжити видавати значення або завершитися передчасно. Проте блок `finally` необхідний для генераторів, що зберігають ресурси відкритими. Блок `finally` гарантовано запуститься, коли або востаннє викличеться `next()`, або викличеться `return()`.
```

2024-08-02 10:16 UTC, alinkedd commented on files/uk/web/javascript/reference/iteration_protocols/index.md
> +Частина вбудованих записів синтаксису загортають ітератор в інший ітератор. Серед них ітератор, що створюється {{jsxref("Iterator.from()")}}, [ітераторні помічники](/uk/docs/Web/JavaScript/Reference/
```suggestion
Частина вбудованих записів синтаксису загортає ітератор в інший ітератор. Серед них ітератор, що створюється методом {{jsxref("Iterator.from()")}}, [ітераторні помічники](/uk/docs/Web/JavaScript/Reference/Global_Objects/Iterator#iteratorni-pomichnyky) (`map()`, `filter()`, `take()`, `drop()` і `flatMap()`), [`yield*`](/uk/docs/Web/JavaScript/Reference/Operators/yield*) і прихована обгортка, коли щодо синхронного ітератора використовується асинхронна ітерація (`for await...of`, `Array.fromAsync`). Загорнутий ітератор тоді відповідає за переспрямування помилок між внутрішнім ітератором і викликачем.
```

Дієслово-присудок буде в однині й тоді, коли за підмет правлять збірні слова — більшість, меншість, частина, ряд, кілька, багато, чимало, група, низка, решта, половина та інші, поєднані з залежними від них іменниками (прикметниками) в родовому відмінку: «Більшість присутніх пристала на цю пропозицію»; «Кілька відер води бухнуло на вогонь» (М. Коцюбинський).

2024-08-02 10:16 UTC, alinkedd commented on files/uk/web/javascript/reference/iteration_protocols/index.md
> +- Усі ітератори-обгортки безпосередньо переспрямовують метод `next()` внутрішнього ітератора, в тому числі повернені значення та викинуті помилки.
```suggestion
- Усі ітератори-обгортки безпосередньо переспрямовують метод `next()` внутрішнього ітератора, включно з поверненими значеннями та викинутими помилками.
```

2024-08-02 10:16 UTC, alinkedd commented on files/uk/web/javascript/reference/iteration_protocols/index.md
> +- Ітератори-обгортки, загалом, безпосередньо переспрямовують метод `return()` внутрішнього ітератора. Якщо метод `return()` на внутрішньому ітераторі не існує, то зовнішній повертає натомість `{ done
```suggestion
- Ітератори-обгортки загалом безпосередньо переспрямовують метод `return()` внутрішнього ітератора. Якщо метод `return()` на внутрішньому ітераторі не існує, то зовнішній повертає натомість `{ done: true, value: undefined }`. У разі ітераторних помічників: якщо метод `next()` ітераторного помічника ще не був викликаний, то після спроби викликати `return()` на внутрішньому ітераторі поточний ітератор завжди повертає `{ done: true, value: undefined }`. Ця поведінка узгоджена з функціями-генераторами, в яких плин виконання ще не дійшов до виразу `yield*`.
```

2024-08-02 10:16 UTC, alinkedd commented on files/uk/web/javascript/reference/iteration_protocols/index.md
> +- `yield*` – це єдиний вбудований запис синтаксису, що переспрямовує метод `throw()` внутрішнього ітератора. Про те, як [`yield*`](/uk/docs/Web/JavaScript/Reference/Operators/yield*) переспрямовує ме
довідці чи довіднику?

2024-08-02 10:17 UTC, alinkedd commented
@undead404 використай, будь ласка, поради зверху для нового PR

2024-08-02 10:36 UTC, undead404 commented on files/uk/web/javascript/reference/iteration_protocols/index.md
> +- `yield*` – це єдиний вбудований запис синтаксису, що переспрямовує метод `throw()` внутрішнього ітератора. Про те, як [`yield*`](/uk/docs/Web/JavaScript/Reference/Operators/yield*) переспрямовує ме
Мабуть, довідці, бо мова ж про одну сторіночку, а не цілу книгу