update(JS): web/javascript/inheritance_and_the_prototype_chain
webdoky/content pull request #3156
Opened 2024-07-18 05:20 UTC by undead404

2024-07-18 05:50 UTC, undead404 commented on files/uk/web/javascript/inheritance_and_the_prototype_chain/index.md
> +При використанні ключа `__proto__` у [ініціалізаторах об'єктів](/uk/docs/Web/JavaScript/Reference/Operators/Object_initializer), спрямування ключа `__proto__` на щось, що не є об'єктом, призводить ли
```suggestion
При використанні ключа `__proto__` в [ініціалізаторах об'єктів](/uk/docs/Web/JavaScript/Reference/Operators/Object_initializer), спрямування ключа `__proto__` на щось, що не є об'єктом, призводить лише до непомітної невдачі, без викидання винятку. На противагу сетеру [`Object.prototype.__proto__`](/uk/docs/Web/JavaScript/Reference/Global_Objects/Object/proto), `__proto__` у літеральних ініціалізаторах об'єктів – стандартизована й оптимізована можливість, що може бути навіть ефективнішою за {{jsxref("Object.create")}}. Оголошення власних додаткових властивостей на об'єкті під час його створення – ергономічніше за {{jsxref("Object.create")}}.
```

2024-08-09 16:24 UTC, alinkedd requested changes

2024-08-09 16:24 UTC, alinkedd commented on files/uk/web/javascript/inheritance_and_the_prototype_chain/index.md
> +Подібно до ключа `__proto__` в об'єктних ініціалізаторах, `Object.create()` дає змогу безпосередньо задавати прототип об'єкта під час його створення, завдяки чому середовище виконання отримує змогу щ
```suggestion
Подібно до ключа `__proto__` в об'єктних ініціалізаторах, `Object.create()` дає змогу безпосередньо задавати прототип об'єкта під час його створення, завдяки чому середовище виконання отримує змогу ще більше оптимізувати цей об'єкт. Також це дає змогу створювати об'єкти з прототипом `null` за допомогою `Object.create(null)`. Другий параметр `Object.create()` дає змогу точно задати атрибути кожної властивості в новому об'єкті, що може бути двосічним мечем:
```

2024-08-09 16:24 UTC, alinkedd commented on files/uk/web/javascript/inheritance_and_the_prototype_chain/index.md
> +- Це дає змогу створювати неперелічувані властивості тощо під час створення об'єкта, що неможливо з використанням об'єктних літералів.
```suggestion
- Це дає змогу створювати неперелічувані властивості та інше під час створення об'єкта, що неможливо з використанням об'єктних літералів.
```

2024-08-09 16:24 UTC, alinkedd commented on files/uk/web/javascript/inheritance_and_the_prototype_chain/index.md
> +Класи пропонують найкращу прочитність і підтримуваність при визначенні складних структур успадкування. [Приватні властивості](/uk/docs/Web/JavaScript/Reference/Classes/Private_properties) – це можлив
```suggestion
Класи пропонують найкращу прочитність і підтримуваність під час визначення складних структур успадкування. [Приватні властивості](/uk/docs/Web/JavaScript/Reference/Classes/Private_properties) – це можливість без тривіальної заміни за допомогою прототипного успадкування. Проте класи менше оптимізовані, аніж традиційні функції-конструктори, й не підтримуються в старих середовищах.
```

2024-08-09 16:24 UTC, alinkedd commented on files/uk/web/javascript/inheritance_and_the_prototype_chain/index.md
> +Проте слід задавати прототип під час створення об'єкта, якщо це можливо, тому що динамічне задання прототипу порушує усі оптимізації, які рушії виконують щодо ланцюжка прототипів. Це може змусити час
```suggestion
Проте, за можливості, слід задавати прототип під час створення об'єкта, тому що динамічне задання прототипу порушує усі оптимізації, які рушії виконують щодо ланцюжка прототипів. Це може змусити частину рушіїв компілювати ваш код наново заради деоптимізації, аби він працював згідно зі специфікаціями.
```

2024-08-09 16:24 UTC, alinkedd commented on files/uk/web/javascript/inheritance_and_the_prototype_chain/index.md
> +Порівняно з `Object.setPrototypeOf`, задання `__proto__` з чимось, що не є об'єктом, тихо не вдається, без викидання винятку. Також у цієї можливості трохи краща підтримка з боку браузерів. Проте вон
```suggestion
Порівняно з `Object.setPrototypeOf`, задання для `__proto__` значення, що не є об'єктом, збоїть непомітно без викидання винятку. Також у цієї можливості трохи краща підтримка з боку браузерів. Проте вона нестандартна та нерекомендована. Замість неї майже завжди слід користуватися `Object.setPrototypeOf`.
```

2024-08-09 20:55 UTC, alinkedd approved these changes

2024-08-09 21:14 UTC, merged