update(HTML): web/html/element/datalist
webdoky/content pull request #3167
Opened 2024-07-18 07:09 UTC by undead404

2024-07-18 07:11 UTC, undead404 commented on files/uk/web/html/element/datalist/index.md
> +Кожний елемент `<option>` повинен мати атрибут `value`, що представляє пропозицію для введення в поле. Також він може мати атрибут `label`, або, якщо останнього немає, то певний текстовий вміст, який
```suggestion
Кожний елемент `<option>` повинен мати атрибут `value`, що представляє пропозицію для введення в поле. Також він може мати атрибут `label`, або, якщо останнього немає, то певний текстовий вміст, який браузер може вивести замість `value` (Firefox) або на додачу до `value` (Chrome і Safari – як доповняльний текст). Конкретний вміст спадного меню залежить від браузера, проте коли варіантом клацають, то вміст, що вводиться у контрольне поле, завжди береться з атрибута `value`.
```

2024-07-20 13:52 UTC, alinkedd requested changes

2024-07-20 13:52 UTC, alinkedd commented on files/uk/web/html/element/datalist/index.md
> +- Оскільки застосування до списку варіантів CSS дуже обмежене або відсутнє, візуалізацію не можна оформити в режимі високого контрасту.
```suggestion
- Оскільки доступ до списку варіантів за допомогою CSS дуже обмежений або відсутній, їхня візуалізація не може бути стилізована для режиму високого контрасту.
```

2024-07-20 13:52 UTC, alinkedd commented on files/uk/web/html/element/datalist/index.md
> +- Частина комбінацій читачів з екрана та браузерів, включно з NVDA та Firefox, не оголошує вміст спливного списку автозаповнення.
```suggestion
- Частина комбінацій читачів з екрана та браузерів, включно з NVDA та Firefox, не виголошує вміст спливного списку автозаповнення.
```

2024-07-20 13:52 UTC, alinkedd commented on files/uk/web/html/element/datalist/index.md
> +Кожний елемент `<option>` повинен мати атрибут `value`, що представляє пропозицію для введення в поле. Також він може мати атрибут `label`, або, якщо останнього немає, то певний текстовий вміст, який
```suggestion
Кожний елемент `<option>` повинен мати атрибут `value`, який є пропозицією для введення в поле. Також він може мати атрибут `label` або, якщо останнього немає, певний текстовий вміст, який браузер може відображати замість `value` (Firefox) або на додачу до `value` (Chrome і Safari – як доповняльний текст). Конкретний вміст спадного меню залежить від браузера, проте коли варіантом клацають, то вміст, що вводиться у поле контрольного елемента, завжди береться з атрибута `value`.
```

2024-07-20 13:52 UTC, alinkedd commented on files/uk/web/html/element/datalist/index.md
> +> **Примітка:** `<datalist>` не є заміною для {{HTMLElement("select")}}. `<datalist>` не представляє саме поле; це список пропонованих значень для пов'язаного контрольного елемента. Цей контрольний е
```suggestion
> **Примітка:** `<datalist>` не є заміною для {{HTMLElement("select")}}. `<datalist>`, по суті, не є полем для введення; це список пропонованих значень для пов'язаного контрольного елемента. Цей контрольний елемент все одно може прийняти будь-яке значення, що проходить валідацію, навіть якщо його нема в списку пропозицій.
```

2024-07-20 14:13 UTC, alinkedd approved these changes

2024-07-20 15:08 UTC, merged