update(HTML): web/html/element/input/tel
webdoky/content pull request #3170
Opened 2024-07-18 07:12 UTC by undead404

2024-07-19 14:36 UTC, alinkedd requested changes

2024-07-19 14:36 UTC, alinkedd commented on files/uk/web/html/element/input/tel/index.md
> +Поле не пройде [валідацію обмежень](/uk/docs/Web/HTML/Constraint_validation), якщо довжина введеного в поле тексту перевищує `maxlength` кодових одиниць UTF-16 завдовжки. Валідація обмежень накладаєт
```suggestion
Поле не пройде [валідацію обмежень](/uk/docs/Web/HTML/Constraint_validation), якщо довжина введеного в поле тексту перевищує `maxlength` кодових одиниць UTF-16 завдовжки. Валідація обмежень відбувається лише тоді, коли користувач змінює значення.
```
нам треба вибрати якесь стандартне (користувач змінює значення, значення змінюється користувачем)
і is applied - тут або застосовується, відбувається, але накладається тут якось трохи не знаю.. обмеження накладаються, але валідація відбувається або проходить або щось інше

2024-07-19 14:41 UTC, undead404 commented on files/uk/web/html/element/input/tel/index.md
> +Поле не пройде [валідацію обмежень](/uk/docs/Web/HTML/Constraint_validation), якщо довжина введеного в поле тексту перевищує `maxlength` кодових одиниць UTF-16 завдовжки. Валідація обмежень накладаєт
По-перше, "відбувається" простіше, тому краще це й лишити.
А ось щодо другої частини, то тут додатком, думаю, має бути саме "користувачем". Тоді логічний наголос звучить правильно

2024-07-19 14:50 UTC, alinkedd commented on files/uk/web/html/element/input/tel/index.md
> +Поле не пройде [валідацію обмежень](/uk/docs/Web/HTML/Constraint_validation), якщо довжина введеного в поле тексту перевищує `maxlength` кодових одиниць UTF-16 завдовжки. Валідація обмежень накладаєт
```suggestion
Поле не пройде [валідацію обмежень](/uk/docs/Web/HTML/Constraint_validation), якщо довжина введеного в поле тексту перевищує `maxlength` кодових одиниць UTF-16 завдовжки. Валідація обмежень відбувається лише тоді, коли значення змінюється користувачем.
```

2024-07-19 14:51 UTC, alinkedd commented on files/uk/web/html/element/input/tel/index.md
> +Поле не пройде [валідацію обмежень](/uk/docs/Web/HTML/Constraint_validation), якщо довжина введеного в поле тексту перевищує `maxlength` кодових одиниць UTF-16 завдовжки. Валідація обмежень накладаєт
треба буде тоді по всіх файлах змінити, де ти додавав, я бачила там однакові рядки

2024-07-20 14:15 UTC, alinkedd requested changes

2024-07-20 14:15 UTC, alinkedd commented on files/uk/web/html/element/input/tel/index.md
> +Поле номера телефону не пройде [валідацію обмежень](/uk/docs/Web/HTML/Constraint_validation), якщо довжина введеного в поле тексту – менша за `minlength` кодових одиниць UTF-16 завдовжки. Валідація о
https://github.com/webdoky/content/pull/3170#discussion_r1684502103
```suggestion
Поле номера телефону не пройде [валідацію обмежень](/uk/docs/Web/HTML/Constraint_validation), якщо довжина введеного в поле тексту – менша за `minlength` кодових одиниць UTF-16 завдовжки. Валідація обмежень відбувається лише тоді, коли значення змінюється користувачем.
```

2024-07-20 16:37 UTC, alinkedd approved these changes

2024-07-20 16:43 UTC, merged