update(CSS): web/css/justify-content
webdoky/content pull request #3194
Opened 2024-07-29 10:59 UTC by undead404

2024-07-29 11:04 UTC, undead404 commented on files/uk/web/css/justify-content/index.md
> +Зауважте, що `justify-contents` шикує колонки та не впливає на елементи чи шикування в сіткових областях. Сіткові елементи, навіть ті з них, що не вміщаються в свою сіткову комірку, не впливають на в
```suggestion
Зауважте, що `justify-contents` шикує колонки та не впливає на елементи чи шикування в сіткових областях. Сіткові елементи, навіть ті з них, що не вміщаються у свою сіткову комірку, не впливають на вирівнювання колонок.
```

2024-07-29 11:04 UTC, undead404 commented on files/uk/web/css/justify-content/index.md
> +Цей приклад демонструє ключовий термін `safe`. Задаються чотири відцентровані гнучкі елементи, яким не дозволено переходити на нову лінію, і як наслідок – вони не вміщаються в своєму однолінійному гн
```suggestion
Цей приклад демонструє ключовий термін `safe`. Задаються чотири відцентровані гнучкі елементи, яким не дозволено переходити на нову лінію, і як наслідок – вони не вміщаються у своєму однолінійному гнучкому контейнері. Коли додати до `center` у властивості `justify-content` `safe`, то вміст, що не вміщається, поводиться так, ніби заданий спосіб шикування – `start`
```

2024-08-08 12:52 UTC, alinkedd requested changes
#1045 + inline [display] як рядний

2024-08-08 12:52 UTC, alinkedd commented on files/uk/web/css/justify-content/index.md
> +Ця властивість поділяє чимало значень – ключових слів зі властивістю {{cssxref("align-content")}}, проте не всі! `justify-content` не бере участі в шикуванні за базовою лінією, а отже – не приймає зн
```suggestion
Ця властивість поділяє чимало значень – ключових слів – із властивістю {{cssxref("align-content")}}, проте не всі! `justify-content` не бере участі в шикуванні за базовою лінією, а отже не приймає значень щодо базової лінії.
```
якщо `отже` можна замінити на `тому`, то його не треба виділяти комами або тире. тут також не пропускається дієслово, тому тире після 'отже' не треба.

2024-08-08 12:52 UTC, alinkedd commented on files/uk/web/css/justify-content/index.md
> +При [гнучкому компонуванні](/uk/docs/Web/CSS/CSS_flexible_box_layout) ця властивість визначає те, як додатний вільний простір розподіляється між або навколо гнучких елементів за головною віссю. Вона
додала крапку з комою, що краще читалось речення
```suggestion
За [гнучкого компонування](/uk/docs/Web/CSS/CSS_flexible_box_layout) ця властивість визначає те, як додатний вільний простір розподіляється між або навколо гнучких елементів за головною віссю. Вона впливає на простір між елементами в лінії, а не на простір між лініями. Шикування виконується, коли довжини та автоматичні зовнішні поля вже застосовані; тобто коли один або більше гнучких елементів на лінії мають множник {{cssxref("flex-grow")}}, більший за `0`, ця властивість не діє, оскільки на цій лінії немає простору для розподілу. Крім цього, оскільки розтягування на головній осі контролюється властивістю {{cssxref("flex")}}, значення `stretch` поводиться як `flex-start`.
```

може `автоматичні зовнішні поля` краще перекласти якось із застосуванням слова `auto` для `auto margins`? мені здається, це важливий момент

2024-08-08 12:52 UTC, alinkedd commented on files/uk/web/css/justify-content/index.md
> +При [сітковому компонуванні](/uk/docs/Web/CSS/CSS_grid_layout) ця властивість розподіляє доступний простір між або навколо сіткових колонок, а не сіткових елементів. Якщо сітковий контейнер більший з
```suggestion
За [сіткового компонування](/uk/docs/Web/CSS/CSS_grid_layout) ця властивість розподіляє доступний простір між або навколо сіткових колонок, а не сіткових елементів. Якщо сітковий контейнер більший за саму сітку, то властивістю `justify-content` можна скористатися для вирівнювання сітки за рядною віссю, шикуючи сіткові колонки.
```

2024-08-08 12:52 UTC, alinkedd commented on files/uk/web/css/justify-content/index.md
> +Сіткові доріжки з розміром `auto` (і лише вони) можуть розтягуватися властивостями `align-content` і `justify-content`. Таким чином, усталено доріжка з розміром `auto` займе всю решту простору в сітк
```suggestion
Сіткові доріжки з розміром `auto` (і лише вони) можуть розтягуватися властивостями `align-content` і `justify-content`. Тому усталено доріжка з розміром `auto` займе всю решту простору в сітковому контейнері. Оскільки рядний розмір сітки повинен бути меншим за рядний розмір сіткового контейнера, щоб для розподілу лишився якийсь простір, то ця властивість у такому разі ніяк не діє.
```

2024-08-08 12:52 UTC, alinkedd commented on files/uk/web/css/justify-content/index.md
> +### Базовий приклад з сіткою
```suggestion
### Базовий приклад із сіткою
```

2024-08-08 12:52 UTC, alinkedd commented on files/uk/web/css/justify-content/index.md
> +Задано різні ширини (та фонові кольори), аби продемонструвати, як вирівнювання застосовується до колонок.
тобто justification - вирівнювання, а aligning - шикування?

2024-08-08 12:52 UTC, alinkedd commented on files/uk/web/css/justify-content/index.md
> +{{EmbedLiveSample("bazovyi-pryklad-z-sitkoiu", "100%", 220)}}
```suggestion
{{EmbedLiveSample("bazovyi-pryklad-iz-sitkoiu", "100%", 220)}}
```

2024-08-08 12:52 UTC, alinkedd commented on files/uk/web/css/justify-content/index.md
> +<p><code>justify-content: safe center;</code> з 3 елементами</p>
```suggestion
<p><code>justify-content: safe center;</code> із 3 елементами</p>
```

2024-08-08 12:52 UTC, alinkedd commented on files/uk/web/css/justify-content/index.md
> +{{EmbedLiveSample("kliuchove-slovo-safe", "100%", 260)}}
тут тоді, мабуть, ключовий термін

2024-08-08 12:52 UTC, alinkedd commented on files/uk/web/css/justify-content/index.md
> +Оскільки елемент не вміщається в контейнері шикування, то з `safe` спосіб шикування поводиться як `start`, а шикування `center` не реалізовано. Ключовий термін `safe` не діє, якщо елементи вміщаються
```suggestion
Оскільки елемент не вміщається в контейнері шикування, то із `safe` спосіб шикування поводиться як `start`, а шикування `center` не реалізовано. Ключовий термін `safe` не діє, якщо елементи вміщаються в контейнері.
```

2024-08-08 12:52 UTC, alinkedd commented on files/uk/web/css/justify-content/index.md
> +Оберіть різні ключові слова в спадному меню, аби побачити візуалізацію різних значень – ключових слів `justify-content`. Оскільки елемент на першій лінії може зростати, на цій лінії немає доступного
```suggestion
Виберіть різні ключові слова в спадному меню, аби побачити візуалізацію різних значень – ключових слів `justify-content`. Оскільки елемент на першій лінії може зростати, на цій лінії немає доступного простору, який могла б розподіляти властивість `justify-content`. У випадку значення `space-between` перший елемент на кожній лінії тримається початкового краю за головною віссю, а останній – кінцевого за головною. Як наслідок, якщо на лінії лише один елемент, то він шикується за головним початковим краєм (як це видно на останній лінії). Все не так для інших значень `space-*`, як то `space-evenly` та `space-around`, які центрують одноелементні гнучкі лінії.
```

2024-08-08 14:12 UTC, undead404 commented on files/uk/web/css/justify-content/index.md
> +При [гнучкому компонуванні](/uk/docs/Web/CSS/CSS_flexible_box_layout) ця властивість визначає те, як додатний вільний простір розподіляється між або навколо гнучких елементів за головною віссю. Вона
А давай в дужках поставимо `margin: auto;`

2024-08-08 14:12 UTC, undead404 commented on files/uk/web/css/justify-content/index.md
> +Задано різні ширини (та фонові кольори), аби продемонструвати, як вирівнювання застосовується до колонок.
Мені хотілось би, щоб так було...

2024-08-08 14:13 UTC, undead404 commented on files/uk/web/css/justify-content/index.md
> +{{EmbedLiveSample("kliuchove-slovo-safe", "100%", 260)}}
```suggestion
{{EmbedLiveSample("kliuchovyi-termin-safe", "100%", 260)}}
```

2024-08-08 16:27 UTC, alinkedd commented on files/uk/web/css/justify-content/index.md
> +Задано різні ширини (та фонові кольори), аби продемонструвати, як вирівнювання застосовується до колонок.
```suggestion
Задано різні ширини (та фонові кольори), аби продемонструвати, як вирівнювання за головною віссю застосовується до колонок.
```

2024-08-08 17:24 UTC, undead404 commented on files/uk/web/css/justify-content/index.md
> +При [гнучкому компонуванні](/uk/docs/Web/CSS/CSS_flexible_box_layout) ця властивість визначає те, як додатний вільний простір розподіляється між або навколо гнучких елементів за головною віссю. Вона
```suggestion
За [гнучкого компонування](/uk/docs/Web/CSS/CSS_flexible_box_layout) ця властивість визначає те, як додатний вільний простір розподіляється між або навколо гнучких елементів за головною віссю. Вона впливає на простір між елементами в лінії, а не на простір між лініями. Шикування виконується, коли довжини та автоматичні зовнішні поля (`margin: auto;`) вже застосовані; тобто коли один або більше гнучких елементів на лінії мають множник {{cssxref("flex-grow")}}, більший за `0`, ця властивість не діє, оскільки на цій лінії немає простору для розподілу. Крім цього, оскільки розтягування на головній осі контролюється властивістю {{cssxref("flex")}}, значення `stretch` поводиться як `flex-start`.
```

2024-08-08 17:33 UTC, alinkedd approved these changes
Апрув, але треба буде окремо прогнати потім базу перекладів для шикування та inline/рядний

2024-08-08 20:46 UTC, merged