update(CSS): web/css/vertical-align
webdoky/content pull request #3201
Opened 2024-07-29 12:57 UTC by undead404

2024-08-08 21:56 UTC, alinkedd requested changes

2024-08-08 21:56 UTC, alinkedd commented on files/uk/web/css/vertical-align/index.md
> +У цьому прикладі – таблиця з одним рядом, що містить шість комірок. Ряд задає `vertical-align` усталене значення `bottom`.
```suggestion
У цьому прикладі таблиця з одним рядом, що містить шість комірок. Ряд задає усталене значення `bottom` для `vertical-align`.
```

2024-08-08 21:56 UTC, alinkedd commented on files/uk/web/css/vertical-align/index.md
> +- Кожна з перших чотирьох комірок має власне значення `vertical-align`, і ці значення перемагають значення від ряду.
```suggestion
- Кожна з перших чотирьох комірок має власне значення `vertical-align`, і ці значення перевизначають значення від ряду.
```

2024-08-08 21:56 UTC, alinkedd commented on files/uk/web/css/vertical-align/index.md
> +- П'ята комірка не задає жодного значення `vertical-align`, тому успадковує значення від ряду.
```suggestion
- П'ята комірка не має жодного значення `vertical-align`, тому успадковує значення від ряду.
```

2024-08-08 21:56 UTC, alinkedd commented on files/uk/web/css/vertical-align/index.md
> +    <td>bottom</td>
перекласти

2024-08-08 21:56 UTC, alinkedd commented on files/uk/web/css/vertical-align/index.md
> +      товарів) критично необхідне для розвитку.
тут lorem ipsum

2024-08-08 22:14 UTC, undead404 commented on files/uk/web/css/vertical-align/index.md
> +    <td>bottom</td>
Це ж ключові слова, хіба ні?

2024-08-08 22:14 UTC, undead404 commented on files/uk/web/css/vertical-align/index.md
> +      товарів) критично необхідне для розвитку.
Так, це він

2024-08-09 11:48 UTC, alinkedd commented on files/uk/web/css/vertical-align/index.md
> +    <td>bottom</td>
тоді ок

2024-08-09 11:48 UTC, alinkedd commented on files/uk/web/css/vertical-align/index.md
> +      товарів) критично необхідне для розвитку.
а чому просто не залишити lorem ipsum?

2024-08-09 12:36 UTC, undead404 commented on files/uk/web/css/vertical-align/index.md
> +      товарів) критично необхідне для розвитку.
Мені здалося, краще втулити щось українською

2024-08-09 12:36 UTC, undead404 commented on files/uk/web/css/vertical-align/index.md
> +      товарів) критично необхідне для розвитку.
Я навіть зазвичай роблю саме так

2024-08-09 13:35 UTC, alinkedd commented on files/uk/web/css/vertical-align/index.md
> +      товарів) критично необхідне для розвитку.
ну добре, добре :)

2024-08-09 13:35 UTC, alinkedd approved these changes

2024-08-09 18:38 UTC, merged