update(CSS): web/css/line-height
webdoky/content pull request #3213
Opened 2024-07-29 13:49 UTC by undead404

2024-07-29 14:51 UTC, undead404 commented on files/uk/web/css/line-height/index.md
> +Властивість [CSS](/uk/docs/Web/CSS) **`line-height`** (висота лінії) задає висоту рамки-лінії за горизонтального [напрямку письма](/uk/docs/Web/CSS/writing-mode#vertical-rl). За вертикального письма
```suggestion
Властивість [CSS](/uk/docs/Web/CSS) **`line-height`** (висота лінії) задає висоту рамки-лінії за горизонтального [напрямку письма](/uk/docs/Web/CSS/writing-mode#vertical-rl). За вертикального письма вона задає ширину рамки-лінії. Цю властивість заведено вживати для задання відстані між рядками тексту. Для елементів блокового рівня за горизонтального письма вона задає бажану висоту рамок-ліній в межах елемента, а для не[заміщених](/uk/docs/Web/CSS/Replaced_element) рядних елементів – задає висоту, що вживається для обчислення висоти рамки-лінії.
```

2024-08-01 12:17 UTC, alinkedd requested changes

2024-08-01 12:17 UTC, alinkedd commented on files/uk/web/css/line-height/index.md
> +Властивість [CSS](/uk/docs/Web/CSS) **`line-height`** (висота лінії) задає висоту рамки-лінії за горизонтального [напрямку письма](/uk/docs/Web/CSS/writing-mode#vertical-rl). За вертикального письма
чому рамки-лінії (line box) через дефіс? тут же лінія не прикладка (загальне уточнюване), а власне чиї рамки. має бути або "рамки рядка", або "рамки лінії"

2024-08-01 12:17 UTC, alinkedd commented on files/uk/web/css/line-height/index.md
> +Властивість [CSS](/uk/docs/Web/CSS) **`line-height`** (висота лінії) задає висоту рамки-лінії за горизонтального [напрямку письма](/uk/docs/Web/CSS/writing-mode#vertical-rl). За вертикального письма
```suggestion
Властивість [CSS](/uk/docs/Web/CSS) **`line-height`** (висота лінії) задає висоту рамки-лінії за горизонтального [напрямку письма](/uk/docs/Web/CSS/writing-mode#vertical-rl). За вертикального письма вона задає ширину рамки-лінії. Цю властивість заведено вживати для задання відстані між рядками тексту. Для елементів блокового рівня за горизонтального письма вона задає бажану висоту рамок-ліній в межах елемента, а для не[заміщених](/uk/docs/Web/CSS/Replaced_element) рядних елементів – висоту, що вживається для обчислення висоти рамки-лінії.
```
тире замість дієслова

2024-08-01 12:17 UTC, alinkedd commented on files/uk/web/css/line-height/index.md
> +Властивість [CSS](/uk/docs/Web/CSS) **`line-height`** (висота лінії) задає висоту рамки-лінії за горизонтального [напрямку письма](/uk/docs/Web/CSS/writing-mode#vertical-rl). За вертикального письма
https://webdoky.org/docs/glossary/#terminy
inline - вбудований, рядковий.
чому рядний? якщо це новий переклад, то треба його в глосарій

2024-08-01 12:17 UTC, alinkedd commented on files/uk/web/css/line-height/index.md
> +Властивість [CSS](/uk/docs/Web/CSS) **`line-height`** (висота лінії) задає висоту рамки-лінії за горизонтального [напрямку письма](/uk/docs/Web/CSS/writing-mode#vertical-rl). За вертикального письма
line - рядок чи лінія? вже вирішили чи це новий переклад?

2024-08-08 11:46 UTC, alinkedd commented on files/uk/web/css/line-height/index.md
> +Властивість [CSS](/uk/docs/Web/CSS) **`line-height`** (висота лінії) задає висоту рамки-лінії за горизонтального [напрямку письма](/uk/docs/Web/CSS/writing-mode#vertical-rl). За вертикального письма
- рамки-лінії означає, що рамки є лініями (прикладка - це означення https://uk.wikipedia.org/wiki/%D0%9F%D1%80%D0%B8%D0%BA%D0%BB%D0%B0%D0%B4%D0%BA%D0%B0)
- рамки лінії означає, що це рамки самої лінії

2024-08-08 11:55 UTC, undead404 commented on files/uk/web/css/line-height/index.md
> +Властивість [CSS](/uk/docs/Web/CSS) **`line-height`** (висота лінії) задає висоту рамки-лінії за горизонтального [напрямку письма](/uk/docs/Web/CSS/writing-mode#vertical-rl). За вертикального письма
Прийму в дар пораду, як це перекладати......

2024-08-08 13:15 UTC, alinkedd commented on files/uk/web/css/line-height/index.md
> +Властивість [CSS](/uk/docs/Web/CSS) **`line-height`** (висота лінії) задає висоту рамки-лінії за горизонтального [напрямку письма](/uk/docs/Web/CSS/writing-mode#vertical-rl). За вертикального письма
да просто без дефіса :smiley:

2024-08-08 14:27 UTC, undead404 commented on files/uk/web/css/line-height/index.md
> +Властивість [CSS](/uk/docs/Web/CSS) **`line-height`** (висота лінії) задає висоту рамки-лінії за горизонтального [напрямку письма](/uk/docs/Web/CSS/writing-mode#vertical-rl). За вертикального письма
```suggestion
Властивість [CSS](/uk/docs/Web/CSS) **`line-height`** (висота лінії) задає висоту рамки-лінії за горизонтального [напрямку письма](/uk/docs/Web/CSS/writing-mode#vertical-rl). За вертикального письма вона задає ширину рамки лінії. Цю властивість заведено вживати для задання відстані між рядками тексту. Для елементів блокового рівня за горизонтального письма вона задає бажану висоту рамок ліній в межах елемента, а для не[заміщених](/uk/docs/Web/CSS/Replaced_element) рядних елементів – задає висоту, що вживається для обчислення висоти рамки лінії.
```

2024-08-08 16:25 UTC, alinkedd approved these changes
line тут лінія (а не рядок) - для inline контенту

2024-08-08 17:23 UTC, merged