update(JS): web/javascript/reference/global_objects/promise/resolve
webdoky/content pull request #3217
Opened 2024-07-29 14:34 UTC by undead404

2024-07-31 21:30 UTC, alinkedd commented on files/uk/web/javascript/reference/global_objects/promise/resolve/index.md
> +> [!NOTE]
А у нас ці штуки є макроси? Це ж щось нове?

2024-07-31 21:35 UTC, alinkedd requested changes

2024-07-31 21:35 UTC, alinkedd commented on files/uk/web/javascript/reference/global_objects/promise/resolve/index.md
> +> Не слід викликати `Promise.resolve()` на очікуваному об'єкті, що вирішується самим собою. Це призводить до нескінченної рекурсії, адже намагається сплющити проміс нескінченної вкладеності.
that resolves to itself - вирішується самим собою
шось не те.

flatten - сплющити?

2024-08-01 06:20 UTC, undead404 commented on files/uk/web/javascript/reference/global_objects/promise/resolve/index.md
> +> [!NOTE]
Це щось нове, макросів на це нема, але ми стараємось дотримуватися відповідності по контенту один-в-один

2024-08-01 06:21 UTC, undead404 commented on files/uk/web/javascript/reference/global_objects/promise/resolve/index.md
> +> Не слід викликати `Promise.resolve()` на очікуваному об'єкті, що вирішується самим собою. Це призводить до нескінченної рекурсії, адже намагається сплющити проміс нескінченної вкладеності.
Ну тут малось на увазі, що проміс отримує значення самого себе.

flatten – сплющити. Можна ще сплощини, можливо?

2024-08-01 12:02 UTC, alinkedd commented on files/uk/web/javascript/reference/global_objects/promise/resolve/index.md
> +> Не слід викликати `Promise.resolve()` на очікуваному об'єкті, що вирішується самим собою. Це призводить до нескінченної рекурсії, адже намагається сплющити проміс нескінченної вкладеності.
я думаю, що тут краще описати про це значення, ніж вирішується самим собою, бо це взагалі не очевидно

про сплющити: в глосарії сплощення (flattening), а дія за цим іменником - це сплощити, сплощувати

2024-08-01 12:21 UTC, undead404 commented on files/uk/web/javascript/reference/global_objects/promise/resolve/index.md
> +> Не слід викликати `Promise.resolve()` на очікуваному об'єкті, що вирішується самим собою. Це призводить до нескінченної рекурсії, адже намагається сплющити проміс нескінченної вкладеності.
Я не знаю, як це стисло описати... Можна і сплощити, непринципово

2024-08-01 14:23 UTC, alinkedd commented on files/uk/web/javascript/reference/global_objects/promise/resolve/index.md
> +> Не слід викликати `Promise.resolve()` на очікуваному об'єкті, що вирішується самим собою. Це призводить до нескінченної рекурсії, адже намагається сплющити проміс нескінченної вкладеності.
Так ти вже описав: отримує значення самого себе. Це доволі стисло

2024-08-01 14:40 UTC, undead404 commented on files/uk/web/javascript/reference/global_objects/promise/resolve/index.md
> +> Не слід викликати `Promise.resolve()` на очікуваному об'єкті, що вирішується самим собою. Це призводить до нескінченної рекурсії, адже намагається сплющити проміс нескінченної вкладеності.
Сплощення тут це не "отримання значення самого себе". Сплощення – це розгортання цибулини зі вкладених одне в одного промісів до одного проміса, в якому вміщається значення, присутнє на кінці ланцюжка.

Це не дуже стисло й не дуже очевидно

2024-08-01 21:24 UTC, alinkedd commented on files/uk/web/javascript/reference/global_objects/promise/resolve/index.md
> +> Не слід викликати `Promise.resolve()` на очікуваному об'єкті, що вирішується самим собою. Це призводить до нескінченної рекурсії, адже намагається сплющити проміс нескінченної вкладеності.
так я не про сплощення або не може зрозуміти

таке
```suggestion
> Не слід викликати `Promise.resolve()` на очікуваному об'єкті, що отримує значення самого себе. Це призводить до нескінченної рекурсії, адже намагається сплощити проміс нескінченної вкладеності.
```
або таке
```suggestion
> Не слід викликати `Promise.resolve()` на очікуваному об'єкті, що звертається до самого себе. Це призводить до нескінченної рекурсії, адже намагається сплощити проміс нескінченної вкладеності.
```

2024-08-02 05:32 UTC, undead404 commented on files/uk/web/javascript/reference/global_objects/promise/resolve/index.md
> +> Не слід викликати `Promise.resolve()` на очікуваному об'єкті, що вирішується самим собою. Це призводить до нескінченної рекурсії, адже намагається сплющити проміс нескінченної вкладеності.
```suggestion
> Не слід викликати `Promise.resolve()` на очікуваному об'єкті, що вміщає самого себе як значення вирішення. Це призводить до нескінченної рекурсії, адже намагається сплощити проміс нескінченної вкладеності.
```
Може бути так.

2024-08-08 16:32 UTC, alinkedd commented on files/uk/web/javascript/reference/global_objects/promise/resolve/index.md
> +> Не слід викликати `Promise.resolve()` на очікуваному об'єкті, що вирішується самим собою. Це призводить до нескінченної рекурсії, адже намагається сплющити проміс нескінченної вкладеності.
ок

2024-08-08 17:32 UTC, alinkedd approved these changes

2024-08-08 20:46 UTC, merged