update(HTML): web/html/attributes/autocomplete
webdoky/content pull request #3239
Opened 2024-08-02 08:44 UTC by undead404

2024-08-02 08:47 UTC, undead404 commented on files/uk/web/html/attributes/autocomplete/index.md
> +  - : Код телефонного розширення в номері телефону, наприклад, номер кімнати чи номеру готеля, чи офісне розширення в компанії.
```suggestion
  - : Код телефонного розширення в номері телефону, наприклад, номер кімнати чи номеру в готелі, чи офісне розширення в компанії.
```

2024-08-09 15:28 UTC, alinkedd requested changes

2024-08-09 15:28 UTC, alinkedd commented on files/uk/web/html/attributes/autocomplete/index.md
> +  - : Новий пароль. При створенні нового облікового запису або зміні пароля це значення повинно застосовуватись для полів "Уведіть новий пароль" і "Підтвердьте новий пароль", на противагу "Введіть св
```suggestion
  - : Новий пароль. Під час створення нового облікового запису або зміні пароля це значення повинно застосовуватись для полів "Уведіть новий пароль" і "Підтвердьте новий пароль", на противагу "Введіть свій теперішній пароль", що також може бути присутнім. Браузер може скористатися цим значенням, щоб не вдатися до випадкового вставляння теперішнього пароля та допомоги зі створення безпечного пароля.
```

2024-08-09 15:28 UTC, alinkedd commented on files/uk/web/html/attributes/autocomplete/index.md
> +  - : Одноразовий пароль (OTP) для перевірки ідентичності користувача, який використовується як додатковий фактор при вході.
```suggestion
  - : Одноразовий пароль (OTP) для перевірки ідентичності користувача, який використовується як додатковий фактор під час входу.
```

2024-08-09 15:28 UTC, alinkedd commented on files/uk/web/html/attributes/autocomplete/index.md
> +  - : Назва посади особи в організації, наприклад, "Старший технічний дописувач", "Президент" або "Заступник керівника відділу".
```suggestion
  - : Назва посади особи просто або в організації, наприклад, "Старший технічний дописувач", "Президент" або "Заступник керівника відділу".
```

2024-08-09 15:28 UTC, alinkedd commented on files/uk/web/html/attributes/autocomplete/index.md
> +  - : Назва компанії або організації, наприклад, "ПАТ Еліт сервіс" або "ГО Теплі серця".
я оце думаю, може і приклад для телефону теж зробити з українським номером, а не американським?

навіть просто через це https://uk.wikipedia.org/wiki/%D0%A2%D0%B5%D0%BB%D0%B5%D1%84%D0%BE%D0%BD%D0%BD%D1%96_%D0%BA%D0%BE%D0%B4%D0%B8_%D0%A3%D0%BA%D1%80%D0%B0%D1%97%D0%BD%D0%B8#%D0%9F%D1%80%D0%BE%D0%B1%D0%BB%D0%B5%D0%BC%D0%B8_%D1%96%D0%BC%D0%BF%D0%BB%D0%B5%D0%BC%D0%B5%D0%BD%D1%82%D0%B0%D1%86%D1%96%D1%97

2024-08-09 15:28 UTC, alinkedd commented on files/uk/web/html/attributes/autocomplete/index.md
> +  - : Сума, вказана в валюті, котра зі свого боку - у "`transaction-currency`", транзакції для платіжної форми.
```suggestion
  - : Сума, вказана в зазначеній у "`transaction-currency`" валюті, транзакції для платіжної форми.
```

2024-08-09 15:28 UTC, alinkedd commented on files/uk/web/html/attributes/autocomplete/index.md
> +  - : Ключі, згенеровані за допомогою [API Вебавтентифікації](/uk/docs/Web/API/Web_Authentication_API), які запитуються за допомогою умовного виклику {{domxref("CredentialsContainer.get()", "navigato
```suggestion
  - : Ключі, згенеровані за допомогою [API Вебавтентифікації](/uk/docs/Web/API/Web_Authentication_API), які запитуються за допомогою умовного виклику {{domxref("CredentialsContainer.get()", "navigator.credentials.get()")}} (тобто того, який включає `mediation: 'conditional'`). Ця лексема за наявності повинна стояти останньою в розділеному пробілами списку лексем. Більше інформації у [Вході за допомогою ключа через автозаповнення форми](https://web.dev/articles/passkey-form-autofill).
```

2024-08-09 18:40 UTC, undead404 commented on files/uk/web/html/attributes/autocomplete/index.md
> +Кожний розділений пробілами список лексем подробиць містить або тип приймача з цифровою контактною інформацією, у заданому порядку, або розділений пробілами список інших лексем.
```suggestion
Кожний розділений пробілами список лексем подробиць містить або тип отримувача з цифровою контактною інформацією, у заданому порядку, або розділений пробілами список інших лексем.
```

2024-08-09 18:41 UTC, undead404 commented on files/uk/web/html/attributes/autocomplete/index.md
> +      - : Номер телефону без кодів країни та місцевості. Може бути розбитий на дві частини, для номерів телефону, що містять номер АТС, а далі номер на цій АТС. Для номера телефону "555-6502" користу
Бо exchange – це (автоматична) телефонна станція. Вузол телефонного зв'язку, який з'єднує з конкретним абонентом

2024-08-09 18:43 UTC, undead404 commented on files/uk/web/html/attributes/autocomplete/index.md
> +  - : Назва компанії або організації, наприклад, "ПАТ Еліт сервіс" або "ГО Теплі серця".
Якщо тобі вистачить фантазії, то давай...

2024-08-09 19:51 UTC, alinkedd commented on files/uk/web/html/attributes/autocomplete/index.md
> +  - : Назва компанії або організації, наприклад, "ПАТ Еліт сервіс" або "ГО Теплі серця".
#3275

2024-08-09 19:52 UTC, alinkedd reviewed
А оце треба додавати?

https://github.com/mdn/content/commit/067a40e4ed27ea6e1f3b8bbfec15cd9dc3078f4c#diff-b9bb0e34e44fa3b71a393a139e4a43a9dd51ab219c7c87402c2a68f93ceaf53aR3

2024-08-09 21:00 UTC, undead404 commented
Так, треба

2024-08-09 21:13 UTC, alinkedd approved these changes

2024-08-09 21:16 UTC, merged