update(HTML): web/html
webdoky/content pull request #3276
Opened 2024-08-10 13:15 UTC by undead404

2024-08-10 13:17 UTC, undead404 commented on files/uk/web/html/index.md
> +  - : Коментарі HTML вживаються для додавання до розмітки пояснювальних приміток або для запобігання тому, щоб браузер залучав певні частини документу.
```suggestion
  - : Коментарі HTML вживаються для додавання до розмітки пояснювальних приміток або для запобігання тому, щоб браузер залучав певні частини документа.
```

2024-08-15 15:46 UTC, alinkedd requested changes

2024-08-15 15:46 UTC, alinkedd commented on files/uk/web/html/index.md
> +  - : Коментарі HTML вживаються для додавання до розмітки пояснювальних приміток або для запобігання тому, щоб браузер залучав певні частини документа.
```suggestion
  - : Коментарі HTML вживаються для додавання до розмітки пояснювальних приміток або для запобігання тому, щоб браузер інтерпретував певні частини документа.
```
https://uk.wikipedia.org/wiki/%D0%86%D0%BD%D1%82%D0%B5%D1%80%D0%BF%D1%80%D0%B5%D1%82%D0%B0%D1%86%D1%96%D1%8F
тут саме про програмну інтерпретацію програми.

або можна якось по-іншому

2024-08-15 17:24 UTC, alinkedd approved these changes

2024-08-16 06:52 UTC, merged