update(CSS): web/css/width
webdoky/content pull request #3283
Opened 2024-08-10 13:57 UTC by undead404

2024-08-15 16:38 UTC, alinkedd commented on files/uk/web/css/width/index.md
> +> Як геометрична властивість, `width` також застосовується до елементів SVG {{SVGElement("svg")}}, {{SVGElement("rect")}}, {{SVGElement("image")}} і {{SVGElement("foreignObject")}}, причому `auto` ви
```suggestion
> Як геометрична властивість, `width` також застосовується до елементів SVG {{SVGElement("svg")}}, {{SVGElement("rect")}}, {{SVGElement("image")}} і {{SVGElement("foreignObject")}}, причому `auto` вирішується як `100%` для `<svg>` і як `0` для інших елементів, а відсоткові значення відносні щодо ширини області перегляду SVG для `<rect>`. Значення властивості CSS `width` перемагає значення атрибута SVG {{SVGAttr("width")}}, якщо на елементі SVG такий задано.
```

2024-08-15 16:40 UTC, alinkedd requested changes

2024-08-15 16:40 UTC, alinkedd commented on files/uk/web/css/width/index.md
> +> Як геометрична властивість, `width` також застосовується до елементів SVG {{SVGElement("svg")}}, {{SVGElement("rect")}}, {{SVGElement("image")}} і {{SVGElement("foreignObject")}}, причому `auto` ви
До речі, чому overrides - перемагає? Може, все-таки якесь інше слово використовувати?

2024-08-15 16:43 UTC, alinkedd commented
Ось це https://github.com/webdoky/content/pull/3283#issuecomment-2281919390 можна виправити:
значенням em

2024-08-16 06:48 UTC, undead404 commented on files/uk/web/css/width/index.md
> +> Як геометрична властивість, `width` також застосовується до елементів SVG {{SVGElement("svg")}}, {{SVGElement("rect")}}, {{SVGElement("image")}} і {{SVGElement("foreignObject")}}, причому `auto` ви
Ну не "перевизначає" ж... Тут властивість перемагає атрибут, краще я не знаю як перекласти

2024-08-23 10:20 UTC, alinkedd approved these changes

2024-08-23 10:36 UTC, undead404 commented
На жаль, потрібна додаткова перевірка (див. додатковий коміт)

2024-08-23 11:37 UTC, alinkedd requested changes

2024-08-23 11:37 UTC, alinkedd commented on files/uk/web/css/width/index.md
> +  - : Задає ширині [рамки зовнішніх відступів](/uk/docs/Learn/CSS/Building_blocks/The_box_model#chastyny-ramky) елемента ширину його [контейнерного блока](/uk/docs/Web/CSS/Containing_block#vybir-kont
```suggestion
  - : Задає ширині [рамки зовнішніх відступів](/uk/docs/Learn/CSS/Building_blocks/The_box_model#chastyny-ramky) елемента ширину його [контейнерного блока](/uk/docs/Web/CSS/Containing_block#vybir-konteinernoho-bloka). Намагається змусити рамку зовнішніх відступів заповнити доступний у контейнерному блоці простір так, щоб це вийшло схоже на `100%`, але застосовуючи результівний розмір до рамки зовнішніх відступів, а не рамки, визначеної [box-sizing](/uk/docs/Web/CSS/box-sizing).
```

2024-08-23 11:38 UTC, alinkedd commented on files/uk/web/css/width/index.md
> +  - : Задає ширині [рамки зовнішніх відступів](/uk/docs/Learn/CSS/Building_blocks/The_box_model#chastyny-ramky) елемента ширину його [контейнерного блока](/uk/docs/Web/CSS/Containing_block#vybir-kont
те саме для PR із height

2024-08-23 12:07 UTC, alinkedd approved these changes

2024-08-23 13:07 UTC, merged