translation(glossary): glossary/accessibility_tree
webdoky/content pull request #3315
Opened 2024-08-23 20:13 UTC by undead404

2024-09-10 07:57 UTC, alinkedd requested changes

2024-09-10 07:57 UTC, alinkedd commented on files/uk/glossary/accessibility_tree/index.md
> +- [Ініціатива з вебдоступності W3C (WAI)](https://www.w3.org/WAI/)
в інших двох PR з доступністю без з
```suggestion
- [Ініціатива вебдоступності W3C (WAI)](https://www.w3.org/WAI/)
```
(можливо треба у них змінити, а не тут)

2024-09-10 07:57 UTC, alinkedd commented on files/uk/glossary/accessibility_tree/index.md
> +- [Доступні багаті інтернет-застосунки (WAI-ARIA)](https://w3c.github.io/aria/)
Тут і в інших двох PR з доступності:
Ми хіба не погодились на "збагачені" замість "багаті"?

2024-09-10 07:57 UTC, alinkedd commented on files/uk/glossary/accessibility_tree/index.md
> +  - : Як нам називати цю штуку? Наприклад, посилання з текстом "Читати далі" матиме назву "Читати далі" (більше про те, як обчислюються назви, читайте в [специфікації Обчислення доступних назви та оп
```suggestion
  - : Як нам називати це? Наприклад, посилання з текстом "Читати далі" матиме назву "Читати далі" (більше про те, як обчислюються назви, читайте в [специфікації Обчислення доступних назви та опису](https://www.w3.org/TR/accname-1.1/)).
```

2024-09-10 07:57 UTC, alinkedd commented on files/uk/glossary/accessibility_tree/index.md
> +  - : Як описати цю штуку, якщо треба надати більше опису, ніж просто назву? Опис таблиці може пояснювати, якого роду інформацію ця таблиця містить.
```suggestion
  - : Як описати це, якщо треба надати більше опису, ніж просто назву? Опис таблиці може пояснювати, якого типу інформацію ця таблиця містить.
```

2024-09-10 07:57 UTC, alinkedd commented on files/uk/glossary/accessibility_tree/index.md
> +  - : Якого різновиду ця штука? Наприклад, чи це кнопка, смуга навігації, чи список елементів?
```suggestion
  - : Якого різновиду це? Наприклад, чи це кнопка, смуга навігації або список елементів?
```

2024-09-10 07:57 UTC, alinkedd commented on files/uk/glossary/accessibility_tree/index.md
> +  - : Чи має вона стан? Серед прикладів – поле для галочки, що має галочку або ні, а також стан згорнутості та розгорнутості елемента [`<summary>`](/uk/docs/Web/HTML/Element/summary).
```suggestion
  - : Чи має це стан? Серед прикладів – поле для галочки, що має галочку або ні, а також стан згорнутості та розгорнутості елемента [`<summary>`](/uk/docs/Web/HTML/Element/summary).
```

2024-09-10 07:57 UTC, alinkedd commented on files/uk/glossary/accessibility_tree/index.md
> +**[Об'єктна модель доступності](https://wicg.github.io/aom/explainer.html) (AOM)**, хоч і досі, на квітень 2022 року, є чернеткою Web Incubator Community Group, має намір виносити API, завдяки яким л
```suggestion
**[Об'єктна модель доступності](https://wicg.github.io/aom/explainer.html) (AOM)**, хоч і досі, на квітень 2022 року, є чернеткою Web Incubator Community Group, має намір вѝносити API, завдяки яким легше буде виражати семантику доступності, і потенційно надавати доступ для зчитування обчисленого дерева доступності.
```

2024-09-11 06:45 UTC, undead404 commented on files/uk/glossary/accessibility_tree/index.md
> +  - : Як нам називати цю штуку? Наприклад, посилання з текстом "Читати далі" матиме назву "Читати далі" (більше про те, як обчислюються назви, читайте в [специфікації Обчислення доступних назви та оп
Ну без іменника, хоча б бутафорського, звучить куди гірше. Доведеться писати "вузол" чи "елемент". Як думаєш?

2024-09-11 06:45 UTC, undead404 commented on files/uk/glossary/accessibility_tree/index.md
> +- [Доступні багаті інтернет-застосунки (WAI-ARIA)](https://w3c.github.io/aria/)
```suggestion
- [Доступні збагачені інтернет-застосунки (WAI-ARIA)](https://w3c.github.io/aria/)
```

2024-09-11 10:30 UTC, alinkedd commented on files/uk/glossary/accessibility_tree/index.md
> +  - : Як нам називати цю штуку? Наприклад, посилання з текстом "Читати далі" матиме назву "Читати далі" (більше про те, як обчислюються назви, читайте в [специфікації Обчислення доступних назви та оп
можна просто `це` перемістити в середину запитання замість кінця
```suggestion
  - : Як це нам називати? Наприклад, посилання з текстом "Читати далі" матиме назву "Читати далі" (більше про те, як обчислюються назви, читайте в [специфікації Обчислення доступних назви та опису](https://www.w3.org/TR/accname-1.1/)).
```
або
```suggestion
  - : Як нам це називати? Наприклад, посилання з текстом "Читати далі" матиме назву "Читати далі" (більше про те, як обчислюються назви, читайте в [специфікації Обчислення доступних назви та опису](https://www.w3.org/TR/accname-1.1/)).
```

2024-09-11 10:31 UTC, alinkedd commented on files/uk/glossary/accessibility_tree/index.md
> +  - : Як нам називати цю штуку? Наприклад, посилання з текстом "Читати далі" матиме назву "Читати далі" (більше про те, як обчислюються назви, читайте в [специфікації Обчислення доступних назви та оп
`Як це` в інших варіантах теж має ок вигляд

2024-09-11 11:49 UTC, undead404 commented on files/uk/glossary/accessibility_tree/index.md
> +  - : Як нам називати цю штуку? Наприклад, посилання з текстом "Читати далі" матиме назву "Читати далі" (більше про те, як обчислюються назви, читайте в [специфікації Обчислення доступних назви та оп
```suggestion
  - : Як нам називати цю річ? Наприклад, посилання з текстом "Читати далі" матиме назву "Читати далі" (більше про те, як обчислюються назви, читайте в [специфікації Обчислення доступних назви та опису](https://www.w3.org/TR/accname-1.1/)).
```
Отак буде без просторічності

2024-09-11 17:01 UTC, alinkedd commented on files/uk/glossary/accessibility_tree/index.md
> +  - : Як нам називати цю штуку? Наприклад, посилання з текстом "Читати далі" матиме назву "Читати далі" (більше про те, як обчислюються назви, читайте в [специфікації Обчислення доступних назви та оп
чому завжди ця штука чи ця річ? Українській це не природно, це калька з англійської, у нас є просто `це`. `річ` - це або відподник для `дело`, або матеріальне у юриспунденції, або ще може бути `мова`

2024-09-11 18:35 UTC, undead404 commented on files/uk/glossary/accessibility_tree/index.md
> +  - : Як нам називати цю штуку? Наприклад, посилання з текстом "Читати далі" матиме назву "Читати далі" (більше про те, як обчислюються назви, читайте в [специфікації Обчислення доступних назви та оп
`Це` що? Ну некрасиво звучить. Коли бачу в тексті "це", постійно шукаю, що мається на увазі

2024-09-13 11:03 UTC, alinkedd commented on files/uk/glossary/accessibility_tree/index.md
> +  - : Як нам називати цю штуку? Наприклад, посилання з текстом "Читати далі" матиме назву "Читати далі" (більше про те, як обчислюються назви, читайте в [специфікації Обчислення доступних назви та оп
цей об'єкт

2024-09-13 12:18 UTC, undead404 commented on files/uk/glossary/accessibility_tree/index.md
> +  - : Як нам називати цю штуку? Наприклад, посилання з текстом "Читати далі" матиме назву "Читати далі" (більше про те, як обчислюються назви, читайте в [специфікації Обчислення доступних назви та оп
О, давай на цьому варіанті зупинимося

2024-09-13 12:49 UTC, alinkedd commented on files/uk/glossary/accessibility_tree/index.md
> +  - : Як нам називати цю штуку? Наприклад, посилання з текстом "Читати далі" матиме назву "Читати далі" (більше про те, як обчислюються назви, читайте в [специфікації Обчислення доступних назви та оп
```suggestion
  - : Як нам називати цей об'єкт? Наприклад, посилання з текстом "Читати далі" матиме назву "Читати далі" (більше про те, як обчислюються назви, читайте в [специфікації Обчислення доступних назви та опису](https://www.w3.org/TR/accname-1.1/)).
```

2024-09-17 14:41 UTC, alinkedd approved these changes

2024-09-17 14:43 UTC, merged