update(JS): web/javascript/guide/modules
webdoky/content pull request #3323
Opened 2024-08-27 10:20 UTC by undead404

2024-08-27 10:27 UTC, undead404 commented on files/uk/web/javascript/guide/modules/index.md
> +Браузери також виконують валідацію типу модуля, яка провалюється, якщо наприклад, `./data.json` не вирішується до файлу JSON. Це дає змогу мати певність, що жодний код випадково не виконається, коли
```suggestion
Браузери також виконують валідацію типу модуля, яка провалюється, якщо, наприклад, `./data.json` не вирішується до файлу JSON. Це дає змогу мати певність, що жодний код випадково не виконається, коли є намір лише імпортувати дані. Імпортоване значення, бувши імпортованим, можна використовувати як звичайний об'єкт JavaScript або об'єкт `CSSStyleSheet`.
```

2024-08-28 11:14 UTC, alinkedd requested changes

2024-08-28 11:14 UTC, alinkedd commented on files/uk/web/javascript/guide/modules/index.md
> +Одна з захопливих можливостей, яку приносить уніфікована архітектура модулів, – це змога завантажувати ресурси, що не є JavaScript, як модулі. Наприклад, можна імпортувати JSON як об'єкт JavaScript,
```suggestion
Одна з захопливих можливостей, яку приносить уніфікована архітектура модулів, – це змога завантажувати ресурси, що не є JavaScript-кодом, як модулі. Наприклад, можна імпортувати JSON як об'єкт JavaScript або імпортувати CSS як об'єкт {{domxref("CSSStyleSheet")}}.
```

2024-08-28 11:14 UTC, alinkedd commented on files/uk/web/javascript/guide/modules/index.md
> +Браузери також виконують валідацію типу модуля, яка провалюється, якщо, наприклад, `./data.json` не вирішується до файлу JSON. Це дає змогу мати певність, що жодний код випадково не виконається, коли
```suggestion
Браузери також виконують валідацію типу модуля, яка провалюється, якщо, наприклад, `./data.json` не вирішується до файлу JSON. Це дає змогу мати певність, що жодний код випадково не виконається, коли є намір лише імпортувати дані. Після успішного імпортування це значення можна використовувати як звичайний об'єкт JavaScript або об'єкт `CSSStyleSheet`.
```

2024-08-28 11:35 UTC, undead404 commented on files/uk/web/javascript/guide/modules/index.md
> +Одна з захопливих можливостей, яку приносить уніфікована архітектура модулів, – це змога завантажувати ресурси, що не є JavaScript, як модулі. Наприклад, можна імпортувати JSON як об'єкт JavaScript,
```suggestion
Одна з захопливих можливостей, яку приносить уніфікована архітектура модулів, – це змога завантажувати ресурси, що не є кодом на JavaScript, як модулі. Наприклад, можна імпортувати JSON як об'єкт JavaScript або імпортувати CSS як об'єкт {{domxref("CSSStyleSheet")}}.
```

2024-08-28 11:37 UTC, alinkedd commented on files/uk/web/javascript/guide/modules/index.md
> +Одна з захопливих можливостей, яку приносить уніфікована архітектура модулів, – це змога завантажувати ресурси, що не є JavaScript, як модулі. Наприклад, можна імпортувати JSON як об'єкт JavaScript,
ок

2024-08-28 11:42 UTC, alinkedd approved these changes

2024-08-28 11:44 UTC, merged