translation(JS): web/javascript/reference/operators/logical_or/
webdoky/content pull request #3344
Opened 2024-08-27 18:05 UTC by astropsy999

2024-08-27 18:25 UTC, undead404 requested changes
Дуже гарний переклад, направду

2024-08-27 18:25 UTC, undead404 commented on files/uk/web/javascript/reference/operators/logical_or/index.md
> +Оператор **логічного АБО (`||`)** (логічна диз'юнкція) для набору булевих операндів буде `true` тоді й лише тоді, коли один або більше операндів будуть `true`. Його зазвичай застосовують із булевими
```suggestion
Оператор **логічного АБО (`||`)** (логічна диз'юнкція) для набору булевих операндів буде `true` тоді й лише тоді, коли один або більше операндів будуть `true`. Його зазвичай застосовують щодо булевих (логічних) значень. У такому разі він повертає булеве значення. Однак насправді оператор `||` повертає значення одного з операндів, тож при використанні щодо небулевих значень він поверне небулеве значення.
```
"небулеве" треба додати до uk_spelling_additions.txt

2024-08-27 18:25 UTC, undead404 commented on files/uk/web/javascript/reference/operators/logical_or/index.md
> +`x`; інакше, повертає `y`.
```suggestion
`x`; інакше – повертає `y`.
```

2024-08-27 18:25 UTC, undead404 commented on files/uk/web/javascript/reference/operators/logical_or/index.md
> +Якщо значення може бути перетворено на `true`, його називають {{Glossary("truthy")}}.
```suggestion
Якщо значення може бути перетворено на `true`, його називають {{Glossary("truthy", "істинним")}}.
```

2024-08-27 18:25 UTC, undead404 commented on files/uk/web/javascript/reference/operators/logical_or/index.md
> +Якщо значення може бути перетворено на `false`, його називають {{Glossary("falsy")}}.
```suggestion
Якщо значення може бути перетворено на `false`, його називають {{Glossary("falsy", "хибним")}}.
```

2024-08-27 18:25 UTC, undead404 commented on files/uk/web/javascript/reference/operators/logical_or/index.md
> +Попри те, що оператор `||` може вживатися над небулевими операндами, він все одно вважається булевим, оскільки його повернене значення завжди може бути перетворено на [булів примітив](/uk/docs/Web/Ja
```suggestion
Попри те, що оператор `||` може застосовуватися щодо небулевих операндів, він все одно вважається булевим, оскільки його повернене значення завжди може бути перетворено на [булів примітив](/uk/docs/Web/JavaScript/Data_structures#typ-boolean).
```

2024-08-27 18:25 UTC, undead404 commented on files/uk/web/javascript/reference/operators/logical_or/index.md
> +Щоб явно перетворити його повернене значення (або будь який вираз загалом) на відповідне булеве значення, слід використати подвійний [оператор НЕ](/uk/docs/Web/JavaScript/Reference/Operators/Logical_
```suggestion
Щоб явно перетворити його повернене значення (або будь-який вираз загалом) на відповідне булеве значення, слід використати подвійний [оператор НЕ](/uk/docs/Web/JavaScript/Reference/Operators/Logical_NOT) або конструктор {{jsxref("Boolean/Boolean", "Boolean()")}}.
```

2024-08-27 18:25 UTC, undead404 commented on files/uk/web/javascript/reference/operators/logical_or/index.md
> +`(якійсь правдивий вираз) || вирз` закорочено обчислюється до `true`.
```suggestion
`(якійсь істинний вираз) || вирз` закорочено обчислюється до `true`.
```

2024-08-27 18:25 UTC, undead404 commented on files/uk/web/javascript/reference/operators/logical_or/index.md
> +`(якійсь правдивий вираз) || вирз` закорочено обчислюється до `true`.
Давай додамо "вирз" до uk_ignore_additions.txt

2024-08-27 18:25 UTC, undead404 commented on files/uk/web/javascript/reference/operators/logical_or/index.md
> +Закорочене означає, що частина `вирз` **не обчислюється**, тобто не трапляється ніяких побічних ефектів (якщо `вирз` це функція, то вона ніколи не викликається). Це тому, що значення оператора вже ви
```suggestion
Закорочене означає, що частина `вирз` **не обчислюється**, тобто не трапляється ніяких побічних ефектів (якщо `вирз` це функція, то вона ніколи не викликається). Це пов'язано з тим, що значення оператора очевидне вже після обчислення першого операнда. Погляньте на приклад:
```

2024-08-27 18:25 UTC, undead404 commented on files/uk/web/javascript/reference/operators/logical_or/index.md
> +// а потім виводить true (яке є результатом оператора)
```suggestion
// а потім виводить true (що є результатом оператора)
```

2024-08-27 18:25 UTC, undead404 commented on files/uk/web/javascript/reference/operators/logical_or/index.md
> +> Якщо ви використовуєте цей оператор для надання значення за замовчуванням якійсь
```suggestion
> Якщо ви використовуєте цей оператор для надання запасного значення якійсь
```

2024-08-27 18:25 UTC, undead404 commented on files/uk/web/javascript/reference/operators/logical_or/index.md
> +> змінній, майте на увазі, що будь-яке _хибне_ значення не буде використано. Якщо вам потрібно
```suggestion
> змінній, майте на увазі, що будь-яке _хибне_ значення не буде використано. Якщо потрібно
```

2024-08-27 18:25 UTC, undead404 commented on files/uk/web/javascript/reference/operators/logical_or/index.md
> +- {{Glossary("Truthy")}}
```suggestion
- {{Glossary("Truthy", "Істинне")}}
```

2024-08-27 18:25 UTC, undead404 commented on files/uk/web/javascript/reference/operators/logical_or/index.md
> +- {{Glossary("Falsy")}}
```suggestion
- {{Glossary("Falsy", "Хибне")}}
```

2024-08-28 04:55 UTC, astropsy999 commented on files/uk/web/javascript/reference/operators/logical_or/index.md
> +Попри те, що оператор `||` може вживатися над небулевими операндами, він все одно вважається булевим, оскільки його повернене значення завжди може бути перетворено на [булів примітив](/uk/docs/Web/Ja
Можливо в [цьому місці](https://webdoky.org/uk/docs/Web/JavaScript/Reference/Operators/Logical_AND/#opys) теж треба виправити це словосполучення?

2024-08-28 05:46 UTC, undead404 approved these changes

2024-08-28 05:47 UTC, merged