translation(glossary): glossary/accessible_name
webdoky/content pull request #3345
Opened 2024-08-27 18:12 UTC by undead404

2024-10-11 16:40 UTC, alinkedd requested changes

2024-10-11 16:40 UTC, alinkedd commented on files/uk/glossary/accessible_name/index.md
> +**Доступна назва** – це назва елемента користувацького інтерфейсу; це текст, пов'язаний з елементом HTML, який служить користувачам допоміжних технологій підписом елемента.
```suggestion
**Доступна назва** – це назва елемента користувацького інтерфейсу; це текст, пов'язаний з елементом HTML, який слугує користувачам допоміжних технологій підписом елемента.
```
https://onlinecorrector.com.ua/uk/%D1%81%D0%BB%D1%83%D0%B3%D1%83%D0%B2%D0%B0%D1%82%D0%B8/

2024-10-11 16:40 UTC, alinkedd commented on files/uk/glossary/accessible_name/index.md
> +Доступні назви доносять призначення чи задум елемента. Це допомагає користувачам зрозуміти, для чого цей елемент і як з ним взаємодіяти. Загалом, доступні назви елементів повинні бути неповторним на
```suggestion
Доступні назви доносять призначення чи намір елемента. Це допомагає користувачам зрозуміти, для чого цей елемент і як з ним взаємодіяти. Загалом, доступні назви елементів повинні бути неповторними на всій сторінці. Це допомагає користувачам відрізняти елемент від інших елементів і визначити елемент, з яким хочуть взаємодіяти.
```

2024-10-11 16:40 UTC, alinkedd commented on files/uk/glossary/accessible_name/index.md
> +Залежно від елемента та розмітки HTML, значення доступної назви може виводитися від видимого (наприклад, тексту всередині {{HTMLElement("figcaption")}}) або невидимого (наприклад, атрибута `aria-labe
```suggestion
Залежно від елемента та розмітки HTML, значення доступної назви може виводитися від видимого (наприклад, тексту всередині {{HTMLElement("figcaption")}}) або невидимого (наприклад, атрибута `aria-label`, заданого на елементі) вмісту, або ж від поєднання першого та другого. Те, як визначається доступна назва елемента, ґрунтується на [обчисленні доступної назви](https://www.w3.org/WAI/ARIA/apg/practices/names-and-descriptions/#name_calculation), яке відрізняється для різних елементів.
```
https://onlinecorrector.com.ua/uk/%D1%89%D0%BE-%D2%91%D1%80%D1%83%D0%BD%D1%82%D1%83%D1%94%D1%82%D1%8C%D1%81%D1%8F-%D0%BD%D0%B0/

2024-10-11 16:40 UTC, alinkedd commented on files/uk/glossary/accessible_name/index.md
> +Інші елементи отримують свою доступну назву від вмісту пов'язаних з ними елементів. Наприклад, коли елемент {{HTMLElement("fieldset")}} або {{HTMLElement("table")}} має серед нащадків елемент, відпов
```suggestion
Інші елементи отримують свою доступну назву від вмісту пов'язаних із ними елементів. Наприклад, коли елемент {{HTMLElement("fieldset")}} або {{HTMLElement("table")}} має серед нащадків елемент, відповідно, {{HTMLElement("legend")}} або {{HTMLElement("caption")}}, то зв'язування вкладеного елемента з предком, якому він надає доступну назву, є автоматичним. Для формових елементів, як-от {{HTMLElement("textarea")}} або {{HTMLElement("input")}}, доступна назва походить від пов'язаного з ними елемента {{HTMLElement("label")}}. Зв'язування необхідно явно визначити, задавши на елементі `<label>` атрибут `for`, що відповідає `id` формового елемента. Інший варіант – утворюється неявне зв'язування, коли формовий контрольний елемент безпосередньо вкладений в елемент `<label>`.
```

2024-10-11 16:40 UTC, alinkedd commented on files/uk/glossary/accessible_name/index.md
> +Для частини елементів доступна назва походить від атрибутів; наприклад, атрибута `alt` у разі {{HTMLElement("img")}}. Для зображення Given `<img src="grape.jpg" alt="банан"/>` доступна назва – це "ба
```suggestion
Для частини елементів доступна назва походить від атрибутів; наприклад, атрибута `alt` у разі {{HTMLElement("img")}}. Для зображення `<img src="grape.jpg" alt="банан"/>` доступна назва – це "банан".
```

2024-10-11 16:40 UTC, alinkedd commented on files/uk/glossary/accessible_name/index.md
> +- [Доступні багаті Інтернет-застосунки (WAI-ARIA)](https://w3c.github.io/aria/)
Так що ми багаті чи збагачені чи які?

2024-10-11 17:44 UTC, undead404 commented on files/uk/glossary/accessible_name/index.md
> +- [Доступні багаті Інтернет-застосунки (WAI-ARIA)](https://w3c.github.io/aria/)
```suggestion
- [Доступні збагачені Інтернет-застосунки (WAI-ARIA)](https://w3c.github.io/aria/)
```

2024-10-13 15:11 UTC, alinkedd approved these changes

2024-10-13 15:24 UTC, merged