translation(glossary): glossary/control_flow
webdoky/content pull request #3352
Opened 2024-08-30 10:56 UTC by undead404

2024-09-10 07:39 UTC, alinkedd requested changes

2024-09-10 07:39 UTC, alinkedd commented on files/uk/glossary/control_flow/index.md
> +Код запускається в порядку від першої лінії в файлі до останньої, якщо комп'ютер не зіткнеться (що трапляється вкрай часто) зі структурою, що змінює контрольний плин, наприклад, умовою чи циклом.
```suggestion
Код запускається в порядку від першої лінії у файлі до останньої, якщо комп'ютер не зіткнеться (що трапляється вкрай часто) зі структурою, що змінює контрольний плин, наприклад, умовою чи циклом.
```

2024-09-10 07:39 UTC, alinkedd commented on files/uk/glossary/control_flow/index.md
> +Наприклад, уявімо сценарій, що використовується для валідування користувацьких даних з форми на вебсторінці. Цей сценарій надсилає валідовані дані, проте якщо користувач, скажімо, залишить обов'язков
додати валідовані до словника

2024-09-10 07:39 UTC, alinkedd commented on files/uk/glossary/control_flow/index.md
> +Наприклад, уявімо сценарій, що використовується для валідування користувацьких даних з форми на вебсторінці. Цей сценарій надсилає валідовані дані, проте якщо користувач, скажімо, залишить обов'язков
```suggestion
Наприклад, уявімо сценарій, що використовується для валідування користувацьких даних із форми на вебсторінці. Цей сценарій надсилає валідовані дані, проте якщо користувач, скажімо, залишить обов'язкове поле порожнім, то сценарій нагадає його заповнити. Щоб це зробити, сценарій користується {{Glossary("Conditional", "умовною")}} структурою, тобто `if...else`, так, щоб виконувати різний код залежно від того, чи заповнена форма, чи ні:
```

2024-09-10 07:39 UTC, alinkedd commented on files/uk/glossary/control_flow/index.md
> +Типовий сценарій на {{glossary("JavaScript")}} або {{glossary("PHP")}} (чи інших подібних мовах) містить чимало контрольних структур, серед яких умови, {{Glossary("Loop", "цикли")}} та {{Glossary("Fu
```suggestion
Типовий сценарій мовами {{glossary("JavaScript")}} або {{glossary("PHP")}} (чи подібними) містить чимало контрольних структур, серед яких умови, {{Glossary("Loop", "цикли")}} та {{Glossary("Function", "функції")}}. Також якісь частини сценарію можуть виконуватися, коли трапляється якась {{Glossary("Event", "подія")}}.
```

2024-09-10 07:39 UTC, alinkedd commented on files/uk/glossary/control_flow/index.md
> +Наприклад, уривок вище може перебувати всередині функції, що запускається, коли користувач клацає в формі кнопку **Надіслати**. Ця функція також може містити цикл, який ітерує по всіх полях у формі,
```suggestion
Наприклад, уривок вище може перебувати всередині функції, що запускається, коли користувач клацає у формі кнопку **Надіслати**. Ця функція також може містити цикл, який ітерує через всі поля у формі, перевіряючи кожне по черзі. Коли знову поглянути на код у частинах `if` та `else`, то лінії `promptUser` і `submitForm` також можуть викликати інші функції сценарію. Як бачимо, контрольні структури можуть утворювати складний спосіб плину обробки, застосовуючи лишень кілька ліній коду.
```
так рядків коду чи ліній коду? :)
бо якщо рядків, то на початку треба рядків файла, а не ліній файла

2024-09-10 07:39 UTC, alinkedd commented on files/uk/glossary/control_flow/index.md
> +**Контрольний плин** – це порядок, в якому комп'ютер виконує інструкції в сценарії.
```suggestion
**Контрольний плин** (control flow) – це порядок, в якому комп'ютер виконує інструкції в сценарії.
```

2024-09-10 07:39 UTC, alinkedd commented on files/uk/glossary/control_flow/index.md
> +- [Потік керування](https://uk.wikipedia.org/wiki/%D0%9F%D0%BE%D1%82%D1%96%D0%BA_%D0%BA%D0%B5%D1%80%D1%83%D0%B2%D0%B0%D0%BD%D0%BD%D1%8F) на Вікіпедії
```suggestion
- [Контрольний плин (або потік керування)](https://uk.wikipedia.org/wiki/%D0%9F%D0%BE%D1%82%D1%96%D0%BA_%D0%BA%D0%B5%D1%80%D1%83%D0%B2%D0%B0%D0%BD%D0%BD%D1%8F) на Вікіпедії
```

2024-09-11 06:43 UTC, undead404 commented on files/uk/glossary/control_flow/index.md
> +Наприклад, уявімо сценарій, що використовується для валідування користувацьких даних з форми на вебсторінці. Цей сценарій надсилає валідовані дані, проте якщо користувач, скажімо, залишить обов'язков
Якого саме словника?..

2024-10-11 16:45 UTC, alinkedd approved these changes

2024-10-11 17:45 UTC, merged