update(JS): web/javascript/reference
webdoky/content pull request #3355
Opened 2024-09-04 06:06 UTC by undead404

2024-09-04 09:17 UTC, alinkedd requested changes

2024-09-04 09:17 UTC, alinkedd commented on files/uk/web/javascript/reference/index.md
> +- [Твердження озирання: `(?<=...)`, `(?<!...)`](/uk/docs/Web/JavaScript/Reference/Regular_expressions/Lookbehind_assertion)
Мені дуже подобаються ці "живі" переклади, набагато більше ніж [скальковані з російської](https://uk.wikipedia.org/wiki/%D0%A0%D0%B5%D0%B3%D1%83%D0%BB%D1%8F%D1%80%D0%BD%D0%B8%D0%B9_%D0%B2%D0%B8%D1%80%D0%B0%D0%B7#%D0%9F%D0%B5%D1%80%D0%B5%D0%B3%D0%BB%D1%8F%D0%B4_%D1%83%D0%BF%D0%B5%D1%80%D0%B5%D0%B4_%D1%82%D0%B0_%D0%BD%D0%B0%D0%B7%D0%B0%D0%B4) чи випереджальні/попереджувальні, але треба якось із чатом обговорити

P.S. і як тоді буде **positive/negative** lookahead/lookbehind assertion https://en.wikipedia.org/wiki/Regular_expression#Assertions?

2024-09-04 09:17 UTC, alinkedd commented on files/uk/web/javascript/reference/index.md
> +- [Твердження про межу вихідної послідовності: `^`, `$`](/uk/docs/Web/JavaScript/Reference/Regular_expressions/Input_boundary_assertion)
Довгувато якось. Є варіанти, як скоротити переклад для input?

2024-09-05 08:42 UTC, alinkedd commented on files/uk/web/javascript/reference/index.md
> +- [Буквальні символи: `a`, `b`](/uk/docs/Web/JavaScript/Reference/Regular_expressions/Literal_character)
але тут це і є літерали https://en.wikipedia.org/wiki/String_literal

2024-09-05 08:46 UTC, alinkedd commented on files/uk/web/javascript/reference/index.md
> +- [Джокер: `.`](/uk/docs/Web/JavaScript/Reference/Regular_expressions/Wildcard)
Запитала у чаті

2024-09-05 08:46 UTC, alinkedd commented on files/uk/web/javascript/reference/index.md
> +- [Квантори: `*`, `+`, `?`, `{n}`, `{n,}`, `{n,m}`](/uk/docs/Web/JavaScript/Reference/Regular_expressions/Quantifier)
```suggestion
- [Квантифікатори: `*`, `+`, `?`, `{n}`, `{n,}`, `{n,m}`](/uk/docs/Web/JavaScript/Reference/Regular_expressions/Quantifier)
```

2024-09-05 08:54 UTC, alinkedd commented on files/uk/web/javascript/reference/index.md
> +- [Твердження про межу вихідної послідовності: `^`, `$`](/uk/docs/Web/JavaScript/Reference/Regular_expressions/Input_boundary_assertion)
най буде ввід, якраз для бокової секції гарно

2024-09-05 08:56 UTC, alinkedd commented on files/uk/web/javascript/reference/index.md
> +- [Буквальні символи: `a`, `b`](/uk/docs/Web/JavaScript/Reference/Regular_expressions/Literal_character)
```suggestion
- [Літеральні символи: `a`, `b`](/uk/docs/Web/JavaScript/Reference/Regular_expressions/Literal_character)
```
https://en.wikipedia.org/wiki/Character_literal

2024-09-05 11:30 UTC, undead404 commented on files/uk/web/javascript/reference/index.md
> +- [Буквальні символи: `a`, `b`](/uk/docs/Web/JavaScript/Reference/Regular_expressions/Literal_character)
Там регулярні вирази ніяк не згадуються. До того ж регулярні вирази – не мова програмування.
Давай лишимо як є

2024-09-07 06:03 UTC, alinkedd commented on files/uk/web/javascript/reference/index.md
> +- [Твердження озирання: `(?<=...)`, `(?<!...)`](/uk/docs/Web/JavaScript/Reference/Regular_expressions/Lookbehind_assertion)
#1290

2024-09-07 06:06 UTC, alinkedd commented on files/uk/web/javascript/reference/index.md
> +- [Джокер: `.`](/uk/docs/Web/JavaScript/Reference/Regular_expressions/Wildcard)
#3371

2024-09-07 06:06 UTC, alinkedd approved these changes

2024-09-07 06:22 UTC, merged