update(CSS): web/css/@media
webdoky/content pull request #3474
Opened 2024-10-28 14:11 UTC by undead404

Оригінальний вміст: ["@media"@MDN](https://developer.mozilla.org/en-us/docs/Web/CSS/@media), [сирці "@media"@GitHub](https://github.com/mdn/content/blob/main/files/en-us/web/css/@media/index.md)

Нові зміни:
- [@media: add name of data types (#36171)](https://github.com/mdn/content/commit/b6752fdac6d0418f8ad6e074c4c6b94c69c7ec38)
- [Synchronize with BCD v5.5.51 (#35730)](https://github.com/mdn/content/commit/06b418a190b8e4a46682ab706d14984e7db34862)

2024-10-28 21:30 UTC, alinkedd requested changes

2024-10-28 21:30 UTC, alinkedd commented on files/uk/web/css/@media/index.md
> +_`<media feature>`_ описує конкретну характеристику {{glossary("User agent", "користувацького агента")}}, пристрою виведення чи оточення.
```suggestion
_`<media feature>`_ описує конкретні характеристики {{glossary("User agent", "користувацького агента")}}, пристрою виведення чи оточення.
```

2024-10-28 21:30 UTC, alinkedd commented on files/uk/web/css/@media/index.md
> +  - : Співвідношення ширини до висоти пристрою виведення. Нерекомендований від Медіазапитів рівня 4.
```suggestion
  - : Співвідношення ширини до висоти пристрою виведення. Застарілий у Медіазапитах рівня 4.
```
Deprecated навряд рекомендований

2024-10-28 21:30 UTC, alinkedd commented on files/uk/web/css/@media/index.md
> +  - : Висота поверхні візуалізації пристрою виведення. Нерекомендований від Медіазапитів рівня 4.
```suggestion
  - : Висота поверхні візуалізації пристрою виведення. Застарілий у Медіазапитах рівня 4.
```
same

2024-10-29 07:39 UTC, undead404 commented on files/uk/web/css/@media/index.md
> +  - : Співвідношення ширини до висоти пристрою виведення. Нерекомендований від Медіазапитів рівня 4.
У нас заведено перекладати саме так. Застарілий це obsolete

2024-10-30 16:06 UTC, alinkedd approved these changes

2024-10-30 18:27 UTC, merged