update(HTML): web/html/element/audio
webdoky/content pull request #3490
Opened 2024-10-28 14:54 UTC by undead404

2024-10-28 21:03 UTC, alinkedd requested changes

2024-10-28 21:03 UTC, alinkedd commented on files/uk/web/html/element/audio/index.md
> +Джерелом аудіо може бути заданий будь-який валідний [URL](/uk/docs/Web/URI), наприклад, URL HTTP(S) і [URL даних](/uk/docs/Web/URI/Schemes/data). При використанні URL HTTP(S) слід мати на увазі, що л
```suggestion
Джерелом аудіо може бути заданий будь-який валідний [URL](/uk/docs/Web/URI), наприклад, URL HTTP(S) і [URL даних](/uk/docs/Web/URI/Schemes/data). Використовуючи URL HTTP(S), слід пам'ятати, що логіка кешування в браузері впливатиме на те, наскільки часто файл буде запитаний із сервера. URL даних вбудовують дані аудіо безпосередньо в HTML, що може бути корисно для невеликих аудіофайлів, але не рекомендується для більших файлів, адже це збільшує розмір файла HTML.
```

2024-10-29 07:30 UTC, undead404 commented on files/uk/web/html/element/audio/index.md
> +Джерелом аудіо може бути заданий будь-який валідний [URL](/uk/docs/Web/URI), наприклад, URL HTTP(S) і [URL даних](/uk/docs/Web/URI/Schemes/data). При використанні URL HTTP(S) слід мати на увазі, що л
```suggestion
Джерелом аудіо може бути заданий будь-який валідний [URL](/uk/docs/Web/URI), наприклад, URL HTTP(S) і [URL даних](/uk/docs/Web/URI/Schemes/data). Використовуючи URL HTTP(S), слід пам'ятати, що логіка кешування в браузері впливатиме на те, наскільки часто файл буде запитаний із сервера. URL даних вбудовують дані аудіо безпосередньо в HTML, що може бути корисно для невеликих аудіофайлів, але не рекомендується для більших файлів, адже це збільшує розмір файлу HTML.
```

2024-10-30 16:11 UTC, alinkedd approved these changes

2024-10-30 18:27 UTC, merged