translation(HTML): web/html/element/input/date/index.md
webdoky/content pull request #351
Opened 2022-06-17 15:58 UTC by undead404

Original content: https://developer.mozilla.org/en-US/docs/Web/HTML/Element/Input/date

2022-06-23 20:49 UTC, AdriandeCita commented on files/uk/web/html/element/input/date/index.md
> +Значення результату включає рік, місяць та день, але _не_ час. Типи полів введення {{HTMLElement("input/time", "time")}} та {{HTMLElement("input/datetime-local", "datetime-local")}} підтримують введе
тут або кому треба, або вжити щось таке для підкреслення відмінності одного від іншого
```suggestion
Значення результату включає рік, місяць та день, але _не_ час. Типи полів введення {{HTMLElement("input/time", "time")}} та {{HTMLElement("input/datetime-local", "datetime-local")}} підтримують введення часу чи дати разом з часом, відповідно.
```

2022-06-23 20:55 UTC, AdriandeCita commented on files/uk/web/html/element/input/date/index.md
> +Цей HTML надсилає введену дату за ключем `bday` на `https://example.com` — в результаті URL буде виду `https://example.com/?bday=1955-06-08`.
```suggestion
Цей HTML надсилає введену дату за ключем `bday` на `https://example.com` — в результаті URL стане виду `https://example.com/?bday=1955-06-08`.
```

2022-06-23 21:05 UTC, AdriandeCita commented on files/uk/web/html/element/input/date/index.md
> +// визначити змінних
```suggestion
// означення змінних
```

2022-06-23 21:06 UTC, AdriandeCita commented on files/uk/web/html/element/input/date/index.md
> +// перевірити, чи відступає поле дати до текстового, чи ні
Додам для зв'язності з попереднім коментарем
```suggestion
// перевірити, чи відступає поле дати до запасного текстового варіанту, чи ні
```

2022-06-23 21:07 UTC, AdriandeCita commented on files/uk/web/html/element/input/date/index.md
> +  // видалити поточний набір елементів <option> із
```suggestion
  // видалити поточний набір елементів <option> із меню
```

2022-06-23 21:08 UTC, AdriandeCita commented on files/uk/web/html/element/input/date/index.md
> +  // <select> дня, готуючи до встановлення нового набору
```suggestion
  // <select> вибору дня, готуючи до встановлення нового набору
```

2022-06-23 21:09 UTC, AdriandeCita commented on files/uk/web/html/element/input/date/index.md
> +  // Зробити цей рік, а також 100 років перед ним – доступними в <select> року
```suggestion
  // Зробити цей рік, а також 100 років перед ним – доступними в меню <select> вибору року
```

2022-06-23 21:16 UTC, AdriandeCita commented on files/uk/web/html/element/input/date/index.md
> +{{EmbedLiveSample('Value', 600, 40)}}
FYI оці блоки отримують на вхід айді елемента - контейнера з кодом, - або айді заголовка розділу, в якому є декілька блоків різного коду. Потім там відбувається трохи магії з АСТ, але суть в тому, що цюди йде або айді контейнера (зазвичай це одразу видно в тексті статті - згадай текст html/input), або якір заголовка в нижньому регістрі
```suggestion
{{EmbedLiveSample('znachennia', 600, 40)}}
```

2022-06-23 21:17 UTC, AdriandeCita commented on files/uk/web/html/element/input/date/index.md
> +{{EmbedLiveSample('Basic_uses_of_date', 600, 40)}}
```suggestion
{{EmbedLiveSample('bazove-vykorystannia-poliv-daty', 600, 40)}}
```

2022-06-23 21:17 UTC, AdriandeCita commented on files/uk/web/html/element/input/date/index.md
> +{{EmbedLiveSample('Validation', 600, 100)}}
```suggestion
{{EmbedLiveSample('validatsiia', 600, 100)}}
```

2022-06-23 21:18 UTC, AdriandeCita commented on files/uk/web/html/element/input/date/index.md
> +{{EmbedLiveSample('Handling_browser_support', 600, 100)}}
```suggestion
{{EmbedLiveSample('povodzhennia-z-pidtrymkoiu-brauzeramy', 600, 100)}}
```

2022-06-23 21:18 UTC, AdriandeCita commented on files/uk/web/html/element/input/date/index.md
> +{{EmbedLiveSample('Examples', 600, 100)}}
```suggestion
{{EmbedLiveSample('pryklady', 600, 100)}}
```

2022-06-24 09:45 UTC, AdriandeCita requested changes
per comments

2022-06-26 17:28 UTC, undead404 commented on files/uk/web/html/element/input/date/index.md
> +Значення результату включає рік, місяць та день, але _не_ час. Типи полів введення {{HTMLElement("input/time", "time")}} та {{HTMLElement("input/datetime-local", "datetime-local")}} підтримують введе
Я не згодний, тут і-і

2022-06-26 17:29 UTC, undead404 commented on files/uk/web/html/element/input/date/index.md
> +// визначити змінних
Тут і далі всюди саме інфінітив, може, хай буде як є?

2022-06-26 21:28 UTC, AdriandeCita commented on files/uk/web/html/element/input/date/index.md
> +Значення результату включає рік, місяць та день, але _не_ час. Типи полів введення {{HTMLElement("input/time", "time")}} та {{HTMLElement("input/datetime-local", "datetime-local")}} підтримують введе
ок, тоді давай якось інакше проставимо акценти, бо зараз не очевидно, що саме мається на увазі: чи "...часу та дати, разом з часом..." (що звучить як нісенітниця), чи "...часу, та дати разом з часом..." (теж непросто, але з урахуванням досвіду роботи з вебом я можу припустити, що це саме бажаний варіант)

2022-06-26 21:29 UTC, AdriandeCita commented on files/uk/web/html/element/input/date/index.md
> +// визначити змінних
Аби узгоджено було
```suggestion
// визначити змінні
```

2022-06-27 11:03 UTC, AdriandeCita commented on files/uk/web/html/element/input/date/index.md
> +Значення результату включає рік, місяць та день, але _не_ час. Типи полів введення {{HTMLElement("input/time", "time")}} та {{HTMLElement("input/datetime-local", "datetime-local")}} підтримують введе
Норм! :+1:

2022-06-27 11:11 UTC, AdriandeCita approved these changes

2022-06-27 11:12 UTC, merged