update(CSS): web/css/css_pseudo-elements
webdoky/content pull request #3541
Opened 2024-11-04 14:41 UTC by undead404

2024-11-15 16:40 UTC, alinkedd requested changes

2024-11-15 16:40 UTC, alinkedd commented on files/uk/web/css/css_pseudo-elements/index.md
> +- Модуль [Переходів представлення CSS](/uk/docs/Web/CSS/CSS_view_transitions)
чому представлення? view тут область перегляду

2024-11-15 17:24 UTC, undead404 commented on files/uk/web/css/css_pseudo-elements/index.md
> +- Модуль [Переходів представлення CSS](/uk/docs/Web/CSS/CSS_view_transitions)
Ні, це дещо інше https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_view_transitions

2024-11-15 17:39 UTC, undead404 commented on files/uk/web/css/css_pseudo-elements/index.md
> +- Модуль [Переходів представлення CSS](/uk/docs/Web/CSS/CSS_view_transitions)
То як ми це назвемо? "Переходи перегляду"?

2024-11-15 18:00 UTC, alinkedd commented on files/uk/web/css/css_pseudo-elements/index.md
> +- Модуль [Переходів представлення CSS](/uk/docs/Web/CSS/CSS_view_transitions)
Переходи між елементами перегляду?

як перекласти просто view?
viewport - область перегляду, я б із цим не змішувала, але треба недалеко йти від цього. зазвичай, ці переходи будуть між різними сторінками навігаційно, але їх можна робити і на одній сторінці, тому я б view як елемент перегляду перекладала

я розумію, що ти відштовхувався, можливо, від MVC - вигляд/представлення, але я б їх тут не тулила

давай у чат

2024-12-24 17:12 UTC, AdriandeCita commented on files/uk/web/css/css_pseudo-elements/index.md
> +- Модуль [Переходів представлення CSS](/uk/docs/Web/CSS/CSS_view_transitions)
```suggestion
- Модуль [Переходів виглядів CSS](/uk/docs/Web/CSS/CSS_view_transitions)
```

2024-12-25 19:51 UTC, AdriandeCita approved these changes

2024-12-25 20:46 UTC, merged