update(CSS): web/css/css_text
webdoky/content pull request #3555
Opened 2024-11-06 07:32 UTC by undead404

2024-11-15 18:29 UTC, alinkedd requested changes

2024-11-15 18:29 UTC, alinkedd commented on files/uk/web/css/css_text/index.md
> +- {{cssxref("overflow-wrap")}} (вкупі з псевдонімом `word-wrap`)
```suggestion
- {{cssxref("overflow-wrap")}} (вкупі із псевдонімом `word-wrap`)
```

2024-11-15 18:29 UTC, alinkedd commented on files/uk/web/css/css_text/index.md
> +- [Переведення на новий рядок і розривання тексту](/uk/docs/Web/CSS/CSS_text/Wrapping_breaking_text)
а не перенесення на новий рядок?

2024-11-15 18:29 UTC, alinkedd commented on files/uk/web/css/css_text/index.md
> +- {{cssxref("overflow-wrap")}} (вкупі з псевдонімом `word-wrap`)
```suggestion
- {{cssxref("overflow-wrap")}} (вкупі із псевдонімом `word-wrap`)
```

2024-11-15 18:29 UTC, alinkedd commented on files/uk/web/css/css_text/index.md
> +  - : Посібник з різними способами, в які можна керувати в CSS текстом, що не вміщається.
```suggestion
  - : Посібник із різними способами керування в CSS текстом, що не вміщається.
```

2024-11-15 18:29 UTC, alinkedd commented on files/uk/web/css/css_text/index.md
> +  - : Посібник з різними способами, в які можна керувати в CSS текстом, що не вміщається.
і чому CSS overflow - переповнення CSS, а overflowing text - текст, що не вміщається?

2024-11-15 21:09 UTC, undead404 commented on files/uk/web/css/css_text/index.md
> +- [Переведення на новий рядок і розривання тексту](/uk/docs/Web/CSS/CSS_text/Wrapping_breaking_text)
Так, треба узгодити

2024-12-05 16:15 UTC, undead404 commented on files/uk/web/css/css_text/index.md
> +- [Переведення на новий рядок і розривання тексту](/uk/docs/Web/CSS/CSS_text/Wrapping_breaking_text)
```suggestion
- [Перенесення на новий рядок і розривання тексту](/uk/docs/Web/CSS/CSS_text/Wrapping_breaking_text)
```

2024-12-05 16:15 UTC, undead404 commented on files/uk/web/css/css_text/index.md
> +  - : Посібник з різними способами, в які можна керувати в CSS текстом, що не вміщається.
```suggestion
  - : Посібник із різними способами керування переповненим текстом у CSS.
```

2024-12-24 16:54 UTC, AdriandeCita approved these changes

2024-12-24 22:29 UTC, merged