update(JS): web/javascript/reference/lexical_grammar
webdoky/content pull request #3569
Opened 2024-11-12 14:11 UTC by undead404

2024-11-15 17:31 UTC, alinkedd requested changes

2024-11-15 17:31 UTC, alinkedd commented on files/uk/web/javascript/reference/lexical_grammar/index.md
> +- Перший символ може бути будь-яким символом категорії [ID_Start](https://util.unicode.org/UnicodeJsps/list-unicodeset.jsp?a=%5Cp%7BID_Start%7D), плюс `_` і `$`.
тут плюс - це "разом з" чи "а також"?

2024-11-15 17:31 UTC, alinkedd commented on files/uk/web/javascript/reference/lexical_grammar/index.md
> +- Після першого символу можна використовувати всі символи категорії [ID_Continue](https://util.unicode.org/UnicodeJsps/list-unicodeset.jsp?a=%5Cp%7BID_Continue%7D) плюс U+200C (ZWNJ) і U+200D (ZWJ).
тут те саме: а якщо це перелік, то я б використовувала "а також"

2024-11-15 18:05 UTC, alinkedd commented on files/uk/web/javascript/reference/lexical_grammar/index.md
> +- Перший символ може бути будь-яким символом категорії [ID_Start](https://util.unicode.org/UnicodeJsps/list-unicodeset.jsp?a=%5Cp%7BID_Start%7D), плюс `_` і `$`.
я просто хочу явно мовно вказати, чи тут перелік, чи тут конкатенація

2024-11-15 20:59 UTC, undead404 commented on files/uk/web/javascript/reference/lexical_grammar/index.md
> +- Перший символ може бути будь-яким символом категорії [ID_Start](https://util.unicode.org/UnicodeJsps/list-unicodeset.jsp?a=%5Cp%7BID_Start%7D), плюс `_` і `$`.
Навіщо домудрувати те, чого нема в оригіналі? Виправимо, коли вони виправлять. А вони виправлять, рано чи пізно

2024-11-29 14:25 UTC, alinkedd requested changes

2024-11-29 14:25 UTC, alinkedd commented on files/uk/web/javascript/reference/lexical_grammar/index.md
> +- Перший символ може бути будь-яким символом категорії [ID_Start](https://util.unicode.org/UnicodeJsps/list-unicodeset.jsp?a=%5Cp%7BID_Start%7D), плюс `_` і `$`.
```suggestion
- Перший символ може бути будь-яким символом категорії [ID_Start](https://util.unicode.org/UnicodeJsps/list-unicodeset.jsp?a=%5Cp%7BID_Start%7D) плюс `_` і `$`.
```

2024-12-12 09:32 UTC, AdriandeCita approved these changes

2024-12-12 10:27 UTC, merged