update(HTML): web/html/element/input/password
webdoky/content pull request #3619
Opened 2024-11-17 08:42 UTC by undead404

2024-11-17 08:52 UTC, undead404 commented on files/uk/web/html/element/input/password/index.md
> +> Глобальний атрибут [`autocorrect`](/uk/docs/Web/HTML/Global_attributes/autocorrect) можна додати до полів паролю, проте доступне в ньому значення завжди буде `off`.
```suggestion
> Глобальний атрибут [`autocorrect`](/uk/docs/Web/HTML/Global_attributes/autocorrect) можна додати до полів пароля, проте доступне в ньому значення завжди буде `off`.
```

2024-11-28 18:02 UTC, alinkedd requested changes

2024-11-28 18:02 UTC, alinkedd commented on files/uk/web/html/element/input/password/index.md
> +На додачу до [глобальних атрибутів](/uk/docs/Web/HTML/Global_attributes) та атрибутів, що працюють на всіх елементах {{HTMLElement("input")}}, незалежно від їхніх типів, поля телефонних номерів підтр
```suggestion
На додачу до [глобальних атрибутів](/uk/docs/Web/HTML/Global_attributes) та атрибутів, що працюють на всіх елементах {{HTMLElement("input")}}, незалежно від їхніх типів, поля пароля підтримують наступні атрибути.
```

2024-11-29 14:22 UTC, alinkedd commented on files/uk/web/html/element/input/password/index.md
> +На додачу до [глобальних атрибутів](/uk/docs/Web/HTML/Global_attributes) та атрибутів, що працюють на всіх елементах {{HTMLElement("input")}}, незалежно від їхніх типів, поля телефонних номерів підтр
це забув

2024-12-18 16:16 UTC, alinkedd requested changes
забув оновити 235 рядок
https://github.com/mdn/content/commit/f10015d1752d5668d8fe0de29f9d9807de475d58#diff-caf6d80f1109a1dcb61dfdc0b86b162a2f98cdbecd5154e34fb21cc0e04197d2L235

2024-12-19 21:22 UTC, alinkedd approved these changes

2024-12-24 16:32 UTC, AdriandeCita approved these changes

2024-12-24 22:26 UTC, merged