update(HTML): web/html/element/area
webdoky/content pull request #3633
Opened 2024-11-18 09:41 UTC by undead404

2024-11-28 17:50 UTC, alinkedd requested changes

2024-11-28 17:50 UTC, alinkedd commented on files/uk/web/html/element/area/index.md
> +  - : Цей атрибут, якщо присутній, вказує на те, що заданий ресурс призначений для стягнення, а не відображення в браузері.
```suggestion
  - : Цей атрибут, якщо присутній, вказує на те, що заданий ресурс призначений для завантаження, а не відображення в браузері.
```

2024-11-28 18:29 UTC, undead404 commented on files/uk/web/html/element/area/index.md
> +  - : Цей атрибут, якщо присутній, вказує на те, що заданий ресурс призначений для стягнення, а не відображення в браузері.
По-моєму, "стягнення" краще, бо "завантаження" – надто загальне поняття

2024-11-28 18:32 UTC, alinkedd commented on files/uk/web/html/element/area/index.md
> +  - : Цей атрибут, якщо присутній, вказує на те, що заданий ресурс призначений для стягнення, а не відображення в браузері.
але там прямо написано download. коли я читала зі стягненням, то не зрозуміла, що то

2024-11-29 08:58 UTC, undead404 commented on files/uk/web/html/element/area/index.md
> +  - : Цей атрибут, якщо присутній, вказує на те, що заданий ресурс призначений для стягнення, а не відображення в браузері.
Але ж усі приєднані ресурси призначені для завантаження, як слово "завантаження" допоможе?

2024-12-12 09:26 UTC, AdriandeCita commented on files/uk/web/html/element/area/index.md
> +  - : Цей атрибут, якщо присутній, вказує на те, що заданий ресурс призначений для стягнення, а не відображення в браузері.
"стягнення" має дуже конкретне значення в юридичній справі https://uk.wikipedia.org/wiki/%D0%A1%D1%82%D1%8F%D0%B3%D0%BD%D0%B5%D0%BD%D0%BD%D1%8F_(%D0%B7%D0%BD%D0%B0%D1%87%D0%B5%D0%BD%D0%BD%D1%8F)

2024-12-12 10:25 UTC, undead404 commented on files/uk/web/html/element/area/index.md
> +  - : Цей атрибут, якщо присутній, вказує на те, що заданий ресурс призначений для стягнення, а не відображення в браузері.
```suggestion
  - : Цей атрибут, якщо присутній, вказує на те, що заданий ресурс призначений для звантаження, а не відображення в браузері.
```
А як вам таке?

2024-12-23 16:33 UTC, alinkedd commented on files/uk/web/html/element/area/index.md
> +  - : Цей атрибут, якщо присутній, вказує на те, що заданий ресурс призначений для стягнення, а не відображення в браузері.
@undead404 просто завантаження, бум ласочка

2024-12-23 19:02 UTC, merged