update(JS): web/javascript/guide/regular_expressions
webdoky/content pull request #3708
Opened 2024-12-20 09:17 UTC by undead404

2024-12-20 09:26 UTC, undead404 commented on files/uk/web/javascript/guide/regular_expressions/index.md
> +Цей розділ описує регулярні вирази у JavaScript. Він пропонує стислий огляд кожного елемента синтаксису. Докладне пояснення семантики кожного з ниж читайте довідник [регулярних виразів](/uk/docs/Web/
```suggestion
Цей розділ описує регулярні вирази у JavaScript. Він пропонує стислий огляд кожного елемента синтаксису. Докладне пояснення семантики кожного з них читайте довідник [регулярних виразів](/uk/docs/Web/JavaScript/Reference/Regular_expressions).
```

2024-12-24 15:27 UTC, AdriandeCita commented on files/uk/web/javascript/guide/regular_expressions/index.md
> +Цей розділ описує регулярні вирази у JavaScript. Він пропонує стислий огляд кожного елемента синтаксису. Докладне пояснення семантики кожного з них читайте довідник [регулярних виразів](/uk/docs/Web/
```suggestion
Цей розділ описує регулярні вирази у JavaScript. Він пропонує стислий огляд кожного елемента синтаксису. Докладне пояснення семантики кожного з них читайте в довіднику [регулярних виразів](/uk/docs/Web/JavaScript/Reference/Regular_expressions).
```

2024-12-24 15:28 UTC, AdriandeCita requested changes
per comment

2024-12-25 19:45 UTC, AdriandeCita approved these changes

2024-12-25 20:43 UTC, merged