translation(JS): /Web/JavaScript/Reference/Statements/for...of
webdoky/content pull request #399
Opened 2022-06-23 17:00 UTC by inperegelion

Original content: [for...of](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/for...of#syntax)

2022-06-23 18:31 UTC, undead404 requested changes

2022-06-23 18:31 UTC, undead404 commented on files/uk/web/javascript/reference/statements/for...of/index.md
> +[ітеративні обʼєкти](/en-US/docs/Web/JavaScript/Reference/Iteration_protocols#the_iterable_protocol),
```suggestion
[ітерованих обʼєктів](/uk/docs/Web/JavaScript/Reference/Iteration_protocols#protokol-iteruvannia),
```

Якорі ми перекладаємо, навіть в тих статтях, котрих іще немає – треба перекласти приблизно, прогнати через паспортний трансліт 2010 року, а потім зробити slug

2022-06-23 18:31 UTC, undead404 commented on files/uk/web/javascript/reference/statements/for...of/index.md
> +масивоподібні обʼєкти (на кшталт, {{jsxref("Functions/arguments", "arguments")}}
```suggestion
масивоподібні обʼєкти (наприклад, {{jsxref("Functions/arguments", "arguments")}}
```
Сам люблю це слово, але в багатьох випадках це зайвий германізм

2022-06-23 18:31 UTC, undead404 commented on files/uk/web/javascript/reference/statements/for...of/index.md
> +{{jsxref("Set")}}, а також ітеративні обʼєкти, які користувач створив сам. Ця конструкція викликає описаний набір інструкцій, які будуть виконані для значення для кожної властивості обʼєкту.
```suggestion
{{jsxref("Set")}}, а також ітеровані обʼєкти, які користувач створив сам. Ця конструкція викликає описаний набір інструкцій, які будуть виконані для значення кожної властивості обʼєкту.
```

2022-06-23 18:31 UTC, undead404 commented on files/uk/web/javascript/reference/statements/for...of/index.md
> +`
```suggestion
```

2022-06-23 18:31 UTC, undead404 commented on files/uk/web/javascript/reference/statements/for...of/index.md
> +Ви можете використовувати також {{jsxref("Statements/let", "let")}} замість {{jsxref("Statements/const",
```suggestion
Також можна використати {{jsxref("Statements/let", "let")}} замість {{jsxref("Statements/const",
```
Особових речень не всюди виходить уникнути, але там, де це легко - краще так і робити

2022-06-23 18:31 UTC, undead404 commented on files/uk/web/javascript/reference/statements/for...of/index.md
> +### Ітерування по `Set`
```suggestion
### Обхід `Set`
```

2022-06-23 18:31 UTC, undead404 commented on files/uk/web/javascript/reference/statements/for...of/index.md
> +### Ітерування по обʼєкту `arguments`
```suggestion
### Обхід обʼєкту `arguments`
```

2022-06-23 18:31 UTC, undead404 commented on files/uk/web/javascript/reference/statements/for...of/index.md
> +Ви можете ітерувати по обʼєкту {{jsxref("Functions/arguments", "arguments")}} щоб обстежити усі параметри передані до JavaScript функції:
```suggestion
Щоб дослідити усі параметри, передані до JavaScript функції, можна виконати обхід об‘єкту {{jsxref("Functions/arguments", "arguments")}}:
```
"обстежувати" звучить усе ж більш медично

2022-06-23 18:31 UTC, undead404 commented on files/uk/web/javascript/reference/statements/for...of/index.md
> +Ітерування по DOM колекціям, таким як [`NodeList`](/en-US/docs/Web/API/NodeList): подальший приклад додає клас `read` до параграфів, які є прямими спадкоємцями елементу `article`:
```suggestion
Обхід DOM-колекцій, наприклад, [`NodeList`](/uk/docs/Web/API/NodeList): наступний приклад додає клас `read` до параграфів, які є прямими спадкоємцями елементу `article`:
```

2022-06-23 18:31 UTC, undead404 commented on files/uk/web/javascript/reference/statements/for...of/index.md
> +// Зазначте: Це буде працювати виключно на платформах, які мають реалізацію для
```suggestion
// Примітка: Це буде працювати виключно на тих платформах, які мають реалізацію 
```

"Note" ми всюди перекладаємо як "Примітка", а "Warning" – як "Застереження"

2022-06-23 18:31 UTC, undead404 commented on files/uk/web/javascript/reference/statements/for...of/index.md
> +У `for...of` циклах, різке переривання ітерації може бути спричинене операторами `break`, `throw` чи `return`. У таких випадках ітератор буде завершено.
```suggestion
У циклах `for...of` операторами `break`, `throw` та `return` може бути спричинено різке переривання ітерації. У таких випадках ітератор буде завершено.
```

2022-06-23 18:31 UTC, undead404 commented on files/uk/web/javascript/reference/statements/for...of/index.md
> +  break; // завершує ітератор, продовжується виконання коду поза конструкцією циклу
```suggestion
  break; // завершує ітератор, виконання коду продовжується поза циклом
```

2022-06-23 18:31 UTC, undead404 commented on files/uk/web/javascript/reference/statements/for...of/index.md
> +### Ітерування по генераторах
```suggestion
### Обхід генераторів
```

2022-06-23 18:31 UTC, undead404 commented on files/uk/web/javascript/reference/statements/for...of/index.md
> +Основна різниця в тому "що" вони ітерують.
```suggestion
Основна різниця в тому, що саме вони обходять.
```

2022-06-23 18:31 UTC, undead404 commented on files/uk/web/javascript/reference/statements/for...of/index.md
> +{{jsxref("Statements/for...in", "for...in")}} ітерує по [зліченних властивостях](/en-US/docs/Web/JavaScript/Enumerability_and_ownership_of_properties) обʼєкта.
```suggestion
{{jsxref("Statements/for...in", "for...in")}} виконує обхід [перелічуваних властивостей](/uk/docs/Web/JavaScript/Enumerability_and_ownership_of_properties) обʼєкта.
```

2022-06-23 18:31 UTC, undead404 commented on files/uk/web/javascript/reference/statements/for...of/index.md
> +`for...of` ітерує значення, які [ітеративний обʼєкт](/en-US/docs/Web/JavaScript/Guide/Iterators_and_Generators#iterables) визначає як такі які можна ітерувати.
```suggestion
`for...of` обходить значення, які [ітеративний обʼєкт](/en-US/docs/Web/JavaScript/Guide/Iterators_and_Generators#iterables) визначає як такі, котрі слід обходити.
```

2022-06-23 18:31 UTC, undead404 commented on files/uk/web/javascript/reference/statements/for...of/index.md
> +Цей цикл виведе лише [зліченні властивості](/en-US/docs/Web/JavaScript/Enumerability_and_ownership_of_properties) обʼєкта `iterable`. Він не виведе масив **елементи** `3`, `5`, `7` чи
```suggestion
Цей цикл виведе лише [перелічувані властивості](/uk/docs/Web/JavaScript/Enumerability_and_ownership_of_properties) обʼєкта `iterable`. Він не виведе **елементи** масиву: `3`, `5`, `7` чи
```

2022-06-23 18:31 UTC, undead404 commented on files/uk/web/javascript/reference/statements/for...of/index.md
> +`Агов`, адже вони **не є** зліченними властивостями, насправді вони не є властивостями взагалі, вони є **значеннями**. Код виведе масив **індексів** включаючи `arrCustom` і `objCustom`. Якщо ви не пе
```suggestion
`Агов`, адже вони **не є** зліченними властивостями; насправді вони не є властивостями взагалі, а лише **значеннями**. Код виведе масив **індексів**, включаючи `arrCustom` і `objCustom`. Якщо ви не певні, чому саме по цих властивостях відбувається ітерація, то зверніть увагу на більш детальне пояснення у статті {{jsxref("Statements/for...in", "array iteration and for...in", "#Array_iteration_and_for...in")}}.
```
Тут наприкінці деяка неузгодженість між частинами складного речення.

2022-06-23 18:31 UTC, undead404 commented on files/uk/web/javascript/reference/statements/for...of/index.md
> +Цей цикл подібний до першого, але натомість використовує {{jsxref("Object.prototype.hasOwnProperty()", "hasOwnProperty()")}}, щоб перевірити чи зліченні властивості належать до власних властивостей о
```suggestion
Цей цикл подібний до першого, але натомість використовує {{jsxref("Object.prototype.hasOwnProperty()", "hasOwnProperty()")}}, щоб перевірити чи належать перелічувані властивості до власних властивостей обʼєкта, а не успадкованих. Якщо належать, то вивести властивість. Властивості `0`, `1`, `2` та `foo` виведено, адже вони є власними властивостями (**не успадкованими**). Властивості `arrCustom` і `objCustom` не виведено, адже вони **успадковані**.
```

2022-06-23 18:31 UTC, undead404 commented on files/uk/web/javascript/reference/statements/for...of/index.md
> +Цей цикл ітерує та виводить **значення**, які [ітеративний обʼєкт](/en-US/docs/Web/JavaScript/Guide/Iterators_and_Generators#iterables), визначає такими, що їх можна ітерувати, `iterable`. **Елементи
```suggestion
Цей цикл ітерує та виводить **значення**, які [ітерований обʼєкт](/uk/docs/Web/JavaScript/Guide/Iterators_and_Generators#iterovani-obiekty) визначає такими, що їх слід обходити. **Елементи**
```

2022-06-23 18:31 UTC, undead404 commented on files/uk/web/javascript/reference/statements/for...of/index.md
> +## Сумісність з браузерами
```suggestion
## Сумісність із браузерами
```

2022-06-24 08:48 UTC, AdriandeCita commented on files/uk/web/javascript/reference/statements/for...of/index.md
> +[ітеративні обʼєкти](/en-US/docs/Web/JavaScript/Reference/Iteration_protocols#the_iterable_protocol),
Я б сказав простіше: якщо у нас цільова сторінка вже перекладена - то краще взяти якір звідти. Якщо ні - то можна не надто заморочуватися, оскільки в перекладі воно потім може звучати інакше, і однаково доведеться оновлювати якорі.

А загалом на етапі генерації сторінок у нас виконується перевірка на актуальність якорів, тож проблемні посилання ми потім однаково відловимо

2022-06-24 08:57 UTC, AdriandeCita commented on files/uk/web/javascript/reference/statements/for...of/index.md
> +  - : На кожній ітерації значення різних властивостей будуть призначатися у `variable`. `variable` може бути оголошеним з використанням `const`, `let`, чи `var`.
Про майбутній час - просто теперішній звучить краще, а головне - лаконічніше. Мені здається, в математичній літературі теж частіше використовується теперішній час, але я не готовий під цим підписатись.

А що додам - варто додавати в тексті отакі ненав'язливі переклади ідентифікаторів, для зв'язності. Англійською текст виглядає зв'язним, бо назви ідентифікаторів також несуть семантику.
```suggestion
  - : На кожній ітерації значення різних властивостей присвоюються змінній `variable`. Ця `variable` може бути оголошеною з використанням `const`, `let`, чи `var`.
```

2022-06-24 08:59 UTC, AdriandeCita commented on files/uk/web/javascript/reference/statements/for...of/index.md
> +### Ітерування по `Array`
ну, настільки в стиль я зазвичай не заглиблююся)

2022-06-24 09:09 UTC, AdriandeCita commented on files/uk/web/javascript/reference/statements/for...of/index.md
> +Ітерування по DOM колекціям, таким як [`NodeList`](/en-US/docs/Web/API/NodeList): подальший приклад додає клас `read` до параграфів, які є прямими спадкоємцями елементу `article`:
так, до речі, локаль в посиланнях треба міняти з `en-US` на `uk`. І в крайньому разі це теж потім відловлюється на етапі перевірки посилань.

2022-06-24 09:24 UTC, AdriandeCita commented on files/uk/web/javascript/reference/statements/for...of/index.md
> +`Агов`, адже вони **не є** зліченними властивостями, насправді вони не є властивостями взагалі, вони є **значеннями**. Код виведе масив **індексів** включаючи `arrCustom` і `objCustom`. Якщо ви не пе
Загалом зліченні - це радше про "countable/uncountable", а enumerable - це про "перебрати кожного"

2022-06-24 11:07 UTC, inperegelion commented on files/uk/web/javascript/reference/statements/for...of/index.md
> +[ітеративні обʼєкти](/en-US/docs/Web/JavaScript/Reference/Iteration_protocols#the_iterable_protocol),
@AdriandeCita @undead404 , це означає, що в рамках цього ПРа якорі можна ігнорувати?

2022-06-24 12:23 UTC, AdriandeCita commented on files/uk/web/javascript/reference/statements/for...of/index.md
> +[ітеративні обʼєкти](/en-US/docs/Web/JavaScript/Reference/Iteration_protocols#the_iterable_protocol),
Якщо вони ведуть на неіснуючу сторінку - то в принципі так. Однаково проконтролювати їх ми не зможемо

2022-06-24 13:38 UTC, inperegelion commented on files/uk/web/javascript/reference/statements/for...of/index.md
> +[ітеративні обʼєкти](/en-US/docs/Web/JavaScript/Reference/Iteration_protocols#the_iterable_protocol),
Застосовую:
```suggestion
[ітерованих обʼєктів](/en-US/docs/Web/JavaScript/Reference/Iteration_protocols#the_iterable_protocol),
```

2022-06-24 13:39 UTC, inperegelion commented on files/uk/web/javascript/reference/statements/for...of/index.md
> +### Ітерування по `String`
```suggestion
### Обхід циклу по `String`
```

2022-06-24 13:39 UTC, inperegelion commented on files/uk/web/javascript/reference/statements/for...of/index.md
> +### Ітерування по `TypedArray`
```suggestion
### Обхід циклу по `TypedArray`
```

2022-06-24 13:40 UTC, inperegelion commented on files/uk/web/javascript/reference/statements/for...of/index.md
> +### Ітерування по `Map`
```suggestion
### Обхід циклу по `Map`
```

2022-06-24 13:44 UTC, inperegelion commented on files/uk/web/javascript/reference/statements/for...of/index.md
> +### Ітерування по `Set`
```suggestion
### Обхід циклу по `Set`
```

2022-06-24 13:44 UTC, inperegelion commented on files/uk/web/javascript/reference/statements/for...of/index.md
> +### Ітерування по обʼєкту `arguments`
```suggestion
### Обхід циклу по обʼєкту `arguments`
```

2022-06-24 13:46 UTC, inperegelion commented on files/uk/web/javascript/reference/statements/for...of/index.md
> +### Ітерування по DOM колекції
```suggestion
### Обхід циклу по DOM колекції
```

2022-06-24 13:49 UTC, inperegelion commented on files/uk/web/javascript/reference/statements/for...of/index.md
> +### Ітерування по генераторах
```suggestion
### Обхід циклу по генераторах
```

2022-06-24 13:51 UTC, inperegelion commented on files/uk/web/javascript/reference/statements/for...of/index.md
> +### Ітерування по інших ітеративних обʼєктах
```suggestion
### Обхід циклу по інших ітерованих об‘єктах
```

2022-06-24 14:12 UTC, inperegelion commented on files/uk/web/javascript/reference/statements/for...of/index.md
> +Ітерування по DOM колекціям, таким як [`NodeList`](/en-US/docs/Web/API/NodeList): подальший приклад додає клас `read` до параграфів, які є прямими спадкоємцями елементу `article`:
applied in the next commit

2022-06-24 20:19 UTC, AdriandeCita approved these changes

2022-06-24 20:20 UTC, merged