translation(JS): web/javascript/reference/global_objects/array/concat
webdoky/content pull request #413
Opened 2022-06-29 08:39 UTC by undead404

Original content: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/concat

2022-07-10 15:43 UTC, AdriandeCita commented on files/uk/web/javascript/reference/global_objects/array/concat/index.md
> +Метод `concat` створює новий масив, що складається з елементів об‘єкта, на котрому його викликали, після яких, по черзі для всіх аргументів, елементи аргументу (якщо аргумент є масивом) або сам аргум
Трохи громіздка конструкція, я без погляду на оригінал її не розпарсив. Також в кінці `аргументи-масиви` мені здалися зайвими... Там рекурсії не відбувається незалежно від того, чи масив вкладено в інший масив, чи просто в об'єкт із `Symbol.isConcatSpreadable` (чи будь-який інший об'єкт).
```suggestion
Метод `concat` створює новий масив, до якого входять спершу елементи об‘єкта, на котрому його викликали. Після нього до масиву додаються по черзі всі аргументи: або як окремі елементи аргумента (якщо аргумент є масивом), або безпосередньо сам аргумент (якщо він не є масивом). Рекурсії на вкладених в аргументи масивах не відбувається.
```

2022-07-10 15:47 UTC, AdriandeCita commented on files/uk/web/javascript/reference/global_objects/array/concat/index.md
> +- Посилання на об‘єкти (а не сам об‘єкт): `concat` копіює в новий масив посилання на об‘єкти. Як вихідний, так і новий масиви посилаються на одні об‘єкти. А отже – при змінах відповідного об‘єкта змі
```suggestion
- Посилання на об‘єкти (а не сам об‘єкт): `concat` копіює в новий масив посилання на об‘єкти. Як вихідний, так і новий масиви посилаються на одні об‘єкти. А отже – при змінах відповідного об‘єкта зміни будуть помітні як в новому, так у вихідному масиві. Це так само діє для масивів, які є елементами аргументів.
```

2022-07-10 15:49 UTC, AdriandeCita requested changes
Пара зауважень

2022-07-12 07:24 UTC, undead404 commented on files/uk/web/javascript/reference/global_objects/array/concat/index.md
> +- Посилання на об‘єкти (а не сам об‘єкт): `concat` копіює в новий масив посилання на об‘єкти. Як вихідний, так і новий масиви посилаються на одні об‘єкти. А отже – при змінах відповідного об‘єкта змі
Wat? У мене мова про передачу масиву як аргументу, а в тебе про що?

2022-07-15 17:50 UTC, merged