translation(JS): web/javascript/reference/global_objects/array/push
webdoky/content pull request #424
Opened 2022-07-07 10:09 UTC by Maksym1910

Original content: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/push

2022-07-07 16:29 UTC, undead404 requested changes
Наполегливо рекомендую переписати особові речення (ми написали, наша користь) інакше. Suggestions не дають мені зручно це зробити

2022-07-07 16:29 UTC, undead404 commented on files/uk/web/javascript/reference/global_objects/array/push/index.md
> +  - : Елемент(и), який потрібно додати у кінець масиву.
```suggestion
  - : Елемент(и), що потрібно додати у кінець масиву.
```
Аби покривало й однину, і множину

2022-07-07 16:29 UTC, undead404 commented on files/uk/web/javascript/reference/global_objects/array/push/index.md
> +`push` є навмисно загальним. Цей метод можна використовувати з
```suggestion
`push` навмисно є узагальненим. Цей метод можна використовувати з
```

2022-07-07 16:29 UTC, undead404 commented on files/uk/web/javascript/reference/global_objects/array/push/index.md
> +використовується індекс 0. Це включає в себе можливість відсутності `length`, у цьому випадку
```suggestion
використовується індекс 0. Це включає в себе можливість відсутності `length`; у цьому випадку
```

2022-07-07 16:29 UTC, undead404 commented on files/uk/web/javascript/reference/global_objects/array/push/index.md
> +Незважаючи на те, що {{jsxref("Global_Objects/String", "strings", "", 1)}} є нативними об'єктами,
```suggestion
Незважаючи на те, що {{jsxref("Global_Objects/String", "рядки", "", 1)}} є нативними об'єктами,
```

2022-07-07 16:29 UTC, undead404 commented on files/uk/web/javascript/reference/global_objects/array/push/index.md
> +Аналогічно для нативних {{jsxref("Functions/arguments", "arguments", "", 1)}}
```suggestion
Те саме стосується нативних 
```

2022-07-07 16:29 UTC, undead404 commented on files/uk/web/javascript/reference/global_objects/array/push/index.md
> +масивоподібних об’єктів.
```suggestion
масивоподібних об’єктів {{jsxref("Functions/arguments", "arguments", "", 1)}}.
```

2022-07-07 16:29 UTC, undead404 commented on files/uk/web/javascript/reference/global_objects/array/push/index.md
> +У цьому прикладі використовується {{jsxref("Operators/Spread_syntax", "spread syntax", "", "1")}},
```suggestion
У цьому прикладі для переміщення всіх елементів з другого масиву в перший
```

2022-07-07 16:29 UTC, undead404 commented on files/uk/web/javascript/reference/global_objects/array/push/index.md
> +щоб перемістити всі елементи з другого масиву в перший.
```suggestion
використовується {{jsxref("Operators/Spread_syntax", "синтаксис розгортання", "", "1")}}
```

2022-07-07 16:29 UTC, undead404 commented on files/uk/web/javascript/reference/global_objects/array/push/index.md
> +### Використання об’єкта у вигляді масиву
```suggestion
### Використання об’єкта у подібний до масиву спосіб
```

2022-07-07 16:29 UTC, undead404 commented on files/uk/web/javascript/reference/global_objects/array/push/index.md
> +Як згадувалося вище, `push` є навмисно загальним, і ми можемо використати це
```suggestion
Як згадувалося вище, `push` є навмисно узагальненим, і це можна використати
```

2022-07-07 16:29 UTC, undead404 commented on files/uk/web/javascript/reference/global_objects/array/push/index.md
> +на нашу користь. `Array.prototype.push` може добре працювати з об’єктом,
```suggestion
на власну користь. `Array.prototype.push` може добре працювати з об’єктом,
```

2022-07-07 16:29 UTC, undead404 commented on files/uk/web/javascript/reference/global_objects/array/push/index.md
> +якби ми мали справу з реальним масивом.
```suggestion
як якщо це був би реальний масив.
```

2022-07-08 17:52 UTC, AdriandeCita commented on files/uk/web/javascript/reference/global_objects/array/push/index.md
> +додає до нього два елементи. Змінна `total` містить нову довжину масиву.
Я б додав трохи акценту на тому, що це нові два елементи
```suggestion
додає до нього ще два елементи. Змінна `total` містить нову довжину масиву.
```

2022-07-10 15:03 UTC, AdriandeCita commented on files/uk/web/javascript/reference/global_objects/array/push/index.md
> +Те саме стосується нативних
Там в оригіналі мається на увазі конкретно об'єкт `arguments`
```suggestion
Те саме стосується нативного
```

2022-07-10 15:03 UTC, AdriandeCita commented on files/uk/web/javascript/reference/global_objects/array/push/index.md
> +масивоподібних об’єктів {{jsxref("Functions/arguments", "arguments", "", 1)}}.
```suggestion
масивоподібного об’єкта {{jsxref("Functions/arguments", "arguments", "", 1)}}.
```

2022-07-12 10:56 UTC, merged