translation(HTML): web/html/element/a
webdoky/content pull request #428
Opened 2022-07-14 17:17 UTC by undead404

Original content: https://developer.mozilla.org/en-US/docs/Web/HTML/Element/A

2022-07-18 15:53 UTC, AdriandeCita commented on files/uk/web/html/element/a/index.md
> +    > - Те, як браузери обробляють завантаження, залежить від браузера, налаштувань користувача та інших чинників. Користувача можуть запитати підтвердження перед початком завантаження, або ж файл мо
два останні пункти стосуються лише відкриття в браузері.
```suggestion
    > - Те, як браузери обробляють завантаження, залежить від браузера, налаштувань користувача та інших чинників. Користувача можуть запитати підтвердження перед початком завантаження, або ж файл може бути збережений автоматично, або ж буде автоматично відкритий: у зовнішньому застосунку, або в самому браузері.
```

2022-07-18 15:55 UTC, AdriandeCita commented on files/uk/web/html/element/a/index.md
> +    - `no-referrer-when-downgrade`: Заголовок {{HTTPHeader("Referer")}} не буде надісланий {{Glossary("origin", "походженням")}}, що не мають {{Glossary("TLS")}} ({{Glossary("HTTPS")}}).
```suggestion
    - `no-referrer-when-downgrade`: Заголовок {{HTTPHeader("Referer")}} не буде надісланий на ті {{Glossary("origin", "походження")}}, що не мають {{Glossary("TLS")}} ({{Glossary("HTTPS")}}).
```

2022-07-18 16:13 UTC, AdriandeCita commented on files/uk/web/html/element/a/index.md
> +    - `_top`: найвищий контекст перегляду (серед тих, що є предками відносно поточного). Якщо предків немає, це значення поводиться як `_self`.
дивлюся на оце і розумію, як працювало давно забуте мистецтво побудови лейауту сторінки на айфреймах :grin:

2022-07-18 16:23 UTC, AdriandeCita commented on files/uk/web/html/element/a/index.md
> +<canvas width="300" height="300"></canvas>
Потестив на МДН - не працює через CSP. Почитав помилку - схоже, це одна із тих ситуацій, коли в нас буде працювати щось, що не працює на МДН :grin:

2022-07-18 16:28 UTC, AdriandeCita commented on files/uk/web/html/element/a/index.md
> +Якщо призначення посилання позначено іконкою, слід пересвідчитись, що ця іконка має {{HTMLAttrxRef("alt", "img", "alt text", "true")}}:
```suggestion
Якщо призначення посилання позначено іконкою, слід пересвідчитись, що ця іконка має {{HTMLAttrxRef("alt", "img", "текстову альтернативу", "true")}}:
```

2022-07-18 16:32 UTC, AdriandeCita commented on files/uk/web/html/element/a/index.md
> +- [Хуткий тест: Достатньо великі мішені (англ.)](https://www.a11yproject.com/posts/large-touch-targets/)
```suggestion
- [Хуткий тест: Великі мішені для дотику (англ.)](https://www.a11yproject.com/posts/large-touch-targets/)
```

2022-07-18 16:35 UTC, AdriandeCita requested changes
Стосовно коментарів

2022-07-20 18:08 UTC, undead404 commented on files/uk/web/html/element/a/index.md
> +    - `_top`: найвищий контекст перегляду (серед тих, що є предками відносно поточного). Якщо предків немає, це значення поводиться як `_self`.
Я коли створював свій перший вебсайт, я AJAX іще не вмів, і у мене форма направляла відповідь у плаваючий фрейм! Оце технології були

2022-07-20 18:10 UTC, undead404 commented on files/uk/web/html/element/a/index.md
> +<canvas width="300" height="300"></canvas>
А в мене у Chrome запрацювало!

2022-07-20 22:26 UTC, AdriandeCita commented on files/uk/web/html/element/a/index.md
> +{{EmbedInteractiveExample("pages/tabbed/a.html")}}
```suggestion
{{EmbedInteractiveExample("pages/tabbed/a.html", "tabbed-shorter")}}
```

2022-07-20 22:27 UTC, AdriandeCita commented
Вніс зміни згідно з цим комітом https://github.com/mdn/content/commit/7e90bb68293370a2419eb28016f1803b594111ba#diff-8dae45e8aa4220ab9b4cd77d1c59ad7d470e590a7f0e6c297123740f937acd8d

2022-07-20 22:27 UTC, merged