Update/js ref functions af
webdoky/content pull request #447
Opened 2022-07-16 18:44 UTC by undead404

Оригінальний вміст: [Arrow function expressions@MDN](https://developer.mozilla.org/en-us/docs/Web/JavaScript/Reference/Functions/Arrow_functions), [сирці Arrow function expressions@GitHub](https://github.com/webdoky/content/tree/master/files/uk/web/javascript/reference/functions/arrow_functions/index.md)

Нові зміни:
- [mdn/content@b66ae46](https://github.com/mdn/content/commit/b66ae4647298ea7af4a2b58d67780df0795121e4)
- [mdn/content@61a8cdd](https://github.com/mdn/content/commit/61a8cddbde9257e05c55063985f28ac8d364082a)

2022-07-16 21:01 UTC, AdriandeCita commented
є свіже оновлення https://github.com/mdn/content/commit/d4b12e290fce9ae43a9ae23b9b9c8a5812b82ebd

2022-07-17 09:22 UTC, undead404 commented
> є свіже оновлення [mdn/content@d4b12e2](https://github.com/mdn/content/commit/d4b12e290fce9ae43a9ae23b9b9c8a5812b82ebd)

Застосовано.

2022-07-17 09:52 UTC, AdriandeCita commented on files/uk/web/javascript/reference/functions/arrow_functions/index.md
> +Because a [class](/uk/docs/Web/JavaScript/Reference/Classes)'s body has a `this` context, arrow functions as [class fields](/uk/docs/Web/JavaScript/Reference/Classes/Public_class_fields) close over t
```suggestion
```

2022-07-17 09:52 UTC, AdriandeCita commented on files/uk/web/javascript/reference/functions/arrow_functions/index.md
> +
```suggestion
```

2022-07-17 09:56 UTC, AdriandeCita requested changes
трохи зайвого тексту

2022-07-17 10:26 UTC, merged