Update/js ref go string
webdoky/content pull request #467
Opened 2022-07-20 20:55 UTC by undead404

Оригінальний вміст: [String@MDN](https://developer.mozilla.org/en-us/docs/Web/JavaScript/Reference/Global_Objects/String), [сирці String@GitHub](https://github.com/mdn/content/blob/main/files/en-us/web/javascript/reference/global_objects/string/index.md)

Нові зміни:
- [mdn/content@c2d5d7c](https://github.com/mdn/content/commit/c2d5d7c18f668ef5785832b93ceadcf321011264)
- [mdn/content@bf788b2](https://github.com/mdn/content/commit/bf788b2f0e62d74bfbd166711c1a4a0ed0592257)

2022-07-21 20:51 UTC, AdriandeCita commented on files/uk/web/javascript/reference/global_objects/string/index.md
> +// splits into the "Man" and "Boy" emoji, joined by a ZWJ
```suggestion
```

2022-07-21 20:51 UTC, AdriandeCita commented on files/uk/web/javascript/reference/global_objects/string/index.md
> +// All flag emojis are formed by joining two region indicator letters
```suggestion
```

2022-07-21 20:51 UTC, AdriandeCita requested changes
трішки почистити

2022-07-22 10:54 UTC, Aenqau approved these changes

2022-07-22 10:54 UTC, Aenqau commented
Бачив коментарі Миколи, апруваю з їх урахуванням

2022-07-22 20:57 UTC, merged