translation(HTML): web/html/element/video
webdoky/content pull request #471
Opened 2022-07-22 21:47 UTC by undead404

Оригінальний вміст: [<video>: The Video Embed element@MDN](https://developer.mozilla.org/en-us/docs/Web/HTML/Element/video), [сирці <video>: The Video Embed element@GitHub](https://github.com/mdn/content/blob/main/files/en-us/web/html/element/video/index.md)

2022-07-22 22:26 UTC, AdriandeCita commented
Оригінальний вміст: [&lt;video>: The Video Embed element@MDN](https://developer.mozilla.org/en-us/docs/Web/HTML/Element/video), [сирці &lt;video>: The Video Embed element@GitHub](https://github.com/mdn/content/blob/main/files/en-us/web/html/element/video/index.md)

test

2022-07-22 22:27 UTC, AdriandeCita commented
Так, схоже поправив копіювання

2022-07-24 20:08 UTC, AdriandeCita commented on files/uk/web/html/element/video/index.md
> +  - : Цей атрибут вказує, чи треба використовувати для отримання відповідного відео CORS. [Ресурси, що дозволяють CORS](/uk/docs/Web/HTML/CORS_enabled_image), можуть бути перевикористані в елементі {
Ого... Я встиг нагуглити переклад, написати виправлення, помітити таке ж слово нижче, погуглити краще, і таки знайти два рядочки притомного пояснення, що це за слово... Моя повага, слово крутезне, хоча може бути трохи заскладним для сприйняття.

2022-07-24 20:10 UTC, AdriandeCita commented on files/uk/web/html/element/video/index.md
> +      - : Надсилає запит на інше походження без авторизації. Інакше кажучи, надсилає заголовок HTTP `Origin:` без реп'яшка, сертифіката X.509 чи виконання базової автентифікації HTTP. Якщо сервер не
Реп'яшки - в принципі ок, але нам треба їх якось так писати, щоб потім нас в гуглі могли знайти зі своїми запитами

2022-07-24 20:52 UTC, AdriandeCita commented on files/uk/web/html/element/video/index.md
> +Особливих міркувань щодо стилізації `<video>` немає; загальною стратегією є надати йому властивість `display` зі значенням `block`, щоб йому було легше задати розташування, розмір тощо, а потім надат
```suggestion
Особливих міркувань щодо стилізації `<video>` немає; загальною стратегією є надати йому властивість `display` зі значенням `block`, щоб йому було легше задати розташування, розмір тощо, а потім надати стилізацію та інформацію про компонування, як необхідно. Певні методи стилізації наведено в [основах стилізації програвача відео](/uk/docs/Web/Guide/Audio_and_video_delivery/Video_player_styling_basics).
```

2022-07-24 20:56 UTC, AdriandeCita commented on files/uk/web/html/element/video/index.md
> +Поки відео починає відтворення, на його місці виводиться зображення, надане атрибутом `poster`. Якщо браузер не підтримує відтворення відео, виводиться запасний текст.
```suggestion
Поки відео починає відтворення, на його місці виводиться зображення, надане атрибутом `poster`. Якщо браузер не підтримує відтворення відео – виводиться запасний текст.
```

2022-07-24 21:00 UTC, AdriandeCita requested changes
Пара загальних коментарів, і пара невеличких зауважень

2022-07-25 18:10 UTC, undead404 commented on files/uk/web/html/element/video/index.md
> +  - : Цей атрибут вказує, чи треба використовувати для отримання відповідного відео CORS. [Ресурси, що дозволяють CORS](/uk/docs/Web/HTML/CORS_enabled_image), можуть бути перевикористані в елементі {
Я насправді з болем виробив цей переклад... Спершу був варіант "опороченими"... Зганьбленими... Бо "заплямованими" тут точно не підходить... Якось так

2022-07-25 18:20 UTC, merged