update(JS): web/javascript/reference/statements/switch
webdoky/content pull request #493
Opened 2022-07-24 08:29 UTC by undead404

Оригінальний вміст: [switch@MDN](https://developer.mozilla.org/en-us/docs/Web/JavaScript/Reference/Statements/switch), [сирці switch@GitHub](https://github.com/mdn/content/blob/main/files/en-us/web/javascript/reference/statements/switch/index.md)

Нові зміни:
- [mdn/content@561ff4d](https://github.com/mdn/content/commit/561ff4d92cf3593a6065f848fb4d08012eaa7ce3)

2022-07-24 14:47 UTC, AdriandeCita commented on files/uk/web/javascript/reference/statements/switch/index.md
> +Пункти `case` і `default` подібні до [позначок](/uk/docs/Web/JavaScript/Reference/Statements/label): вони вказують місця, куди контроль плину виконання може перестрибнути. Проте вони не створюють сам
Я зазвичай в цьому контексті перекладаю їх як "мітки", аби відмежовувати від інших позначок і підписів.
https://uk.wikipedia.org/wiki/%D0%9C%D1%96%D1%82%D0%BA%D0%B0
```suggestion
Пункти `case` і `default` подібні до [міток](/uk/docs/Web/JavaScript/Reference/Statements/label): вони вказують місця, куди контроль плину виконання може перестрибнути. Проте вони не створюють самі по собі лексичних [областей видимості](/uk/docs/Glossary/Scope) (так само як не виконують автоматично виходу – як показано вище). Наприклад:
```

2022-07-24 14:51 UTC, AdriandeCita commented on files/uk/web/javascript/reference/statements/switch/index.md
> +### Користування з провалювання
```suggestion
### Як скористатися провалюванням
```

2022-07-24 14:51 UTC, AdriandeCita commented on files/uk/web/javascript/reference/statements/switch/index.md
> +Нерідко доводиться робити ряд перевірок [`if...else`](/uk/docs/Web/JavaScript/Reference/Statements/if...else) matches.
```suggestion
Нерідко доводиться робити ряд перевірок [`if...else`](/uk/docs/Web/JavaScript/Reference/Statements/if...else).
```

2022-07-24 14:52 UTC, AdriandeCita requested changes
пара зауважень

2022-07-25 18:17 UTC, undead404 commented on files/uk/web/javascript/reference/statements/switch/index.md
> +### Користування з провалювання
```suggestion
### Користь від провалювання
```
Тут насправді малось на увазі дещо таке.

2022-07-25 18:24 UTC, AdriandeCita commented on files/uk/web/javascript/reference/statements/switch/index.md
> +### Користування з провалювання
най буде, цей варіант точно звучить узгодженіше, аніж поточний

2022-07-25 18:25 UTC, merged