translation(JS): web/javascript/reference/statements/import
webdoky/content pull request #498
Opened 2022-07-25 22:39 UTC by AdriandeCita

Оригінальний вміст: [import@MDN](https://developer.mozilla.org/en-us/docs/Web/JavaScript/Reference/Statements/import), [сирці import@GitHub](https://github.com/mdn/content/blob/main/files/en-us/web/javascript/reference/statements/import/index.md)

2022-07-25 22:42 UTC, AdriandeCita commented
Докинув свіжі зміни https://github.com/mdn/content/commit/8bf018f0a39d012a0d98afe3f15e0ed0fb7c8ce5#diff-05d7ccfe01b69e4a8e8a3de8fcb1b2f09704163f77269906b697568d11359e54

2022-07-27 05:25 UTC, undead404 requested changes
І головне: `/en-US/` -> `/uk/`

2022-07-27 05:25 UTC, undead404 commented on files/uk/web/javascript/reference/statements/import/index.md
> +  - : Назва об'єкта модуля, який під час звертання до імпортів буде вжито як свого роду простір імен. Повинен бути дійсним ідентифікатором JavaScript.
```suggestion
  - : Назва об'єкта модуля, яку під час звертання до імпортів буде вжито як свого роду простір імен. Повинна бути дійсним ідентифікатором JavaScript.
```

2022-07-27 05:25 UTC, undead404 commented on files/uk/web/javascript/reference/statements/import/index.md
> +Параметр `name` позначає ім'я "модульного об'єкта", що буде вжито як свого роду простір імен, для звертання до експортованих значень. Параметри `export` вказують окремі названі експортні об'єкти, в т
```suggestion
Параметр `name` позначає ім'я "модульного об'єкта", що буде вжито як свого роду простір імен для звертання до експортованих значень. Параметри `export` вказують окремі названі експортні об'єкти, в той час, як синтаксис `import * as name` імпортує їх всіх. Нижче буде наведено приклади уточнення цього синтаксису.
```

2022-07-27 05:25 UTC, undead404 commented on files/uk/web/javascript/reference/statements/import/index.md
> +Оголошення `import` сконструйовані таким чином, щоб бути синтаксично жорсткими (зокрема: допускаються лише літеральні рядкові вказівники, і лише на верхньому рівні, і за умови, що всі прив'язки являю
```suggestion
Оголошення `import` сконструйовані таким чином, щоб бути синтаксично жорсткими (зокрема: допускаються лише літеральні рядкові вказівники, і лише на верхньому рівні, і за умови, що всі прив'язки є ідентифікаторами). Це дає можливість статично аналізувати модулі та синхронно їх компонувати, іще до їхнього виконання. Це — ключова особливість, необхідна, аби зробити модулі асинхронними за природою, що дає змогу працювати функціональності штибу [`await` верхнього рівня](/en-US/docs/Web/JavaScript/Guide/Modules#await-verkhnioho-rivnia).
```

2022-07-27 09:12 UTC, AdriandeCita commented on files/uk/web/javascript/reference/statements/import/index.md
> +Оголошення `import` сконструйовані таким чином, щоб бути синтаксично жорсткими (зокрема: допускаються лише літеральні рядкові вказівники, і лише на верхньому рівні, і за умови, що всі прив'язки являю
Докинув окремим комітом тут https://github.com/webdoky/content/pull/498/commits/8ecf3faefdb8f89ea1ee22083aae82aa100fffb6

2022-07-27 11:03 UTC, undead404 approved these changes

2022-08-02 05:33 UTC, undead404 requested changes
New changes: https://github.com/mdn/content/commit/8579f04f440a8392d0aa6605df984513a52b24cc#diff-05d7ccfe01b69e4a8e8a3de8fcb1b2f09704163f77269906b697568d11359e54

2022-08-13 07:48 UTC, undead404 commented
Just to check: https://github.com/mdn/content/commit/4f5e0e38cd51ed4d52be2003375b87ceb9874974#diff-05d7ccfe01b69e4a8e8a3de8fcb1b2f09704163f77269906b697568d11359e54

2022-08-22 10:07 UTC, undead404 commented
Нові зміни: https://github.com/mdn/content/commit/7d03812b4a5bc66eca899effe3d1aba5af6185f8

2022-09-08 12:06 UTC, undead404 commented
Поки без нових змін

2022-09-15 08:12 UTC, undead404 commented
Нові зміни:
* https://github.com/mdn/content/commit/1533276490d15cff6ddcd201fc05562180058a99

2022-10-09 13:56 UTC, AdriandeCita commented
Оновлено аж до https://github.com/mdn/content/commit/1533276490d15cff6ddcd201fc05562180058a99#diff-05d7ccfe01b69e4a8e8a3de8fcb1b2f09704163f77269906b697568d11359e54

2022-10-10 08:09 UTC, undead404 requested changes

2022-10-10 08:09 UTC, undead404 commented on files/uk/web/javascript/reference/statements/import/index.md
> ++- [Імпорт простору імен](#namespace_import): `import * as name from "module-name";`
```suggestion
+- [Імпорт простору імен](#import-prostoru-imen): `import * as name from "module-name";`
```

2022-10-10 08:09 UTC, undead404 commented on files/uk/web/javascript/reference/statements/import/index.md
> ++- [Імпорт заради побічних ефектів](#import_a_module_for_its_side_effects_only): `import "module-name";`
```suggestion
+- [Імпорт заради побічних ефектів](#importuvannia-modulia-lyshe-zarady-yoho-pobichnykh-efektiv): `import "module-name";`
```

2022-10-10 08:09 UTC, undead404 commented on files/uk/web/javascript/reference/statements/import/index.md
> +Нехай дано певне значення під назвою `myExport`, експортоване з модуля `my-module` або явно за допомогою інструкції {{JSxRef("Statements/export", "export")}}, або неявно (як `export * from 'another.j
```suggestion
Нехай дано певне значення під назвою `myExport`, експортоване з модуля `my-module` або явно за допомогою інструкції {{JSxRef("Statements/export", "export")}}, або неявно (як `export * from 'another.js'`). Такий код додасть значення `myExport` у поточну область.
```

2022-10-10 08:09 UTC, undead404 commented on files/uk/web/javascript/reference/statements/import/index.md
> +Можна перейменувати експорт під час імпортування його значення. Наприклад, цей код вставляє значення `shortName` у поточну область видимості.
```suggestion
Можна перейменувати експорт під час імпортування його значення. Наприклад, цей код додає значення `shortName` у поточну область видимості.
```

2022-10-10 08:09 UTC, undead404 commented on files/uk/web/javascript/reference/statements/import/index.md
> +Усталений експорт слід імпортувати за допомогою відповідного синтаксису усталеного імпорту. Найпростіший варіант безпосередньо імпортує усталене значення:
```suggestion
Усталений експорт слід імпортувати за допомогою відповідного йому синтаксису усталеного імпорту. Найпростіший варіант безпосередньо імпортує усталене значення:
```

2022-10-10 08:09 UTC, undead404 commented on files/uk/web/javascript/reference/statements/import/index.md
> +Значення `myModule` — це [запечатаний](/uk/docs/Web/JavaScript/Reference/Global_Objects/Object/isSealed) об'єкт, чиїм прототипом є `null`. Всі його ключі є [перелічуваними](/uk/docs/Web/JavaScript/En
```suggestion
Значення `myModule` — це [запечатаний](/uk/docs/Web/JavaScript/Reference/Global_Objects/Object/isSealed) об'єкт, чиїм прототипом є `null`. Всі його ключі є [перелічуваними](/uk/docs/Web/JavaScript/Enumerability_and_ownership_of_properties) в лексикографічному порядку (тобто в послідовності, згідно з якою працює [`Array.prototype.sort()`](/uk/docs/Web/JavaScript/Reference/Global_Objects/Array/sort#opys)), причому усталений експорт буде доступний за ключем `default`.
```

2022-10-10 21:10 UTC, undead404 approved these changes

2022-10-10 21:11 UTC, merged