translation(JS): web/javascript/reference/global_objects/array/every
webdoky/content pull request #499
Opened 2022-07-27 05:14 UTC by undead404

Оригінальний вміст: [Array.prototype.every()@MDN](https://developer.mozilla.org/en-us/docs/Web/JavaScript/Reference/Global_Objects/Array/every), [сирці Array.prototype.every()@GitHub](https://github.com/mdn/content/blob/main/files/en-us/web/javascript/reference/global_objects/array/every/index.md)

2022-08-04 08:28 UTC, AdriandeCita commented on files/uk/web/javascript/reference/global_objects/array/every/index.md
> +// Супутня функція зворотного виклику
Супутня?

2022-08-04 08:45 UTC, AdriandeCita commented on files/uk/web/javascript/reference/global_objects/array/every/index.md
> +// Супутня функція зворотного виклику
"Вбудована" здається значно кращим перекладом. Ну або вже перекладати по суті:
```suggestion
// Функція зворотного виклику, оголошена на місці
```

2022-08-04 08:46 UTC, AdriandeCita requested changes
одне зауваження щодо "inline"

2022-08-05 06:12 UTC, undead404 commented on files/uk/web/javascript/reference/global_objects/array/every/index.md
> +// Супутня функція зворотного виклику
```suggestion
// Вбудована функція зворотного виклику
```
Я проти громіздкого звороту. Хай вже краще вбудована.

2022-08-05 10:26 UTC, AdriandeCita approved these changes

2022-08-05 10:27 UTC, merged