add translation for JavaScript index page
webdoky/content pull request #5
Opened 2021-08-01 10:11 UTC by AdriandeCita

Original page is here https://developer.mozilla.org/en-US/docs/Web/JavaScript

2021-08-01 10:40 UTC, AdriandeCita commented
Є декілька кандидатів у глоссарій
![image](https://user-images.githubusercontent.com/11510394/127767889-c0e7f646-c1a1-41eb-9c10-4e988c307215.png)

2021-08-03 15:31 UTC, undead404 requested changes

2021-08-03 15:31 UTC, undead404 commented on files/uk/web/javascript/index.md
> +> Ми зібрали докупи курс, що містить всю необхідну інформацію, що знадобиться вам
Можливо, замість другого "що" - "котра"?

2021-08-03 15:31 UTC, undead404 commented on files/uk/web/javascript/index.md
> +  - : StackBlitz &mdash; це іще один онлайн-майданчик та інструмент зневадження, який може розміщувати та розгортати повно стекові застосунки із використанням React, Angular, та ін.
Повно стекові? Напевне, правильний варіант не пропустить LanguageTool

2021-08-03 15:31 UTC, undead404 commented on files/uk/web/javascript/index.md
> +  - : RunJS &mdash; це ПК-весія майданчику/чернетки для роботи з JavaScript, яка надає можливість виконувати код, із доступом до API браузеру та Node.
ПК-весія - ПК-версія

2021-08-03 19:13 UTC, IhorHordiichuk commented on files/uk/web/javascript/index.md
> +**JavaScript** (**JS**) &mdash; це невибаглива до ресурсів мова програмування з {{Glossary("First-class Function", "функціями першого класу")}}, код якої інтерпретується, або компілюється ["на льоту"
1. Перше посилання на вікі можна замінити посиланням на українську вікі https://uk.wikipedia.org/wiki/JIT-%D0%BA%D0%BE%D0%BC%D0%BF%D1%96%D0%BB%D1%8F%D1%86%D1%96%D1%8F
2. не браузерних — навіть не знаю, здається все ж окремо
3. не прототип-орієнтована. Йдеться про прототипну мову (без додаткових слів)
4. функційне програмування — функціональне програмування
5. останнє посилання не працюватиме, якщо не замінити його на https://developer.mozilla.org/en-US/docs/Web/JavaScript/About_JavaScript

2021-08-03 19:18 UTC, IhorHordiichuk commented on files/uk/web/javascript/index.md
> +Цей розділ присвячено саме мові JavaScript, і він не торкається тонкощів роботи з вебсторінками, чи іншими оточенням для виконання JavaScript. Конкретну інформацію стосовно {{Glossary("API")}} вебсто
1. оточення — середовище
2. торкається я б замінив на «описує»
3. їхнє «please» ігноруємо, воно зайве у більшості випадків
4. знову ж, посилання внутрішнє навряд працюватиме https://developer.mozilla.org/en-US/docs/Web/API

2021-08-03 19:21 UTC, IhorHordiichuk commented on files/uk/web/javascript/index.md
> +Не плутайте JavaScript з [мовою програмування Java](<https://en.wikipedia.org/wiki/Java_(programming_language)>). Так, обидві мови "Java" та "JavaScript" є товарними знаками чи зареєстрованими торгов
1. https://uk.wikipedia.org/wiki/Java
2. лапки замінити на «»

2021-08-03 19:22 UTC, IhorHordiichuk commented on files/uk/web/javascript/index.md
> +> Ми зібрали докупи курс, що містить всю необхідну інформацію, що знадобиться вам
> Можливо, замість другого "що" - "котра"?
доречніше «яка»

2021-08-03 19:25 UTC, IhorHordiichuk commented on files/uk/web/javascript/index.md
> +Вчіться програмувати на JavaScript з нашими настановами та посібниками.
з — за допомогою

2021-08-03 19:30 UTC, IhorHordiichuk commented on files/uk/web/javascript/index.md
> +  - : Відповідає на деякі базові питання, як-от: "що таке JavaScript?", "на що вона схожа?", та "що вона може?"; включно з обговоренням ключових особливостей JavaScript, таких як: змінні, стрічки, чи
стрічки — рядки

2021-08-03 19:31 UTC, AdriandeCita commented on files/uk/web/javascript/index.md
> +  - : Замикання являє собою сполучення функції та лексичного оточення, всередині якого ця функція була об'явлена.
до речі, класне слово. "Об'явлення змінних" а-ля "declaration" трохи ріже вуха, а от оголошення здається дуже навіть притомним варіантом. Думаю, я всі декларації так опрацюю

2021-08-03 19:33 UTC, AdriandeCita commented on files/uk/web/javascript/index.md
> +  - : Дізнайтеся, як працювати зі функціями у  JavaScript для створення ваших застосунків.
справедливо. Як би нам не довелося іще й в languageTool фікси носити х)

2021-08-03 19:34 UTC, AdriandeCita commented on files/uk/web/javascript/index.md
> +  - : Дізнайтеся, як працювати зі функціями у  JavaScript для створення ваших застосунків.
тим паче, що їх репозиторії я позавчора таки відкопав на гітхабі х)

2021-08-03 19:36 UTC, AdriandeCita commented on files/uk/web/javascript/index.md
> +  - : StackBlitz &mdash; це іще один онлайн-майданчик та інструмент зневадження, який може розміщувати та розгортати повно стекові застосунки із використанням React, Angular, та ін.
можливо кандидат на обговорення. Я спочатку хотів вжити "застосунки повного стеку", але це трохі інший звір, ніж "fullstack application"

2021-08-03 19:41 UTC, IhorHordiichuk commented on files/uk/web/javascript/index.md
> +- [Клієнтські веб-API](/en-US/docs/Learn/JavaScript/Client-side_web_APIs)
вилка з веб-API, як подолати — не знаю. Мабуть, так і буде поки що.

2021-08-03 19:47 UTC, IhorHordiichuk commented on files/uk/web/javascript/index.md
> +  - : JavaScript фреймвоки &mdash; неодмінна частина сучасної клієнтської веброзробки, що забезпечує розробників перевіреними інструментами для побудови масштабованих інтерактивних вебзастосунків. Це
1. фреймвоки — фреймвРоки
2. фундаментальні базисні — залишити щось одне, бо масло масляне)))
3. фундаментальні знання про роботу клієнтських фреймворків

2021-08-03 19:49 UTC, IhorHordiichuk commented on files/uk/web/javascript/index.md
> +  - : Замикання являє собою сполучення функції та лексичного оточення, всередині якого ця функція була об'явлена.
оточення — середовища

2021-08-03 19:50 UTC, IhorHordiichuk commented on files/uk/web/javascript/index.md
> +  ### Передовий рівень
Якщо ми змінемо на «Поглиблене вивчення», нас не битимуть)

2021-08-03 19:54 UTC, IhorHordiichuk commented on files/uk/web/javascript/index.md
> +  - : Суворий режим встановлює неможливість використання змінної до її ініціалізації. Це обмежений варіант ECMAScript 5, який було створено для поліпшення швидкості виконання програми, та спрощення п
можна просто «пришвидшення» або «пришвидшеного»

2021-08-03 19:56 UTC, IhorHordiichuk commented on files/uk/web/javascript/index.md
> +- [Модель багатопотоковості, та Цикл подій](/en-US/docs/Web/JavaScript/EventLoop)
перед та прибрати кому

2021-08-03 19:59 UTC, IhorHordiichuk commented on files/uk/web/javascript/index.md
> +- [Інструкції та об'явлення](/en-US/docs/Web/JavaScript/Reference/Statements)
оголошення

2021-08-03 20:02 UTC, IhorHordiichuk commented on files/uk/web/javascript/index.md
> +Допоміжні інструменти, що полегшують написання і допомагають у зневадження вашого **JavaScript**-коду.
допомагають зневаджувати код **JavaScript**. «Ваш» і «будь ласка» варто пропускати за можливості.

2021-08-03 20:02 UTC, IhorHordiichuk commented on files/uk/web/javascript/index.md
> +  - : [Вебконсоль](/en-US/docs/Tools/Web_Console), [Інструмент профілювання JavaScript](/en-US/docs/Tools/Performance), [Debugger](/en-US/docs/Tools/Debugger), та інші.
JavaScript Profiler — власна назва

2021-08-03 20:04 UTC, IhorHordiichuk commented on files/uk/web/javascript/index.md
> +  - : Прекрасний ресурс для веброзробників, що прагнуть навчатися. Вчіть JavaScript всередині інтерактивного оточення, з короткими лекціями та інтерактивними тестами, які дають оцінку в автоматичному
> Вільні, як птахи, чи вільні, як пиво?

Так, мова про безплатність

2021-08-03 20:06 UTC, IhorHordiichuk commented on files/uk/web/javascript/index.md
> +  - : Прекрасний ресурс для веброзробників, що прагнуть навчатися. Вчіть JavaScript всередині інтерактивного оточення, з короткими лекціями та інтерактивними тестами, які дають оцінку в автоматичному
Вивчайте JavaScript в інтерактивному середовищі

2021-08-03 20:08 UTC, IhorHordiichuk commented on files/uk/web/javascript/index.md
> +  - : Співпраця, що створена простою. Після додавання TogetherJS до сайту, його користувачі зможуть допомагати один одному на вебсайті у реальному часі!
Співпраця, що створена простою — Проста (легка) взаємодопомога

2021-08-03 20:11 UTC, IhorHordiichuk commented on files/uk/web/javascript/index.md
> +  - : Редагуйте JavaScript, CSS, HTML, і отримуйте живі результати. Застосовуйте зовнішні ресурси, і співпрацюйте зі своєю командою онлайн.
1. HTML та одразу переглядайте результати.
2. ресурси та (кому прибрати)

2021-08-03 20:12 UTC, IhorHordiichuk commented on files/uk/web/javascript/index.md
> +  - : Plunker &mdash; це онлайн-спільнота для створення, співпраці, та обміну вашими ідеями для веброзробки. Редагуйте ваші JavaScript-, CSS- і HTML-файли, та отримуйте живі результати й файлову стру
HTML-файли та одразу переглядайте результати

2021-08-03 20:13 UTC, IhorHordiichuk commented on files/uk/web/javascript/index.md
> +  - : JS Bin &mdash; це колаборативний опенсорсний інструмент зневадження для веброзробки.
інструмент з відкритим кодом для спільного зневадження для веброзробки

2021-08-03 20:16 UTC, IhorHordiichuk commented on files/uk/web/javascript/index.md
> +  - : Codepen &mdash; це інший інструмент для колаборативної веброзробки, що використовується як майданчик для розміщення живих результатів.
розміщення живих результатів — перегляду результатів роботи коду у реальному часі

2021-08-03 20:18 UTC, IhorHordiichuk commented on files/uk/web/javascript/index.md
> +  - : StackBlitz &mdash; це іще один онлайн-майданчик та інструмент зневадження, який може розміщувати та розгортати повно стекові застосунки із використанням React, Angular, та ін.
Angular тощо.

2021-08-03 20:28 UTC, IhorHordiichuk commented on files/uk/web/javascript/index.md
> +  - : RunJS &mdash; це ПК-весія майданчику/чернетки для роботи з JavaScript, яка надає можливість виконувати код, із доступом до API браузеру та Node.
1. комп'ютерна версія «ігрового» майданчикА — хоча якось дивно звучить, але просто майданчик — це ще дивніше.
2. браузерА

2021-08-04 12:55 UTC, AdriandeCita commented on files/uk/web/javascript/index.md
> +  - : JavaScript фреймвоки &mdash; неодмінна частина сучасної клієнтської веброзробки, що забезпечує розробників перевіреними інструментами для побудови масштабованих інтерактивних вебзастосунків. Це
3 - переформулював по іншому, бо запропонований варіант погано вписувався у речення загалом

2021-08-04 12:56 UTC, AdriandeCita commented on files/uk/web/javascript/index.md
> +  ### Передовий рівень
я за будь-що, аби не просунутий х)

2021-08-04 13:43 UTC, AdriandeCita commented on files/uk/web/javascript/index.md
> +  - : RunJS &mdash; це ПК-весія майданчику/чернетки для роботи з JavaScript, яка надає можливість виконувати код, із доступом до API браузеру та Node.
Прийнято, поки зробимо так. Але взагалі з десктопами треба буде щось придумати, бо ні ПК, ні комп'ютер не відповідають семантиці оригіналу. Принаймні, у достатній мірі

2021-08-04 13:57 UTC, IhorHordiichuk commented
То що, заливати?

2021-08-05 07:16 UTC, AdriandeCita commented
Поправив іще пару пару дрібниць. Думаю, тепер можна

2021-08-13 10:58 UTC, merged