translation(JS): web/javascript/reference/operators/optional_chaining
webdoky/content pull request #512
Opened 2022-07-30 09:09 UTC by undead404

Оригінальний вміст: [Optional chaining (?.)@MDN](https://developer.mozilla.org/en-us/docs/Web/JavaScript/Reference/Operators/Optional_chaining), [сирці Optional chaining (?.)@GitHub](https://github.com/mdn/content/blob/main/files/en-us/web/javascript/reference/operators/optional_chaining/index.md)

2022-08-06 09:40 UTC, undead404 commented
Оновлено

2022-08-13 07:50 UTC, undead404 commented
Up to date

2022-08-22 10:09 UTC, undead404 commented
Без змін

2022-08-31 13:12 UTC, undead404 commented
Оновлено: https://github.com/mdn/content/commit/b01d1a6b1ed153eaf24e980da825349c9a5b0cb8#diff-a566e6355b428cc5ec1fe9d3a25a5796ec6ae3358f029620ee79f62928319ada

2022-09-15 08:31 UTC, undead404 commented
Оновлено: https://github.com/mdn/content/commit/1533276490d15cff6ddcd201fc05562180058a99

2022-09-22 12:54 UTC, AdriandeCita commented on files/uk/web/javascript/reference/operators/optional_chaining/index.md
> +Оператор необов'язкового ланцюжка пропонує спосіб до спрощення доступу до значень в пов'язаних об'єктах, коли можливо, що певне посилання чи певна функція може бути `undefined` чи `null`.
```suggestion
Оператор необов'язкового ланцюжка пропонує спосіб спрощення доступу до значень в пов'язаних об'єктах, коли можливо, що певне посилання чи певна функція може бути `undefined` чи `null`.
```

2022-09-22 12:59 UTC, AdriandeCita requested changes
невеличке зауваження

2022-09-22 13:00 UTC, AdriandeCita commented
Також є свіжі оновлення:

- https://github.com/mdn/content/commit/1c281241020fa0958597d3834c4c9d76ac1a079f
- https://github.com/mdn/content/commit/36e34a907ab3e65e11a0a685f6028638877172bd

2022-09-22 13:58 UTC, undead404 commented
Оновлено

2022-09-22 20:15 UTC, merged