translation(CSS): web/css/border-radius
webdoky/content pull request #526
Opened 2022-07-30 15:27 UTC by undead404

Оригінальний вміст: [border-radius@MDN](https://developer.mozilla.org/en-us/docs/Web/CSS/border-radius), [сирці border-radius@GitHub](https://github.com/mdn/content/blob/main/files/en-us/web/css/border-radius/index.md)

2022-08-13 07:51 UTC, undead404 commented
Up to date

2022-08-22 10:10 UTC, undead404 commented
Без змін

2022-08-31 13:19 UTC, undead404 commented
Оновлено: https://github.com/mdn/content/commit/283bc6b0a2310227f75a7772c2cff6c8082bb33f

2022-09-08 12:55 UTC, undead404 commented
Без змін

2022-09-15 08:37 UTC, undead404 commented
Без змін

2022-09-22 13:04 UTC, AdriandeCita approved these changes

2022-09-22 13:08 UTC, AdriandeCita requested changes
У мене є підозра, що оці зміни в форматуванні не доїхали, глянь будь ласка. https://github.com/mdn/content/commit/88866ee128116bd07235f5d3531152d5686a1e6d#diff-d2136b68d053dbd453ebcd68b768f1a4a23b9e8adf1ea3b390dd8b44ecb461b3

А в цілому виглядає ок

2022-09-23 14:23 UTC, undead404 commented
Поправив

2022-09-23 15:16 UTC, merged