translation(HTML): web/html/element/img
webdoky/content pull request #528
Opened 2022-07-31 07:22 UTC by undead404

Оригінальний вміст: [&lt;img>: The Image Embed element@MDN](https://developer.mozilla.org/en-us/docs/Web/HTML/Element/img), [сирці &lt;img>: The Image Embed element@GitHub](https://github.com/mdn/content/blob/main/files/en-us/web/html/element/img/index.md)

2022-08-13 08:06 UTC, undead404 commented
Оновлено

2022-08-22 10:10 UTC, undead404 commented
Без змін

2022-09-08 13:01 UTC, undead404 commented
Оновлено:
* https://github.com/mdn/content/commit/8294a075fcb8295f38037b34a68fe59010a9e77e

2022-09-22 13:19 UTC, AdriandeCita commented on files/uk/web/html/element/img/index.md
> +Якщо помилка трапляється при завантаженні чи візуалізації помилки, і якщо був встановлений обробник помилки {{htmlattrxref("onerror")}} для події {{domxref("Element/error_event", "error")}}, то такий
```suggestion
Якщо помилка трапляється при завантаженні чи візуалізації зображення, і якщо був встановлений обробник помилки {{htmlattrxref("onerror")}} для події {{domxref("Element/error_event", "error")}}, то такий обробник помилки буде викликаний. Це може статися в низці ситуацій, в тому числі:
```

2022-09-22 13:22 UTC, AdriandeCita commented on files/uk/web/html/element/img/index.md
> +  - : Вказує, що отримання зображення повинно виконуватися за допомогою запиту із {{glossary("CORS")}}. Дані зображення з [зображення із CORS](/uk/docs/Web/HTML/CORS_enabled_image), повернені з запит
Пропоную спростити запис
```suggestion
  - : Вказує, що отримання зображення повинно виконуватися за допомогою запиту із {{glossary("CORS")}}. Дані [зображення із CORS](/uk/docs/Web/HTML/CORS_enabled_image), повернені з запиту CORS, можуть бути повторно використані в елементі {{HTMLElement("canvas")}}, не бувши позначеними як "[ославлені](/uk/docs/Web/HTML/CORS_enabled_image#shcho-take-oslavlene-polotno)".
```

2022-09-22 13:26 UTC, AdriandeCita commented on files/uk/web/html/element/img/index.md
> +  - : Цей булів атрибут вказує, що зображення є частиною [серверної карти](https://en.wikipedia.org/wiki/Image_map#servernyi-bik). Якщо це так, то координати, в яких користувач клацнув зображення, на
```suggestion
  - : Цей булів атрибут вказує, що зображення є частиною [серверної карти](https://uk.wikipedia.org/wiki/%D0%9A%D0%B0%D1%80%D1%82%D0%B0_%D0%B7%D0%BE%D0%B1%D1%80%D0%B0%D0%B6%D0%B5%D0%BD%D1%8C#%D0%9D%D0%B0_%D1%81%D1%82%D0%BE%D1%80%D0%BE%D0%BD%D1%96_%D1%81%D0%B5%D1%80%D0%B2%D0%B5%D1%80%D0%B0). Якщо це так, то координати, в яких користувач клацнув зображення, надсилаються на сервер.
```

2022-09-22 13:49 UTC, AdriandeCita requested changes
Декілька зауважень

2022-09-22 13:53 UTC, AdriandeCita commented
Також є оновлення тут https://github.com/mdn/content/commit/0ec93e995168e0bafc50f73a3c5523ea5e5959f2#diff-e2459864fa55131421c75d03114d68a2ba8aa63bef3230f792c0f079253c76df, але виглядає нерелевантним

2022-09-22 14:31 UTC, undead404 commented
Оновлено

2022-09-22 20:16 UTC, merged