translation(HTML): web/html/element/heading_elements
webdoky/content pull request #529
Opened 2022-07-31 09:49 UTC by undead404

Оригінальний вміст: [&lt;h1>–<h6>: The HTML Section Heading elements@MDN](https://developer.mozilla.org/en-us/docs/Web/HTML/Element/Heading_Elements), [сирці &lt;h1>–<h6>: The HTML Section Heading elements@GitHub](https://github.com/mdn/content/blob/main/files/en-us/web/html/element/heading_elements/index.md)

2022-07-31 09:50 UTC, undead404 commented
@AdriandeCita не було враховано, що в назві може бути більше одного знака "<"; довелось лагодити опис вручну

2022-08-13 08:06 UTC, undead404 commented
Up to date

2022-08-22 10:23 UTC, undead404 commented
Без змін.

2022-08-31 13:20 UTC, undead404 commented
Без змін

2022-09-08 13:01 UTC, undead404 commented
Без змін

2022-09-22 14:02 UTC, AdriandeCita commented on files/uk/web/html/element/heading_elements/index.md
> +Розділення вмісту може отримати підписи завдяки комбінації атрибутів [`aria-labelledby`](/uk/docs/Web/Accessibility/ARIA/Attributes/aria-labelledby) та {{htmlattrxref("id")}}, і такі підписи повинні
Пропоную трохи перефразувати
```suggestion
Розділений вміст можна розмітити за допомогою комбінації атрибутів [`aria-labelledby`](/uk/docs/Web/Accessibility/ARIA/Attributes/aria-labelledby) та {{htmlattrxref("id")}}, які повинні стисло описувати призначення розділу. Такий підхід корисний в тих ситуаціях, коли на одній сторінці більш ніж один розділовий елемент.
```

2022-09-22 14:04 UTC, AdriandeCita requested changes
Одна пропозиція перефразувати речення, там дещо дивне формулювання

2022-09-22 14:21 UTC, AdriandeCita commented
Свіжі зміни https://github.com/mdn/content/commit/ffe47487ac9051c0a39e37d93d708288961a7c5f

2022-09-22 14:43 UTC, undead404 commented
Оновлено

2022-09-22 20:17 UTC, merged