translation(HTML): web/html/element/iframe
webdoky/content pull request #531
Opened 2022-08-02 07:06 UTC by undead404

Оригінальний вміст: [&lt;iframe>: The Inline Frame element@MDN](https://developer.mozilla.org/en-us/docs/Web/HTML/Element/iframe), [сирці &lt;iframe>: The Inline Frame element@GitHub](https://github.com/mdn/content/blob/main/files/en-us/web/html/element/iframe/index.md)

2022-08-13 08:13 UTC, undead404 commented
Без змін

2022-08-22 10:24 UTC, undead404 commented
Без змін

2022-08-31 13:32 UTC, undead404 commented
Оновлено:
* https://github.com/mdn/content/commit/a74d5d8410e463c77410d4000e9985cf2d8c89d9
* https://github.com/mdn/content/commit/3693e09ef2846ba9370b7e66e0cf66a67b712022

2022-09-15 09:03 UTC, undead404 commented
Без змін

2022-09-22 14:46 UTC, undead404 commented
Без змін

2022-09-22 14:49 UTC, AdriandeCita commented on files/uk/web/html/element/iframe/index.md
> +    - `origin-when-cross-origin`: Посилач, надісланий іншим походженням, буде обмежений схемою, хостом і портом. Переходи в межах того самого походження все ж включатимуть повний шлях.
Незрозуміло, чи запит надходить _від_ інших походжень, чи надсилається _на_ інші походження. Пропоную вживати більш однозначне формулювання
```suggestion
    - `origin-when-cross-origin`: Посилач, надісланий до інших походженнь, буде обмежений схемою, хостом і портом. Переходи в межах того самого походження все ж включатимуть повний шлях.
```

2022-09-22 15:05 UTC, AdriandeCita commented on files/uk/web/html/element/iframe/index.md
> +Ці атрибути є нерекомендованими й можуть більше не підтримуватися в усіх користувацьких агентах. Їх слід не використовувати в новому вмісті й намагатися усунути зі старого вмісту.
```suggestion
Ці атрибути є нерекомендованими й можуть більше не підтримуватися в усіх користувацьких агентах. Слід уникати їх використання в новому вмісті, а зі старого намагатися усувати.
```

2022-09-22 15:08 UTC, AdriandeCita requested changes
Пара зауважень

2022-09-23 14:25 UTC, undead404 commented
Поправив

2022-09-23 15:17 UTC, merged