translation(HTML): web/html/element/input/number
webdoky/content pull request #536
Opened 2022-08-05 06:08 UTC by undead404

Оригінальний вміст: [&lt;input type="number">@MDN](https://developer.mozilla.org/en-us/docs/Web/HTML/Element/input/number), [сирці &lt;input type="number">@GitHub](https://github.com/mdn/content/blob/main/files/en-us/web/html/element/input/number/index.md)

2022-08-13 08:16 UTC, undead404 commented
Оновлено

2022-08-22 10:38 UTC, undead404 commented
Оновлено

2022-08-31 13:32 UTC, undead404 commented
Без змін

2022-09-08 13:12 UTC, undead404 commented
Без змін

2022-09-15 09:03 UTC, undead404 commented
Без змін

2022-09-22 14:47 UTC, undead404 commented
Без змін

2022-09-22 19:18 UTC, AdriandeCita commented on files/uk/web/html/element/input/number/index.md
> +Атрибут `placeholder` (заповнювач) – рядок, що надає стислу підказку користувачеві щодо того, якого роду інформація очікується в полі. Це повинно бути слово чи коротка фраза, що демонструє очікуваний
```suggestion
Атрибут `placeholder` (заповнювач) – рядок, що надає стислу підказку користувачеві щодо того, якого роду інформація очікується в полі. Це повинно бути слово чи коротка фраза, що демонструє очікуваний тип даних, а не пояснювальне повідомлення. Текст _не повинен_ містити повернень каретки чи символів нового рядка.
```

2022-09-22 19:20 UTC, AdriandeCita commented on files/uk/web/html/element/input/number/index.md
> +> **Примітка:** За можливості слід уникати використання атрибута `placeholder`. Він не настільки семантично корисний, як інші способи пояснити форму, і може призвести до неочікуваних технічних пробле
```suggestion
> **Примітка:** За можливості слід уникати використання атрибута `placeholder`. Він не настільки семантично корисний, як інші способи пояснити форму, і може призвести до неочікуваних технічних проблем зі вмістом. Дивіться {{SectionOnPage("/uk/docs/Web/HTML/Element/input", "Підписи й заповнювачі")}} для отримання докладнішої інформації.
```

2022-09-22 19:44 UTC, AdriandeCita commented on files/uk/web/html/element/input/number/index.md
> +The `number` input type should only be used for incremental numbers, especially when spinbutton incrementing and decrementing are helpful to user experience. The `number` input type is not appropriat
```suggestion
Слід використовувати тип поля `number` лише для інкрементних чисел, особливо якщо наявність кнопки обертання для збільшення і зменшення є корисною для користувацького досвіду. Тип поля `number` недоречний для значень, яким випало складатися з одних цифр, проте які не є, по суті, числом, як от поштові коди в багатьох країнах, чи номери кредитних карт. Для нечислового вводу краще розглянути можливість вживання іншого типу поля, такого як [`<input type="tel">`](/uk/docs/Web/HTML/Element/input/tel) чи якогось іншого типу {{HTMLElement('input', 'поля введення')}} з атрибутом {{HTMLAttrXref('inputmode')}}:
```

2022-09-22 19:46 UTC, AdriandeCita commented on files/uk/web/html/element/input/number/index.md
> +Мобільні заходять в допомозі з користувацьким досвідом іще далі, показуючи особливу клавіатуру, котра краще підходить для введення чисел, коли користувач пробує ввести значення.
```suggestion
Мобільні браузери заходять в допомозі з користувацьким досвідом іще далі, показуючи особливу клавіатуру, котра краще підходить для введення чисел, коли користувач пробує ввести значення.
```

2022-09-22 20:14 UTC, AdriandeCita requested changes
декілька зауважень

2022-09-23 14:27 UTC, undead404 commented
Зауваження прийнято

2022-09-23 15:17 UTC, merged