update(JS): web/javascript/reference/global_objects/math
webdoky/content pull request #557
Opened 2022-08-05 10:03 UTC by undead404

Оригінальний вміст: [Math@MDN](https://developer.mozilla.org/en-us/docs/Web/JavaScript/Reference/Global_Objects/Math), [сирці Math@GitHub](https://github.com/mdn/content/blob/main/files/en-us/web/javascript/reference/global_objects/math/index.md)

Нові зміни:
- [mdn/content@2e2eab5](https://github.com/mdn/content/commit/2e2eab54121a9f521d5ea9438c635a76dfdfe255)
- [mdn/content@281e3b2](https://github.com/mdn/content/commit/281e3b21178946c8301232a8eb50d11770ee8450)

2022-08-05 12:28 UTC, AdriandeCita approved these changes

2022-08-05 12:28 UTC, AdriandeCita requested changes
Свіжі зміни https://github.com/mdn/content/commit/a6785a8e4ddad80069acf2de418235c0640688e7#diff-b7ccc9ecc9892c00e665e4648613868a449ccff6137ae9b688590cef95ed7985

2022-08-06 09:43 UTC, undead404 commented
Оновив

2022-08-07 09:25 UTC, AdriandeCita approved these changes

2022-08-07 09:25 UTC, merged