translation(JS): web/javascript/reference/global_objects/number
webdoky/content pull request #564
Opened 2022-08-06 06:04 UTC by undead404

Оригінальний вміст: [Number@MDN](https://developer.mozilla.org/en-us/docs/Web/JavaScript/Reference/Global_Objects/Number), [сирці Number@GitHub](https://github.com/mdn/content/blob/main/files/en-us/web/javascript/reference/global_objects/number/index.md)

2022-08-13 08:18 UTC, undead404 commented
Оновлено

2022-08-22 10:39 UTC, undead404 commented
Без змін

2022-09-08 13:17 UTC, undead404 commented
Оновлено:
* https://github.com/mdn/content/commit/8d76e99363dab6c2f8d31216b5b28620dd1e041f#diff-eda83b7448923ecef5ec3ca605372d2baa9198e83538056c2fb10635aff479a9

2022-09-15 10:48 UTC, undead404 commented
Оновлено: https://github.com/mdn/content/commit/8b6b6e735601c9bdc04a88695d3f93546df86ff9#diff-eda83b7448923ecef5ec3ca605372d2baa9198e83538056c2fb10635aff479a9

2022-09-22 14:54 UTC, undead404 commented
Без змін

2022-09-22 20:24 UTC, AdriandeCita commented on files/uk/web/javascript/reference/global_objects/number/index.md
> +  - : З'ясовує, чи є передане значення безпечним числом (числом в діапазоні від -(2<sup>53</sup> - 1) до 2<sup>53</sup> - 1).
```suggestion
  - : З'ясовує, чи є передане значення безпечним цілим (числом в діапазоні від -(2<sup>53</sup> - 1) до 2<sup>53</sup> - 1).
```

2022-09-22 20:26 UTC, AdriandeCita requested changes
Невеличке уточнення

2022-09-23 14:28 UTC, undead404 commented
Прийнято

2022-09-23 15:18 UTC, AdriandeCita approved these changes

2022-09-23 15:18 UTC, merged