update(JS): web/javascript/reference/global_objects/array
webdoky/content pull request #566
Opened 2022-08-06 06:10 UTC by undead404

Оригінальний вміст: [Array (масив)@MDN](https://developer.mozilla.org/en-us/docs/Web/JavaScript/Reference/Global_Objects/Array), [сирці Array (масив)@GitHub](https://github.com/mdn/content/blob/main/files/en-us/web/javascript/reference/global_objects/array/index.md)

Нові зміни:
- [mdn/content@d6f63f6](https://github.com/mdn/content/commit/d6f63f6e41146f459e21046af1c51fadb772de70)

2022-08-07 09:27 UTC, AdriandeCita commented
Нові зміни:
- [mdn/content@2d6d6a1](https://github.com/mdn/content/commit/2d6d6a1d9f8ba2073c9f8e1bbc6b4e20204fb53c)
- [mdn/content@8a5ab92](https://github.com/mdn/content/commit/8a5ab92ceab8fe1b8f44597381cf3fd996e252e9)

2022-08-07 09:28 UTC, AdriandeCita requested changes
є свіжі зміни

2022-08-13 08:38 UTC, undead404 commented
Оновлено

2022-08-13 12:18 UTC, AdriandeCita approved these changes

2022-08-13 12:18 UTC, merged