update(JS): web/javascript/reference/global_objects/date
webdoky/content pull request #569
Opened 2022-08-06 06:36 UTC by undead404

Оригінальний вміст: [Date@MDN](https://developer.mozilla.org/en-us/docs/Web/JavaScript/Reference/Global_Objects/Date), [сирці Date@GitHub](https://github.com/mdn/content/blob/main/files/en-us/web/javascript/reference/global_objects/date/index.md)

Нові зміни:
- [mdn/content@999a15c](https://github.com/mdn/content/commit/999a15c7fff68f635b6b5a5fc34cd3d803e6d8e9)

2022-08-07 09:30 UTC, AdriandeCita requested changes
Є свіжі зміни
- [mdn/content@999a15c](https://github.com/mdn/content/commit/999a15c7fff68f635b6b5a5fc34cd3d803e6d8e9)

2022-08-13 08:41 UTC, undead404 commented
Оновлено

2022-08-22 10:39 UTC, undead404 commented
Без змін

2022-08-26 16:03 UTC, AdriandeCita approved these changes

2022-08-26 16:03 UTC, merged