update(JS): web/javascript/reference/global_objects/string/replace
webdoky/content pull request #573
Opened 2022-08-06 06:56 UTC by undead404

Оригінальний вміст: [String.prototype.replace()@MDN](https://developer.mozilla.org/en-us/docs/Web/JavaScript/Reference/Global_Objects/String/replace), [сирці String.prototype.replace()@GitHub](https://github.com/mdn/content/blob/main/files/en-us/web/javascript/reference/global_objects/string/replace/index.md)

Нові зміни:
- [mdn/content@d6f63f6](https://github.com/mdn/content/commit/d6f63f6e41146f459e21046af1c51fadb772de70)

2022-08-07 09:33 UTC, AdriandeCita requested changes
Є свіжі зміни:
- [mdn/content@8a5ab92](https://github.com/mdn/content/commit/8a5ab92ceab8fe1b8f44597381cf3fd996e252e9)

2022-08-13 08:56 UTC, undead404 commented
Оновлено

2022-08-22 10:42 UTC, undead404 commented
Без змін

2022-08-26 16:08 UTC, AdriandeCita commented
Тут доволі масштабні зміни:
https://github.com/mdn/content/commit/f82233a2e58b3804af334ae0318fb8627153474c#diff-2362e7e0aa3e051b3cdc27e43b5dfa2a9cccc505366083c1430636c52fd09b0b

2022-08-26 16:09 UTC, AdriandeCita requested changes
per comment

2022-08-31 18:31 UTC, undead404 commented
Оновлено:
* https://github.com/mdn/content/commit/f82233a2e58b3804af334ae0318fb8627153474c
* https://github.com/mdn/content/commit/cf402f743c3b7f8f4ca954097c76d118119a81a2

2022-08-31 19:54 UTC, AdriandeCita commented on files/uk/web/javascript/reference/global_objects/string/replace/index.md
> +Якщо `pattern` є об'єктом із методом [`Symbol.replace`](/uk/docs/Web/JavaScript/Reference/Global_Objects/Symbol/replace) (в т.ч. об'єктом `RegExp`), то такий метод викликається з цільовим рядком і `r
```suggestion
Якщо `pattern` є об'єктом із методом [`Symbol.replace`](/uk/docs/Web/JavaScript/Reference/Global_Objects/Symbol/replace) (в т.ч. об'єктом `RegExp`), то такий метод викликається з цільовим рядком і `replacement` як аргументами. Його повернене значення стає поверненим значенням `replace()`. У такому випадку поведінка `replace()` цілком захована у методі `@@replace`: наприклад, будь-які згадки "груп захоплення" в описі нижче насправді є функціональністю, наданою [`RegExp.prototype[@@replace]`](/uk/docs/Web/JavaScript/Reference/Global_Objects/RegExp/@@replace).
```

2022-08-31 19:55 UTC, AdriandeCita commented on files/uk/web/javascript/reference/global_objects/string/replace/index.md
> +Конкретне число аргументів залежить від того, чи є перший аргумент об'єктом {{jsxref("RegExp")}} – і, якщо це так, того, скільки груп захоплення він має.
Коми там точно недостатньо
```suggestion
Конкретне число аргументів залежить від того, чи є перший аргумент об'єктом {{jsxref("RegExp")}} – і, якщо це так – того, скільки груп захоплення він має.
```

2022-08-31 20:03 UTC, AdriandeCita commented on files/uk/web/javascript/reference/global_objects/string/replace/index.md
> +Проте такий замінювач буде важко узагальнити, якщо він повинен працювати з будь-яким патерном регулярного виразу. Замінювач є _варіативним_: число аргументів, котре він отримує, залежить від числа пр
```suggestion
Проте такий замінювач буде важко узагальнити, якщо він повинен працювати з будь-яким патерном регулярного виразу. Замінювач є _варіативним_: число аргументів, котре він отримує, залежить від числа присутніх груп захоплення. Можна застосувати [решту параметрів](/uk/docs/Web/JavaScript/Reference/Functions/rest_parameters), але вона так само захопить у масив `offset`, `string` тощо. Факт того, що `groups` може бути або не бути переданим, залежно від ідентичності регулярного виразу, також ускладнює узагальнене з'ясування того, котрий із аргументів відповідає параметрові `offset`.
```

2022-09-07 15:27 UTC, undead404 commented
Без змін

2022-09-07 16:43 UTC, merged