update(JS): web/javascript/reference/functions/arrow_functions
webdoky/content pull request #574
Opened 2022-08-06 07:06 UTC by undead404

Оригінальний вміст: [Вирази стрілкових функцій@MDN](https://developer.mozilla.org/en-us/docs/Web/JavaScript/Reference/Functions/Arrow_functions), [сирці Вирази стрілкових функцій@GitHub](https://github.com/mdn/content/blob/main/files/en-us/web/javascript/reference/functions/arrow_functions/index.md)

Нові зміни:
- [mdn/content@a6785a8](https://github.com/mdn/content/commit/a6785a8e4ddad80069acf2de418235c0640688e7)
- [mdn/content@2665f98](https://github.com/mdn/content/commit/2665f98fa021d22f9b0678f836fba25590bd6aa4)

2022-08-07 09:34 UTC, AdriandeCita commented on files/uk/web/javascript/reference/functions/arrow_functions/index.md
> +> **Примітка:** В [суворому режимі](/en-US/docs/Web/JavaScript/Reference/Strict_mode#sproshchennia-eval-i-arguments) не можна оголошувати змінну з назвою `arguments`, тож код вище призвів би до синта
```suggestion
> **Примітка:** В [суворому режимі](/uk/docs/Web/JavaScript/Reference/Strict_mode#sproshchennia-eval-i-arguments) не можна оголошувати змінну з назвою `arguments`, тож код вище призвів би до синтаксичної помилки. Це робить область видимості `arguments` куди простішою для осмислення.
```

2022-08-07 09:35 UTC, AdriandeCita requested changes
дрібничка

2022-08-13 09:06 UTC, undead404 commented
Оновлено

2022-08-22 10:42 UTC, undead404 commented
Без змін

2022-08-26 16:11 UTC, AdriandeCita approved these changes

2022-08-26 16:12 UTC, merged