update(JS): web/javascript/reference/global_objects/string/match
webdoky/content pull request #579
Opened 2022-08-06 09:23 UTC by undead404

Оригінальний вміст: [String.prototype.match()@MDN](https://developer.mozilla.org/en-us/docs/Web/JavaScript/Reference/Global_Objects/String/match), [сирці String.prototype.match()@GitHub](https://github.com/mdn/content/blob/main/files/en-us/web/javascript/reference/global_objects/string/match/index.md)

Нові зміни:
- [mdn/content@a48583d](https://github.com/mdn/content/commit/a48583d3d51d7db2c5cbe4d0a84b80e9f09d57a9)

2022-08-07 09:39 UTC, AdriandeCita requested changes
Є свіжі зміни:
- [mdn/content@2d6d6a1](https://github.com/mdn/content/commit/2d6d6a1d9f8ba2073c9f8e1bbc6b4e20204fb53c)
- [mdn/content@c362aeb](https://github.com/mdn/content/commit/c362aebc2e4e7600be3a8ce6e97aaa8f7bad8810)

2022-08-13 11:36 UTC, undead404 commented
Оновлено

2022-08-22 10:59 UTC, undead404 commented
Оновлено

2022-08-31 18:32 UTC, undead404 commented
Без змін

2022-08-31 20:10 UTC, AdriandeCita approved these changes

2022-08-31 20:10 UTC, merged