update(JS): web/javascript/reference/statements/for...of
webdoky/content pull request #625
Opened 2022-09-08 09:16 UTC by undead404

Оригінальний вміст: [for...of@MDN](https://developer.mozilla.org/en-us/docs/Web/JavaScript/Reference/Statements/for...of), [сирці for...of@GitHub](https://github.com/mdn/content/blob/main/files/en-us/web/javascript/reference/statements/for...of/index.md)

Нові зміни:
- [mdn/content@1533276](https://github.com/mdn/content/commit/1533276490d15cff6ddcd201fc05562180058a99)
- [mdn/content@b609f73](https://github.com/mdn/content/commit/b609f73c5a910a274aca201cb6b20cf10ac46225)
- [mdn/content@f0648d8](https://github.com/mdn/content/commit/f0648d85c8408259af526ef1b9184bf95faf5083)
- [mdn/content@9b06a13](https://github.com/mdn/content/commit/9b06a13f934f101153c8ca2c77ab6d0cae2cf42a)

2022-09-09 09:31 UTC, AdriandeCita commented on files/uk/web/javascript/reference/statements/for...of/index.md
> +The `variable` part of `for...of` accepts anything that can come before the `=` operator. You can use {{jsxref("Statements/const", "const")}} to declare the variable as long as it's not reassigned wi
```suggestion
```

2022-09-09 09:39 UTC, AdriandeCita commented on files/uk/web/javascript/reference/statements/for...of/index.md
> +_Ітеровані ітератори_ (ітератори з методом `[@@iterator]()`, що повертає `this`) є доволі поширеним підходом, щоб зробити ітератори застосовними в синтаксичних конструкціях, що очікують ітерованих, я
Таке формулювання виглядає дивним, я б додавав "що саме є ітерованим". З одного боку - хочеться трішки натягувати сову на глобус, і розширювати українську мову, а з іншого - трохи бентежить, що результат іноді виглядає як переклад гуглотранслейтом зразка 16го року
```suggestion
_Ітеровані ітератори_ (ітератори з методом `[@@iterator]()`, що повертає `this`) є доволі поширеним підходом, щоб зробити ітератори застосовними в синтаксичних конструкціях, що очікують на ітеровані об'єкти, як то `for...of`.
```

2022-09-09 09:44 UTC, AdriandeCita commented on files/uk/web/javascript/reference/statements/for...of/index.md
> +Цикл `for...in` виводить лише [перелічувані властивості](/uk/docs/Web/JavaScript/Enumerability_and_ownership_of_properties) об'єкта `iterable`. Він не виводить _елементи_ масиву, `3`, `5`, `7` чи `"а
```suggestion
Цикл `for...in` виводить лише [перелічувані властивості](/uk/docs/Web/JavaScript/Enumerability_and_ownership_of_properties) об'єкта `iterable`. Він не виводить _елементи_ масиву, `3`, `5`, `7` чи `"агов"`, бо вони не є _властивостями_: вони є _значеннями_. Він виводить _індекси_ масиву, так само як `arrCustom` і `objCustom`, що є справжніми властивостями. Якщо немає певності в тому, чому ітеруються саме ці властивості — є більш поглиблене роз'яснення, як працюють [ітерування масиву та цикл `for...in`](/uk/docs/Web/JavaScript/Reference/Statements/for...in#array_iteration_and_for...in).
```

2022-09-09 09:44 UTC, AdriandeCita commented on files/uk/web/javascript/reference/statements/for...of/index.md
> +The `for...in` loop logs only [enumerable properties](/uk/docs/Web/JavaScript/Enumerability_and_ownership_of_properties) of the `iterable` object. It doesn't log array _elements_ `3`, `5`, `7` or `"h
```suggestion
```

2022-09-09 09:49 UTC, AdriandeCita commented on files/uk/web/javascript/reference/statements/for...of/index.md
> +Цикл `for...of` ітерує й виводить _значення_, котрі `iterable`, як масив (а масиви є [ітерованими](/uk/docs/Web/JavaScript/Reference/Global_Objects/Array/@@iterator)), визначає для ітерування. Демонс
довго думав, до чого тут "визначає для ітерування", якщо достатньо просто "значення [є] `iterable`, як масив"... Пропоную додати акценту, аби не виникало питань, хто то визначає
```suggestion
Цикл `for...of` ітерує й виводить _значення_, котрі об'єкт `iterable`, як масив (а масиви є [ітерованими](/uk/docs/Web/JavaScript/Reference/Global_Objects/Array/@@iterator)), визначає для ітерування. Демонструються _елементи_ об'єкта – `3`, `5`, `7`, але жодна з _властивостей_ об'єкта.
```

2022-09-16 10:59 UTC, undead404 commented on files/uk/web/javascript/reference/statements/for...of/index.md
> +Цикл `for...in` виводить лише [перелічувані властивості](/uk/docs/Web/JavaScript/Enumerability_and_ownership_of_properties) об'єкта `iterable`. Він не виводить _елементи_ масиву, `3`, `5`, `7` чи `"а
```suggestion
Цикл `for...in` виводить лише [перелічувані властивості](/uk/docs/Web/JavaScript/Enumerability_and_ownership_of_properties) об'єкта `iterable`. Він не виводить _елементи_ масиву, `3`, `5`, `7` чи `"агов"`, бо вони не є _властивостями_: вони є _значеннями_. Він виводить _індекси_ масиву, так само як `arrCustom` і `objCustom`, що є справжніми властивостями. Якщо немає певності в тому, чому ітеруються саме ці властивості — є більш поглиблене роз'яснення, як працюють [ітерування масиву та цикл `for...in`](/uk/docs/Web/JavaScript/Reference/Statements/for...in#iteruvannia-masyvu-i-tsykl-forin).
```

2022-09-16 11:27 UTC, AdriandeCita commented on files/uk/web/javascript/reference/statements/for...of/index.md
>  ```js
```suggestion
```js-nolint
```

2022-09-16 11:27 UTC, AdriandeCita commented on files/uk/web/javascript/reference/statements/for...of/index.md
> +for (variable of iterable) statement;
```suggestion
for (variable of iterable)
  statement;
```

2022-09-16 11:28 UTC, AdriandeCita requested changes
Додав іще зміни в контексті останнього оновлення
https://github.com/mdn/content/commit/1533276490d15cff6ddcd201fc05562180058a99#diff-2d89f66fa7d8ffb9d4fa84fab3c7d4effa4959d952cb3c9c3084e393c108b739

2022-09-22 10:49 UTC, undead404 commented
Без змін

2022-09-22 11:44 UTC, AdriandeCita approved these changes

2022-09-22 11:44 UTC, merged