update(JS): web/javascript/data_structures
webdoky/content pull request #643
Opened 2022-09-09 14:24 UTC by undead404

Оригінальний вміст: [JavaScript data types and data structures@MDN](https://developer.mozilla.org/en-us/docs/Web/JavaScript/Data_structures), [сирці JavaScript data types and data structures@GitHub](https://github.com/mdn/content/blob/main/files/en-us/web/javascript/data_structures/index.md)

2022-09-15 11:14 UTC, undead404 commented
Без змін

2022-09-22 15:48 UTC, undead404 commented
Оновлено

2022-09-22 20:44 UTC, AdriandeCita commented on files/uk/web/javascript/data_structures/index.md
> +JavaScript is also a [weakly typed](https://en.wikipedia.org/wiki/Strong_and_weak_typing) language, which means it allows implicit type conversion when an operation involves mismatched types, instead
```suggestion
```

2022-09-22 20:44 UTC, AdriandeCita commented on files/uk/web/javascript/data_structures/index.md
> +
```suggestion
```

2022-09-22 20:48 UTC, AdriandeCita commented on files/uk/web/javascript/data_structures/index.md
> +> **Примітка:** Попри те, що бітові оператори _можуть_ використовуватися для представлення декількох булевих значень в межах одного числа за допомогою [бітового маскування](<https://uk.wikipedia.org/
```suggestion
> **Примітка:** Попри те, що бітові оператори _можуть_ використовуватися для представлення декількох булевих значень в межах одного числа за допомогою [бітового маскування](https://uk.wikipedia.org/wiki/%D0%9C%D0%B0%D1%81%D0%BA%D1%83%D0%B2%D0%B0%D0%BD%D0%BD%D1%8F_(%D0%BF%D1%80%D0%BE%D0%B3%D1%80%D0%B0%D0%BC%D1%83%D0%B2%D0%B0%D0%BD%D0%BD%D1%8F)), такий код зазвичай вважається недоброю практикою. JavaScript надає інші засоби для представлення набору булевих значень (як то масив булевих значень чи об'єкт з булевими значеннями, присвоєними іменованим властивостям). Бітове маскування має тенденцію до ускладнення читання, розуміння й підтримки коду.
```

2022-09-22 21:06 UTC, AdriandeCita requested changes
Пара зауважень

2022-09-23 14:31 UTC, undead404 commented on files/uk/web/javascript/data_structures/index.md
> +> **Примітка:** Попри те, що бітові оператори _можуть_ використовуватися для представлення декількох булевих значень в межах одного числа за допомогою [бітового маскування](<https://uk.wikipedia.org/
Ці знаки додає Markdownlint, нехай будуть

2022-09-23 15:18 UTC, AdriandeCita commented on files/uk/web/javascript/data_structures/index.md
> +> **Примітка:** Попри те, що бітові оператори _можуть_ використовуватися для представлення декількох булевих значень в межах одного числа за допомогою [бітового маскування](<https://uk.wikipedia.org/
пняв

2022-09-23 15:19 UTC, merged