translation(JS): web/javascript/guide/modules
webdoky/content pull request #646
Opened 2022-09-13 16:35 UTC by undead404

Оригінальний вміст: [JavaScript modules@MDN](https://developer.mozilla.org/en-us/docs/Web/JavaScript/Guide/Modules), [сирці JavaScript modules@GitHub](https://github.com/mdn/content/blob/main/files/en-us/web/javascript/guide/modules/index.md)

2022-09-15 11:17 UTC, undead404 commented
Без змін.

2022-09-22 15:51 UTC, undead404 commented
Без змін

2022-09-22 21:57 UTC, AdriandeCita commented on files/uk/web/javascript/guide/modules/index.md
> +Також є різновид експорту, що зветься **усталеним експортом** — він розроблений для спрощення використання єдиної функції, наданої модулем, а також допомагає модулям JavaScript взаємодіяти з наявними
```suggestion
Також є різновид експорту, що зветься **усталеним експортом** — він розроблений для спрощення використання єдиної функції, наданої модулем, а також допомагає модулям JavaScript взаємодіяти з наявними модульними системами CommonJS та AMD (як це файно описано в [Поглиблено про ES6: Модулі (англ.)](https://hacks.mozilla.org/2015/08/es6-in-depth-modules/) від Джейсона Орендорффа; шукайте "Default exports").
```

2022-09-22 21:57 UTC, AdriandeCita commented on files/uk/web/javascript/guide/modules/index.md
> +- Крім того, зверніть увагу, що поведінка частин сценарію, визначених всередині модулів, коли порівняти зі звичайними сценаріями, може відрізнятися. Це пов'язано з тим, що модулі автоматично застосов
```suggestion
- Крім того, зверніть увагу, що поведінка частин сценарію, визначених всередині модулів, коли порівняти зі звичайними сценаріями, може відрізнятися. Це пов'язано з тим, що модулі автоматично застосовують {{JSxRef("Strict_mode", "суворий режим", "", 1)}}.
```

2022-09-22 22:00 UTC, AdriandeCita commented on files/uk/web/javascript/guide/modules/index.md
> +Погляньмо на робочий приклад. В нашій директорії [renaming](https://github.com/mdn/js-examples/tree/master/module-examples/renaming) – така сама модульна система, як в попередньому прикладі, крім тог
```suggestion
Погляньмо на робочий приклад. В нашій директорії [renaming](https://github.com/mdn/js-examples/tree/master/module-examples/renaming) – така сама модульна система, як в попередньому прикладі, крім того, що додалися модулі `circle.js` і `triangle.js`, для малювання й звітування про круги та трикутники.
```

2022-09-22 22:06 UTC, AdriandeCita commented on files/uk/web/javascript/guide/modules/index.md
> +Якщо включити цей модуль в файл [`main.js`](https://github.com/mdn/js-examples/blob/master/module-examples/top-level-await/main.js):
```suggestion
Включімо цей модуль до файлу [`main.js`](https://github.com/mdn/js-examples/blob/master/module-examples/top-level-await/main.js):
```

2022-09-22 22:13 UTC, AdriandeCita commented on files/uk/web/javascript/guide/modules/index.md
> +Запровадження модулів заохочує екосистему JavaScript поширювати й повторно використовувати код у модульному стилі. Проте це не обов'язково означає, що певний код JavaScript може працювати в будь-яком
Я здається зрозумів, у чому проблема з "породжує" - українською воно звучить радше як "щось, що створює, причому робить це самодостатньо". Це може підходити для опису `/dev/random` в лінуксах, який буквально є джерелом псевдовипадкових чисел. Проте це погано пасує до операції гешування, яка за визначенням потребує зовнішнього аргумента
```suggestion
Запровадження модулів заохочує екосистему JavaScript поширювати й повторно використовувати код у модульному стилі. Проте це не обов'язково означає, що певний код JavaScript може працювати в будь-якому середовищі. Припустімо, ви знайшли модуль, що обчислює геші SHA паролів користувача. Чи можна його використати у браузерному фронтенді? Чи можна його використати на Node.js сервері? Відповідь: буває по різному.
```

2022-09-22 22:16 UTC, AdriandeCita commented on files/uk/web/javascript/guide/modules/index.md
> +- Розділення модулів на "ядро" і "зв'язування". У "ядрі" слід зосередитися на щирій логіці JavaScript, як то обчисленні гешу, жодної DOM, звертань до мережі, файлової системи, і відкрити доступ до ко
```suggestion
- Розділення модулів на "ядро" і "зв'язування". У "ядрі" слід зосередитися на щирій логіці JavaScript, як то обчисленні гешу, жодної DOM, звертань до мережі, файлової системи – і відкрити доступ до корисних функцій. У "зв'язуванні" можна зчитувати й змінювати глобальний контекст. Наприклад, "браузерне зв'язування" може вирішити отримати значення з поля введення, а "зв'язування Node" – отримати його з `process.env`, але значення з обох місць передаються до однієї функції ядра й обробляються однаково. Ядро може бути імпортоване в кожному середовищі й використовуватися однаково, тим часом лише зв'язування, котре зазвичай є легковагим, мусить бути специфічним щодо платформи.
```

2022-09-22 22:20 UTC, AdriandeCita commented on files/uk/web/javascript/guide/modules/index.md
> +Проте ми вирішили надалі використовувати `.js`, принаймні поки що. Аби модулі коректно працювали в браузері, треба пересвідчитися, що сервер видає їх з заголовком `Content-Type`, що містить MIME тип
Наскільки я знаю, рушій видає нелокалізовані помилки.
```suggestion
Проте ми вирішили надалі використовувати `.js`, принаймні поки що. Аби модулі коректно працювали в браузері, треба пересвідчитися, що сервер видає їх з заголовком `Content-Type`, що містить MIME тип JavaScript, як то `text/javascript`. Без цього буде помилка строгої перевірки типу MIME і слова "The server responded with a non-JavaScript MIME type", і браузер такий JavaScript не запускатиме. Більшість серверів самі по собі встановлюють коректний тип для файлів `.js`, але не для файлів `.mjs`. Серед серверів, що уже видають файли `.mjs` коректно – [GitHub Pages](https://pages.github.com/) і [`http-server`](https://github.com/http-party/http-server#readme) для Node.js.
```

2022-09-22 22:22 UTC, AdriandeCita commented on uk_ignore_additions.txt
> -Байненса
Слух, а який сенс виносити частину імен звідси? Це якось впливає на роботу LT?

2022-09-22 22:23 UTC, AdriandeCita requested changes
Загалом круто, є декілька зауважень

2022-09-23 14:32 UTC, undead404 commented on uk_ignore_additions.txt
> -Байненса
Ні, але концептуально в цьому файлі повинні буди невідмінювані слова.

2022-09-23 14:35 UTC, undead404 commented
Прийнято

2022-09-23 15:20 UTC, AdriandeCita commented on uk_ignore_additions.txt
> -Байненса
а-а, он як... Цікаво, матиму на увазі

2022-09-25 09:50 UTC, AdriandeCita approved these changes
Круть, все ок, але є пара конфліктів

2022-09-25 13:58 UTC, merged