translation(JS): web/javascript/reference/global_objects/array/from
webdoky/content pull request #684
Opened 2022-09-15 12:07 UTC by undead404

Оригінальний вміст: [Array.from()@MDN](https://developer.mozilla.org/en-us/docs/Web/JavaScript/Reference/Global_Objects/Array/from), [сирці Array.from()@GitHub](https://github.com/mdn/content/blob/main/files/en-us/web/javascript/reference/global_objects/array/from/index.md)

2022-09-22 15:38 UTC, KlashReik commented on files/uk/web/javascript/reference/global_objects/array/from/index.md
> +// Породити діапазон чисел 0..4
Я б радше використав "згенерувати" чи "створити" (це вже непрямий переклад) замість "породити".

2022-09-22 15:52 UTC, undead404 commented on files/uk/web/javascript/reference/global_objects/array/from/index.md
> +// Породити діапазон чисел 0..4
```suggestion
// Згенерувати діапазон чисел 0..4
```

2022-09-22 15:55 UTC, undead404 commented
Без змін

2022-09-23 06:19 UTC, AdriandeCita commented on files/uk/web/javascript/reference/global_objects/array/from/index.md
> +// Породити послідовність чисел
```suggestion
// Згенерувати послідовність чисел
```

2022-09-23 06:19 UTC, AdriandeCita commented on files/uk/web/javascript/reference/global_objects/array/from/index.md
> +// Породити діапазон чисел 1..10 з кроком 2
```suggestion
// Згенерувати діапазон чисел 1..10 з кроком 2
```

2022-09-23 06:19 UTC, AdriandeCita commented on files/uk/web/javascript/reference/global_objects/array/from/index.md
> +// Породити за допомогою Array.from алфавіт, користуючись тим, що він має послідовний порядок
```suggestion
// Згенерувати за допомогою Array.from алфавіт, користуючись тим, що він має послідовний порядок
```

2022-09-23 06:20 UTC, AdriandeCita requested changes
Декілька правок, все стосується терміну "породити"

2022-09-23 14:36 UTC, undead404 commented
Прийнято

2022-09-23 15:24 UTC, merged