Translate web/js/reference/global_objects index
webdoky/content pull request #7
Opened 2021-08-01 13:09 UTC by AdriandeCita

Original content is here https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects

2021-08-03 18:25 UTC, undead404 requested changes

2021-08-03 21:47 UTC, IhorHordiichuk commented on files/uk/web/javascript/reference/global_objects/index.md
> +Ці об'єкти являють собою колекції, що використовують ключі. Колекції з перебиранням ({{JSxRef("Map")}} та {{JSxRef("Set")}}) містять елементи, що легко доступні для перебирання в порядку їх вставки.
1. Воно наче й дозволено, але згоден, варто, хоча б, чергувати «є». Тут можна замінити на «Ці об'єкти — це колекції»
2. у порядку їхнього вставляння. («їх» в українській мові відмінюється, вставка — результат, вставляння — дія)

2021-08-05 08:04 UTC, AdriandeCita commented
Вніс виправлення відповідно до зауважень

2021-08-07 14:57 UTC, IhorHordiichuk commented on files/uk/web/javascript/reference/global_objects/index.md
> +## Стандартні об'єкти по категоріях
за категоріями

2021-08-07 14:58 UTC, IhorHordiichuk commented on files/uk/web/javascript/reference/global_objects/index.md
> +Ці глобальні функції (ті функції, які радше викликаються глобально, аніж як методи об'єкту) — прямо повертають результат тому, хто їх викликав.
об'єктА

2021-08-07 14:59 UTC, IhorHordiichuk commented on files/uk/web/javascript/reference/global_objects/index.md
> +Об'єкти помилок - це особливий тип фундаментального об'єкта. Сюди входить базовий тип {{JSxRef("Error")}}, а також декілька спеціалізованих типів помилок.
«—»

2021-08-07 15:02 UTC, IhorHordiichuk commented on files/uk/web/javascript/reference/global_objects/index.md
> +Ці об'єкти служать для представлення стрічок тексту, та маніпуляцій із ними.
рядків (з текстом?) і маніпуляцій із ними.

2021-08-07 15:10 UTC, IhorHordiichuk commented on files/uk/web/javascript/reference/global_objects/index.md
> +Це колекції даних, які упорядковані за значенням індексу. Це охоплює масиви (в тому числі типізовані) і подібні до масивів конструкти.
Це об'єкти які містять колекції даних, впорядкованих за значенням індексу. Включають масиви (в тому числі типізовані) і подібні до масивів конструкції (об'єкти).
Про об'єкти обов'язково згадати на початку. Мова саме про них і їхній вміст.

2021-08-07 15:10 UTC, IhorHordiichuk commented on files/uk/web/javascript/reference/global_objects/index.md
> +Це колекції, що використовують тиак звані ключі для доступу до даних. Колекції з перебиранням ({{JSxRef("Map")}} та {{JSxRef("Set")}}) містять елементи, що легко доступні для перебирання у порядку їх
тиак -» так

2021-08-07 15:14 UTC, IhorHordiichuk commented on files/uk/web/javascript/reference/global_objects/index.md
> +Ці об'єкти представляють і взаємодіють зі структурованими буферами даних, а також і даними, що закодовані за допомогою Об'єктної Нотації JavaScript (JSON).
а також із закодованими за допомогою Об'єктної Нотації JavaScript (JSON).

2021-08-28 16:09 UTC, AdriandeCita commented
Вніс зміни згідно зауважень

2021-08-30 20:40 UTC, merged