translation(JS): web/javascript/closures
webdoky/content pull request #703
Opened 2022-09-17 08:25 UTC by undead404

Оригінальний вміст: [Closures@MDN](https://developer.mozilla.org/en-us/docs/Web/JavaScript/Closures), [сирці Closures@GitHub](https://github.com/mdn/content/blob/main/files/en-us/web/javascript/closures/index.md)

2022-09-22 16:22 UTC, KlashReik commented on files/uk/web/javascript/closures/index.md
> +Запустіть цей код за допомогою [цього посилання на JSFiddle](https://jsfiddle.net/3dxck52m/) і зауважте, що інструкція `console.log()` всередині функції `displayName()` успішно демонструє значення зм
```suggestion
як розбирач розуміє імена змінних
як розбирач розпізнає імена змінних
```

2022-09-22 16:22 UTC, KlashReik commented on files/uk/web/javascript/closures/index.md
> +Запустіть цей код за допомогою [цього посилання на JSFiddle](https://jsfiddle.net/3dxck52m/) і зауважте, що інструкція `console.log()` всередині функції `displayName()` успішно демонструє значення зм
```suggestion
Запустіть цей код за допомогою [цього посилання на JSFiddle](https://jsfiddle.net/3dxck52m/) і зауважте, що інструкція `console.log()` всередині функції `displayName()` успішно демонструє значення змінної `name`, котра оголошена в її батьківській функції. Це приклад _лексичного охоплення_, котрий показує, як розбирач розуміє імена змінних, коли функції вкладені одна в одну. Слово _лексичне_ вказує на факт того, що лексичне охоплення використовує місце, в якому змінна оголошена у вихідному коді, для з'ясування, де ця змінна доступна. Вкладені функції мають доступ до змінних, оголошених у зовнішній щодо себе області.
```
Запустіть цей код за допомогою [цього посилання на JSFiddle](https://jsfiddle.net/3dxck52m/) і зауважте, що інструкція `console.log()` всередині функції `displayName()` успішно демонструє значення змінної `name`, котра оголошена в її батьківській функції. Це приклад _лексичного охоплення_, котрий показує, як розбирач розпізнає імена змінних, коли функції вкладені одна в одну. Слово _лексичне_ вказує на факт того, що лексичне охоплення використовує місце, в якому змінна оголошена у вихідному коді, для з'ясування, де ця змінна доступна. Вкладені функції мають доступ до змінних, оголошених у зовнішній щодо себе області.

2022-09-22 16:25 UTC, KlashReik commented on files/uk/web/javascript/closures/index.md
> +Запустіть цей код за допомогою [цього посилання на JSFiddle](https://jsfiddle.net/3dxck52m/) і зауважте, що інструкція `console.log()` всередині функції `displayName()` успішно демонструє значення зм
```suggestion
Запустіть цей код за допомогою [цього посилання на JSFiddle](https://jsfiddle.net/3dxck52m/) і зауважте, що інструкція `console.log()` всередині функції `displayName()` успішно демонструє значення змінної `name`, котра оголошена в її батьківській функції. Це приклад _лексичного охоплення_, котрий показує, як розбирач розпізнає імена змінних, коли функції вкладені одна в одну. Слово _лексичне_ вказує на факт того, що лексичне охоплення використовує місце, в якому змінна оголошена у вихідному коді, для з'ясування, де ця змінна доступна. Вкладені функції мають доступ до змінних, оголошених у зовнішній щодо себе області.
```

2022-09-23 14:37 UTC, undead404 commented
Без змін

2022-09-25 09:54 UTC, AdriandeCita commented on files/uk/web/javascript/closures/index.md
> +**Замикання** – поєднання функції, зчепленої вкупі з (замкненої на) посилання на стан, що її оточує (**лексичне оточення**). Інакше кажучи, замикання надає з внутрішньої функції доступ до області вид
Думаю, краще в першу чергу узгоджувати основний вміст речення, а не той, що в дужках
```suggestion
**Замикання** – поєднання функції, зчепленої вкупі з (замкненої на) посиланням на стан, що її оточує (**лексичне оточення**). Інакше кажучи, замикання надає з внутрішньої функції доступ до області видимості зовнішньої функції. У JavaScript замикання породжуються щоразу, коли створюється функція, під час її створення.
```

2022-09-25 10:08 UTC, AdriandeCita commented on files/uk/web/javascript/closures/index.md
> +Ситуації, за яких можна розглянути такий варіант, у вебтехнологіях особливо поширені. Значна частина коду JavaScript фронтенду заснована на подіях. Описується певна логіка, котра потім прикріпляється
В оригіналі було `...written in front-end JavaScript...`, що не зовсім тотожно `JavaScript фронтенду`. Ну і ще поняття "%languageName% фронтенд" радше натякає на оболонку компілятора (принаймні, для мене)
```suggestion
Ситуації, за яких можна розглянути такий варіант, у вебтехнологіях особливо поширені. Значна частина коду, написаного клієнтським JavaScript, заснована на подіях. Описується певна логіка, котра потім прикріпляється до події, котру запускає користувач (як то клацання чи натискання клавіші). Код прикріпляється у вигляді функції зворотного виклику (однієї функції, що виконується у відповідь на подію).
```

2022-09-25 10:21 UTC, AdriandeCita commented on files/uk/web/javascript/closures/index.md
> +Замикання також можуть замикатися над імпортованими значеннями, котрі вважаються _мінливими зв'язуваннями_, адже коли змінюється початкове значення, відповідно змінюються значення імпортовані.
_Мінливе зв'язування_ - я вперше чую таку версію. Щоправда, я в принципі не пригадую достойного перекладу терміну live bindings :joy:
В будь-якому разі, "мінливий" звучить трохи дивно, адже саме зв'язування якраз не змінюється. Звідки він? Чи є сенс його переглянути?

2022-09-25 10:27 UTC, AdriandeCita requested changes
пара дрібниць

2022-09-25 13:49 UTC, undead404 commented on files/uk/web/javascript/closures/index.md
> +Замикання також можуть замикатися над імпортованими значеннями, котрі вважаються _мінливими зв'язуваннями_, адже коли змінюється початкове значення, відповідно змінюються значення імпортовані.
Є сенс. Як варіант – буквальний переклад? Слово "live" загалом має дуже багато варіантів перекладу.
```suggestion
Замикання також можуть замикатися над імпортованими значеннями, котрі вважаються _живими зв'язуваннями_, адже коли змінюється початкове значення, відповідно змінюються значення імпортовані.
```

2022-09-25 13:59 UTC, AdriandeCita commented on files/uk/web/javascript/closures/index.md
> +Замикання також можуть замикатися над імпортованими значеннями, котрі вважаються _мінливими зв'язуваннями_, адже коли змінюється початкове значення, відповідно змінюються значення імпортовані.
Підтримую. Окрім того, що "живий" достатньо непогано узгоджується зі суттю терміну, в нього є іще одна перевага - можливість тривіально отримати оригінальний термін шляхом зворотного перекладу

2022-09-25 14:00 UTC, AdriandeCita commented on files/uk/web/javascript/closures/index.md
> +export const getX = () => x; // Замкнутися над імпортованим мінливим зв'язуванням
```suggestion
export const getX = () => x; // Замкнутися над імпортованим живим зв'язуванням
```

2022-09-25 14:01 UTC, AdriandeCita commented on files/uk/web/javascript/closures/index.md
> +Замикання також можуть замикатися над імпортованими значеннями, котрі вважаються _мінливими зв'язуваннями_, адже коли змінюється початкове значення, відповідно змінюються значення імпортовані.
Докинув у пропозиції іще одине входження цього терміну нижче

2022-09-26 12:17 UTC, undead404 commented
Погодились

2022-09-26 13:13 UTC, KlashReik commented on files/uk/web/javascript/closures/index.md
> +Причина цього в тому, що функції в JavaScript утворюють замикання. _Замикання_ – це поєднання функції й лексичного оточення, всередині якого ця функція оголошена. Таке оточення складається з усіх змі
```suggestion
Причина цього в тому, що функції в JavaScript утворюють замикання. _Замикання_ – це поєднання функції й лексичного оточення, всередині якого ця функція оголошена. Таке оточення складається з усіх змінних, що були в поточній області видимості, коли створювалось замикання. В конкретному випадку `myFunc` є посиланням на примірник функції `displayName`, що створюється, коли запускається `makeFunc`. Примірник `displayName` зберігає посилання на своє лексичне оточення, всередині якого існує змінна `name`. Через це, коли викликається `myFunc`, то змінна `name` залишається доступною для використання, і в `console.log` передається "ВебДоки".
```
В моєму розумінні закликати можна до бою, але не функцію.

2022-09-26 13:57 UTC, KlashReik commented on files/uk/web/javascript/closures/index.md
> +Замикання також можуть замикатися над імпортованими значеннями, котрі вважаються _живими зв'язуваннями_, адже коли змінюється початкове значення, відповідно змінюються значення імпортовані.
```suggestion
Замикання також можуть замикатися над імпортованими значеннями, котрі вважаються _живими зв'язуваннями_, адже коли змінюється початкове значення, відповідно змінюються й імпортовані значення.
```
Можна і без "й", але "значення імпортовані" варто замінити на "імпортовані значення".

2022-09-26 16:50 UTC, undead404 commented on files/uk/web/javascript/closures/index.md
> +Причина цього в тому, що функції в JavaScript утворюють замикання. _Замикання_ – це поєднання функції й лексичного оточення, всередині якого ця функція оголошена. Таке оточення складається з усіх змі
Пропоную не збіднювати мову і лишити як є. Викликати також можна до бою. А можна функцію закликати, щоб вона перестала сидіти склавши руки і зробила щось!

2022-09-27 21:13 UTC, AdriandeCita commented on files/uk/web/javascript/closures/index.md
> +Причина цього в тому, що функції в JavaScript утворюють замикання. _Замикання_ – це поєднання функції й лексичного оточення, всередині якого ця функція оголошена. Таке оточення складається з усіх змі
англійською функцію можна як `call` - викликати, `execute` - виконати, і `invoke`. Ось з останнім є нюанс, бо зводити все до "викликати" не хочеться, але й з гарним перекладом складно. Я особисто надаю перевагу варіантові "звернутися до", але це ціла конструкція, яку іще в контекст треба вписати, тож продати її на загал я не зміг :smile:

2022-09-27 21:14 UTC, AdriandeCita approved these changes

2022-09-27 21:14 UTC, merged