translation(CSS): web/css/grid-template-columns
webdoky/content pull request #711
Opened 2022-09-17 16:52 UTC by undead404

Оригінальний вміст: [grid-template-columns@MDN](https://developer.mozilla.org/en-us/docs/Web/CSS/grid-template-columns), [сирці grid-template-columns@GitHub](https://github.com/mdn/content/blob/main/files/en-us/web/css/grid-template-columns/index.md)

2022-09-22 19:50 UTC, undead404 commented
Без змін

2022-09-23 14:39 UTC, undead404 commented
Без змін

2022-09-25 13:50 UTC, undead404 commented
Без змін

2022-10-03 07:33 UTC, KlashReik commented on files/uk/web/css/grid-template-columns/index.md
> +Властивість CSS **`grid-template-columns`** визначає імена ліній і функцій калібрування доріжок {{glossary("grid column", "сіткових колонок")}}.
```suggestion
Властивість CSS **`grid-template-columns`** визначає імена ліній і функції калібрування доріжок {{glossary("grid column", "сіткових колонок")}}.
```

2022-10-03 07:46 UTC, KlashReik commented on files/uk/web/css/grid-template-columns/index.md
> +    Внутрішній розмір доріжки можна припасувати до розміру контейнера сітки й збільшити підсумковий розбір доріжки на найменшу величину, котра дасть змогу відповідати відсотковому значенню.
```suggestion
    Внутрішній розмір доріжки можна припасувати до розміру контейнера сітки й збільшити сумарний розмір доріжки на найменшу величину, котра дасть змогу відповідати відсотковому значенню.
```

2022-10-03 08:00 UTC, KlashReik commented on files/uk/web/css/grid-template-columns/index.md
> +  - : Представляє формулу `max(minimum, min(limit, max-content))`, де _minimum_ представляє мінімум `auto` (котрий нерідко, хоч і не завжди, рівний мінімумові {{cssxref("min-content")}}), а _limit_ –
```suggestion
  - : Представляє формулу `max(minimum, min(limit, max-content))`, де _minimum_ представляє мінімум `auto` (котрий нерідко, хоч і не завжди, рівний мінімумові {{cssxref("min-content")}}), а _limit_ – функція калібрування доріжки, передана як аргумент у fit-content(). По суті, обчислюється як менше серед `minmax(auto, max-content)` і `minmax(auto, limit)`.
 
```

2022-10-08 09:13 UTC, AdriandeCita commented on files/uk/web/css/grid-template-columns/index.md
> +  - : Є ключовим словом, що представляє [внесок максимального вмісту (англ.)](https://www.w3.org/TR/css-sizing-3/#max-content) елементів сітки, що займають доріжку сітки. Наприклад, якщо перший елеме
ого, і тут русня спиздила. Я завжди вважав "повторенье - мать ученья" російським прислів'ям, а виявляється - це іще з латини

2022-10-08 09:38 UTC, AdriandeCita commented on files/uk/web/css/grid-template-columns/index.md
> +#### Result
```suggestion
#### Результат
```

2022-10-08 09:39 UTC, AdriandeCita requested changes
Єдине зауваження щодо пропущеного перекладу

2022-10-16 14:05 UTC, merged