translation(CSS): web/css/font-weight
webdoky/content pull request #712
Opened 2022-09-17 17:54 UTC by undead404

Оригінальний вміст: [font-weight@MDN](https://developer.mozilla.org/en-us/docs/Web/CSS/font-weight), [сирці font-weight@GitHub](https://github.com/mdn/content/blob/main/files/en-us/web/css/font-weight/index.md)

2022-09-22 19:52 UTC, undead404 commented
Без змін

2022-09-23 14:39 UTC, undead404 commented
Без змін

2022-09-25 10:49 UTC, AdriandeCita commented on files/uk/web/css/font-weight/index.md
> +Числові значення `100` й `900` приблизно відповідають наступним загальноприйнятим іменам ваг (дивіться [Специфікацію OpenType (англ.)](https://docs.microsoft.com/typography/opentype/spec/os2#usweight
```suggestion
Числові значення від `100` до `900` приблизно відповідають наступним загальноприйнятим іменам ваг (дивіться [Специфікацію OpenType (англ.)](https://docs.microsoft.com/typography/opentype/spec/os2#usweightclass)):
```

2022-09-25 10:52 UTC, AdriandeCita requested changes
Одне зауваження

2022-09-25 14:01 UTC, AdriandeCita approved these changes

2022-09-26 12:19 UTC, merged