translation(CSS): web/css/transform
webdoky/content pull request #714
Opened 2022-09-18 08:06 UTC by undead404

Оригінальний вміст: [transform@MDN](https://developer.mozilla.org/en-us/docs/Web/CSS/transform), [сирці transform@GitHub](https://github.com/mdn/content/blob/main/files/en-us/web/css/transform/index.md)

2022-09-22 19:54 UTC, undead404 commented
Без змін

2022-09-23 14:40 UTC, undead404 commented
Без змін

2022-09-25 10:56 UTC, AdriandeCita commented on files/uk/web/css/transform/index.md
> +Анімації масштабування й наближення є проблемними для доступності, адже вони є поширеним пускачем певних різновидів мігрені.
```suggestion
Анімації масштабування й наближення є проблемними для доступності, адже вони є поширеною причиною певних різновидів мігрені.
```

2022-09-25 10:58 UTC, AdriandeCita commented on files/uk/web/css/transform/index.md
> +Крім того, слід розглянути використання ознаки медіа {{cssxref("@media/prefers-reduced-motion", "prefers-reduced-motion")}}: за її допомогою можна написати [запит медіа](/uk/docs/Web/CSS/Media_Querie
медіаознаки я б теж волів писати разом, але у нас уже є більше однієї статті, де ми їх окремо пишемо. Що ж до медіазапитів - то ми їх одразу почали писати разом https://webdoky.org/uk/docs/Web/CSS/Media_Queries/Using_media_queries/
```suggestion
Крім того, слід розглянути використання ознаки медіа {{cssxref("@media/prefers-reduced-motion", "prefers-reduced-motion")}}: за її допомогою можна написати [медіазапит](/uk/docs/Web/CSS/Media_Queries), котрий вимкне анімації, якщо користувач має у своїх системних налаштуваннях позначку "менше анімації".
```

2022-09-25 11:03 UTC, AdriandeCita commented on files/uk/web/css/transform/index.md
> +- Мережевий інструмент для візуалізації функцій перетворень CSS: [Ігровий майданчик перетворень CSS](https://css-transform.moro.es/)
"Мережевий інструмент" викликає абсолютно недоречні асоціації)
```suggestion
- Інструмент для візуалізації функцій перетворень CSS, доступний в мережі: [Ігровий майданчик перетворень CSS](https://css-transform.moro.es/)
```

2022-09-25 11:03 UTC, AdriandeCita requested changes
Декілька зауважень

2022-09-25 13:52 UTC, undead404 commented on files/uk/web/css/transform/index.md
> +Анімації масштабування й наближення є проблемними для доступності, адже вони є поширеним пускачем певних різновидів мігрені.
```suggestion
Анімації масштабування й наближення є проблемними для доступності, адже вони є поширеним тригером певних різновидів мігрені.
```
Хіба що отак.

2022-09-26 12:31 UTC, KlashReik commented on files/uk/web/css/transform/index.md
> +Анімації масштабування й наближення є проблемними для доступності, адже вони є поширеним пускачем певних різновидів мігрені.
Віддаю перевагу варіанту "тригером".

2022-09-27 21:18 UTC, AdriandeCita commented on files/uk/web/css/transform/index.md
> +Анімації масштабування й наближення є проблемними для доступності, адже вони є поширеним пускачем певних різновидів мігрені.
ну, аби не пускач, бо то занадто технічний термін. Тим паче для мігрені, котра любить підкрадатися поступово.

2022-09-27 21:21 UTC, AdriandeCita approved these changes

2022-09-27 21:22 UTC, merged