translation(CSS): web/css/overflow
webdoky/content pull request #715
Opened 2022-09-18 09:29 UTC by undead404

Оригінальний вміст: [overflow@MDN](https://developer.mozilla.org/en-us/docs/Web/CSS/overflow), [сирці overflow@GitHub](https://github.com/mdn/content/blob/main/files/en-us/web/css/overflow/index.md)

2022-09-22 19:54 UTC, undead404 commented
Без змін

2022-09-23 14:41 UTC, undead404 commented
Без змін

2022-09-25 11:32 UTC, AdriandeCita commented on files/uk/web/css/overflow/index.md
> +Задання значення, відмінного від `visible` (усталеного) і `clip`, породжує новий [контекст блокового форматування](/uk/docs/Web/Guide/CSS/Block_formatting_context). Це необхідно з технічних причин: я
Ймовірно малася на увазі властивість "обтікання текстом елементів із встановленою властивістю `float: ...`
```suggestion
Задання значення, відмінного від `visible` (усталеного) і `clip`, породжує новий [контекст блокового форматування](/uk/docs/Web/Guide/CSS/Block_formatting_context). Це необхідно з технічних причин: якби плаваючий елемент перетнувся з прокрутним, це змусило б повторно розставляти переноси всередині вмісту після кожного кроку прокручування, і як наслідок – повільного прокручування.
```

2022-09-25 11:34 UTC, AdriandeCita commented on uk_spelling_additions.txt
> +перезагортання
Відповідно, немає потреби в цьому терміні
```suggestion
```

2022-09-25 11:34 UTC, AdriandeCita requested changes
Одне зауваження

2022-09-25 13:54 UTC, undead404 commented on files/uk/web/css/overflow/index.md
> +Задання значення, відмінного від `visible` (усталеного) і `clip`, породжує новий [контекст блокового форматування](/uk/docs/Web/Guide/CSS/Block_formatting_context). Це необхідно з технічних причин: я
Суттєве зауваження, але тоді отак.

```suggestion
Задання значення, відмінного від `visible` (усталеного) і `clip`, породжує новий [контекст блокового форматування](/uk/docs/Web/Guide/CSS/Block_formatting_context). Це необхідно з технічних причин: якби плавучий елемент перетнувся з прокрутним елементом, це змусило б повторно розставляти переноси всередині вмісту після кожного кроку прокручування, і як наслідок – призвело б до повільного прокручування.
```

2022-09-27 21:23 UTC, AdriandeCita commented on files/uk/web/css/overflow/index.md
> +Задання значення, відмінного від `visible` (усталеного) і `clip`, породжує новий [контекст блокового форматування](/uk/docs/Web/Guide/CSS/Block_formatting_context). Це необхідно з технічних причин: я
маєте рацію, питань немає

2022-09-27 21:23 UTC, AdriandeCita approved these changes

2022-09-27 21:23 UTC, merged