translation(CSS): web/css/css_grid_layout
webdoky/content pull request #717
Opened 2022-09-18 11:43 UTC by undead404

Оригінальний вміст: [CSS Grid Layout@MDN](https://developer.mozilla.org/en-us/docs/Web/CSS/CSS_Grid_Layout), [сирці CSS Grid Layout@GitHub](https://github.com/mdn/content/blob/main/files/en-us/web/css/css_grid_layout/index.md)

2022-09-22 19:55 UTC, undead404 commented
Без змін

2022-09-23 14:41 UTC, undead404 commented
Без змін

2022-09-25 13:55 UTC, undead404 commented
Без змін

2022-09-30 06:37 UTC, undead404 commented
Оновлено

2022-10-05 11:14 UTC, KlashReik commented on files/uk/web/css/css_grid_layout/index.md
> +Приклад нижче демонструє сітку триколонкової доріжки, в котрій нові ряди створюються щонайменше зі 100 пікселями, а щонайбільше - з auto. Елементи розташовані на сітці за допомогою розташування на ос
```suggestion
Приклад нижче демонструє сітку триколонкової доріжки, в котрій нові ряди створюються щонайменше зі 100 пікселями, а щонайбільше - з auto. Елементи розміщені на сітці за допомогою розташування на основі ліній.
```

2022-10-08 12:01 UTC, AdriandeCita commented on files/uk/web/css/css_grid_layout/index.md
> +**Сіткове компонування CSS** чудово справляється з поділом сторінки на основні ділянки й визначенням взаємин між частинами контрольної панелі, збудованої з примітивів HTML, щодо розмірів, положення й
```suggestion
**Сіткове компонування CSS** чудово справляється з поділом сторінки на основні ділянки, чи визначенням взаємин між частинами інтерфейсу, збудованого з примітивів HTML, в термінах розмірів, положення й нашарування.
```

2022-10-08 12:01 UTC, AdriandeCita commented on files/uk/web/css/css_grid_layout/index.md
> +Подібно до таблиць, сіткове компонування дає авторові змогу шикувати елементи в колонки й ряди. Проте за допомогою сітки CSS, на противагу таблиці, чимало видів компонування можливо чи легше реалізув
```suggestion
Подібно до таблиць, сіткове компонування дає авторові змогу шикувати елементи в колонки й ряди. Проте сітки CSS також дають змогу реалізувати чимало видів компонування, які значно складніше (або взагалі неможливо) виконати за допомогою таблиць. Наприклад, дочірні елементи контейнера сітки можуть розташовуватися так, що вони насправді перекриваються й нашаровуються, подібно до елементів, розташованих за допомогою CSS `position`.
```

2022-10-08 12:07 UTC, AdriandeCita requested changes
Пропоную трохи переформулювати

2022-10-10 21:03 UTC, undead404 commented on files/uk/web/css/css_grid_layout/index.md
> +Подібно до таблиць, сіткове компонування дає авторові змогу шикувати елементи в колонки й ряди. Проте за допомогою сітки CSS, на противагу таблиці, чимало видів компонування можливо чи легше реалізув
Ну ок, але навіщо тут згадувати `position`?

2022-10-10 21:17 UTC, AdriandeCita commented on files/uk/web/css/css_grid_layout/index.md
> +Подібно до таблиць, сіткове компонування дає авторові змогу шикувати елементи в колонки й ряди. Проте за допомогою сітки CSS, на противагу таблиці, чимало видів компонування можливо чи легше реалізув
для однозначної вказівки на `position` при зберіганні твого формулювання. Можна натомість сказати так, щоб це краще перетиналося з `position` (хоча мені наявність слова "позиціонованих" здається не зовсім достатньо для цього, але ймовірно це суб'єктив)
```suggestion
Подібно до таблиць, сіткове компонування дає авторові змогу шикувати елементи в колонки й ряди. Проте сітки CSS також дають змогу реалізувати чимало видів компонування, які значно складніше (або взагалі неможливо) виконати за допомогою таблиць. Наприклад, дочірні елементи контейнера сітки можуть розташовуватися так, що вони насправді перекриваються й нашаровуються, подібно до елементів, позиціонованих за допомогою CSS.
```

2022-10-13 06:15 UTC, undead404 commented
Прийнято, конфлікт вирішено

2022-10-16 14:05 UTC, merged