translation(CSS): web/css/vertical-align
webdoky/content pull request #719
Opened 2022-09-18 13:57 UTC by undead404

Оригінальний вміст: [vertical-align@MDN](https://developer.mozilla.org/en-us/docs/Web/CSS/vertical-align), [сирці vertical-align@GitHub](https://github.com/mdn/content/blob/main/files/en-us/web/css/vertical-align/index.md)

2022-09-22 19:55 UTC, undead404 commented
Без змін

2022-09-23 14:42 UTC, undead404 commented
Без змін

2022-09-25 11:38 UTC, AdriandeCita commented on files/uk/web/css/vertical-align/index.md
> +### Вертикальне шикування в стройових рамках
```suggestion
### Вертикальне шикування в рамках рядка
```

2022-09-25 11:39 UTC, AdriandeCita requested changes
Невеличке зауваження

2022-09-25 13:56 UTC, undead404 commented on files/uk/web/css/vertical-align/index.md
> +### Вертикальне шикування в стройових рамках
Тоді отак.

```suggestion
### Вертикальне шикування в рядкових рамках
```

2022-09-25 13:56 UTC, undead404 commented on files/uk/web/css/vertical-align/index.md
> +{{EmbedLiveSample("vertykalne-shykuvannia-v-stroiovykh-ramkakh", '100%', 160, "", "")}}
```suggestion
{{EmbedLiveSample("vertykalne-shykuvannia-v-riadkovykh-ramkakh", '100%', 160, "", "")}}
```

2022-09-27 21:25 UTC, merged