translation(CSS): web/css/css_transitions/using_css_transitions
webdoky/content pull request #720
Opened 2022-09-18 14:45 UTC by undead404

Оригінальний вміст: [Using CSS transitions@MDN](https://developer.mozilla.org/en-us/docs/Web/CSS/CSS_Transitions/Using_CSS_transitions), [сирці Using CSS transitions@GitHub](https://github.com/mdn/content/blob/main/files/en-us/web/css/css_transitions/using_css_transitions/index.md)

2022-09-22 19:58 UTC, undead404 commented
Оновлено

2022-09-23 14:42 UTC, undead404 commented
Без змін

2022-09-25 13:56 UTC, undead404 commented
Без змін

2022-09-27 21:36 UTC, AdriandeCita commented on files/uk/web/css/css_transitions/using_css_transitions/index.md
> +  - : Задає функцію, котра визначає, як обчислюються проміжні значення властивостей. _Функції хронометражу_ визначають, як обраховуються проміжні значення переходу. Більшість [функцій хронометражу](/
трохи уточнень, плюс дещо розбавив `...задані шляхом задання... що задає...`
```suggestion
  - : Задає функцію, котра визначає, як обчислюються проміжні значення властивостей. _Функції хронометражу_ визначають, як обраховуються проміжні значення переходу. Більшість [функцій хронометражу](/uk/docs/Web/CSS/easing-function) можуть бути задані шляхом опису графіка відповідної функції, що задає чотири точки, по яких будується кубічна крива Безьє. Також можна обрати пом'якшення зі [Шпаргалки функцій пом'якшення](https://easings.net/uk).
```

2022-09-27 21:41 UTC, AdriandeCita commented on files/uk/web/css/css_transitions/using_css_transitions/index.md
> +Переходи – чудовий інструмент, аби зробити речі куди плавнішими на вигляд без потреби будь-що робити з функціональністю JavaScript. Про це – наступний приклад.
```suggestion
Переходи – чудовий інструмент, аби зробити речі куди плавнішими на вигляд, без потреби будь-що робити з функціональністю JavaScript. Про це – наступний приклад.
```

2022-09-27 21:43 UTC, AdriandeCita requested changes
пара невеличких зауважень

2022-10-01 20:57 UTC, AdriandeCita approved these changes

2022-10-01 20:57 UTC, merged