translation(CSS): web/css/css_animations/using_css_animations
webdoky/content pull request #722
Opened 2022-09-19 12:51 UTC by undead404

Оригінальний вміст: [Using CSS animations@MDN](https://developer.mozilla.org/en-us/docs/Web/CSS/CSS_Animations/Using_CSS_animations), [сирці Using CSS animations@GitHub](https://github.com/mdn/content/blob/main/files/en-us/web/css/css_animations/using_css_animations/index.md)

2022-09-20 08:20 UTC, valeryfourin requested changes
На мій погляд все ок. 
Дуже гарне використання різних конструкцій української мови)
Перший раз побачила порівняння "штибу", звучить автентично)

2022-09-20 08:20 UTC, valeryfourin commented on files/uk/web/css/css_animations/using_css_animations/index.md
> +У цьому, третьому прикладі, задаються три анімації, але лише дві тривалості й дві кількості ітерацій. В таких випадках, коли в списку недостатньо значень, аби надати кожній анімації окреме, присвоєнн
```suggestion
У цьому, третьому прикладі, задаються три анімації, але лише дві тривалості й дві кількості ітерацій. У таких випадках, коли в списку недостатньо значень, аби надати кожній анімації окреме, присвоєння значень йде від першого елемента до останнього в доступному списку, а потім продовжується від першого. Таким чином, `fadeInOut` отримує тривалість `2.5s`, `moveLeft300px` отримує тривалість `5s`, що є останнім значенням в списку значень тривалості. Присвоєння значень тривалості далі перестрибує на перше значення; `bounce`, таким чином, отримує тривалість `2.5s`. Значення кількості ітерацій (та інші задані значення властивостей) присвоюються так само.
```

2022-09-20 08:20 UTC, valeryfourin commented on files/uk/web/css/css_animations/using_css_animations/index.md
> +Щоб анімація повторювалася, треба додати властивість {{cssxref("animation-iteration-count")}}, котра вказує на те, скільки разів треба повторити анімацію. В цьому випадку використаймо `infinite`, аби
```suggestion
Щоб анімація повторювалася, треба додати властивість {{cssxref("animation-iteration-count")}}, котра вказує на те, скільки разів треба повторити анімацію. У цьому випадку використаймо `infinite`, аби анімація повторювалася нескінченно:
```

2022-09-20 08:20 UTC, valeryfourin commented on files/uk/web/css/css_animations/using_css_animations/index.md
> +Чому? Бо подія `animationstart` спрацьовує, щойно почалась анімація, а в нашому випадку це відбувається до спрацювання нашого коду. Тож почнімо анімацію самі, встановивши клас елемента зі стилем, що
```suggestion
Чому? Бо подія `animationstart` спрацьовує, щойно почалась анімація, а в нашому випадку це відбувається до спрацювання нашого коду. Тож почнімо анімацію самі, встановивши клас елемента зі стилем, що, зрештою, анімується.
```
"Зрештою" - вставне слово

2022-09-20 23:34 UTC, AdriandeCita commented on files/uk/web/css/css_animations/using_css_animations/index.md
> +Зверніть увагу, що анімації штибу цієї можуть призвести до того, що сторінка стане ширшою за вікно браузера. Аби цього уникнути цієї проблеми, слід помістити анімований у контейнер, і цьому контейнер
```suggestion
Зверніть увагу, що анімації штибу цієї можуть призвести до того, що сторінка стане ширшою за вікно браузера. Аби цього уникнути цієї проблеми, слід помістити анімований елемент у контейнер, і цьому контейнеру задати {{cssxref("overflow")}}`:hidden`.
```

2022-09-20 23:38 UTC, AdriandeCita commented on files/uk/web/css/css_animations/using_css_animations/index.md
> +- Started: elapsed time is 0
```suggestion
- Почалося: час, що минув – 0
```

2022-09-20 23:38 UTC, AdriandeCita commented on files/uk/web/css/css_animations/using_css_animations/index.md
> +- New loop started at time 3.01200008392334
```suggestion
- Новий цикл почався після 3.01200008392334
```

2022-09-20 23:38 UTC, AdriandeCita commented on files/uk/web/css/css_animations/using_css_animations/index.md
> +- New loop started at time 6.00600004196167
```suggestion
- Новий цикл почався після 6.00600004196167
```

2022-09-20 23:39 UTC, AdriandeCita commented on files/uk/web/css/css_animations/using_css_animations/index.md
> +- Ended: elapsed time is 9.234000205993652
```suggestion
- Скінчилося: час, що минув – 9.234000205993652
```

2022-09-20 23:41 UTC, AdriandeCita commented on files/uk/web/css/css_animations/using_css_animations/index.md
> +> **Примітка:** Частина старих браузерів (до 2017 року) могли потребувати префіксів; жваві приклади, котрі для перегляду треба клацнути, включають синтаксис із префіксом `-webkit`.
Я знайшов іще пару суттєвих нюансів нижче, тож внесу і цю зміну
```suggestion
> **Примітка:** Частина старих браузерів (до 2017 року) могли потребувати префіксів; живі приклади, котрі для перегляду треба клацнути, включають синтаксис із префіксом `-webkit`.
```

2022-09-20 23:41 UTC, AdriandeCita requested changes
декілька зауважень

2022-09-21 07:32 UTC, AdriandeCita approved these changes

2022-09-21 07:32 UTC, merged