translation(CSS): web/css/margin
webdoky/content pull request #724
Opened 2022-09-20 07:28 UTC by undead404

Оригінальний вміст: [margin@MDN](https://developer.mozilla.org/en-us/docs/Web/CSS/margin), [сирці margin@GitHub](https://github.com/mdn/content/blob/main/files/en-us/web/css/margin/index.md)

2022-09-23 14:43 UTC, undead404 commented
Без змін

2022-09-25 13:59 UTC, undead404 commented
Без змін

2022-09-27 22:12 UTC, AdriandeCita commented on files/uk/web/css/margin/index.md
> +Верхній та нижній зовнішні відступи елементів іноді стягуються в один відступ, рівний більшому з двох відступів. Більше подробиць – у [Майстерності зі стягування берегів](/uk/docs/Web/CSS/CSS_Box_Mod
Мастерінг тут означає "вивчення, опанування", буквально - "набуття майстерності". Також пропоную переглянути термін `collapsing`.
```suggestion
Верхній та нижній зовнішні відступи елементів іноді стягуються в один відступ, рівний більшому з двох відступів. Більше подробиць – у розділі [Освоєння явища складання берегів](/uk/docs/Web/CSS/CSS_Box_Model/Mastering_margin_collapsing).
```

2022-09-27 22:13 UTC, AdriandeCita commented on files/uk/web/css/margin/index.md
> +- [Стягування берегів](/uk/docs/Web/CSS/CSS_Box_Model/Mastering_margin_collapsing)
```suggestion
- [Опанування явища складання берегів](/uk/docs/Web/CSS/CSS_Box_Model/Mastering_margin_collapsing)
```

2022-09-27 22:13 UTC, AdriandeCita requested changes
Щодо термінології

2022-09-30 06:43 UTC, undead404 commented
Оновлено

2022-10-01 20:58 UTC, AdriandeCita approved these changes

2022-10-01 20:58 UTC, merged