translation(CSS): web/css/flex
webdoky/content pull request #727
Opened 2022-09-21 06:59 UTC by undead404

Оригінальний вміст: [flex@MDN](https://developer.mozilla.org/en-us/docs/Web/CSS/flex), [сирці flex@GitHub](https://github.com/mdn/content/blob/main/files/en-us/web/css/flex/index.md)

2022-09-22 20:01 UTC, undead404 commented
Без змін

2022-09-23 14:43 UTC, undead404 commented
Без змін

2022-09-28 21:20 UTC, AdriandeCita commented on files/uk/web/css/flex/index.md
> +[Властивість-скорочення](/uk/docs/Web/CSS/Shorthand_properties) [CSS](/uk/docs/Web/CSS) **`flex`** (гнучкий шнур) задає те, як гнучкий _елемент_ зростатиме чи скорочуватиметься для заповнення доступн
Пропоную взяти дещо нейтральніший переклад. Шнур видається занадто далеким і від вебу загалом, і від концепції гнучких блоків зокрема
```suggestion
[Властивість-скорочення](/uk/docs/Web/CSS/Shorthand_properties) [CSS](/uk/docs/Web/CSS) **`flex`** (гнутися) задає те, як гнучкий _елемент_ зростатиме чи скорочуватиметься для заповнення доступного в гнучкому контейнері простору.
```

2022-09-28 21:24 UTC, AdriandeCita requested changes
По-перше, зауваження щодо допоміжного перекладу.
По-друге - в оригінальному файлі присутні свіжі зміни

2022-09-30 06:44 UTC, undead404 commented
Оновлено

2022-10-02 10:34 UTC, AdriandeCita approved these changes

2022-10-02 10:34 UTC, merged