translation(CSS): web/css/_colon_nth-child
webdoky/content pull request #728
Opened 2022-09-21 08:13 UTC by undead404

Оригінальний вміст: [:nth-child()@MDN](https://developer.mozilla.org/en-us/docs/Web/CSS/:nth-child), [сирці :nth-child()@GitHub](https://github.com/mdn/content/blob/main/files/en-us/web/css/_colon_nth-child/index.md)

2022-09-22 20:02 UTC, undead404 commented
Без змін

2022-09-23 14:44 UTC, undead404 commented
Без змін

2022-09-28 21:30 UTC, AdriandeCita commented on files/uk/web/css/_colon_nth-child/index.md
> +#### Result
```suggestion
#### Результат
```

2022-09-28 21:30 UTC, AdriandeCita approved these changes

2022-09-28 21:30 UTC, AdriandeCita requested changes
Невеличке зауваження

2022-10-02 10:35 UTC, merged