translation(CSS): web/css/text-overflow
webdoky/content pull request #729
Opened 2022-09-21 10:57 UTC by undead404

Оригінальний вміст: [text-overflow@MDN](https://developer.mozilla.org/en-us/docs/Web/CSS/text-overflow), [сирці text-overflow@GitHub](https://github.com/mdn/content/blob/main/files/en-us/web/css/text-overflow/index.md)

2022-09-22 20:03 UTC, undead404 commented
Без змін

2022-09-23 14:44 UTC, undead404 commented
Без змін

2022-09-28 21:34 UTC, AdriandeCita commented on files/uk/web/css/text-overflow/index.md
> +Властивість [CSS](/uk/docs/Web/CSS) **`text-overflow`** (переповнення текстом) задає те, як користувачів повідомляють про прихований вміст, що переливається через край. Він може бути обрізаний, може
Я не зустрічав щоб ellipsis перекладали як еліпс
```suggestion
Властивість [CSS](/uk/docs/Web/CSS) **`text-overflow`** (переповнення текстом) задає те, як користувачів повідомляють про прихований вміст, що переливається через край. Він може бути обрізаний, може бути показана трикрапка ('`…`') чи якийсь особливий рядок.
```

2022-09-28 21:36 UTC, AdriandeCita commented on files/uk/web/css/text-overflow/index.md
> +- функція `fade()`, котрій передається {{cssxref("&lt;length&gt;")}} чи {{cssxref("&lt;percentage&gt;")}} для контролю довжини шляху зникнення
ого, я знову дізнався щось нове)

2022-09-28 21:37 UTC, AdriandeCita commented on files/uk/web/css/text-overflow/index.md
> +- `ellipsis` (еліпс)
```suggestion
- `ellipsis` (трикрапка)
```

2022-09-28 21:45 UTC, AdriandeCita commented on files/uk/web/css/text-overflow/index.md
> +Властивість [CSS](/uk/docs/Web/CSS) **`text-overflow`** (переповнення текстом) задає те, як користувачів повідомляють про прихований вміст, що переливається через край. Він може бути обрізаний, може
справді, в деяких словниках зустрічається. Також зустрічається пряма калька "еліпсис".
Пропоную еліпс залишити для "ellipse", а для перекладу "ellipsis" використовувати або "еліпсис", або більш специфічний термін "трикрапка" (підозрюю, можуть бути колізії з еліпсисами в мовах штибу китайської, де трикрапка може не мати сенсу)

2022-09-28 21:45 UTC, AdriandeCita commented on files/uk/web/css/text-overflow/index.md
> +  - : Це ключове слово покаже еліпс (`'…'`, `U+2026 HORIZONTAL ELLIPSIS`), що представлятиме обрізаний текст. Еліпс демонструється всередині [області вмісту](/uk/docs/Web/CSS/CSS_Box_Model/Introducti
Тут треба буде оновити термінологію, якщо ми прийдемо до іншого перекладу

2022-09-28 21:48 UTC, AdriandeCita requested changes
Щодо термінології

2022-09-30 06:47 UTC, undead404 commented on files/uk/web/css/text-overflow/index.md
> +  - : Це ключове слово покаже еліпс (`'…'`, `U+2026 HORIZONTAL ELLIPSIS`), що представлятиме обрізаний текст. Еліпс демонструється всередині [області вмісту](/uk/docs/Web/CSS/CSS_Box_Model/Introducti
```suggestion
  - : Це ключове слово покаже трикрапку (`'…'`, `U+2026 HORIZONTAL ELLIPSIS`), що представлятиме обрізаний текст. Трикрапка демонструється всередині [області вмісту](/uk/docs/Web/CSS/CSS_Box_Model/Introduction_to_the_CSS_box_model), зменшуючи кількість показаного тексту. Якщо простору для виведення трикрапки недостатньо, вона обрізається.
```

2022-09-30 06:48 UTC, undead404 commented
Ну, ніби з трикрапкою працює

2022-10-02 10:36 UTC, AdriandeCita approved these changes

2022-10-02 10:36 UTC, merged