translation(CSS): web/css/color_value
webdoky/content pull request #731
Opened 2022-09-22 09:09 UTC by undead404

Оригінальний вміст: [&lt;color>@MDN](https://developer.mozilla.org/en-us/docs/Web/CSS/color_value), [сирці &lt;color>@GitHub](https://github.com/mdn/content/blob/main/files/en-us/web/css/color_value/index.md)

2022-09-22 20:05 UTC, undead404 commented
Без змін

2022-09-23 14:45 UTC, undead404 commented
Без змін

2022-09-27 10:58 UTC, valeryfourin requested changes

2022-09-27 10:58 UTC, valeryfourin commented on files/uk/web/css/color_value/index.md
> +Іменовані кольори – нечутливі до регістру символів ідентифікатори, що представляють певні кольори, як то `red`, `blue`, `black` чи `lightseagreen`. Попри те, що імена більш-менш описують відповідні ї
```suggestion
Іменовані кольори – нечутливі до регістру символів ідентифікатори, що представляють певні кольори, як то `red`, `blue`, `black` чи `lightseagreen`. Попри те, що імена більш-менш описують відповідні їм кольори, ці імена, по суті, є штучними, без строго обґрунтування їх вибору.
```

2022-09-27 10:58 UTC, valeryfourin commented on files/uk/web/css/color_value/index.md
> +Кольори RGB можуть бути виражені як шістнадцятковим (з префіксом `#`), так функційним (`rgb()`, `rgba()`) записами.
```suggestion
Кольори RGB можуть бути виражені як шістнадцятковим (з префіксом `#`), так і функційним (`rgb()`, `rgba()`) записами.
```

2022-09-27 10:58 UTC, valeryfourin commented on files/uk/web/css/color_value/index.md
> +  - : Як само як в HSL: `H` (hue – відтінок) – це {{cssxref("&lt;angle&gt;", "кут")}} на кольоровому колі, заданий у специфікації [кольору CSS (англ.)](https://drafts.csswg.org/css-color/#the-hsl-not
```suggestion
  - : Так само як в HSL: `H` (hue – відтінок) – це {{cssxref("&lt;angle&gt;", "кут")}} на кольоровому колі, заданий у специфікації [кольору CSS (англ.)](https://drafts.csswg.org/css-color/#the-hsl-notation) в `deg` – градусах, `rad` – радіанах, `grad` – градах чи `turn` – обертах. Коли записаний як {{cssxref("&lt;number&gt;")}} без одиниць, це тлумачиться як градуси, як зазначено в специфікації [Колір CSS, рівень 3](https://drafts.csswg.org/css-color-3/#hsl-color). За визначенням червоний = 0° = 360°, а решта кольорів розкидані по колу, тож зелений = 120°, синій = 240° тощо. Оскільки це `<angle>`, то значення є неявно циклічними, тож -120deg=240deg, 480deg=120deg, -1turn=1turn тощо.
```

2022-09-27 10:58 UTC, valeryfourin commented on files/uk/web/css/color_value/index.md
> +> **Примітка:** Зверніть увагу, що ці ключові слова є _нечутливими до регістру_, але представлені тут зі змішаним написанням з міркувань прочитності.
'читабельний' не використовуємо через російський суфікс?

2022-09-27 10:58 UTC, valeryfourin commented on files/uk/web/css/color_value/index.md
> +- За допомогою функційного запису {{cssxref("color_value/color","color()")}}, аби задати колір в одному з багатьох наперед визначених або власному кольоровому просторі.
```suggestion
- За допомогою функційного запису {{cssxref("color_value/color","color()")}}, аби задати колір в одному з багатьох наперед визначених або власних кольорових просторах.
```

2022-09-27 10:58 UTC, valeryfourin commented on files/uk/web/css/color_value/index.md
> +- Частина загальновживаних властивостей, котрі використовують цей тип даних: {{Cssxref("color")}}, {{Cssxref("background-color")}}, {{Cssxref("border-color")}}, {{Cssxref("box-shadow")}}, {{Cssxref("
```suggestion
- Кілька загальновживаних властивостей, котрі використовують цей тип даних: {{Cssxref("color")}}, {{Cssxref("background-color")}}, {{Cssxref("border-color")}}, {{Cssxref("box-shadow")}}, {{Cssxref("outline-color")}}, {{Cssxref("text-shadow")}}
```

2022-09-27 21:30 UTC, undead404 commented on files/uk/web/css/color_value/index.md
> +> **Примітка:** Зверніть увагу, що ці ключові слова є _нечутливими до регістру_, але представлені тут зі змішаним написанням з міркувань прочитності.
Так. Власне, за цим слідкує LanguageTool

2022-09-29 21:50 UTC, AdriandeCita commented on files/uk/web/css/color_value/index.md
> +/* Whitespace syntax */
```suggestion
/* Запис із пробілами */
```

2022-09-29 21:50 UTC, AdriandeCita commented on files/uk/web/css/color_value/index.md
> +/* Percentage value for alpha */
```suggestion
/* Відсоткове значення альфа */
```

2022-09-30 06:49 UTC, undead404 commented on files/uk/web/css/color_value/index.md
> +- За допомогою функційного запису {{cssxref("color_value/color","color()")}}, аби задати колір в одному з багатьох наперед визначених або власному кольоровому просторі.
```suggestion
- За допомогою функційного запису {{cssxref("color_value/color","color()")}}, аби задати колір в одному з багатьох наперед визначених кольорових просторів, або ж власному.
```

2022-09-30 06:55 UTC, undead404 commented
Оновлено

2022-09-30 07:10 UTC, valeryfourin approved these changes

2022-09-30 07:11 UTC, merged