update(JS): web/javascript/reference/global_objects/array
webdoky/content pull request #736
Opened 2022-09-22 09:37 UTC by undead404

Оригінальний вміст: [Array (масив)@MDN](https://developer.mozilla.org/en-us/docs/Web/JavaScript/Reference/Global_Objects/Array), [сирці Array (масив)@GitHub](https://github.com/mdn/content/blob/main/files/en-us/web/javascript/reference/global_objects/array/index.md)

Нові зміни:
- [mdn/content@e1f571e](https://github.com/mdn/content/commit/e1f571eced916f60ca387ecb562271f6235beb5c)
- [mdn/content@968e6f1](https://github.com/mdn/content/commit/968e6f1f3b6f977a09e116a0ac552459b741eac3)

2022-09-22 10:25 UTC, AdriandeCita approved these changes

2022-09-22 10:26 UTC, AdriandeCita requested changes
Свіжі зміни https://github.com/mdn/content/pull/20530/files#diff-24d0aab1f8d007cc2fac950232b782271f892761ed5a9c9a6e1f72a5d7ccbe90

2022-09-23 11:45 UTC, undead404 commented
Оновлено

2022-09-23 14:40 UTC, AdriandeCita approved these changes

2022-09-23 14:40 UTC, merged