update(JS): web/javascript/reference/global_objects/string
webdoky/content pull request #741
Opened 2022-09-22 10:10 UTC by undead404

Оригінальний вміст: [String@MDN](https://developer.mozilla.org/en-us/docs/Web/JavaScript/Reference/Global_Objects/String), [сирці String@GitHub](https://github.com/mdn/content/blob/main/files/en-us/web/javascript/reference/global_objects/string/index.md)

Нові зміни:
- [mdn/content@dde5b6f](https://github.com/mdn/content/commit/dde5b6fc81cd6f96d12c910e2d5f2f3431647ab0)
- [mdn/content@9b38f88](https://github.com/mdn/content/commit/9b38f886d21c5d0a428f58acb20c4d0fc6c2e098)
- [mdn/content@968e6f1](https://github.com/mdn/content/commit/968e6f1f3b6f977a09e116a0ac552459b741eac3)

2022-09-22 10:33 UTC, AdriandeCita approved these changes

2022-09-22 10:34 UTC, AdriandeCita requested changes
Свіжі зміни https://github.com/mdn/content/pull/20965/files#diff-0f99acf740a1307fa04182aa4a817f019dd1a1aeef8da6f085ebc7352a268b4b

2022-09-23 11:54 UTC, undead404 commented
Оновлено

2022-09-23 14:42 UTC, AdriandeCita approved these changes

2022-09-23 14:42 UTC, merged