update(HTML): web/html/element/select
webdoky/content pull request #756
Opened 2022-09-22 11:06 UTC by undead404

Оригінальний вміст: [&lt;select>: Елемент вибору HTML@MDN](https://developer.mozilla.org/en-us/docs/Web/HTML/Element/select), [сирці &lt;select>: Елемент вибору HTML@GitHub](https://github.com/mdn/content/blob/main/files/en-us/web/html/element/select/index.md)

Нові зміни:
- [mdn/content@f230873](https://github.com/mdn/content/commit/f23087355761587655698b39f48ed96a3454f86a)

2022-09-22 11:36 UTC, AdriandeCita approved these changes

2022-09-22 11:37 UTC, AdriandeCita requested changes
Свіжі зміни https://github.com/mdn/content/commit/03c5110696fb433c13f3ccf63266d8affe446d8a#diff-48ecd4a5e65b3a0ee0385ab9f66bebf581ab44d359d350f5e4630981870820c8

2022-09-23 12:57 UTC, undead404 commented
Оновлено

2022-09-23 14:45 UTC, AdriandeCita approved these changes

2022-09-23 14:45 UTC, merged