update(JS): web/javascript/reference/global_objects/json/parse
webdoky/content pull request #769
Opened 2022-09-23 14:07 UTC by undead404

Оригінальний вміст: [JSON.parse()@MDN](https://developer.mozilla.org/en-us/docs/Web/JavaScript/Reference/Global_Objects/JSON/parse), [сирці JSON.parse()@GitHub](https://github.com/mdn/content/blob/main/files/en-us/web/javascript/reference/global_objects/json/parse/index.md)

Нові зміни:
- [mdn/content@9010030](https://github.com/mdn/content/commit/9010030c393cad71250a3813d29b4afc799f639f)

2022-09-23 14:56 UTC, AdriandeCita commented on files/uk/web/javascript/reference/global_objects/json/parse/index.md
> +  - : Якщо є функцією — цей параметр прописує те, як початкове, сконструйоване під час розбору, значення слід трансформувати перед його поверненням. Non-callable values are ignored. The function is c
```suggestion
  - : Якщо є функцією — цей параметр прописує те, як початкове, сконструйоване під час розбору, значення слід трансформувати перед його поверненням. Невикличні значення ігноруються. Функція викликається з наступними аргументами:
```

2022-09-23 14:57 UTC, AdriandeCita commented on files/uk/web/javascript/reference/global_objects/json/parse/index.md
> +      - : The key associated with the value.
```suggestion
      - : Ключ, який відповідає значенню.
```

2022-09-23 14:58 UTC, AdriandeCita commented on files/uk/web/javascript/reference/global_objects/json/parse/index.md
> +      - : The value produced by parsing.
```suggestion
      - : Значення, випродуковане під час розбору.
```

2022-09-23 15:16 UTC, AdriandeCita requested changes
Троха зауважень

2022-09-24 09:01 UTC, undead404 commented on files/uk/web/javascript/reference/global_objects/json/parse/index.md
> +      - : The value produced by parsing.
```suggestion
      - : Значення – результат розбору.
```

2022-09-24 09:02 UTC, undead404 commented on files/uk/web/javascript/reference/global_objects/json/parse/index.md
> +Зверніть увагу, що `reviver` спрацьовує після розбору значення. Тому, наприклад, числа в тексті JSON вже будуть перетворені на числа JavaScript, в процесі чого можуть втратити частину точності. Для п
Тут не це мається на увазі: формат – довільний, але це має бути точний формат. Чи не так?

2022-09-24 09:03 UTC, undead404 commented
Згодний не з усім

2022-09-24 16:34 UTC, AdriandeCita commented on files/uk/web/javascript/reference/global_objects/json/parse/index.md
> +      - : The value produced by parsing.
най буде

2022-09-24 17:00 UTC, AdriandeCita commented on files/uk/web/javascript/reference/global_objects/json/parse/index.md
> +Зверніть увагу, що `reviver` спрацьовує після розбору значення. Тому, наприклад, числа в тексті JSON вже будуть перетворені на числа JavaScript, в процесі чого можуть втратити частину точності. Для п
Ну, по-перше, мені здалося, що тут явне посилання на властивості формату BigInt. Нагадаю, у статті про структури даних (яку я переглядав незадовго перед цією) BigInt описується так:

> The BigInt type is a numeric primitive in JavaScript that can represent integers with arbitrary precision

Тобто з точки зору змісту здається логічнішим сприймати оригінальне речення так `...other appropriate (arbitrary precision formats)`, ніж просто перекладати по порядку. Та й збіг "appropriate arbitrary" виглядає дещо нелогічно.

А по-друге - трохи забагато прикметників підряд (`...іншого відповідного довільного точного...`), які хотілося б трохи рознести для простішого сприйняття

2022-09-25 12:38 UTC, undead404 commented
Погодився

2022-09-25 13:13 UTC, merged