translation(CSS): web/css/line-height
webdoky/content pull request #771
Opened 2022-09-23 16:59 UTC by undead404

Оригінальний вміст: [line-height@MDN](https://developer.mozilla.org/en-us/docs/Web/CSS/line-height), [сирці line-height@GitHub](https://github.com/mdn/content/blob/main/files/en-us/web/css/line-height/index.md)

2022-09-29 22:09 UTC, AdriandeCita commented on files/uk/web/css/line-height/index.md
> +<div class="box red">
```suggestion
<div class="box red">
  <h1>
```

2022-09-29 22:17 UTC, AdriandeCita commented on files/uk/web/css/line-height/index.md
> +Властивість [CSS](/uk/docs/Web/CSS) **`line-height`** (висота строю) задає висоту рамок строю. Вона загальновживана для задання відстані між рядками тексту. Для елементів блокового рівня вона задає м
Тут і далі: чи є сенс в якомусь іншому терміні, якщо це буквально висота рядка, і використовується ця властивість саме для тексту? Ну теоретично можливо через набір із "line-height + vertical-align + inline-block", але за наявності флексів люди не повинні таким страждати
```suggestion
Властивість [CSS](/uk/docs/Web/CSS) **`line-height`** (висота рядка) задає висоту рамок рядка. Вона загальновживана для задання відстані між рядками тексту. Для елементів блокового рівня вона задає мінімальну висоту рядкових рамок всередині елемента. Для не[заміщених](/uk/docs/Web/CSS/Replaced_element) рядкових елементів вона задає висоту, котра використовується для обчислення висоти рамок рядка.
```

2022-09-29 22:18 UTC, AdriandeCita requested changes
Питання щодо термінології

2022-09-30 06:58 UTC, undead404 commented on files/uk/web/css/line-height/index.md
> +Властивість [CSS](/uk/docs/Web/CSS) **`line-height`** (висота строю) задає висоту рамок строю. Вона загальновживана для задання відстані між рядками тексту. Для елементів блокового рівня вона задає м
Я просто трохи спантеличений тим, що в рядка раптом з‘явилися якісь рамки, тому такий термін як варіант. До того ж ми текст шикуємо, шикуємо стрій, так би мовити :-)

2022-10-02 11:12 UTC, AdriandeCita commented on files/uk/web/css/line-height/index.md
> +Властивість [CSS](/uk/docs/Web/CSS) **`line-height`** (висота строю) задає висоту рамок строю. Вона загальновживана для задання відстані між рядками тексту. Для елементів блокового рівня вона задає м
Не певен, що "рамки строю" звучить суттєво краще, ніж "рамки рядка"... Але окей, ось аргументація:

- По-перше, у тексту є якщо не рамки, то принаймні певні направляючі (які функційно цілком собі рамки, якщо розглядати текст як одновимірне утворення - але заглиблюватись так далеко наші відвідувачі точно не будуть :grin: ):
![image](https://user-images.githubusercontent.com/11510394/193450341-76a416bf-5a2a-4a4d-86f4-ee6049217f31.png)
- По-друге - ми не шикуємо літери в рядку, як в строю. Думаю, це можливо в окремих випадках (наприклад, якщо розбити рядок спанами, і кожному з них почати прописувати `vertical-align`), Але усталено всі літери в рядку вже вишикувані відносно `baseline`. А те, що ми називаємо `text-align` - це вирівнювання кінців рядка. Навіть якщо розглядати шикування на рівні тексту як двовимірного прямокутного утворення - воно все одно так не працює, бо ширина літер у шрифті не однакова. Єдиний спосіб по справжньому вишикувати текст в обох координатах - це задіяти моноширинний шрифт (що ніяк не залежить від використання `text-align`). І якщо термін "шикування" іще можна прийняти як стилістичний зворот, люди нас все ще зрозуміють - хоча б по аналогії з флексовим `align-items`, - то розширювати цю практику на інші типографські терміни на підставі нашого перекладу `text-align` здається зайвим

2022-10-02 14:01 UTC, undead404 commented on files/uk/web/css/line-height/index.md
> +Властивість [CSS](/uk/docs/Web/CSS) **`line-height`** (висота строю) задає висоту рамок строю. Вона загальновживана для задання відстані між рядками тексту. Для елементів блокового рівня вона задає м
Гаразд, ти переміг, значить, є рамки

2022-10-03 21:16 UTC, AdriandeCita commented on files/uk/web/css/line-height/index.md
> +  - : Задане {{cssxref("&lt;length&gt;")}} використовується при обчисленні висоти рамок строю. Значення, задані в одиницях **em**, можуть призвести до неочікуваних результат (дивіться приклад нижче).
```suggestion
  - : Задане {{cssxref("&lt;length&gt;")}} використовується при обчисленні висоти рамок рядка. Значення, задані в одиницях **em**, можуть призвести до неочікуваних результат (дивіться приклад нижче).
```

2022-10-03 21:17 UTC, AdriandeCita commented on files/uk/web/css/line-height/index.md
> +  - : Робить висоту строю рівною висоті вмісту поточного блока.
```suggestion
  - : Робить висоту рядка рівною висоті вмісту поточного блока.
```

2022-10-03 21:17 UTC, AdriandeCita commented on files/uk/web/css/line-height/index.md
> +Для вмісту головного абзацу слід задавати `line-height` мінімальне значення `1.5`. Це може допомогти людям з розладами зору, а також когнітивними негараздами, як то дислексією. Якщо сторінка масштабо
```suggestion
Для вмісту головного абзацу слід задавати `line-height` мінімальне значення `1.5`. Це може допомогти людям з розладами зору, а також когнітивними негараздами, як то дислексією. Якщо сторінка масштабована для збільшення розміру тексту, то використання значення без одиниць вимірювання дає змогу мати певність, що висота рядка масштабується пропорційно.
```

2022-10-03 21:17 UTC, AdriandeCita commented on files/uk/web/css/line-height/index.md
> +/* Усі правила нижче дають однакову результівну висоту строю */
```suggestion
/* Усі правила нижче дають однакову результівну висоту рядка */
```

2022-10-03 21:18 UTC, AdriandeCita requested changes
Оновив інші входження, які залишались

2022-10-04 10:43 UTC, undead404 commented
Прийняв

2022-10-05 19:39 UTC, merged