translation(CSS): web/css/text-decoration
webdoky/content pull request #773
Opened 2022-09-23 18:01 UTC by undead404

Оригінальний вміст: [text-decoration@MDN](https://developer.mozilla.org/en-us/docs/Web/CSS/text-decoration), [сирці text-decoration@GitHub](https://github.com/mdn/content/blob/main/files/en-us/web/css/text-decoration/index.md)

2022-09-29 22:21 UTC, AdriandeCita approved these changes

2022-09-29 22:21 UTC, AdriandeCita requested changes
Є свіжі зміни https://github.com/mdn/content/commit/44439c7254c9da1797e4438bade0f8e8984cbc35#diff-dfceca5d46ee055cc367360eed1ddffe14acc033c4e3e43ae469282716394855

2022-09-30 07:04 UTC, undead404 commented
Оновлено

2022-10-02 11:18 UTC, AdriandeCita approved these changes

2022-10-02 11:18 UTC, merged