translation(CSS): web/css/css_grid_layout/basic_concepts_of_grid_layout
webdoky/content pull request #775
Opened 2022-09-24 10:35 UTC by undead404

Оригінальний вміст: [Basic concepts of grid layout@MDN](https://developer.mozilla.org/en-us/docs/Web/CSS/CSS_Grid_Layout/Basic_Concepts_of_Grid_Layout), [сирці Basic concepts of grid layout@GitHub](https://github.com/mdn/content/blob/main/files/en-us/web/css/css_grid_layout/basic_concepts_of_grid_layout/index.md)

2022-09-30 07:07 UTC, undead404 commented
Оновлено

2022-10-05 11:20 UTC, KlashReik commented on files/uk/web/css/css_grid_layout/basic_concepts_of_grid_layout/index.md
> +[Сіткове компонування CSS](/uk/docs/Web/CSS/CSS_Grid_Layout) запроваджує в CSS двовимірну сіткову систему. Сітки можуть використовуватися для компонування головних частин сторінки чи невеликих елемен
```suggestion
[Сіткове компонування CSS](/uk/docs/Web/CSS/CSS_Grid_Layout) запроваджує в CSS двовимірну сіткову систему. Сітки можуть використовуватися для компонування головних частин сторінки чи невеликих елементів користувацького інтерфейсу. Ця стаття знайомить з Сітковим компонуванням CSS та новою термінологією, що є частиною специфікації Сіткового компонування CSS 1 рівня. Можливості, показані в цьому огляді, надалі пояснюються докладніше в решті цього посібника.
```

2022-10-05 11:44 UTC, KlashReik commented on files/uk/web/css/css_grid_layout/basic_concepts_of_grid_layout/index.md
> +У цьому прикінцевому прикладі змішуються доріжки з абсолютним розміром та одиниці `fr`. Перша доріжка - 500 пікселів, тож від доступного простору віднімається фіксована ширина. Решта простору ділитьс
```suggestion
У цьому заключному прикладі змішуються доріжки з абсолютним розміром та одиниці `fr`. Перша доріжка - 500 пікселів, тож від доступного простору віднімається фіксована ширина. Решта простору ділиться натроє й пропорційно присвоюється двом гнучким доріжкам.
```

2022-10-05 11:48 UTC, KlashReik commented on files/uk/web/css/css_grid_layout/basic_concepts_of_grid_layout/index.md
> +Запис повторення може застосовуватися як частина переліку доріжок. В наступному прикладі – сітка з 20-піксельною доріжкою на початку, після якої – повторюваний розділ з 6 доріжок `1fr`, а потім – кін
```suggestion
Запис повторення може застосовуватися для частини переліку доріжок. В наступному прикладі – сітка з 20-піксельною доріжкою на початку, після якої – повторюваний розділ з 6 доріжок `1fr`, а потім – кінцева 20-піксельна доріжка.
```

2022-10-08 10:08 UTC, AdriandeCita commented on files/uk/web/css/css_grid_layout/basic_concepts_of_grid_layout/index.md
> +![Використання Сіткового значника в DevTools для перегляду сітки](1-grid-inspector.png)
Пропоную перефразувати у щось зрозуміліше
```suggestion
![Використання підсвітки сіток в DevTools для перегляду сітки](1-grid-inspector.png)
```

2022-10-08 10:14 UTC, AdriandeCita commented on files/uk/web/css/css_grid_layout/basic_concepts_of_grid_layout/index.md
> +Відтепер всі безпосередні нащадки стали сітковими елементами. У веббраузері не буде помітна жодна різниця щодо того, як ці елементи виводилися до перетворення їх на сітку, адже сітка створила для еле
"To inspect" тут фактично означає "відкрити в інспекторі"... Пропоную перефразувати з явною вказівкою на девтулс
```suggestion
Відтепер всі безпосередні нащадки стали сітковими елементами. У веббраузері не буде помітна жодна різниця щодо того, як ці елементи виводилися до перетворення їх на сітку, адже сітка створила для елементів одноколонкову сітку. На цьому етапі може мати зміст скористатися [Сітковим дослідником (англ.)](https://firefox-source-docs.mozilla.org/devtools-user/page_inspector/how_to/examine_grid_layouts/index.html), доступним як частина Інструментів розробника Firefox. Якщо переглянути цей приклад за допомогою інструментів розробника Firefox, то буде помітна невелика піктограма біля значення `grid`. Клацніть на неї – і сітка елемента з'явиться у вікні браузера.
```

2022-10-08 10:19 UTC, AdriandeCita commented on files/uk/web/css/css_grid_layout/basic_concepts_of_grid_layout/index.md
> +Відтепер всі безпосередні нащадки стали сітковими елементами. У веббраузері не буде помітна жодна різниця щодо того, як ці елементи виводилися до перетворення їх на сітку, адже сітка створила для еле
![image](https://user-images.githubusercontent.com/11510394/194702664-dced2e4a-9199-4df6-be2e-606a024a5e40.png)
До речі, в офіційній локалізації інспектор перекладено саме як інспектор. Оновив коментар з урахуванням цього факту

2022-10-08 10:26 UTC, AdriandeCita commented on files/uk/web/css/css_grid_layout/basic_concepts_of_grid_layout/index.md
> +Великі сітки з багатьма доріжками можуть використовувати запис `repeat()`, котрий дає змогу повторювати всі чи розділ переліку доріжок. Наприклад, таке визначення сітки:
```suggestion
Великі сітки з багатьма доріжками можуть використовувати запис `repeat()`, котрий дає змогу повторити весь перелік доріжок чи його частину. Наприклад, таке визначення сітки:
```

2022-10-08 10:29 UTC, AdriandeCita commented on files/uk/web/css/css_grid_layout/basic_concepts_of_grid_layout/index.md
> +### Неявні та явні сітки
Просто стилістика, зазвичай базовий термін вказують першим, а його похідні лексеми - наступними
```suggestion
### Явні та неявні сітки
```

2022-10-08 10:34 UTC, AdriandeCita commented on files/uk/web/css/css_grid_layout/basic_concepts_of_grid_layout/index.md
> +Якщо щось розташовується поза визначеною сіткою, або якщо у зв'язку з кількість вмісту необхідно більше доріжок, то сітка створює ряди й колонки неявної сітки. Такі доріжки усталено автоматично каліб
```suggestion
Якщо щось розташовується поза визначеною сіткою, або якщо у зв'язку з кількістю вмісту необхідно більше доріжок, то сітка створює ряди й колонки неявної сітки. Такі доріжки усталено автоматично калібруються, завдяки чому їх розмір заснований на вмісті, що в них є.
```

2022-10-08 11:00 UTC, AdriandeCita commented on files/uk/web/css/css_grid_layout/basic_concepts_of_grid_layout/index.md
> +Елемент `box2` тепер перекривається з `box1`, він виводиться поверх, адже стоїть пізніше в коді.
Давай вже краще так, бо "`box2` ... перекривається `box1`" і "він [`box2`] виводиться поверх" радше протирічять одне одному
```suggestion
Елемент `box2` тепер перекриває `box1`, він виводиться поверх, адже стоїть пізніше в коді.
```

2022-10-08 11:05 UTC, AdriandeCita commented on files/uk/web/css/css_grid_layout/basic_concepts_of_grid_layout/index.md
> +Порядок, в якому нагромаджуються елементи, можна контролювати за допомогою властивості `z-index` – як із будь-якими розташованими елементами. Можна дати `box2` менший `z-index`, ніж в `box1`, і він б
Тут маються на увазі елементи, що мають явно вказану властивість `position`, відмінну від `static`
```suggestion
Порядок, в якому нагромаджуються елементи, можна контролювати за допомогою властивості `z-index` – як із будь-якими нестатично позиціонованими елементами. Можна дати `box2` менший `z-index`, ніж в `box1`, і він буде показаний під `box1`.
```

2022-10-08 11:10 UTC, AdriandeCita requested changes
є декілька зауважень

2022-10-10 21:06 UTC, undead404 commented on files/uk/web/css/css_grid_layout/basic_concepts_of_grid_layout/index.md
> +В цьому випадку вкладена сітка не має взаємин з батьківською. Як це можна помітити у прикладі, вона не успадкувала {{cssxref("gap")}} предка
```suggestion
В цьому випадку вкладена сітка не має взаємин з батьківською. Як це можна помітити у прикладі, вона не успадкувала {{cssxref("gap")}} предка, і лінії у вкладеній сітці не шикуються за сітками батьківської сітки.
```

2022-10-12 17:51 UTC, AdriandeCita commented on files/uk/web/css/css_grid_layout/basic_concepts_of_grid_layout/index.md
> +В цьому випадку вкладена сітка не має взаємин з батьківською. Як це можна помітити у прикладі, вона не успадкувала {{cssxref("gap")}} предка
мені здається, краще вже так, ніж "за сітками батьківської сітки"
```suggestion
В цьому випадку вкладена сітка не має взаємин з батьківською. Як це можна помітити у прикладі, вона не успадкувала {{cssxref("gap")}} предка, і лінії у вкладеній сітці не шикуються до ліній батьківської сітки.
```

2022-10-13 06:17 UTC, undead404 commented
Прийнято

2022-10-16 14:05 UTC, AdriandeCita approved these changes

2022-10-16 14:06 UTC, merged