translation(HTML): web/html/element/br
webdoky/content pull request #777
Opened 2022-09-24 12:12 UTC by undead404

Оригінальний вміст: [&lt;br>: The Line Break element@MDN](https://developer.mozilla.org/en-us/docs/Web/HTML/Element/br), [сирці &lt;br>: The Line Break element@GitHub](https://github.com/mdn/content/blob/main/files/en-us/web/html/element/br/index.md)

2022-10-02 12:31 UTC, AdriandeCita commented on files/uk/web/html/element/br/index.md
> +Елемент `<br>` має єдине, чітко визначене призначення: утворювати розрив рядка в блоку тексту. Таким чином, він не має власних розмірів чи власного візуального представлення, і можна небагато що змін
```suggestion
Елемент `<br>` має єдине, чітко визначене призначення: утворювати розрив рядка в блоці тексту. Таким чином, він не має власних розмірів чи власного візуального представлення, і можна небагато що змінити в його оформленні.
```

2022-10-02 12:31 UTC, AdriandeCita commented on files/uk/web/html/element/br/index.md
> +Можна задати елементам `<br>` {{cssxref("margin")}}, аби збільшити відступ між рядками тексту в блоку, проте це є недоброю практикою: слід використовувати властивість {{cssxref("line-height")}}, розр
```suggestion
Можна задати елементам `<br>` {{cssxref("margin")}}, аби збільшити відступ між рядками тексту в блоці, проте це є недоброю практикою: слід використовувати властивість {{cssxref("line-height")}}, розроблену для цієї потреби.
```

2022-10-02 12:32 UTC, AdriandeCita commented on files/uk/web/html/element/br/index.md
> +В наступному прикладі елементи `<br>` застосовуються для утворення розривів рядка між окремими рядками поштової адреси:
Думаю, це можна з чистою совістю спростити
```suggestion
В наступному прикладі елементи `<br>` застосовуються для утворення розривів між окремими рядками поштової адреси:
```

2022-10-02 12:33 UTC, AdriandeCita requested changes
Декілька дрібниць

2022-10-03 21:20 UTC, AdriandeCita requested changes
Є свіжі оновлення https://github.com/mdn/content/commit/bb5e443fad3be7d126732a85155d5776ad977cad#diff-e80cb0c5a7ff5ddc99074339d820f9171876ebe56c230d47570995fe3550aafa

2022-10-04 10:45 UTC, undead404 commented
Оновлено

2022-10-05 19:40 UTC, merged