translation(HTML): web/html/element/table
webdoky/content pull request #797
Opened 2022-09-26 11:50 UTC by undead404

Оригінальний вміст: [&lt;table>: The Table element@MDN](https://developer.mozilla.org/en-us/docs/Web/HTML/Element/table), [сирці &lt;table>: The Table element@GitHub](https://github.com/mdn/content/blob/main/files/en-us/web/html/element/table/index.md)

2022-10-03 21:37 UTC, AdriandeCita approved these changes

2022-10-03 21:37 UTC, AdriandeCita requested changes
Є свіжі зміни, плюс конфлікт

2022-10-04 10:51 UTC, undead404 commented
Зміни – несуттєві, конфлікт – розв‘язано

2022-10-05 19:42 UTC, AdriandeCita requested changes
знову є свіжі зміни, цього разу виглядають більш суттєво https://github.com/mdn/content/commit/a30a908b5a6c05f739e74a8af4505172ce5431c4#diff-2ea1205812f14a6e51f5e575991c27620b89d87172234f66e82c43923c7bd017

2022-10-06 20:54 UTC, undead404 commented
Оновлено

2022-10-06 21:09 UTC, merged