translate web-js-ref-global_objects-array-index
webdoky/content pull request #8
Opened 2021-08-01 18:57 UTC by AdriandeCita

Source content https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array

2021-08-04 08:01 UTC, undead404 requested changes

2021-08-04 08:01 UTC, undead404 commented on files/uk/web/javascript/reference/global_objects/array/index.md
> +  - : Додає один або більше елементів спочатку масиву, і повертає нове значення довжини `length` масиву.
Можливо, замість "спочатку" - "на початку"?

2021-08-07 15:21 UTC, IhorHordiichuk commented on files/uk/web/javascript/reference/global_objects/array/index.md
> +JavaScript клас **`Array`** - це глобальний об'єкт, що використовується при створенні масивів; які, зі свого боку, є високорівневими об'єктами, подібними до списків.
Так, крапко-кому варто замінити на кому та залишити «які є високорівневими». Ще б «при» замінив на «під час»

2021-08-07 15:23 UTC, IhorHordiichuk commented on files/uk/web/javascript/reference/global_objects/array/index.md
> +Масиви &mdash; це подібні до списків об'єкти, чий прототип володіє методами для перебирання елементів та операцій зміни. Ні довжина масиву у JavaScript, ні тип його елементів не являються фіксованими
«лежати» -» «перебувати» «бути розміщеними»

2021-08-07 20:37 UTC, IhorHordiichuk commented on files/uk/web/javascript/reference/global_objects/array/index.md
> +Масиви не можуть використовувати рядок як індекс елементу (так, як це працює в [асоціативному масиві](https://en.wikipedia.org/wiki/Associative_array)), але повинні використовувати цілі числа. Заданн
рядок як індекс елементу -» рядок індексом елемента

2021-08-07 20:39 UTC, IhorHordiichuk commented on files/uk/web/javascript/reference/global_objects/array/index.md
> +**Видалення елементу спочатку масиву**
з початку

2021-08-07 20:40 UTC, IhorHordiichuk commented on files/uk/web/javascript/reference/global_objects/array/index.md
> +**Додавання елементу спочатку масиву**
на початок

2021-08-07 20:47 UTC, IhorHordiichuk commented on files/uk/web/javascript/reference/global_objects/array/index.md
> +Тут немає нічого особливого у JavaScript масивах і властивостях, що призводять до цього. На властивості, що починаються з цифри, не можна посилатися за допомогою крапкової нотації; до них можна досту
«Тут» зайве

2021-08-07 20:48 UTC, IhorHordiichuk commented on files/uk/web/javascript/reference/global_objects/array/index.md
> +У прикладі із `3d`, стрічка `'3d'` *повинна* бути в лапках (бо вона починається з цифри). Але також можливо подавати в лапках також і індекси масиву (наприклад, `years['2']` замість `years[2]`), хоча
стрічка -» рядок

2021-08-07 20:53 UTC, IhorHordiichuk commented on files/uk/web/javascript/reference/global_objects/array/index.md
> +При заданні властивості у масиві JavaScript, коли назва властивості є коректним числовим індексом, і при цьому цей індекс вказує за поточні межі масиву, рушій внесе відповідні зміни до значення власт
і водночас цей індекс

2021-08-07 21:02 UTC, IhorHordiichuk commented on files/uk/web/javascript/reference/global_objects/array/index.md
> +  - : Зображає кількість елементів у масиві.
Тут можна й відображає або показує.

2021-08-07 21:10 UTC, IhorHordiichuk commented on files/uk/web/javascript/reference/global_objects/array/index.md
> +  - : Викликає функцію відносно акумулятора і кожного зі значень масиву (зліва направо) з метою скорочення його до єдиного значення.
Apply — Застосовує функцію до акумулятора

2021-08-07 21:10 UTC, IhorHordiichuk commented on files/uk/web/javascript/reference/global_objects/array/index.md
> +  - : Викликає функцію відносно акумулятора і кожного зі значень масиву (справа наліво) з метою скорочення його до єдиного значення.
Застосовує функцію до акумулятора

2021-08-07 21:13 UTC, IhorHordiichuk commented on files/uk/web/javascript/reference/global_objects/array/index.md
> +  - : Додає один або більше елементів спочатку масиву, і повертає нове значення довжини `length` масиву.
А ліпше «на початок»

2021-08-28 16:33 UTC, AdriandeCita commented on files/uk/web/javascript/reference/global_objects/array/index.md
> +  - : Повертає `true`, якщо кожний з елементів масиву задовольняє подану перевіркову функцію.
Іще одне класне слово, дякую. Я часто використовую `подану`, але `передана` звучить значно ліпше

2021-08-28 16:41 UTC, AdriandeCita commented on files/uk/web/javascript/reference/global_objects/array/index.md
> +JavaScript клас **`Array`** - це глобальний об'єкт, що використовується при створенні масивів; які, зі свого боку, є високорівневими об'єктами, подібними до списків.
гарне зауваження, у мене тут було багато таких неприродніх словосполучень з джаваскриптом, треба по всіх пройтись

2021-08-28 17:00 UTC, AdriandeCita commented
Вніс виправлення згідно зауважень.

2021-08-30 20:40 UTC, merged