translation(HTML): web/html/global_attributes
webdoky/content pull request #808
Opened 2022-09-27 19:22 UTC by undead404

Оригінальний вміст: [Global attributes@MDN](https://developer.mozilla.org/en-us/docs/Web/HTML/Global_attributes), [сирці Global attributes@GitHub](https://github.com/mdn/content/blob/main/files/en-us/web/html/global_attributes/index.md)

2022-10-03 21:41 UTC, AdriandeCita commented on files/uk/web/html/global_attributes/index.md
> +    - `true` чи _порожні рядок_, що вказує, що елемент повинен бути редагованим;
```suggestion
    - `true` чи _порожній рядок_, що вказує, що елемент повинен бути редагованим;
```

2022-10-03 21:55 UTC, AdriandeCita requested changes
дрібниці

2022-10-05 19:44 UTC, AdriandeCita requested changes
Тут також додався новий термін в глосарій https://github.com/mdn/content/commit/a30a908b5a6c05f739e74a8af4505172ce5431c4#diff-0fb9c547a197730ce284762a181b04ec1ab52ee6a853bfd588d6587f15c8a965

2022-10-06 21:01 UTC, undead404 commented
Оновлено

2022-10-06 21:10 UTC, AdriandeCita approved these changes

2022-10-06 21:10 UTC, merged