translation(HTML): web/html/element/link
webdoky/content pull request #836
Opened 2022-09-30 15:48 UTC by undead404

Оригінальний вміст: [&lt;link>: The External Resource Link element@MDN](https://developer.mozilla.org/en-us/docs/Web/HTML/Element/link), [сирці &lt;link>: The External Resource Link element@GitHub](https://github.com/mdn/content/blob/main/files/en-us/web/html/element/link/index.md)

2022-10-04 12:38 UTC, undead404 commented
Оновлено

2022-10-05 20:24 UTC, AdriandeCita commented on files/uk/web/html/element/link/index.md
> +            Елементи <code>&#x3C;script></code>, Worker <code>importScripts</code>
```suggestion
            Елементи <code>&#x3C;script></code>, <code>importScripts</code> для Worker
```

2022-10-05 20:25 UTC, AdriandeCita commented on files/uk/web/html/element/link/index.md
> +        Якщо сервер не дає даних автентифікації сайту походження (шляхом не вказування заголовка HTTP {{HTTPHeader("Access-Control-Allow-Origin")}}), то ресурс буде ославленим, а його використання –
```suggestion
        Якщо сервер не надає даних автентифікації сайту походження (шляхом опускання заголовка HTTP {{HTTPHeader("Access-Control-Allow-Origin")}}), то ресурс буде ославленим, а його використання – обмеженим.
```

2022-10-05 20:31 UTC, AdriandeCita commented on files/uk/web/html/element/link/index.md
> +  - : Містить рядкові метадані – зашифрований в base64 криптографічний геш ресурсу (файлу), котрий браузер має стягнути.
```suggestion
  - : Містить рядкові метадані – закодований в base64 криптографічний геш ресурсу (файлу), котрий браузер має стягнути.
```

2022-10-05 20:40 UTC, AdriandeCita commented on files/uk/web/html/element/link/index.md
> +Користувач може обрати, яку таблицю стилів використовувати, обравши її в меню **Перегляд > Стиль сторінки** menu.
```suggestion
Користувач може обрати, яку таблицю стилів використовувати, обравши її в меню **Перегляд > Стиль сторінки**.
```

2022-10-05 20:48 UTC, AdriandeCita requested changes
Декілька зауважень

2022-10-06 21:05 UTC, undead404 commented
Оновлено

2022-10-06 21:11 UTC, merged