translation(JS): web/javascript/guide/loops_and_iteration
webdoky/content pull request #855
Opened 2022-10-09 10:39 UTC by undead404

Оригінальний вміст: [Loops and iteration@MDN](https://developer.mozilla.org/en-us/docs/Web/JavaScript/Guide/Loops_and_iteration), [сирці Loops and iteration@GitHub](https://github.com/mdn/content/blob/main/files/en-us/web/javascript/guide/loops_and_iteration/index.md)

2022-10-14 21:31 UTC, AdriandeCita commented on files/uk/web/javascript/guide/loops_and_iteration/index.md
> +У прикладі нижче функція містить інструкцію `for`, котра підраховує кількість обраних у прокрутному списку варіантів (елементі [`<select>`](/uk/docs/Web/HTML/Element/select), що дозволяє вибрати декі
```suggestion
У прикладі нижче функція містить інструкцію `for`, котра підраховує кількість обраних варіантів у прокрутному списку (елементі [`<select>`](/uk/docs/Web/HTML/Element/select), що дозволяє вибрати декілька варіантів).
```

2022-10-15 10:11 UTC, AdriandeCita commented on files/uk/web/javascript/guide/loops_and_iteration/index.md
> +- [Інструкція з підписом](#instruktsiia-z-pidpysom)
Нагадую, що це трохи різні labels. Елемент `<label` в HTML ми називаємо підписом, бо його призначення - це підписувати елементи форм. `label:` в JavaScript - це мітка, яка позначає певне місце в коді для керування переходом потоку виконання програми, і функціонально вона подібна до міток в С/ASM (https://uk.wikipedia.org/wiki/%D0%9C%D1%96%D1%82%D0%BA%D0%B0)
```suggestion
- [Інструкція з міткою](#instruktsiia-z-mitkoyu)
```

2022-10-15 10:11 UTC, AdriandeCita commented on files/uk/web/javascript/guide/loops_and_iteration/index.md
> +## Інструкція з підписом
```suggestion
## Інструкція з міткою
```

2022-10-15 10:11 UTC, AdriandeCita commented on files/uk/web/javascript/guide/loops_and_iteration/index.md
> +{{jsxref("statements/label","Підпис")}} дає інструкції ідентифікатор, що дає змогу звертатися до неї деінде в програмі. Наприклад, можна використати підпис для ідентифікації циклу, а потім використат
```suggestion
{{jsxref("statements/label","Мітка")}} дає інструкції ідентифікатор, що дає змогу звертатися до неї деінде в програмі. Наприклад, можна використати мітку для ідентифікації циклу, а потім використати інструкції `break` чи `continue`, аби вказати, коли програма повинна перервати цикл чи продовжити його виконання.
```

2022-10-15 10:11 UTC, AdriandeCita commented on files/uk/web/javascript/guide/loops_and_iteration/index.md
> +Синтаксис інструкції з підписом має наступний вигляд:
```suggestion
Синтаксис інструкції з міткою має наступний вигляд:
```

2022-10-15 10:12 UTC, AdriandeCita commented on files/uk/web/javascript/guide/loops_and_iteration/index.md
> +Значення `label` може бути будь-яким ідентифікатором JavaScript, що не є зарезервованим словом. `statement`, котра ідентифікується підписом, може бути будь-якою інструкцією.
```suggestion
Значення `label` може бути будь-яким ідентифікатором JavaScript, що не є зарезервованим словом. `statement`, котра ідентифікується міткою, може бути будь-якою інструкцією.
```

2022-10-15 10:12 UTC, AdriandeCita commented on files/uk/web/javascript/guide/loops_and_iteration/index.md
> +В цьому прикладі підпис `markLoop` ідентифікує цикл `while`.
```suggestion
В цьому прикладі мітка `markLoop` ідентифікує цикл `while`.
```

2022-10-15 10:12 UTC, AdriandeCita commented on files/uk/web/javascript/guide/loops_and_iteration/index.md
> +- Коли `break` використовується без підпису, вона негайно завершує `while`, `do-while`, `for` або
```suggestion
- Коли `break` використовується без мітки, вона негайно завершує `while`, `do-while`, `for` або
```

2022-10-15 10:13 UTC, AdriandeCita commented on files/uk/web/javascript/guide/loops_and_iteration/index.md
> +- Коли `break` використовується з підписом, вона завершує вказану інструкцію з підписом.
```suggestion
- Коли `break` використовується з міткою, вона завершує вказану інструкцію з міткою.
```

2022-10-15 10:13 UTC, AdriandeCita commented on files/uk/web/javascript/guide/loops_and_iteration/index.md
> +### Приклад 2: переривання за підписом
```suggestion
### Приклад 2: переривання за міткою
```

2022-10-15 10:13 UTC, AdriandeCita commented on files/uk/web/javascript/guide/loops_and_iteration/index.md
> +- Коли `continue` використовується без підпису, вона завершує поточну ітерацію інструкції `while`, `do-while` чи `for` навколо, що має найглибший рівень вкладеності, й продовжує виконання циклу з нас
```suggestion
- Коли `continue` використовується без мітки, вона завершує поточну ітерацію інструкції `while`, `do-while` чи `for` навколо, що має найглибший рівень вкладеності, й продовжує виконання циклу з наступної ітерації. На противагу інструкції `break`, `continue` не завершує виконання всього циклу. В циклі `while` вона перестрибує назад до умови. В циклі `for` вона перестрибує до `increment-expression`.
```

2022-10-15 10:13 UTC, AdriandeCita commented on files/uk/web/javascript/guide/loops_and_iteration/index.md
> +- Коли `continue` використовується з підписом, то застосовується до інструкції циклу, що ідентифікується заданим підписом.
```suggestion
- Коли `continue` використовується з міткою, то застосовується до інструкції циклу, що ідентифікується заданою міткою.
```

2022-10-15 10:14 UTC, AdriandeCita commented on files/uk/web/javascript/guide/loops_and_iteration/index.md
> +Інструкція з підписом `checkiandj` містить інструкцію з підписом `checkj`. Якщо трапилась `continue`, то програма завершує поточну ітерацію `checkj`, і починає наступну. Щоразу, коли трапляється `con
```suggestion
Інструкція з міткою `checkiandj` містить інструкцію з міткою `checkj`. Якщо трапилась `continue`, то програма завершує поточну ітерацію `checkj`, і починає наступну. Щоразу, коли трапляється `continue`, `checkj` повторює виконання, поки її умова не поверне `false`. Коли повернено `false`, завершується решта `checkiandj`, і `checkiandj` повторює своє виконання, поки її умова не поверне `false`. Коли повернено `false`, програма продовжується з інструкції, що стоїть після `checkiandj`.
```

2022-10-15 10:14 UTC, AdriandeCita commented on files/uk/web/javascript/guide/loops_and_iteration/index.md
> +Якби `continue` мала підпис `checkiandj`, програма продовжилася б з верху інструкції `checkiandj`.
```suggestion
Якби `continue` мала мітку `checkiandj`, програма продовжилася б з верху інструкції `checkiandj`.
```

2022-10-15 10:23 UTC, AdriandeCita commented on files/uk/web/javascript/guide/loops_and_iteration/index.md
> +Інструкцію {{jsxref("statements/break","break")}} слід використовувати для завершення циклу чи `switch`, або вкупі з інструкцією з підписом.
```suggestion
Для завершення циклу чи `switch` слід використовувати інструкцію {{jsxref("statements/break","break")}} окремо, або вкупі з інструкцією, позначеною міткою.
```

2022-10-15 10:35 UTC, AdriandeCita commented on files/uk/web/javascript/guide/loops_and_iteration/index.md
> +  `switch` найглибшого рівня вкладеності, що її оточує, і передає контроль виконання до наступної інструкції.
```suggestion
  `switch`, що її оточує, і передає контроль виконання до наступної інструкції.
```

2022-10-15 10:36 UTC, AdriandeCita commented on files/uk/web/javascript/guide/loops_and_iteration/index.md
> +1. Перша форма синтаксису завершує цикл чи `switch` навколо, що має найглибшу вкладеність.
```suggestion
1. Перша форма синтаксису завершує найглибший вкладений цикл чи `switch` навколо.
```

2022-10-15 21:43 UTC, AdriandeCita requested changes
Декілька зауважень, зокрема термінологія.

2022-10-22 13:23 UTC, undead404 commented
Прийняв усе

2022-10-24 20:50 UTC, merged