tramslations(JS): Web/JavaScript/Guide/Working_with_Objects
webdoky/content pull request #856
Opened 2022-10-09 12:12 UTC by AdriandeCita

Оригінальний вміст: [Working with objects@MDN](https://developer.mozilla.org/en-us/docs/Web/JavaScript/Guide/Working_with_Objects), [сирці Working with objects@GitHub](https://github.com/mdn/content/blob/main/files/en-us/web/javascript/guide/working_with_objects/index.md)

2022-10-10 14:39 UTC, undead404 requested changes

2022-10-10 14:39 UTC, undead404 commented on files/uk/web/javascript/guide/working_with_objects/index.md
> +- або означені всередині [об'єктних ініціалізаторів](#object_initializers),
```suggestion
- або означені всередині [об'єктних ініціалізаторів](#initsializatory-obiektiv),
```

2022-10-10 14:39 UTC, undead404 commented on files/uk/web/javascript/guide/working_with_objects/index.md
> +Все, що потрібно зробити, аби додати гетер чи сетер через [об'єктний ініціалізатор](#object_initializers) — це вказати перед методом гетера префікс `get`, а перед сетером, відповідно, — `set`. Звісно
```suggestion
Все, що потрібно зробити, аби додати гетер чи сетер через [об'єктний ініціалізатор](#initsializatory-obiektiv) — це вказати перед методом гетера префікс `get`, а перед сетером, відповідно, — `set`. Звісно, метод гетера не повинен приймати вхідних параметрів, тоді як метод сетера повинен очікувати на один і лише один параметр (нове значення для встановлення). Приміром:
```

2022-10-10 14:39 UTC, undead404 commented on files/uk/web/javascript/guide/working_with_objects/index.md
> +myObj.c = 50;         //   <-- А тут діє метод сетера c(x) method
```suggestion
myObj.c = 50;         //   <-- А тут діє метод сетера c(x)
```

2022-10-10 14:39 UTC, undead404 commented on files/uk/web/javascript/guide/working_with_objects/index.md
> +Яку з цих двох форм обрати — залежить від стилю програмування та конкретного завдання під руками. Якщо для означення прототипу вже використано об'єктний ініціалізатор — скоріш за все варто обрати пер
```suggestion
Яку з цих двох форм обрати — залежить від стилю програмування та конкретного завдання під руками. Якщо для означення прототипу вже використано об'єктний ініціалізатор — скоріш за все, варто обрати першу форму. Ця форма компактніша і дещо природніша. Проте, якщо потрібно додати гетери й сетери постфактум, оскільки не ми писали прототип, чи конкретний об'єкт — єдиним варіантом залишається друга форма. Друга форма, ймовірно, найкраще ілюструє динамічну природу JavaScript — хоча це може робити код складнішим для прочитання і розуміння.
```

2022-10-10 14:39 UTC, undead404 commented on files/uk/web/javascript/guide/working_with_objects/index.md
> +Можна видалити не успадковану властивість, шляхом використання оператора [`delete`](/uk/docs/Web/JavaScript/Reference/Operators/delete). Наступний код ілюструє, як видалити властивість:
```suggestion
Неуспадковану властивість можна видалити шляхом використання оператора [`delete`](/uk/docs/Web/JavaScript/Reference/Operators/delete). Наступний код ілюструє, як видалити властивість:
```

2022-10-10 14:39 UTC, undead404 commented on files/uk/web/javascript/guide/working_with_objects/index.md
> +Більше інформації про оператори порівняння можна знайти у розділі [оператори порівняння](/uk/docs/Web/JavaScript/Reference/Operators#equality_operators).
```suggestion
Більше інформації про оператори порівняння можна знайти у розділі [оператори порівняння](/uk/docs/Web/JavaScript/Reference/Operators#equality_operators).
```
```suggestion
Більше інформації про оператори порівняння можна знайти у розділі [операторів рівності](/uk/docs/Web/JavaScript/Reference/Operators#operatory-rivnosti).
```

2022-10-10 14:39 UTC, undead404 commented on files/uk/web/javascript/guide/working_with_objects/index.md
> +- Для заглиблення в тему, прочитайте про [Успадкування та ланцюжок прототипів](/uk/docs/Web/JavaScript/Inheritance_and_the_prototype_chain).
```suggestion
- Для заглиблення в тему прочитайте про [Успадкування та ланцюжок прототипів](/uk/docs/Web/JavaScript/Inheritance_and_the_prototype_chain).
```

2022-10-10 21:02 UTC, AdriandeCita commented on files/uk/web/javascript/guide/working_with_objects/index.md
> +Не присвоєні властивості об'єкта є {{jsxref("undefined", "невизначеними")}} (а не [`null` (пустими)](/uk/docs/Web/JavaScript/Reference/Operators/null)).
ммм, напевне ти правий, краще це в additions додати

2022-10-11 05:18 UTC, undead404 commented
Одне зауваження пропущено

2022-10-12 16:10 UTC, AdriandeCita commented
@undead404 твоя правда, дякую, прийняв

2022-10-12 20:10 UTC, merged