update(JS): web/javascript/reference/global_objects/array/sort
webdoky/content pull request #864
Opened 2022-10-09 19:15 UTC by undead404

Оригінальний вміст: [Array.prototype.sort()@MDN](https://developer.mozilla.org/en-us/docs/Web/JavaScript/Reference/Global_Objects/Array/sort), [сирці Array.prototype.sort()@GitHub](https://github.com/mdn/content/blob/main/files/en-us/web/javascript/reference/global_objects/array/sort/index.md)

Нові зміни:
- [mdn/content@eff56eb](https://github.com/mdn/content/commit/eff56eb74d327a74032f52418ab15e202f019f9a)

2022-10-12 18:35 UTC, AdriandeCita commented on files/uk/web/javascript/reference/global_objects/array/sort/index.md
> +Метод `reverse()` є [узагальненим](/uk/docs/Web/JavaScript/Reference/Global_Objects/Array#uzahalneni-metody-masyvu). Він лишень очікує, що значення `this` матиме властивість `length`, а також властив
```suggestion
Метод `sort()` є [узагальненим](/uk/docs/Web/JavaScript/Reference/Global_Objects/Array#uzahalneni-metody-masyvu). Він лишень очікує, що значення `this` матиме властивість `length`, а також властивості з цілочисловими ключами.
```

2022-10-12 18:35 UTC, AdriandeCita requested changes
Невеличке зауваження

2022-10-12 20:08 UTC, undead404 commented on files/uk/web/javascript/reference/global_objects/array/sort/index.md
> +Метод `reverse()` є [узагальненим](/uk/docs/Web/JavaScript/Reference/Global_Objects/Array#uzahalneni-metody-masyvu). Він лишень очікує, що значення `this` матиме властивість `length`, а також властив
Я хз, ця помилка є в оригіналі, точно будемо виправляти?

2022-10-13 06:06 UTC, undead404 commented on files/uk/web/javascript/reference/global_objects/array/sort/index.md
> +Метод `reverse()` є [узагальненим](/uk/docs/Web/JavaScript/Reference/Global_Objects/Array#uzahalneni-metody-masyvu). Він лишень очікує, що значення `this` матиме властивість `length`, а також властив
Ого ти міць!

2022-10-13 06:06 UTC, undead404 commented
Прийнято

2022-10-24 14:56 UTC, undead404 commented
Оновлено

2022-10-24 20:53 UTC, AdriandeCita approved these changes

2022-10-24 20:53 UTC, merged