update(JS): web/javascript/reference/global_objects/array/push
webdoky/content pull request #874
Opened 2022-10-10 07:44 UTC by undead404

Оригінальний вміст: [Array.prototype.push()@MDN](https://developer.mozilla.org/en-us/docs/Web/JavaScript/Reference/Global_Objects/Array/push), [сирці Array.prototype.push()@GitHub](https://github.com/mdn/content/blob/main/files/en-us/web/javascript/reference/global_objects/array/push/index.md)

Нові зміни:
- [mdn/content@eff56eb](https://github.com/mdn/content/commit/eff56eb74d327a74032f52418ab15e202f019f9a)

2022-10-12 21:40 UTC, AdriandeCita commented on files/uk/web/javascript/reference/global_objects/array/push/index.md
> +// There's no length property, so the length is 0
```suggestion
// Тут немає властивості `length`, тому значення довжини вважається за 0
```

2022-10-12 21:40 UTC, AdriandeCita requested changes
Пропущений текст

2022-10-13 06:10 UTC, undead404 commented
Прийнято

2022-10-24 20:54 UTC, AdriandeCita approved these changes

2022-10-26 08:56 UTC, merged