translation(JS): web/javascript/reference/global_objects/promise/then
webdoky/content pull request #885
Opened 2022-10-12 19:57 UTC by undead404

Оригінальний вміст: [Promise.prototype.then()@MDN](https://developer.mozilla.org/en-us/docs/Web/JavaScript/Reference/Global_Objects/Promise/then), [сирці Promise.prototype.then()@GitHub](https://github.com/mdn/content/blob/main/files/en-us/web/javascript/reference/global_objects/promise/then/index.md)

2022-10-15 22:04 UTC, AdriandeCita commented on files/uk/web/javascript/reference/global_objects/promise/then/index.md
> +> **Примітка:** Якщо один з аргументів пропущений, або не є функцією, то `then` не вистачатиме обробників, але ніяких помилок породжено не буде. Якщо `Promise`, метод `then` викликається, набуває ста
```suggestion
> **Примітка:** Якщо один з аргументів пропущений, або не є функцією, то `then` не вистачатиме обробників, але ніяких помилок породжено не буде. Якщо `Promise`, метод `then` якого викликається, набуває стану (`fulfillment` чи `rejection`), для якого `then` не має обробника, то повернений проміс набуває остаточного стану оригінального `Promise`, на якому викликали `then`.
```

2022-10-15 22:08 UTC, AdriandeCita commented on files/uk/web/javascript/reference/global_objects/promise/then/index.md
> +Щойно {{jsxref("Promise")}} сповнюється чи відхиляється, відповідна функція-обробник (`onFulfilled` або `onRejected`) викликається **асинхронно** (планується на наступну ітерацію потоку). Поведінка ф
В оригіналі "in the current thread loop"
```suggestion
Щойно {{jsxref("Promise")}} сповнюється чи відхиляється, відповідна функція-обробник (`onFulfilled` або `onRejected`) викликається **асинхронно** (планується у поточній ітерації потоку). Поведінка функції-обробника відповідає конкретному наборові правил. Якщо функція-обробник:
```

2022-10-15 22:17 UTC, AdriandeCita commented on files/uk/web/javascript/reference/global_objects/promise/then/index.md
> +Крім цього, ланцюжки можна використовувати для реалізації однієї функції з API на основі Promise на основі інакшої такої функції.
"...на основі Promise на основі..."
```suggestion
Крім цього, ланцюжки можна використовувати для реалізації однієї функції з API, заснованому на Promise, на основі інакшої такої функції.
```

2022-10-15 22:18 UTC, AdriandeCita commented on files/uk/web/javascript/reference/global_objects/promise/then/index.md
> +  // більшої обробки.
```suggestion
  // додаткової обробки.
```

2022-10-15 22:22 UTC, AdriandeCita commented on files/uk/web/javascript/reference/global_objects/promise/then/index.md
> +  const noop = () => {}; // буквально
```suggestion
  const noop = () => {}; // буквально ("noop" – це скорочення від "no operation")
```

2022-10-15 22:22 UTC, AdriandeCita requested changes
Декілька зауважень

2022-10-22 13:25 UTC, undead404 commented
Прийнято

2022-10-25 20:34 UTC, AdriandeCita approved these changes

2022-10-25 20:34 UTC, merged