translation(JS): web/javascript/reference/operators/delete
webdoky/content pull request #890
Opened 2022-10-13 12:55 UTC by undead404

Оригінальний вміст: [delete operator@MDN](https://developer.mozilla.org/en-us/docs/Web/JavaScript/Reference/Operators/delete), [сирці delete operator@GitHub](https://github.com/mdn/content/blob/main/files/en-us/web/javascript/reference/operators/delete/index.md)

2022-10-15 22:30 UTC, AdriandeCita commented on files/uk/web/javascript/reference/operators/delete/index.md
> +Оператор `delete` прибирає з об'єкта задану властивість. У випадку успішного видалення – повертає `true`, інакше – `false`. Всупереч поширеному уявленню (мабуть, пов'язаному з іншими мовами програмув
```suggestion
Оператор `delete` прибирає з об'єкта задану властивість. У випадку успішного видалення – повертає `true`, інакше – `false`. Всупереч поширеному уявленню (мабуть, пов'язаному з іншими мовами програмування, як то [delete у C++](https://docs.microsoft.com/cpp/cpp/delete-operator-cpp?view=msvc-170)), оператор `delete` **не має** стосунку до безпосереднього звільнення пам'яті. Керування пам'яттю виконується в непрямий спосіб, шляхом розриву посилань. Дивіться подробиці на сторінці [керування пам'яттю](/uk/docs/Web/JavaScript/Memory_Management).
```

2022-10-15 22:32 UTC, AdriandeCita commented on files/uk/web/javascript/reference/operators/delete/index.md
> +Оператор `delete` прибирає з об'єкта задану властивість. У випадку успішного видалення – повертає `true`, інакше – `false`. Всупереч поширеному уявленню (мабуть, пов'язаному з іншими мовами програмув
нагадую, що "управління" - це про "центральне управління Приватбанку у Вінницькій обл", а процес краще називати керуванням

2022-10-15 22:35 UTC, AdriandeCita commented on files/uk/web/javascript/reference/operators/delete/index.md
> +### Кросбраузерні примітки
Українською це звучить радше як "примітки, які відображаються в різних браузерах" :slightly_smiling_face: 
```suggestion
### Примітки щодо кросбраузерності
```

2022-10-15 22:40 UTC, AdriandeCita commented on files/uk/web/javascript/reference/operators/delete/index.md
> +За потреби використати упорядкований асоціативний масив з підтримкою старих середовищ виконання слід використовувати об'єкт {{jsxref("Map")}}, якщо він доступний (за допомогою поліфілу, наприклад), а
неочевидно, чи це масив має властивість містити, чи об'єкти
```suggestion
За потреби використати упорядкований асоціативний масив з підтримкою старих середовищ виконання слід використовувати об'єкт {{jsxref("Map")}}, якщо він доступний (за допомогою поліфілу, наприклад), або імітувати таку структуру за допомогою двох окремих масивів (одного з ключами та іншого зі значеннями), або робити масив з об'єктами, які містять одну властивістю тощо.
```

2022-10-15 22:41 UTC, AdriandeCita commented on files/uk/web/javascript/reference/operators/delete/index.md
> +> **Примітка:** Наступний приклад використовує можливості, доступні лише в нестрогому режимі, як то неявне створення глобальних змінних та видалення ідентифікаторів, але заборонені в строгому.
```suggestion
> **Примітка:** Наступний приклад використовує можливості, доступні лише в нестрогому режимі, але заборонені в строгому, як то неявне створення глобальних змінних та видалення ідентифікаторів.
```

2022-10-15 22:45 UTC, AdriandeCita commented on files/uk/web/javascript/reference/operators/delete/index.md
> +Коли властивість позначена як неналаштовувана, `delete` won't have any effect, and will return `false`. In strict mode, this will raise a `TypeError`.
```suggestion
Коли властивість позначена як неналаштовувана, `delete` не дасть жодного ефекту і поверне `false`. У суворому режимі така дія викине помилку `TypeError`.
```

2022-10-15 22:47 UTC, AdriandeCita commented on uk_spelling_additions.txt
>  кросбраузерність
```suggestion
кросбраузерність
кросбраузерності
```

2022-10-15 22:48 UTC, AdriandeCita requested changes
Залишив декілька зауважень.

Плюс питання в чаті про додаткові суфікси в "неналаштовуваний".

2022-10-22 13:27 UTC, undead404 commented
Прийнято

2022-10-25 20:41 UTC, AdriandeCita requested changes
Глянь будь ласка іще до можливого спрощення слова "налаштовуваний", там можна щонайменше один суфікс прибрати, лишень треба перевірити як LanguageTool відреагує

2022-11-04 19:27 UTC, KlashReik commented on files/uk/web/javascript/reference/operators/delete/index.md
> +**Оператор `delete`** усуває властивість з об'єкта. Якщо значення властивості саме є об'єктом і на цей об'єкт більше немає посилань, то об'єкт з цієї властивості, врешті решт, автоматично звільняєтьс
```suggestion
**Оператор `delete`** усуває властивість з об'єкта. Якщо значення властивості саме є об'єктом і на цей об'єкт більше немає посилань, то об'єкт з цієї властивості, врешті-решт, автоматично звільняється.
```

2022-11-04 19:35 UTC, KlashReik commented on files/uk/web/javascript/reference/operators/delete/index.md
> +- `delete` діє лише на власні властивості. Якщо властивість з таким само іменем існує в ланцюжку прототипів об'єкта, то після видалення власної властивості об'єкт використовуватиме властивість з ланц
```suggestion
- `delete` діє лише на власні властивості. Якщо властивість з ідентичним іменем існує в ланцюжку прототипів об'єкта, то після видалення власної властивості об'єкт використовуватиме властивість з ланцюжка прототипів.
```

2022-11-04 19:46 UTC, KlashReik commented on files/uk/web/javascript/reference/operators/delete/index.md
> +Згідно з сучасною специфікацією ECMAScript, порядок обробки властивостей об'єкта – чітко визначений та стабільний в усіх реалізаціях. Проте у випадку Internet Explorer, коли `delete` застосовується д
Я б змінив на "ідентичним іменем", проте як хочете)

2022-11-04 19:47 UTC, KlashReik commented on files/uk/web/javascript/reference/operators/delete/index.md
> +За потреби використати упорядкований асоціативний масив з підтримкою старих середовищ виконання слід використовувати об'єкт {{jsxref("Map")}}, якщо він доступний (за допомогою поліфілу, наприклад), а
```suggestion
За потреби використати упорядкований асоціативний масив з підтримкою старих середовищ виконання слід використовувати об'єкт {{jsxref("Map")}}, якщо він доступний (за допомогою поліфілу, наприклад), або імітувати таку структуру за допомогою двох окремих масивів (одного з ключами та іншого зі значеннями), або робити масив з об'єктами, які містять одну властивість тощо.
```

2022-11-04 19:50 UTC, KlashReik commented on files/uk/web/javascript/reference/operators/delete/index.md
> +В наступному прикладі видаляється власна властивість об'єкта, коли властивість з таким само іменем доступна в ланцюжку прототипів:
Втретє зустрічається "таким само", тож, як на мене, варто один із них замінити синонімом "ідентичним" :))

2022-11-06 13:11 UTC, undead404 commented on files/uk/web/javascript/reference/operators/delete/index.md
> +В наступному прикладі видаляється власна властивість об'єкта, коли властивість з таким само іменем доступна в ланцюжку прототипів:
Ти про зміни вище?

2022-11-06 13:24 UTC, KlashReik commented on files/uk/web/javascript/reference/operators/delete/index.md
> +Згідно з сучасною специфікацією ECMAScript, порядок обробки властивостей об'єкта – чітко визначений та стабільний в усіх реалізаціях. Проте у випадку Internet Explorer, коли `delete` застосовується д
```suggestion
Згідно з сучасною специфікацією ECMAScript, порядок обробки властивостей об'єкта – чітко визначений та стабільний в усіх реалізаціях. Проте у випадку Internet Explorer, коли `delete` застосовується до властивості, це призводить до дещо плутаної поведінки, котра заважає іншим браузерам використовувати прості об'єкти штибу об'єктних літералів як упорядковані асоціативні масиви. В Explorer, хоч _значення_ властивості справді стає `undefined`, але якщо хтось пізніше знову додасть властивість з ідентичним іменем, то властивість буде ітеруватися за своєю _старою_ позицією – не в кінці послідовності ітерації, як можна було б очікувати унаслідок її видалення та повторного додавання.
```

2022-11-06 13:24 UTC, KlashReik commented on files/uk/web/javascript/reference/operators/delete/index.md
> +В наступному прикладі видаляється власна властивість об'єкта, коли властивість з таким само іменем доступна в ланцюжку прототипів:
```suggestion
В наступному прикладі видаляється власна властивість об'єкта, коли властивість з ідентичним іменем доступна в ланцюжку прототипів:
```

2022-11-07 20:51 UTC, AdriandeCita commented on files/uk/web/javascript/reference/operators/delete/index.md
> +Завжди `true`, окрім випадків, коли властивість є [власною](/uk/docs/Web/JavaScript/Reference/Global_Objects/Object/hasOwn) та [неналаштовуваною](/uk/docs/Web/JavaScript/Reference/Global_Objects/Obje
```suggestion
Завжди `true`, окрім випадків, коли властивість є [власною](/uk/docs/Web/JavaScript/Reference/Global_Objects/Object/hasOwn) та [неналаштовною](/uk/docs/Web/JavaScript/Reference/Global_Objects/Object/defineProperty#atrybut-configurable) – тоді, якщо виконання відбувається не в суворому режимі, буде повернено `false`.
```

2022-11-07 20:51 UTC, AdriandeCita commented on files/uk/web/javascript/reference/operators/delete/index.md
> +  - : Викидається в [суворому режимі](/uk/docs/Web/JavaScript/Reference/Strict_mode), якщо властивість є власною та неналаштовуваною.
```suggestion
  - : Викидається в [суворому режимі](/uk/docs/Web/JavaScript/Reference/Strict_mode), якщо властивість є власною та неналаштовною.
```

2022-11-07 20:51 UTC, AdriandeCita commented on files/uk/web/javascript/reference/operators/delete/index.md
> +Завдяки тому, що [класи](/uk/docs/Web/JavaScript/Reference/Classes) автоматично отримують суворий режим, а [приватні властивості](/uk/docs/Web/JavaScript/Reference/Classes/Private_class_fields) можна
```suggestion
Завдяки тому, що [класи](/uk/docs/Web/JavaScript/Reference/Classes) автоматично отримують суворий режим, а [приватні властивості](/uk/docs/Web/JavaScript/Reference/Classes/Private_class_fields) можна правомірно використовувати лише в тілах класів, приватні властивості ніколи не можуть бути видалені. Попри те, що `delete identifier` [може спрацювати](#vydalennia-hlobalnykh-vlastyvostei), якщо `identifier` вказує на налаштовну властивість глобального об'єкта, цієї форми слід уникати, ставлячи натомість перед ідентифікатором [`globalThis`](/uk/docs/Web/JavaScript/Reference/Global_Objects/globalThis).
```

2022-11-07 20:52 UTC, AdriandeCita commented on files/uk/web/javascript/reference/operators/delete/index.md
> +- Неналаштовувані властивості не можуть бути прибрані. Серед них – властивості вбудованих об'єктів, як то {{jsxref("Math")}}, {{jsxref("Array")}}, {{jsxref("Object")}}, а також властивості, створені
```suggestion
- Неналаштовні властивості не можуть бути прибрані. Серед них – властивості вбудованих об'єктів, як то {{jsxref("Math")}}, {{jsxref("Array")}}, {{jsxref("Object")}}, а також властивості, створені як неналаштовні за допомогою методів штибу {{jsxref("Object.defineProperty()")}}.
```

2022-11-07 20:52 UTC, AdriandeCita commented on files/uk/web/javascript/reference/operators/delete/index.md
> +  - Змінні, оголошені за допомогою {{jsxref("Statements/var", "var")}}, не можуть бути видалені з глобальної області видимості, чи області функції, адже хоч вони могли бути прикріплені до [глобальног
```suggestion
  - Змінні, оголошені за допомогою {{jsxref("Statements/var", "var")}}, не можуть бути видалені з глобальної області видимості, чи області функції, адже хоч вони могли бути прикріплені до [глобального об'єкта](/uk/docs/Glossary/Global_object), та не є налаштовними.
```

2022-11-07 20:52 UTC, AdriandeCita commented on files/uk/web/javascript/reference/operators/delete/index.md
> +// Оскільки використовується var, вона буде позначена як неналаштовувана.
```suggestion
// Оскільки використовується var, вона буде позначена як неналаштовна.
```

2022-11-07 20:52 UTC, AdriandeCita commented on files/uk/web/javascript/reference/operators/delete/index.md
> +// Оскільки var не використовується, вона буде позначена як налаштовувана.
```suggestion
// Оскільки var не використовується, вона буде позначена як налаштовна.
```

2022-11-07 20:53 UTC, AdriandeCita commented on files/uk/web/javascript/reference/operators/delete/index.md
> +// Натомість empCount – не налаштовувана властивість,
```suggestion
// Натомість empCount – не налаштовна властивість,
```

2022-11-07 20:53 UTC, AdriandeCita commented on files/uk/web/javascript/reference/operators/delete/index.md
> +// котрі є неналаштовуваними.
```suggestion
// котрі є неналаштовними.
```

2022-11-07 20:53 UTC, AdriandeCita commented on files/uk/web/javascript/reference/operators/delete/index.md
> +### Видалення неналаштовуваних властивостей
```suggestion
### Видалення неналаштовних властивостей
```

2022-11-07 20:53 UTC, AdriandeCita commented on files/uk/web/javascript/reference/operators/delete/index.md
> +Коли властивість позначена як неналаштовувана, `delete` не дасть жодного ефекту і поверне `false`. У суворому режимі така дія викине помилку `TypeError`.
```suggestion
Коли властивість позначена як неналаштовна, `delete` не дасть жодного ефекту і поверне `false`. У суворому режимі така дія викине помилку `TypeError`.
```

2022-11-07 20:53 UTC, AdriandeCita commented on files/uk/web/javascript/reference/operators/delete/index.md
> +{{jsxref("Statements/var","var")}} створює неналаштовувані властивості, котрі не можна видалити оператором `delete`:
```suggestion
{{jsxref("Statements/var","var")}} створює неналаштовні властивості, котрі не можна видалити оператором `delete`:
```

2022-11-07 20:53 UTC, AdriandeCita commented on files/uk/web/javascript/reference/operators/delete/index.md
> +// ключового слова var, вона позначена як неналаштовувана
```suggestion
// ключового слова var, вона позначена як неналаштовна
```

2022-11-07 20:54 UTC, AdriandeCita commented on files/uk/web/javascript/reference/operators/delete/index.md
> +Якщо глобальна властивість є налаштовуваною (наприклад, створена безпосереднім присвоєнням властивості), то вона може бути видалена, і подальші звертання до неї як до глобальної змінної спричинять {{
```suggestion
Якщо глобальна властивість є налаштовною (наприклад, створена безпосереднім присвоєнням властивості), то вона може бути видалена, і подальші звертання до неї як до глобальної змінної спричинять {{jsxref("ReferenceError")}}.
```

2022-11-07 20:57 UTC, AdriandeCita commented on uk_spelling_additions.txt
> +неналаштовувана
LT мало того, що приймає запропоновану вище форму, та ще й наче не матюкається на її форми з "не-". Я рекомендую перевірити всі, бо я реками міняв лише декілька перших слів, але виглядає обіцяюче.

```suggestion
```

2022-11-07 20:57 UTC, AdriandeCita commented on uk_spelling_additions.txt
> +неналаштовуваних
```suggestion
```

2022-11-07 20:57 UTC, AdriandeCita commented on uk_spelling_additions.txt
> +неналаштовувані
```suggestion
```

2022-11-07 20:57 UTC, AdriandeCita commented on uk_spelling_additions.txt
> +неналаштовуваною
```suggestion
```

2022-11-07 20:58 UTC, AdriandeCita requested changes
Нагадую за спрощену форму, без зайвих суфіксів

2022-12-13 13:20 UTC, undead404 commented
З телефона важко зрозуміти, чи лишились пропозиції, шліфану згодом

2022-12-14 12:02 UTC, AdriandeCita commented on files/uk/web/javascript/reference/operators/delete/index.md
> +// ключового слова var, вона позначена як неналаштовувана
схоже, іще залишилися

2023-01-05 21:19 UTC, AdriandeCita requested changes
Є іще оновлення https://github.com/mdn/content/commit/0f248adcab759bdad247a5dbfb7da12dc32bce59#diff-babaeef129095f2f1452c65de09b8953c088cd5552bd715e60a7e43fe78f8b2e

2023-01-31 17:33 UTC, merged