update(JS): web/javascript/reference/global_objects/string
webdoky/content pull request #893
Opened 2022-10-16 11:03 UTC by undead404

Оригінальний вміст: [String@MDN](https://developer.mozilla.org/en-us/docs/Web/JavaScript/Reference/Global_Objects/String), [сирці String@GitHub](https://github.com/mdn/content/blob/main/files/en-us/web/javascript/reference/global_objects/string/index.md)

Нові зміни:
- [mdn/content@d3e1f5c](https://github.com/mdn/content/commit/d3e1f5ca55900b1cf3f73378ec4c365c1f2512fe)

Лише перегляд формулювань насправді.

2022-10-21 11:30 UTC, undead404 commented
Додано https://github.com/mdn/content/commit/1d99fd3e73c445e5121b4af77461232f28be4337#diff-0f99acf740a1307fa04182aa4a817f019dd1a1aeef8da6f085ebc7352a268b4b

2022-10-25 21:04 UTC, AdriandeCita commented on files/uk/web/javascript/reference/global_objects/string/index.md
> +Об'єкт **`String`** — «Рядок», «Стрічка» — використовується для представлення та обробки послідовностей символів.
Чи є сенс повертати цей термін? Схоже, він добряче застарів http://www.inmo.org.ua/sum.html?wrd=%D0%A1%D1%82%D1%80%D1%96%D1%87%D0%BA%D0%B0
```suggestion
Об'єкт **`String`** — «Рядок» — використовується для представлення та обробки послідовностей символів.
```

2022-10-25 21:08 UTC, AdriandeCita commented on files/uk/web/javascript/reference/global_objects/string/index.md
> +### Довгі стрічки з літер
Тут і нижче - теж стрічки

2022-10-25 21:40 UTC, AdriandeCita commented on files/uk/web/javascript/reference/global_objects/string/index.md
> +Слід бути обережними з рівнями символів, на котрих відбувається ітерація. Наприклад, [`split("")`](/uk/docs/Web/JavaScript/Reference/Global_Objects/String/split) розбиває рядок на кодові одиниці UTF-
Ця форма тут підходить мало, "[одна] ітерація" - це в першу чергу один цикл дії. Ну можливо наполовину підходить, якщо розуміти під "ітерацією" також і процес виконання всіх ітерацій циклу. Але тоді виходить, що ми навмисне вживаємо неоднозначний термін, заплутуючи користувача.
Давай хоча б якось так. В ідеалі я б радше вживав прості однозначні терміни, аби цих проблем взагалі не виникало.
```suggestion
Слід бути обережними з тим, по якому рівню символів відбувається ітерування. Наприклад, [`split("")`](/uk/docs/Web/JavaScript/Reference/Global_Objects/String/split) розбиває рядок на кодові одиниці UTF-16 і розриває сурогатні пари. Рядкові індекси також вказують на індекси всіх кодових одиниць UTF-16. З іншого боку, [`@@iterator()`](/uk/docs/Web/JavaScript/Reference/Global_Objects/String/@@iterator) виконує обхід за кодовими точками Unicode. Обхід за графемними кластерами потребуватиме написання певного коду самотужки.
```

2022-10-25 21:57 UTC, AdriandeCita requested changes
Маю пару зауважень. Круто, що ти вичитав текст іще раз і виправив чимало граматичних помилок, я був дещо здивований з їхньої кількості. Разом з тим, багато змін здаються настільки косметичними, що мені стає шкода часу, який ти витратив на їх внесення :slightly_smiling_face:

2022-10-26 08:38 UTC, undead404 commented on files/uk/web/javascript/reference/global_objects/string/index.md
> +Об'єкт **`String`** — «Рядок», «Стрічка» — використовується для представлення та обробки послідовностей символів.
Я завагався, тому що низка символів, що умістилися в текстовий файл по горизонталі поруч – це рядок...

І колекція з багатьох символів – це теж рядок, рядок №2! І серед символів у рядку №2 може бути символ "\n", тож вийде, що в рядку №2 багато рядків №1!

Я спантеличився од цього і десь ввів "стрічку"

2022-10-28 10:47 UTC, undead404 commented
Замість "стрічок" зробив просто "текст"

2022-11-07 12:19 UTC, undead404 commented
Оновлено

2022-11-07 21:07 UTC, AdriandeCita approved these changes

2022-11-07 21:07 UTC, merged