update(JS): web/javascript/reference/global_objects/object
webdoky/content pull request #897
Opened 2022-10-21 11:41 UTC by undead404

Оригінальний вміст: [Object (Об'єкт)@MDN](https://developer.mozilla.org/en-us/docs/Web/JavaScript/Reference/Global_Objects/Object), [сирці Object (Об'єкт)@GitHub](https://github.com/mdn/content/blob/main/files/en-us/web/javascript/reference/global_objects/object/index.md)

Нові зміни:
- [mdn/content@1d99fd3](https://github.com/mdn/content/commit/1d99fd3e73c445e5121b4af77461232f28be4337)

2022-11-07 19:21 UTC, undead404 commented
Оновлено

2022-11-08 12:06 UTC, AdriandeCita commented on files/uk/web/javascript/reference/global_objects/object/index.md
> +Слід уникати виклику будь-яких методів `Object.prototype`, особливо тих, котрі не створені поліморфними (тобто їх початкова логіка має зміст, і жодний об'єкт-нащадок не зможе перевизначити їх у зміст
```suggestion
Слід уникати виклику будь-яких методів `Object.prototype`, особливо тих, котрі не створені поліморфними (тобто лише їхня початкова логіка має зміст, і жодний об'єкт-нащадок не зможе перевизначити їх у змістовний спосіб). Усі об'єкти, що походять від `Object.prototype`, можуть визначати власні властивості, що мають ідентичні імена, але з геть інакшою семантикою, ніж та, на котру ви очікуєте. Понад те, ці властивості не успадковуються [об'єктами з прототипом `null`](#obiekty-z-prototypom-null). Усі сучасні службові засоби JavaScript для роботи з об'єктами є [статичними](#statychni-metody). Конкретніше:
```

2022-11-08 13:54 UTC, AdriandeCita requested changes
невеличке зауваження

2022-11-26 12:09 UTC, undead404 commented
Прийнято

2022-11-28 15:37 UTC, merged