update(JS): web/javascript/reference/global_objects/math/floor
webdoky/content pull request #911
Opened 2022-10-22 13:42 UTC by undead404

Оригінальний вміст: [Math.floor()@MDN](https://developer.mozilla.org/en-us/docs/Web/JavaScript/Reference/Global_Objects/Math/floor), [сирці Math.floor()@GitHub](https://github.com/mdn/content/blob/main/files/en-us/web/javascript/reference/global_objects/math/floor/index.md)

Нові зміни:
- [mdn/content@d6ce8fc](https://github.com/mdn/content/commit/d6ce8fcbbc4a71ec9209f379e5ea9774bbf1f5ac)
- [mdn/content@0a1a69b](https://github.com/mdn/content/commit/0a1a69b30f7b746af84f26788b47ebdf396f6775)
- [mdn/content@04c4cb2](https://github.com/mdn/content/commit/04c4cb231c95bc814bcc1f59676ca336fdab343a)
- [mdn/content@4df8b04](https://github.com/mdn/content/commit/4df8b04c7cda029dc29c4ef5375a1af9d3171095)
- [mdn/content@ea3c7e8](https://github.com/mdn/content/commit/ea3c7e895db294be7c9535f849ced1ad63e6158e)

2022-11-22 12:17 UTC, AdriandeCita approved these changes

2022-11-22 12:19 UTC, AdriandeCita requested changes
Дрібниця, але є невраховані зміни https://github.com/mdn/content/commit/9e52d335675a9f7daa34b5e24c9b1292dbf23b2e#diff-5cd8be0480313c33144bf4afb30692cfc2f0b42328907a0b7dd3b1f59e6569c6

2022-12-07 14:15 UTC, undead404 commented
Оновив

2022-12-07 23:10 UTC, AdriandeCita approved these changes

2022-12-07 23:10 UTC, merged