translation(CSS): web/css/value_definition_syntax
webdoky/content pull request #913
Opened 2022-10-24 14:45 UTC by undead404

Оригінальний вміст: [Value definition syntax@MDN](https://developer.mozilla.org/en-us/docs/Web/CSS/Value_definition_syntax), [сирці Value definition syntax@GitHub](https://github.com/mdn/content/blob/main/files/en-us/web/css/value_definition_syntax/index.md)

2022-11-08 16:22 UTC, undead404 commented
Конфлікт розв'язано, у решті без змін.

2022-11-23 22:57 UTC, AdriandeCita commented on files/uk/web/css/value_definition_syntax/index.md
> +**Синтаксис визначення значення CSS**, формальна граматика, використовується для визначення множини дійсних значень властивості чи функції CSS. На додачу до цього синтаксису, множина дійсних значень
```suggestion
**Синтаксис визначення значення CSS** — це формальна граматика, що використовується для визначення множини дійсних значень властивості чи функції CSS. На додачу до цього синтаксису, множина дійсних значень може бути звужена семантичними обмеженнями (наприклад, число може бути строго додатним).
```

2022-11-23 23:00 UTC, AdriandeCita commented on files/uk/web/css/value_definition_syntax/index.md
> +Ключове слово з наперед визначеним значенням з'являється буквально, без лапок. Наприклад: `auto`, `smaller` чи `ease-in`.
```suggestion
Ключове слово з наперед визначеним значенням вживається буквально, без лапок. Наприклад: `auto`, `smaller` чи `ease-in`.
```

2022-11-23 23:08 UTC, AdriandeCita commented on files/uk/web/css/value_definition_syntax/index.md
> +У CSS кілька символів можуть з'являтись самі по собі, як то скісна риска ('`/`') чи кома ('`,`'), і використовуватись у визначенні властивості для розділення його частин. Кома нерідко використовуєтьс
```suggestion
У CSS кілька символів можуть з'являтись самі по собі, як то скісна риска ('`/`') чи кома ('`,`'), і використовуватись у визначенні властивості для розділення його частин. Кома нерідко використовується для розділення значень в переліченнях, або параметрів у функціях математичного вигляду; скісна риска нерідко розділяє частини значення, що є семантично відмінними, але мають спільний синтаксис. Зазвичай скісна риска використовується у властивостях-скороченнях: для розділення компонентів, що мають один тип, але належать різним властивостям.
```

2022-11-23 23:14 UTC, AdriandeCita commented on files/uk/web/css/value_definition_syntax/index.md
> +- типи даних, що _поділяють ім'я зі властивістю_, поставлене в лапки. У такому випадку тип даних поділяє множину значень зі властивістю. Такі типи нерідко використовуються у визначеннях властивостей-
Трохи переформулював, бо не зрозуміло, чому нас цікавіть якась властивість множини даних. Також вжив іншу форму, бо у нас підряд йдуть "у такому... Такі типи..." 
```suggestion
- типи даних, що _поділяють ім'я зі властивістю_, поставлене в лапки. У цьому випадку і тип даних, і властивість  поділяють спільну множину значень. Такі типи нерідко використовуються у визначеннях властивостей-скорочень.
```

2022-11-23 23:18 UTC, AdriandeCita commented on files/uk/web/css/value_definition_syntax/index.md
> +- `thin bold 3em`, адже `bold` ставиться поруч з компонентом, визначеним квадратними дужками, і повинно стояти перед ним.
```suggestion
- `thin bold 3em`, адже `bold` ставиться поруч з компонентом, визначеним квадратними дужками, хоча повинно стояти перед ним.
```

2022-11-23 23:28 UTC, AdriandeCita commented on files/uk/web/css/value_definition_syntax/index.md
> +_Помножувач оклику_ після групи вказує, що група є обов'язковою і мусить дати принаймні одне значення; навіть якщо граматика елементів усередині групи дозволяє пропустити увесь вміст, то принаймні од
```suggestion
_Помножувач оклику_ після групи вказує, що група є обов'язковою і мусить дати принаймні одне значення; навіть якщо граматика елементів усередині групи дозволяє пропустити увесь вміст, то принаймні одне значення компонента усе ж повинно бути вказано.
```

2022-11-23 23:32 UTC, AdriandeCita requested changes
Маю декілька побажань

2022-11-24 22:41 UTC, merged