translation(Guide): web/guide/html/content_categories
webdoky/content pull request #916
Opened 2022-10-25 08:43 UTC by undead404

Оригінальний вміст: [Content categories@MDN](https://developer.mozilla.org/en-us/docs/Web/Guide/HTML/Content_categories), [сирці Content categories@GitHub](https://github.com/mdn/content/blob/main/files/en-us/web/guide/html/content_categories/index.md)

2022-11-08 16:23 UTC, undead404 commented
Без змін

2022-12-01 07:45 UTC, AdriandeCita commented on files/uk/web/guide/html/content_categories/index.md
> +- Особливі категорії вмісту, що описують рідкісні категорії, що поділяються лишень кількома елементами, іноді лише в конкретному контексті.
"що.., що"
```suggestion
- Особливі категорії вмісту, що описують рідкісні категорії, які поділяються лишень кількома елементами, іноді лише в конкретному контексті.
```

2022-12-01 07:51 UTC, AdriandeCita commented on files/uk/web/guide/html/content_categories/index.md
> +Елементи, що належать до категорії _вмісту метаданих_, видозмінюють представлення чи поведінку решти документа, задають посилання на інші документи чи доносять іншу _позасмугову_ інформацію.
а що таке "позасмугова інформація"? Гугл мене послав сюди https://en.wikipedia.org/wiki/Out-of-band, але я не певен, як саме це застосовується на документ

2022-12-01 07:58 UTC, AdriandeCita commented on files/uk/web/guide/html/content_categories/index.md
> +### Вміст вбудування
В оригіналі це просто "Embedded content", і мені здається цілком ок перекладати його дослівно
```suggestion
### Вбудований вміст
```

2022-12-01 07:58 UTC, AdriandeCita commented on files/uk/web/guide/html/content_categories/index.md
> +Вміст вбудування – підмножина потокового вмісту, що імпортує інші ресурси чи вставляє в документ вміст з іншої мови розмітки чи простору імен і може використовуватися всюди, де очікується потоковий в
```suggestion
Вбудований вміст – підмножина потокового вмісту, що імпортує інші ресурси чи вставляє в документ вміст з іншої мови розмітки чи простору імен і може використовуватися всюди, де очікується потоковий вміст. Серед елементів, що належать до цієї категорії:
```

2022-12-01 08:10 UTC, AdriandeCita commented on files/uk/web/guide/html/content_categories/index.md
> +### Сценарно-підтримувальні елементи
Пропоную написати простими словами. З терміну "сценарно-підтримувальні" не зовсім зрозуміло, чи то вони сценарні, чи -- пітдтримувальні.
```suggestion
### Елементи з підтримкою сценаріїв
```

2022-12-01 08:11 UTC, AdriandeCita commented on files/uk/web/guide/html/content_categories/index.md
> +**Сценарно-підтримувальні елементи** – елементи, котрі безпосередньо не докладаються до зображеного виводу документа. Натомість вони служать підтримкою сценаріям, або вміщаючи, або задаючи код сценар
```suggestion
**Елементи з підтримкою сценаріїв** – елементи, котрі безпосередньо не докладаються до зображеного виводу документа. Натомість вони служать підтримкою сценаріям, або вміщаючи, або задаючи код сценаріїв, або вміщаючи дані, котрі будуть використані сценаріями.
```

2022-12-01 08:12 UTC, AdriandeCita commented on files/uk/web/guide/html/content_categories/index.md
> +Сценарно-підтримувальні елементи:
```suggestion
Елементи з підтримкою сценаріїв:
```

2022-12-01 08:14 UTC, AdriandeCita commented on files/uk/web/guide/html/content_categories/index.md
> +Коли елемент має модель прозорого вмісту, то його вміст мусить мати таку структуру, що була б дійсним HTML 5, навіть коли прозорий елемент прибирається і заміщається його дочірніми елементами.
Пропоную уточнити для кращої зрозумілості
```suggestion
Коли елемент має модель прозорого вмісту, то його вміст мусить мати таку структуру, що була б дійсним HTML 5, навіть коли сам прозорий елемент прибирається і заміщається його дочірніми елементами.
```

2022-12-01 08:16 UTC, AdriandeCita requested changes
Є декілька зауважень і питань

2022-12-01 08:52 UTC, undead404 commented on files/uk/web/guide/html/content_categories/index.md
> +Елементи, що належать до категорії _вмісту метаданих_, видозмінюють представлення чи поведінку решти документа, задають посилання на інші документи чи доносять іншу _позасмугову_ інформацію.
Можливо, це "придаткова"?

2022-12-01 08:56 UTC, undead404 commented on files/uk/web/guide/html/content_categories/index.md
> +### Сценарно-підтримувальні елементи
Пропоную тоді таке

```suggestion
### Елементи підтримки сценаріїв
```

2022-12-01 08:57 UTC, undead404 commented on files/uk/web/guide/html/content_categories/index.md
> +**Сценарно-підтримувальні елементи** – елементи, котрі безпосередньо не докладаються до зображеного виводу документа. Натомість вони служать підтримкою сценаріям, або вміщаючи, або задаючи код сценар
```suggestion
**Елементи підтримки сценаріїв** – елементи, котрі безпосередньо не докладаються до зображеного виводу документа. Натомість вони служать підтримкою сценаріям, або вміщаючи, або задаючи код сценаріїв, або вміщаючи дані, котрі будуть використані сценаріями.
```

2022-12-01 08:58 UTC, undead404 commented on files/uk/web/guide/html/content_categories/index.md
> +Сценарно-підтримувальні елементи:
```suggestion
Елементи підтримки сценаріїв:
```

2022-12-01 09:00 UTC, undead404 commented on files/uk/web/guide/html/content_categories/index.md
> +Коли елемент має модель прозорого вмісту, то його вміст мусить мати таку структуру, що була б дійсним HTML 5, навіть коли прозорий елемент прибирається і заміщається його дочірніми елементами.
```suggestion
Коли елемент має модель прозорого вмісту, то його вміст мусить мати таку структуру, що була б дійсним HTML 5, навіть коли сам прозорий елемент був би прибраний і заміщений власними дочірніми елементами.
```

2022-12-01 10:28 UTC, AdriandeCita commented on files/uk/web/guide/html/content_categories/index.md
> +### Сценарно-підтримувальні елементи
Мені здається це більш далеким перекладом, але зміст не втрачається, тож чому б і ні

2022-12-01 10:53 UTC, AdriandeCita commented on files/uk/web/guide/html/content_categories/index.md
> +Елементи, що належать до категорії _вмісту метаданих_, видозмінюють представлення чи поведінку решти документа, задають посилання на інші документи чи доносять іншу _позасмугову_ інформацію.
можливо. А може мається на увазі інформація, яку не потрібно завантажувати з інтернету...

2022-12-02 09:22 UTC, undead404 commented on files/uk/web/guide/html/content_categories/index.md
> +Елементи, що належать до категорії _вмісту метаданих_, видозмінюють представлення чи поведінку решти документа, задають посилання на інші документи чи доносять іншу _позасмугову_ інформацію.
Ну це все усе одно частина HTML, інформація "доноситься", а не "на неї посилаються".

```suggestion
Елементи, що належать до категорії _вмісту метаданих_, видозмінюють представлення чи поведінку решти документа, задають посилання на інші документи чи доносять іншу _супутню_ інформацію.
```

2022-12-02 09:23 UTC, undead404 commented on uk_spelling_additions.txt
> +сценарно-підтримувальні
```suggestion
```

2022-12-07 11:15 UTC, undead404 commented
Вніс власні пропозиції

2022-12-07 23:12 UTC, AdriandeCita approved these changes

2022-12-07 23:12 UTC, merged