translation(CSS): web/css/length
webdoky/content pull request #922
Opened 2022-10-27 20:07 UTC by undead404

Оригінальний вміст: [&lt;length>@MDN](https://developer.mozilla.org/en-us/docs/Web/CSS/length), [сирці &lt;length>@GitHub](https://github.com/mdn/content/blob/main/files/en-us/web/css/length/index.md)

2022-11-08 16:28 UTC, undead404 commented
Оновлено: https://github.com/mdn/content/commit/b6501026f4485ef6958e9f36010849589cac2271#diff-72757d89fa9a8816274c169b9a3641841f4ca21b9c998aa87b3913a1f2ca3013

2022-12-03 11:46 UTC, AdriandeCita commented on files/uk/web/css/length/index.md
> +    Наприклад, елемент, що отримує розмір за допомогою одиниць вимірювання відсотків області перегляду на основі малої області перегляду, досконало заповнює екран, і жодний вміст не затуляється, коли
Пропоную спростити, бо українською це складно сприймається (та й англійською не надто простіше)
```suggestion
    Наприклад, елемент, що отримує розмір у відсоткових одиницях від малої області перегляду, досконало заповнює екран, і жодний вміст не затуляється, коли виводиться динамічний браузерний інтерфейс. Проте коли такий інтерфейс приховано, навколо елемента може бути зайвий порожній простір. Таким чином, загалом одиниці вимірювання відсотків від малої області перегляду "безпечніше" використовувати, але вони можуть виробляти не найпривабливіший макет, коли користувач починає взаємодіяти зі сторінкою.
```

2022-12-03 11:49 UTC, AdriandeCita commented on files/uk/web/css/length/index.md
> +  - : Коли при реагуванні на динамічне звуження елементів браузерного інтерфейсу використовується найбільша можлива область перегляду, слід використовувати великий розмір області. Великий розмір обла
В оригіналі "When you want..."
```suggestion
  - : Коли при реагуванні на динамічне звуження елементів браузерного інтерфейсу потрібно отримати найбільшу можливу область перегляду, слід використовувати великий розмір області. Великий розмір області перегляду дає змогу заповнити усю область перегляду, коли браузерний інтерфейс звужується. Проте слід мати на увазі, що частина вмісту може бути прихована, коли браузерний інтерфейс розшириться.
```

2022-12-03 11:56 UTC, AdriandeCita commented on files/uk/web/css/length/index.md
> +    Наприклад, на мобільних телефонах, де квадратура екрана – преміального рівня, браузери нерідко частково або повністю приховують заголовок і поле адреси, коли користувач починає прокручувати сторі
Аналогічно, трохи перевантажена конструкція
```suggestion
    Наприклад, на мобільних телефонах, де квадратура екрана – преміального рівня, браузери нерідко частково або повністю приховують заголовок і поле адреси, коли користувач починає прокручувати сторінку. Коли елемент отримує розмір за допомогою одиниці вимірювання у відсоткових одиницях від великого розміру області, вміст елемента заповнить усю видиму сторінку, коли інтерфейс браузера – прихований. Проте коли ці зменшувані елементи інтерфейсу виводяться, вони можуть приховати вміст, що отримує розмір чи розташування у відсоткових одиницях відносно _великої_ області видимості.
```

2022-12-03 12:11 UTC, AdriandeCita commented on files/uk/web/css/length/index.md
> +    > **Примітка:** Хоч динамічний розмір області перегляду може дати більше контролю і гнучкості, використання одиниць вимірювання у відсотках від області перегляду може змусити вміст змінювати розм
```suggestion
    > **Примітка:** Хоч динамічний розмір області перегляду може дати більше контролю і гнучкості, використання відсотків від динамічного розміру області перегляду може змусити вміст змінювати розмір, коли користувач прокручує сторінку. Це може призвести до деградації користувацького інтерфейсу та падіння швидкодії.
```

2022-12-03 12:16 UTC, AdriandeCita commented on files/uk/web/css/length/index.md
> +    Динамічна одиниця області перегляду представлена префіксом `dv` і приводить до одиниць вимірювання, відсоткових щодо області перегляду, `dv*`. Розміри одиниць вимірювання у відсотках від динамічн
Трохи переформулював
```suggestion
    Динамічна одиниця області перегляду представлена префіксом `dv` і приводить до відсоткових одиниць вимірювання `dv*`. Розміри одиниць вимірювання у відсотках від динамічної області – нестабільні, навіть якщо сама область перегляду не змінюється.
```

2022-12-03 12:22 UTC, AdriandeCita commented on files/uk/web/css/length/index.md
> +  - : Усталений розмір області перегляду – визначений браузером. Логіка результівної одиниці відсотків щодо області перегляду може бути рівносильним одиниці на основі малої області перегляду, великої
не певен, що логіку можна вважати рівносильною чомусь. Та й загалом пропоную трохи спростити
```suggestion
  - : Усталений розмір області перегляду – визначений браузером. Поведінка результівної одиниці вимірювання може наслідувати логіку роботи відсоткових одиниць малої області перегляду, великої області, проміжної між попередніми двома, або ж динамічного розміру.
```

2022-12-03 12:26 UTC, AdriandeCita commented on files/uk/web/css/length/index.md
> +    > **Примітка:** Наприклад, браузер може реалізувати усталену одиницю відсотків щодо області видимості для висоти (`vh`), рівносильну одиниці висоти щодо великої області перегляду (`lvh`). Якщо це
тип реалізації нічого не затуляє. В оригіналі "obscure", що радше про "приховання"
```suggestion
    > **Примітка:** Наприклад, браузер може реалізувати усталену одиницю відсотків щодо області видимості для висоти (`vh`), рівносильну одиниці висоти щодо великої області перегляду (`lvh`). Якщо це так, то це може призвести до затулення вмісту при повносторінковому перегляді, коли браузерний інтерфейс – розгорнутий.
```

2022-12-03 12:33 UTC, AdriandeCita commented on files/uk/web/css/length/index.md
> +При застосуванні стилів до контейнера за допомогою контейнерних запитів можна використовувати одиниці вимірювання довжини для контейнерних запитів.
Я не певен, чи можна застосовувати відносні одиниці для самих запитів. В оригіналі маються на увазі спеціальні одиниці, які можна використовувати _всередині_ контейнерних запитів. Пропоную уточнити це таким чином
```suggestion
При застосуванні стилів до контейнера за допомогою контейнерних запитів можна використовувати окремі одиниці вимірювання довжини для контейнерних запитів.
```

2022-12-03 12:34 UTC, AdriandeCita commented on files/uk/web/css/length/index.md
> +Компоненти, що використовують одиниці вимірювання довжини, відносні щодо контейнера, є гнучкішими у використанні в різних контейнерах, без потреби заново обчислювати конкретні значення довжини.
```suggestion
Компоненти, що використовують одиниці вимірювання довжини, відносні щодо контейнера, є гнучкішими у використанні в різних контейнерах, адже не потребують заново обчислювати конкретні значення довжини.
```

2022-12-03 12:42 UTC, AdriandeCita commented on files/uk/web/css/length/index.md
> +При анімації значення типу даних `<length>` інтерполюються як дробові числа з рухомою комою. Інтерполяція відбувається на підрахованому значенні. Швидкість інтерполяції визначається [функцією хрономе
```suggestion
При анімації значення типу даних `<length>` інтерполюються як дробові числа з рухомою комою. Інтерполяція відбувається на підрахованому значенні. Швидкість інтерполяції визначається [функцією хронометражу](/uk/docs/Web/CSS/easing-function), пов'язаною з конкретною анімацією.
```

2022-12-03 12:45 UTC, AdriandeCita requested changes
Декілька пропозицій

2022-12-07 11:18 UTC, undead404 commented
Усе вподобав і прийняв

2022-12-07 23:12 UTC, AdriandeCita approved these changes

2022-12-07 23:12 UTC, merged