update(JS): web/javascript/reference/global_objects/promise/all
webdoky/content pull request #925
Opened 2022-10-28 12:01 UTC by undead404

Оригінальний вміст: [Promise.all()@MDN](https://developer.mozilla.org/en-us/docs/Web/JavaScript/Reference/Global_Objects/Promise/all), [сирці Promise.all()@GitHub](https://github.com/mdn/content/blob/main/files/en-us/web/javascript/reference/global_objects/promise/all/index.md)

Нові зміни:
- [mdn/content@6b60565](https://github.com/mdn/content/commit/6b60565289762f7be9bf377022e610e71e5867d1)

2022-11-07 20:33 UTC, undead404 commented
Без змін

2022-11-26 20:02 UTC, AdriandeCita commented on files/uk/web/javascript/reference/global_objects/promise/all/index.md
> +  - : [Ітерований об'єкт](/uk/docs/Web/JavaScript/Reference/Iteration_protocols#protokol-iteruvannia) (наприклад, {{jsxref("Array")}}) промісів.
"Об'єкт промісів" звучить радше неприродно
```suggestion
  - : [Ітерований об'єкт](/uk/docs/Web/JavaScript/Reference/Iteration_protocols#protokol-iteruvannia) (наприклад, {{jsxref("Array")}}) з промісами.
```

2022-11-26 20:31 UTC, AdriandeCita commented on files/uk/web/javascript/reference/global_objects/promise/all/index.md
> +Проте, `Promise.all` вирішується синхронно лише в тому випадку, якщо передане значення `iterable` — порожнє:
Неоднозначний вираз, незрозуміло -- чи то мається на увазі порожній масив, чи порожнє значення (`null`? `undefined`?)
Я починаю схилятися до того, щоб ці терміни в гравісах або не виділяти, або перекладати прям всередині... Але я до цього іще морально не готовий, пропоную отакий компромісний варіант
```suggestion
Проте, `Promise.all` вирішується синхронно лише в тому випадку, якщо передано порожній ітерований об'єкт (`iterable`):
```

2022-11-26 20:38 UTC, AdriandeCita commented on files/uk/web/javascript/reference/global_objects/promise/all/index.md
> +`Promise.all` приймає ітеровану колекцію промісів, тож якщо він використовується для паралелізації виконання декількох асинхронних функцій, слід викликати асинхронні функції та використовувати поверн
Чим ітерована колекція відрізняється від неітерованої? Можливо тоді краще вживати просто термін "колекція", оскільки ця різниця тут нерелевантна, тільки нагромаджує додаткових конотацій?
```suggestion
`Promise.all` приймає колекцію промісів, тож якщо він використовується для паралелізації виконання декількох асинхронних функцій, слід викликати асинхронні функції та використовувати повернені ними проміси. Безпосередня передача функцій в `Promise.all` не працює, адже вони не є промісами.
```

2022-11-26 20:40 UTC, AdriandeCita requested changes
декілька пропозицій

2022-11-28 11:07 UTC, undead404 commented
Прийнято

2022-11-28 21:36 UTC, AdriandeCita approved these changes

2022-11-28 21:36 UTC, merged