translation(JS): web/javascript/reference/global_objects/nan
webdoky/content pull request #928
Opened 2022-10-29 18:05 UTC by undead404

Оригінальний вміст: [NaN@MDN](https://developer.mozilla.org/en-us/docs/Web/JavaScript/Reference/Global_Objects/NaN), [сирці NaN@GitHub](https://github.com/mdn/content/blob/main/files/en-us/web/javascript/reference/global_objects/nan/index.md)

2022-12-03 13:00 UTC, AdriandeCita commented on files/uk/web/javascript/reference/global_objects/nan/index.md
> +Проте зверніть увагу на різницю між `isNaN()` і `Number.isNaN()`: перший варіант поверне `true` уже є `NaN` або буде `NaN` після зведення до числа, натомість другий – поверне `true` лише коли значенн
```suggestion
Проте зверніть увагу на різницю між `isNaN()` і `Number.isNaN()`: перший варіант поверне `true`, коли значення вже дорівнює `NaN`, або стане `NaN` після зведення до числа, натомість другий – поверне `true` лише коли значення вже є `NaN`:
```

2022-12-03 13:05 UTC, AdriandeCita commented on files/uk/web/javascript/reference/global_objects/nan/index.md
> +`NaN` пролізає крізь усі математичні операції, тож здебільшого ефективно перевірити на `NaN` один раз – у кінці обчислення, щоб помітити помилку. Єдиний випадок, коли `NaN` тихо екранується – при [пі
```suggestion
`NaN` пролізає крізь усі математичні операції, тож зазвичай достатньо перевірити на `NaN` один раз – у кінці обчислення, щоб помітити помилку. Єдиний випадок, коли `NaN` тихо екранується – при [піднесенні до степеня](/uk/docs/Web/JavaScript/Reference/Operators/Exponentiation) з показником степеня `0`, що зразу повертає `1`, без перевірки значення основи.
```

2022-12-03 13:05 UTC, AdriandeCita requested changes
Пара пропозицій

2022-12-07 11:19 UTC, undead404 commented
Прийняв

2022-12-07 23:13 UTC, AdriandeCita approved these changes

2022-12-07 23:13 UTC, merged