translation(CSS): web/css/computed_value
webdoky/content pull request #929
Opened 2022-10-29 18:40 UTC by undead404

Оригінальний вміст: [Computed value@MDN](https://developer.mozilla.org/en-us/docs/Web/CSS/computed_value), [сирці Computed value@GitHub](https://github.com/mdn/content/blob/main/files/en-us/web/css/computed_value/index.md)

2022-11-08 16:29 UTC, undead404 commented
Без змін

2022-12-03 15:18 UTC, AdriandeCita commented on files/uk/web/css/computed_value/index.md
> +Проте для частини властивостей (тих, чиї відсотки відносні щодо чогось, що може вимагати визначення макета, як то `width`, `margin-right`, `text-indent` і `top`) процентно-задані значення перетворюют
Не зовсім зрозуміло, що таке "процентно-задані" і "процентно-обчислені" значення. Я трохи поколупав специфікацію, але нічого конкретного не знайшов. Ймовірно мається на увазі, що відсоткові значення залишаються відсотковими, переходячи в розряд обчислених, поки інформація з макета іще недоступна. Переформулював це, і ще трохи всякого.
```suggestion
Проте для частини властивостей (тих, чиї відсотки відносні щодо чогось, що може потребувати макета для визначення, як то `width`, `margin-right`, `text-indent` і `top`) задані відсоткові значення перетворюються на обчислені відсоткові значення. Крім цього, безрозмірні числа, задані у властивості `line-height`, стають обчисленим значенням, як задано. Відносні величини, що залишаються в обчисленому значенні, стають абсолютними, коли з'ясовується [застосоване значення](/uk/docs/Web/CSS/used_value)
```

2022-12-03 15:22 UTC, AdriandeCita requested changes
по коментарю

2022-12-07 11:20 UTC, undead404 commented
Слушна каверза, прийняв

2022-12-07 23:14 UTC, AdriandeCita approved these changes

2022-12-07 23:15 UTC, merged