translation(CSS): web/css/inheritance
webdoky/content pull request #931
Opened 2022-10-29 19:24 UTC by undead404

Оригінальний вміст: [Inheritance@MDN](https://developer.mozilla.org/en-us/docs/Web/CSS/inheritance), [сирці Inheritance@GitHub](https://github.com/mdn/content/blob/main/files/en-us/web/css/inheritance/index.md)

2022-11-08 16:30 UTC, undead404 commented
Без змін

2022-12-02 10:51 UTC, undead404 commented
Оновлено: https://github.com/mdn/content/commit/dd52f7e4915810060d525ce62a870dcf1ae17a63

2022-12-03 15:29 UTC, AdriandeCita commented on files/uk/web/css/inheritance/index.md
> +Зверніться до визначення [властивостей CSS](/uk/docs/Web/CSS/Reference#pokazhchyk-kliuchovykh-sliv), аби дізнатися, чи успадковується усталено конкретна властивість ("Inherited: yes"), чи ні ("Inheri
Це не код. Скоріш за все, мається на увазі оцей рядок в таблиці формального визначення (посилання з якого веде на цю сторінку):
![image](https://user-images.githubusercontent.com/11510394/205448692-e64dcb16-a43b-4303-bf5c-f452901b3730.png).
У нас воно перекладено:
![image](https://user-images.githubusercontent.com/11510394/205448717-9d5ed896-7bb2-410a-8e2f-5752e97722af.png)
```suggestion
Зверніться до визначення [властивостей CSS](/uk/docs/Web/CSS/Reference#pokazhchyk-kliuchovykh-sliv), аби дізнатися, чи успадковується усталено конкретна властивість ("Успадковується: так"), чи ні ("Успадковується: ні").
```

2022-12-03 15:32 UTC, AdriandeCita commented on files/uk/web/css/inheritance/index.md
> +Типовий приклад успадкованої властивості – властивість [`color`](/uk/docs/Web/CSS/color). Для прикладу – наступні правила стилю та розмітка:
думаю, можна спростити
```suggestion
Типовий приклад успадкованої властивості – [`color`](/uk/docs/Web/CSS/color). Для прикладу – наступні правила стилю та розмітка:
```

2022-12-03 15:39 UTC, AdriandeCita commented on files/uk/web/css/inheritance/index.md
> +Типовий приклад неуспадкованої властивості – властивість {{Cssxref("border")}}. Для прикладу – наступні правила стилю та розмітка:
```suggestion
Типовий приклад неуспадкованої властивості – властивість {{Cssxref("border")}}. Розгляньмо наступні правила стилю та розмітку:
```

2022-12-03 15:42 UTC, AdriandeCita commented on files/uk/web/css/inheritance/index.md
> +Це повертає стиль властивості [`font`](/uk/docs/Web/CSS/font) абзацу до усталеного значення користувацького агента, якщо немає користувацької таблиці стилів, у випадку чого використовується значення
```suggestion
Це повертає стиль властивості [`font`](/uk/docs/Web/CSS/font) абзацу до усталеного значення користувацького агента, якщо немає користувацької таблиці стилів, у випадку чого використовується значення з неї. А потім цей код подвоює розмір шрифту та застосовує [`font-weight`](/uk/docs/Web/CSS/font-weight) зі значенням `"bold"`.
```

2022-12-03 15:42 UTC, AdriandeCita commented on files/uk/web/css/inheritance/index.md
> +- Значення CSS для контролю успадкування: [`inherit`](/uk/docs/Web/CSS/inherit), [`initial`](/uk/docs/Web/CSS/initial), [`revert`](/uk/docs/Web/CSS/revert), [`revert-layer`](/uk/docs/Web/CSS/revert-l
```suggestion
- Значення CSS для контролю успадкування: [`inherit`](/uk/docs/Web/CSS/inherit), [`initial`](/uk/docs/Web/CSS/initial), [`revert`](/uk/docs/Web/CSS/revert), [`revert-layer`](/uk/docs/Web/CSS/revert-layer) та [`unset`](/uk/docs/Web/CSS/unset)
```

2022-12-03 15:46 UTC, AdriandeCita requested changes
Декілька зауважень

2022-12-07 11:22 UTC, undead404 commented on files/uk/web/css/inheritance/index.md
> +Зверніться до визначення [властивостей CSS](/uk/docs/Web/CSS/Reference#pokazhchyk-kliuchovykh-sliv), аби дізнатися, чи успадковується усталено конкретна властивість ("Inherited: yes"), чи ні ("Inheri
Йой, розумів, що не код, але не звернув увагу, що перекладено

2022-12-07 23:17 UTC, AdriandeCita approved these changes

2022-12-07 23:17 UTC, merged