translation(JS): web/javascript/reference/global_objects/undefined
webdoky/content pull request #932
Opened 2022-10-29 20:11 UTC by undead404

Оригінальний вміст: [undefined@MDN](https://developer.mozilla.org/en-us/docs/Web/JavaScript/Reference/Global_Objects/undefined), [сирці undefined@GitHub](https://github.com/mdn/content/blob/main/files/en-us/web/javascript/reference/global_objects/undefined/index.md)

2022-12-04 22:10 UTC, AdriandeCita commented on files/uk/web/javascript/reference/global_objects/undefined/index.md
> +Проте є іще один варіант. JavaScript – мова статичних областей видимості, тож чи оголошена змінна – можна дізнатися, поглянувши, чи оголошена вона в замкненому контексті.
```suggestion
Проте є іще один варіант. JavaScript – мова статичних областей видимості, тож чи оголошена змінна – можна дізнатися, поглянувши, чи оголошена вона в охоплювальному контексті.
```

2022-12-04 22:10 UTC, AdriandeCita commented on files/uk/web/javascript/reference/global_objects/undefined/index.md
> +### оператор void і undefined
```suggestion
### Оператори void і undefined
```

2022-12-04 22:11 UTC, AdriandeCita commented on files/uk/web/javascript/reference/global_objects/undefined/index.md
> +## See also
```suggestion
## Дивіться також
```

2022-12-04 22:11 UTC, AdriandeCita requested changes
Декілька зауважень

2022-12-07 11:28 UTC, undead404 commented
Прийнято

2022-12-07 23:17 UTC, AdriandeCita approved these changes

2022-12-07 23:17 UTC, merged