translation(JS): web/javascript/reference/global_objects/regexp/exec
webdoky/content pull request #935
Opened 2022-10-30 09:25 UTC by undead404

Оригінальний вміст: [RegExp.prototype.exec()@MDN](https://developer.mozilla.org/en-us/docs/Web/JavaScript/Reference/Global_Objects/RegExp/exec), [сирці RegExp.prototype.exec()@GitHub](https://github.com/mdn/content/blob/main/files/en-us/web/javascript/reference/global_objects/regexp/exec/index.md)

2022-11-08 16:43 UTC, undead404 commented
Оновлено: https://github.com/mdn/content/commit/554d7f64f5afb769b7d6bc273f4c3d6562da9e6a#diff-c98e56175cf74ffac0289012404938e0fbbf863e98ca53ecf0c8e22318bdd15f

2022-11-08 16:47 UTC, undead404 commented
Оновлено: https://github.com/mdn/content/commit/9f13c1860c50d15a1c499c7cf3524c3be7cf467f#diff-c98e56175cf74ffac0289012404938e0fbbf863e98ca53ecf0c8e22318bdd15f

2022-12-08 23:04 UTC, AdriandeCita commented on files/uk/web/javascript/reference/global_objects/regexp/exec/index.md
> +При використанні `exec()` позначка глобальності не має дії за присутності позначки липкості: зіставлення обов'язково буде липким.
```suggestion
При використанні `exec()` позначка глобальності не діє за присутності позначки липкості: зіставлення обов'язково буде липким.
```

2022-12-08 23:15 UTC, AdriandeCita commented on files/uk/web/javascript/reference/global_objects/regexp/exec/index.md
> +## See also
```suggestion
## Дивіться також
```

2022-12-08 23:15 UTC, AdriandeCita requested changes
Є трохи зауважень

2022-12-09 12:28 UTC, undead404 commented
Прийнято

2022-12-14 12:04 UTC, AdriandeCita commented on files/uk/web/javascript/reference/global_objects/regexp/exec/index.md
> +tags:
```suggestion
page-type: javascript-instance-method
tags:
```

2022-12-14 12:04 UTC, AdriandeCita commented
Вніс іще ці зміни https://github.com/mdn/content/commit/2eb202adbe3d83292500ed46344d63fbbae410b5#diff-c98e56175cf74ffac0289012404938e0fbbf863e98ca53ecf0c8e22318bdd15f

2022-12-14 12:05 UTC, merged