translation(JS): web/javascript/guide/indexed_collections
webdoky/content pull request #938
Opened 2022-11-07 11:22 UTC by undead404

Оригінальний вміст: [Indexed collections@MDN](https://developer.mozilla.org/en-us/docs/Web/JavaScript/Guide/Indexed_collections), [сирці Indexed collections@GitHub](https://github.com/mdn/content/blob/main/files/en-us/web/javascript/guide/indexed_collections/index.md)

2022-11-24 14:07 UTC, undead404 commented
Оновлено: https://github.com/mdn/content/commit/42816e8a99c3ccd7bd6150adbfe886a7c025802f#diff-5c4a0934314207ea50445414f281b3c5af677c2003fb5080284b8bdd82c19191

2022-12-09 09:57 UTC, AdriandeCita commented on files/uk/web/javascript/guide/indexed_collections/index.md
> +// OR
Навряд чи логічний оператор справді має сенс в цьому контексті
```suggestion
// Або
```

2022-12-09 10:06 UTC, AdriandeCita commented on files/uk/web/javascript/guide/indexed_collections/index.md
> +> **Примітка:** Якщо передати оператору масиву значення, що не є цілим числом, у код вище, то в об'єкті, що представляє масив, буде створена властивість, а не елемент масиву.
звучить як наче значення передається в код, що не зовсім так. Пропоную зробити якось так
```suggestion
> **Примітка:** Якщо, в наведеному вище коді, передати оператору масиву значення, що не є цілим числом, то в об'єкті, що представляє масив, буде створена властивість, а не елемент масиву.
```

2022-12-09 10:06 UTC, AdriandeCita commented on files/uk/web/javascript/guide/indexed_collections/index.md
> +// OR
```suggestion
// Або
```

2022-12-09 10:10 UTC, AdriandeCita commented on files/uk/web/javascript/guide/indexed_collections/index.md
> +Слід пам'ятати, що індекси Array JavaScript починаються від `0`, а не `1`. А отже, властивість `length` буде на одиницю більшою за найбільший індекс, присутній в масиві:
```suggestion
Слід пам'ятати, що індекси об'єктів Array у JavaScript починаються від `0`, а не `1`. А отже, властивість `length` буде на одиницю більшою за найбільший індекс, присутній в масиві:
```

2022-12-09 10:17 UTC, AdriandeCita commented on files/uk/web/javascript/guide/indexed_collections/index.md
> +Такий підхід дає змогу уникнути накладних витрат з перевірки довжини масиву й пересвідчитися, що змінна `div` щоразу отримує поточний елемент, із покращеною зручністю.
```suggestion
Такий підхід дає змогу уникнути накладних витрат з перевірки довжини масиву й пересвідчитися, що змінна `div` щоразу отримує поточний елемент, для зручністі.
```

2022-12-09 10:19 UTC, AdriandeCita commented on files/uk/web/javascript/guide/indexed_collections/index.md
> +Такий підхід дає змогу уникнути накладних витрат з перевірки довжини масиву й пересвідчитися, що змінна `div` щоразу отримує поточний елемент, із покращеною зручністю.
Або розгорнутіший варіант. "Покращена зручність" - це щось дивне)
```suggestion
Такий підхід дає змогу уникнути накладних витрат з перевірки довжини масиву й пересвідчитися, що змінна `div` щоразу отримує поточний елемент, задля додаткової зручності.
```

2022-12-09 10:35 UTC, AdriandeCita commented on files/uk/web/javascript/guide/indexed_collections/index.md
> +- якщо `a` і `b` вважаються рівносильними, то повернути `0`.
рівносильний - хороше слово для порявння результатів якоїсь дії, чи логіки. У нас тут йде мова про порівняння значень, то чому б не вжити більш підходящий для цього термін?
```suggestion
- якщо `a` і `b` вважаються рівнозначними, то повернути `0`.
```

2022-12-09 10:46 UTC, AdriandeCita commented on files/uk/web/javascript/guide/indexed_collections/index.md
> +Метод [`lastIndexOf()`](/uk/docs/Web/JavaScript/Reference/Global_Objects/Array/lastIndexOf) працює як `indexOf`, але починає з кінця й шукаю задом наперед.
```suggestion
Метод [`lastIndexOf()`](/uk/docs/Web/JavaScript/Reference/Global_Objects/Array/lastIndexOf) працює як `indexOf`, але починає з кінця й шукає задом наперед.
```

2022-12-09 10:48 UTC, AdriandeCita commented on files/uk/web/javascript/guide/indexed_collections/index.md
> +> **Примітка:** Метод `sort()`, описаний вище, не є ітеративним методом, тому що його функція зворотного виклику використовується лише для порівняння і може не бути викликана у певному відомому на ос
```suggestion
> **Примітка:** Метод `sort()`, описаний вище, не є ітеративним методом, тому що його функція зворотного виклику використовується лише для порівняння і може не бути викликана у певному відомому на основі послідовності елементів порядку. Також `sort()` не приймає параметр `thisArg`.
```

2022-12-09 12:27 UTC, undead404 commented
Прийнято

2022-12-09 20:57 UTC, AdriandeCita commented on files/uk/web/javascript/guide/indexed_collections/index.md
> +Наприклад, коли масив є результатом пошуку збігу між регулярним виразом та рядком, масив повертає властивості та елементи, що містять інформацію про збіг. Масив є поверненим значенням [`RegExp.protot
Дивний зворот, пропоную трохи уточнити
```suggestion
Наприклад, коли масив є результатом пошуку збігу між регулярним виразом та рядком, масив повертає властивості та елементи, що містять інформацію про збіг. Масив є поверненим значенням методів [`RegExp.prototype.exec()`](/uk/docs/Web/JavaScript/Reference/Global_Objects/RegExp/exec), [`String.prototype.match()`](/uk/docs/Web/JavaScript/Reference/Global_Objects/String/match) і [`String.prototype.split()`](/uk/docs/Web/JavaScript/Reference/Global_Objects/String/split). Інформацію про використання масивів з регулярними виразами дивіться на сторінці [Регулярні вирази](/uk/docs/Web/JavaScript/Guide/Regular_Expressions).
```

2022-12-09 21:00 UTC, AdriandeCita commented on files/uk/web/javascript/guide/indexed_collections/index.md
> +Частина об'єктів JavaScript, як то [`NodeList`](/uk/docs/Web/API/NodeList), повернений [`document.getElementsByTagName()`](/uk/docs/Web/API/Document/getElementsByTagName), чи об'єкт {{jsxref("Functio
Тут складний перелік, який не одразу видно де закінчується, і з чого складається
```suggestion
Частина об'єктів JavaScript, як то [`NodeList`](/uk/docs/Web/API/NodeList), повернений методом [`document.getElementsByTagName()`](/uk/docs/Web/API/Document/getElementsByTagName), чи об'єкт {{jsxref("Functions/arguments","arguments")}}, доступний в межах тіла функції, — нібито мають вигляд та поведінку, подібну до масивів, але не поділяють всіх їхніх методів. Об'єкт `arguments` має атрибут {{jsxref("Global_Objects/Function/length","length")}}, але не реалізовує методів масиву, як то [`forEach()`](/uk/docs/Web/JavaScript/Reference/Global_Objects/Array/forEach).
```

2022-12-09 21:01 UTC, AdriandeCita requested changes
Ти встиг прийняти зауваження раніше, ніж я повернувся до ревю)
Ось іще декілька навздогін

2022-12-13 12:19 UTC, KlashReik commented on files/uk/web/javascript/guide/indexed_collections/index.md
> +JavaScript не має явного типу даних – масиву. Проте для роботи з масивами в застосунках можна використати наперед визначений об'єкт `Array` і його методи. Об'єкт `Array` має методи для роботи з масив
```suggestion
JavaScript не має явного типу даних – масиву. Проте для роботи з масивами в застосунках можна використати наперед визначений об'єкт `Array` і його методи. Об'єкт `Array` має методи для роботи з масивами за різними способами, як то їх об'єднання, розвороту й сортування. Він має властивість для з'ясування довжини масиву та інші властивості – для використання з регулярними виразами.
```

2022-12-13 12:23 UTC, KlashReik commented on files/uk/web/javascript/guide/indexed_collections/index.md
> +На додачі до нововизначеної змінної, як це показано вище, масив може бути присвоєний властивості нового або наявного об'єкта:
```suggestion
На додачу до нововизначеної змінної, як це показано вище, масив може бути присвоєний властивості нового або наявного об'єкта:
```

2022-12-13 14:32 UTC, KlashReik commented on files/uk/web/javascript/guide/indexed_collections/index.md
> +- якщо `a` більше за `b`, згідно з системою сортування, то повернути `1` (або будь-яке додатне число)
Те ж саме тут

2022-12-13 14:32 UTC, KlashReik commented on files/uk/web/javascript/guide/indexed_collections/index.md
> +- якщо `a` і `b` вважаються рівнозначними, то повернути `0`.
Те ж саме тут

2022-12-13 14:47 UTC, KlashReik commented
Декілька незначних зауважень.

2022-12-14 21:56 UTC, undead404 commented on files/uk/web/javascript/guide/indexed_collections/index.md
> +JavaScript не має явного типу даних – масиву. Проте для роботи з масивами в застосунках можна використати наперед визначений об'єкт `Array` і його методи. Об'єкт `Array` має методи для роботи з масив
Нормальний же зворот. https://www.google.com/search?q=%22%D1%83+%D1%80%D1%96%D0%B7%D0%BD%D0%B8%D0%B9+%D1%81%D0%BF%D0%BE%D1%81%D1%96%D0%B1%22&lr=(-lang_ru)

@AdriandeCita ?

2022-12-14 21:57 UTC, undead404 commented on files/uk/web/javascript/guide/indexed_collections/index.md
> +- якщо `a` більше за `b`, згідно з системою сортування, то повернути `1` (або будь-яке додатне число)
```suggestion
- якщо `a` більше за `b`, згідно з системою сортування, то повертається `1` (або будь-яке додатне число)
```

2022-12-14 21:57 UTC, undead404 commented on files/uk/web/javascript/guide/indexed_collections/index.md
> +- якщо `a` і `b` вважаються рівнозначними, то повернути `0`.
```suggestion
- якщо `a` і `b` вважаються рівнозначними, то повертається `0`.
```

2022-12-15 16:08 UTC, AdriandeCita commented on files/uk/web/javascript/guide/indexed_collections/index.md
> +slug: Web/JavaScript/Guide/Indexed_collections
```suggestion
slug: Web/JavaScript/Guide/Indexed_collections
page-type: guide
```

2022-12-15 16:09 UTC, AdriandeCita commented
Вніс зміни згідно цього https://github.com/mdn/content/commit/effd5de5e42bfe045c3bf44b2d7b14f4d6146785#diff-5c4a0934314207ea50445414f281b3c5af677c2003fb5080284b8bdd82c19191

2022-12-15 16:11 UTC, AdriandeCita commented on files/uk/web/javascript/guide/indexed_collections/index.md
> +JavaScript не має явного типу даних – масиву. Проте для роботи з масивами в застосунках можна використати наперед визначений об'єкт `Array` і його методи. Об'єкт `Array` має методи для роботи з масив
поки мержу, наступного разу можемо кращий варіант надумати

2022-12-15 16:11 UTC, AdriandeCita approved these changes

2022-12-15 16:11 UTC, merged