update(JS): web/javascript/reference/global_objects/array
webdoky/content pull request #940
Opened 2022-11-07 11:29 UTC by undead404

Оригінальний вміст: [Array (масив)@MDN](https://developer.mozilla.org/en-us/docs/Web/JavaScript/Reference/Global_Objects/Array), [сирці Array (масив)@GitHub](https://github.com/mdn/content/blob/main/files/en-us/web/javascript/reference/global_objects/array/index.md)

Нові зміни:
- [mdn/content@9e52d33](https://github.com/mdn/content/commit/9e52d335675a9f7daa34b5e24c9b1292dbf23b2e)

2022-11-07 21:11 UTC, AdriandeCita approved these changes

2022-11-07 21:11 UTC, AdriandeCita requested changes
Є свіжі зміни https://github.com/mdn/content/commit/c8b8f31280d83a525f6c58924254b86099eccee3#diff-24d0aab1f8d007cc2fac950232b782271f892761ed5a9c9a6e1f72a5d7ccbe90

2022-11-10 21:12 UTC, undead404 commented
Оновлено

2022-11-13 19:34 UTC, undead404 commented
Оновлено

2022-11-24 14:13 UTC, undead404 commented
Останні зміни – нерелевантні

2022-11-26 20:45 UTC, AdriandeCita commented on files/uk/web/javascript/reference/global_objects/array/index.md
> +- **[Операції копіювання масиву](#kopiiuvannia-masyvu) створюють [поверхневі копії](/uk/docs/Glossary/Shallow_copy)**. (Усі стандартні вбудовані операції копіювання _будь-яких_ об'єктів JavaScript ст
забагато "копій" на рядок)
```suggestion
- **[Операції копіювання масиву](#kopiiuvannia-masyvu) створюють [поверхневі копії](/uk/docs/Glossary/Shallow_copy)**. (Усі стандартні вбудовані операції копіювання _будь-яких_ об'єктів JavaScript створюють поверхневі, а не [глибинні копії](/uk/docs/Glossary/Deep_copy)).
```

2022-11-26 20:55 UTC, AdriandeCita commented on files/uk/web/javascript/reference/global_objects/array/index.md
> +`2` в записі `years[2]` зводиться до рядка рушієм JavaScript шляхом неявного перетворення `toString`. Як наслідок, `'2'` і `'02'` вказують на дві різні комірки в об'єкті `years`, і в наступному прикл
не зовсім зрозуміле формулювання. Оригінал каже, що "наступний приклад може бути дійсним", і разом з тим вказує на повернене значення `true`... Нам така розкіш недоступна, але пропоную переформулювати хоча б якось так
```suggestion
`2` в записі `years[2]` зводиться до рядка рушієм JavaScript шляхом неявного перетворення `toString`. Як наслідок, `'2'` і `'02'` вказують на дві різні комірки в об'єкті `years`, і результатом роботи наступного прикладу може бути `true`:
```

2022-11-26 21:00 UTC, AdriandeCita commented on files/uk/web/javascript/reference/global_objects/array/index.md
> +Increasing the {{jsxref("Array/length", "length")}}.
```suggestion
Збільшення властивості {{jsxref("Array/length", "length")}}.
```

2022-11-26 21:08 UTC, AdriandeCita commented on files/uk/web/javascript/reference/global_objects/array/index.md
> +Чимало методів масиву приймає як аргумент функцію зворотного виклику. Вона викликається послідовно й щонайбільше раз для кожного елемента масиву, і її повернене значення використовується для визначен
Думаю, тут краще сказати так. Однакових речей зазвичай декілька, а одна - вона одна, навіть якщо математично її можна вважати однаковою у порівнянні із собою
```suggestion
Чимало методів масиву приймає як аргумент функцію зворотного виклику. Вона викликається послідовно й щонайбільше раз для кожного елемента масиву, і її повернене значення використовується для визначення поверненого методом значення. Вони поділяють одну сигнатуру:
```

2022-11-26 21:19 UTC, AdriandeCita commented on files/uk/web/javascript/reference/global_objects/array/index.md
> +  - : Масив, на якому було викликано `groupToMap()`.
Думаю, хтось там трішки проїбався)
Ось [ПР](https://github.com/mdn/content/pull/22553), можна почекати поки вони його спершу змержать
```suggestion
  - : Масив, на якому було викликано `method()`.
```

2022-11-26 21:22 UTC, AdriandeCita commented on files/uk/web/javascript/reference/global_objects/array/index.md
> +Аргумент `thisArg` (чиє усталене значення – `undefined`) використовуватиметься як значення `this` при виклику `callbackFn`. Значення `this`, отримане `callbackFn`, визначається згідно зі [звичними пр
```suggestion
Аргумент `thisArg` (чиє усталене значення – `undefined`) використовуватиметься як значення `this` при виклику `callbackFn`. Значення `this`, отримане функцією `callbackFn`, визначається згідно зі [звичними правилами](/uk/docs/Web/JavaScript/Reference/Operators/this): якщо `callbackFn` є [несуворою](/uk/docs/Web/JavaScript/Reference/Strict_mode#bez-zaminy-this) функцією, то примітивні значення `this` загортаються в об'єкти, а `undefined` і `null` – замінюються на [`globalThis`](/uk/docs/Web/JavaScript/Reference/Global_Objects/globalThis). Аргумент `thisArg` є беззмістовним для будь-якої `callbackFn`, визначеною у вигляді [стрілкової функції](/uk/docs/Web/JavaScript/Reference/Functions/Arrow_functions), адже такі функції не мають власного зв'язування `this`.
```

2022-11-26 21:25 UTC, AdriandeCita commented on files/uk/web/javascript/reference/global_objects/array/index.md
> +Усі ітеративні методи є [копіювальними](#kopiiuvalni-ta-zminiuvalni-metody) та [узагальненими](#uzahalneni-metody-masyvu), хоч вони поводяться інакше з [порожніми комірками](#metody-masyvu-y-porozhni
```suggestion
Усі ітеративні методи є [копіювальними](#kopiiuvalni-ta-zminiuvalni-metody) та [узагальненими](#uzahalneni-metody-masyvu), хоч вони по-різному поводяться з [порожніми комірками](#metody-masyvu-y-porozhni-komirky).
```

2022-11-26 21:27 UTC, AdriandeCita commented on files/uk/web/javascript/reference/global_objects/array/index.md
> +А саме – {{jsxref("Array/every", "every()")}}, {{jsxref("Array/find", "find()")}}, {{jsxref("Array/findIndex", "findIndex()")}}, {{jsxref("Array/findLast", "findLast()")}}, {{jsxref("Array/findLastIn
Вони не переривають ітерацію, проте зупиняють ітерування всього масиву в цілому
```suggestion
А саме – {{jsxref("Array/every", "every()")}}, {{jsxref("Array/find", "find()")}}, {{jsxref("Array/findIndex", "findIndex()")}}, {{jsxref("Array/findLast", "findLast()")}}, {{jsxref("Array/findLastIndex", "findLastIndex()")}} і {{jsxref("Array/some", "some()")}} не завжди закликають `callbackFn` на кожному елементі: вони зупиняють ітерування, щойно повернене значення визначено.
```

2022-11-26 21:36 UTC, AdriandeCita commented on files/uk/web/javascript/reference/global_objects/array/index.md
> +Властивість `length` [перетворюється на ціле число](/uk/docs/Web/JavaScript/Reference/Global_Objects/Number#peretvorennia-na-tsile), обрізається до цілого, а потім примушується до діапазону між 0 і 2
```suggestion
Властивість `length` [перетворюється на ціле число](/uk/docs/Web/JavaScript/Reference/Global_Objects/Number#peretvorennia-na-tsile), а потім обрізається до діапазону між 0 і 2<sup>53</sup> - 1. `NaN` стає `0`, тож навіть тоді, коли `length` немає або в ній `undefined`, це працює так, ніби довжина дорівнює `0`.
```

2022-11-26 21:38 UTC, AdriandeCita requested changes
Є декілька пропозицій

2022-11-27 12:38 UTC, undead404 commented
Прийняв усі, усі сподобались

2022-11-28 10:37 UTC, undead404 commented
Прийняли Миколин PR в MDN :-)

2022-11-28 16:57 UTC, AdriandeCita approved these changes

2022-11-28 16:57 UTC, merged