update(JS): web/javascript/reference/global_objects/array/reduce
webdoky/content pull request #945
Opened 2022-11-07 11:51 UTC by undead404

Оригінальний вміст: [Array.prototype.reduce()@MDN](https://developer.mozilla.org/en-us/docs/Web/JavaScript/Reference/Global_Objects/Array/reduce), [сирці Array.prototype.reduce()@GitHub](https://github.com/mdn/content/blob/main/files/en-us/web/javascript/reference/global_objects/array/reduce/index.md)

Нові зміни:
- [mdn/content@9e52d33](https://github.com/mdn/content/commit/9e52d335675a9f7daa34b5e24c9b1292dbf23b2e)

2022-11-07 22:02 UTC, AdriandeCita approved these changes

2022-11-07 22:02 UTC, AdriandeCita requested changes
Є свіжі зміни https://github.com/mdn/content/commit/44f9dc3a1056277117c2d6174e1b2f7941672ead

2022-11-11 10:21 UTC, undead404 commented
Оновлено

2022-11-24 14:15 UTC, undead404 commented
Останні зміни – нерелевантні

2022-11-26 21:39 UTC, AdriandeCita approved these changes

2022-11-26 21:39 UTC, merged