update(JS): web/javascript/reference/global_objects/set
webdoky/content pull request #963
Opened 2022-11-07 20:30 UTC by undead404

Оригінальний вміст: [Set@MDN](https://developer.mozilla.org/en-us/docs/Web/JavaScript/Reference/Global_Objects/Set), [сирці Set@GitHub](https://github.com/mdn/content/blob/main/files/en-us/web/javascript/reference/global_objects/set/index.md)

Нові зміни:
- [mdn/content@9e52d33](https://github.com/mdn/content/commit/9e52d335675a9f7daa34b5e24c9b1292dbf23b2e)

2022-11-07 22:28 UTC, AdriandeCita commented on files/uk/web/javascript/reference/global_objects/set/index.md
> +mySet1.add(5); // Set(5) { 1, 'якийсь текст', {...}, {...}, 5 } - попередньо видалений елемент буде доданий як новий елемент, він не збереже позиції, що мав до видалення
"Попередньо ..." зазвичай вживається в значенні "заздалегідь ..."
```suggestion
mySet1.add(5); // Set(5) { 1, 'якийсь текст', {...}, {...}, 5 } - видалений раніше елемент буде доданий заново; він не збереже позиції, що мав до видалення
```

2022-11-07 22:30 UTC, AdriandeCita requested changes
невеличке зауваження

2022-11-26 12:34 UTC, undead404 commented
Прийнято пропозицію, оновлено

2022-11-26 21:41 UTC, AdriandeCita approved these changes

2022-11-26 21:41 UTC, merged