update(JS): web/javascript/guide/working_with_objects
webdoky/content pull request #978
Opened 2022-11-08 09:17 UTC by undead404

Оригінальний вміст: [Робота з об'єктами@MDN](https://developer.mozilla.org/en-us/docs/Web/JavaScript/Guide/Working_with_Objects), [сирці Робота з об'єктами@GitHub](https://github.com/mdn/content/blob/main/files/en-us/web/javascript/guide/working_with_objects/index.md)

Нові зміни:
- [mdn/content@8e308c0](https://github.com/mdn/content/commit/8e308c03f6df5a8cd14843a609f8d1529bb444cf)
- [mdn/content@9e52d33](https://github.com/mdn/content/commit/9e52d335675a9f7daa34b5e24c9b1292dbf23b2e)
- [mdn/content@b7cd76a](https://github.com/mdn/content/commit/b7cd76af245c330c6a1a9f489602015fa0714044)

2022-11-27 08:13 UTC, AdriandeCita commented on files/uk/web/javascript/guide/working_with_objects/index.md
> +### Застосування ініціалізаторів об'єкта
Є об'єктивні причини, чому це краще за попередній варіант?

Формлуювання "ініціалізатори об'єкта" натякає на те, що ініціалізаторів у об'єкта може бути декілька, чого б я краще уникав
```suggestion
### Застосування об'єктних ініціалізаторів
```

2022-11-27 08:14 UTC, AdriandeCita commented on files/uk/web/javascript/guide/working_with_objects/index.md
> +Ініціалізатори об'єктів – це вирази, і кожний такий ініціалізатор призводить до створення нового об'єкта щоразу, коли виконується інструкція, в якій він зустрічається. Ідентичні ініціалізатори об'єкт
хммм, є причини вважати, що `Ініціалізатор об'єкта` !== `об'єктний ініціалізатор`?

2022-11-27 08:36 UTC, AdriandeCita commented on files/uk/web/javascript/guide/working_with_objects/index.md
> +Подібно до змінних JavaScript, імена властивостей - чутливі до регістру. Вони можуть бути лише рядками чи Symbol: усі ключі [перетворюються на рядки](/uk/docs/Web/JavaScript/Reference/Global_Objects/
Це звучить неузгоджено. Я б з радістю перекладав назву типу (тільки писав би його так само з великої літери), але цю дискусію пропоную винести кудись
```suggestion
Подібно до змінних JavaScript, імена властивостей - чутливі до регістру. Вони можуть бути лише рядками чи примірниками Symbol: усі ключі [перетворюються на рядки](/uk/docs/Web/JavaScript/Reference/Global_Objects/String#zvedennia-do-riadka), окрім Symbol. [Індекси масивів](/uk/docs/Web/JavaScript/Reference/Global_Objects/Array#notes) фактично є властивостями з рядковими ключами, що містять цілі числа.
```

2022-11-27 08:57 UTC, AdriandeCita commented on files/uk/web/javascript/guide/working_with_objects/index.md
> +Докладніше про це – в [Перелічуваності та власництві властивостей](/uk/docs/Web/JavaScript/Enumerability_and_ownership_of_properties).
Тут вказується назва статті, я не певен, що такі речі варто відмінювати. Або якщо відмінювати - то писати з малої літери, щоб це не сприймалося як назва
```suggestion
Докладніше про це – у статті [Перелічуваність та власність властивостей](/uk/docs/Web/JavaScript/Enumerability_and_ownership_of_properties).
```

2022-11-27 09:00 UTC, AdriandeCita commented on files/uk/web/javascript/guide/working_with_objects/index.md
> +Додати властивість до всіх об'єктів, створених за допомогою одного [конструктора](#zastosuvannia-funktsii-konstruktora), можна за допомогою властивості [`prototype`](/uk/docs/Web/JavaScript/Reference
Тут колізія, "означає" в сенсі "значити, позначати", і "означає" в сенсі "означити". Пропоную трохи додати слів для конкретизації
```suggestion
Додати властивість до всіх об'єктів, створених за допомогою одного [конструктора](#zastosuvannia-funktsii-konstruktora), можна за допомогою властивості [`prototype`](/uk/docs/Web/JavaScript/Reference/Global_Objects/Function/prototype). Такий підхід дає можливість означити властивість, котру поділяють всі об'єкти конкретного типу, а не лише один примірник об'єкта. Наступний код додає властивість `color` до всіх об'єктів типу `Car`, а потім зчитує значення властивості з примірника `car1`.
```

2022-11-27 17:41 UTC, AdriandeCita commented on files/uk/web/javascript/guide/working_with_objects/index.md
> +Методи здебільшого означають на об'єкті зі властивості конструктора `prototype`, аби усі об'єкти такого типу поділяли один метод. Наприклад, можна означити функцію, котра оформлює та виводить властив
```suggestion
Означення методів здебільшого виконують на об'єкті зі властивості конструктора `prototype`, аби усі об'єкти такого типу поділяли один метод. Наприклад, можна означити функцію, котра оформлює та виводить властивості раніше означених об'єктів `Car`.
```

2022-11-27 17:49 UTC, AdriandeCita requested changes
Декілька пропозицій

2022-11-27 21:41 UTC, undead404 commented on files/uk/web/javascript/guide/working_with_objects/index.md
> +Свої об'єкти можна створити, застосувавши [ініціалізатор об'єкта](/uk/docs/Web/JavaScript/Reference/Operators/Object_initializer). Окрім цього, можна також спершу створити функцію-конструктор, і поті
```suggestion
Свої об'єкти можна створити, застосувавши [об'єктний ініціалізатор](/uk/docs/Web/JavaScript/Reference/Operators/Object_initializer). Окрім цього, можна також спершу створити функцію-конструктор, і потім реалізувати новий об'єкт шляхом звертання до функції з оператором `new`.
```

2022-11-27 21:41 UTC, undead404 commented on files/uk/web/javascript/guide/working_with_objects/index.md
> +Ініціалізатори об'єктів також звуть _літералами об'єктів_. Термін "об'єктний ініціалізатор" сумісний з термінологією, прийнятою в середовищі C++.
```suggestion
Об'єктні ініціалізатори також звуть _літералами об'єктів_. Термін "об'єктний ініціалізатор" сумісний з термінологією, прийнятою в середовищі C++.
```

2022-11-27 21:42 UTC, undead404 commented on files/uk/web/javascript/guide/working_with_objects/index.md
> +Кожна назва властивості до двокрапки — ідентифікатор (або ім'я, або число, або рядковий літерал), та кожний `valueN` — вираз, чиє значення присвоюється назві властивості. Ім'я властивості також може
```suggestion
Кожна назва властивості до двокрапки — ідентифікатор (або ім'я, або число, або рядковий літерал), та кожний `valueN` — вираз, чиє значення присвоюється назві властивості. Ім'я властивості також може бути виразом; обчислювані ключі повинні бути огорнуті квадратними дужками. Довідкова сторінка [об'єктних ініціалізаторів](/uk/docs/Web/JavaScript/Reference/Operators/Object_initializer) містить детальніше пояснення синтаксису.
```

2022-11-27 21:42 UTC, undead404 commented on files/uk/web/javascript/guide/working_with_objects/index.md
> +Ініціалізатори об'єктів – це вирази, і кожний такий ініціалізатор призводить до створення нового об'єкта щоразу, коли виконується інструкція, в якій він зустрічається. Ідентичні ініціалізатори об'єкт
```suggestion
Об'єктні ініціалізатори – це вирази, і кожний такий ініціалізатор призводить до створення нового об'єкта щоразу, коли виконується інструкція, в якій він зустрічається. Ідентичні об'єктні ініціалізатори створюють окремі об'єкти, котрі при порівнянні не вважатимуться рівними одне одному.
```

2022-11-27 21:45 UTC, undead404 commented on files/uk/web/javascript/guide/working_with_objects/index.md
> +В [ініціалізаторах об'єктів](#zastosuvannia-initsializatoriv-obiekta) гетери й сетери означаються подібно до звичайних [методів](/uk/docs/Web/JavaScript/Reference/Functions/Method_definitions), але м
```suggestion
В [об'єктних ініціалізаторах](#zastosuvannia-obiektnykh-initsializatoriv) гетери й сетери означаються подібно до звичайних [методів](/uk/docs/Web/JavaScript/Reference/Functions/Method_definitions), але мають на початку означень ключові слова `get` або `set`. Метод-гетер не повинен очікувати на параметр, натомість метод-сетер очікує рівно на один параметр (нове значення, котре присвоюється). Наприклад:
```

2022-11-27 21:46 UTC, undead404 commented on files/uk/web/javascript/guide/working_with_objects/index.md
> +Подібно до змінних JavaScript, імена властивостей - чутливі до регістру. Вони можуть бути лише рядками чи Symbol: усі ключі [перетворюються на рядки](/uk/docs/Web/JavaScript/Reference/Global_Objects/
```suggestion
Подібно до змінних JavaScript, імена властивостей - чутливі до регістру. Вони можуть бути лише рядками чи примірниками Symbol: усі ключі [перетворюються на рядки](/uk/docs/Web/JavaScript/Reference/Global_Objects/String#zvedennia-do-riadka), окрім Symbol. [Індекси масивів](/uk/docs/Web/JavaScript/Reference/Global_Objects/Array#indeksy-masyviv) фактично є властивостями з рядковими ключами, що містять цілі числа.
```

2022-11-27 21:48 UTC, undead404 commented
Оновлено, прийнято пропозиції

2022-11-28 21:34 UTC, AdriandeCita approved these changes

2022-11-28 21:35 UTC, merged