update(JS): web/javascript/reference/global_objects/array/map
webdoky/content pull request #982
Opened 2022-11-10 21:48 UTC by undead404

Оригінальний вміст: [Array.prototype.map()@MDN](https://developer.mozilla.org/en-us/docs/Web/JavaScript/Reference/Global_Objects/Array/map), [сирці Array.prototype.map()@GitHub](https://github.com/mdn/content/blob/main/files/en-us/web/javascript/reference/global_objects/array/map/index.md)

Нові зміни:
- [mdn/content@cca000c](https://github.com/mdn/content/commit/cca000c28ef661e58a5beaff9c64f7a397a5f68a)

2022-11-10 23:40 UTC, AdriandeCita commented on files/uk/web/javascript/reference/global_objects/array/map/index.md
> +  - : Функція для виклику для кожного елемента масиву. Її повернене значення додається у новий масив як один з елементів.
для-для. Давай може якось так...
```suggestion
  - : Функція для виклику на кожному елементі масиву. Її повернене значення додається окремим елементом у новий масив.
```

2022-11-10 23:47 UTC, AdriandeCita commented on files/uk/web/javascript/reference/global_objects/array/map/index.md
> +Метод `map()` є [копіювальним методом](/uk/docs/Web/JavaScript/Reference/Global_Objects/Array#kopiiuvalni-ta-zminiuvalni-metody). Він не вносить змін до `this`. Проте функція, передана як `callbackFn
Думав, чому довжина перестає зберігатися після першого заклику, потім глянув в оригінал :grin: 

Пропоную трохи замінити синонімами, там також іще "проте-проте" в суміжних реченнях
```suggestion
Метод `map()` є [копіювальним методом](/uk/docs/Web/JavaScript/Reference/Global_Objects/Array#kopiiuvalni-ta-zminiuvalni-metody). Він не вносить змін до `this`. Проте функція, передана як `callbackFn`, може змінювати масив. Хоча зверніть увагу, що довжина масиву запам'ятовується _до_ моменту першого заклику `callbackFn`. Таким чином:
```

2022-11-10 23:49 UTC, AdriandeCita commented on files/uk/web/javascript/reference/global_objects/array/map/index.md
> +- Якщо наявний, іще не оброблений елемент масиву змінюється `callbackFn`, то його значення, передане в `callbackFn`, буде значенням на ту мить, коли такий елемент обробляється. [Видалені](/uk/docs/We
Певен, тут малася на увазі зміна елемента під час попередньої ітерації
```suggestion
- Якщо наявний, іще не оброблений елемент масиву вже був змінений `callbackFn`, то його значення, передане в `callbackFn`, буде значенням на ту мить, коли такий елемент обробляється. [Видалені](/uk/docs/Web/JavaScript/Reference/Operators/delete) елементи – не обробляються.
```

2022-11-10 23:51 UTC, AdriandeCita requested changes
Декілька зауважень

2022-11-24 14:14 UTC, undead404 commented
Останні зміни – нерелевантні.

2022-11-26 21:40 UTC, AdriandeCita approved these changes

2022-11-26 21:40 UTC, merged