update(JS): web/javascript/reference/global_objects/array/find
webdoky/content pull request #984
Opened 2022-11-11 09:06 UTC by undead404

Оригінальний вміст: [Array.prototype.find()@MDN](https://developer.mozilla.org/en-us/docs/Web/JavaScript/Reference/Global_Objects/Array/find), [сирці Array.prototype.find()@GitHub](https://github.com/mdn/content/blob/main/files/en-us/web/javascript/reference/global_objects/array/find/index.md)

Нові зміни:
- [mdn/content@cca000c](https://github.com/mdn/content/commit/cca000c28ef661e58a5beaff9c64f7a397a5f68a)

2022-11-24 14:14 UTC, undead404 commented
Останні зміни – нерелевантні

2022-11-27 17:51 UTC, AdriandeCita commented on files/uk/web/javascript/reference/global_objects/array/find/index.md
> +- `callbackFn` не оброблятиме жодних елементів, доданих поза початковою довжиною масиву, відколи почався виклик `filter()`.
```suggestion
- `callbackFn` не оброблятиме жодних елементів, доданих поза початковою довжиною масиву, відколи почався виклик `find()`.
```

2022-11-27 17:53 UTC, AdriandeCita requested changes
Невеличке зауваження

2022-11-28 10:46 UTC, undead404 commented
Прийнято

2022-11-28 21:35 UTC, AdriandeCita approved these changes

2022-11-28 21:35 UTC, merged