update(JS): web/javascript/reference/global_objects/array/foreach
webdoky/content pull request #985
Opened 2022-11-11 11:09 UTC by undead404

Оригінальний вміст: [Array.prototype.forEach()@MDN](https://developer.mozilla.org/en-us/docs/Web/JavaScript/Reference/Global_Objects/Array/forEach), [сирці Array.prototype.forEach()@GitHub](https://github.com/mdn/content/blob/main/files/en-us/web/javascript/reference/global_objects/array/foreach/index.md)

Нові зміни:
- [mdn/content@cca000c](https://github.com/mdn/content/commit/cca000c28ef661e58a5beaff9c64f7a397a5f68a)

2022-11-24 14:21 UTC, undead404 commented
Останні зміни – нерелевантні.

2022-11-27 17:54 UTC, AdriandeCita commented on files/uk/web/javascript/reference/global_objects/array/foreach/index.md
> +  - : A value to use as `this` when executing `callbackFn`. See [iterative methods](/uk/docs/Web/JavaScript/Reference/Global_Objects/Array#iterative_methods).
```suggestion
```

2022-11-27 17:55 UTC, AdriandeCita commented on files/uk/web/javascript/reference/global_objects/array/foreach/index.md
> +- `callbackFn` не оброблятиме жодних елементів, доданих поза початковою довжиною масиву, відколи почався виклик `filter()`.
```suggestion
- `callbackFn` не оброблятиме жодних елементів, доданих поза початковою довжиною масиву, відколи почався виклик `forEach()`.
```

2022-11-27 18:08 UTC, AdriandeCita commented on files/uk/web/javascript/reference/global_objects/array/foreach/index.md
> +- `callbackFn` не оброблятиме жодних елементів, доданих поза початковою довжиною масиву, відколи почався виклик `filter()`.
В оригіналі теж помилка :sweat_smile: 
https://github.com/mdn/content/pull/22563

2022-11-27 18:11 UTC, AdriandeCita requested changes
Невеличке зауваження

2022-11-28 10:48 UTC, undead404 commented
Пропозиції прийнято

2022-11-28 21:36 UTC, AdriandeCita approved these changes

2022-11-28 21:36 UTC, merged