update(HTML): web/html/element/input
webdoky/content pull request #993
Opened 2022-11-23 20:40 UTC by undead404

Оригінальний вміст: [&lt;input>: Елемент введення (форм)@MDN](https://developer.mozilla.org/en-us/docs/Web/HTML/Element/input), [сирці &lt;input>: Елемент введення (форм)@GitHub](https://github.com/mdn/content/blob/main/files/en-us/web/html/element/input/index.md)

Нові зміни:
- [mdn/content@0a50e68](https://github.com/mdn/content/commit/0a50e68c2b1f86fd73d68cb7f7a550e418dfb395)

2022-11-23 22:51 UTC, AdriandeCita approved these changes

2022-11-23 22:52 UTC, AdriandeCita requested changes
Є свіжі зміни https://github.com/mdn/content/commit/7d4c4fbfb2faaef1450b22816a920af6d0e1d785

2022-11-24 14:19 UTC, undead404 commented
Оновлено: https://github.com/mdn/content/commit/7d4c4fbfb2faaef1450b22816a920af6d0e1d785#diff-65357dcc81d104cabb85b8fb26e8406be0fb64e5088b18e63a6ea6d77f3aa7c5

2022-11-24 22:44 UTC, AdriandeCita approved these changes

2022-11-24 22:44 UTC, merged