update(JS): web/javascript/reference/functions/arrow_functions
webdoky/content pull request #997
Opened 2022-11-24 13:16 UTC by undead404

Оригінальний вміст: [Вирази стрілкових функцій@MDN](https://developer.mozilla.org/en-us/docs/Web/JavaScript/Reference/Functions/Arrow_functions), [сирці Вирази стрілкових функцій@GitHub](https://github.com/mdn/content/blob/main/files/en-us/web/javascript/reference/functions/arrow_functions/index.md)

Нові зміни:
- [mdn/content@9a8197a](https://github.com/mdn/content/commit/9a8197aa421feea16a4e115606701235b3cfdb4e)

2022-11-27 18:27 UTC, AdriandeCita commented on files/uk/web/javascript/reference/functions/arrow_functions/index.md
> +У прикладі вище і дужки навколо параметра, і фігурні дужки навколо тіла функції – можуть бути опущені. Проте – не лише за певних умов.
```suggestion
У прикладі вище і дужки навколо параметра, і фігурні дужки навколо тіла функції – можуть бути опущені. Проте – лише за певних умов.
```

2022-11-27 18:37 UTC, AdriandeCita commented on files/uk/web/javascript/reference/functions/arrow_functions/index.md
>  Для прикладу, якщо є **декілька аргументів** чи **аргументів немає** взагалі, то дужки навколо аргументів доведеться повернути на місце:
Ймовірно пропущений переклад, в оригіналі там трохи більше тексту
```suggestion
Дужки можна опустити лише в тому випадку, якщо функція має єдиний простий параметр. Якщо передано декілька аргументів, жодного, або використано усталене, деструктуроване значення, чи решту параметрів – то дужки навколо списку параметрів обов'язкові.
```

2022-11-27 18:43 UTC, AdriandeCita commented on files/uk/web/javascript/reference/functions/arrow_functions/index.md
> +У стислому тілі задається лише один вираз, котрий стає неявним поверненим значенням. У блоковому тілі слід використовувати явну інструкцію `return`.
В оригіналі `implicit return value`, що радше є "значенням неявного повернення", навряд чи повернене значення можна назвати "неявним".
```suggestion
У стислому тілі задається лише один вираз, котрий стає неявно поверненим значенням. У блоковому тілі слід використовувати явну інструкцію `return`.
```

2022-11-27 18:45 UTC, AdriandeCita commented on files/uk/web/javascript/reference/functions/arrow_functions/index.md
> +Так відбувається через те, що JavaScript впізнає стрілкову функцію як таку, що має стисле тіло, лише якщо знак після стрілки не є лівою фігурною дужкою, тож код всередині фігурних дужок обробляється
```suggestion
Так відбувається через те, що JavaScript впізнає стрілкову функцію як таку, що має стисле тіло, лише якщо знак після стрілки не є лівою фігурною дужкою, тож код всередині фігурних дужок обробляється як послідовність інструкцій, у якій `foo` є [міткою](/uk/docs/Web/JavaScript/Reference/Statements/label), а не ключем літерала об'єкта.
```

2022-11-27 18:59 UTC, AdriandeCita commented on files/uk/web/javascript/reference/functions/arrow_functions/index.md
> +Arrow function expressions should only be used for non-method functions because they do not have their own `this`. Let's see what happens when we try to use them as methods:
```suggestion
Вирази стрілкових функцій слід застосовувати лише для тих функцій, які не є методами, оскільки вони не мають свого власного `this`. Погляньмо, що трапиться, якщо спробувати використати їх як методи:
```

2022-11-27 19:03 UTC, AdriandeCita requested changes
Пара зауважень

2022-11-28 11:03 UTC, undead404 commented
Прийнято

2022-11-28 21:37 UTC, AdriandeCita approved these changes

2022-11-28 21:37 UTC, merged